import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-11-food",
  name: "Food",
  level: "A1",
  theme: "Food & Eating",
  emoji: "🍎",
  prerequisiteUnits: ["a1-unit-10-body"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary
    // -------------------------------------------------------------------------
    {
      id: "a111-t1-001",
      type: "produce",
      prompt: "the bread",
      accepted: ["il pane"],
      prompts: { "es": "el pan" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "food", "staple", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-002",
      type: "produce",
      prompt: "the cheese",
      accepted: ["il formaggio"],
      prompts: { "es": "el queso" },
      hint: "masculine noun — double g",
      tags: ["noun", "masculine", "food", "dairy", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-003",
      type: "produce",
      prompt: "the meat",
      accepted: ["la carne"],
      prompts: { "es": "la carne" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "food", "protein", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-004",
      type: "produce",
      prompt: "the chicken",
      accepted: ["il pollo"],
      prompts: { "es": "el pollo" },
      hint: "masculine noun — double l",
      tags: ["noun", "masculine", "food", "protein", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-005",
      type: "produce",
      prompt: "the fish",
      accepted: ["il pesce"],
      prompts: { "es": "el pescado" },
      hint: "masculine noun — note the -sce ending",
      tags: ["noun", "masculine", "food", "protein", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-006",
      type: "produce",
      prompt: "the eggs",
      accepted: ["le uova"],
      prompts: { "es": "los huevos" },
      hint: "feminine plural — irregular plural of l'uovo (n.)",
      tags: ["noun", "feminine", "food", "protein", "plural", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-007",
      type: "produce",
      prompt: "the pasta",
      accepted: ["la pasta"],
      prompts: { "es": "la pasta" },
      hint: "feminine noun — same word in English!",
      tags: ["noun", "feminine", "food", "staple", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-008",
      type: "produce",
      prompt: "the rice",
      accepted: ["il riso"],
      prompts: { "es": "el arroz" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "food", "staple", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-009",
      type: "produce",
      prompt: "the potatoes",
      accepted: ["le patate"],
      prompts: { "es": "las patatas" },
      hint: "feminine plural noun",
      tags: ["noun", "feminine", "food", "vegetable", "plural", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-010",
      type: "produce",
      prompt: "the tomatoes",
      accepted: ["i pomodori"],
      prompts: { "es": "los tomates" },
      hint: "masculine plural — pomodoro → pomodori",
      tags: ["noun", "masculine", "food", "vegetable", "plural", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-011",
      type: "produce",
      prompt: "the salad",
      accepted: ["l'insalata"],
      prompts: { "es": "la ensalada" },
      hint: "feminine — l' before vowel",
      tags: ["noun", "feminine", "food", "vegetable", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-012",
      type: "produce",
      prompt: "the onion",
      accepted: ["la cipolla"],
      prompts: { "es": "la cebolla" },
      hint: "feminine noun — double l",
      tags: ["noun", "feminine", "food", "vegetable", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-013",
      type: "produce",
      prompt: "the garlic",
      accepted: ["l'aglio"],
      prompts: { "es": "el ajo" },
      hint: "masculine — l' before vowel; gli = soft sound",
      tags: ["noun", "masculine", "food", "vegetable", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-014",
      type: "produce",
      prompt: "the olive oil",
      accepted: ["l'olio d'oliva"],
      prompts: { "es": "el aceite de oliva" },
      hint: "l' before vowel; d' = elided di",
      tags: ["noun", "masculine", "food", "condiment", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-015",
      type: "produce",
      prompt: "the salt",
      accepted: ["il sale"],
      prompts: { "es": "la sal" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "food", "condiment", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-016",
      type: "produce",
      prompt: "the pepper",
      accepted: ["il pepe"],
      prompts: { "es": "la pimienta" },
      hint: "masculine noun — not to be confused with peperone (bell pepper)",
      tags: ["noun", "masculine", "food", "condiment", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-017",
      type: "produce",
      prompt: "the sugar",
      accepted: ["lo zucchero"],
      prompts: { "es": "el azúcar" },
      hint: "masculine — lo before z; double ch",
      tags: ["noun", "masculine", "food", "condiment", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-018",
      type: "produce",
      prompt: "the butter",
      accepted: ["il burro"],
      prompts: { "es": "la mantequilla" },
      hint: "masculine noun — double r",
      tags: ["noun", "masculine", "food", "dairy", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-019",
      type: "produce",
      prompt: "the milk",
      accepted: ["il latte"],
      prompts: { "es": "la leche" },
      hint: "masculine noun — double t",
      tags: ["noun", "masculine", "food", "dairy", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-020",
      type: "produce",
      prompt: "the fruit",
      accepted: ["la frutta"],
      prompts: { "es": "la fruta" },
      hint: "feminine noun — collective, usually singular",
      tags: ["noun", "feminine", "food", "fruit", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-021",
      type: "produce",
      prompt: "the vegetables",
      accepted: ["la verdura"],
      prompts: { "es": "las verduras" },
      hint: "feminine noun — collective, usually singular",
      tags: ["noun", "feminine", "food", "vegetable", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-022",
      type: "produce",
      prompt: "the apple",
      accepted: ["la mela"],
      prompts: { "es": "la manzana" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "food", "fruit", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-023",
      type: "produce",
      prompt: "the banana",
      accepted: ["la banana"],
      prompts: { "es": "el plátano" },
      hint: "feminine noun — same word!",
      tags: ["noun", "feminine", "food", "fruit", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-024",
      type: "produce",
      prompt: "the orange",
      accepted: ["l'arancia"],
      prompts: { "es": "la naranja" },
      hint: "feminine — l' before vowel",
      tags: ["noun", "feminine", "food", "fruit", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-025",
      type: "produce",
      prompt: "the ice cream",
      accepted: ["il gelato"],
      prompts: { "es": "el helado" },
      hint: "masculine noun — same root as 'gelato' in English!",
      tags: ["noun", "masculine", "food", "dessert", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-026",
      type: "produce",
      prompt: "the cake",
      accepted: ["la torta"],
      prompts: { "es": "el pastel" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "food", "dessert", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-027",
      type: "produce",
      prompt: "the biscuit / cookie",
      accepted: ["il biscotto"],
      prompts: { "es": "la galleta" },
      hint: "masculine noun — double t",
      tags: ["noun", "masculine", "food", "dessert", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-028",
      type: "produce",
      prompt: "the chocolate",
      accepted: ["il cioccolato"],
      prompts: { "es": "el chocolate" },
      hint: "masculine noun — double c",
      tags: ["noun", "masculine", "food", "dessert", "tier1"],
      tier: 1,
    },

    // --- Recognize cards (Italian → English) ---

    {
      id: "a111-t1-100",
      type: "recognize",
      prompt: "il pane",
      accepted: ["bread", "the bread"],
      translations: { "es": ["pan", "el pan"] },
      hint: "think 'pain' in French — same root, both mean bread",
      tags: ["noun", "masculine", "food", "staple", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-101",
      type: "recognize",
      prompt: "il formaggio",
      accepted: ["cheese", "the cheese"],
      translations: { "es": ["queso", "el queso"] },
      hint: "think 'fromage' in French — cognate",
      tags: ["noun", "masculine", "food", "dairy", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-102",
      type: "recognize",
      prompt: "la carne",
      accepted: ["meat", "the meat"],
      translations: { "es": ["carne", "la carne"] },
      hint: "'carnal' shares this root — relating to flesh",
      tags: ["noun", "feminine", "food", "protein", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-103",
      type: "recognize",
      prompt: "il pollo",
      accepted: ["chicken", "the chicken"],
      translations: { "es": ["pollo", "el pollo"] },
      hint: "think 'poultry' — same Latin root",
      tags: ["noun", "masculine", "food", "protein", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-104",
      type: "recognize",
      prompt: "il pesce",
      accepted: ["fish", "the fish"],
      translations: { "es": ["pescado", "el pescado"] },
      hint: "think 'pescatarian'",
      tags: ["noun", "masculine", "food", "protein", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-105",
      type: "recognize",
      prompt: "le uova",
      accepted: ["eggs", "the eggs"],
      translations: { "es": ["huevos", "los huevos"] },
      hint: "uovo → uova (irregular plural); think 'oval'",
      tags: ["noun", "feminine", "food", "protein", "plural", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-106",
      type: "recognize",
      prompt: "la pasta",
      accepted: ["pasta", "the pasta"],
      translations: { "es": ["pasta", "la pasta"] },
      hint: "identical to English",
      tags: ["noun", "feminine", "food", "staple", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-107",
      type: "recognize",
      prompt: "il riso",
      accepted: ["rice", "the rice"],
      translations: { "es": ["arroz", "el arroz"] },
      hint: "also means 'laughter' — same spelling, different meaning",
      tags: ["noun", "masculine", "food", "staple", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-108",
      type: "recognize",
      prompt: "le patate",
      accepted: ["potatoes", "the potatoes"],
      translations: { "es": ["patatas", "las patatas"] },
      hint: "near-cognate with English 'potato'",
      tags: ["noun", "feminine", "food", "vegetable", "plural", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-109",
      type: "recognize",
      prompt: "i pomodori",
      accepted: ["tomatoes", "the tomatoes"],
      translations: { "es": ["tomates", "los tomates"] },
      hint: "pomo d'oro = golden apple — old Italian name for tomato",
      tags: ["noun", "masculine", "food", "vegetable", "plural", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-110",
      type: "recognize",
      prompt: "l'insalata",
      accepted: ["salad", "the salad"],
      translations: { "es": ["ensalada", "la ensalada"] },
      hint: "near-cognate with English 'salad'",
      tags: ["noun", "feminine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-111",
      type: "recognize",
      prompt: "la cipolla",
      accepted: ["onion", "the onion"],
      translations: { "es": ["cebolla", "la cebolla"] },
      hint: "think 'cipollini' — small Italian pickled onions",
      tags: ["noun", "feminine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-112",
      type: "recognize",
      prompt: "l'aglio",
      accepted: ["garlic", "the garlic"],
      translations: { "es": ["ajo", "el ajo"] },
      hint: "think 'aglio olio' — the classic pasta dish",
      tags: ["noun", "masculine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-113",
      type: "recognize",
      prompt: "l'olio d'oliva",
      accepted: ["olive oil", "the olive oil"],
      translations: { "es": ["aceite de oliva", "el aceite de oliva"] },
      hint: "olio = oil; d'oliva = of the olive",
      tags: ["noun", "masculine", "food", "condiment", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-114",
      type: "recognize",
      prompt: "il sale",
      accepted: ["salt", "the salt"],
      translations: { "es": ["sal", "la sal"] },
      hint: "think 'salary' — Romans were paid in salt",
      tags: ["noun", "masculine", "food", "condiment", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-115",
      type: "recognize",
      prompt: "il pepe",
      accepted: ["pepper", "black pepper", "the pepper"],
      translations: { "es": ["pimienta", "pimienta negra", "la pimienta"] },
      hint: "near-cognate; ground black pepper, not the vegetable",
      tags: ["noun", "masculine", "food", "condiment", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-116",
      type: "recognize",
      prompt: "lo zucchero",
      accepted: ["sugar", "the sugar"],
      translations: { "es": ["azúcar", "el azúcar"] },
      hint: "same Arabic root 'sukkar' as English 'sugar'",
      tags: ["noun", "masculine", "food", "condiment", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-117",
      type: "recognize",
      prompt: "il burro",
      accepted: ["butter", "the butter"],
      translations: { "es": ["mantequilla", "la mantequilla"] },
      hint: "think 'butyric acid' — the compound that gives butter its smell",
      tags: ["noun", "masculine", "food", "dairy", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-118",
      type: "recognize",
      prompt: "il latte",
      accepted: ["milk", "the milk"],
      translations: { "es": ["leche", "la leche"] },
      hint: "think 'latte' — coffee with milk",
      tags: ["noun", "masculine", "food", "dairy", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-119",
      type: "recognize",
      prompt: "la frutta",
      accepted: ["fruit", "the fruit"],
      translations: { "es": ["fruta", "la fruta"] },
      hint: "near-cognate; collective noun, usually singular",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-120",
      type: "recognize",
      prompt: "la verdura",
      accepted: ["vegetables", "the vegetables", "greens", "the greens"],
      translations: { "es": ["verduras", "las verduras"] },
      hint: "'verde' = green — verdura is greens and vegetables",
      tags: ["noun", "feminine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-121",
      type: "recognize",
      prompt: "la mela",
      accepted: ["apple", "the apple"],
      translations: { "es": ["manzana", "la manzana"] },
      hint: "malic acid (the sour taste in apples) shares this Latin root",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-122",
      type: "recognize",
      prompt: "la banana",
      accepted: ["banana", "the banana"],
      translations: { "es": ["plátano", "el plátano"] },
      hint: "identical to English",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-123",
      type: "recognize",
      prompt: "l'arancia",
      accepted: ["orange", "the orange"],
      translations: { "es": ["naranja", "la naranja"] },
      hint: "same Arabic root 'naranj' as English 'orange'",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-124",
      type: "recognize",
      prompt: "il gelato",
      accepted: ["ice cream", "gelato", "the ice cream"],
      translations: { "es": ["helado", "helado", "el helado"] },
      hint: "same word used in English",
      tags: ["noun", "masculine", "food", "dessert", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-125",
      type: "recognize",
      prompt: "la torta",
      accepted: ["cake", "the cake", "tart", "the tart"],
      translations: { "es": ["pastel", "el pastel"] },
      hint: "think 'torte' — a rich layered cake",
      tags: ["noun", "feminine", "food", "dessert", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-126",
      type: "recognize",
      prompt: "il biscotto",
      accepted: ["biscuit", "cookie", "the biscuit", "the cookie"],
      translations: { "es": ["galleta", "la galleta"] },
      hint: "think 'biscotti' — twice-baked Italian cookies",
      tags: ["noun", "masculine", "food", "dessert", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-127",
      type: "recognize",
      prompt: "il cioccolato",
      accepted: ["chocolate", "the chocolate"],
      translations: { "es": ["chocolate", "el chocolate"] },
      hint: "near-cognate with English 'chocolate'",
      tags: ["noun", "masculine", "food", "dessert", "A1", "tier1"],
      tier: 1,
    },

    // --- Additional vocabulary (produce) ---

    {
      id: "a111-t1-150",
      type: "produce",
      prompt: "the soup",
      accepted: ["la zuppa"],
      prompts: { "es": "la sopa" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-151",
      type: "produce",
      prompt: "the sandwich",
      accepted: ["il panino"],
      prompts: { "es": "el sándwich" },
      hint: "masculine noun — diminutive of 'pane' (bread)",
      tags: ["noun", "masculine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-152",
      type: "produce",
      prompt: "the pizza",
      accepted: ["la pizza"],
      prompts: { "es": "la pizza" },
      hint: "feminine noun — same word!",
      tags: ["noun", "feminine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-153",
      type: "produce",
      prompt: "the lemon",
      accepted: ["il limone"],
      prompts: { "es": "el limón" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-154",
      type: "produce",
      prompt: "the strawberries",
      accepted: ["le fragole"],
      prompts: { "es": "las fresas" },
      hint: "feminine plural — fragola → fragole",
      tags: ["noun", "feminine", "food", "fruit", "plural", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-155",
      type: "produce",
      prompt: "the grapes",
      accepted: ["l'uva"],
      prompts: { "es": "las uvas" },
      hint: "feminine — l' before vowel; collective, usually singular",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-156",
      type: "produce",
      prompt: "the pear",
      accepted: ["la pera"],
      prompts: { "es": "la pera" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-157",
      type: "produce",
      prompt: "the carrot",
      accepted: ["la carota"],
      prompts: { "es": "la zanahoria" },
      hint: "feminine noun — near-cognate with 'carrot'",
      tags: ["noun", "feminine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-158",
      type: "produce",
      prompt: "the mushroom",
      accepted: ["il fungo"],
      prompts: { "es": "el champiñón" },
      hint: "masculine noun — plural: i funghi",
      tags: ["noun", "masculine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-159",
      type: "produce",
      prompt: "the bell pepper",
      accepted: ["il peperone"],
      prompts: { "es": "el pimiento" },
      hint: "masculine noun — not 'il pepe' (black pepper)",
      tags: ["noun", "masculine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },

    // --- Additional vocabulary (recognize) ---

    {
      id: "a111-t1-160",
      type: "recognize",
      prompt: "la zuppa",
      accepted: ["soup", "the soup"],
      translations: { "es": ["sopa", "la sopa"] },
      hint: "think 'zuppa di pesce' — Italian fish soup",
      tags: ["noun", "feminine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-161",
      type: "recognize",
      prompt: "il panino",
      accepted: ["sandwich", "the sandwich", "bread roll", "the bread roll"],
      translations: { "es": ["sándwich", "el sándwich"] },
      hint: "diminutive of 'pane' (bread)",
      tags: ["noun", "masculine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-162",
      type: "recognize",
      prompt: "la pizza",
      accepted: ["pizza", "the pizza"],
      translations: { "es": ["pizza", "la pizza"] },
      hint: "identical to English",
      tags: ["noun", "feminine", "food", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-163",
      type: "recognize",
      prompt: "il limone",
      accepted: ["lemon", "the lemon"],
      translations: { "es": ["limón", "el limón"] },
      hint: "think 'limonata' — lemonade",
      tags: ["noun", "masculine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-164",
      type: "recognize",
      prompt: "le fragole",
      accepted: ["strawberries", "the strawberries"],
      translations: { "es": ["fresas", "las fresas"] },
      hint: "singular: la fragola",
      tags: ["noun", "feminine", "food", "fruit", "plural", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-165",
      type: "recognize",
      prompt: "l'uva",
      accepted: ["grapes", "the grapes", "grape"],
      translations: { "es": ["uvas", "las uvas"] },
      hint: "collective noun, feminine — l' before vowel",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-166",
      type: "recognize",
      prompt: "la pera",
      accepted: ["pear", "the pear"],
      translations: { "es": ["pera", "la pera"] },
      hint: "cognate with English 'pear'",
      tags: ["noun", "feminine", "food", "fruit", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-167",
      type: "recognize",
      prompt: "la carota",
      accepted: ["carrot", "the carrot"],
      translations: { "es": ["zanahoria", "la zanahoria"] },
      hint: "near-cognate with English 'carrot'",
      tags: ["noun", "feminine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-168",
      type: "recognize",
      prompt: "il fungo",
      accepted: ["mushroom", "the mushroom"],
      translations: { "es": ["champiñón", "el champiñón"] },
      hint: "plural: i funghi; think 'fungi'",
      tags: ["noun", "masculine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a111-t1-169",
      type: "recognize",
      prompt: "il peperone",
      accepted: ["bell pepper", "the bell pepper", "pepper", "capsicum"],
      translations: { "es": ["pimiento", "el pimiento"] },
      hint: "not to be confused with 'il pepe' (black pepper)",
      tags: ["noun", "masculine", "food", "vegetable", "A1", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Grammar (partitive articles & hunger/likes)
    // -------------------------------------------------------------------------
    {
      id: "a111-t2-001",
      type: "fill_blank",
      prompt: "I want some bread. → Voglio ___ pane.",
      accepted: ["del"],
      hint: "partitive article: di + il = del (masculine singular)",
      tags: ["grammar", "partitive", "masculine", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-001"],
    },
    {
      id: "a111-t2-002",
      type: "fill_blank",
      prompt: "She's buying some meat. → Compra ___ carne.",
      accepted: ["della"],
      hint: "partitive article: di + la = della (feminine singular)",
      tags: ["grammar", "partitive", "feminine", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-003"],
    },
    {
      id: "a111-t2-003",
      type: "fill_blank",
      prompt: "He drinks some water. → Beve ___ acqua.",
      accepted: ["dell'"],
      hint: "partitive article: di + l' = dell' (before vowel)",
      tags: ["grammar", "partitive", "elision", "tier2"],
      tier: 2,
    },
    {
      id: "a111-t2-004",
      type: "produce",
      prompt: "Are you hungry? (informal)",
      accepted: ["Hai fame?"],
      prompts: { "es": "¿Tienes hambre?" },
      hint: "literally 'do you have hunger?' — avere fame",
      tags: ["grammar", "avere", "hunger", "question", "tier2"],
      tier: 2,
    },

    // --- Additional grammar drills ---

    {
      id: "a111-t2-100",
      type: "fill_blank",
      prompt: "I want some tomatoes. → Voglio ___ pomodori.",
      accepted: ["dei"],
      hint: "partitive: di + i = dei (masculine plural, before consonant)",
      tags: ["grammar", "partitive", "masculine", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-010"],
    },
    {
      id: "a111-t2-101",
      type: "fill_blank",
      prompt: "I'm buying some potatoes. → Compro ___ patate.",
      accepted: ["delle"],
      hint: "partitive: di + le = delle (feminine plural)",
      tags: ["grammar", "partitive", "feminine", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-009"],
    },
    {
      id: "a111-t2-102",
      type: "fill_blank",
      prompt: "He eats some spaghetti. → Mangia ___ spaghetti.",
      accepted: ["degli"],
      hint: "partitive: di + gli = degli (masculine plural, s+consonant)",
      tags: ["grammar", "partitive", "masculine", "plural", "A1", "tier2"],
      tier: 2,
    },
    {
      id: "a111-t2-103",
      type: "fill_blank",
      prompt: "Do you want some sugar in your coffee? → Vuoi ___ zucchero nel caffè?",
      accepted: ["dello"],
      hint: "partitive: di + lo = dello (masculine singular, before z)",
      tags: ["grammar", "partitive", "masculine", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-017"],
    },
    {
      id: "a111-t2-104",
      type: "produce",
      prompt: "I'm thirsty.",
      accepted: ["Ho sete.", "Ho sete"],
      prompts: { "es": "Tengo sed." },
      hint: "avere sete — literally 'I have thirst'",
      tags: ["grammar", "avere", "thirst", "A1", "tier2"],
      tier: 2,
    },
    {
      id: "a111-t2-105",
      type: "fill_blank",
      prompt: "There is some fruit on the table. → C'è ___ frutta sul tavolo.",
      accepted: ["della"],
      hint: "partitive: di + la = della (feminine singular, before consonant)",
      tags: ["grammar", "partitive", "feminine", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-020"],
    },
    {
      id: "a111-t2-106",
      type: "fill_blank",
      prompt: "There are some mushrooms in the soup. → Ci sono ___ funghi nella zuppa.",
      accepted: ["dei"],
      hint: "partitive: di + i = dei (masculine plural, before consonant)",
      tags: ["grammar", "partitive", "masculine", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-158", "a111-t1-150"],
    },
    {
      id: "a111-t2-107",
      type: "fill_blank",
      prompt: "I like ice cream. → Mi ___ il gelato.",
      accepted: ["piace"],
      hint: "piace + singular noun",
      tags: ["grammar", "piacere", "singular", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-025"],
    },
    {
      id: "a111-t2-108",
      type: "fill_blank",
      prompt: "I like strawberries. → Mi ___ le fragole.",
      accepted: ["piacciono"],
      hint: "piacciono + plural noun",
      tags: ["grammar", "piacere", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-154"],
    },
    {
      id: "a111-t2-109",
      type: "fill_blank",
      prompt: "I don't like garlic. → Non mi ___ l'aglio.",
      accepted: ["piace"],
      hint: "non mi piace + singular noun",
      tags: ["grammar", "piacere", "negation", "singular", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-013"],
    },
    {
      id: "a111-t2-110",
      type: "produce",
      prompt: "I really like chocolate. (singular thing liked)",
      accepted: ["Mi piace molto il cioccolato.", "Mi piace molto il cioccolato"],
      prompts: { "es": "Me gusta mucho el chocolate." },
      hint: "mi piace + molto + singular noun",
      tags: ["grammar", "piacere", "singular", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-028"],
    },
    {
      id: "a111-t2-111",
      type: "fill_blank",
      prompt: "She wants some butter. → Lei vuole ___ burro.",
      accepted: ["del"],
      hint: "partitive: di + il = del (masculine singular, before consonant)",
      tags: ["grammar", "partitive", "masculine", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a111-t1-018"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Chunks / Phrases
    // -------------------------------------------------------------------------
    {
      id: "a111-t3-001",
      type: "produce",
      prompt: "I'm hungry.",
      accepted: ["Ho fame.", "Ho fame"],
      prompts: { "es": "Tengo hambre." },
      hint: "avere fame — literally 'I have hunger'",
      tags: ["chunk", "hunger", "avere", "tier3"],
      tier: 3,
      prerequisites: ["a111-t2-004"],
    },
    {
      id: "a111-t3-002",
      type: "produce",
      prompt: "I'd like some bread.",
      accepted: [
        "Vorrei del pane.",
        "Vorrei del pane",
      ],
      prompts: { "es": "Quisiera un poco de pan." },
      hint: "vorrei = I would like (conditional of volere)",
      tags: ["chunk", "ordering", "partitive", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-001", "a111-t2-001"],
    },
    {
      id: "a111-t3-003",
      type: "produce",
      prompt: "Do you have fish?",
      accepted: ["Hai il pesce?", "Avete il pesce?", "Ha il pesce?"],
      prompts: { "es": "¿Tienes pescado?" },
      hint: "hai = you have (informal); avete = you have (plural/formal shop)",
      tags: ["chunk", "question", "avere", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-005"],
    },
    {
      id: "a111-t3-004",
      type: "produce",
      prompt: "No sugar for me.",
      accepted: [
        "Niente zucchero per me.",
        "Niente zucchero per me",
        "Per me niente zucchero.",
      ],
      prompts: { "es": "Sin azúcar para mí." },
      hint: "niente = nothing / no; per me = for me",
      tags: ["chunk", "preference", "negation", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-017"],
    },
    {
      id: "a111-t3-005",
      type: "produce",
      prompt: "This cake is delicious.",
      accepted: [
        "Questa torta è deliziosa.",
        "Questa torta è deliziosa",
      ],
      prompts: { "es": "Este pastel está delicioso." },
      hint: "questa = this (feminine); deliziosa agrees with la torta",
      tags: ["chunk", "opinion", "adjective", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-026"],
    },
    {
      id: "a111-t3-006",
      type: "produce",
      prompt: "I like pasta. (singular thing liked)",
      accepted: ["Mi piace la pasta.", "Mi piace la pasta"],
      prompts: { "es": "Me gusta la pasta." },
      hint: "mi piace + singular noun",
      tags: ["chunk", "piacere", "singular", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-007"],
    },
    {
      id: "a111-t3-007",
      type: "produce",
      prompt: "I like tomatoes. (plural thing liked)",
      accepted: ["Mi piacciono i pomodori.", "Mi piacciono i pomodori"],
      prompts: { "es": "Me gustan los tomates." },
      hint: "mi piacciono + plural noun",
      tags: ["chunk", "piacere", "plural", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-010"],
    },

    // --- Additional phrases ---

    {
      id: "a111-t3-100",
      type: "produce",
      prompt: "I'm not hungry.",
      accepted: ["Non ho fame.", "Non ho fame"],
      prompts: { "es": "No tengo hambre." },
      hint: "negate avere fame — non before the verb",
      tags: ["chunk", "hunger", "avere", "negation", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t3-001"],
    },
    {
      id: "a111-t3-101",
      type: "produce",
      prompt: "What do you want to eat?",
      accepted: ["Cosa vuoi mangiare?", "Cosa vuoi mangiare"],
      prompts: { "es": "¿Qué quieres comer?" },
      hint: "cosa = what; vuoi = you want (informal); mangiare = to eat",
      tags: ["chunk", "question", "volere", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a111-t3-102",
      type: "produce",
      prompt: "I eat breakfast every morning.",
      accepted: ["Faccio colazione ogni mattina.", "Faccio colazione ogni mattina"],
      prompts: { "es": "Desayuno cada mañana." },
      hint: "fare colazione = to have breakfast; ogni mattina = every morning",
      tags: ["chunk", "meals", "fare", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a111-t3-103",
      type: "produce",
      prompt: "The food is very good.",
      accepted: ["Il cibo è molto buono.", "Il cibo è molto buono"],
      prompts: { "es": "La comida está muy buena." },
      hint: "cibo = food (general term); molto buono = very good",
      tags: ["chunk", "opinion", "adjective", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a111-t3-104",
      type: "produce",
      prompt: "Can I have some water?",
      accepted: [
        "Posso avere dell'acqua?",
        "Posso avere dell'acqua",
        "Posso avere un po' d'acqua?",
      ],
      prompts: { "es": "¿Me pone un poco de agua?" },
      hint: "posso = can I (potere); dell'acqua = some water (partitive)",
      tags: ["chunk", "ordering", "partitive", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a111-t3-105",
      type: "produce",
      prompt: "I really like fruit.",
      accepted: ["Mi piace molto la frutta.", "Mi piace molto la frutta"],
      prompts: { "es": "Me gusta mucho la fruta." },
      hint: "mi piace + molto; frutta is a singular collective noun",
      tags: ["chunk", "piacere", "fruit", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t3-006", "a111-t1-020"],
    },
    {
      id: "a111-t3-106",
      type: "produce",
      prompt: "We eat pasta every day.",
      accepted: ["Mangiamo la pasta ogni giorno.", "Mangiamo la pasta ogni giorno"],
      prompts: { "es": "Comemos pasta cada día." },
      hint: "mangiamo = we eat (noi); ogni giorno = every day",
      tags: ["chunk", "habits", "pasta", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-007"],
    },
    {
      id: "a111-t3-107",
      type: "produce",
      prompt: "There's no more bread.",
      accepted: [
        "Non c'è più pane.",
        "Non c'è più pane",
        "Non c'è più il pane.",
      ],
      prompts: { "es": "Ya no hay pan." },
      hint: "non c'è più = there's no more; pane without article is natural here",
      tags: ["chunk", "availability", "negation", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-001"],
    },
    {
      id: "a111-t3-108",
      type: "produce",
      prompt: "I want a coffee with milk.",
      accepted: [
        "Voglio un caffè con il latte.",
        "Voglio un caffè con il latte",
        "Voglio un caffè con latte.",
      ],
      prompts: { "es": "Quiero un café con leche." },
      hint: "caffè = coffee; con = with; il latte = the milk",
      tags: ["chunk", "drinks", "ordering", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-019"],
    },
    {
      id: "a111-t3-109",
      type: "produce",
      prompt: "For me, the salad, please.",
      accepted: [
        "Per me l'insalata, per favore.",
        "Per me l'insalata, grazie.",
        "Per me l'insalata per favore.",
      ],
      prompts: { "es": "Para mí, la ensalada, por favor." },
      hint: "per me = for me; per favore = please",
      tags: ["chunk", "ordering", "restaurant", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-011"],
    },

    // --- Additional phrases (collocation coverage) ---

    {
      id: "a111-t3-110",
      type: "produce",
      prompt: "I cook chicken with onion.",
      accepted: ["Cucino il pollo con la cipolla.", "Cucino il pollo con la cipolla"],
      prompts: { "es": "Cocino el pollo con la cebolla." },
      hint: "cucino = I cook (cucinare); con = with",
      tags: ["chunk", "cooking", "food", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-004", "a111-t1-012"],
    },
    {
      id: "a111-t3-111",
      type: "produce",
      prompt: "I put eggs in the sandwich.",
      accepted: ["Metto le uova nel panino.", "Metto le uova nel panino"],
      prompts: { "es": "Pongo los huevos en el sándwich." },
      hint: "metto = I put (mettere); nel = in + il",
      tags: ["chunk", "cooking", "food", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-006", "a111-t1-151"],
    },
    {
      id: "a111-t3-112",
      type: "produce",
      prompt: "I eat vegetables and a carrot for lunch.",
      accepted: ["Mangio la verdura e una carota a pranzo.", "Mangio la verdura e una carota a pranzo"],
      prompts: { "es": "Como verduras y una zanahoria para el almuerzo." },
      hint: "mangio = I eat; a pranzo = for lunch",
      tags: ["chunk", "meals", "food", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-021", "a111-t1-157"],
    },
    {
      id: "a111-t3-113",
      type: "produce",
      prompt: "I want a lemon and a pear.",
      accepted: ["Voglio un limone e una pera.", "Voglio un limone e una pera"],
      prompts: { "es": "Quiero un limón y una pera." },
      hint: "voglio = I want; un/una = indefinite article (a)",
      tags: ["chunk", "fruit", "ordering", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-153", "a111-t1-156"],
    },
    {
      id: "a111-t3-114",
      type: "produce",
      prompt: "The pizza has a mushroom and a bell pepper.",
      accepted: ["La pizza ha un fungo e un peperone.", "La pizza ha un fungo e un peperone"],
      prompts: { "es": "La pizza tiene un champiñón y un pimiento." },
      hint: "ha = has (avere); un = a (masculine indefinite article)",
      tags: ["chunk", "pizza", "food", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-158", "a111-t1-159"],
    },
    {
      id: "a111-t3-115",
      type: "produce",
      prompt: "I'd like some grapes, please.",
      accepted: [
        "Vorrei dell'uva, per favore.",
        "Vorrei dell'uva per favore.",
        "Vorrei dell'uva, per favore",
      ],
      prompts: { "es": "Quisiera uvas, por favor." },
      hint: "vorrei = I would like; dell' = di + l' (partitive before vowel)",
      tags: ["chunk", "ordering", "partitive", "fruit", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-155"],
    },
    {
      id: "a111-t3-116",
      type: "produce",
      prompt: "The sandwich has chicken and lemon.",
      accepted: ["Il panino ha il pollo e il limone.", "Il panino ha il pollo e il limone"],
      prompts: { "es": "El sándwich tiene pollo y limón." },
      hint: "ha = has (avere); list items take definite articles in Italian",
      tags: ["chunk", "food", "ordering", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-151", "a111-t1-004", "a111-t1-153"],
    },
    {
      id: "a111-t3-117",
      type: "produce",
      prompt: "The salad has onion and bell pepper.",
      accepted: ["L'insalata ha la cipolla e il peperone.", "L'insalata ha la cipolla e il peperone"],
      prompts: { "es": "La ensalada tiene cebolla y pimiento." },
      hint: "ha = has (avere); l' before vowel",
      tags: ["chunk", "food", "salad", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a111-t1-011", "a111-t1-012", "a111-t1-159"],
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Passage Cloze / Sentences
    // -------------------------------------------------------------------------
    {
      id: "a111-t4-001",
      type: "passage_cloze",
      prompt: "Sono al mercato con la mia amica Giulia.\nLei compra della frutta: una mela, una banana e un'arancia.\nIo prendo del ___, perché voglio fare la pasta stasera.\nIl venditore sorride: «Ottima scelta! È fresco di stamattina.»\nUsciamo dal mercato contenti.",
      accepted: ["pesce"],
      hint: "a fresh ingredient bought at the market to cook with pasta — which protein from this unit fits?",
      tags: ["passage_cloze", "food", "market", "partitive", "tier4"],
      tier: 4,
      prerequisites: [
        "a111-t1-005",
        "a111-t1-007",
        "a111-t1-020",
        "a111-t1-022",
        "a111-t1-023",
        "a111-t1-024",
        "a111-t2-001",
        "a111-t3-002",
      ],
    },

    // --- Additional sentences ---

    {
      id: "a111-t4-100",
      type: "produce",
      prompt: "My mother cooks fish and potatoes every evening.",
      accepted: [
        "Mia madre cucina il pesce e le patate ogni sera.",
        "Mia madre cucina il pesce e le patate ogni sera",
      ],
      prompts: { "es": "Mi madre cocina pescado y patatas todas las noches." },
      hint: "mia madre = my mother (no article); cucina = she cooks; ogni sera = every evening",
      tags: ["sentence", "food", "family", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-005", "a111-t1-009"],
    },
    {
      id: "a111-t4-101",
      type: "produce",
      prompt: "Marco buys bread and cheese at the market.",
      accepted: [
        "Marco compra il pane e il formaggio al mercato.",
        "Marco compra il pane e il formaggio al mercato",
      ],
      prompts: { "es": "Marco compra pan y queso en el mercado." },
      hint: "compra = he buys; al mercato = at the market (a + il)",
      tags: ["sentence", "food", "shopping", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-001", "a111-t1-002"],
    },
    {
      id: "a111-t4-102",
      type: "produce",
      prompt: "We eat rice with tomatoes for lunch.",
      accepted: [
        "Mangiamo il riso con i pomodori a pranzo.",
        "Mangiamo il riso con i pomodori a pranzo",
      ],
      prompts: { "es": "Comemos arroz con tomates para el almuerzo." },
      hint: "mangiamo = we eat; a pranzo = for lunch",
      tags: ["sentence", "food", "meals", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-008", "a111-t1-010"],
    },
    {
      id: "a111-t4-103",
      type: "fill_blank",
      prompt: "Sara eats an apple every morning. → Sara mangia ___ mela ogni mattina.",
      accepted: ["una"],
      hint: "feminine indefinite article before consonant",
      tags: ["sentence", "food", "article", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-022"],
    },
    {
      id: "a111-t4-104",
      type: "produce",
      prompt: "There is no milk in the fridge.",
      accepted: [
        "Non c'è latte in frigo.",
        "Non c'è il latte in frigo.",
        "Non c'è latte in frigorifero.",
        "Non c'è il latte in frigorifero.",
      ],
      prompts: { "es": "No hay leche en el frigorífico." },
      hint: "non c'è = there isn't; in frigo = in the fridge",
      tags: ["sentence", "food", "dairy", "negation", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-019"],
    },
    {
      id: "a111-t4-105",
      type: "produce",
      prompt: "I put sugar and butter in the cake.",
      accepted: [
        "Metto lo zucchero e il burro nella torta.",
        "Metto lo zucchero e il burro nella torta",
      ],
      prompts: { "es": "Pongo azúcar y mantequilla en el pastel." },
      hint: "metto = I put (mettere); nella = in + la",
      tags: ["sentence", "food", "cooking", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-017", "a111-t1-018", "a111-t1-026"],
    },
    {
      id: "a111-t4-106",
      type: "fill_blank",
      prompt: "We want some ice cream for dessert. → Vogliamo ___ gelato per dessert.",
      accepted: ["del"],
      hint: "partitive: di + il = del (masculine singular)",
      tags: ["sentence", "food", "dessert", "partitive", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-025", "a111-t2-001"],
    },
    {
      id: "a111-t4-107",
      type: "produce",
      prompt: "The pizza has tomatoes, cheese, and olive oil.",
      accepted: [
        "La pizza ha i pomodori, il formaggio e l'olio d'oliva.",
        "La pizza ha i pomodori, il formaggio e l'olio d'oliva",
      ],
      prompts: { "es": "La pizza tiene tomates, queso y aceite de oliva." },
      hint: "ha = has (avere); list items take definite articles in Italian",
      tags: ["sentence", "food", "pizza", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-002", "a111-t1-010", "a111-t1-014", "a111-t1-152"],
    },
    {
      id: "a111-t4-108",
      type: "produce",
      prompt: "I put a bit of pepper and salt in the soup.",
      accepted: [
        "Metto un po' di pepe e sale nella zuppa.",
        "Metto un po' di pepe e sale nella zuppa",
      ],
      prompts: { "es": "Pongo un poco de pimienta y sal en la sopa." },
      hint: "metto = I put; un po' di = a bit of; nella = in + la",
      tags: ["sentence", "food", "cooking", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a111-t1-015", "a111-t1-016", "a111-t1-150"],
    },
    {
      id: "a111-t4-109",
      type: "passage_cloze",
      prompt: "Ogni domenica la famiglia Rossi mangia insieme.\nLa nonna prepara la ___ con i pomodori freschi e l'aglio.\nTutti portano qualcosa: chi il pane, chi il vino.\nDopo, c'è sempre della frutta e un biscotto con il caffè.\nÈ il momento più bello della settimana.",
      accepted: ["pasta"],
      hint: "grandma's Sunday dish — made with fresh tomatoes and garlic",
      tags: ["passage_cloze", "food", "family", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a111-t1-001",
        "a111-t1-007",
        "a111-t1-010",
        "a111-t1-013",
        "a111-t1-020",
        "a111-t1-027",
        "a111-t2-002",
      ],
    },
  ],
};

export default unit;
