import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-17-weather",
  name: "Weather & Nature",
  level: "A1",
  theme: "Weather & Nature",
  emoji: "🌤",
  prerequisiteUnits: [],
  cards: [
    // ─── Tier 1 – Vocabulary (produce) ────────────────────────────────────────
    {
      id: "a117-t1-001",
      type: "produce",
      prompt: "the sun",
      accepted: ["il sole"],
      prompts: { "es": "el sol" },
      hint: "Masculine; sol- root",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-002",
      type: "produce",
      prompt: "the rain",
      accepted: ["la pioggia"],
      prompts: { "es": "la lluvia" },
      hint: "Feminine; piogg- root",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-003",
      type: "produce",
      prompt: "the snow",
      accepted: ["la neve"],
      prompts: { "es": "la nieve" },
      hint: "Feminine; nev- root (nevica = it snows)",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-004",
      type: "produce",
      prompt: "the wind",
      accepted: ["il vento"],
      prompts: { "es": "el viento" },
      hint: "Masculine; like 'ventilate'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-005",
      type: "produce",
      prompt: "the cloud",
      accepted: ["la nuvola"],
      prompts: { "es": "la nube" },
      hint: "Feminine; plural: le nuvole",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-006",
      type: "produce",
      prompt: "the fog",
      accepted: ["la nebbia"],
      prompts: { "es": "la niebla" },
      hint: "Feminine; think 'nebulous'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-007",
      type: "produce",
      prompt: "the thunderstorm",
      accepted: ["il temporale"],
      prompts: { "es": "la tormenta" },
      hint: "Masculine; like 'temporal' — a stormy moment",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-008",
      type: "produce",
      prompt: "the thunder",
      accepted: ["il tuono"],
      prompts: { "es": "el trueno" },
      hint: "Masculine; tuon- root",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-009",
      type: "produce",
      prompt: "the lightning",
      accepted: ["il fulmine"],
      prompts: { "es": "el relámpago" },
      hint: "Masculine; think 'fulminate'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-010",
      type: "produce",
      prompt: "the heat / the warmth",
      accepted: ["il caldo"],
      prompts: { "es": "el calor" },
      hint: "Masculine; fa caldo = it's hot",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-011",
      type: "produce",
      prompt: "the cold",
      accepted: ["il freddo"],
      prompts: { "es": "el frío" },
      hint: "Masculine; fa freddo = it's cold",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-012",
      type: "produce",
      prompt: "hot / warm (adjective, m.sg.)",
      accepted: ["caldo"],
      prompts: { "es": "caliente / cálido" },
      hint: "Changes: caldo/calda/caldi/calde",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-013",
      type: "produce",
      prompt: "cold (adjective, m.sg.)",
      accepted: ["freddo"],
      prompts: { "es": "frío" },
      hint: "Changes: freddo/fredda/freddi/fredde",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-014",
      type: "produce",
      prompt: "cool / fresh (adjective, m.sg.)",
      accepted: ["fresco"],
      prompts: { "es": "fresco" },
      hint: "Familiar from 'al fresco'",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-015",
      type: "produce",
      prompt: "cloudy (adjective, m.sg.)",
      accepted: ["nuvoloso"],
      prompts: { "es": "nublado" },
      hint: "From nuvola (cloud)",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-016",
      type: "produce",
      prompt: "sunny (adjective, m.sg.)",
      accepted: ["soleggiato"],
      prompts: { "es": "soleado" },
      hint: "From sole (sun)",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-017",
      type: "produce",
      prompt: "the mountain",
      accepted: ["la montagna"],
      prompts: { "es": "la montaña" },
      hint: "Feminine; think 'Montana'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-018",
      type: "produce",
      prompt: "the sea",
      accepted: ["il mare"],
      prompts: { "es": "el mar" },
      hint: "Masculine; think 'marine'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-019",
      type: "produce",
      prompt: "the lake",
      accepted: ["il lago"],
      prompts: { "es": "el lago" },
      hint: "Masculine; think 'lagoon'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-020",
      type: "produce",
      prompt: "the river",
      accepted: ["il fiume"],
      prompts: { "es": "el río" },
      hint: "Masculine; think 'fluvial'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-021",
      type: "produce",
      prompt: "the hill",
      accepted: ["la collina"],
      prompts: { "es": "la colina" },
      hint: "Feminine; smaller than a mountain",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-022",
      type: "produce",
      prompt: "the forest / the wood",
      accepted: ["il bosco", "la foresta"],
      prompts: { "es": "el bosque / la foresta" },
      hint: "Il bosco = wood; la foresta = forest",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-023",
      type: "produce",
      prompt: "the sky",
      accepted: ["il cielo"],
      prompts: { "es": "el cielo" },
      hint: "Masculine; think 'celestial'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-024",
      type: "produce",
      prompt: "spring (the season)",
      accepted: ["la primavera"],
      prompts: { "es": "la primavera" },
      hint: "Feminine; prima (first) + vera (green/true)",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-025",
      type: "produce",
      prompt: "summer (the season)",
      accepted: ["l'estate"],
      prompts: { "es": "el verano" },
      hint: "Feminine; starts with vowel — l'estate",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-026",
      type: "produce",
      prompt: "autumn (the season)",
      accepted: ["l'autunno"],
      prompts: { "es": "el otoño" },
      hint: "Masculine; think 'autumnal'",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-027",
      type: "produce",
      prompt: "winter (the season)",
      accepted: ["l'inverno"],
      prompts: { "es": "el invierno" },
      hint: "Masculine; think 'hibernal'",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    // ─── Tier 1 – Vocabulary (recognize) seq 100–126 ──────────────────────────
    {
      id: "a117-t1-100",
      type: "recognize",
      prompt: "il sole",
      accepted: ["the sun", "sun"],
      translations: { "es": ["el sol"] },
      hint: "Sol- root; masculine noun",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-101",
      type: "recognize",
      prompt: "la pioggia",
      accepted: ["the rain", "rain"],
      translations: { "es": ["la lluvia"] },
      hint: "Piogg- root; feminine noun",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-102",
      type: "recognize",
      prompt: "la neve",
      accepted: ["the snow", "snow"],
      translations: { "es": ["la nieve"] },
      hint: "Nev- root; nevica = it snows",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-103",
      type: "recognize",
      prompt: "il vento",
      accepted: ["the wind", "wind"],
      translations: { "es": ["el viento"] },
      hint: "Think 'ventilate'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-104",
      type: "recognize",
      prompt: "la nuvola",
      accepted: ["the cloud", "cloud"],
      translations: { "es": ["la nube"] },
      hint: "Plural: le nuvole",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-105",
      type: "recognize",
      prompt: "la nebbia",
      accepted: ["the fog", "fog", "mist"],
      translations: { "es": ["la niebla"] },
      hint: "Think 'nebulous'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-106",
      type: "recognize",
      prompt: "il temporale",
      accepted: ["the thunderstorm", "thunderstorm", "storm"],
      translations: { "es": ["la tormenta"] },
      hint: "Like 'temporal' — a stormy moment",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-107",
      type: "recognize",
      prompt: "il tuono",
      accepted: ["the thunder", "thunder"],
      translations: { "es": ["el trueno"] },
      hint: "Tuon- root",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-108",
      type: "recognize",
      prompt: "il fulmine",
      accepted: ["the lightning", "lightning", "lightning bolt"],
      translations: { "es": ["el relámpago"] },
      hint: "Think 'fulminate'",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-109",
      type: "recognize",
      prompt: "il caldo",
      accepted: ["the heat", "the warmth", "heat", "warmth"],
      translations: { "es": ["el calor"] },
      hint: "Fa caldo = it's hot",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-110",
      type: "recognize",
      prompt: "il freddo",
      accepted: ["the cold", "cold"],
      translations: { "es": ["el frío"] },
      hint: "Fa freddo = it's cold",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-111",
      type: "recognize",
      prompt: "caldo",
      accepted: ["hot", "warm"],
      translations: { "es": ["caliente","cálido"] },
      hint: "Adjective; noun form: il caldo",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-112",
      type: "recognize",
      prompt: "freddo",
      accepted: ["cold"],
      translations: { "es": ["frío"] },
      hint: "Adjective; fa freddo = it's cold",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-113",
      type: "recognize",
      prompt: "fresco",
      accepted: ["cool", "fresh"],
      translations: { "es": ["fresco"] },
      hint: "Al fresco = in the open air",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-114",
      type: "recognize",
      prompt: "nuvoloso",
      accepted: ["cloudy"],
      translations: { "es": ["nublado"] },
      hint: "From nuvola (cloud)",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-115",
      type: "recognize",
      prompt: "soleggiato",
      accepted: ["sunny"],
      translations: { "es": ["soleado"] },
      hint: "From sole (sun)",
      tags: ["A1", "weather", "adjectives"],
      tier: 1,
    },
    {
      id: "a117-t1-116",
      type: "recognize",
      prompt: "la montagna",
      accepted: ["the mountain", "mountain"],
      translations: { "es": ["la montaña"] },
      hint: "Think 'Montana'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-117",
      type: "recognize",
      prompt: "il mare",
      accepted: ["the sea", "sea"],
      translations: { "es": ["el mar"] },
      hint: "Think 'marine'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-118",
      type: "recognize",
      prompt: "il lago",
      accepted: ["the lake", "lake"],
      translations: { "es": ["el lago"] },
      hint: "Think 'lagoon'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-119",
      type: "recognize",
      prompt: "il fiume",
      accepted: ["the river", "river"],
      translations: { "es": ["el río"] },
      hint: "Think 'fluvial'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-120",
      type: "recognize",
      prompt: "la collina",
      accepted: ["the hill", "hill"],
      translations: { "es": ["la colina"] },
      hint: "Smaller than la montagna",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-121",
      type: "recognize",
      prompt: "il bosco",
      accepted: ["the wood", "the forest", "wood", "forest"],
      translations: { "es": ["el bosque"] },
      hint: "Smaller than la foresta",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-122",
      type: "recognize",
      prompt: "il cielo",
      accepted: ["the sky", "sky"],
      translations: { "es": ["el cielo"] },
      hint: "Think 'celestial'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-123",
      type: "recognize",
      prompt: "la primavera",
      accepted: ["spring", "springtime"],
      translations: { "es": ["la primavera"] },
      hint: "Prima (first) + vera (green)",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-124",
      type: "recognize",
      prompt: "l'estate",
      accepted: ["summer", "summertime"],
      translations: { "es": ["el verano"] },
      hint: "Feminine; starts with vowel",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-125",
      type: "recognize",
      prompt: "l'autunno",
      accepted: ["autumn", "fall"],
      translations: { "es": ["el otoño"] },
      hint: "Think 'autumnal'",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-126",
      type: "recognize",
      prompt: "l'inverno",
      accepted: ["winter", "wintertime"],
      translations: { "es": ["el invierno"] },
      hint: "Think 'hibernal'",
      tags: ["A1", "seasons", "nouns"],
      tier: 1,
    },
    // ─── Tier 1 – Additional vocabulary (produce + recognize) seq 150–169 ─────
    {
      id: "a117-t1-150",
      type: "produce",
      prompt: "the rainbow",
      accepted: ["l'arcobaleno"],
      prompts: { "es": "el arcoíris" },
      hint: "Masculine; arco (arc) + baleno (flash)",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-151",
      type: "recognize",
      prompt: "l'arcobaleno",
      accepted: ["the rainbow", "rainbow"],
      translations: { "es": ["el arcoíris"] },
      hint: "Arco = arc; baleno = flash of light",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-152",
      type: "produce",
      prompt: "the hail",
      accepted: ["la grandine"],
      prompts: { "es": "el granizo" },
      hint: "Feminine; grandina = it hails",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-153",
      type: "recognize",
      prompt: "la grandine",
      accepted: ["the hail", "hail"],
      translations: { "es": ["el granizo"] },
      hint: "Grandina = it hails",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-154",
      type: "produce",
      prompt: "the ice",
      accepted: ["il ghiaccio"],
      prompts: { "es": "el hielo" },
      hint: "Masculine; think 'glacier'",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-155",
      type: "recognize",
      prompt: "il ghiaccio",
      accepted: ["the ice", "ice"],
      translations: { "es": ["el hielo"] },
      hint: "Think 'glacier'",
      tags: ["A1", "weather", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-156",
      type: "produce",
      prompt: "the tree",
      accepted: ["l'albero"],
      prompts: { "es": "el árbol" },
      hint: "Masculine; think 'arboreal'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-157",
      type: "recognize",
      prompt: "l'albero",
      accepted: ["the tree", "tree"],
      translations: { "es": ["el árbol"] },
      hint: "Think 'arboreal'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-158",
      type: "produce",
      prompt: "the flower",
      accepted: ["il fiore"],
      prompts: { "es": "la flor" },
      hint: "Masculine; think 'flora'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-159",
      type: "recognize",
      prompt: "il fiore",
      accepted: ["the flower", "flower"],
      translations: { "es": ["la flor"] },
      hint: "Think 'flora'",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-160",
      type: "produce",
      prompt: "the beach",
      accepted: ["la spiaggia"],
      prompts: { "es": "la playa" },
      hint: "Feminine; plural: le spiagge",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-161",
      type: "recognize",
      prompt: "la spiaggia",
      accepted: ["the beach", "beach"],
      translations: { "es": ["la playa"] },
      hint: "Plural: le spiagge",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-162",
      type: "produce",
      prompt: "the umbrella",
      accepted: ["l'ombrello"],
      prompts: { "es": "el paraguas" },
      hint: "Masculine; from ombra (shadow)",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-163",
      type: "recognize",
      prompt: "l'ombrello",
      accepted: ["the umbrella", "umbrella"],
      translations: { "es": ["el paraguas"] },
      hint: "From ombra (shadow)",
      tags: ["A1", "weather", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-164",
      type: "produce",
      prompt: "the countryside",
      accepted: ["la campagna"],
      prompts: { "es": "el campo" },
      hint: "Feminine; think 'campaign' (open fields)",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-165",
      type: "recognize",
      prompt: "la campagna",
      accepted: ["the countryside", "countryside", "the country"],
      translations: { "es": ["el campo"] },
      hint: "Think 'campaign' (open fields)",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-166",
      type: "produce",
      prompt: "the sunset",
      accepted: ["il tramonto"],
      prompts: { "es": "la puesta de sol / el atardecer" },
      hint: "Masculine; tramontare = to set (of the sun)",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-167",
      type: "recognize",
      prompt: "il tramonto",
      accepted: ["the sunset", "sunset"],
      translations: { "es": ["la puesta de sol"] },
      hint: "Tramontare = to set (of the sun)",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-168",
      type: "produce",
      prompt: "the dawn / the sunrise",
      accepted: ["l'alba"],
      prompts: { "es": "el amanecer" },
      hint: "Feminine; sky brightening at first light",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    {
      id: "a117-t1-169",
      type: "recognize",
      prompt: "l'alba",
      accepted: ["the dawn", "the sunrise", "dawn", "sunrise"],
      translations: { "es": ["el amanecer"] },
      hint: "Sky brightening at first light",
      tags: ["A1", "nature", "nouns"],
      tier: 1,
    },
    // ─── Tier 2 – Grammar ──────────────────────────────────────────────────────
    {
      id: "a117-t2-001",
      type: "fill_blank",
      prompt: "It's hot. → ___ caldo.",
      accepted: ["Fa"],
      hint: "Fare + adjective for weather; impersonal 3rd person",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-002",
      type: "fill_blank",
      prompt: "It's cold. → ___ freddo.",
      accepted: ["Fa"],
      hint: "Same structure as fa caldo",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-003",
      type: "fill_blank",
      prompt: "It's cool / fresh. → ___ fresco.",
      accepted: ["Fa"],
      hint: "Fa + adjective — the pattern is consistent",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-004",
      type: "fill_blank",
      prompt: "The weather is nice. → ___ bello.",
      accepted: ["Fa"],
      hint: "Fa bello = nice weather",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-005",
      type: "fill_blank",
      prompt: "The weather is bad. → ___ brutto.",
      accepted: ["Fa"],
      hint: "Fa brutto = bad weather",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-006",
      type: "fill_blank",
      prompt: "The sun is out. → ___ il sole.",
      accepted: ["C'è"],
      hint: "C'è = there is (c'è = ci + è)",
      tags: ["A1", "weather", "grammar", "ci-e"],
      tier: 2,
    },
    {
      id: "a117-t2-007",
      type: "fill_blank",
      prompt: "There is fog. → ___ la nebbia.",
      accepted: ["C'è"],
      hint: "C'è for singular; ci sono for plural",
      tags: ["A1", "weather", "grammar", "ci-e"],
      tier: 2,
    },
    {
      id: "a117-t2-008",
      type: "fill_blank",
      prompt: "There is a thunderstorm. → ___ il temporale.",
      accepted: ["C'è"],
      hint: "C'è + masculine singular noun",
      tags: ["A1", "weather", "grammar", "ci-e"],
      tier: 2,
    },
    {
      id: "a117-t2-009",
      type: "fill_blank",
      prompt: "There are clouds. → ___ le nuvole.",
      accepted: ["Ci sono"],
      hint: "Ci sono = there are (plural)",
      tags: ["A1", "weather", "grammar", "ci-sono"],
      tier: 2,
    },
    {
      id: "a117-t2-010",
      type: "produce",
      prompt: "it is raining (impersonal verb)",
      accepted: ["piove"],
      prompts: { "es": "llueve" },
      hint: "Impersonal — no subject, only 3rd person singular",
      tags: ["A1", "weather", "grammar", "impersonal"],
      tier: 2,
    },
    {
      id: "a117-t2-011",
      type: "produce",
      prompt: "it is snowing (impersonal verb)",
      accepted: ["nevica"],
      prompts: { "es": "nieva" },
      hint: "From nevicare; impersonal like piove",
      tags: ["A1", "weather", "grammar", "impersonal"],
      tier: 2,
    },
    {
      id: "a117-t2-012",
      type: "produce",
      prompt: "it is windy (literally: it pulls wind)",
      accepted: ["tira vento"],
      prompts: { "es": "hace viento" },
      hint: "Tira = it pulls; fixed expression",
      tags: ["A1", "weather", "grammar", "expressions"],
      tier: 2,
    },
    {
      id: "a117-t2-013",
      type: "produce",
      prompt: "What is the weather like? (question)",
      accepted: ["Che tempo fa?", "Che tempo fa"],
      prompts: { "es": "¿Qué tiempo hace?" },
      hint: "Che = what; tempo = weather; fa = does/makes",
      tags: ["A1", "weather", "grammar", "questions"],
      tier: 2,
    },
    {
      id: "a117-t2-014",
      type: "fill_blank",
      prompt: "In spring I go to the countryside. → ___ primavera vado in campagna.",
      accepted: ["In"],
      hint: "Season preposition: in primavera / in estate / in autunno / in inverno",
      tags: ["A1", "seasons", "grammar", "prepositions"],
      tier: 2,
    },
    {
      id: "a117-t2-015",
      type: "fill_blank",
      prompt: "In winter it snows. → ___ inverno nevica.",
      accepted: ["In"],
      hint: "Always 'in' + season, no article",
      tags: ["A1", "seasons", "grammar", "prepositions"],
      tier: 2,
    },
    // ─── Tier 2 – Additional grammar drills seq 100–110 ───────────────────────
    {
      id: "a117-t2-100",
      type: "fill_blank",
      prompt: "It's hailing. → ___ .",
      accepted: ["Grandina"],
      hint: "Impersonal verb like piove and nevica",
      tags: ["A1", "weather", "grammar", "impersonal"],
      tier: 2,
    },
    {
      id: "a117-t2-101",
      type: "fill_blank",
      prompt: "The weather is nice. → Il tempo ___ bello.",
      accepted: ["è"],
      hint: "Essere to describe il tempo as a noun",
      tags: ["A1", "weather", "grammar", "essere"],
      tier: 2,
    },
    {
      id: "a117-t2-102",
      type: "fill_blank",
      prompt: "In autumn it rains a lot. → ___ autunno piove molto.",
      accepted: ["In"],
      hint: "Always 'in' + season, no article",
      tags: ["A1", "seasons", "grammar", "prepositions"],
      tier: 2,
    },
    {
      id: "a117-t2-103",
      type: "fill_blank",
      prompt: "In spring the weather is nice. → ___ primavera fa bello.",
      accepted: ["In"],
      hint: "In + season — no article needed",
      tags: ["A1", "seasons", "grammar", "prepositions"],
      tier: 2,
    },
    {
      id: "a117-t2-104",
      type: "fill_blank",
      prompt: "There is a rainbow. → ___ un arcobaleno.",
      accepted: ["C'è"],
      hint: "C'è = there is; un because it's a new, indefinite rainbow",
      tags: ["A1", "weather", "grammar", "ci-e"],
      tier: 2,
    },
    {
      id: "a117-t2-105",
      type: "fill_blank",
      prompt: "The sun isn't out today. → Oggi non ___ il sole.",
      accepted: ["c'è"],
      hint: "Non c'è = there isn't",
      tags: ["A1", "weather", "grammar", "ci-e", "negation"],
      tier: 2,
    },
    {
      id: "a117-t2-106",
      type: "fill_blank",
      prompt: "Today the sky is cloudy (m.sg.). → Il cielo è ___ oggi.",
      accepted: ["nuvoloso"],
      hint: "Masculine singular: cielo → nuvoloso",
      tags: ["A1", "weather", "grammar", "adjectives"],
      tier: 2,
    },
    {
      id: "a117-t2-107",
      type: "fill_blank",
      prompt: "The day is beautiful (f.sg.). → La giornata è ___.",
      accepted: ["bella"],
      hint: "Feminine singular: giornata → bella",
      tags: ["A1", "weather", "grammar", "adjectives"],
      tier: 2,
    },
    {
      id: "a117-t2-108",
      type: "fill_blank",
      prompt: "There are many clouds today. → Oggi ___ molte nuvole.",
      accepted: ["ci sono"],
      hint: "Ci sono = there are (plural)",
      tags: ["A1", "weather", "grammar", "ci-sono"],
      tier: 2,
    },
    {
      id: "a117-t2-109",
      type: "fill_blank",
      prompt: "It's a bit cold today. → Oggi fa ___ freddo.",
      accepted: ["un po'"],
      hint: "Un po' = a bit; softens fa freddo",
      tags: ["A1", "weather", "grammar", "fare"],
      tier: 2,
    },
    {
      id: "a117-t2-110",
      type: "fill_blank",
      prompt: "It's very windy today. → Oggi ___ molto vento.",
      accepted: ["tira"],
      hint: "Tira vento = it's windy; literally 'pulls wind'",
      tags: ["A1", "weather", "grammar", "expressions"],
      tier: 2,
    },
    // ─── Tier 3 – Chunks / Phrases ─────────────────────────────────────────────
    {
      id: "a117-t3-001",
      type: "produce",
      prompt: "What's the weather like today?",
      accepted: ["Che tempo fa oggi?", "Che tempo fa oggi"],
      prompts: { "es": "¿Qué tiempo hace hoy?" },
      hint: "Che tempo fa? + oggi (today)",
      tags: ["A1", "weather", "chunks", "questions"],
      tier: 3,
      prerequisites: ["a117-t2-013"],
    },
    {
      id: "a117-t3-002",
      type: "produce",
      prompt: "It's sunny and warm.",
      accepted: ["C'è il sole e fa caldo.", "C'è il sole e fa caldo"],
      prompts: { "es": "Hay sol y hace calor." },
      hint: "C'è il sole (there's sun) + e (and) + fa caldo",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-001", "a117-t2-006"],
    },
    {
      id: "a117-t3-003",
      type: "produce",
      prompt: "It's raining. Take an umbrella.",
      accepted: [
        "Piove. Prendi l'ombrello.",
        "Piove. Prendi l'ombrello",
      ],
      prompts: { "es": "Llueve. Lleva un paraguas." },
      hint: "Piove + prendi (take, tu imperative) + l'ombrello",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-010"],
    },
    {
      id: "a117-t3-004",
      type: "produce",
      prompt: "In winter it snows in the mountains.",
      accepted: [
        "In inverno nevica in montagna.",
        "In inverno nevica in montagna",
      ],
      prompts: { "es": "En invierno nieva en las montañas." },
      hint: "In inverno + nevica + in montagna",
      tags: ["A1", "weather", "seasons", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-011", "a117-t2-015"],
    },
    {
      id: "a117-t3-005",
      type: "produce",
      prompt: "It's very cold today.",
      accepted: ["Oggi fa molto freddo.", "Oggi fa molto freddo"],
      prompts: { "es": "Hoy hace mucho frío." },
      hint: "Oggi (today) + fa + molto (very) + freddo",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-002"],
    },
    {
      id: "a117-t3-006",
      type: "produce",
      prompt: "What a beautiful day!",
      accepted: ["Che bella giornata!", "Che bella giornata"],
      prompts: { "es": "¡Qué día tan bonito!" },
      hint: "Che + bella (beautiful, f.) + giornata (day)",
      tags: ["A1", "weather", "chunks", "exclamations"],
      tier: 3,
    },
    {
      id: "a117-t3-007",
      type: "produce",
      prompt: "There are clouds in the sky.",
      accepted: [
        "Ci sono le nuvole nel cielo.",
        "Ci sono le nuvole nel cielo",
      ],
      prompts: { "es": "Hay nubes en el cielo." },
      hint: "Ci sono + le nuvole + nel cielo (nel = in + il)",
      tags: ["A1", "weather", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-009"],
    },
    {
      id: "a117-t3-008",
      type: "produce",
      prompt: "In summer it's very hot.",
      accepted: ["In estate fa molto caldo.", "In estate fa molto caldo"],
      prompts: { "es": "En verano hace mucho calor." },
      hint: "In estate + fa + molto + caldo",
      tags: ["A1", "weather", "seasons", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-001"],
    },
    // ─── Tier 3 – Additional phrases seq 100–107 ──────────────────────────────
    {
      id: "a117-t3-100",
      type: "produce",
      prompt: "The weather is bad today. Stay at home.",
      accepted: [
        "Il tempo è brutto oggi. Resta a casa.",
        "Il tempo è brutto oggi. Resta a casa",
      ],
      prompts: { "es": "El tiempo está malo hoy. Quédate en casa." },
      hint: "Il tempo è brutto + resta (stay, tu imperative) + a casa",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-005"],
    },
    {
      id: "a117-t3-101",
      type: "produce",
      prompt: "It's hailing. Let's go inside.",
      accepted: ["Grandina. Entriamo.", "Grandina. Entriamo"],
      prompts: { "es": "Está granizando. Entremos." },
      hint: "Grandina (it's hailing) + entriamo (let's go in)",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-100"],
    },
    {
      id: "a117-t3-102",
      type: "produce",
      prompt: "What's the weather like in autumn?",
      accepted: ["Che tempo fa in autunno?", "Che tempo fa in autunno"],
      prompts: { "es": "¿Qué tiempo hace en otoño?" },
      hint: "Che tempo fa? + in autunno",
      tags: ["A1", "weather", "seasons", "chunks", "questions"],
      tier: 3,
      prerequisites: ["a117-t2-013"],
    },
    {
      id: "a117-t3-103",
      type: "produce",
      prompt: "It's a beautiful day for a walk.",
      accepted: [
        "È una bella giornata per una passeggiata.",
        "È una bella giornata per una passeggiata",
      ],
      prompts: { "es": "Es un día bonito para pasear." },
      hint: "È una bella giornata + per (for) + una passeggiata (a walk)",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
    },
    {
      id: "a117-t3-104",
      type: "produce",
      prompt: "Do you prefer summer or winter?",
      accepted: [
        "Preferisci l'estate o l'inverno?",
        "Preferisci l'estate o l'inverno",
      ],
      prompts: { "es": "¿Prefieres el verano o el invierno?" },
      hint: "Preferisci (do you prefer, tu) + l'estate + o (or) + l'inverno",
      tags: ["A1", "seasons", "chunks", "questions"],
      tier: 3,
      prerequisites: ["a117-t1-025", "a117-t1-027"],
    },
    {
      id: "a117-t3-105",
      type: "produce",
      prompt: "I like spring because it's warm.",
      accepted: [
        "Mi piace la primavera perché fa caldo.",
        "Mi piace la primavera perché fa caldo",
      ],
      prompts: { "es": "Me gusta la primavera porque hace calor." },
      hint: "Mi piace + la primavera + perché (because) + fa caldo",
      tags: ["A1", "seasons", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-024", "a117-t2-001"],
    },
    {
      id: "a117-t3-106",
      type: "produce",
      prompt: "There's a rainbow after the rain.",
      accepted: [
        "C'è un arcobaleno dopo la pioggia.",
        "C'è un arcobaleno dopo la pioggia",
      ],
      prompts: { "es": "Hay un arcoíris después de la lluvia." },
      hint: "C'è + un arcobaleno + dopo (after) + la pioggia",
      tags: ["A1", "weather", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-002", "a117-t1-150"],
    },
    {
      id: "a117-t3-107",
      type: "produce",
      prompt: "It's sunny. Let's go to the beach.",
      accepted: [
        "C'è il sole. Andiamo in spiaggia.",
        "C'è il sole. Andiamo in spiaggia",
      ],
      prompts: { "es": "Hay sol. Vamos a la playa." },
      hint: "C'è il sole + andiamo (let's go) + in spiaggia",
      tags: ["A1", "weather", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t2-006", "a117-t1-160"],
    },
    // ─── Tier 3 – Word-coverage additions seq 108–117 ─────────────────────────
    {
      id: "a117-t3-108",
      type: "produce",
      prompt: "In the mountains there is snow and ice.",
      accepted: [
        "In montagna c'è la neve e il ghiaccio.",
        "In montagna c'è la neve e il ghiaccio",
      ],
      prompts: { "es": "En las montañas hay nieve y hielo." },
      hint: "In montagna + c'è + la neve + e + il ghiaccio",
      tags: ["A1", "weather", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-003", "a117-t1-154"],
    },
    {
      id: "a117-t3-109",
      type: "produce",
      prompt: "The cloud covers the sun.",
      accepted: ["La nuvola copre il sole.", "La nuvola copre il sole"],
      prompts: { "es": "La nube cubre el sol." },
      hint: "La nuvola + copre (covers) + il sole",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-005"],
    },
    {
      id: "a117-t3-110",
      type: "produce",
      prompt: "I hear the thunder and I see the lightning.",
      accepted: [
        "Sento il tuono e vedo il fulmine.",
        "Sento il tuono e vedo il fulmine",
      ],
      prompts: { "es": "Oigo el trueno y veo el relámpago." },
      hint: "Sento (I hear) + il tuono + e + vedo (I see) + il fulmine",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-008", "a117-t1-009"],
    },
    {
      id: "a117-t3-111",
      type: "produce",
      prompt: "Today the sky is sunny and blue.",
      accepted: [
        "Oggi il cielo è soleggiato e blu.",
        "Oggi il cielo è soleggiato e blu",
      ],
      prompts: { "es": "Hoy el cielo está soleado y azul." },
      hint: "Oggi + il cielo è + soleggiato + e + blu",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-016"],
    },
    {
      id: "a117-t3-112",
      type: "produce",
      prompt: "The river is near the hill.",
      accepted: ["Il fiume è vicino alla collina.", "Il fiume è vicino alla collina"],
      prompts: { "es": "El río está cerca de la colina." },
      hint: "Il fiume + è vicino a (near) + la collina",
      tags: ["A1", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-020", "a117-t1-021"],
    },
    {
      id: "a117-t3-113",
      type: "produce",
      prompt: "The wood has many green trees.",
      accepted: ["Il bosco ha molti alberi verdi.", "Il bosco ha molti alberi verdi"],
      prompts: { "es": "El bosque tiene muchos árboles verdes." },
      hint: "Il bosco + ha (has) + molti alberi verdi",
      tags: ["A1", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-022"],
    },
    {
      id: "a117-t3-114",
      type: "produce",
      prompt: "The forest is near the sea.",
      accepted: ["La foresta è vicino al mare.", "La foresta è vicino al mare"],
      prompts: { "es": "El bosque está cerca del mar." },
      hint: "La foresta + è vicino al (near the) + mare",
      tags: ["A1", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-022", "a117-t1-018"],
    },
    {
      id: "a117-t3-115",
      type: "produce",
      prompt: "The flower near the tree is red.",
      accepted: [
        "Il fiore vicino all'albero è rosso.",
        "Il fiore vicino all'albero è rosso",
      ],
      prompts: { "es": "La flor cerca del árbol es roja." },
      hint: "Il fiore + vicino all'albero (near the tree) + è rosso",
      tags: ["A1", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-158", "a117-t1-156"],
    },
    {
      id: "a117-t3-116",
      type: "produce",
      prompt: "The sunset is orange, the dawn is pink.",
      accepted: [
        "Il tramonto è arancione, l'alba è rosa.",
        "Il tramonto è arancione, l'alba è rosa",
      ],
      prompts: { "es": "El atardecer es naranja, el amanecer es rosa." },
      hint: "Il tramonto + è arancione + l'alba + è rosa",
      tags: ["A1", "nature", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-166", "a117-t1-168"],
    },
    {
      id: "a117-t3-117",
      type: "produce",
      prompt: "There is hail and it's cold.",
      accepted: ["C'è la grandine e fa freddo.", "C'è la grandine e fa freddo"],
      prompts: { "es": "Hay granizo y hace frío." },
      hint: "C'è + la grandine + e + fa freddo",
      tags: ["A1", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-152", "a117-t2-002"],
    },
    // ─── Tier 3 – Context-rescue addition seq 118 ─────────────────────────────
    {
      id: "a117-t3-118",
      type: "produce",
      prompt: "The lake is calm today because there is no wind.",
      accepted: [
        "Il lago è calmo oggi perché non c'è vento.",
        "Il lago è calmo oggi perché non c'è vento",
      ],
      prompts: { "es": "El lago está tranquilo hoy porque no hay viento." },
      hint: "Il lago + è calmo + oggi + perché + non c'è vento",
      tags: ["A1", "nature", "weather", "chunks"],
      tier: 3,
      prerequisites: ["a117-t1-019", "a117-t2-006"],
    },
    // ─── Tier 4 – Sentences ────────────────────────────────────────────────────
    {
      id: "a117-t4-001",
      type: "produce",
      prompt: "Today the weather is bad. It's raining and it's cold.",
      accepted: [
        "Oggi il tempo è brutto. Piove e fa freddo.",
        "Oggi il tempo è brutto. Piove e fa freddo",
      ],
      prompts: { "es": "Hoy el tiempo está malo. Llueve y hace frío." },
      hint: "Oggi + il tempo è brutto + piove + e + fa freddo",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t2-002", "a117-t2-010"],
    },
    {
      id: "a117-t4-002",
      type: "produce",
      prompt: "In summer it's very hot in Rome.",
      accepted: [
        "In estate fa molto caldo a Roma.",
        "In estate fa molto caldo a Roma",
      ],
      prompts: { "es": "En verano hace mucho calor en Roma." },
      hint: "In estate + fa molto caldo + a Roma (use 'a' before city names)",
      tags: ["A1", "weather", "seasons", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t3-008"],
    },
    {
      id: "a117-t4-003",
      type: "produce",
      prompt: "Is it sunny? I want to go to the sea.",
      accepted: [
        "C'è il sole? Voglio andare al mare.",
        "C'è il sole? Voglio andare al mare",
      ],
      prompts: { "es": "¿Hay sol? Quiero ir al mar." },
      hint: "C'è il sole? + voglio (I want) + andare + al mare (al = a + il)",
      tags: ["A1", "weather", "nature", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t2-006", "a117-t1-018"],
    },
    {
      id: "a117-t4-004",
      type: "produce",
      prompt: "Today the sky is cloudy and there is fog.",
      accepted: [
        "Oggi il cielo è nuvoloso e c'è la nebbia.",
        "Oggi il cielo è nuvoloso e c'è la nebbia",
      ],
      prompts: { "es": "Hoy el cielo está nublado y hay niebla." },
      hint: "Oggi + il cielo è nuvoloso + e + c'è la nebbia",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-023", "a117-t1-006", "a117-t2-007"],
    },
    {
      id: "a117-t4-005",
      type: "produce",
      prompt: "Spring is my favourite season. It's warm and there are flowers.",
      accepted: [
        "La primavera è la mia stagione preferita. Fa caldo e ci sono i fiori.",
        "La primavera è la mia stagione preferita. Fa caldo e ci sono i fiori",
      ],
      prompts: { "es": "La primavera es mi estación favorita. Hace calor y hay flores." },
      hint: "La primavera è la mia stagione preferita + fa caldo + e + ci sono i fiori",
      tags: ["A1", "seasons", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-024", "a117-t2-001", "a117-t2-009"],
    },
    // ─── Tier 4 – Additional sentences seq 100–107 ────────────────────────────
    {
      id: "a117-t4-100",
      type: "produce",
      prompt: "In autumn the leaves are yellow and red.",
      accepted: [
        "In autunno le foglie sono gialle e rosse.",
        "In autunno le foglie sono gialle e rosse",
      ],
      prompts: { "es": "En otoño las hojas son amarillas y rojas." },
      hint: "In autunno + le foglie (leaves) + sono + gialle (f.pl) + e + rosse (f.pl)",
      tags: ["A1", "seasons", "nature", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-026"],
    },
    {
      id: "a117-t4-101",
      type: "produce",
      prompt: "I don't like fog because I can't see anything.",
      accepted: [
        "Non mi piace la nebbia perché non vedo niente.",
        "Non mi piace la nebbia perché non vedo niente",
      ],
      prompts: { "es": "No me gusta la niebla porque no veo nada." },
      hint: "Non mi piace + la nebbia + perché + non vedo (I don't see) + niente",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-006"],
    },
    {
      id: "a117-t4-102",
      type: "produce",
      prompt: "When it snows, the mountains are white.",
      accepted: [
        "Quando nevica, le montagne sono bianche.",
        "Quando nevica, le montagne sono bianche",
      ],
      prompts: { "es": "Cuando nieva, las montañas son blancas." },
      hint: "Quando (when) + nevica + le montagne + sono + bianche (white, f.pl)",
      tags: ["A1", "weather", "nature", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t2-011", "a117-t1-017"],
    },
    {
      id: "a117-t4-103",
      type: "produce",
      prompt: "In winter I don't want to go out because it's too cold.",
      accepted: [
        "In inverno non voglio uscire perché fa troppo freddo.",
        "In inverno non voglio uscire perché fa troppo freddo",
      ],
      prompts: { "es": "En invierno no quiero salir porque hace demasiado frío." },
      hint: "In inverno + non voglio + uscire (to go out) + perché + fa troppo freddo",
      tags: ["A1", "seasons", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-027", "a117-t2-002", "a117-t2-015"],
    },
    {
      id: "a117-t4-104",
      type: "fill_blank",
      prompt: "After the storm, there is always a rainbow. → Dopo il temporale, c'è sempre ___.",
      accepted: ["l'arcobaleno", "un arcobaleno"],
      hint: "After every storm (temporale) comes the rainbow",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-007", "a117-t1-150"],
    },
    {
      id: "a117-t4-105",
      type: "produce",
      prompt: "Today it's very windy. I can't go to the beach.",
      accepted: [
        "Oggi tira molto vento. Non posso andare in spiaggia.",
        "Oggi tira molto vento. Non posso andare in spiaggia",
      ],
      prompts: { "es": "Hoy hace mucho viento. No puedo ir a la playa." },
      hint: "Tira molto vento + non posso (I can't) + andare in spiaggia",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t2-012", "a117-t1-160"],
    },
    {
      id: "a117-t4-106",
      type: "produce",
      prompt: "The lake is beautiful in summer.",
      accepted: [
        "Il lago è bello in estate.",
        "Il lago è bello in estate",
      ],
      prompts: { "es": "El lago es bonito en verano." },
      hint: "Il lago + è bello (beautiful, m.sg.) + in estate",
      tags: ["A1", "nature", "seasons", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t1-019", "a117-t1-025"],
    },
    {
      id: "a117-t4-107",
      type: "produce",
      prompt: "It rains a lot in this city in winter.",
      accepted: [
        "Piove molto in questa città in inverno.",
        "Piove molto in questa città in inverno",
      ],
      prompts: { "es": "Llueve mucho en esta ciudad en invierno." },
      hint: "Piove molto + in questa (in this) + città + in inverno",
      tags: ["A1", "weather", "sentences"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a117-t2-010", "a117-t1-027"],
    },
    // ─── Tier 4 – Passage cloze (real 4-6 sentence mini-stories, seq 108–115) ──
    {
      id: "a117-t4-108",
      type: "passage_cloze",
      prompt: "Marco abita vicino al mare.\nOggi il cielo è azzurro e non ci sono nuvole.\nLui dice: «Che bella giornata! C'è il ___ e voglio nuotare.»\nPrende l'asciugamano e corre in spiaggia con gli amici.\nRestano al mare fino al tramonto.",
      accepted: ["sole"],
      hint: "The weather word for a clear, bright sky — what makes Marco want to swim",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t1-001", "a117-t1-018", "a117-t1-160"],
    },
    {
      id: "a117-t4-109",
      type: "passage_cloze",
      prompt: "Sono le otto di mattina e Anna esce di casa.\nIl cielo è grigio e ci sono molte nuvole.\nAnna guarda fuori e dice: «Oggi ___, prendo l'ombrello.»\nCammina fino alla fermata dell'autobus sotto la pioggia.\nArriva al lavoro un po' bagnata ma contenta.",
      accepted: ["piove"],
      hint: "The impersonal verb for rain — what the grey sky and umbrella tell you",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t2-010", "a117-t1-162"],
    },
    {
      id: "a117-t4-110",
      type: "passage_cloze",
      prompt: "In inverno, Luca va sempre in montagna con suo padre.\nQuando arrivano, il paesaggio è bianco e freddo.\nLuca dice: «Guarda, papà! ___ tanto qui!»\nMettono gli sci e scendono felici lungo la montagna.\nLa sera tornano a casa stanchi ma felici.",
      accepted: ["Nevica"],
      hint: "The impersonal verb for snow, capitalized — matches the white landscape",
      tags: ["A1", "weather", "seasons", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t2-011", "a117-t1-017", "a117-t1-027"],
    },
    {
      id: "a117-t4-111",
      type: "passage_cloze",
      prompt: "Oggi Sara vuole andare in spiaggia con la sua bicicletta.\nMa fuori tira molto ___ e le nuvole si muovono veloci.\nSara decide di restare a casa e legge un libro.\nDalla finestra guarda gli alberi: si muovono forte fuori.\nDomani, forse, c'è di nuovo il sole.",
      accepted: ["vento"],
      hint: "Follows 'tira' — the fixed expression for windy weather",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t2-012", "a117-t1-160"],
    },
    {
      id: "a117-t4-112",
      type: "passage_cloze",
      prompt: "Il signor Rossi guida verso l'ufficio molto presto la mattina.\nFuori c'è la ___ e non vede bene la strada.\nAccende le luci della macchina e guida piano piano.\nDopo dieci minuti il cielo si schiarisce e lui vede meglio.\nIl signor Rossi arriva al lavoro in orario.",
      accepted: ["nebbia"],
      hint: "Why he can't see the road well and turns on his lights",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t1-006", "a117-t1-023"],
    },
    {
      id: "a117-t4-113",
      type: "passage_cloze",
      prompt: "È una sera d'estate e Giulia è in giardino con il cane.\nAll'improvviso il cielo diventa scuro e il vento tira forte.\nGiulia sente un rumore forte: è il primo ___ della stagione.\nCorre dentro casa con il cane prima della pioggia.\nGuardano insieme il temporale dalla finestra.",
      accepted: ["tuono"],
      hint: "A loud sound you hear, not something you see like il fulmine",
      tags: ["A1", "weather", "seasons", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t1-008", "a117-t1-007", "a117-t1-025"],
    },
    {
      id: "a117-t4-114",
      type: "passage_cloze",
      prompt: "Siamo a gennaio e la temperatura è molto bassa in città.\nLa piccola Elena non vuole uscire di casa senza il cappotto.\nSua madre le dice: «Metti anche i guanti, oggi fa ___.»\nElena si veste bene e finalmente esce con la madre.\nCamminano insieme fino al parco vicino a casa.",
      accepted: ["freddo"],
      hint: "Why Elena needs a coat and gloves before going out in January",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t2-002"],
    },
    {
      id: "a117-t4-115",
      type: "passage_cloze",
      prompt: "Dopo tre giorni di pioggia, oggi il tempo cambia in fretta.\nLe nuvole vanno via e il sole torna a splendere.\nMarco guarda fuori dalla finestra e grida: «Guarda, mamma, un ___!»\nCorrono insieme in giardino per vederlo meglio.\nIl cielo è pieno di colori sopra le montagne.",
      accepted: ["arcobaleno"],
      hint: "What appears after rain when the sun comes back, full of colors",
      tags: ["A1", "weather", "passage_cloze"],
      tier: 4,
      prerequisites: ["a117-t1-002", "a117-t1-150", "a117-t2-006"],
    },
  ],
};

export default unit;
