import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-14-animals",
  name: "Animals",
  level: "A1",
  theme: "Animals & Nature Basics",
  emoji: "🐾",
  prerequisiteUnits: ["a1-unit-13-household"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: produce (22 original cards)
    // -------------------------------------------------------------------------
    {
      id: "a114-t1-001",
      type: "produce",
      prompt: "the cat",
      accepted: ["il gatto"],
      prompts: { "es": "el gato" },
      hint: "masculine noun — il gatto",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-002",
      type: "produce",
      prompt: "the dog",
      accepted: ["il cane"],
      prompts: { "es": "el perro" },
      hint: "masculine noun — il cane",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-003",
      type: "produce",
      prompt: "the horse",
      accepted: ["il cavallo"],
      prompts: { "es": "el caballo" },
      hint: "masculine noun — il cavallo",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-004",
      type: "produce",
      prompt: "the cow",
      accepted: ["la mucca"],
      prompts: { "es": "la vaca" },
      hint: "feminine noun — la mucca",
      tags: ["noun", "animal", "farm", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-005",
      type: "produce",
      prompt: "the pig",
      accepted: ["il maiale"],
      prompts: { "es": "el cerdo" },
      hint: "masculine noun — il maiale",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-006",
      type: "produce",
      prompt: "the chicken",
      accepted: ["il pollo"],
      prompts: { "es": "el pollo" },
      hint: "masculine noun — il pollo (also means chicken the food)",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-007",
      type: "produce",
      prompt: "the sheep",
      accepted: ["la pecora"],
      prompts: { "es": "la oveja" },
      hint: "feminine noun — la pecora",
      tags: ["noun", "animal", "farm", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-008",
      type: "produce",
      prompt: "the rabbit",
      accepted: ["il coniglio"],
      prompts: { "es": "el conejo" },
      hint: "masculine noun — il coniglio",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-009",
      type: "produce",
      prompt: "the mouse",
      accepted: ["il topo"],
      prompts: { "es": "el ratón" },
      hint: "masculine noun — il topo",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-010",
      type: "produce",
      prompt: "the bird",
      accepted: ["l'uccello"],
      prompts: { "es": "el pájaro" },
      hint: "masculine noun — l'uccello (elided article before vowel)",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-011",
      type: "produce",
      prompt: "the fish",
      accepted: ["il pesce"],
      prompts: { "es": "el pez" },
      hint: "masculine noun — il pesce",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-012",
      type: "produce",
      prompt: "the snake",
      accepted: ["il serpente"],
      prompts: { "es": "la serpiente" },
      hint: "masculine noun — il serpente",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-013",
      type: "produce",
      prompt: "the frog",
      accepted: ["la rana"],
      prompts: { "es": "la rana" },
      hint: "feminine noun — la rana",
      tags: ["noun", "animal", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-014",
      type: "produce",
      prompt: "the butterfly",
      accepted: ["la farfalla"],
      prompts: { "es": "la mariposa" },
      hint: "feminine noun — la farfalla",
      tags: ["noun", "animal", "insect", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-015",
      type: "produce",
      prompt: "the bee",
      accepted: ["l'ape"],
      prompts: { "es": "la abeja" },
      hint: "feminine noun — l'ape (elided article before vowel)",
      tags: ["noun", "animal", "insect", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-016",
      type: "produce",
      prompt: "the lion",
      accepted: ["il leone"],
      prompts: { "es": "el león" },
      hint: "masculine noun — il leone",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-017",
      type: "produce",
      prompt: "the bear",
      accepted: ["l'orso"],
      prompts: { "es": "el oso" },
      hint: "masculine noun — l'orso (elided article before vowel)",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-018",
      type: "produce",
      prompt: "the wolf",
      accepted: ["il lupo"],
      prompts: { "es": "el lobo" },
      hint: "masculine noun — il lupo",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-019",
      type: "produce",
      prompt: "the fox",
      accepted: ["la volpe"],
      prompts: { "es": "el zorro" },
      hint: "feminine noun — la volpe",
      tags: ["noun", "animal", "wild", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-020",
      type: "produce",
      prompt: "the elephant",
      accepted: ["l'elefante"],
      prompts: { "es": "el elefante" },
      hint: "masculine noun — l'elefante (elided article before vowel)",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-021",
      type: "produce",
      prompt: "the monkey",
      accepted: ["la scimmia"],
      prompts: { "es": "el mono" },
      hint: "feminine noun — la scimmia",
      tags: ["noun", "animal", "wild", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-022",
      type: "produce",
      prompt: "the dolphin",
      accepted: ["il delfino"],
      prompts: { "es": "el delfín" },
      hint: "masculine noun — il delfino",
      tags: ["noun", "animal", "sea", "masculine", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: recognize — existing vocab (seq 100–121)
    // -------------------------------------------------------------------------
    {
      id: "a114-t1-100",
      type: "recognize",
      prompt: "il gatto",
      accepted: ["cat"],
      translations: { "es": ["gato"] },
      hint: "think of 'tabby' — the classic Italian pet",
      tags: ["noun", "animal", "pet", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-101",
      type: "recognize",
      prompt: "il cane",
      accepted: ["dog"],
      translations: { "es": ["perro"] },
      hint: "think of 'canine'",
      tags: ["noun", "animal", "pet", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-102",
      type: "recognize",
      prompt: "il cavallo",
      accepted: ["horse"],
      translations: { "es": ["caballo"] },
      hint: "think of 'cavalry' — soldiers on horses",
      tags: ["noun", "animal", "farm", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-103",
      type: "recognize",
      prompt: "la mucca",
      accepted: ["cow"],
      translations: { "es": ["vaca"] },
      hint: "feminine noun — common farm animal",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-104",
      type: "recognize",
      prompt: "il maiale",
      accepted: ["pig"],
      translations: { "es": ["cerdo"] },
      hint: "Italian pig — also means pork (the meat)",
      tags: ["noun", "animal", "farm", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-105",
      type: "recognize",
      prompt: "il pollo",
      accepted: ["chicken"],
      translations: { "es": ["pollo"] },
      hint: "pollo is both the animal and the meat",
      tags: ["noun", "animal", "farm", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-106",
      type: "recognize",
      prompt: "la pecora",
      accepted: ["sheep"],
      translations: { "es": ["oveja"] },
      hint: "pecorino cheese comes from sheep's milk",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-107",
      type: "recognize",
      prompt: "il coniglio",
      accepted: ["rabbit"],
      translations: { "es": ["conejo"] },
      hint: "Italian rabbit — also a popular meat dish",
      tags: ["noun", "animal", "pet", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-108",
      type: "recognize",
      prompt: "il topo",
      accepted: ["mouse", "rat"],
      translations: { "es": ["ratón", "rata"] },
      hint: "Italian mouse — also used informally for rat",
      tags: ["noun", "animal", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-109",
      type: "recognize",
      prompt: "l'uccello",
      accepted: ["bird"],
      translations: { "es": ["pájaro"] },
      hint: "elided article before vowel — l'uccello",
      tags: ["noun", "animal", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-110",
      type: "recognize",
      prompt: "il pesce",
      accepted: ["fish"],
      translations: { "es": ["pez"] },
      hint: "think of Pisces — the zodiac fish sign",
      tags: ["noun", "animal", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-111",
      type: "recognize",
      prompt: "il serpente",
      accepted: ["snake"],
      translations: { "es": ["serpiente"] },
      hint: "cognate with 'serpent'",
      tags: ["noun", "animal", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-112",
      type: "recognize",
      prompt: "la rana",
      accepted: ["frog"],
      translations: { "es": ["rana"] },
      hint: "Italian frog — Kermit is 'Kermit la rana'",
      tags: ["noun", "animal", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-113",
      type: "recognize",
      prompt: "la farfalla",
      accepted: ["butterfly"],
      translations: { "es": ["mariposa"] },
      hint: "a beautiful word for a beautiful insect",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-114",
      type: "recognize",
      prompt: "l'ape",
      accepted: ["bee"],
      translations: { "es": ["abeja"] },
      hint: "think of 'apiary' — a place where bees are kept",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-115",
      type: "recognize",
      prompt: "il leone",
      accepted: ["lion"],
      translations: { "es": ["león"] },
      hint: "cognate — think 'leonine' (lion-like)",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-116",
      type: "recognize",
      prompt: "l'orso",
      accepted: ["bear"],
      translations: { "es": ["oso"] },
      hint: "think of 'ursine' or the Ursa Major constellation",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-117",
      type: "recognize",
      prompt: "il lupo",
      accepted: ["wolf"],
      translations: { "es": ["lobo"] },
      hint: "think of 'lupine' (wolf-like)",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-118",
      type: "recognize",
      prompt: "la volpe",
      accepted: ["fox"],
      translations: { "es": ["zorro"] },
      hint: "the cunning fox of Italian fables",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-119",
      type: "recognize",
      prompt: "l'elefante",
      accepted: ["elephant"],
      translations: { "es": ["elefante"] },
      hint: "near-cognate — one of the largest land animals",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-120",
      type: "recognize",
      prompt: "la scimmia",
      accepted: ["monkey"],
      translations: { "es": ["mono"] },
      hint: "Italian monkey — feminine noun ending in -ia",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-121",
      type: "recognize",
      prompt: "il delfino",
      accepted: ["dolphin"],
      translations: { "es": ["delfín"] },
      hint: "think of 'Delphinus' — the dolphin constellation",
      tags: ["noun", "animal", "sea", "masculine", "A1", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: additional animals, produce (seq 150–161)
    // -------------------------------------------------------------------------
    {
      id: "a114-t1-150",
      type: "produce",
      prompt: "the duck",
      accepted: ["l'anatra"],
      prompts: { "es": "el pato" },
      hint: "feminine noun — l'anatra (elided article before vowel)",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-151",
      type: "produce",
      prompt: "the goat",
      accepted: ["la capra"],
      prompts: { "es": "la cabra" },
      hint: "feminine noun — la capra",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-152",
      type: "produce",
      prompt: "the rooster",
      accepted: ["il gallo"],
      prompts: { "es": "el gallo" },
      hint: "masculine noun — il gallo; the female is la gallina",
      tags: ["noun", "animal", "farm", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-153",
      type: "produce",
      prompt: "the deer",
      accepted: ["il cervo"],
      prompts: { "es": "el ciervo" },
      hint: "masculine noun — il cervo",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-154",
      type: "produce",
      prompt: "the turtle",
      accepted: ["la tartaruga"],
      prompts: { "es": "la tortuga" },
      hint: "feminine noun — la tartaruga",
      tags: ["noun", "animal", "pet", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-155",
      type: "produce",
      prompt: "the spider",
      accepted: ["il ragno"],
      prompts: { "es": "la araña" },
      hint: "masculine noun — il ragno",
      tags: ["noun", "animal", "insect", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-156",
      type: "produce",
      prompt: "the parrot",
      accepted: ["il pappagallo"],
      prompts: { "es": "el loro" },
      hint: "masculine noun — il pappagallo",
      tags: ["noun", "animal", "pet", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-157",
      type: "produce",
      prompt: "the tiger",
      accepted: ["la tigre"],
      prompts: { "es": "el tigre" },
      hint: "feminine noun — la tigre",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-158",
      type: "produce",
      prompt: "the giraffe",
      accepted: ["la giraffa"],
      prompts: { "es": "la jirafa" },
      hint: "feminine noun — la giraffa",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-159",
      type: "produce",
      prompt: "the ant",
      accepted: ["la formica"],
      prompts: { "es": "la hormiga" },
      hint: "feminine noun — la formica",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-160",
      type: "produce",
      prompt: "the fly",
      accepted: ["la mosca"],
      prompts: { "es": "la mosca" },
      hint: "feminine noun — la mosca",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-161",
      type: "produce",
      prompt: "the goose",
      accepted: ["l'oca"],
      prompts: { "es": "el ganso" },
      hint: "feminine noun — l'oca (elided article before vowel)",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: additional animals, recognize (seq 162–173)
    // -------------------------------------------------------------------------
    {
      id: "a114-t1-162",
      type: "recognize",
      prompt: "l'anatra",
      accepted: ["duck"],
      translations: { "es": ["pato"] },
      hint: "the farm bird that quacks — feminine noun",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-163",
      type: "recognize",
      prompt: "la capra",
      accepted: ["goat"],
      translations: { "es": ["cabra"] },
      hint: "think of 'Capricorn' — the goat zodiac sign",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-164",
      type: "recognize",
      prompt: "il gallo",
      accepted: ["rooster", "cock"],
      translations: { "es": ["gallo"] },
      hint: "the male chicken that crows in the morning",
      tags: ["noun", "animal", "farm", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-165",
      type: "recognize",
      prompt: "il cervo",
      accepted: ["deer", "stag"],
      translations: { "es": ["ciervo"] },
      hint: "think of 'cervine' (deer-like)",
      tags: ["noun", "animal", "wild", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-166",
      type: "recognize",
      prompt: "la tartaruga",
      accepted: ["turtle", "tortoise"],
      translations: { "es": ["tortuga"] },
      hint: "Italian uses one word for both turtle and tortoise",
      tags: ["noun", "animal", "pet", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-167",
      type: "recognize",
      prompt: "il ragno",
      accepted: ["spider"],
      translations: { "es": ["araña"] },
      hint: "think of 'arachnid' — the eight-legged creature",
      tags: ["noun", "animal", "insect", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-168",
      type: "recognize",
      prompt: "il pappagallo",
      accepted: ["parrot"],
      translations: { "es": ["loro"] },
      hint: "the colourful talking bird — sounds like babbling",
      tags: ["noun", "animal", "pet", "masculine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-169",
      type: "recognize",
      prompt: "la tigre",
      accepted: ["tiger"],
      translations: { "es": ["tigre"] },
      hint: "near-cognate — feminine noun despite the -e ending",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-170",
      type: "recognize",
      prompt: "la giraffa",
      accepted: ["giraffe"],
      translations: { "es": ["jirafa"] },
      hint: "cognate — the tallest land animal",
      tags: ["noun", "animal", "wild", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-171",
      type: "recognize",
      prompt: "la formica",
      accepted: ["ant"],
      translations: { "es": ["hormiga"] },
      hint: "think of 'formic acid' produced by ants",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-172",
      type: "recognize",
      prompt: "la mosca",
      accepted: ["fly"],
      translations: { "es": ["mosca"] },
      hint: "the buzzing insect — also the Italian name for Moscow",
      tags: ["noun", "animal", "insect", "feminine", "A1", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-173",
      type: "recognize",
      prompt: "l'oca",
      accepted: ["goose"],
      translations: { "es": ["ganso"] },
      hint: "elided article before vowel — l'oca",
      tags: ["noun", "animal", "farm", "feminine", "A1", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Fill-in-the-blank: favourite animal + verb collocations
    // -------------------------------------------------------------------------
    {
      id: "a114-t2-001",
      type: "fill_blank",
      prompt: "Il mio animale preferito è ___.",
      accepted: [
        "il gatto",
        "il cane",
        "il cavallo",
        "la mucca",
        "il maiale",
        "il pollo",
        "la pecora",
        "il coniglio",
        "il topo",
        "l'uccello",
        "il pesce",
        "il serpente",
        "la rana",
        "la farfalla",
        "l'ape",
        "il leone",
        "l'orso",
        "il lupo",
        "la volpe",
        "l'elefante",
        "la scimmia",
        "il delfino",
      ],
      hint: "name any animal with its article — e.g. il gatto, la volpe",
      tags: ["fill_blank", "animal", "favourite", "tier2"],
      tier: 2,
      prerequisites: [
        "a114-t1-001",
        "a114-t1-002",
        "a114-t1-003",
        "a114-t1-016",
        "a114-t1-019",
      ],
    },
    {
      id: "a114-t2-002",
      type: "fill_blank",
      prompt: "Il cane ___. (barks)",
      accepted: ["abbaia"],
      hint: "abbaiare = to bark — 3rd person singular: abbaia",
      tags: ["fill_blank", "animal", "verb-collocation", "abbaiare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-002"],
    },
    {
      id: "a114-t2-003",
      type: "fill_blank",
      prompt: "Il gatto ___. (meows)",
      accepted: ["miagola"],
      hint: "miagolare = to meow — 3rd person singular: miagola",
      tags: ["fill_blank", "animal", "verb-collocation", "miagolare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t2-004",
      type: "fill_blank",
      prompt: "L'uccello ___. (sings)",
      accepted: ["canta"],
      hint: "cantare = to sing — 3rd person singular: canta",
      tags: ["fill_blank", "animal", "verb-collocation", "cantare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-010"],
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Grammar: more animal sounds, plural formation, mi piace (seq 100–113)
    // -------------------------------------------------------------------------
    {
      id: "a114-t2-100",
      type: "fill_blank",
      prompt: "Il cavallo ___. (neighs)",
      accepted: ["nitrisce"],
      hint: "nitrire = to neigh — 3rd person singular: nitrisce",
      tags: ["fill_blank", "animal", "verb-collocation", "nitrire", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-003"],
    },
    {
      id: "a114-t2-101",
      type: "fill_blank",
      prompt: "La mucca ___. (moos)",
      accepted: ["muggisce"],
      hint: "muggire = to moo — 3rd person singular: muggisce",
      tags: ["fill_blank", "animal", "verb-collocation", "muggire", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-004"],
    },
    {
      id: "a114-t2-102",
      type: "fill_blank",
      prompt: "La pecora ___. (bleats)",
      accepted: ["bela"],
      hint: "belare = to bleat — 3rd person singular: bela",
      tags: ["fill_blank", "animal", "verb-collocation", "belare", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-007"],
    },
    {
      id: "a114-t2-103",
      type: "fill_blank",
      prompt: "L'ape ___. (buzzes)",
      accepted: ["ronza"],
      hint: "ronzare = to buzz — 3rd person singular: ronza",
      tags: ["fill_blank", "animal", "verb-collocation", "ronzare", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-015"],
    },
    {
      id: "a114-t2-104",
      type: "fill_blank",
      prompt: "Un gatto, due ___. (plural)",
      accepted: ["gatti"],
      hint: "-o → -i in the plural for most masculine nouns",
      tags: ["fill_blank", "animal", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t2-105",
      type: "fill_blank",
      prompt: "Una pecora, due ___. (plural)",
      accepted: ["pecore"],
      hint: "-a → -e in the plural for most feminine nouns",
      tags: ["fill_blank", "animal", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-007"],
    },
    {
      id: "a114-t2-106",
      type: "fill_blank",
      prompt: "Un pesce, due ___. (plural)",
      accepted: ["pesci"],
      hint: "-e → -i in the plural for nouns ending in -e",
      tags: ["fill_blank", "animal", "plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-011"],
    },
    {
      id: "a114-t2-107",
      type: "fill_blank",
      prompt: "Una mucca, due ___. (plural)",
      accepted: ["mucche"],
      hint: "-ca → -che to keep the hard 'k' sound in the plural",
      tags: ["fill_blank", "animal", "plural", "irregular-plural", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-004"],
    },
    {
      id: "a114-t2-108",
      type: "fill_blank",
      prompt: "Mi ___ i cani. (I like dogs — plural subject)",
      accepted: ["piacciono"],
      hint: "mi piacciono = I like — piacciono for plural subjects",
      tags: ["fill_blank", "animal", "mi-piace", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-002"],
    },
    {
      id: "a114-t2-109",
      type: "fill_blank",
      prompt: "Mi ___ il gatto. (I like the cat — singular subject)",
      accepted: ["piace"],
      hint: "mi piace = I like — piace for singular subjects",
      tags: ["fill_blank", "animal", "mi-piace", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t2-110",
      type: "fill_blank",
      prompt: "A Maria ___ i cavalli. (Maria likes horses)",
      accepted: ["piacciono"],
      hint: "a Maria piacciono = Maria likes — piacciono for plural subjects",
      tags: ["fill_blank", "animal", "mi-piace", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-003"],
    },
    {
      id: "a114-t2-111",
      type: "fill_blank",
      prompt: "Non mi ___ i serpenti. (I don't like snakes)",
      accepted: ["piacciono"],
      hint: "non mi piacciono = I don't like — piacciono for plural subjects",
      tags: ["fill_blank", "animal", "mi-piace", "negation", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-012"],
    },
    {
      id: "a114-t2-112",
      type: "fill_blank",
      prompt: "Il gatto è ___. (black — masc. singular)",
      accepted: ["nero"],
      hint: "nero = black, masculine singular — adjectives agree with the noun",
      tags: ["fill_blank", "animal", "adjective-agreement", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t2-113",
      type: "fill_blank",
      prompt: "La volpe è ___. (intelligent — fem. singular)",
      accepted: ["intelligente"],
      hint: "intelligente ends in -e: same form for masc. and fem.",
      tags: ["fill_blank", "animal", "adjective-agreement", "A1", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-019"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — English to Italian: full sentences
    // -------------------------------------------------------------------------
    {
      id: "a114-t3-001",
      type: "produce",
      prompt: "I have a cat and a dog.",
      accepted: [
        "Ho un gatto e un cane.",
        "Ho un gatto e un cane",
      ],
      prompts: { "es": "Tengo un gato y un perro." },
      hint: "avere = to have; ho = I have; un = a (masculine)",
      tags: ["sentence", "animal", "pet", "avere", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-001", "a114-t1-002"],
    },
    {
      id: "a114-t3-002",
      type: "produce",
      prompt: "The horse is big and beautiful.",
      accepted: [
        "Il cavallo è grande e bello.",
        "Il cavallo è grande e bello",
        "Il cavallo è bello e grande.",
        "Il cavallo è bello e grande",
      ],
      prompts: { "es": "El caballo es grande y bonito." },
      hint: "grande = big; bello = beautiful; è = is",
      tags: ["sentence", "animal", "farm", "adjective", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-003"],
    },
    {
      id: "a114-t3-003",
      type: "produce",
      prompt: "She's afraid of snakes.",
      accepted: [
        "Lei ha paura dei serpenti.",
        "Ha paura dei serpenti.",
        "Lei ha paura dei serpenti",
        "Ha paura dei serpenti",
      ],
      prompts: { "es": "Ella tiene miedo de las serpientes." },
      hint: "avere paura di = to be afraid of; dei serpenti = of snakes (plural)",
      tags: ["sentence", "animal", "fear", "avere-paura", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-012"],
    },
    {
      id: "a114-t3-004",
      type: "produce",
      prompt: "Bees make honey.",
      accepted: [
        "Le api fanno il miele.",
        "Le api fanno il miele",
        "Le api producono il miele.",
        "Le api producono il miele",
      ],
      prompts: { "es": "Las abejas hacen miel." },
      hint: "le api = the bees (plural of l'ape); fanno = they make (fare); il miele = the honey",
      tags: ["sentence", "animal", "insect", "fare", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-015"],
    },
    {
      id: "a114-t3-005",
      type: "produce",
      prompt: "The dolphin swims in the sea.",
      accepted: [
        "Il delfino nuota nel mare.",
        "Il delfino nuota nel mare",
        "Il delfino nuota in mare.",
        "Il delfino nuota in mare",
      ],
      prompts: { "es": "El delfín nada en el mar." },
      hint: "nuotare = to swim; nel mare = in the sea",
      tags: ["sentence", "animal", "sea", "nuotare", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-022"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Phrases and sentences: additional (seq 100–113)
    // -------------------------------------------------------------------------
    {
      id: "a114-t3-100",
      type: "produce",
      prompt: "Do you have a pet?",
      accepted: [
        "Hai un animale domestico?",
        "Hai un animale domestico",
      ],
      prompts: { "es": "¿Tienes una mascota?" },
      hint: "hai = you have (tu); animale domestico = pet",
      tags: ["sentence", "animal", "pet", "avere", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a114-t3-101",
      type: "produce",
      prompt: "I like cats more than dogs.",
      accepted: [
        "Mi piacciono i gatti più dei cani.",
        "Mi piacciono i gatti più dei cani",
      ],
      prompts: { "es": "Me gustan más los gatos que los perros." },
      hint: "mi piacciono = I like (plural subject); più dei cani = more than dogs",
      tags: ["sentence", "animal", "pet", "mi-piace", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-001", "a114-t1-002"],
    },
    {
      id: "a114-t3-102",
      type: "produce",
      prompt: "What is your favourite animal?",
      accepted: [
        "Qual è il tuo animale preferito?",
        "Qual è il tuo animale preferito",
      ],
      prompts: { "es": "¿Cuál es tu animal favorito?" },
      hint: "Qual è = What is; il tuo = your (masc.); preferito = favourite",
      tags: ["sentence", "animal", "question", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a114-t3-103",
      type: "produce",
      prompt: "The wolf howls at night.",
      accepted: [
        "Il lupo ulula di notte.",
        "Il lupo ulula di notte",
      ],
      prompts: { "es": "El lobo aúlla de noche." },
      hint: "ululare = to howl; ulula = 3rd person singular; di notte = at night",
      tags: ["sentence", "animal", "wild", "ululare", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-018"],
    },
    {
      id: "a114-t3-104",
      type: "produce",
      prompt: "There are two cats in the garden.",
      accepted: [
        "Ci sono due gatti in giardino.",
        "Ci sono due gatti in giardino",
      ],
      prompts: { "es": "Hay dos gatos en el jardín." },
      hint: "Ci sono = There are; in giardino = in the garden",
      tags: ["sentence", "animal", "pet", "ci-sono", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t3-105",
      type: "produce",
      prompt: "My dog is very friendly.",
      accepted: [
        "Il mio cane è molto simpatico.",
        "Il mio cane è molto simpatico",
      ],
      prompts: { "es": "Mi perro es muy simpático." },
      hint: "il mio cane = my dog; molto = very; simpatico = friendly",
      tags: ["sentence", "animal", "pet", "adjective", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-002"],
    },
    {
      id: "a114-t3-106",
      type: "produce",
      prompt: "The bird flies above the trees.",
      accepted: [
        "L'uccello vola sopra gli alberi.",
        "L'uccello vola sopra gli alberi",
      ],
      prompts: { "es": "El pájaro vuela sobre los árboles." },
      hint: "volare = to fly; vola = 3rd person singular; sopra = above",
      tags: ["sentence", "animal", "volare", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-010"],
    },
    {
      id: "a114-t3-107",
      type: "produce",
      prompt: "The lion is the king of animals.",
      accepted: [
        "Il leone è il re degli animali.",
        "Il leone è il re degli animali",
      ],
      prompts: { "es": "El león es el rey de los animales." },
      hint: "il re = the king; degli animali = of the animals (di + gli)",
      tags: ["sentence", "animal", "wild", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-016"],
    },
    {
      id: "a114-t3-108",
      type: "produce",
      prompt: "Monkeys live in the trees.",
      accepted: [
        "Le scimmie vivono sugli alberi.",
        "Le scimmie vivono sugli alberi",
      ],
      prompts: { "es": "Los monos viven en los árboles." },
      hint: "le scimmie = monkeys (plural fem.); vivono = they live; sugli alberi = in the trees",
      tags: ["sentence", "animal", "wild", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-021"],
    },
    {
      id: "a114-t3-109",
      type: "produce",
      prompt: "I have a rabbit and a turtle.",
      accepted: [
        "Ho un coniglio e una tartaruga.",
        "Ho un coniglio e una tartaruga",
      ],
      prompts: { "es": "Tengo un conejo y una tortuga." },
      hint: "ho = I have; un = a (masc.); una = a (fem.)",
      tags: ["sentence", "animal", "pet", "avere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-008", "a114-t1-154"],
    },
    {
      id: "a114-t3-110",
      type: "produce",
      prompt: "How many animals are there in the zoo?",
      accepted: [
        "Quanti animali ci sono allo zoo?",
        "Quanti animali ci sono allo zoo",
      ],
      prompts: { "es": "¿Cuántos animales hay en el zoológico?" },
      hint: "Quanti = How many (masc. plural); allo zoo = at the zoo",
      tags: ["sentence", "animal", "question", "ci-sono", "A1", "tier3"],
      tier: 3,
    },
    {
      id: "a114-t3-111",
      type: "produce",
      prompt: "The cat sleeps all day.",
      accepted: [
        "Il gatto dorme tutto il giorno.",
        "Il gatto dorme tutto il giorno",
      ],
      prompts: { "es": "El gato duerme todo el día." },
      hint: "dormire = to sleep; dorme = 3rd person singular; tutto il giorno = all day",
      tags: ["sentence", "animal", "pet", "dormire", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t3-112",
      type: "produce",
      prompt: "The parrot says hello.",
      accepted: [
        "Il pappagallo dice ciao.",
        "Il pappagallo dice ciao",
      ],
      prompts: { "es": "El loro dice hola." },
      hint: "dire = to say; dice = 3rd person singular; ciao = hello",
      tags: ["sentence", "animal", "pet", "dire", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-156"],
    },
    {
      id: "a114-t3-113",
      type: "produce",
      prompt: "The bear lives in the forest.",
      accepted: [
        "L'orso vive nel bosco.",
        "L'orso vive nel bosco",
      ],
      prompts: { "es": "El oso vive en el bosque." },
      hint: "vivere = to live; vive = 3rd person singular; nel bosco = in the forest",
      tags: ["sentence", "animal", "wild", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-017"],
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Passage cloze: fable scene
    // -------------------------------------------------------------------------
    {
      id: "a114-t4-001",
      type: "passage_cloze",
      prompt: "Nel bosco vivono molti animali. La volpe è furba e veloce.\nL'orso è grande e forte. Ma il più piccolo di tutti è il ___,\nche vive vicino al fiume e salta da una pietra all'altra tutto il giorno.",
      accepted: ["ranocchio", "la rana", "rana"],
      hint: "a small jumping amphibian that lives near water — feminine noun",
      tags: ["passage_cloze", "animal", "nature", "fable", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-013", // la rana
        "a114-t1-017", // l'orso
        "a114-t1-019", // la volpe
      ],
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Sentences and passages: additional (seq 100–111)
    // -------------------------------------------------------------------------
    {
      id: "a114-t4-100",
      type: "produce",
      prompt: "The dog plays in the garden.",
      accepted: [
        "Il cane gioca in giardino.",
        "Il cane gioca in giardino",
      ],
      prompts: { "es": "El perro juega en el jardín." },
      hint: "giocare = to play; gioca = 3rd person singular; in giardino = in the garden",
      tags: ["sentence", "animal", "pet", "giocare", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-002"],
    },
    {
      id: "a114-t4-101",
      type: "produce",
      prompt: "My cat is black and white.",
      accepted: [
        "Il mio gatto è nero e bianco.",
        "Il mio gatto è nero e bianco",
        "Il mio gatto è bianco e nero.",
        "Il mio gatto è bianco e nero",
      ],
      prompts: { "es": "Mi gato es negro y blanco." },
      hint: "il mio gatto = my cat; nero = black; bianco = white (both masculine)",
      tags: ["sentence", "animal", "pet", "adjective", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t4-102",
      type: "fill_blank",
      prompt: "Il ___ è il re degli animali.",
      accepted: ["leone"],
      hint: "the king of the jungle — without the article",
      tags: ["fill_blank", "animal", "wild", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-016"],
    },
    {
      id: "a114-t4-103",
      type: "produce",
      prompt: "My sister has a small rabbit.",
      accepted: [
        "Mia sorella ha un coniglio piccolo.",
        "Mia sorella ha un coniglio piccolo",
        "Mia sorella ha un piccolo coniglio.",
        "Mia sorella ha un piccolo coniglio",
      ],
      prompts: { "es": "Mi hermana tiene un conejo pequeño." },
      hint: "mia sorella = my sister; ha = she has; piccolo = small (masc.)",
      tags: ["sentence", "animal", "pet", "avere", "family", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-008"],
    },
    {
      id: "a114-t4-104",
      type: "produce",
      prompt: "There is a big fish in the lake.",
      accepted: [
        "C'è un pesce grande nel lago.",
        "C'è un pesce grande nel lago",
        "C'è un grande pesce nel lago.",
        "C'è un grande pesce nel lago",
      ],
      prompts: { "es": "Hay un pez grande en el lago." },
      hint: "c'è = there is; nel lago = in the lake",
      tags: ["sentence", "animal", "nature", "ce-e", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-011"],
    },
    {
      id: "a114-t4-105",
      type: "produce",
      prompt: "The elephant has a very long nose.",
      accepted: [
        "L'elefante ha un naso molto lungo.",
        "L'elefante ha un naso molto lungo",
      ],
      prompts: { "es": "El elefante tiene una trompa muy larga." },
      hint: "il naso = the nose; molto = very; lungo = long (masculine)",
      tags: ["sentence", "animal", "wild", "avere", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-020"],
    },
    {
      id: "a114-t4-106",
      type: "passage_cloze",
      prompt: "Marco va allo zoo con la sua famiglia. Prima vedono i leoni e i lupi.\nPoi c'è una vasca grande dove nuota un ___ grigio e intelligente.\nMarco vuole tornare domani.",
      accepted: ["delfino"],
      hint: "a highly intelligent grey sea mammal — il delfino",
      tags: ["passage_cloze", "animal", "zoo", "sea", "A1", "tier4"],
      tier: 4,
      prerequisites: ["a114-t1-022", "a114-t1-016", "a114-t1-018"],
    },
    {
      id: "a114-t4-107",
      type: "produce",
      prompt: "In the forest there are wolves and foxes.",
      accepted: [
        "Nel bosco ci sono lupi e volpi.",
        "Nel bosco ci sono lupi e volpi",
      ],
      prompts: { "es": "En el bosque hay lobos y zorros." },
      hint: "nel bosco = in the forest; lupi = wolves (plural); volpi = foxes (plural)",
      tags: ["sentence", "animal", "wild", "ci-sono", "plural", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-018", "a114-t1-019"],
    },
    {
      id: "a114-t4-108",
      type: "produce",
      prompt: "My favourite animal is the dolphin.",
      accepted: [
        "Il mio animale preferito è il delfino.",
        "Il mio animale preferito è il delfino",
      ],
      prompts: { "es": "Mi animal favorito es el delfín." },
      hint: "animale preferito = favourite animal; il mio = my (masculine)",
      tags: ["sentence", "animal", "sea", "preferito", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-022"],
    },
    {
      id: "a114-t4-109",
      type: "produce",
      prompt: "The tiger is big and dangerous.",
      accepted: [
        "La tigre è grande e pericolosa.",
        "La tigre è grande e pericolosa",
        "La tigre è pericolosa e grande.",
        "La tigre è pericolosa e grande",
      ],
      prompts: { "es": "El tigre es grande y peligroso." },
      hint: "pericolosa = dangerous (feminine, agrees with la tigre)",
      tags: ["sentence", "animal", "wild", "adjective", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-157"],
    },
    {
      id: "a114-t4-110",
      type: "fill_blank",
      prompt: "Il gatto ha quattro ___. (legs/paws)",
      accepted: ["zampe"],
      hint: "zampe = animal legs/paws — animals have zampe, people have gambe",
      tags: ["fill_blank", "animal", "body-parts", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t4-111",
      type: "produce",
      prompt: "The goat eats grass in the field.",
      accepted: [
        "La capra mangia l'erba nel campo.",
        "La capra mangia l'erba nel campo",
        "La capra mangia erba nel campo.",
        "La capra mangia erba nel campo",
      ],
      prompts: { "es": "La cabra come hierba en el campo." },
      hint: "mangiare = to eat; mangia = 3rd person singular; nel campo = in the field",
      tags: ["sentence", "animal", "farm", "mangiare", "A1", "tier4"],
      tier: 4,
      deprecated: true,
      prerequisites: ["a114-t1-151"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Sentences: closing word-isolation gaps (seq 114–119)
    // -------------------------------------------------------------------------
    {
      id: "a114-t3-114",
      type: "produce",
      prompt: "The duck swims in the pond every morning.",
      accepted: [
        "L'anatra nuota nello stagno ogni mattina.",
        "L'anatra nuota nello stagno ogni mattina",
      ],
      prompts: { "es": "El pato nada en el estanque cada mañana." },
      hint: "nello stagno = in the pond (in + lo); ogni mattina = every morning",
      tags: ["sentence", "animal", "farm", "nuotare", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-150"],
    },
    {
      id: "a114-t3-115",
      type: "produce",
      prompt: "The giraffe and the deer live at the zoo.",
      accepted: [
        "La giraffa e il cervo vivono allo zoo.",
        "La giraffa e il cervo vivono allo zoo",
      ],
      prompts: { "es": "La jirafa y el ciervo viven en el zoológico." },
      hint: "vivono = they live (vivere); allo zoo = at the zoo (a + lo)",
      tags: ["sentence", "animal", "wild", "zoo", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-158", "a114-t1-153"],
    },
    {
      id: "a114-t3-116",
      type: "produce",
      prompt: "The spider makes a web in the corner.",
      accepted: [
        "Il ragno fa una ragnatela nell'angolo.",
        "Il ragno fa una ragnatela nell'angolo",
      ],
      prompts: { "es": "La araña hace una telaraña en el rincón." },
      hint: "fare = to make; fa = 3rd person singular; nell'angolo = in the corner",
      tags: ["sentence", "animal", "insect", "fare", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-155"],
    },
    {
      id: "a114-t3-117",
      type: "produce",
      prompt: "The ant is small, the fly is fast.",
      accepted: [
        "La formica è piccola, la mosca è veloce.",
        "La formica è piccola, la mosca è veloce",
      ],
      prompts: { "es": "La hormiga es pequeña, la mosca es rápida." },
      hint: "piccola = small (fem.); veloce = fast — no article before the adjective",
      tags: ["sentence", "animal", "insect", "adjective", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-159", "a114-t1-160"],
    },
    {
      id: "a114-t3-118",
      type: "produce",
      prompt: "The duck and the goose live near the water.",
      accepted: [
        "L'anatra e l'oca vivono vicino all'acqua.",
        "L'anatra e l'oca vivono vicino all'acqua",
      ],
      prompts: { "es": "El pato y el ganso viven cerca del agua." },
      hint: "vivono = they live (vivere); vicino a = near",
      tags: ["sentence", "animal", "farm", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-150", "a114-t1-161"],
    },
    {
      id: "a114-t3-119",
      type: "produce",
      prompt: "The deer and the fox live in the forest.",
      accepted: [
        "Il cervo e la volpe vivono nel bosco.",
        "Il cervo e la volpe vivono nel bosco",
      ],
      prompts: { "es": "El ciervo y el zorro viven en el bosque." },
      hint: "vivono = they live (vivere); nel bosco = in the forest",
      tags: ["sentence", "animal", "wild", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-153", "a114-t1-019"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Sentences: context rescue for words orphaned by Tier 4 deprecations
    // (elefante, tigre, capra lost their only sentence context — see Tier 4 note)
    // -------------------------------------------------------------------------
    {
      id: "a114-t3-120",
      type: "produce",
      prompt: "The elephant lives in Africa.",
      accepted: [
        "L'elefante vive in Africa.",
        "L'elefante vive in Africa",
      ],
      prompts: { "es": "El elefante vive en África." },
      hint: "vivere = to live; vive = 3rd person singular; in Africa = no article before continent names",
      tags: ["sentence", "animal", "wild", "vivere", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-020"],
    },
    {
      id: "a114-t3-121",
      type: "produce",
      prompt: "The tiger hunts at night.",
      accepted: [
        "La tigre caccia di notte.",
        "La tigre caccia di notte",
      ],
      prompts: { "es": "El tigre caza de noche." },
      hint: "cacciare = to hunt; caccia = 3rd person singular; di notte = at night",
      tags: ["sentence", "animal", "wild", "cacciare", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-157"],
    },
    {
      id: "a114-t3-122",
      type: "produce",
      prompt: "The goat climbs the mountain.",
      accepted: [
        "La capra sale sulla montagna.",
        "La capra sale sulla montagna",
      ],
      prompts: { "es": "La cabra sube a la montaña." },
      hint: "salire = to climb; sale = 3rd person singular; sulla montagna = up the mountain",
      tags: ["sentence", "animal", "farm", "salire", "A1", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-151"],
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Passage cloze: self-contained mini-stories (replacing retired
    // single-sentence Tier 4 cards a114-t4-100 through a114-t4-111, minus 106)
    // -------------------------------------------------------------------------
    {
      id: "a114-t4-112",
      type: "passage_cloze",
      prompt: "Ogni mattina Paolo va nella stalla per dare da mangiare agli animali.\nLe mucche mangiano il fieno e bevono l'acqua.\nLe pecore restano vicine, una accanto all'altra.\nPaolo sente il gallo cantare fuori dalla finestra.\nPoi porta l'erba fresca alle ___, che la mangiano subito.",
      accepted: ["capre"],
      hint: "plural of la capra — the goats eat the fresh grass right away",
      tags: ["passage_cloze", "animal", "farm", "plural", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-004", // la mucca
        "a114-t1-007", // la pecora
        "a114-t1-152", // il gallo
        "a114-t1-151", // la capra
      ],
    },
    {
      id: "a114-t4-113",
      type: "passage_cloze",
      prompt: "Sofia ha tre animali domestici in casa.\nIl cane dorme vicino alla porta e il gatto guarda fuori dalla finestra.\nIl coniglio salta nella sua gabbia bianca.\nOgni sera Sofia dà da mangiare a tutti e tre.\nStasera nota che manca la sua ___, che di solito sta sotto il divano.",
      accepted: ["tartaruga"],
      hint: "the slow pet that hides under furniture — la tartaruga",
      tags: ["passage_cloze", "animal", "pet", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-002", // il cane
        "a114-t1-001", // il gatto
        "a114-t1-008", // il coniglio
        "a114-t1-154", // la tartaruga
      ],
    },
    {
      id: "a114-t4-114",
      type: "passage_cloze",
      prompt: "La domenica, Luca va allo zoo con suo nonno.\nVedono il leone che dorme sotto un albero grande.\nLe scimmie saltano da un ramo all'altro, veloci e rumorose.\nVicino alla vasca d'acqua, un animale enorme spruzza acqua con il naso.\nLuca grida: «Guarda il ___! È il mio animale preferito!»",
      accepted: ["elefante", "l'elefante"],
      hint: "the enormous zoo animal that sprays water with its trunk — l'elefante",
      tags: ["passage_cloze", "animal", "wild", "zoo", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-016", // il leone
        "a114-t1-021", // la scimmia
        "a114-t1-020", // l'elefante
      ],
    },
    {
      id: "a114-t4-115",
      type: "passage_cloze",
      prompt: "Nel bosco d'inverno fa molto freddo.\nIl cervo cerca cibo sotto la neve, vicino agli alberi.\nLa volpe osserva tutto da lontano, nascosta dietro una roccia.\nD'un tratto, il cervo e la volpe sentono un rumore forte: è il verso di un ___\nche cammina lentamente tra gli alberi, grande e peloso.",
      accepted: ["orso", "l'orso"],
      hint: "the large, furry animal that lives in the winter forest — l'orso",
      tags: ["passage_cloze", "animal", "wild", "forest", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-153", // il cervo
        "a114-t1-019", // la volpe
        "a114-t1-017", // l'orso
      ],
    },
    {
      id: "a114-t4-116",
      type: "passage_cloze",
      prompt: "In giardino, in primavera, ci sono molti insetti diversi.\nLe api volano di fiore in fiore e fanno il miele.\nLe farfalle colorate si posano sulle rose.\nSotto una foglia, un piccolo ___ tesse la sua ragnatela in silenzio.\nI bambini osservano tutto con curiosità, senza toccare niente.",
      accepted: ["ragno", "il ragno"],
      hint: "the eight-legged creature that weaves a web — il ragno",
      tags: ["passage_cloze", "animal", "insect", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-015", // l'ape
        "a114-t1-014", // la farfalla
        "a114-t1-155", // il ragno
      ],
    },
    {
      id: "a114-t4-117",
      type: "passage_cloze",
      prompt: "All'acquario, Anna guarda con emozione la vasca principale.\nUn delfino salta felice fuori dall'acqua e tutti i bambini applaudono.\nIntorno a lui nuotano tanti ___ piccoli e colorati.\nAnna chiede alla guida quanti animali vivono in quella vasca.\nLa guida sorride e risponde: «Più di cento!»",
      accepted: ["pesci"],
      hint: "plural of il pesce — small colourful fish swimming around the dolphin",
      tags: ["passage_cloze", "animal", "sea", "plural", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-022", // il delfino
        "a114-t1-011", // il pesce
      ],
    },
    {
      id: "a114-t4-118",
      type: "passage_cloze",
      prompt: "Alla fattoria di nonno Carlo ci sono molti animali diversi.\nI polli camminano liberi nel cortile, cercando semi per terra.\nIl gallo canta forte ogni mattina presto.\nVicino al recinto dorme un grosso ___, rosa e tranquillo, sotto il sole caldo.\nNonno Carlo lo chiama sempre «il pigrone della fattoria».",
      accepted: ["maiale", "il maiale"],
      hint: "the pink farm animal known for napping in the sun — il maiale",
      tags: ["passage_cloze", "animal", "farm", "A1", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-006", // il pollo
        "a114-t1-152", // il gallo
        "a114-t1-005", // il maiale
      ],
    },
  ],
};

export default unit;
