import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-06-describing",
  name: "Describing Things",
  level: "A1",
  theme: "Describing Things",
  emoji: "🎨",
  prerequisiteUnits: ["a1-unit-01-greetings", "a1-unit-03-family"],
  cards: [
    // ── TIER 1: VOCABULARY ─────────────────────────────────────
    {
      id: "u06-t1-001",
      type: "produce",
      prompt: "the car",
      accepted: ["la macchina", "l'auto", "l'automobile"],
      hint: "Feminine — la macchina.",
      tags: ["nouns", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-002",
      type: "produce",
      prompt: "the dog",
      accepted: ["il cane"],
      hint: "Masculine — il cane.",
      tags: ["nouns", "animals", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-003",
      type: "produce",
      prompt: "the house",
      accepted: ["la casa"],
      hint: "Feminine — la casa.",
      tags: ["nouns", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-004",
      type: "produce",
      prompt: "the book",
      accepted: ["il libro"],
      hint: "Masculine — il libro.",
      tags: ["nouns", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-005",
      type: "produce",
      prompt: "big / large",
      accepted: ["grande"],
      hint: "Same form m/f; plurals: grandi.",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-006",
      type: "produce",
      prompt: "small",
      accepted: ["piccolo", "piccola"],
      hint: "piccolo (m) / piccola (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-007",
      type: "produce",
      prompt: "beautiful / nice",
      accepted: ["bello", "bella"],
      hint: "bello (m) / bella (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-008",
      type: "produce",
      prompt: "ugly",
      accepted: ["brutto", "brutta"],
      hint: "brutto (m) / brutta (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-009",
      type: "produce",
      prompt: "new",
      accepted: ["nuovo", "nuova"],
      hint: "nuovo (m) / nuova (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-010",
      type: "produce",
      prompt: "old",
      accepted: ["vecchio", "vecchia"],
      hint: "vecchio (m) / vecchia (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-011",
      type: "produce",
      prompt: "red",
      accepted: ["rosso", "rossa"],
      hint: "rosso (m) / rossa (f).",
      tags: ["colors", "adjectives", "A1"],
      tier: 1,
    },
    {
      id: "u06-t1-012",
      type: "produce",
      prompt: "nice / likeable",
      accepted: ["simpatico", "simpatica"],
      hint: "simpatico (m) / simpatica (f).",
      tags: ["adjectives", "describing", "A1"],
      tier: 1,
    },

    // ── TIER 2: GRAMMAR ────────────────────────────────────────
    {
      id: "u06-t2-001",
      type: "conjugate",
      prompt: "essere – lui/lei",
      accepted: ["è"],
      hint: "Remember the accent grave: è.",
      tags: ["essere", "conjugation", "A1"],
      tier: 2,
    },
    {
      id: "u06-t2-002",
      type: "produce",
      prompt: "the red car (article + noun + adj agreement)",
      accepted: ["la macchina rossa"],
      hint: "Adjective follows noun; rossa agrees with la macchina (f).",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-001", "u06-t1-011"],
    },
    {
      id: "u06-t2-003",
      type: "produce",
      prompt: "the big dog (article + noun + adj agreement)",
      accepted: ["il cane grande"],
      hint: "grande is invariable for gender; follows noun.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-002", "u06-t1-005"],
    },
    {
      id: "u06-t2-004",
      type: "produce",
      prompt: "the new house (article + noun + adj agreement)",
      accepted: ["la casa nuova"],
      hint: "nuova agrees with casa (f); adjective after noun.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-003", "u06-t1-009"],
    },
    {
      id: "u06-t2-005",
      type: "produce",
      prompt: "the old book (article + noun + adj agreement)",
      accepted: ["il libro vecchio"],
      hint: "vecchio agrees with libro (m); follows noun.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-004", "u06-t1-010"],
    },
    {
      id: "u06-t2-006",
      type: "produce",
      prompt: "the beautiful dog (article + noun + adj agreement)",
      accepted: ["il cane bello"],
      hint: "bello after noun → bello (m). Before noun → bel.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-002", "u06-t1-007"],
    },
    {
      id: "u06-t2-007",
      type: "produce",
      prompt: "the small car (article + noun + adj agreement)",
      accepted: ["la macchina piccola"],
      hint: "piccola agrees with macchina (f); adjective after noun.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-001", "u06-t1-006"],
    },
    {
      id: "u06-t2-008",
      type: "produce",
      prompt: "the ugly house (article + noun + adj agreement)",
      accepted: ["la casa brutta"],
      hint: "brutta agrees with casa (f); follows noun.",
      tags: ["adjective-agreement", "articles", "A1"],
      tier: 2,
      prerequisites: ["u06-t1-003", "u06-t1-008"],
    },

    // ── TIER 3: CHUNKS / PHRASES ───────────────────────────────
    {
      id: "u06-t3-001",
      type: "produce",
      prompt: "How is it? / What's it like?",
      accepted: ["Com'è?", "Come è?"],
      hint: "Com'è = Come + è contracted. Very common.",
      tags: ["phrases", "describing", "A1"],
      tier: 3,
    },
    {
      id: "u06-t3-002",
      type: "produce",
      prompt: "It is very beautiful.",
      accepted: ["È molto bello.", "È molto bella.", "È molto bello", "È molto bella"],
      hint: "molto is invariable; agree bello/bella with the thing.",
      tags: ["phrases", "describing", "A1"],
      tier: 3,
    },
    {
      id: "u06-t3-003",
      type: "produce",
      prompt: "It is not big.",
      accepted: ["Non è grande.", "Non è grande"],
      hint: "Non before verb negates; grande same m/f.",
      tags: ["phrases", "describing", "negation", "A1"],
      tier: 3,
    },
    {
      id: "u06-t3-004",
      type: "produce",
      prompt: "What color is it?",
      accepted: ["Di che colore è?", "Di che colore è"],
      hint: "Lit. 'Of what color is it?' — standard question form.",
      tags: ["phrases", "colors", "A1"],
      tier: 3,
    },
    {
      id: "u06-t3-005",
      type: "produce",
      prompt: "It is red.",
      accepted: ["È rosso.", "È rossa.", "È rosso", "È rossa"],
      hint: "Match rosso/rossa to the gender of the thing described.",
      tags: ["phrases", "colors", "A1"],
      tier: 3,
    },
    {
      id: "u06-t3-006",
      type: "produce",
      prompt: "It is big and beautiful.",
      accepted: ["È grande e bello.", "È grande e bella.", "È grande e bello", "È grande e bella"],
      hint: "e = and; grande stays same, bello/bella must agree.",
      tags: ["phrases", "describing", "A1"],
      tier: 3,
    },

    // ── TIER 4: SENTENCES ──────────────────────────────────────
    {
      id: "u06-t4-001",
      type: "produce",
      prompt: "The new car is red and big.",
      accepted: [
        "La macchina nuova è rossa e grande.",
        "La macchina nuova è grande e rossa.",
      ],
      hint: "Adjectives follow noun; rossa agrees with macchina (f).",
      tags: ["sentences", "describing", "A1"],
      tier: 4,
      prerequisites: [
        "u06-t1-001",
        "u06-t1-005",
        "u06-t1-009",
        "u06-t1-011",
        "u06-t2-001",
      ],
    },
    {
      id: "u06-t4-002",
      type: "produce",
      prompt: "The dog is big and nice.",
      accepted: [
        "Il cane è grande e simpatico.",
        "Il cane è simpatico e grande.",
      ],
      hint: "grande invariable; simpatico agrees (m) with il cane.",
      tags: ["sentences", "describing", "A1"],
      tier: 4,
      prerequisites: [
        "u06-t1-002",
        "u06-t1-005",
        "u06-t1-012",
        "u06-t2-001",
      ],
    },
    {
      id: "u06-t4-003",
      type: "produce",
      prompt: "The old house is not beautiful.",
      accepted: [
        "La casa vecchia non è bella.",
        "La vecchia casa non è bella.",
      ],
      hint: "Non è = is not; vecchia and bella agree with casa (f).",
      tags: ["sentences", "describing", "negation", "A1"],
      tier: 4,
      prerequisites: [
        "u06-t1-003",
        "u06-t1-007",
        "u06-t1-010",
        "u06-t2-001",
      ],
    },
    {
      id: "u06-t4-004",
      type: "fill_blank",
      prompt: "Il libro nuovo è ___. (The new book is small.)",
      accepted: ["piccolo"],
      hint: "piccolo agrees with libro (m).",
      tags: ["sentences", "describing", "A1"],
      tier: 4,
      prerequisites: [
        "u06-t1-004",
        "u06-t1-006",
        "u06-t1-009",
        "u06-t2-001",
      ],
    },
    {
      id: "u06-t4-005",
      type: "produce",
      prompt: "What color is the new car?",
      accepted: [
        "Di che colore è la macchina nuova?",
        "Di che colore è la nuova macchina?",
      ],
      hint: "Use Di che colore è…? + article + noun + adjective.",
      tags: ["sentences", "colors", "questions", "A1"],
      tier: 4,
      prerequisites: [
        "u06-t1-001",
        "u06-t1-009",
        "u06-t2-001",
      ],
    },
  ],
};

export default unit;
