import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-02-bar",
  name: "At the Bar",
  level: "A1",
  theme: "At the Bar",
  emoji: "☕",
  prerequisiteUnits: ["a1-unit-01-greetings"],
  cards: [
    // ── Tier 1: Vocabulary ──────────────────────────────────────────────────
    {
      id: "u02-t1-001",
      type: "produce",
      prompt: "the coffee",
      prompts: { "es": "el café" },
      accepted: ["il caffè"],
      hint: "accent on final -è",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-002",
      type: "produce",
      prompt: "the cappuccino",
      prompts: { "es": "el capuchino" },
      accepted: ["il cappuccino"],
      hint: "double p, double c",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-003",
      type: "produce",
      prompt: "the croissant",
      prompts: { "es": "el cruasán" },
      accepted: ["il cornetto"],
      hint: "literally 'little horn'",
      tags: ["noun", "food", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-004",
      type: "produce",
      prompt: "the orange juice",
      prompts: { "es": "el jugo de naranja" },
      accepted: ["il succo d'arancia"],
      hint: "succo = juice, elided article",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-005",
      type: "produce",
      prompt: "the water",
      prompts: { "es": "el agua" },
      accepted: ["l'acqua"],
      hint: "l' before vowel — feminine",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-006",
      type: "produce",
      prompt: "the beer",
      prompts: { "es": "la cerveza" },
      accepted: ["la birra"],
      hint: "double r — feminine",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-007",
      type: "produce",
      prompt: "the wine",
      prompts: { "es": "el vino" },
      accepted: ["il vino"],
      hint: "sounds like 'vino' in English",
      tags: ["noun", "drink", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-008",
      type: "produce",
      prompt: "the bill / check",
      prompts: { "es": "la cuenta" },
      accepted: ["il conto"],
      hint: "conto = account/bill",
      tags: ["noun", "bar", "paying"],
      tier: 1,
    },
    {
      id: "u02-t1-009",
      type: "produce",
      prompt: "the barista / bartender",
      prompts: { "es": "el barista" },
      accepted: ["il barista"],
      hint: "same word in English!",
      tags: ["noun", "person", "bar"],
      tier: 1,
    },
    {
      id: "u02-t1-010",
      type: "produce",
      prompt: "the bar / café",
      prompts: { "es": "el bar / el café" },
      accepted: ["il bar"],
      hint: "invariable — no -s in plural",
      tags: ["noun", "place", "bar"],
      tier: 1,
    },

    // --- Recognize cards for existing vocabulary (seq 100–109) ---
    {
      id: "u02-t1-100",
      type: "recognize",
      prompt: "il caffè",
      accepted: ["coffee", "espresso"],
      translations: { "es": ["café", "expreso"] },
      hint: "the classic Italian short shot",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-101",
      type: "recognize",
      prompt: "il cappuccino",
      accepted: ["cappuccino"],
      translations: { "es": ["capuchino"] },
      hint: "espresso with steamed milk foam",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-102",
      type: "recognize",
      prompt: "il cornetto",
      accepted: ["croissant", "brioche"],
      translations: { "es": ["cruasán"] },
      hint: "literally 'little horn'",
      tags: ["noun", "food", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-103",
      type: "recognize",
      prompt: "il succo d'arancia",
      accepted: ["orange juice"],
      translations: { "es": ["jugo de naranja"] },
      hint: "succo = juice, arancia = orange",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-104",
      type: "recognize",
      prompt: "l'acqua",
      accepted: ["water"],
      translations: { "es": ["agua"] },
      hint: "l' before vowel — feminine",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-105",
      type: "recognize",
      prompt: "la birra",
      accepted: ["beer"],
      translations: { "es": ["cerveza"] },
      hint: "double r — feminine noun",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-106",
      type: "recognize",
      prompt: "il vino",
      accepted: ["wine"],
      translations: { "es": ["vino"] },
      hint: "borrowed directly into English",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-107",
      type: "recognize",
      prompt: "il conto",
      accepted: ["bill", "check"],
      translations: { "es": ["cuenta"] },
      hint: "ask for it to pay and leave",
      tags: ["noun", "bar", "paying", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-108",
      type: "recognize",
      prompt: "il barista",
      accepted: ["barista", "bartender"],
      translations: { "es": ["barista"] },
      hint: "same word used in English cafés",
      tags: ["noun", "person", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-109",
      type: "recognize",
      prompt: "il bar",
      accepted: ["bar", "café", "coffee shop"],
      translations: { "es": ["bar", "café"] },
      hint: "invariable noun — no plural ending",
      tags: ["noun", "place", "bar", "A1"],
      tier: 1,
    },

    // --- New vocabulary: produce cards (seq 150–165) ---
    {
      id: "u02-t1-150",
      type: "produce",
      prompt: "the tea",
      prompts: { "es": "el té" },
      accepted: ["il tè"],
      hint: "accent on final -è, like caffè",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-151",
      type: "produce",
      prompt: "the hot chocolate",
      prompts: { "es": "el chocolate caliente" },
      accepted: ["la cioccolata calda"],
      hint: "cioccolata (fem.) + calda (hot, fem.)",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-152",
      type: "produce",
      prompt: "the glass",
      prompts: { "es": "el vaso" },
      accepted: ["il bicchiere"],
      hint: "bi-KYER-eh — masculine",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-153",
      type: "produce",
      prompt: "the cup",
      prompts: { "es": "la taza" },
      accepted: ["la tazza"],
      hint: "double z — feminine",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-154",
      type: "produce",
      prompt: "the sugar",
      prompts: { "es": "el azúcar" },
      accepted: ["lo zucchero"],
      hint: "lo before z — ZOO-keh-ro",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-155",
      type: "produce",
      prompt: "the milk",
      prompts: { "es": "la leche" },
      accepted: ["il latte"],
      hint: "same as 'latte' in English coffee shops",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-156",
      type: "produce",
      prompt: "the receipt",
      prompts: { "es": "el recibo" },
      accepted: ["lo scontrino"],
      hint: "lo before sc- — always ask at Italian bars",
      tags: ["noun", "bar", "paying", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-157",
      type: "produce",
      prompt: "the sandwich",
      prompts: { "es": "el sándwich" },
      accepted: ["il tramezzino"],
      hint: "tra-med-ZEE-no — triangular crustless bar snack",
      tags: ["noun", "food", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-158",
      type: "produce",
      prompt: "the fresh squeezed juice",
      prompts: { "es": "el zumo natural" },
      accepted: ["la spremuta"],
      hint: "from spremere — to squeeze",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-159",
      type: "produce",
      prompt: "the ice",
      prompts: { "es": "el hielo" },
      accepted: ["il ghiaccio"],
      hint: "GYAH-cho — silent h",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-160",
      type: "produce",
      prompt: "the pastry (at a bar)",
      prompts: { "es": "el bollo" },
      accepted: ["la pasta"],
      hint: "at a bar, una pasta = sweet pastry, not spaghetti",
      tags: ["noun", "food", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-161",
      type: "produce",
      prompt: "the table",
      prompts: { "es": "la mesa" },
      accepted: ["il tavolo"],
      hint: "TAH-vo-lo — masculine",
      tags: ["noun", "place", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-162",
      type: "produce",
      prompt: "the waiter",
      prompts: { "es": "el camarero" },
      accepted: ["il cameriere"],
      hint: "ca-meh-RYEH-reh — masculine",
      tags: ["noun", "person", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-163",
      type: "produce",
      prompt: "the apple juice",
      prompts: { "es": "el jugo de manzana" },
      accepted: ["il succo di mela"],
      hint: "succo = juice, mela = apple",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-164",
      type: "produce",
      prompt: "the bottle",
      prompts: { "es": "la botella" },
      accepted: ["la bottiglia"],
      hint: "bot-TEE-lya — feminine",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-165",
      type: "produce",
      prompt: "the aperitif",
      prompts: { "es": "el aperitivo" },
      accepted: ["l'aperitivo"],
      hint: "l' before vowel — classic Italian pre-dinner drink",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },

    // --- New vocabulary: recognize cards (seq 166–181) ---
    {
      id: "u02-t1-166",
      type: "recognize",
      prompt: "il tè",
      accepted: ["tea"],
      translations: { "es": ["té"] },
      hint: "accent on final -è, like caffè",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-167",
      type: "recognize",
      prompt: "la cioccolata calda",
      accepted: ["hot chocolate"],
      translations: { "es": ["chocolate caliente"] },
      hint: "calda = hot (feminine)",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-168",
      type: "recognize",
      prompt: "il bicchiere",
      accepted: ["glass"],
      translations: { "es": ["vaso"] },
      hint: "used for water, wine, juice",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-169",
      type: "recognize",
      prompt: "la tazza",
      accepted: ["cup"],
      translations: { "es": ["taza"] },
      hint: "used for coffee and tea",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-170",
      type: "recognize",
      prompt: "lo zucchero",
      accepted: ["sugar"],
      translations: { "es": ["azúcar"] },
      hint: "lo before z",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-171",
      type: "recognize",
      prompt: "il latte",
      accepted: ["milk"],
      translations: { "es": ["leche"] },
      hint: "same as 'latte' in English",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-172",
      type: "recognize",
      prompt: "lo scontrino",
      accepted: ["receipt"],
      translations: { "es": ["recibo"] },
      hint: "lo before sc-",
      tags: ["noun", "bar", "paying", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-173",
      type: "recognize",
      prompt: "il tramezzino",
      accepted: ["sandwich", "snack"],
      translations: { "es": ["sándwich"] },
      hint: "triangular crustless bar snack",
      tags: ["noun", "food", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-174",
      type: "recognize",
      prompt: "la spremuta",
      accepted: ["fresh squeezed juice", "fresh juice"],
      translations: { "es": ["zumo natural", "jugo fresco"] },
      hint: "from spremere — to squeeze",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-175",
      type: "recognize",
      prompt: "il ghiaccio",
      accepted: ["ice"],
      translations: { "es": ["hielo"] },
      hint: "GYAH-cho — silent h",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-176",
      type: "recognize",
      prompt: "la pasta",
      accepted: ["pastry", "cake"],
      translations: { "es": ["bollo", "pastel"] },
      hint: "at a bar, una pasta is always something sweet",
      tags: ["noun", "food", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-177",
      type: "recognize",
      prompt: "il tavolo",
      accepted: ["table"],
      translations: { "es": ["mesa"] },
      hint: "where you sit at the bar",
      tags: ["noun", "place", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-178",
      type: "recognize",
      prompt: "il cameriere",
      accepted: ["waiter"],
      translations: { "es": ["camarero"] },
      hint: "table service at a bar or restaurant",
      tags: ["noun", "person", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-179",
      type: "recognize",
      prompt: "il succo di mela",
      accepted: ["apple juice"],
      translations: { "es": ["jugo de manzana"] },
      hint: "succo = juice, mela = apple",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-180",
      type: "recognize",
      prompt: "la bottiglia",
      accepted: ["bottle"],
      translations: { "es": ["botella"] },
      hint: "una bottiglia d'acqua = a bottle of water",
      tags: ["noun", "bar", "A1"],
      tier: 1,
    },
    {
      id: "u02-t1-181",
      type: "recognize",
      prompt: "l'aperitivo",
      accepted: ["aperitif", "pre-dinner drink"],
      translations: { "es": ["aperitivo"] },
      hint: "classic Italian pre-meal ritual",
      tags: ["noun", "drink", "bar", "A1"],
      tier: 1,
    },

    // ── Tier 2: Grammar ─────────────────────────────────────────────────────
    {
      id: "u02-t2-001",
      type: "conjugate",
      prompt: "prendere – io",
      accepted: ["prendo"],
      hint: "-ERE verb: drop -ere, add -o",
      tags: ["verb", "conjugation", "-ere"],
      tier: 2,
    },
    {
      id: "u02-t2-002",
      type: "conjugate",
      prompt: "prendere – tu",
      accepted: ["prendi"],
      hint: "-ERE verb: drop -ere, add -i",
      tags: ["verb", "conjugation", "-ere"],
      tier: 2,
    },
    {
      id: "u02-t2-003",
      type: "conjugate",
      prompt: "volere – io",
      accepted: ["voglio"],
      hint: "irregular: vo- stem, -glio ending",
      tags: ["verb", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u02-t2-004",
      type: "conjugate",
      prompt: "volere – tu",
      accepted: ["vuoi"],
      hint: "irregular: vuo- stem",
      tags: ["verb", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u02-t2-005",
      type: "conjugate",
      prompt: "avere – io",
      accepted: ["ho"],
      hint: "silent h — irregular",
      tags: ["verb", "conjugation", "irregular", "avere"],
      tier: 2,
    },
    {
      id: "u02-t2-006",
      type: "produce",
      prompt: "indefinite article: masculine singular (normal consonant)",
      prompts: { "es": "artículo indefinido: masculino singular (consonante normal)" },
      accepted: ["un"],
      hint: "un caffè, un vino",
      tags: ["grammar", "article", "indefinite"],
      tier: 2,
    },
    {
      id: "u02-t2-007",
      type: "produce",
      prompt: "indefinite article: feminine singular",
      prompts: { "es": "artículo indefinido: femenino singular" },
      accepted: ["una"],
      hint: "una birra, una pizza",
      tags: ["grammar", "article", "indefinite"],
      tier: 2,
    },
    {
      id: "u02-t2-008",
      type: "produce",
      prompt: "indefinite article: before vowel (feminine)",
      prompts: { "es": "artículo indefinido: femenino antes de vocal" },
      accepted: ["un'"],
      hint: "elision: un'acqua, un'arancia",
      tags: ["grammar", "article", "indefinite", "elision"],
      tier: 2,
    },
    {
      id: "u02-t2-009",
      type: "produce",
      prompt: "indefinite article: masculine before s+consonant or z",
      prompts: { "es": "artículo indefinido: masculino antes de s+consonante o z" },
      accepted: ["uno"],
      hint: "uno studente, uno zaino",
      tags: ["grammar", "article", "indefinite"],
      tier: 2,
    },

    // --- New grammar drills (seq 100–119) ---
    {
      id: "u02-t2-100",
      type: "conjugate",
      prompt: "prendere – lui/lei",
      accepted: ["prende"],
      hint: "-ERE verb: drop -ere, add -e",
      tags: ["verb", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-101",
      type: "conjugate",
      prompt: "prendere – noi",
      accepted: ["prendiamo"],
      hint: "-ERE verb: drop -ere, add -iamo",
      tags: ["verb", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-102",
      type: "conjugate",
      prompt: "prendere – voi",
      accepted: ["prendete"],
      hint: "-ERE verb: drop -ere, add -ete",
      tags: ["verb", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-103",
      type: "conjugate",
      prompt: "prendere – loro",
      accepted: ["prendono"],
      hint: "-ERE verb: drop -ere, add -ono",
      tags: ["verb", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-104",
      type: "conjugate",
      prompt: "volere – lui/lei",
      accepted: ["vuole"],
      hint: "irregular: vuo- stem, like vuoi",
      tags: ["verb", "conjugation", "irregular", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-105",
      type: "conjugate",
      prompt: "volere – noi",
      accepted: ["vogliamo"],
      hint: "irregular: vog- stem, like voglio",
      tags: ["verb", "conjugation", "irregular", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-106",
      type: "conjugate",
      prompt: "volere – voi",
      accepted: ["volete"],
      hint: "irregular: vol- stem + -ete",
      tags: ["verb", "conjugation", "irregular", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-107",
      type: "conjugate",
      prompt: "avere – tu",
      accepted: ["hai"],
      hint: "silent h — sounds like 'eye'",
      tags: ["verb", "conjugation", "irregular", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-108",
      type: "conjugate",
      prompt: "avere – lui/lei",
      accepted: ["ha"],
      hint: "silent h — one syllable",
      tags: ["verb", "conjugation", "irregular", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-109",
      type: "conjugate",
      prompt: "avere – noi",
      accepted: ["abbiamo"],
      hint: "double b: ab-BYA-mo",
      tags: ["verb", "conjugation", "irregular", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-110",
      type: "conjugate",
      prompt: "avere – voi",
      accepted: ["avete"],
      hint: "regular ending: av- + -ete",
      tags: ["verb", "conjugation", "irregular", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-111",
      type: "conjugate",
      prompt: "avere – loro",
      accepted: ["hanno"],
      hint: "silent h, double n — sounds like ANNO",
      tags: ["verb", "conjugation", "irregular", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-112",
      type: "produce",
      prompt: "definite article: masculine singular (normal consonant)",
      prompts: { "es": "artículo definido: masculino singular (consonante normal)" },
      accepted: ["il"],
      hint: "il caffè, il vino, il latte, il bar",
      tags: ["grammar", "article", "definite", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-113",
      type: "produce",
      prompt: "definite article: masculine singular (before s+consonant or z)",
      prompts: { "es": "artículo definido: masculino singular (antes de s+consonante o z)" },
      accepted: ["lo"],
      hint: "lo zucchero, lo scontrino — mirrors uno",
      tags: ["grammar", "article", "definite", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-114",
      type: "produce",
      prompt: "definite article: feminine singular (before consonant)",
      prompts: { "es": "artículo definido: femenino singular (antes de consonante)" },
      accepted: ["la"],
      hint: "la birra, la tazza, la pasta, la bottiglia",
      tags: ["grammar", "article", "definite", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-115",
      type: "produce",
      prompt: "definite article: singular before a vowel (any gender)",
      prompts: { "es": "artículo definido: singular antes de vocal (cualquier género)" },
      accepted: ["l'"],
      hint: "l'acqua, l'aperitivo — elide before any vowel",
      tags: ["grammar", "article", "definite", "elision", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-116",
      type: "fill_blank",
      prompt: "Il barista ___ due caffè. (The barista has two coffees.)",
      accepted: ["ha"],
      hint: "avere: lui/lei → ha",
      tags: ["grammar", "conjugation", "avere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-117",
      type: "fill_blank",
      prompt: "Voi cosa ___? (What are you all having?)",
      accepted: ["prendete"],
      hint: "prendere: voi → prendete",
      tags: ["grammar", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-118",
      type: "fill_blank",
      prompt: "Noi ___ una birra e un vino. (We'll have a beer and a wine.)",
      accepted: ["prendiamo"],
      hint: "prendere: noi → prendiamo",
      tags: ["grammar", "conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u02-t2-119",
      type: "fill_blank",
      prompt: "___ caffè è caldo. (The coffee is hot.)",
      accepted: ["Il"],
      hint: "definite article: masculine singular before consonant",
      tags: ["grammar", "article", "definite", "A1"],
      tier: 2,
    },

    // ── Tier 3: Chunks / Phrases ─────────────────────────────────────────────
    {
      id: "u02-t3-001",
      type: "produce",
      prompt: "I'll have a coffee. (ordering)",
      prompts: { "es": "Tomo un café." },
      accepted: ["Prendo un caffè", "Prendo un caffè."],
      hint: "literally 'I take a coffee'",
      tags: ["chunk", "ordering", "bar"],
      tier: 3,
      prerequisites: ["u02-t2-001", "u02-t2-006", "u02-t1-001"],
    },
    {
      id: "u02-t3-002",
      type: "produce",
      prompt: "I would like a cappuccino. (polite order)",
      prompts: { "es": "Quisiera un capuchino." },
      accepted: ["Vorrei un cappuccino", "Vorrei un cappuccino."],
      hint: "vorrei = conditional of volere",
      tags: ["chunk", "ordering", "bar", "polite"],
      tier: 3,
      prerequisites: ["u02-t2-003", "u02-t2-006", "u02-t1-002"],
    },
    {
      id: "u02-t3-003",
      type: "produce",
      prompt: "How much is it?",
      prompts: { "es": "¿Cuánto es?" },
      accepted: ["Quant'è?", "Quant'è"],
      hint: "quanto + è → elision",
      tags: ["chunk", "paying", "bar"],
      tier: 3,
    },
    {
      id: "u02-t3-004",
      type: "produce",
      prompt: "The bill, please.",
      prompts: { "es": "La cuenta, por favor." },
      accepted: ["Il conto, per favore", "Il conto, per favore."],
      hint: "per favore = please",
      tags: ["chunk", "paying", "bar"],
      tier: 3,
      prerequisites: ["u02-t1-008"],
    },
    {
      id: "u02-t3-005",
      type: "produce",
      prompt: "What are you having? / What will you take?",
      prompts: { "es": "¿Qué vas a tomar?" },
      accepted: ["Cosa prendi?", "Cosa prendi"],
      hint: "cosa = what, prendi = you take",
      tags: ["chunk", "ordering", "bar"],
      tier: 3,
      prerequisites: ["u02-t2-002"],
    },
    {
      id: "u02-t3-006",
      type: "produce",
      prompt: "Do you have beer?",
      prompts: { "es": "¿Tienes cerveza?" },
      accepted: ["Hai la birra?", "Ha la birra?"],
      hint: "hai = you have (informal)",
      tags: ["chunk", "bar", "question"],
      tier: 3,
      prerequisites: ["u02-t2-005", "u02-t1-006"],
    },

    // --- New phrases (seq 100–114) ---
    {
      id: "u02-t3-100",
      type: "produce",
      prompt: "A tea with milk, please.",
      prompts: { "es": "Un té con leche, por favor." },
      accepted: ["Un tè con il latte, per favore.", "Un tè con il latte per favore."],
      hint: "con = with; il latte = the milk",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-150", "u02-t1-155"],
    },
    {
      id: "u02-t3-101",
      type: "produce",
      prompt: "Without sugar, please.",
      prompts: { "es": "Sin azúcar, por favor." },
      accepted: ["Senza zucchero, per favore.", "Senza zucchero per favore."],
      hint: "senza = without",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-154"],
    },
    {
      id: "u02-t3-102",
      type: "produce",
      prompt: "Still or sparkling? (water)",
      prompts: { "es": "¿Natural o con gas?" },
      accepted: ["Naturale o frizzante?", "Naturale o frizzante"],
      hint: "o = or; two types of water at Italian bars",
      tags: ["chunk", "bar", "question", "A1"],
      tier: 3,
    },
    {
      id: "u02-t3-103",
      type: "produce",
      prompt: "Can I pay?",
      prompts: { "es": "¿Puedo pagar?" },
      accepted: ["Posso pagare?", "Posso pagare"],
      hint: "posso = I can; pagare = to pay",
      tags: ["chunk", "paying", "bar", "A1"],
      tier: 3,
    },
    {
      id: "u02-t3-104",
      type: "produce",
      prompt: "We'll have two coffees.",
      prompts: { "es": "Tomamos dos cafés." },
      accepted: ["Prendiamo due caffè.", "Prendiamo due caffè"],
      hint: "noi prendere → prendiamo; caffè is invariable in plural",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t2-101", "u02-t1-001"],
    },
    {
      id: "u02-t3-105",
      type: "produce",
      prompt: "A glass of red wine, please.",
      prompts: { "es": "Un vaso de vino tinto, por favor." },
      accepted: ["Un bicchiere di vino rosso, per favore.", "Un bicchiere di vino rosso per favore."],
      hint: "bicchiere di = glass of; rosso = red (masc.)",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-152", "u02-t1-007"],
    },
    {
      id: "u02-t3-106",
      type: "produce",
      prompt: "Do you want sugar? (informal)",
      prompts: { "es": "¿Quieres azúcar?" },
      accepted: ["Vuoi lo zucchero?", "Vuoi lo zucchero"],
      hint: "vuoi = you want (tu); lo before zucchero",
      tags: ["chunk", "bar", "question", "A1"],
      tier: 3,
      prerequisites: ["u02-t2-004", "u02-t1-154"],
    },
    {
      id: "u02-t3-107",
      type: "produce",
      prompt: "I'll pay.",
      prompts: { "es": "Pago yo." },
      accepted: ["Pago io.", "Pago io"],
      hint: "'io' after verb adds emphasis — I'm paying, not you",
      tags: ["chunk", "paying", "bar", "A1"],
      tier: 3,
    },
    {
      id: "u02-t3-108",
      type: "produce",
      prompt: "Would you like anything else? (formal)",
      prompts: { "es": "¿Desea algo más?" },
      accepted: ["Vuole altro?", "Vuole altro"],
      hint: "vuole = formal 'you want'; altro = else / more",
      tags: ["chunk", "bar", "question", "A1"],
      tier: 3,
      prerequisites: ["u02-t2-104"],
    },
    {
      id: "u02-t3-109",
      type: "produce",
      prompt: "Do you accept cards?",
      prompts: { "es": "¿Aceptan tarjetas?" },
      accepted: ["Accettate la carta?", "Accettate la carta"],
      hint: "accettate = you (pl.) accept; la carta = card",
      tags: ["chunk", "paying", "bar", "A1"],
      tier: 3,
    },
    {
      id: "u02-t3-110",
      type: "produce",
      prompt: "Cheers!",
      prompts: { "es": "¡Salud!" },
      accepted: ["Salute!", "Cin cin!", "Salute", "Cin cin"],
      hint: "salute also means health; cin cin is the clink sound",
      tags: ["chunk", "bar", "social", "A1"],
      tier: 3,
    },
    {
      id: "u02-t3-111",
      type: "produce",
      prompt: "A bottle of water, please.",
      prompts: { "es": "Una botella de agua, por favor." },
      accepted: ["Una bottiglia d'acqua, per favore.", "Una bottiglia d'acqua per favore."],
      hint: "d'acqua = di + acqua — elide before vowel",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-164", "u02-t1-005"],
    },
    {
      id: "u02-t3-112",
      type: "produce",
      prompt: "With ice or without?",
      prompts: { "es": "¿Con hielo o sin hielo?" },
      accepted: ["Con ghiaccio o senza?", "Con ghiaccio o senza"],
      hint: "con = with, senza = without",
      tags: ["chunk", "bar", "question", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-159"],
    },
    {
      id: "u02-t3-113",
      type: "produce",
      prompt: "A fresh squeezed orange juice, please.",
      prompts: { "es": "Un zumo de naranja natural, por favor." },
      accepted: ["Una spremuta d'arancia, per favore.", "Una spremuta d'arancia per favore."],
      hint: "d'arancia = di + arancia — elide before vowel",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-158"],
    },
    {
      id: "u02-t3-114",
      type: "produce",
      prompt: "I want a coffee at the counter.",
      prompts: { "es": "Quiero un café en la barra." },
      accepted: ["Voglio un caffè al banco.", "Voglio un caffè al banco"],
      hint: "al = a + il; banco = the counter where Italians stand to drink",
      tags: ["chunk", "ordering", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t2-003", "u02-t1-001"],
    },

    // --- New phrases: coverage for isolated vocabulary (seq 115–120) ---
    {
      id: "u02-t3-115",
      type: "produce",
      prompt: "The tea is hot.",
      prompts: { "es": "El té está caliente." },
      accepted: ["Il tè è caldo.", "Il tè è caldo"],
      hint: "il tè + è caldo (is hot)",
      tags: ["chunk", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-150"],
    },
    {
      id: "u02-t3-116",
      type: "produce",
      prompt: "The cup is empty.",
      prompts: { "es": "La taza está vacía." },
      accepted: ["La tazza è vuota.", "La tazza è vuota"],
      hint: "la tazza + vuota (empty, feminine)",
      tags: ["chunk", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-153"],
    },
    {
      id: "u02-t3-117",
      type: "produce",
      prompt: "Excuse me, where is the receipt?",
      prompts: { "es": "Disculpe, ¿dónde está el recibo?" },
      accepted: ["Scusi, dov'è lo scontrino?", "Scusi, dov'è lo scontrino"],
      hint: "scusi = excuse me; dov'è = where is; lo scontrino = the receipt",
      tags: ["chunk", "bar", "paying", "question", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-156"],
    },
    {
      id: "u02-t3-118",
      type: "produce",
      prompt: "The sandwich is good.",
      prompts: { "es": "El sándwich está bueno." },
      accepted: ["Il tramezzino è buono.", "Il tramezzino è buono"],
      hint: "il tramezzino + buono (good, masculine)",
      tags: ["chunk", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-157"],
    },
    {
      id: "u02-t3-119",
      type: "produce",
      prompt: "The aperitif is at seven.",
      prompts: { "es": "El aperitivo es a las siete." },
      accepted: ["L'aperitivo è alle sette.", "L'aperitivo è alle sette"],
      hint: "l'aperitivo + alle sette (at seven o'clock)",
      tags: ["chunk", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-165"],
    },
    {
      id: "u02-t3-120",
      type: "produce",
      prompt: "The tea in the cup is already cold.",
      prompts: { "es": "El té en la taza ya está frío." },
      accepted: ["Il tè nella tazza è già freddo.", "Il tè nella tazza è già freddo"],
      hint: "nella = in + la; già = already",
      tags: ["chunk", "bar", "A1"],
      tier: 3,
      prerequisites: ["u02-t1-150", "u02-t1-153"],
    },

    // ── Tier 4: Sentences ────────────────────────────────────────────────────
    {
      id: "u02-t4-001",
      type: "produce",
      prompt: "Good morning! I'll have a cappuccino and a croissant, please.",
      prompts: { "es": "¡Buenos días! Tomo un capuchino y un cruasán, por favor." },
      accepted: [
        "Buongiorno! Prendo un cappuccino e un cornetto, per favore.",
        "Buongiorno! Prendo un cappuccino e un cornetto per favore.",
      ],
      hint: "e = and; use prendo for ordering",
      tags: ["sentence", "ordering", "bar"],
      tier: 4,
      prerequisites: ["u02-t1-002", "u02-t1-003", "u02-t2-001", "u02-t2-006"],
    },
    {
      id: "u02-t4-002",
      type: "produce",
      prompt: "I would like a coffee and a water, please.",
      prompts: { "es": "Quisiera un café y un agua, por favor." },
      accepted: [
        "Vorrei un caffè e un'acqua, per favore.",
        "Vorrei un caffè e un'acqua per favore.",
      ],
      hint: "un'acqua — elide before vowel",
      tags: ["sentence", "ordering", "bar"],
      tier: 4,
      prerequisites: [
        "u02-t1-001",
        "u02-t1-005",
        "u02-t2-003",
        "u02-t2-006",
        "u02-t2-008",
      ],
    },
    {
      id: "u02-t4-003",
      type: "produce",
      prompt: "The bill, please. How much is it?",
      prompts: { "es": "La cuenta, por favor. ¿Cuánto es?" },
      accepted: [
        "Il conto, per favore. Quant'è?",
        "Il conto per favore. Quant'è?",
      ],
      hint: "combine two learned chunks",
      tags: ["sentence", "paying", "bar"],
      tier: 4,
      prerequisites: ["u02-t1-008"],
    },
    {
      id: "u02-t4-004",
      type: "fill_blank",
      prompt: "Io ___ un vino rosso. (I'll have a red wine.)",
      accepted: ["prendo"],
      hint: "io + prendere present tense",
      tags: ["sentence", "ordering", "bar"],
      tier: 4,
      prerequisites: ["u02-t1-007", "u02-t2-001"],
    },
    {
      id: "u02-t4-005",
      type: "produce",
      prompt: "Do you have orange juice?",
      prompts: { "es": "¿Tienes jugo de naranja?" },
      accepted: ["Hai il succo d'arancia?", "Ha il succo d'arancia?"],
      hint: "hai = informal 'you have'",
      tags: ["sentence", "bar", "question"],
      tier: 4,
      prerequisites: ["u02-t1-004", "u02-t2-005"],
    },

    // --- New sentences (seq 100–112) ---
    {
      id: "u02-t4-100",
      type: "produce",
      prompt: "Good morning! I'd like a hot chocolate and a pastry, please.",
      prompts: { "es": "¡Buenos días! Quisiera un chocolate caliente y un bollo, por favor." },
      accepted: [
        "Buongiorno! Vorrei una cioccolata calda e una pasta, per favore.",
        "Buongiorno! Vorrei una cioccolata calda e una pasta per favore.",
      ],
      hint: "cioccolata and pasta are both feminine → una",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-151", "u02-t1-160"],
    },
    {
      id: "u02-t4-101",
      type: "produce",
      prompt: "Marco orders a cappuccino and Lucia orders a tea.",
      prompts: { "es": "Marco toma un capuchino y Lucía toma un té." },
      accepted: [
        "Marco prende un cappuccino e Lucia prende un tè.",
        "Marco prende un cappuccino e Lucia un tè.",
      ],
      hint: "third person singular: prende (lui/lei)",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t2-100", "u02-t1-002", "u02-t1-150"],
    },
    {
      id: "u02-t4-102",
      type: "produce",
      prompt: "We want two glasses of wine and a bottle of water.",
      prompts: { "es": "Queremos dos vasos de vino y una botella de agua." },
      accepted: [
        "Vogliamo due bicchieri di vino e una bottiglia d'acqua.",
        "Vogliamo due bicchieri di vino e una bottiglia d'acqua",
      ],
      hint: "vogliamo = we want; bicchieri = glasses (plural of bicchiere)",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t2-105", "u02-t1-152", "u02-t1-007", "u02-t1-164"],
    },
    {
      id: "u02-t4-103",
      type: "fill_blank",
      prompt: "Noi ___ due caffè. (We'll have two coffees.)",
      accepted: ["prendiamo"],
      hint: "prendere: noi → prendiamo",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t2-101"],
    },
    {
      id: "u02-t4-104",
      type: "produce",
      prompt: "Do you have apple juice? I don't want coffee.",
      prompts: { "es": "¿Tienes jugo de manzana? No quiero café." },
      accepted: [
        "Hai il succo di mela? Non voglio il caffè.",
        "Ha il succo di mela? Non voglio il caffè.",
      ],
      hint: "non + verb for negation; hai (informal) / ha (formal)",
      tags: ["sentence", "bar", "question", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-163", "u02-t2-003"],
    },
    {
      id: "u02-t4-105",
      type: "produce",
      prompt: "The waiter brings two coffees to the table.",
      prompts: { "es": "El camarero trae dos cafés a la mesa." },
      accepted: ["Il cameriere porta due caffè al tavolo."],
      hint: "portare: lui → porta (regular -ARE verb)",
      tags: ["sentence", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-162", "u02-t1-161"],
    },
    {
      id: "u02-t4-106",
      type: "produce",
      prompt: "Excuse me, can I pay? Do you accept cards?",
      prompts: { "es": "Disculpe, ¿puedo pagar? ¿Aceptan tarjetas?" },
      accepted: [
        "Scusi, posso pagare? Accettate la carta?",
        "Scusi, posso pagare? Accettate la carta",
      ],
      hint: "scusi = formal excuse me; posso = I can",
      tags: ["sentence", "paying", "bar", "A1"],
      tier: 4,
    },
    {
      id: "u02-t4-107",
      type: "fill_blank",
      prompt: "___ una birra, per favore. (I'd like a beer, please.)",
      accepted: ["Vorrei"],
      hint: "polite ordering: vorrei = I would like",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-006"],
    },
    {
      id: "u02-t4-108",
      type: "produce",
      prompt: "The coffee is hot and the water is cold.",
      prompts: { "es": "El café está caliente y el agua está fría." },
      accepted: [
        "Il caffè è caldo e l'acqua è fredda.",
        "Il caffè è caldo e l'acqua è fredda",
      ],
      hint: "caldo (masc.) vs fredda (fem.) — adjective agrees with noun",
      tags: ["sentence", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-001", "u02-t1-005"],
    },
    {
      id: "u02-t4-109",
      type: "produce",
      prompt: "I have a cappuccino every morning at the bar.",
      prompts: { "es": "Tomo un capuchino cada mañana en el bar." },
      accepted: [
        "Prendo un cappuccino ogni mattina al bar.",
        "Ogni mattina prendo un cappuccino al bar.",
      ],
      hint: "ogni = every, mattina = morning, al bar = at the bar",
      tags: ["sentence", "bar", "routine", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-002", "u02-t2-001"],
    },
    {
      id: "u02-t4-110",
      type: "produce",
      prompt: "She wants a fresh squeezed orange juice without ice.",
      prompts: { "es": "Ella quiere un zumo de naranja natural sin hielo." },
      accepted: [
        "Lei vuole una spremuta d'arancia senza ghiaccio.",
        "Vuole una spremuta d'arancia senza ghiaccio.",
      ],
      hint: "lei vuole = she wants; senza = without",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t2-104", "u02-t1-158", "u02-t1-159"],
    },
    {
      id: "u02-t4-111",
      type: "produce",
      prompt: "How much are a coffee and a croissant?",
      prompts: { "es": "¿Cuánto cuestan un café y un cruasán?" },
      accepted: [
        "Quant'è un caffè e un cornetto?",
        "Quant'è per un caffè e un cornetto?",
      ],
      hint: "quant'è extends to asking the total price",
      tags: ["sentence", "paying", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t1-001", "u02-t1-003"],
    },
    {
      id: "u02-t4-112",
      type: "fill_blank",
      prompt: "Loro ___ due tramezzini e una birra. (They'll have two sandwiches and a beer.)",
      accepted: ["prendono"],
      hint: "prendere: loro → prendono",
      tags: ["sentence", "ordering", "bar", "A1"],
      tier: 4,
      prerequisites: ["u02-t2-103", "u02-t1-157"],
    },
  ],
};

export default unit;
