import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-14-animals",
  name: "Animals",
  level: "A1",
  theme: "Animals & Nature Basics",
  emoji: "🐾",
  prerequisiteUnits: ["a1-unit-13-household"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary (22 cards)
    // -------------------------------------------------------------------------
    {
      id: "a114-t1-001",
      type: "produce",
      prompt: "the cat",
      accepted: ["il gatto"],
      hint: "masculine noun — il gatto",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-002",
      type: "produce",
      prompt: "the dog",
      accepted: ["il cane"],
      hint: "masculine noun — il cane",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-003",
      type: "produce",
      prompt: "the horse",
      accepted: ["il cavallo"],
      hint: "masculine noun — il cavallo",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-004",
      type: "produce",
      prompt: "the cow",
      accepted: ["la mucca"],
      hint: "feminine noun — la mucca",
      tags: ["noun", "animal", "farm", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-005",
      type: "produce",
      prompt: "the pig",
      accepted: ["il maiale"],
      hint: "masculine noun — il maiale",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-006",
      type: "produce",
      prompt: "the chicken",
      accepted: ["il pollo"],
      hint: "masculine noun — il pollo (also means chicken the food)",
      tags: ["noun", "animal", "farm", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-007",
      type: "produce",
      prompt: "the sheep",
      accepted: ["la pecora"],
      hint: "feminine noun — la pecora",
      tags: ["noun", "animal", "farm", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-008",
      type: "produce",
      prompt: "the rabbit",
      accepted: ["il coniglio"],
      hint: "masculine noun — il coniglio",
      tags: ["noun", "animal", "pet", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-009",
      type: "produce",
      prompt: "the mouse",
      accepted: ["il topo"],
      hint: "masculine noun — il topo",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-010",
      type: "produce",
      prompt: "the bird",
      accepted: ["l'uccello"],
      hint: "masculine noun — l'uccello (elided article before vowel)",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-011",
      type: "produce",
      prompt: "the fish",
      accepted: ["il pesce"],
      hint: "masculine noun — il pesce",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-012",
      type: "produce",
      prompt: "the snake",
      accepted: ["il serpente"],
      hint: "masculine noun — il serpente",
      tags: ["noun", "animal", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-013",
      type: "produce",
      prompt: "the frog",
      accepted: ["la rana"],
      hint: "feminine noun — la rana",
      tags: ["noun", "animal", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-014",
      type: "produce",
      prompt: "the butterfly",
      accepted: ["la farfalla"],
      hint: "feminine noun — la farfalla",
      tags: ["noun", "animal", "insect", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-015",
      type: "produce",
      prompt: "the bee",
      accepted: ["l'ape"],
      hint: "feminine noun — l'ape (elided article before vowel)",
      tags: ["noun", "animal", "insect", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-016",
      type: "produce",
      prompt: "the lion",
      accepted: ["il leone"],
      hint: "masculine noun — il leone",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-017",
      type: "produce",
      prompt: "the bear",
      accepted: ["l'orso"],
      hint: "masculine noun — l'orso (elided article before vowel)",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-018",
      type: "produce",
      prompt: "the wolf",
      accepted: ["il lupo"],
      hint: "masculine noun — il lupo",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-019",
      type: "produce",
      prompt: "the fox",
      accepted: ["la volpe"],
      hint: "feminine noun — la volpe",
      tags: ["noun", "animal", "wild", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-020",
      type: "produce",
      prompt: "the elephant",
      accepted: ["l'elefante"],
      hint: "masculine noun — l'elefante (elided article before vowel)",
      tags: ["noun", "animal", "wild", "masculine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-021",
      type: "produce",
      prompt: "the monkey",
      accepted: ["la scimmia"],
      hint: "feminine noun — la scimmia",
      tags: ["noun", "animal", "wild", "feminine", "tier1"],
      tier: 1,
    },
    {
      id: "a114-t1-022",
      type: "produce",
      prompt: "the dolphin",
      accepted: ["il delfino"],
      hint: "masculine noun — il delfino",
      tags: ["noun", "animal", "sea", "masculine", "tier1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Fill-in-the-blank: favourite animal + verb collocations
    // -------------------------------------------------------------------------
    {
      id: "a114-t2-001",
      type: "fill_blank",
      prompt: "Il mio animale preferito è ___.",
      accepted: [
        "il gatto",
        "il cane",
        "il cavallo",
        "la mucca",
        "il maiale",
        "il pollo",
        "la pecora",
        "il coniglio",
        "il topo",
        "l'uccello",
        "il pesce",
        "il serpente",
        "la rana",
        "la farfalla",
        "l'ape",
        "il leone",
        "l'orso",
        "il lupo",
        "la volpe",
        "l'elefante",
        "la scimmia",
        "il delfino",
      ],
      hint: "name any animal with its article — e.g. il gatto, la volpe",
      tags: ["fill_blank", "animal", "favourite", "tier2"],
      tier: 2,
      prerequisites: [
        "a114-t1-001",
        "a114-t1-002",
        "a114-t1-003",
        "a114-t1-016",
        "a114-t1-019",
      ],
    },
    {
      id: "a114-t2-002",
      type: "fill_blank",
      prompt: "Il cane ___. (barks)",
      accepted: ["abbaia"],
      hint: "abbaiare = to bark — 3rd person singular: abbaia",
      tags: ["fill_blank", "animal", "verb-collocation", "abbaiare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-002"],
    },
    {
      id: "a114-t2-003",
      type: "fill_blank",
      prompt: "Il gatto ___. (meows)",
      accepted: ["miagola"],
      hint: "miagolare = to meow — 3rd person singular: miagola",
      tags: ["fill_blank", "animal", "verb-collocation", "miagolare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-001"],
    },
    {
      id: "a114-t2-004",
      type: "fill_blank",
      prompt: "L'uccello ___. (sings)",
      accepted: ["canta"],
      hint: "cantare = to sing — 3rd person singular: canta",
      tags: ["fill_blank", "animal", "verb-collocation", "cantare", "tier2"],
      tier: 2,
      prerequisites: ["a114-t1-010"],
    },

    // -------------------------------------------------------------------------
    // TIER 3 — English to Italian: full sentences
    // -------------------------------------------------------------------------
    {
      id: "a114-t3-001",
      type: "produce",
      prompt: "I have a cat and a dog.",
      accepted: [
        "Ho un gatto e un cane.",
        "Ho un gatto e un cane",
      ],
      hint: "avere = to have; ho = I have; un = a (masculine)",
      tags: ["sentence", "animal", "pet", "avere", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-001", "a114-t1-002"],
    },
    {
      id: "a114-t3-002",
      type: "produce",
      prompt: "The horse is big and beautiful.",
      accepted: [
        "Il cavallo è grande e bello.",
        "Il cavallo è grande e bello",
        "Il cavallo è bello e grande.",
        "Il cavallo è bello e grande",
      ],
      hint: "grande = big; bello = beautiful; è = is",
      tags: ["sentence", "animal", "farm", "adjective", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-003"],
    },
    {
      id: "a114-t3-003",
      type: "produce",
      prompt: "She's afraid of snakes.",
      accepted: [
        "Lei ha paura dei serpenti.",
        "Ha paura dei serpenti.",
        "Lei ha paura dei serpenti",
        "Ha paura dei serpenti",
      ],
      hint: "avere paura di = to be afraid of; dei serpenti = of snakes (plural)",
      tags: ["sentence", "animal", "fear", "avere-paura", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-012"],
    },
    {
      id: "a114-t3-004",
      type: "produce",
      prompt: "Bees make honey.",
      accepted: [
        "Le api fanno il miele.",
        "Le api fanno il miele",
        "Le api producono il miele.",
        "Le api producono il miele",
      ],
      hint: "le api = the bees (plural of l'ape); fanno = they make (fare); il miele = the honey",
      tags: ["sentence", "animal", "insect", "fare", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-015"],
    },
    {
      id: "a114-t3-005",
      type: "produce",
      prompt: "The dolphin swims in the sea.",
      accepted: [
        "Il delfino nuota nel mare.",
        "Il delfino nuota nel mare",
        "Il delfino nuota in mare.",
        "Il delfino nuota in mare",
      ],
      hint: "nuotare = to swim; nel mare = in the sea",
      tags: ["sentence", "animal", "sea", "nuotare", "tier3"],
      tier: 3,
      prerequisites: ["a114-t1-022"],
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Passage cloze: fable scene
    // -------------------------------------------------------------------------
    {
      id: "a114-t4-001",
      type: "passage_cloze",
      prompt: "Nel bosco vivono molti animali. La volpe è furba e veloce.\nL'orso è grande e forte. Ma il più piccolo di tutti è il ___,\nche vive vicino al fiume e salta da una pietra all'altra tutto il giorno.",
      accepted: ["ranocchio", "la rana", "rana"],
      hint: "a small jumping amphibian that lives near water — feminine noun",
      tags: ["passage_cloze", "animal", "nature", "fable", "tier4"],
      tier: 4,
      prerequisites: [
        "a114-t1-013", // la rana
        "a114-t1-017", // l'orso
        "a114-t1-019", // la volpe
      ],
    },
  ],
};

export default unit;
