import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-09-colors",
  name: "Colors",
  level: "A1",
  theme: "Colors & Adjective Agreement",
  emoji: "🎨",
  prerequisiteUnits: ["a1-unit-06-describing"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: basic colors
    // Pattern: odd IDs = recognize, even IDs = produce
    // -------------------------------------------------------------------------
    {
      id: "a109-t1-001",
      type: "recognize",
      prompt: "rosso / rossa",
      accepted: ["red"],
      translations: { "es": ["rojo", "roja"] },
      hint: "agree with noun: rosso (m.) / rossa (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-002",
      type: "produce",
      prompt: "red",
      accepted: ["rosso", "rossa"],
      prompts: { "es": "rojo/a" },
      hint: "rosso (m.) / rossa (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-003",
      type: "recognize",
      prompt: "blu",
      accepted: ["blue"],
      translations: { "es": ["azul"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-004",
      type: "produce",
      prompt: "blue",
      accepted: ["blu"],
      prompts: { "es": "azul" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-005",
      type: "recognize",
      prompt: "giallo / gialla",
      accepted: ["yellow"],
      translations: { "es": ["amarillo", "amarilla"] },
      hint: "giallo (m.) / gialla (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-006",
      type: "produce",
      prompt: "yellow",
      accepted: ["giallo", "gialla"],
      prompts: { "es": "amarillo/a" },
      hint: "giallo (m.) / gialla (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-007",
      type: "recognize",
      prompt: "verde",
      accepted: ["green"],
      translations: { "es": ["verde"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-008",
      type: "produce",
      prompt: "green",
      accepted: ["verde"],
      prompts: { "es": "verde" },
      hint: "verde — no gender agreement",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-009",
      type: "recognize",
      prompt: "bianco / bianca",
      accepted: ["white"],
      translations: { "es": ["blanco", "blanca"] },
      hint: "bianco (m.) / bianca (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-010",
      type: "produce",
      prompt: "white",
      accepted: ["bianco", "bianca"],
      prompts: { "es": "blanco/a" },
      hint: "bianco (m.) / bianca (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-011",
      type: "recognize",
      prompt: "nero / nera",
      accepted: ["black"],
      translations: { "es": ["negro", "negra"] },
      hint: "nero (m.) / nera (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-012",
      type: "produce",
      prompt: "black",
      accepted: ["nero", "nera"],
      prompts: { "es": "negro/a" },
      hint: "nero (m.) / nera (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-013",
      type: "recognize",
      prompt: "rosa",
      accepted: ["pink"],
      translations: { "es": ["rosa"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-014",
      type: "produce",
      prompt: "pink",
      accepted: ["rosa"],
      prompts: { "es": "rosa" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-015",
      type: "recognize",
      prompt: "viola",
      accepted: ["purple", "violet"],
      translations: { "es": ["morado", "morada"] },
      hint: "invariable — viola for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-016",
      type: "produce",
      prompt: "purple / violet",
      accepted: ["viola"],
      prompts: { "es": "morado/a" },
      hint: "invariable — no gender agreement",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-017",
      type: "recognize",
      prompt: "arancione",
      accepted: ["orange"],
      translations: { "es": ["naranja"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-018",
      type: "produce",
      prompt: "orange (color)",
      accepted: ["arancione"],
      prompts: { "es": "naranja" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-019",
      type: "recognize",
      prompt: "marrone",
      accepted: ["brown"],
      translations: { "es": ["marrón"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-020",
      type: "produce",
      prompt: "brown",
      accepted: ["marrone"],
      prompts: { "es": "marrón" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-021",
      type: "recognize",
      prompt: "grigio / grigia",
      accepted: ["grey", "gray"],
      translations: { "es": ["gris"] },
      hint: "grigio (m.) / grigia (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-022",
      type: "produce",
      prompt: "grey / gray",
      accepted: ["grigio", "grigia"],
      prompts: { "es": "gris" },
      hint: "grigio (m.) / grigia (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-023",
      type: "recognize",
      prompt: "azzurro / azzurra",
      accepted: ["light blue", "sky blue", "azure"],
      translations: { "es": ["azul cielo", "celeste"] },
      hint: "azzurro (m.) / azzurra (f.) — lighter than blu",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-024",
      type: "produce",
      prompt: "light blue / sky blue",
      accepted: ["azzurro", "azzurra"],
      prompts: { "es": "azul cielo" },
      hint: "azzurro (m.) / azzurra (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-025",
      type: "recognize",
      prompt: "beige",
      accepted: ["beige"],
      translations: { "es": ["beige"] },
      hint: "invariable — borrowed from French",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-026",
      type: "recognize",
      prompt: "dorato / dorata",
      accepted: ["golden", "gold"],
      translations: { "es": ["dorado", "dorada"] },
      hint: "dorato (m.) / dorata (f.) — from oro (gold)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-027",
      type: "recognize",
      prompt: "argentato / argentata",
      accepted: ["silver", "silvery"],
      translations: { "es": ["plateado", "plateada"] },
      hint: "argentato (m.) / argentata (f.) — from argento (silver)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-028",
      type: "recognize",
      prompt: "Di che colore è?",
      accepted: ["What color is it?", "What colour is it?"],
      translations: { "es": ["¿De qué color es?"] },
      hint: "di che = of what; colore = color",
      tags: ["phrase", "color", "question", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-029",
      type: "produce",
      prompt: "What color is it?",
      accepted: ["Di che colore è?", "Di che colore è"],
      prompts: { "es": "¿De qué color es?" },
      hint: "di che colore + è = of what color is it",
      tags: ["phrase", "color", "question", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-030",
      type: "recognize",
      prompt: "a colori",
      accepted: ["in color", "in colour", "color (as adjective)"],
      translations: { "es": ["en color"] },
      hint: "una foto a colori = a color photo",
      tags: ["phrase", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-031",
      type: "recognize",
      prompt: "in bianco e nero",
      accepted: ["in black and white", "black and white"],
      translations: { "es": ["en blanco y negro"] },
      hint: "un film in bianco e nero = a black-and-white film",
      tags: ["phrase", "color", "tier1", "A1"],
      tier: 1,
    },

    // --- Extended vocabulary (seq 100–173) ---
    {
      id: "a109-t1-100",
      type: "produce",
      prompt: "beige",
      accepted: ["beige"],
      prompts: { "es": "beige" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-101",
      type: "produce",
      prompt: "golden / gold (color)",
      accepted: ["dorato", "dorata"],
      prompts: { "es": "dorado/a" },
      hint: "dorato (m.) / dorata (f.) — from oro (gold)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-102",
      type: "produce",
      prompt: "silver / silvery",
      accepted: ["argentato", "argentata"],
      prompts: { "es": "plateado/a" },
      hint: "argentato (m.) / argentata (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-103",
      type: "produce",
      prompt: "in color (as in a color photo or film)",
      accepted: ["a colori"],
      prompts: { "es": "en color" },
      hint: "una foto a colori = a color photo",
      tags: ["phrase", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-150",
      type: "recognize",
      prompt: "chiaro / chiara",
      accepted: ["light", "pale", "light-colored"],
      translations: { "es": ["claro", "clara"] },
      hint: "chiaro (m.) / chiara (f.) — also means 'clear'",
      tags: ["adjective", "color", "modifier", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-151",
      type: "produce",
      prompt: "light / pale (as a color modifier)",
      accepted: ["chiaro", "chiara"],
      prompts: { "es": "claro/a" },
      hint: "blu chiaro = light blue; also means 'clear'",
      tags: ["adjective", "color", "modifier", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-152",
      type: "recognize",
      prompt: "scuro / scura",
      accepted: ["dark"],
      translations: { "es": ["oscuro", "oscura"] },
      hint: "scuro (m.) / scura (f.) — opposite of chiaro",
      tags: ["adjective", "color", "modifier", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-153",
      type: "produce",
      prompt: "dark (as a color modifier)",
      accepted: ["scuro", "scura"],
      prompts: { "es": "oscuro/a" },
      hint: "blu scuro = dark blue; opposite of chiaro",
      tags: ["adjective", "color", "modifier", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-154",
      type: "recognize",
      prompt: "il colore",
      accepted: ["the color", "color", "the colour", "colour"],
      translations: { "es": ["el color"] },
      hint: "plural: i colori",
      tags: ["noun", "masculine", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-155",
      type: "produce",
      prompt: "color (noun)",
      accepted: ["il colore"],
      prompts: { "es": "el color" },
      hint: "masculine noun — plural: i colori",
      tags: ["noun", "masculine", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-156",
      type: "recognize",
      prompt: "colorato / colorata",
      accepted: ["colorful", "colored", "in color"],
      translations: { "es": ["colorido", "colorida"] },
      hint: "colorato (m.) / colorata (f.) — from colore",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-157",
      type: "produce",
      prompt: "colorful / colored",
      accepted: ["colorato", "colorata"],
      prompts: { "es": "colorido/a" },
      hint: "colorato (m.) / colorata (f.)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-158",
      type: "recognize",
      prompt: "preferito / preferita",
      accepted: ["favorite", "favourite", "preferred"],
      translations: { "es": ["favorito", "favorita"] },
      hint: "preferito (m.) / preferita (f.) — from preferire",
      tags: ["adjective", "opinion", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-159",
      type: "produce",
      prompt: "favorite / favourite",
      accepted: ["preferito", "preferita"],
      prompts: { "es": "favorito/a" },
      hint: "preferito (m.) / preferita (f.)",
      tags: ["adjective", "opinion", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-160",
      type: "recognize",
      prompt: "brillante",
      accepted: ["bright", "shiny", "brilliant", "sparkling"],
      translations: { "es": ["brillante"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-161",
      type: "produce",
      prompt: "bright / shiny",
      accepted: ["brillante"],
      prompts: { "es": "brillante" },
      hint: "invariable — same root as 'brilliant'",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-162",
      type: "recognize",
      prompt: "turchese",
      accepted: ["turquoise"],
      translations: { "es": ["turquesa"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-163",
      type: "produce",
      prompt: "turquoise",
      accepted: ["turchese"],
      prompts: { "es": "turquesa" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-164",
      type: "recognize",
      prompt: "bordeaux",
      accepted: ["burgundy", "wine red", "bordeaux"],
      translations: { "es": ["burdeos"] },
      hint: "invariable — borrowed from French wine region",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-165",
      type: "produce",
      prompt: "burgundy / wine red",
      accepted: ["bordeaux"],
      prompts: { "es": "burdeos" },
      hint: "invariable — from the Bordeaux wine region",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-166",
      type: "recognize",
      prompt: "lilla",
      accepted: ["lilac", "lavender (color)"],
      translations: { "es": ["lila"] },
      hint: "invariable — same for m. and f.",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-167",
      type: "produce",
      prompt: "lilac / lavender (color)",
      accepted: ["lilla"],
      prompts: { "es": "lila" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-168",
      type: "recognize",
      prompt: "avorio",
      accepted: ["ivory"],
      translations: { "es": ["marfil"] },
      hint: "invariable — from 'avorio' (elephant ivory)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-169",
      type: "produce",
      prompt: "ivory (color)",
      accepted: ["avorio"],
      prompts: { "es": "marfil" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-170",
      type: "recognize",
      prompt: "corallo",
      accepted: ["coral"],
      translations: { "es": ["coral"] },
      hint: "invariable — from the sea creature",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-171",
      type: "produce",
      prompt: "coral (color)",
      accepted: ["corallo"],
      prompts: { "es": "coral" },
      hint: "invariable — no agreement needed",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-172",
      type: "recognize",
      prompt: "celeste",
      accepted: ["sky blue", "pale blue", "light blue (celestial)"],
      translations: { "es": ["celeste"] },
      hint: "invariable — from 'cielo' (sky)",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a109-t1-173",
      type: "produce",
      prompt: "sky blue / pale blue (lighter than azzurro)",
      accepted: ["celeste"],
      prompts: { "es": "celeste" },
      hint: "invariable — celestial, heavenly blue",
      tags: ["adjective", "color", "tier1", "A1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Grammar: adjective agreement drills (fill_blank — skip all)
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // TIER 3 — Chunks: color phrases
    // -------------------------------------------------------------------------
    {
      id: "a109-t3-001",
      type: "produce",
      prompt: "the red car",
      accepted: ["la macchina rossa", "l'auto rossa"],
      prompts: { "es": "el coche rojo" },
      hint: "macchina is feminine — rossa",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-002",
      type: "produce",
      prompt: "a blue shirt",
      accepted: ["una camicia blu"],
      prompts: { "es": "una camisa azul" },
      hint: "blu is invariable — no agreement",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-003",
      type: "produce",
      prompt: "What color is it?",
      accepted: ["Di che colore è?"],
      prompts: { "es": "¿De qué color es?" },
      hint: "di che colore = of what color",
      tags: ["chunk", "color", "question", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-004",
      type: "produce",
      prompt: "I like green.",
      accepted: ["Mi piace il verde."],
      prompts: { "es": "Me gusta el verde." },
      hint: "il verde = the color green (noun use of adjective)",
      tags: ["chunk", "color", "piacere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-005",
      type: "produce",
      prompt: "black and white",
      accepted: ["bianco e nero", "in bianco e nero"],
      prompts: { "es": "blanco y negro" },
      hint: "bianco e nero — m. forms (generic phrase)",
      tags: ["chunk", "color", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-100",
      type: "produce",
      prompt: "a green dress",
      accepted: ["un vestito verde"],
      prompts: { "es": "un vestido verde" },
      hint: "verde is invariable — no agreement needed",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-101",
      type: "produce",
      prompt: "yellow flowers",
      accepted: ["fiori gialli"],
      prompts: { "es": "flores amarillas" },
      hint: "fiori (m. pl.) → gialli",
      tags: ["chunk", "color", "agreement", "plural", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-102",
      type: "produce",
      prompt: "a white house",
      accepted: ["una casa bianca"],
      prompts: { "es": "una casa blanca" },
      hint: "casa (f.) → bianca",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-103",
      type: "produce",
      prompt: "It is pink.",
      accepted: ["È rosa."],
      prompts: { "es": "Es rosa." },
      hint: "rosa is invariable — no agreement",
      tags: ["chunk", "color", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-104",
      type: "produce",
      prompt: "My favorite color is blue.",
      accepted: ["Il mio colore preferito è il blu.", "Il mio colore preferito è blu."],
      prompts: { "es": "Mi color favorito es el azul." },
      hint: "colore (m.) → preferito; il blu = the color blue",
      tags: ["chunk", "color", "opinion", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-105",
      type: "produce",
      prompt: "The sky is light blue.",
      accepted: ["Il cielo è azzurro.", "Il cielo è celeste."],
      prompts: { "es": "El cielo es azul cielo." },
      hint: "il cielo (m.) → azzurro; invariable nouns (blu/rosa) don't change",
      tags: ["chunk", "color", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-106",
      type: "produce",
      prompt: "a dark jacket",
      accepted: ["una giacca scura"],
      prompts: { "es": "una chaqueta oscura" },
      hint: "giacca (f.) → scura",
      tags: ["chunk", "color", "modifier", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-107",
      type: "produce",
      prompt: "light colors",
      accepted: ["i colori chiari"],
      prompts: { "es": "colores claros" },
      hint: "colori (m. pl.) → chiari",
      tags: ["chunk", "color", "modifier", "plural", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-108",
      type: "produce",
      prompt: "black shoes",
      accepted: ["scarpe nere"],
      prompts: { "es": "zapatos negros" },
      hint: "scarpe (f. pl.) → nere",
      tags: ["chunk", "color", "agreement", "plural", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-109",
      type: "produce",
      prompt: "purple flowers",
      accepted: ["fiori viola"],
      prompts: { "es": "flores moradas" },
      hint: "viola is invariable — no agreement",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-110",
      type: "produce",
      prompt: "I do not like orange.",
      accepted: ["Non mi piace l'arancione.", "Non mi piace l'arancio."],
      prompts: { "es": "No me gusta el naranja." },
      hint: "non mi piace + color noun",
      tags: ["chunk", "color", "piacere", "negation", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-111",
      type: "produce",
      prompt: "His shirt is pink.",
      accepted: ["La sua camicia è rosa."],
      prompts: { "es": "Su camisa es rosa." },
      hint: "camicia (f.); rosa is invariable",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-112",
      type: "produce",
      prompt: "We prefer dark colors.",
      accepted: ["Preferiamo i colori scuri."],
      prompts: { "es": "Preferimos los colores oscuros." },
      hint: "preferiamo = we prefer (noi form); colori (m. pl.) → scuri",
      tags: ["chunk", "color", "modifier", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-113",
      type: "produce",
      prompt: "The walls are grey.",
      accepted: ["Le pareti sono grigie.", "I muri sono grigi."],
      prompts: { "es": "Las paredes son grises." },
      hint: "pareti (f. pl.) → grigie; muri (m. pl.) → grigi",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-114",
      type: "produce",
      prompt: "dark blue",
      accepted: ["blu scuro", "azzurro scuro"],
      prompts: { "es": "azul oscuro" },
      hint: "blu is invariable; scuro (m.) agrees with the implied noun",
      tags: ["chunk", "color", "modifier", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a109-t3-115",
      type: "produce",
      prompt: "a colorful market",
      accepted: ["un mercato colorato"],
      prompts: { "es": "un mercado colorido" },
      hint: "mercato (m.) → colorato",
      tags: ["chunk", "color", "agreement", "tier3", "A1"],
      tier: 3,
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Sentences (passage_cloze and fill_blank skipped)
    // -------------------------------------------------------------------------
    {
      id: "a109-t4-100",
      type: "produce",
      prompt: "The apple is red.",
      accepted: ["La mela è rossa."],
      prompts: { "es": "La manzana es roja." },
      hint: "la mela (f.) → rossa",
      tags: ["sentence", "color", "agreement", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-101",
      type: "produce",
      prompt: "My jacket is dark blue.",
      accepted: ["La mia giacca è blu scuro.", "La mia giacca è blu scura."],
      prompts: { "es": "Mi chaqueta es azul oscuro." },
      hint: "blu is invariable; scuro agrees with giacca (f.) → scura",
      tags: ["sentence", "color", "modifier", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-102",
      type: "produce",
      prompt: "What color is your car?",
      accepted: ["Di che colore è la tua macchina?", "Di che colore è la tua auto?"],
      prompts: { "es": "¿De qué color es tu coche?" },
      hint: "di che colore è = what color is",
      tags: ["sentence", "color", "question", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-103",
      type: "produce",
      prompt: "I have a black cat and a white dog.",
      accepted: ["Ho un gatto nero e un cane bianco."],
      prompts: { "es": "Tengo un gato negro y un perro blanco." },
      hint: "gatto (m.) → nero; cane (m.) → bianco",
      tags: ["sentence", "color", "agreement", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-105",
      type: "produce",
      prompt: "Marco wears a grey shirt every day.",
      accepted: ["Marco porta una camicia grigia ogni giorno."],
      prompts: { "es": "Marco lleva una camisa gris todos los días." },
      hint: "camicia (f.) → grigia; ogni giorno = every day",
      tags: ["sentence", "color", "agreement", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-106",
      type: "produce",
      prompt: "The sky is clear and light blue today.",
      accepted: ["Il cielo è limpido e azzurro oggi.", "Il cielo è chiaro e azzurro oggi."],
      prompts: { "es": "El cielo está despejado y azul cielo hoy." },
      hint: "cielo (m.) → azzurro; limpido = clear/limpid",
      tags: ["sentence", "color", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-108",
      type: "produce",
      prompt: "Anna's dress is green and her shoes are black.",
      accepted: ["Il vestito di Anna è verde e le scarpe sono nere."],
      prompts: { "es": "El vestido de Anna es verde y sus zapatos son negros." },
      hint: "verde invariable; scarpe (f. pl.) → nere",
      tags: ["sentence", "color", "agreement", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-109",
      type: "produce",
      prompt: "I prefer light colors in summer.",
      accepted: ["Preferisco i colori chiari in estate."],
      prompts: { "es": "Prefiero los colores claros en verano." },
      hint: "colori (m. pl.) → chiari; in estate = in summer",
      tags: ["sentence", "color", "modifier", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-111",
      type: "produce",
      prompt: "These trousers are dark grey.",
      accepted: ["Questi pantaloni sono grigio scuro.", "Questi pantaloni sono grigi scuri."],
      prompts: { "es": "Estos pantalones son gris oscuro." },
      hint: "pantaloni (m. pl.) → grigio scuro (compound color, often invariable)",
      tags: ["sentence", "color", "modifier", "tier4", "A1"],
      tier: 4,
    },
    {
      id: "a109-t4-112",
      type: "produce",
      prompt: "She wears a golden necklace every day.",
      accepted: ["Porta una collana dorata ogni giorno."],
      prompts: { "es": "Lleva un collar dorado todos los días." },
      hint: "collana (f.) → dorata; ogni giorno = every day",
      tags: ["sentence", "color", "agreement", "tier4", "A1"],
      tier: 4,
    },
  ],
};

export default unit;
