import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-12-emotions",
  name: "Emotions",
  level: "A1",
  theme: "Feelings & Personality",
  emoji: "😊",
  prerequisiteUnits: ["a1-unit-11-food"],
  cards: [
    // ── TIER 1: VOCABULARY — Produce (English → Italian) ──────────────────

    {
      id: "a112-t1-001",
      type: "produce",
      prompt: "happy",
      accepted: ["felice"],
      prompts: { "es": "feliz" },
      hint: "Same m/f — felice. Plural: felici.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-002",
      type: "produce",
      prompt: "sad",
      accepted: ["triste"],
      prompts: { "es": "triste" },
      hint: "Same m/f — triste. Plural: tristi.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-003",
      type: "produce",
      prompt: "angry (m)",
      accepted: ["arrabbiato"],
      prompts: { "es": "enojado" },
      hint: "-ato ending = masculine",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-004",
      type: "produce",
      prompt: "tired (m)",
      accepted: ["stanco"],
      prompts: { "es": "cansado" },
      hint: "stanco (m) / stanca (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-005",
      type: "produce",
      prompt: "bored (m)",
      accepted: ["annoiato"],
      prompts: { "es": "aburrido" },
      hint: "annoiato (m) / annoiata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-006",
      type: "produce",
      prompt: "scared / frightened (m)",
      accepted: ["spaventato"],
      prompts: { "es": "asustado" },
      hint: "spaventato (m) / spaventata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-007",
      type: "produce",
      prompt: "surprised (m)",
      accepted: ["sorpreso"],
      prompts: { "es": "sorprendido" },
      hint: "sorpreso (m) / sorpresa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-008",
      type: "produce",
      prompt: "nervous",
      accepted: ["nervoso", "nervosa"],
      prompts: { "es": "nervioso" },
      hint: "nervoso (m) / nervosa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-009",
      type: "produce",
      prompt: "content / pleased (m)",
      accepted: ["contento"],
      prompts: { "es": "contento" },
      hint: "contento (m) / contenta (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-010",
      type: "produce",
      prompt: "worried (m)",
      accepted: ["preoccupato"],
      prompts: { "es": "preocupado" },
      hint: "preoccupato (m) / preoccupata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-011",
      type: "produce",
      prompt: "calm / peaceful (m)",
      accepted: ["tranquillo"],
      prompts: { "es": "tranquilo" },
      hint: "tranquillo (m) / tranquilla (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-012",
      type: "produce",
      prompt: "jealous (m)",
      accepted: ["geloso"],
      prompts: { "es": "celoso" },
      hint: "geloso (m) / gelosa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-013",
      type: "produce",
      prompt: "in love (m)",
      accepted: ["innamorato"],
      prompts: { "es": "enamorado" },
      hint: "innamorato (m) / innamorata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-014",
      type: "produce",
      prompt: "disappointed (m)",
      accepted: ["deluso"],
      prompts: { "es": "decepcionado" },
      hint: "deluso (m) / delusa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-015",
      type: "produce",
      prompt: "proud (m)",
      accepted: ["orgoglioso"],
      prompts: { "es": "orgulloso" },
      hint: "orgoglioso (m) / orgogliosa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-016",
      type: "produce",
      prompt: "embarrassed (m)",
      accepted: ["imbarazzato"],
      prompts: { "es": "avergonzado" },
      hint: "imbarazzato (m) / imbarazzata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-017",
      type: "produce",
      prompt: "curious (m)",
      accepted: ["curioso"],
      prompts: { "es": "curioso" },
      hint: "curioso (m) / curiosa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-018",
      type: "produce",
      prompt: "confused (m)",
      accepted: ["confuso"],
      prompts: { "es": "confundido" },
      hint: "confuso (m) / confusa (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-019",
      type: "produce",
      prompt: "enthusiastic",
      accepted: ["entusiasta"],
      prompts: { "es": "entusiasta" },
      hint: "Same m/f — entusiasta. Plural: entusiasti/e.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-020",
      type: "produce",
      prompt: "alone / lonely (m)",
      accepted: ["solo"],
      prompts: { "es": "solo" },
      hint: "solo (m) / sola (f). Also means 'only'.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-021",
      type: "produce",
      prompt: "grateful (m)",
      accepted: ["grato"],
      prompts: { "es": "agradecido" },
      hint: "grato (m) / grata (f). Think 'gratitude'.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-022",
      type: "produce",
      prompt: "optimistic",
      accepted: ["ottimista"],
      prompts: { "es": "optimista" },
      hint: "Same m/f — ottimista.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-023",
      type: "produce",
      prompt: "stressed (m)",
      accepted: ["stressato"],
      prompts: { "es": "estresado" },
      hint: "stressato (m) / stressata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-024",
      type: "produce",
      prompt: "sorry / upset (m)",
      accepted: ["dispiaciuto"],
      prompts: { "es": "disgustado" },
      hint: "dispiaciuto (m) / dispiaciuta (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-025",
      type: "produce",
      prompt: "relaxed (m)",
      accepted: ["rilassato"],
      prompts: { "es": "relajado" },
      hint: "rilassato (m) / rilassata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-026",
      type: "produce",
      prompt: "excited / emotional (m)",
      accepted: ["emozionato"],
      prompts: { "es": "emocionado" },
      hint: "emozionato (m) / emozionata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-027",
      type: "produce",
      prompt: "agitated / anxious (m)",
      accepted: ["agitato"],
      prompts: { "es": "agitado" },
      hint: "agitato (m) / agitata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-028",
      type: "produce",
      prompt: "well / fine",
      accepted: ["bene"],
      prompts: { "es": "bien" },
      hint: "Adverb — sto bene (I'm fine)",
      tags: ["adverb", "emotion", "A1"],
      tier: 1,
    },

    // ── TIER 1: VOCABULARY — Recognize (Italian → English) ────────────────

    {
      id: "a112-t1-101",
      type: "recognize",
      prompt: "felice",
      accepted: ["happy", "glad"],
      translations: { "es": ["feliz"] },
      hint: "same m/f form",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-102",
      type: "recognize",
      prompt: "triste",
      accepted: ["sad", "unhappy"],
      translations: { "es": ["triste"] },
      hint: "same m/f form",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-103",
      type: "recognize",
      prompt: "arrabbiato / arrabbiata",
      accepted: ["angry", "mad"],
      translations: { "es": ["enojado", "enfadado"] },
      hint: "-ato (m) / -ata (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-104",
      type: "recognize",
      prompt: "stanco / stanca",
      accepted: ["tired", "exhausted"],
      translations: { "es": ["cansado"] },
      hint: "-o (m) / -a (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-105",
      type: "recognize",
      prompt: "annoiato / annoiata",
      accepted: ["bored"],
      translations: { "es": ["aburrido"] },
      hint: "-ato/-ata gender pair",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-106",
      type: "recognize",
      prompt: "spaventato / spaventata",
      accepted: ["scared", "frightened", "afraid"],
      translations: { "es": ["asustado"] },
      hint: "from spaventare (to frighten)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-107",
      type: "recognize",
      prompt: "sorpreso / sorpresa",
      accepted: ["surprised"],
      translations: { "es": ["sorprendido"] },
      hint: "sorpresa also = surprise (noun)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-108",
      type: "recognize",
      prompt: "nervoso / nervosa",
      accepted: ["nervous", "anxious"],
      translations: { "es": ["nervioso"] },
      hint: "think 'nervous' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-109",
      type: "recognize",
      prompt: "contento / contenta",
      accepted: ["content", "pleased", "happy"],
      translations: { "es": ["contento"] },
      hint: "think 'content' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-110",
      type: "recognize",
      prompt: "preoccupato / preoccupata",
      accepted: ["worried", "anxious", "concerned"],
      translations: { "es": ["preocupado"] },
      hint: "think 'preoccupied'",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-111",
      type: "recognize",
      prompt: "tranquillo / tranquilla",
      accepted: ["calm", "peaceful", "quiet"],
      translations: { "es": ["tranquilo"] },
      hint: "think 'tranquil'",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-112",
      type: "recognize",
      prompt: "geloso / gelosa",
      accepted: ["jealous"],
      translations: { "es": ["celoso"] },
      hint: "think 'zeal' — same Latin root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-113",
      type: "recognize",
      prompt: "innamorato / innamorata",
      accepted: ["in love"],
      translations: { "es": ["enamorado"] },
      hint: "from amore (love)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-114",
      type: "recognize",
      prompt: "deluso / delusa",
      accepted: ["disappointed"],
      translations: { "es": ["decepcionado"] },
      hint: "think 'disillusioned'",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-115",
      type: "recognize",
      prompt: "orgoglioso / orgogliosa",
      accepted: ["proud"],
      translations: { "es": ["orgulloso"] },
      hint: "orgoglio = pride (noun)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-116",
      type: "recognize",
      prompt: "imbarazzato / imbarazzata",
      accepted: ["embarrassed"],
      translations: { "es": ["avergonzado"] },
      hint: "imbarazzo = embarrassment",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-117",
      type: "recognize",
      prompt: "curioso / curiosa",
      accepted: ["curious"],
      translations: { "es": ["curioso"] },
      hint: "think 'curious' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-118",
      type: "recognize",
      prompt: "confuso / confusa",
      accepted: ["confused"],
      translations: { "es": ["confundido"] },
      hint: "think 'confused' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-119",
      type: "recognize",
      prompt: "entusiasta",
      accepted: ["enthusiastic"],
      translations: { "es": ["entusiasta"] },
      hint: "same m/f form",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-120",
      type: "recognize",
      prompt: "solo / sola",
      accepted: ["alone", "lonely", "only"],
      translations: { "es": ["solo"] },
      hint: "context tells you which meaning",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-121",
      type: "recognize",
      prompt: "grato / grata",
      accepted: ["grateful", "thankful"],
      translations: { "es": ["agradecido"] },
      hint: "gratitudine = gratitude",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-122",
      type: "recognize",
      prompt: "ottimista",
      accepted: ["optimistic"],
      translations: { "es": ["optimista"] },
      hint: "same m/f form",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-123",
      type: "recognize",
      prompt: "stressato / stressata",
      accepted: ["stressed", "stressed out"],
      translations: { "es": ["estresado"] },
      hint: "-ato/-ata ending",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-124",
      type: "recognize",
      prompt: "dispiaciuto / dispiaciuta",
      accepted: ["sorry", "upset", "regretful"],
      translations: { "es": ["disgustado", "apenado"] },
      hint: "from piacere with dis- negative prefix",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-125",
      type: "recognize",
      prompt: "rilassato / rilassata",
      accepted: ["relaxed"],
      translations: { "es": ["relajado"] },
      hint: "think 'relaxed' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-126",
      type: "recognize",
      prompt: "emozionato / emozionata",
      accepted: ["excited", "emotional", "moved"],
      translations: { "es": ["emocionado"] },
      hint: "emozione = emotion",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-127",
      type: "recognize",
      prompt: "agitato / agitata",
      accepted: ["agitated", "anxious", "flustered"],
      translations: { "es": ["agitado"] },
      hint: "think 'agitated' — same root",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-128",
      type: "recognize",
      prompt: "bene",
      accepted: ["well", "fine", "good"],
      translations: { "es": ["bien"] },
      hint: "adverb — sto bene = I'm fine",
      tags: ["adverb", "emotion", "A1"],
      tier: 1,
    },

    // ── TIER 1: VOCABULARY — Personality (continued) ──────────────────────

    {
      id: "a112-t1-129",
      type: "produce",
      prompt: "nice / likeable (m)",
      accepted: ["simpatico"],
      prompts: { "es": "simpático" },
      hint: "simpatico (m) / simpatica (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-130",
      type: "recognize",
      prompt: "simpatico / simpatica",
      accepted: ["nice", "likeable", "pleasant"],
      translations: { "es": ["simpático"] },
      hint: "-o (m) / -a (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-131",
      type: "produce",
      prompt: "kind",
      accepted: ["gentile"],
      prompts: { "es": "amable" },
      hint: "Same m/f — gentile. Plural: gentili.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-132",
      type: "recognize",
      prompt: "gentile",
      accepted: ["kind"],
      translations: { "es": ["amable"] },
      hint: "same m/f form",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-133",
      type: "produce",
      prompt: "shy (m)",
      accepted: ["timido"],
      prompts: { "es": "tímido" },
      hint: "timido (m) / timida (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-134",
      type: "recognize",
      prompt: "timido / timida",
      accepted: ["shy"],
      translations: { "es": ["tímido"] },
      hint: "-o (m) / -a (f)",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-135",
      type: "produce",
      prompt: "patient",
      accepted: ["paziente"],
      prompts: { "es": "paciente" },
      hint: "Same m/f — paziente. Plural: pazienti.",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },
    {
      id: "a112-t1-136",
      type: "recognize",
      prompt: "paziente",
      accepted: ["patient"],
      translations: { "es": ["paciente"] },
      hint: "same m/f form — think 'patience'",
      tags: ["adjective", "emotion", "A1"],
      tier: 1,
    },

    // ── TIER 2: GRAMMAR ───────────────────────────────────────────────────

    {
      id: "a112-t2-001",
      type: "conjugate",
      prompt: "Conjugate 'stare' (to be / to feel) — all six persons",
      accepted: ["io sto, tu stai, lui/lei sta, noi stiamo, voi state, loro stanno"],
      hint: "Irregular — sto, stai, sta, stiamo, state, stanno",
      tags: ["verb", "stare", "grammar", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-002",
      type: "fill_blank",
      prompt: "Come ___ oggi, Marco? — Sto bene, grazie.",
      accepted: ["stai"],
      hint: "tu form of stare",
      tags: ["grammar", "stare", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-003",
      type: "fill_blank",
      prompt: "I bambini non ___ bene — sono tutti malati.",
      accepted: ["stanno"],
      hint: "loro form of stare",
      tags: ["grammar", "stare", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-004",
      type: "fill_blank",
      prompt: "Noi ___ benissimo qui in vacanza.",
      accepted: ["stiamo"],
      hint: "noi form of stare",
      tags: ["grammar", "stare", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-005",
      type: "conjugate",
      prompt: "Conjugate 'sentirsi' (to feel) — all six persons",
      accepted: ["io mi sento, tu ti senti, lui/lei si sente, noi ci sentiamo, voi vi sentite, loro si sentono"],
      hint: "Reflexive: mi/ti/si/ci/vi/si before sento/senti/sente...",
      tags: ["verb", "sentirsi", "reflexive", "grammar", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-006",
      type: "fill_blank",
      prompt: "Mi ___ molto felice oggi perché è il mio compleanno.",
      accepted: ["sento"],
      hint: "io form of sentirsi",
      tags: ["grammar", "sentirsi", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-007",
      type: "fill_blank",
      prompt: "Ti ___ meglio adesso, dopo il riposo?",
      accepted: ["senti"],
      hint: "tu form of sentirsi",
      tags: ["grammar", "sentirsi", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-008",
      type: "fill_blank",
      prompt: "Luisa si ___ stanca dopo il lungo viaggio.",
      accepted: ["sente"],
      hint: "lei form of sentirsi",
      tags: ["grammar", "sentirsi", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-009",
      type: "fill_blank",
      prompt: "Marco ___ stanco — ha lavorato tutto il giorno.",
      accepted: ["sembra"],
      hint: "lui form of sembrare (to seem)",
      tags: ["grammar", "sembrare", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-010",
      type: "fill_blank",
      prompt: "I tuoi genitori ___ molto felici della tua laurea.",
      accepted: ["sembrano"],
      hint: "loro form of sembrare",
      tags: ["grammar", "sembrare", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-011",
      type: "fill_blank",
      prompt: "Il bambino è molto ___. (tired)",
      accepted: ["stanco"],
      hint: "masculine singular — stanco",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-012",
      type: "fill_blank",
      prompt: "La bambina è molto ___. (tired)",
      accepted: ["stanca"],
      hint: "feminine singular — stanca",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-013",
      type: "fill_blank",
      prompt: "I ragazzi sono ___. (worried)",
      accepted: ["preoccupati"],
      hint: "masculine plural — preoccupati",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-014",
      type: "fill_blank",
      prompt: "Le ragazze sono ___. (worried)",
      accepted: ["preoccupate"],
      hint: "feminine plural — preoccupate",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-015",
      type: "fill_blank",
      prompt: "Sono ___ di te. (proud — male speaker)",
      accepted: ["orgoglioso"],
      hint: "speaker masculine → orgoglioso",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-016",
      type: "fill_blank",
      prompt: "Perché sei così ___? (angry — addressing a man)",
      accepted: ["arrabbiato"],
      hint: "masculine singular — arrabbiato",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-017",
      type: "fill_blank",
      prompt: "Mi sento ___ quando non dormo abbastanza. (exhausted — female speaker)",
      accepted: ["stanca"],
      hint: "feminine singular agreement with speaker",
      tags: ["grammar", "adjective-agreement", "sentirsi", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-018",
      type: "fill_blank",
      prompt: "Lei sembra ___ del risultato. (disappointed)",
      accepted: ["delusa"],
      hint: "feminine singular — delusa",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-019",
      type: "fill_blank",
      prompt: "Sono ___ di conoscerla. (pleased — male speaker)",
      accepted: ["contento"],
      hint: "masculine singular — contento",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-020",
      type: "fill_blank",
      prompt: "Gli studenti sembrano ___ per l'esame di domani. (nervous)",
      accepted: ["nervosi"],
      hint: "masculine plural — nervosi",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-021",
      type: "fill_blank",
      prompt: "Il mio vicino è molto ___. Ci aiuta sempre. (kind)",
      accepted: ["gentile"],
      hint: "same m/f form — gentile",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-022",
      type: "fill_blank",
      prompt: "Devi essere più ___ con i bambini piccoli. (patient)",
      accepted: ["paziente"],
      hint: "same m/f form — paziente",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-023",
      type: "fill_blank",
      prompt: "Loro sembrano molto ___ — sorridono sempre a tutti. (nice / likeable, m pl)",
      accepted: ["simpatici"],
      hint: "masculine plural — simpatici",
      tags: ["grammar", "sembrare", "adjective-agreement", "A1"],
      tier: 2,
    },
    {
      id: "a112-t2-024",
      type: "fill_blank",
      prompt: "Sara è molto ___ e non parla con persone nuove. (shy)",
      accepted: ["timida"],
      hint: "feminine singular — timida",
      tags: ["grammar", "adjective-agreement", "A1"],
      tier: 2,
    },

    // ── TIER 3: PHRASES ───────────────────────────────────────────────────

    {
      id: "a112-t3-001",
      type: "produce",
      prompt: "I feel happy today.",
      accepted: ["Mi sento felice oggi.", "Sono felice oggi."],
      prompts: { "es": "Hoy me siento feliz." },
      hint: "sentirsi or essere + adjective",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-002",
      type: "produce",
      prompt: "She seems worried.",
      accepted: ["Sembra preoccupata.", "Lei sembra preoccupata."],
      prompts: { "es": "Parece preocupada." },
      hint: "sembrare + adjective (feminine)",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-003",
      type: "produce",
      prompt: "Are you okay? (informal)",
      accepted: ["Stai bene?", "Va bene?", "Come stai?"],
      prompts: { "es": "¿Estás bien?" },
      hint: "stare bene = to be well",
      tags: ["phrase", "emotion", "question", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-004",
      type: "produce",
      prompt: "I'm very tired.",
      accepted: ["Sono molto stanco.", "Sono molto stanca.", "Mi sento molto stanco.", "Mi sento molto stanca."],
      prompts: { "es": "Estoy muy cansado." },
      hint: "essere/sentirsi + molto + adjective",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-005",
      type: "produce",
      prompt: "Don't worry!",
      accepted: ["Non ti preoccupare!", "Non preoccuparti!"],
      prompts: { "es": "¡No te preocupes!" },
      hint: "preoccuparsi = to worry (reflexive)",
      tags: ["phrase", "emotion", "imperative", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-006",
      type: "produce",
      prompt: "I'm bored.",
      accepted: ["Sono annoiato.", "Sono annoiata.", "Mi annoio."],
      prompts: { "es": "Estoy aburrido." },
      hint: "essere annoiato/a or annoiarsi",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-007",
      type: "produce",
      prompt: "He's in love.",
      accepted: ["È innamorato.", "Lui è innamorato."],
      prompts: { "es": "Está enamorado." },
      hint: "essere innamorato — masculine",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-008",
      type: "produce",
      prompt: "I'm nervous about the exam.",
      accepted: ["Sono nervoso per l'esame.", "Sono nervosa per l'esame."],
      prompts: { "es": "Estoy nervioso por el examen." },
      hint: "nervoso/a + per + noun",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-009",
      type: "produce",
      prompt: "She's proud of her son.",
      accepted: ["È orgogliosa di suo figlio.", "Lei è orgogliosa di suo figlio."],
      prompts: { "es": "Está orgullosa de su hijo." },
      hint: "orgogliosa (f) + di + person",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-010",
      type: "produce",
      prompt: "I'm embarrassed.",
      accepted: ["Sono imbarazzato.", "Sono imbarazzata.", "Mi sento imbarazzato.", "Mi sento imbarazzata."],
      prompts: { "es": "Estoy avergonzado." },
      hint: "essere/sentirsi imbarazzato/a",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-011",
      type: "produce",
      prompt: "We're excited.",
      accepted: ["Siamo emozionati.", "Siamo entusiasti.", "Siamo emozionate."],
      prompts: { "es": "Estamos emocionados." },
      hint: "noi form of essere + adjective",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-012",
      type: "produce",
      prompt: "He's jealous.",
      accepted: ["È geloso.", "Lui è geloso."],
      prompts: { "es": "Está celoso." },
      hint: "essere geloso — masculine",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-013",
      type: "produce",
      prompt: "I'm grateful.",
      accepted: ["Sono grato.", "Sono grata.", "Ti sono grato.", "Ti sono grata."],
      prompts: { "es": "Estoy agradecido." },
      hint: "essere grato/a; optionally + a qualcuno",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-014",
      type: "produce",
      prompt: "She's surprised.",
      accepted: ["È sorpresa.", "Lei è sorpresa.", "Sembra sorpresa."],
      prompts: { "es": "Está sorprendida." },
      hint: "sorpresa — feminine",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-015",
      type: "produce",
      prompt: "I'm confused.",
      accepted: ["Sono confuso.", "Sono confusa.", "Mi sento confuso.", "Mi sento confusa."],
      prompts: { "es": "Estoy confundido." },
      hint: "essere/sentirsi confuso/a",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-016",
      type: "produce",
      prompt: "I can't wait to see you.",
      accepted: ["Non vedo l'ora di vederti."],
      prompts: { "es": "No veo la hora de verte." },
      hint: "non vedere l'ora di + infinitive",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-017",
      type: "produce",
      prompt: "I'm having a bad day.",
      accepted: ["Ho una brutta giornata.", "Sto passando una brutta giornata."],
      prompts: { "es": "Estoy teniendo un mal día." },
      hint: "avere una brutta giornata",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-018",
      type: "produce",
      prompt: "He's in a good mood.",
      accepted: ["È di buon umore.", "Lui è di buon umore."],
      prompts: { "es": "Está de buen humor." },
      hint: "essere di buon umore",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },
    {
      id: "a112-t3-019",
      type: "produce",
      prompt: "She's in a bad mood.",
      accepted: ["È di cattivo umore.", "Lei è di cattivo umore."],
      prompts: { "es": "Está de mal humor." },
      hint: "essere di cattivo umore",
      tags: ["phrase", "emotion", "A1"],
      tier: 3,
    },

    // ── TIER 4: SENTENCES ─────────────────────────────────────────────────

    {
      id: "a112-t4-001",
      type: "produce",
      prompt: "Today I'm very happy because it's my birthday.",
      accepted: ["Oggi sono molto felice perché è il mio compleanno."],
      prompts: { "es": "Hoy estoy muy feliz porque es mi cumpleaños." },
      hint: "felice + perché + è il mio compleanno",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-002",
      type: "produce",
      prompt: "She's tired and a little stressed.",
      accepted: ["È stanca e un po' stressata.", "Lei è stanca e un po' stressata."],
      prompts: { "es": "Está cansada y un poco estresada." },
      hint: "stanca + e + un po' + stressata",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-003",
      type: "produce",
      prompt: "Why are you sad? I'm not sad, I'm just tired.",
      accepted: ["Perché sei triste? Non sono triste, sono solo stanco.", "Perché sei triste? Non sono triste, sono solo stanca."],
      prompts: { "es": "¿Por qué estás triste? No estoy triste, solo estoy cansado." },
      hint: "solo here means 'just/only'",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-004",
      type: "produce",
      prompt: "He's nervous because he has an important meeting.",
      accepted: ["È nervoso perché ha una riunione importante.", "Lui è nervoso perché ha una riunione importante."],
      prompts: { "es": "Está nervioso porque tiene una reunión importante." },
      hint: "nervoso + perché + ha una riunione",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-005",
      type: "produce",
      prompt: "I'm grateful for your help. Thank you very much.",
      accepted: ["Sono grato per il tuo aiuto. Grazie mille.", "Sono grata per il tuo aiuto. Grazie mille."],
      prompts: { "es": "Estoy agradecido por tu ayuda. Muchas gracias." },
      hint: "grato/a + per + il tuo aiuto",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-006",
      type: "produce",
      prompt: "My little sister is scared of dogs.",
      accepted: ["Mia sorella piccola ha paura dei cani.", "La mia sorella piccola ha paura dei cani."],
      prompts: { "es": "Mi hermana pequeña tiene miedo de los perros." },
      hint: "avere paura di = to be afraid of",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-007",
      type: "produce",
      prompt: "Are you calm? Yes, I feel relaxed.",
      accepted: ["Sei tranquillo? Sì, mi sento rilassato.", "Sei tranquilla? Sì, mi sento rilassata."],
      prompts: { "es": "¿Estás tranquilo? Sí, me siento relajado." },
      hint: "tranquillo/a + sentirsi + rilassato/a",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-008",
      type: "produce",
      prompt: "They're very excited about the trip.",
      accepted: ["Sono molto emozionati per il viaggio.", "Sono molto emozionate per il viaggio."],
      prompts: { "es": "Están muy emocionados con el viaje." },
      hint: "emozionati (mixed/m pl) / emozionate (f pl)",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-009",
      type: "produce",
      prompt: "I'm disappointed because the concert is cancelled.",
      accepted: ["Sono deluso perché il concerto è annullato.", "Sono delusa perché il concerto è annullato."],
      prompts: { "es": "Estoy decepcionado porque el concierto está cancelado." },
      hint: "deluso/a + perché + è annullato",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-010",
      type: "produce",
      prompt: "She's embarrassed but it's not serious.",
      accepted: ["È imbarazzata ma non è grave.", "Lei è imbarazzata ma non è grave."],
      prompts: { "es": "Está avergonzada pero no es grave." },
      hint: "imbarazzata + ma + non è grave",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-011",
      type: "produce",
      prompt: "Marco is curious about everything.",
      accepted: ["Marco è curioso di tutto.", "Marco è curioso riguardo a tutto."],
      prompts: { "es": "Marco es curioso de todo." },
      hint: "curioso + di + tutto",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-012",
      type: "produce",
      prompt: "I'm confused. Can you explain again?",
      accepted: ["Sono confuso. Puoi spiegare ancora?", "Sono confusa. Puoi spiegare ancora?", "Sono confuso. Puoi ripetere?", "Sono confusa. Puoi ripetere?"],
      prompts: { "es": "Estoy confundido. ¿Puedes explicar de nuevo?" },
      hint: "confuso/a + puoi + infinitive",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-013",
      type: "fill_blank",
      prompt: "Luca sembra ___ — non sorride mai. (sad)",
      accepted: ["triste"],
      hint: "same m/f — triste",
      tags: ["sentence", "emotion", "fill_blank", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-014",
      type: "fill_blank",
      prompt: "Mi sento ___ quando parlo davanti a molte persone. (embarrassed — male speaker)",
      accepted: ["imbarazzato"],
      hint: "masculine singular — imbarazzato",
      tags: ["sentence", "emotion", "fill_blank", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-015",
      type: "produce",
      prompt: "Don't be sad. Everything will be okay.",
      accepted: ["Non essere triste. Va tutto bene.", "Non essere triste. Andrà tutto bene."],
      prompts: { "es": "No estés triste. Todo va a salir bien." },
      hint: "non essere + adjective; va bene = it's fine",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-016",
      type: "produce",
      prompt: "My grandmother is very kind and always helps everyone.",
      accepted: ["Mia nonna è molto gentile e aiuta sempre tutti."],
      prompts: { "es": "Mi abuela es muy amable y siempre ayuda a todos." },
      hint: "gentile + e + aiuta sempre tutti",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-017",
      type: "produce",
      prompt: "I can't wait for the weekend. I'm very tired.",
      accepted: ["Non vedo l'ora del weekend. Sono molto stanco.", "Non vedo l'ora del weekend. Sono molto stanca."],
      prompts: { "es": "No veo la hora del fin de semana. Estoy muy cansado." },
      hint: "non vedere l'ora del + noun",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-018",
      type: "fill_blank",
      prompt: "Oggi sono di ___ umore perché è una bella giornata. (good)",
      accepted: ["buon"],
      hint: "buono → buon before umore",
      tags: ["sentence", "emotion", "fill_blank", "A1"],
      tier: 4,
    },
    {
      id: "a112-t4-019",
      type: "produce",
      prompt: "He's shy, but he's very nice once you know him.",
      accepted: ["È timido, ma è molto simpatico quando lo conosci."],
      prompts: { "es": "Es tímido, pero es muy simpático cuando lo conoces." },
      hint: "timido + ma + simpatico + quando + lo conosci",
      tags: ["sentence", "emotion", "A1"],
      tier: 4,
    },
  ],
};

export default unit;
