import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-01-greetings",
  name: "Greetings & Identity",
  level: "A1",
  theme: "Greetings & Identity",
  emoji: "👋",
  prerequisiteUnits: [],
  cards: [
    // ─── Tier 1 – Vocabulary ───────────────────────────────────────────────
    {
      id: "u01-t1-001",
      type: "produce",
      prompt: "good morning / good day",
      accepted: ["buongiorno"],
      hint: "Buon + giorno (day)",
      tags: ["greetings", "formal"],
      tier: 1,
    },
    {
      id: "u01-t1-002",
      type: "produce",
      prompt: "good evening",
      accepted: ["buonasera"],
      hint: "Buona + sera (evening)",
      tags: ["greetings", "formal"],
      tier: 1,
    },
    {
      id: "u01-t1-003",
      type: "produce",
      prompt: "good night",
      accepted: ["buonanotte"],
      hint: "Buona + notte (night)",
      tags: ["greetings", "farewell"],
      tier: 1,
    },
    {
      id: "u01-t1-004",
      type: "produce",
      prompt: "hello / bye (informal)",
      accepted: ["ciao"],
      hint: "Informal; both hello and goodbye",
      tags: ["greetings", "farewell", "informal"],
      tier: 1,
    },
    {
      id: "u01-t1-005",
      type: "produce",
      prompt: "goodbye (formal)",
      accepted: ["arrivederci"],
      hint: "Until we see each other again",
      tags: ["farewell", "formal"],
      tier: 1,
    },
    {
      id: "u01-t1-006",
      type: "produce",
      prompt: "you're welcome / please",
      accepted: ["prego"],
      hint: "Response to grazie",
      tags: ["courtesy"],
      tier: 1,
    },
    {
      id: "u01-t1-007",
      type: "produce",
      prompt: "thank you",
      accepted: ["grazie"],
      hint: "Sounds like 'grat-see-ay'",
      tags: ["courtesy"],
      tier: 1,
    },
    {
      id: "u01-t1-008",
      type: "produce",
      prompt: "well / fine",
      accepted: ["bene"],
      hint: "Think 'benefit' — good",
      tags: ["responses"],
      tier: 1,
    },
    {
      id: "u01-t1-009",
      type: "produce",
      prompt: "badly / not well",
      accepted: ["male"],
      hint: "Opposite of bene",
      tags: ["responses"],
      tier: 1,
    },
    {
      id: "u01-t1-010",
      type: "produce",
      prompt: "so-so / not bad",
      accepted: ["così così"],
      hint: "Literally 'so so'",
      tags: ["responses"],
      tier: 1,
    },
    {
      id: "u01-t1-011",
      type: "produce",
      prompt: "the Italian man",
      accepted: ["l'italiano", "il ragazzo italiano"],
      hint: "Nationality adjective, masculine",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },
    {
      id: "u01-t1-012",
      type: "produce",
      prompt: "the Italian woman",
      accepted: ["l'italiana", "la ragazza italiana"],
      hint: "Nationality adjective, feminine",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },
    {
      id: "u01-t1-013",
      type: "produce",
      prompt: "the American man",
      accepted: ["l'americano"],
      hint: "Masculine nationality",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },
    {
      id: "u01-t1-014",
      type: "produce",
      prompt: "the American woman",
      accepted: ["l'americana"],
      hint: "Feminine nationality",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },
    {
      id: "u01-t1-015",
      type: "produce",
      prompt: "English (person, m/f)",
      accepted: ["inglese"],
      hint: "Same form for m/f",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },
    {
      id: "u01-t1-016",
      type: "produce",
      prompt: "French (person, m/f)",
      accepted: ["francese"],
      hint: "Same form for m/f",
      tags: ["nationalities", "vocab"],
      tier: 1,
    },

    // ─── Tier 2 – Grammar (essere conjugation + subject pronouns) ──────────
    {
      id: "u01-t2-001",
      type: "conjugate",
      prompt: "essere – io",
      accepted: ["sono"],
      hint: "Irregular; I am",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-002",
      type: "conjugate",
      prompt: "essere – tu",
      accepted: ["sei"],
      hint: "Informal you; are",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-003",
      type: "conjugate",
      prompt: "essere – lui / lei",
      accepted: ["è"],
      hint: "He/she is; accent required",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-004",
      type: "conjugate",
      prompt: "essere – Lei (formal)",
      accepted: ["è"],
      hint: "Polite you; same as lui/lei",
      tags: ["essere", "conjugation", "formal", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-005",
      type: "conjugate",
      prompt: "essere – noi",
      accepted: ["siamo"],
      hint: "We are",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-006",
      type: "conjugate",
      prompt: "essere – voi",
      accepted: ["siete"],
      hint: "You all are",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-007",
      type: "conjugate",
      prompt: "essere – loro",
      accepted: ["sono"],
      hint: "Same as io; they are",
      tags: ["essere", "conjugation", "pronouns"],
      tier: 2,
    },
    {
      id: "u01-t2-008",
      type: "produce",
      prompt: "my name is (literally: I call myself)",
      accepted: ["mi chiamo"],
      hint: "Reflexive; chiamo = I call",
      tags: ["identity", "phrases"],
      tier: 2,
    },
    {
      id: "u01-t2-009",
      type: "produce",
      prompt: "how are you? (informal)",
      accepted: ["come stai?", "come stai"],
      hint: "Informal tu form of stare",
      tags: ["greetings", "informal"],
      tier: 2,
    },
    {
      id: "u01-t2-010",
      type: "produce",
      prompt: "how are you? (formal)",
      accepted: ["come sta?", "come sta"],
      hint: "Formal Lei form of stare",
      tags: ["greetings", "formal"],
      tier: 2,
    },

    // ─── Tier 3 – Chunks / Phrases ─────────────────────────────────────────
    {
      id: "u01-t3-001",
      type: "produce",
      prompt: "How are you? (informal)",
      accepted: ["Come stai?", "Come stai"],
      hint: "Tu form; casual setting",
      tags: ["chunks", "greetings", "informal"],
      tier: 3,
      prerequisites: ["u01-t2-009"],
    },
    {
      id: "u01-t3-002",
      type: "produce",
      prompt: "How are you? (formal)",
      accepted: ["Come sta?", "Come sta"],
      hint: "Lei form; polite setting",
      tags: ["chunks", "greetings", "formal"],
      tier: 3,
      prerequisites: ["u01-t2-010"],
    },
    {
      id: "u01-t3-003",
      type: "produce",
      prompt: "My name is…",
      accepted: ["Mi chiamo…"],
      hint: "Introduce yourself",
      tags: ["chunks", "identity"],
      tier: 3,
      prerequisites: ["u01-t2-008"],
    },
    {
      id: "u01-t3-004",
      type: "produce",
      prompt: "I am from…",
      accepted: ["Sono di…"],
      hint: "sono + di + city/country",
      tags: ["chunks", "identity"],
      tier: 3,
      prerequisites: ["u01-t2-001"],
    },
    {
      id: "u01-t3-005",
      type: "produce",
      prompt: "Pleased to meet you",
      accepted: ["Molto piacere", "Piacere"],
      hint: "molto = very; formal/informal both ok",
      tags: ["chunks", "courtesy"],
      tier: 3,
    },
    {
      id: "u01-t3-006",
      type: "produce",
      prompt: "She is… (formal you / third person)",
      accepted: ["Lei è…", "lei è…"],
      hint: "Capital Lei = formal you",
      tags: ["chunks", "identity", "formal"],
      tier: 3,
      prerequisites: ["u01-t2-003", "u01-t2-004"],
    },
    {
      id: "u01-t3-007",
      type: "produce",
      prompt: "Very well, thank you",
      accepted: ["Molto bene, grazie", "Bene, grazie"],
      hint: "Common reply to come stai?",
      tags: ["chunks", "responses"],
      tier: 3,
      prerequisites: ["u01-t1-008", "u01-t1-007"],
    },

    // ─── Tier 4 – Sentences ────────────────────────────────────────────────
    {
      id: "u01-t4-001",
      type: "produce",
      prompt: "Good morning, my name is Marco. I am Italian.",
      accepted: [
        "Buongiorno, mi chiamo Marco. Sono italiano.",
        "Buongiorno, mi chiamo Marco. Sono italiano",
      ],
      hint: "Combine greeting + intro + nationality",
      tags: ["sentences", "identity"],
      tier: 4,
      prerequisites: ["u01-t1-001", "u01-t2-008", "u01-t2-001", "u01-t1-011"],
    },
    {
      id: "u01-t4-002",
      type: "produce",
      prompt: "Hello! How are you? (informal) I am fine, thank you.",
      accepted: [
        "Ciao! Come stai? Sto bene, grazie.",
        "Ciao! Come stai? Bene, grazie.",
      ],
      hint: "Informal greeting + wellbeing reply",
      tags: ["sentences", "greetings", "informal"],
      tier: 4,
      prerequisites: ["u01-t1-004", "u01-t2-009", "u01-t1-008", "u01-t1-007"],
    },
    {
      id: "u01-t4-003",
      type: "produce",
      prompt: "Good evening, I am Anna. I am American.",
      accepted: [
        "Buonasera, mi chiamo Anna. Sono americana.",
        "Buonasera, sono Anna. Sono americana.",
      ],
      hint: "Evening greeting + identity + nationality",
      tags: ["sentences", "identity"],
      tier: 4,
      prerequisites: ["u01-t1-002", "u01-t2-008", "u01-t2-001", "u01-t1-014"],
    },
    {
      id: "u01-t4-004",
      type: "produce",
      prompt: "Good morning! How are you? (formal) So-so, thank you.",
      accepted: [
        "Buongiorno! Come sta? Così così, grazie.",
        "Buongiorno! Come sta? Così così, grazie",
      ],
      hint: "Formal register throughout",
      tags: ["sentences", "greetings", "formal"],
      tier: 4,
      prerequisites: ["u01-t1-001", "u01-t2-010", "u01-t1-010", "u01-t1-007"],
    },
    {
      id: "u01-t4-005",
      type: "produce",
      prompt: "Goodbye! Thank you. You're welcome.",
      accepted: [
        "Arrivederci! Grazie. Prego.",
        "Ciao! Grazie. Prego.",
      ],
      hint: "Farewell + courtesy exchange",
      tags: ["sentences", "farewell", "courtesy"],
      tier: 4,
      prerequisites: ["u01-t1-005", "u01-t1-007", "u01-t1-006"],
    },
  ],
};

export default unit;
