import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-08-review",
  name: "Work & Modal Verbs",
  level: "A1",
  theme: "Work & Modal Verbs",
  emoji: "💼",
  prerequisiteUnits: ["a1-unit-07-likes"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: work/office
    // -------------------------------------------------------------------------
    {
      id: "u08-t1-001",
      type: "produce",
      prompt: "the work / job",
      accepted: ["il lavoro"],
      prompts: { "es": "el trabajo" },
      hint: "masculine noun — same root as 'labor'",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-100",
      type: "recognize",
      prompt: "il lavoro",
      accepted: ["the work", "work", "the job", "job"],
      translations: { "es": ["el trabajo"] },
      hint: "same root as 'labor'",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-002",
      type: "produce",
      prompt: "the office",
      accepted: ["l'ufficio"],
      prompts: { "es": "la oficina" },
      hint: "masculine noun — l'ufficio (elision before vowel)",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-101",
      type: "recognize",
      prompt: "l'ufficio",
      accepted: ["the office", "office"],
      translations: { "es": ["la oficina"] },
      hint: "ufficio — think 'official space'",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-003",
      type: "produce",
      prompt: "the colleague",
      accepted: ["il collega", "la collega"],
      prompts: { "es": "el/la colega" },
      hint: "collega is gender-neutral in form — il/la depending on the person",
      tags: ["noun", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-102",
      type: "recognize",
      prompt: "il collega / la collega",
      accepted: ["the colleague", "colleague", "coworker", "the coworker"],
      translations: { "es": ["el colega", "la colega"] },
      hint: "collega works for any gender",
      tags: ["noun", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-004",
      type: "produce",
      prompt: "the meeting",
      accepted: ["la riunione"],
      prompts: { "es": "la reunión" },
      hint: "feminine noun — same root as 'reunion'",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-103",
      type: "recognize",
      prompt: "la riunione",
      accepted: ["the meeting", "meeting"],
      translations: { "es": ["la reunión"] },
      hint: "riunione = re-union, gathering together",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-005",
      type: "produce",
      prompt: "the phone",
      accepted: ["il telefono"],
      prompts: { "es": "el teléfono" },
      hint: "masculine noun — same as English!",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-104",
      type: "recognize",
      prompt: "il telefono",
      accepted: ["the phone", "phone", "the telephone", "telephone"],
      translations: { "es": ["el teléfono"] },
      hint: "tele = far; fono = sound",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-006",
      type: "produce",
      prompt: "the computer",
      accepted: ["il computer"],
      prompts: { "es": "el ordenador" },
      hint: "masculine noun — borrowed from English",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-105",
      type: "recognize",
      prompt: "il computer",
      accepted: ["the computer", "computer"],
      translations: { "es": ["el ordenador", "el computador"] },
      hint: "direct English loanword",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-007",
      type: "produce",
      prompt: "the message",
      accepted: ["il messaggio"],
      prompts: { "es": "el mensaje" },
      hint: "masculine noun — same root as English",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-106",
      type: "recognize",
      prompt: "il messaggio",
      accepted: ["the message", "message"],
      translations: { "es": ["el mensaje"] },
      hint: "plural: i messaggi",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-008",
      type: "produce",
      prompt: "to write",
      accepted: ["scrivere"],
      prompts: { "es": "escribir" },
      hint: "-ERE infinitive",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-107",
      type: "recognize",
      prompt: "scrivere",
      accepted: ["to write", "write"],
      translations: { "es": ["escribir"] },
      hint: "scribe — same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-009",
      type: "produce",
      prompt: "to send",
      accepted: ["mandare", "inviare"],
      prompts: { "es": "enviar/mandar" },
      hint: "mandare is more common; inviare is formal",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-108",
      type: "recognize",
      prompt: "mandare",
      accepted: ["to send", "send"],
      translations: { "es": ["enviar", "mandar"] },
      hint: "mandare = to send / to command",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-010",
      type: "produce",
      prompt: "to call (phone)",
      accepted: ["chiamare"],
      prompts: { "es": "llamar" },
      hint: "-ARE infinitive; chi-a-MA-re",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-109",
      type: "recognize",
      prompt: "chiamare",
      accepted: ["to call", "call", "to phone", "phone"],
      translations: { "es": ["llamar"] },
      hint: "chi-a-MA-re — also means 'to name'",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-011",
      type: "produce",
      prompt: "to understand",
      accepted: ["capire"],
      prompts: { "es": "entender" },
      hint: "-IRE verb, -isc- form: capisco",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-110",
      type: "recognize",
      prompt: "capire",
      accepted: ["to understand", "understand"],
      translations: { "es": ["entender"] },
      hint: "-isc- form in present: capisco, capisci, capisce…",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-012",
      type: "produce",
      prompt: "to finish",
      accepted: ["finire"],
      prompts: { "es": "terminar" },
      hint: "-IRE verb, -isc- form: finisco",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-111",
      type: "recognize",
      prompt: "finire",
      accepted: ["to finish", "finish", "to end", "end"],
      translations: { "es": ["terminar"] },
      hint: "finire = to finish; finale = the finish",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-013",
      type: "produce",
      prompt: "to begin / start",
      accepted: ["cominciare", "iniziare"],
      prompts: { "es": "empezar/comenzar" },
      hint: "cominciare = most common; iniziare = also correct",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-112",
      type: "recognize",
      prompt: "cominciare",
      accepted: ["to begin", "begin", "to start", "start"],
      translations: { "es": ["empezar", "comenzar"] },
      hint: "co-min-CHAH-reh",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-150",
      type: "produce",
      prompt: "the answer / reply",
      accepted: ["la risposta"],
      prompts: { "es": "la respuesta" },
      hint: "feminine noun — same root as 'response'",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-151",
      type: "recognize",
      prompt: "la risposta",
      accepted: ["the answer", "answer", "the reply", "reply", "the response", "response"],
      translations: { "es": ["la respuesta"] },
      hint: "plural: le risposte",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-152",
      type: "produce",
      prompt: "the question",
      accepted: ["la domanda"],
      prompts: { "es": "la pregunta" },
      hint: "feminine noun — think 'demand'",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-153",
      type: "recognize",
      prompt: "la domanda",
      accepted: ["the question", "question"],
      translations: { "es": ["la pregunta"] },
      hint: "fare una domanda = to ask a question",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-154",
      type: "produce",
      prompt: "the email",
      accepted: ["l'email", "la mail"],
      prompts: { "es": "el correo electrónico" },
      hint: "feminine noun — l'email (elision) or la mail",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-155",
      type: "recognize",
      prompt: "l'email",
      accepted: ["the email", "email", "the e-mail", "e-mail"],
      translations: { "es": ["el correo electrónico", "el email"] },
      hint: "often feminine in Italian",
      tags: ["noun", "feminine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-156",
      type: "produce",
      prompt: "the document",
      accepted: ["il documento"],
      prompts: { "es": "el documento" },
      hint: "masculine noun — same as English",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-157",
      type: "recognize",
      prompt: "il documento",
      accepted: ["the document", "document"],
      translations: { "es": ["el documento"] },
      hint: "plural: i documenti",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-158",
      type: "produce",
      prompt: "the boss",
      accepted: ["il capo", "il/la capo"],
      prompts: { "es": "el jefe" },
      hint: "masculine; la capo for a female boss",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-159",
      type: "recognize",
      prompt: "il capo",
      accepted: ["the boss", "boss", "the chief", "chief", "the head", "the manager"],
      translations: { "es": ["el jefe", "la jefa"] },
      hint: "capo also means 'head' and 'cape'",
      tags: ["noun", "masculine", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-160",
      type: "produce",
      prompt: "to wait",
      accepted: ["aspettare"],
      prompts: { "es": "esperar" },
      hint: "-ARE infinitive; as-pet-TAH-reh",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-161",
      type: "recognize",
      prompt: "aspettare",
      accepted: ["to wait", "wait", "to wait for"],
      translations: { "es": ["esperar"] },
      hint: "aspettare qualcuno = to wait for someone",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-162",
      type: "produce",
      prompt: "to reply / to answer",
      accepted: ["rispondere"],
      prompts: { "es": "responder" },
      hint: "-ERE infinitive — same root as 'respond'",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-163",
      type: "recognize",
      prompt: "rispondere",
      accepted: ["to reply", "reply", "to answer", "answer", "to respond", "respond"],
      translations: { "es": ["responder"] },
      hint: "rispondere a = to reply to",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-164",
      type: "produce",
      prompt: "to open",
      accepted: ["aprire"],
      prompts: { "es": "abrir" },
      hint: "-IRE infinitive — aperture is the same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-165",
      type: "recognize",
      prompt: "aprire",
      accepted: ["to open", "open"],
      translations: { "es": ["abrir"] },
      hint: "apertura = opening — same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-166",
      type: "produce",
      prompt: "to work",
      accepted: ["lavorare"],
      prompts: { "es": "trabajar" },
      hint: "-ARE infinitive — same root as 'labor'",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-167",
      type: "recognize",
      prompt: "lavorare",
      accepted: ["to work", "work"],
      translations: { "es": ["trabajar"] },
      hint: "lavoro (n.) and lavorare (v.) — same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-168",
      type: "produce",
      prompt: "to speak / to talk",
      accepted: ["parlare"],
      prompts: { "es": "hablar" },
      hint: "-ARE infinitive — parliament debates",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-169",
      type: "recognize",
      prompt: "parlare",
      accepted: ["to speak", "speak", "to talk", "talk"],
      translations: { "es": ["hablar"] },
      hint: "parlamento (parliament) = place of speaking",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-170",
      type: "produce",
      prompt: "to help",
      accepted: ["aiutare"],
      prompts: { "es": "ayudar" },
      hint: "-ARE infinitive; ai-u-TAH-reh",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-171",
      type: "recognize",
      prompt: "aiutare",
      accepted: ["to help", "help"],
      translations: { "es": ["ayudar"] },
      hint: "aiuto! = help! (exclamation)",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-172",
      type: "produce",
      prompt: "to read",
      accepted: ["leggere"],
      prompts: { "es": "leer" },
      hint: "-ERE infinitive",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-173",
      type: "recognize",
      prompt: "leggere",
      accepted: ["to read", "read"],
      translations: { "es": ["leer"] },
      hint: "leg-GE-re — lectura, lecture — same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-174",
      type: "produce",
      prompt: "to see",
      accepted: ["vedere"],
      prompts: { "es": "ver" },
      hint: "-ERE infinitive — video, vision — same root",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-175",
      type: "recognize",
      prompt: "vedere",
      accepted: ["to see", "see"],
      translations: { "es": ["ver"] },
      hint: "vedo = I see (irregular io form)",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-176",
      type: "produce",
      prompt: "to take / to get",
      accepted: ["prendere"],
      prompts: { "es": "tomar/coger" },
      hint: "-ERE infinitive; also 'to have (food/drink)'",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-177",
      type: "recognize",
      prompt: "prendere",
      accepted: ["to take", "take", "to get", "get", "to grab", "grab"],
      translations: { "es": ["tomar", "coger"] },
      hint: "prendere un caffè = to have a coffee",
      tags: ["verb", "infinitive", "work", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-178",
      type: "produce",
      prompt: "to sleep",
      accepted: ["dormire"],
      prompts: { "es": "dormir" },
      hint: "-IRE infinitive — dormitory — same root",
      tags: ["verb", "infinitive", "daily", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-179",
      type: "recognize",
      prompt: "dormire",
      accepted: ["to sleep", "sleep"],
      translations: { "es": ["dormir"] },
      hint: "dormire = to sleep; il dormitorio = dormitory",
      tags: ["verb", "infinitive", "daily", "tier1", "A1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Chunks: modal verb phrases
    // -------------------------------------------------------------------------
    {
      id: "u08-t3-001",
      type: "produce",
      prompt: "I have to work.",
      accepted: ["Devo lavorare."],
      prompts: { "es": "Tengo que trabajar." },
      hint: "devo = I must / I have to (from dovere)",
      tags: ["chunk", "dovere", "work", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-002",
      type: "produce",
      prompt: "Can I help you?",
      accepted: ["Posso aiutarti?", "Posso aiutarla?"],
      prompts: { "es": "¿Puedo ayudarte?" },
      hint: "posso = I can (from potere); aiutarti = help you (informal)",
      tags: ["chunk", "potere", "work", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-003",
      type: "produce",
      prompt: "I have finished.",
      accepted: ["Ho finito."],
      prompts: { "es": "He terminado." },
      hint: "ho + past participle = passato prossimo",
      tags: ["chunk", "finire", "work", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-004",
      type: "produce",
      prompt: "I don't understand.",
      accepted: ["Non capisco."],
      prompts: { "es": "No entiendo." },
      hint: "capisco = I understand (-isc- form of capire)",
      tags: ["chunk", "capire", "negation", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-005",
      type: "produce",
      prompt: "I want to read.",
      accepted: ["Voglio leggere."],
      prompts: { "es": "Quiero leer." },
      hint: "voglio = I want (from volere, irregular)",
      tags: ["chunk", "volere", "work", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-006",
      type: "produce",
      prompt: "I prefer to write.",
      accepted: ["Preferisco scrivere."],
      prompts: { "es": "Prefiero escribir." },
      hint: "preferisco = I prefer (-isc- form of preferire)",
      tags: ["chunk", "preferire", "work", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-100",
      type: "produce",
      prompt: "I have to go.",
      accepted: ["Devo andare."],
      prompts: { "es": "Tengo que ir." },
      hint: "devo + infinitive = have to + verb",
      tags: ["chunk", "dovere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-101",
      type: "produce",
      prompt: "Can you help me?",
      accepted: ["Puoi aiutarmi?"],
      prompts: { "es": "¿Puedes ayudarme?" },
      hint: "puoi = you can (from potere, tu form)",
      tags: ["chunk", "potere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-102",
      type: "produce",
      prompt: "I want to understand.",
      accepted: ["Voglio capire."],
      prompts: { "es": "Quiero entender." },
      hint: "voglio + infinitive = I want to + verb",
      tags: ["chunk", "volere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-103",
      type: "produce",
      prompt: "I can't come.",
      accepted: ["Non posso venire."],
      prompts: { "es": "No puedo venir." },
      hint: "non posso = I cannot (potere, negated)",
      tags: ["chunk", "potere", "negation", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-104",
      type: "produce",
      prompt: "I have to wait.",
      accepted: ["Devo aspettare."],
      prompts: { "es": "Tengo que esperar." },
      hint: "devo + aspettare",
      tags: ["chunk", "dovere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-105",
      type: "produce",
      prompt: "Do you want to start?",
      accepted: ["Vuoi cominciare?"],
      prompts: { "es": "¿Quieres empezar?" },
      hint: "vuoi = you want (volere, tu form)",
      tags: ["chunk", "volere", "question", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-106",
      type: "produce",
      prompt: "We can see.",
      accepted: ["Possiamo vedere."],
      prompts: { "es": "Podemos ver." },
      hint: "possiamo = we can (potere, noi form)",
      tags: ["chunk", "potere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-107",
      type: "produce",
      prompt: "I want to speak.",
      accepted: ["Voglio parlare."],
      prompts: { "es": "Quiero hablar." },
      hint: "voglio + parlare",
      tags: ["chunk", "volere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-108",
      type: "produce",
      prompt: "I prefer to read.",
      accepted: ["Preferisco leggere."],
      prompts: { "es": "Prefiero leer." },
      hint: "preferisco + infinitive",
      tags: ["chunk", "preferire", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-109",
      type: "produce",
      prompt: "You have to finish.",
      accepted: ["Devi finire."],
      prompts: { "es": "Tienes que terminar." },
      hint: "devi = you have to (dovere, tu form)",
      tags: ["chunk", "dovere", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-110",
      type: "produce",
      prompt: "I don't want to write.",
      accepted: ["Non voglio scrivere."],
      prompts: { "es": "No quiero escribir." },
      hint: "non voglio = I don't want to",
      tags: ["chunk", "volere", "negation", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-111",
      type: "produce",
      prompt: "Can I open?",
      accepted: ["Posso aprire?"],
      prompts: { "es": "¿Puedo abrir?" },
      hint: "posso = can I? (potere, first person)",
      tags: ["chunk", "potere", "question", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "u08-t3-112",
      type: "produce",
      prompt: "I prefer to wait.",
      accepted: ["Preferisco aspettare."],
      prompts: { "es": "Prefiero esperar." },
      hint: "preferisco + aspettare",
      tags: ["chunk", "preferire", "tier3", "A1"],
      tier: 3,
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Sentences: modal verbs in context
    // -------------------------------------------------------------------------
    {
      id: "u08-t4-001",
      type: "produce",
      prompt: "I have to finish the work and then I can call my mother.",
      accepted: ["Devo finire il lavoro e poi posso chiamare mia madre."],
      prompts: { "es": "Tengo que terminar el trabajo y luego puedo llamar a mi madre." },
      hint: "devo + finire; posso + chiamare — two modals in one sentence",
      tags: ["sentence", "dovere", "potere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-001", "u08-t1-010", "u08-t1-012", "u08-t3-001"],
    },
    {
      id: "u08-t4-002",
      type: "produce",
      prompt: "I want to send a message to my colleague.",
      accepted: [
        "Voglio mandare un messaggio al mio collega.",
        "Voglio mandare un messaggio alla mia collega.",
      ],
      prompts: { "es": "Quiero enviar un mensaje a mi colega." },
      hint: "voglio + mandare; al mio (m.) or alla mia (f.) before collega",
      tags: ["sentence", "volere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-003", "u08-t1-007", "u08-t1-009", "u08-t3-005"],
    },
    {
      id: "u08-t4-003",
      type: "produce",
      prompt: "Can you open the email from the boss?",
      accepted: ["Puoi aprire l'email del capo?"],
      prompts: { "es": "¿Puedes abrir el correo del jefe?" },
      hint: "puoi + aprire; del capo = of the boss",
      tags: ["sentence", "potere", "work", "question", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-006", "u08-t1-154", "u08-t1-158", "u08-t1-164", "u08-t3-101"],
    },
    {
      id: "u08-t4-004",
      type: "produce",
      prompt: "I have to write an email in the office.",
      accepted: [
        "Devo scrivere un'email in ufficio.",
        "Devo scrivere una mail in ufficio.",
      ],
      prompts: { "es": "Tengo que escribir un correo en la oficina." },
      hint: "devo + scrivere; in ufficio (no article)",
      tags: ["sentence", "dovere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-002", "u08-t1-008", "u08-t1-154", "u08-t3-001"],
    },
    {
      id: "u08-t4-005",
      type: "produce",
      prompt: "I prefer to start the meeting at nine.",
      accepted: ["Preferisco cominciare la riunione alle nove."],
      prompts: { "es": "Prefiero empezar la reunión a las nueve." },
      hint: "preferisco + cominciare; alle nove = at nine",
      tags: ["sentence", "preferire", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-004", "u08-t1-013", "u08-t3-006"],
    },
    {
      id: "u08-t4-100",
      type: "produce",
      prompt: "Marco can take the phone and call the office.",
      accepted: ["Marco può prendere il telefono e chiamare l'ufficio."],
      prompts: { "es": "Marco puede coger el teléfono y llamar a la oficina." },
      hint: "può = he/she can (potere, terza persona)",
      tags: ["sentence", "potere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-002", "u08-t1-005", "u08-t1-010", "u08-t1-176"],
    },
    {
      id: "u08-t4-101",
      type: "produce",
      prompt: "She has to read the document and write a reply.",
      accepted: ["Deve leggere il documento e scrivere una risposta."],
      prompts: { "es": "Ella tiene que leer el documento y escribir una respuesta." },
      hint: "deve = he/she has to (dovere, terza persona)",
      tags: ["sentence", "dovere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: [
        "u08-t1-008",
        "u08-t1-150",
        "u08-t1-156",
        "u08-t1-172",
        "u08-t3-001",
      ],
    },
    {
      id: "u08-t4-102",
      type: "produce",
      prompt: "Do you want to speak with the colleague?",
      accepted: [
        "Vuoi parlare con il collega?",
        "Vuoi parlare con la collega?",
      ],
      prompts: { "es": "¿Quieres hablar con el/la colega?" },
      hint: "vuoi + parlare; con = with",
      tags: ["sentence", "volere", "work", "question", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-003", "u08-t1-168", "u08-t3-005"],
    },
    {
      id: "u08-t4-103",
      type: "produce",
      prompt: "They can't understand the message.",
      accepted: ["Non possono capire il messaggio."],
      prompts: { "es": "No pueden entender el mensaje." },
      hint: "non possono = they cannot (potere, terza plural, negated)",
      tags: ["sentence", "potere", "negation", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-007", "u08-t1-011", "u08-t3-103"],
    },
    {
      id: "u08-t4-104",
      type: "produce",
      prompt: "I prefer to send an email.",
      accepted: [
        "Preferisco mandare un'email.",
        "Preferisco mandare una mail.",
      ],
      prompts: { "es": "Prefiero enviar un correo." },
      hint: "preferisco + mandare; un'email (elision) or una mail",
      tags: ["sentence", "preferire", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-009", "u08-t1-154", "u08-t3-006"],
    },
    {
      id: "u08-t4-105",
      type: "produce",
      prompt: "We have to wait for the boss.",
      accepted: ["Dobbiamo aspettare il capo."],
      prompts: { "es": "Tenemos que esperar al jefe." },
      hint: "dobbiamo = we have to (dovere, noi form)",
      tags: ["sentence", "dovere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-158", "u08-t1-160", "u08-t3-104"],
    },
    {
      id: "u08-t4-106",
      type: "produce",
      prompt: "I can see the document on the computer.",
      accepted: ["Posso vedere il documento sul computer."],
      prompts: { "es": "Puedo ver el documento en el ordenador." },
      hint: "posso + vedere; sul = su + il (on the)",
      tags: ["sentence", "potere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-006", "u08-t1-156", "u08-t1-174", "u08-t3-002"],
    },
    {
      id: "u08-t4-107",
      type: "produce",
      prompt: "He wants to begin to speak with the colleague.",
      accepted: [
        "Vuole cominciare a parlare con il collega.",
        "Vuole cominciare a parlare con la collega.",
      ],
      prompts: { "es": "Él quiere empezar a hablar con el/la colega." },
      hint: "vuole = he/she wants; cominciare a + infinitive",
      tags: ["sentence", "volere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-003", "u08-t1-013", "u08-t1-168", "u08-t3-005"],
    },
    {
      id: "u08-t4-108",
      type: "produce",
      prompt: "Can you call the boss?",
      accepted: ["Puoi chiamare il capo?"],
      prompts: { "es": "¿Puedes llamar al jefe?" },
      hint: "puoi + chiamare; il capo (no preposition needed)",
      tags: ["sentence", "potere", "work", "question", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-010", "u08-t1-158", "u08-t3-101"],
    },
    {
      id: "u08-t4-109",
      type: "produce",
      prompt: "I want to ask a question.",
      accepted: ["Voglio fare una domanda."],
      prompts: { "es": "Quiero hacer una pregunta." },
      hint: "fare una domanda = to ask a question (idiomatic)",
      tags: ["sentence", "volere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-152", "u08-t3-005"],
    },
    {
      id: "u08-t4-110",
      type: "produce",
      prompt: "She has to send the document to the colleague.",
      accepted: [
        "Deve mandare il documento al collega.",
        "Deve mandare il documento alla collega.",
      ],
      prompts: { "es": "Ella tiene que enviar el documento al/a la colega." },
      hint: "deve + mandare; al collega (m.) or alla collega (f.)",
      tags: ["sentence", "dovere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-003", "u08-t1-009", "u08-t1-156", "u08-t3-001"],
    },
    {
      id: "u08-t4-111",
      type: "produce",
      prompt: "I can help my colleague to understand.",
      accepted: [
        "Posso aiutare il mio collega a capire.",
        "Posso aiutare la mia collega a capire.",
      ],
      prompts: { "es": "Puedo ayudar a mi colega a entender." },
      hint: "posso + aiutare + a + infinitive",
      tags: ["sentence", "potere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-003", "u08-t1-011", "u08-t1-170", "u08-t3-002"],
    },
    {
      id: "u08-t4-112",
      type: "produce",
      prompt: "They want to read all the messages.",
      accepted: ["Vogliono leggere tutti i messaggi."],
      prompts: { "es": "Quieren leer todos los mensajes." },
      hint: "vogliono = they want (volere, terza plural)",
      tags: ["sentence", "volere", "work", "tier4", "A1"],
      tier: 4,
      prerequisites: ["u08-t1-007", "u08-t1-172", "u08-t3-005"],
    },
  ],
};

export default unit;
