import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-04-city",
  name: "The City",
  level: "A1",
  theme: "Around the City",
  emoji: "🏙️",
  prerequisiteUnits: ["a1-unit-01-greetings", "a1-unit-02-bar"],
  cards: [
    // ── TIER 1 — VOCABULARY ────────────────────────────────────
    {
      id: "u04-t1-001",
      type: "produce",
      prompt: "the supermarket",
      accepted: ["il supermercato"],
      hint: "Masculine — il supermercato.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-002",
      type: "produce",
      prompt: "the pharmacy",
      accepted: ["la farmacia"],
      hint: "Feminine — la farmacia.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-003",
      type: "produce",
      prompt: "the bank",
      accepted: ["la banca"],
      hint: "Feminine — la banca.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-004",
      type: "produce",
      prompt: "the square / plaza",
      accepted: ["la piazza"],
      hint: "Feminine — la piazza.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-005",
      type: "produce",
      prompt: "the street",
      accepted: ["la strada"],
      hint: "Feminine — la strada.",
      tags: ["city", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-006",
      type: "produce",
      prompt: "the hospital",
      accepted: ["l'ospedale"],
      hint: "Masculine, vowel start → l'ospedale.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-007",
      type: "produce",
      prompt: "the station",
      accepted: ["la stazione"],
      hint: "Feminine — la stazione.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-008",
      type: "produce",
      prompt: "the museum",
      accepted: ["il museo"],
      hint: "Masculine — il museo.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-009",
      type: "produce",
      prompt: "the restaurant",
      accepted: ["il ristorante"],
      hint: "Masculine — il ristorante.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-010",
      type: "produce",
      prompt: "the park",
      accepted: ["il parco"],
      hint: "Masculine — il parco.",
      tags: ["city", "places", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-011",
      type: "produce",
      prompt: "right (direction)",
      accepted: ["destra"],
      hint: "No article needed as a direction word.",
      tags: ["city", "directions", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-012",
      type: "produce",
      prompt: "left (direction)",
      accepted: ["sinistra"],
      hint: "No article needed as a direction word.",
      tags: ["city", "directions", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-013",
      type: "produce",
      prompt: "straight ahead",
      accepted: ["dritto", "diritto"],
      hint: "Both spellings are accepted.",
      tags: ["city", "directions", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-014",
      type: "produce",
      prompt: "near / nearby",
      accepted: ["vicino"],
      hint: "Can also precede a noun: vicino alla banca.",
      tags: ["city", "directions", "A1"],
      tier: 1,
    },
    {
      id: "u04-t1-015",
      type: "produce",
      prompt: "far / far away",
      accepted: ["lontano"],
      hint: "Opposite of vicino.",
      tags: ["city", "directions", "A1"],
      tier: 1,
    },

    // ── TIER 2 — GRAMMAR ───────────────────────────────────────
    {
      id: "u04-t2-001",
      type: "conjugate",
      prompt: "andare – io",
      accepted: ["vado"],
      hint: "Irregular: io vado (not ando).",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-002",
      type: "conjugate",
      prompt: "andare – tu",
      accepted: ["vai"],
      hint: "Irregular: tu vai.",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-003",
      type: "conjugate",
      prompt: "andare – lui/lei",
      accepted: ["va"],
      hint: "Irregular: lui/lei va.",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-004",
      type: "conjugate",
      prompt: "andare – noi",
      accepted: ["andiamo"],
      hint: "Regular stem for noi/voi: andiamo.",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-005",
      type: "conjugate",
      prompt: "andare – voi",
      accepted: ["andate"],
      hint: "Regular stem for voi: andate.",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-006",
      type: "conjugate",
      prompt: "andare – loro",
      accepted: ["vanno"],
      hint: "Irregular: loro vanno (double n).",
      tags: ["verbs", "andare", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-007",
      type: "produce",
      prompt: "a + il → ___ (preposition contraction)",
      accepted: ["al"],
      hint: "a + il = al; e.g. vado al museo.",
      tags: ["grammar", "prepositions", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-008",
      type: "produce",
      prompt: "a + la → ___ (preposition contraction)",
      accepted: ["alla"],
      hint: "a + la = alla; e.g. vado alla banca.",
      tags: ["grammar", "prepositions", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-009",
      type: "produce",
      prompt: "di + il → ___ (preposition contraction)",
      accepted: ["del"],
      hint: "di + il = del; e.g. vicino del parco.",
      tags: ["grammar", "prepositions", "A1"],
      tier: 2,
    },
    {
      id: "u04-t2-010",
      type: "produce",
      prompt: "in + il → ___ (preposition contraction)",
      accepted: ["nel"],
      hint: "in + il = nel; e.g. nel parco.",
      tags: ["grammar", "prepositions", "A1"],
      tier: 2,
    },

    // ── TIER 3 — CHUNKS / PHRASES ──────────────────────────────
    {
      id: "u04-t3-001",
      type: "produce",
      prompt: "Where is…?",
      accepted: ["Dov'è…?", "Dov'è"],
      hint: "Dove + è = Dov'è (elision).",
      tags: ["city", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-002",
      type: "produce",
      prompt: "Turn right.",
      accepted: ["Gira a destra.", "Gira a destra"],
      hint: "Gira = turn (imperative tu).",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-003",
      type: "produce",
      prompt: "Go straight ahead.",
      accepted: ["Vai dritto.", "Vai dritto", "Vai diritto.", "Vai diritto"],
      hint: "Vai = go (imperative tu of andare).",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-004",
      type: "produce",
      prompt: "It is nearby.",
      accepted: ["È vicino.", "È vicino"],
      hint: "È = is (essere, third person).",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-005",
      type: "produce",
      prompt: "It is far away.",
      accepted: ["È lontano.", "È lontano"],
      hint: "Opposite of è vicino.",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-006",
      type: "produce",
      prompt: "Turn left.",
      accepted: ["Gira a sinistra.", "Gira a sinistra"],
      hint: "Gira = turn (imperative tu).",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },
    {
      id: "u04-t3-007",
      type: "produce",
      prompt: "Where is the pharmacy?",
      accepted: ["Dov'è la farmacia?", "Dov'è la farmacia"],
      hint: "Dov'è + article + noun.",
      tags: ["city", "directions", "phrases", "A1"],
      tier: 3,
    },

    // ── TIER 4 — SENTENCES ─────────────────────────────────────
    {
      id: "u04-t4-001",
      type: "produce",
      prompt: "I go to the supermarket and then to the bank.",
      accepted: [
        "Vado al supermercato e poi alla banca.",
        "Vado al supermercato e poi alla banca",
      ],
      hint: "al = a + il; alla = a + la.",
      tags: ["city", "sentences", "A1"],
      tier: 4,
      prerequisites: [
        "u04-t1-001",
        "u04-t1-003",
        "u04-t2-001",
        "u04-t2-007",
        "u04-t2-008",
      ],
    },
    {
      id: "u04-t4-002",
      type: "produce",
      prompt: "Where is the museum? It is nearby.",
      accepted: [
        "Dov'è il museo? È vicino.",
        "Dov'è il museo? È vicino",
      ],
      hint: "Dov'è for where is; è vicino for it's nearby.",
      tags: ["city", "sentences", "A1"],
      tier: 4,
      prerequisites: ["u04-t1-008", "u04-t1-014"],
    },
    {
      id: "u04-t4-003",
      type: "produce",
      prompt: "She goes to the station.",
      accepted: [
        "Va alla stazione.",
        "Lei va alla stazione.",
        "Lei va alla stazione",
        "Va alla stazione",
      ],
      hint: "lei va + alla (a + la) + stazione.",
      tags: ["city", "sentences", "A1"],
      tier: 4,
      prerequisites: ["u04-t1-007", "u04-t2-003", "u04-t2-008"],
    },
    {
      id: "u04-t4-004",
      type: "produce",
      prompt: "Go straight ahead and then turn right.",
      accepted: [
        "Vai dritto e poi gira a destra.",
        "Vai dritto e poi gira a destra",
        "Vai diritto e poi gira a destra.",
        "Vai diritto e poi gira a destra",
      ],
      hint: "Commands: vai dritto, gira a destra.",
      tags: ["city", "directions", "sentences", "A1"],
      tier: 4,
      prerequisites: ["u04-t1-011", "u04-t1-013"],
    },
    {
      id: "u04-t4-005",
      type: "produce",
      prompt: "We go to the park.",
      accepted: [
        "Andiamo al parco.",
        "Noi andiamo al parco.",
        "Andiamo al parco",
        "Noi andiamo al parco",
      ],
      hint: "andiamo (noi) + al (a + il) + parco.",
      tags: ["city", "sentences", "A1"],
      tier: 4,
      prerequisites: ["u04-t1-010", "u04-t2-004", "u04-t2-007"],
    },
  ],
};

export default unit;
