import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-08-review",
  name: "Putting It Together",
  level: "A1",
  theme: "Mixed A1 Review",
  emoji: "🏰",
  prerequisiteUnits: ["a1-unit-05-time", "a1-unit-06-describing", "a1-unit-07-likes"],
  cards: [
    // ─── TIER 1 — Vocabulary ───────────────────────────────────────────────

    {
      id: "u08-t1-001",
      type: "produce",
      prompt: "the work / job",
      accepted: ["il lavoro", "lavoro"],
      hint: "False friend: 'lavoro' ≠ 'labor' (effort).",
      tags: ["work", "noun", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-002",
      type: "produce",
      prompt: "the office",
      accepted: ["l'ufficio", "ufficio"],
      hint: "Think 'official' place.",
      tags: ["work", "noun", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-003",
      type: "produce",
      prompt: "the colleague",
      accepted: ["il collega", "collega"],
      hint: "Looks like English 'colleague'.",
      tags: ["work", "noun", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-004",
      type: "produce",
      prompt: "the meeting",
      accepted: ["la riunione", "riunione"],
      hint: "Root: riunire = to reunite.",
      tags: ["work", "noun", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-005",
      type: "produce",
      prompt: "the phone",
      accepted: ["il telefono", "telefono"],
      hint: "Same root as English 'telephone'.",
      tags: ["work", "noun", "technology", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-006",
      type: "produce",
      prompt: "the computer",
      accepted: ["il computer", "computer"],
      hint: "Same word, Italian pronunciation.",
      tags: ["work", "noun", "technology", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-007",
      type: "produce",
      prompt: "the message",
      accepted: ["il messaggio", "messaggio"],
      hint: "Double -gg- in Italian.",
      tags: ["work", "noun", "technology", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-008",
      type: "produce",
      prompt: "to write",
      accepted: ["scrivere"],
      hint: "-ERE verb; root in 'script'.",
      tags: ["verb", "-ere", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-009",
      type: "produce",
      prompt: "to send",
      accepted: ["mandare"],
      hint: "-ARE verb; think 'mandate'.",
      tags: ["verb", "-are", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-010",
      type: "produce",
      prompt: "to call (phone)",
      accepted: ["chiamare"],
      hint: "-ARE verb; 'chiamare' sounds like a call.",
      tags: ["verb", "-are", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-011",
      type: "produce",
      prompt: "to understand",
      accepted: ["capire"],
      hint: "-ISC- verb: capisco, capisci…",
      tags: ["verb", "-ire", "-isc-", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-012",
      type: "produce",
      prompt: "to finish",
      accepted: ["finire"],
      hint: "-ISC- verb: finisco, finisci…",
      tags: ["verb", "-ire", "-isc-", "A1"],
      tier: 1,
    },
    {
      id: "u08-t1-013",
      type: "produce",
      prompt: "to begin / start",
      accepted: ["cominciare", "iniziare"],
      hint: "-ARE verb; 'com-' = together + start.",
      tags: ["verb", "-are", "A1"],
      tier: 1,
    },

    // ─── TIER 2 — Grammar (conjugations) ──────────────────────────────────

    {
      id: "u08-t2-001",
      type: "conjugate",
      prompt: "capire – io",
      accepted: ["capisco"],
      hint: "-ISC- insert before endings: -o, -i, -e, -ono.",
      tags: ["conjugation", "-ire", "-isc-", "A1"],
      tier: 2,
      prerequisites: ["u08-t1-011"],
    },
    {
      id: "u08-t2-002",
      type: "conjugate",
      prompt: "finire – io",
      accepted: ["finisco"],
      hint: "-ISC- pattern like capire.",
      tags: ["conjugation", "-ire", "-isc-", "A1"],
      tier: 2,
      prerequisites: ["u08-t1-012"],
    },
    {
      id: "u08-t2-003",
      type: "conjugate",
      prompt: "preferire – io",
      accepted: ["preferisco"],
      hint: "-ISC- pattern; same family as finire.",
      tags: ["conjugation", "-ire", "-isc-", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-004",
      type: "conjugate",
      prompt: "dormire – io",
      accepted: ["dormo"],
      hint: "Regular -IRE without -ISC-: just drop -ire, add -o.",
      tags: ["conjugation", "-ire", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-005",
      type: "conjugate",
      prompt: "scrivere – io",
      accepted: ["scrivo"],
      hint: "Regular -ERE: drop -ere, add -o.",
      tags: ["conjugation", "-ere", "A1"],
      tier: 2,
      prerequisites: ["u08-t1-008"],
    },
    {
      id: "u08-t2-006",
      type: "conjugate",
      prompt: "vedere – io",
      accepted: ["vedo"],
      hint: "Regular -ERE: vedo, vedi, vede…",
      tags: ["conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-007",
      type: "conjugate",
      prompt: "leggere – io",
      accepted: ["leggo"],
      hint: "-ERE; double -gg- in io/loro forms.",
      tags: ["conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-008",
      type: "conjugate",
      prompt: "prendere – io",
      accepted: ["prendo"],
      hint: "Regular -ERE; think 'to take'.",
      tags: ["conjugation", "-ere", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-009",
      type: "conjugate",
      prompt: "potere – io",
      accepted: ["posso"],
      hint: "Irregular modal; stem changes: poss-.",
      tags: ["conjugation", "modal", "irregular", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-010",
      type: "conjugate",
      prompt: "dovere – io",
      accepted: ["devo", "debbo"],
      hint: "Irregular modal; stem: dev-.",
      tags: ["conjugation", "modal", "irregular", "A1"],
      tier: 2,
    },
    {
      id: "u08-t2-011",
      type: "conjugate",
      prompt: "volere – io",
      accepted: ["voglio"],
      hint: "Irregular modal; remember: voglio.",
      tags: ["conjugation", "modal", "irregular", "A1"],
      tier: 2,
    },

    // ─── TIER 3 — Chunks / Phrases ────────────────────────────────────────

    {
      id: "u08-t3-001",
      type: "produce",
      prompt: "I have to work.",
      accepted: ["Devo lavorare.", "Devo lavorare"],
      hint: "Modal dovere + infinitive.",
      tags: ["phrase", "modal", "work", "A1"],
      tier: 3,
      prerequisites: ["u08-t2-010"],
    },
    {
      id: "u08-t3-002",
      type: "produce",
      prompt: "Can I help you?",
      accepted: ["Posso aiutarti?", "Posso aiutarti", "Posso aiutarLa?"],
      hint: "Modal potere + infinitive + clitic.",
      tags: ["phrase", "modal", "A1"],
      tier: 3,
      prerequisites: ["u08-t2-009"],
    },
    {
      id: "u08-t3-003",
      type: "produce",
      prompt: "I have finished. / I'm done.",
      accepted: ["Ho finito.", "Ho finito"],
      hint: "Passato prossimo of finire: avere + finito.",
      tags: ["phrase", "past", "A1"],
      tier: 3,
      prerequisites: ["u08-t1-012"],
    },
    {
      id: "u08-t3-004",
      type: "produce",
      prompt: "I don't understand.",
      accepted: ["Non capisco.", "Non capisco"],
      hint: "non + verb; -ISC- form.",
      tags: ["phrase", "A1"],
      tier: 3,
      prerequisites: ["u08-t2-001"],
    },
    {
      id: "u08-t3-005",
      type: "produce",
      prompt: "I want to read.",
      accepted: ["Voglio leggere.", "Voglio leggere"],
      hint: "Modal volere + infinitive.",
      tags: ["phrase", "modal", "A1"],
      tier: 3,
      prerequisites: ["u08-t2-011", "u08-t2-007"],
    },
    {
      id: "u08-t3-006",
      type: "produce",
      prompt: "I prefer to write.",
      accepted: ["Preferisco scrivere.", "Preferisco scrivere"],
      hint: "-ISC- form of preferire + infinitive.",
      tags: ["phrase", "A1"],
      tier: 3,
      prerequisites: ["u08-t2-003", "u08-t2-005"],
    },

    // ─── TIER 4 — Sentences ───────────────────────────────────────────────

    {
      id: "u08-t4-001",
      type: "produce",
      prompt: "I have to finish the work and then I can call my mother.",
      accepted: [
        "Devo finire il lavoro e poi posso chiamare mia madre.",
        "Devo finire il lavoro e poi posso chiamare la mia madre.",
      ],
      hint: "Two modals: devo + finire; posso + chiamare.",
      tags: ["sentence", "modal", "work", "family", "A1"],
      tier: 4,
      prerequisites: [
        "u08-t2-010",
        "u08-t1-012",
        "u08-t1-001",
        "u08-t2-009",
        "u08-t1-010",
      ],
    },
    {
      id: "u08-t4-002",
      type: "produce",
      prompt: "I want to send a message to my colleague.",
      accepted: [
        "Voglio mandare un messaggio al mio collega.",
        "Voglio mandare un messaggio al collega.",
      ],
      hint: "volere + infinitive; al = a + il.",
      tags: ["sentence", "modal", "work", "A1"],
      tier: 4,
      prerequisites: [
        "u08-t2-011",
        "u08-t1-009",
        "u08-t1-007",
        "u08-t1-003",
      ],
    },
    {
      id: "u08-t4-003",
      type: "fill_blank",
      prompt: "Non ___ (capire – io) la riunione.",
      accepted: ["capisco"],
      hint: "-ISC- form of capire.",
      tags: ["sentence", "fill-blank", "work", "A1"],
      tier: 4,
      prerequisites: ["u08-t2-001", "u08-t1-004"],
    },
    {
      id: "u08-t4-004",
      type: "produce",
      prompt: "I have to write an email in the office.",
      accepted: [
        "Devo scrivere un'email in ufficio.",
        "Devo scrivere una email in ufficio.",
        "Devo scrivere un'e-mail in ufficio.",
      ],
      hint: "dovere + scrivere; 'in ufficio' no article.",
      tags: ["sentence", "modal", "work", "A1"],
      tier: 4,
      prerequisites: [
        "u08-t2-010",
        "u08-t2-005",
        "u08-t1-002",
      ],
    },
    {
      id: "u08-t4-005",
      type: "produce",
      prompt: "I prefer to start the meeting at nine.",
      accepted: [
        "Preferisco cominciare la riunione alle nove.",
        "Preferisco iniziare la riunione alle nove.",
      ],
      hint: "preferire (-ISC-) + infinitive; alle = a + le.",
      tags: ["sentence", "work", "time", "A1"],
      tier: 4,
      prerequisites: [
        "u08-t2-003",
        "u08-t1-013",
        "u08-t1-004",
      ],
    },
  ],
};

export default unit;
