import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-10-body",
  name: "The Body",
  level: "A1",
  theme: "Body Parts",
  emoji: "🫀",
  prerequisiteUnits: ["a1-unit-06-describing"],
  cards: [
    // -------------------------------------------------------------------------
    // TIER 1 — Vocabulary: body parts
    // Pattern: odd IDs = recognize, even IDs = produce
    // -------------------------------------------------------------------------
    {
      id: "a110-t1-001",
      type: "recognize",
      prompt: "la testa",
      accepted: ["the head", "head"],
      translations: { "es": ["la cabeza"] },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-002",
      type: "produce",
      prompt: "the head",
      accepted: ["la testa"],
      prompts: { "es": "la cabeza" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-003",
      type: "recognize",
      prompt: "la faccia",
      accepted: ["the face", "face"],
      translations: { "es": ["la cara"] },
      hint: "feminine noun — also il viso",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-004",
      type: "produce",
      prompt: "the face",
      accepted: ["la faccia", "il viso"],
      prompts: { "es": "la cara" },
      hint: "la faccia (common) or il viso (slightly formal)",
      tags: ["noun", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-005",
      type: "recognize",
      prompt: "gli occhi",
      accepted: ["the eyes", "eyes"],
      translations: { "es": ["los ojos"] },
      hint: "singular: l'occhio (m.); plural: gli occhi",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-006",
      type: "produce",
      prompt: "the eyes",
      accepted: ["gli occhi"],
      prompts: { "es": "los ojos" },
      hint: "singular: l'occhio — gli occhi in plural",
      tags: ["noun", "masculine", "body", "plural", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-007",
      type: "recognize",
      prompt: "il naso",
      accepted: ["the nose", "nose"],
      translations: { "es": ["la nariz"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-008",
      type: "produce",
      prompt: "the nose",
      accepted: ["il naso"],
      prompts: { "es": "la nariz" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-009",
      type: "recognize",
      prompt: "la bocca",
      accepted: ["the mouth", "mouth"],
      translations: { "es": ["la boca"] },
      hint: "feminine noun — bocca grande = big mouth",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-010",
      type: "produce",
      prompt: "the mouth",
      accepted: ["la bocca"],
      prompts: { "es": "la boca" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-011",
      type: "recognize",
      prompt: "le orecchie",
      accepted: ["the ears", "ears"],
      translations: { "es": ["las orejas"] },
      hint: "singular: l'orecchio (m.) or l'orecchia (f.); plural: le orecchie",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-012",
      type: "produce",
      prompt: "the ears",
      accepted: ["le orecchie"],
      prompts: { "es": "las orejas" },
      hint: "singular: l'orecchio — le orecchie in plural",
      tags: ["noun", "body", "plural", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-013",
      type: "recognize",
      prompt: "il collo",
      accepted: ["the neck", "neck"],
      translations: { "es": ["el cuello"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-014",
      type: "produce",
      prompt: "the neck",
      accepted: ["il collo"],
      prompts: { "es": "el cuello" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-015",
      type: "recognize",
      prompt: "la spalla",
      accepted: ["the shoulder", "shoulder"],
      translations: { "es": ["el hombro"] },
      hint: "feminine noun — plural: le spalle",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-016",
      type: "produce",
      prompt: "the shoulder",
      accepted: ["la spalla"],
      prompts: { "es": "el hombro" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-017",
      type: "recognize",
      prompt: "il braccio",
      accepted: ["the arm", "arm"],
      translations: { "es": ["el brazo"] },
      hint: "masculine noun — irregular plural: le braccia (f. pl.)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-018",
      type: "produce",
      prompt: "the arm",
      accepted: ["il braccio"],
      prompts: { "es": "el brazo" },
      hint: "masculine noun — irregular plural: le braccia",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-019",
      type: "recognize",
      prompt: "il gomito",
      accepted: ["the elbow", "elbow"],
      translations: { "es": ["el codo"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-020",
      type: "produce",
      prompt: "the elbow",
      accepted: ["il gomito"],
      prompts: { "es": "el codo" },
      hint: "masculine noun — plural: i gomiti",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-021",
      type: "recognize",
      prompt: "la mano",
      accepted: ["the hand", "hand"],
      translations: { "es": ["la mano"] },
      hint: "feminine noun — irregular: la mano (f.) despite -o ending",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-022",
      type: "produce",
      prompt: "the hand",
      accepted: ["la mano"],
      prompts: { "es": "la mano" },
      hint: "feminine despite -o ending — plural: le mani",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-023",
      type: "recognize",
      prompt: "il dito",
      accepted: ["the finger", "finger"],
      translations: { "es": ["el dedo"] },
      hint: "masculine noun — irregular plural: le dita (f. pl.)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-024",
      type: "produce",
      prompt: "the finger",
      accepted: ["il dito"],
      prompts: { "es": "el dedo" },
      hint: "masculine noun — irregular plural: le dita",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-025",
      type: "recognize",
      prompt: "il petto",
      accepted: ["the chest", "chest"],
      translations: { "es": ["el pecho"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-026",
      type: "produce",
      prompt: "the chest",
      accepted: ["il petto"],
      prompts: { "es": "el pecho" },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-027",
      type: "recognize",
      prompt: "la schiena",
      accepted: ["the back", "back"],
      translations: { "es": ["la espalda"] },
      hint: "feminine noun — the back of the body",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-028",
      type: "produce",
      prompt: "the back (body)",
      accepted: ["la schiena"],
      prompts: { "es": "la espalda" },
      hint: "feminine noun — la schiena (not il dorso in everyday speech)",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-029",
      type: "recognize",
      prompt: "la pancia",
      accepted: ["the belly", "belly", "the tummy", "tummy", "the stomach", "the abdomen"],
      translations: { "es": ["la barriga", "el vientre"] },
      hint: "feminine noun — informal word for abdomen",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-030",
      type: "produce",
      prompt: "the belly / tummy",
      accepted: ["la pancia"],
      prompts: { "es": "la barriga" },
      hint: "feminine noun — informal; lo stomaco = the internal organ",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-031",
      type: "recognize",
      prompt: "i fianchi",
      accepted: ["the hips", "hips"],
      translations: { "es": ["las caderas"] },
      hint: "singular: il fianco (m.) — plural: i fianchi",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-032",
      type: "produce",
      prompt: "the hips",
      accepted: ["i fianchi"],
      prompts: { "es": "las caderas" },
      hint: "singular: il fianco — i fianchi in plural",
      tags: ["noun", "masculine", "body", "plural", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-033",
      type: "recognize",
      prompt: "la gamba",
      accepted: ["the leg", "leg"],
      translations: { "es": ["la pierna"] },
      hint: "feminine noun — plural: le gambe",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-034",
      type: "produce",
      prompt: "the leg",
      accepted: ["la gamba"],
      prompts: { "es": "la pierna" },
      hint: "feminine noun — plural: le gambe",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-035",
      type: "recognize",
      prompt: "il ginocchio",
      accepted: ["the knee", "knee"],
      translations: { "es": ["la rodilla"] },
      hint: "masculine noun — irregular plural: le ginocchia (f. pl.)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-036",
      type: "produce",
      prompt: "the knee",
      accepted: ["il ginocchio"],
      prompts: { "es": "la rodilla" },
      hint: "masculine noun — irregular plural: le ginocchia",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-037",
      type: "recognize",
      prompt: "il piede",
      accepted: ["the foot", "foot"],
      translations: { "es": ["el pie"] },
      hint: "masculine noun — plural: i piedi",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-038",
      type: "produce",
      prompt: "the foot",
      accepted: ["il piede"],
      prompts: { "es": "el pie" },
      hint: "masculine noun — plural: i piedi",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-039",
      type: "recognize",
      prompt: "il tallone",
      accepted: ["the heel", "heel"],
      translations: { "es": ["el talón"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-040",
      type: "produce",
      prompt: "the heel",
      accepted: ["il tallone"],
      prompts: { "es": "el talón" },
      hint: "masculine noun — plural: i talloni",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-041",
      type: "recognize",
      prompt: "il dente",
      accepted: ["the tooth", "tooth"],
      translations: { "es": ["el diente"] },
      hint: "masculine noun — plural: i denti",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-042",
      type: "produce",
      prompt: "the tooth",
      accepted: ["il dente"],
      prompts: { "es": "el diente" },
      hint: "masculine noun — plural: i denti",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-043",
      type: "recognize",
      prompt: "i capelli",
      accepted: ["the hair", "hair"],
      translations: { "es": ["el cabello", "el pelo"] },
      hint: "plural noun — singular: il capello (one strand)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-044",
      type: "produce",
      prompt: "the hair (on your head)",
      accepted: ["i capelli"],
      prompts: { "es": "el cabello" },
      hint: "usually plural in Italian — i capelli",
      tags: ["noun", "masculine", "body", "plural", "tier1", "A1"],
      tier: 1,
    },

    // --- Extended body parts (seq 150–173) ---
    {
      id: "a110-t1-150",
      type: "recognize",
      prompt: "la lingua",
      accepted: ["the tongue", "tongue", "the language", "language"],
      translations: { "es": ["la lengua"] },
      hint: "feminine noun — lingua = both tongue and language",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-151",
      type: "produce",
      prompt: "the tongue",
      accepted: ["la lingua"],
      prompts: { "es": "la lengua" },
      hint: "also means 'language' — la lingua italiana",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-152",
      type: "recognize",
      prompt: "le labbra",
      accepted: ["the lips", "lips"],
      translations: { "es": ["los labios"] },
      hint: "singular: il labbro (m.) — plural: le labbra (f. pl.)",
      tags: ["noun", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-153",
      type: "produce",
      prompt: "the lips",
      accepted: ["le labbra"],
      prompts: { "es": "los labios" },
      hint: "irregular plural — le labbra (feminine plural)",
      tags: ["noun", "body", "plural", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-154",
      type: "recognize",
      prompt: "la guancia",
      accepted: ["the cheek", "cheek"],
      translations: { "es": ["la mejilla"] },
      hint: "feminine noun — plural: le guance",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-155",
      type: "produce",
      prompt: "the cheek",
      accepted: ["la guancia"],
      prompts: { "es": "la mejilla" },
      hint: "feminine noun — plural: le guance",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-156",
      type: "recognize",
      prompt: "il mento",
      accepted: ["the chin", "chin"],
      translations: { "es": ["la barbilla"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-157",
      type: "produce",
      prompt: "the chin",
      accepted: ["il mento"],
      prompts: { "es": "la barbilla" },
      hint: "masculine noun — plural: i menti",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-158",
      type: "recognize",
      prompt: "la fronte",
      accepted: ["the forehead", "forehead"],
      translations: { "es": ["la frente"] },
      hint: "feminine noun — fronte also means 'front' (mil.)",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-159",
      type: "produce",
      prompt: "the forehead",
      accepted: ["la fronte"],
      prompts: { "es": "la frente" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-160",
      type: "recognize",
      prompt: "il polso",
      accepted: ["the wrist", "wrist", "the pulse", "pulse"],
      translations: { "es": ["la muñeca"] },
      hint: "masculine noun — also means 'pulse'",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-161",
      type: "produce",
      prompt: "the wrist",
      accepted: ["il polso"],
      prompts: { "es": "la muñeca" },
      hint: "masculine noun — also 'pulse' (heartbeat)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-162",
      type: "recognize",
      prompt: "la caviglia",
      accepted: ["the ankle", "ankle"],
      translations: { "es": ["el tobillo"] },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-163",
      type: "produce",
      prompt: "the ankle",
      accepted: ["la caviglia"],
      prompts: { "es": "el tobillo" },
      hint: "feminine noun — plural: le caviglie",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-164",
      type: "recognize",
      prompt: "lo stomaco",
      accepted: ["the stomach", "stomach"],
      translations: { "es": ["el estómago"] },
      hint: "masculine noun — uses 'lo' before s+consonant",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-165",
      type: "produce",
      prompt: "the stomach (internal organ)",
      accepted: ["lo stomaco"],
      prompts: { "es": "el estómago" },
      hint: "lo before s+consonant — lo stomaco",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-166",
      type: "recognize",
      prompt: "il cuore",
      accepted: ["the heart", "heart"],
      translations: { "es": ["el corazón"] },
      hint: "masculine noun — cordial, core — same root",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-167",
      type: "produce",
      prompt: "the heart",
      accepted: ["il cuore"],
      prompts: { "es": "el corazón" },
      hint: "masculine noun — cordial comes from cor (heart)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-168",
      type: "recognize",
      prompt: "le unghie",
      accepted: ["the nails", "nails", "the fingernails", "fingernails"],
      translations: { "es": ["las uñas"] },
      hint: "singular: l'unghia (f.) — plural: le unghie",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-169",
      type: "produce",
      prompt: "the nails / fingernails",
      accepted: ["le unghie"],
      prompts: { "es": "las uñas" },
      hint: "singular: l'unghia — le unghie in plural",
      tags: ["noun", "feminine", "body", "plural", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-170",
      type: "recognize",
      prompt: "la coscia",
      accepted: ["the thigh", "thigh"],
      translations: { "es": ["el muslo"] },
      hint: "feminine noun — plural: le cosce",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-171",
      type: "produce",
      prompt: "the thigh",
      accepted: ["la coscia"],
      prompts: { "es": "el muslo" },
      hint: "feminine noun — plural: le cosce",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-172",
      type: "recognize",
      prompt: "il pollice",
      accepted: ["the thumb", "thumb"],
      translations: { "es": ["el pulgar"] },
      hint: "masculine noun — pollice = thumb and old unit of length (inch)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-173",
      type: "produce",
      prompt: "the thumb",
      accepted: ["il pollice"],
      prompts: { "es": "el pulgar" },
      hint: "masculine noun — plural: i pollici",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },

    // --- Extended body parts, batch 2 (seq 174–183) ---
    {
      id: "a110-t1-174",
      type: "recognize",
      prompt: "la vita",
      accepted: ["the waist"],
      translations: { "es": ["la cintura"] },
      hint: "feminine noun — la vita also means 'life' depending on context",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-175",
      type: "produce",
      prompt: "the waist",
      accepted: ["la vita"],
      prompts: { "es": "la cintura" },
      hint: "feminine noun — same word as 'life', context makes it clear",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-176",
      type: "recognize",
      prompt: "la pelle",
      accepted: ["the skin"],
      translations: { "es": ["la piel"] },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-177",
      type: "produce",
      prompt: "the skin",
      accepted: ["la pelle"],
      prompts: { "es": "la piel" },
      hint: "feminine noun",
      tags: ["noun", "feminine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-178",
      type: "recognize",
      prompt: "il sopracciglio",
      accepted: ["the eyebrow", "eyebrow"],
      translations: { "es": ["la ceja"] },
      hint: "masculine noun — irregular plural: le sopracciglia (f. pl.)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-179",
      type: "produce",
      prompt: "the eyebrow",
      accepted: ["il sopracciglio"],
      prompts: { "es": "la ceja" },
      hint: "masculine noun — irregular plural: le sopracciglia",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-180",
      type: "recognize",
      prompt: "l'osso",
      accepted: ["the bone", "bone"],
      translations: { "es": ["el hueso"] },
      hint: "masculine noun — irregular plural: le ossa (f. pl.)",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-181",
      type: "produce",
      prompt: "the bone",
      accepted: ["l'osso"],
      prompts: { "es": "el hueso" },
      hint: "masculine noun — irregular plural: le ossa",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-182",
      type: "recognize",
      prompt: "il muscolo",
      accepted: ["the muscle", "muscle"],
      translations: { "es": ["el músculo"] },
      hint: "masculine noun",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },
    {
      id: "a110-t1-183",
      type: "produce",
      prompt: "the muscle",
      accepted: ["il muscolo"],
      prompts: { "es": "el músculo" },
      hint: "masculine noun — plural: i muscoli",
      tags: ["noun", "masculine", "body", "tier1", "A1"],
      tier: 1,
    },

    // -------------------------------------------------------------------------
    // TIER 2 — Grammar: "mi fa male" / "mi fanno male" agreement, stare bene/male/così così, sentirsi
    // -------------------------------------------------------------------------
    {
      id: "a110-t2-001",
      type: "conjugate",
      prompt: "Conjugate 'stare' (to be / to feel) — all six persons",
      accepted: ["io sto, tu stai, lui/lei sta, noi stiamo, voi state, loro stanno"],
      hint: "Irregular — sto, stai, sta, stiamo, state, stanno",
      tags: ["verb", "stare", "grammar", "body", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-002",
      type: "conjugate",
      prompt: "Conjugate 'sentirsi' (to feel) — all six persons",
      accepted: ["io mi sento, tu ti senti, lui/lei si sente, noi ci sentiamo, voi vi sentite, loro si sentono"],
      hint: "Reflexive: mi/ti/si/ci/vi/si before sento/senti/sente...",
      tags: ["verb", "sentirsi", "reflexive", "grammar", "body", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-003",
      type: "fill_blank",
      prompt: "Mi ___ male la testa dopo tanto studio.",
      accepted: ["fa"],
      hint: "fare + male: singular body part (la testa) → fa",
      tags: ["grammar", "fare-male", "body", "singular", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-004",
      type: "fill_blank",
      prompt: "Mi ___ male i piedi dopo la lunga camminata.",
      accepted: ["fanno"],
      hint: "fare + male: plural body part (i piedi) → fanno",
      tags: ["grammar", "fare-male", "body", "plural", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-005",
      type: "fill_blank",
      prompt: "Ci ___ male le gambe dopo la partita.",
      accepted: ["fanno"],
      hint: "ci = us; le gambe is plural → fanno",
      tags: ["grammar", "fare-male", "body", "plural", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-006",
      type: "fill_blank",
      prompt: "Ti ___ male lo stomaco se mangi troppo in fretta.",
      accepted: ["fa"],
      hint: "ti = you; lo stomaco is singular → fa",
      tags: ["grammar", "fare-male", "body", "singular", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-007",
      type: "fill_blank",
      prompt: "Gli ___ male le orecchie quando la musica è alta.",
      accepted: ["fanno"],
      hint: "gli = to him; le orecchie is plural → fanno",
      tags: ["grammar", "fare-male", "body", "plural", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-008",
      type: "fill_blank",
      prompt: "Le ___ male la schiena dopo il lavoro in giardino.",
      accepted: ["fa"],
      hint: "le = to her; la schiena is singular → fa",
      tags: ["grammar", "fare-male", "body", "singular", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-009",
      type: "fill_blank",
      prompt: "— Come stai? — ___ bene, grazie.",
      accepted: ["Sto"],
      hint: "io form of stare",
      tags: ["grammar", "stare", "body", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-010",
      type: "fill_blank",
      prompt: "Oggi non mi sento bene, sto ___.",
      accepted: ["male"],
      hint: "opposite of bene",
      tags: ["grammar", "stare", "body", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-011",
      type: "fill_blank",
      prompt: "— Come va? — ___, non benissimo ma nemmeno male.",
      accepted: ["Così così"],
      hint: "così così = so-so",
      tags: ["grammar", "stare", "body", "tier2", "A1"],
      tier: 2,
    },
    {
      id: "a110-t2-012",
      type: "fill_blank",
      prompt: "Luca non si ___ bene, ha la febbre.",
      accepted: ["sente"],
      hint: "lui form of sentirsi",
      tags: ["grammar", "sentirsi", "body", "tier2", "A1"],
      tier: 2,
    },

    // -------------------------------------------------------------------------
    // TIER 3 — Chunks: body phrases
    // -------------------------------------------------------------------------
    {
      id: "a110-t3-001",
      type: "produce",
      prompt: "My head hurts.",
      accepted: ["Mi fa male la testa.", "Ho mal di testa."],
      prompts: { "es": "Me duele la cabeza." },
      hint: "mi fa male = hurts me; ho mal di = I have an ache in",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-002",
      type: "produce",
      prompt: "She has blue eyes.",
      accepted: ["Ha gli occhi azzurri.", "Ha gli occhi blu."],
      prompts: { "es": "Ella tiene los ojos azules." },
      hint: "avere + body part + color = to have colored body parts",
      tags: ["chunk", "body", "color", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-003",
      type: "produce",
      prompt: "Wash your hands.",
      accepted: ["Lavati le mani.", "Si lavi le mani."],
      prompts: { "es": "Lávate las manos." },
      hint: "lavarsi = reflexive; le mani = the hands (article used with body parts)",
      tags: ["chunk", "body", "reflexive", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-004",
      type: "produce",
      prompt: "I hurt my knee.",
      accepted: ["Mi fa male il ginocchio.", "Mi sono fatto male al ginocchio."],
      prompts: { "es": "Me duele la rodilla." },
      hint: "mi fa male = hurts me; al ginocchio = at/in the knee",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-005",
      type: "produce",
      prompt: "He has long hair.",
      accepted: ["Ha i capelli lunghi."],
      prompts: { "es": "Él tiene el pelo largo." },
      hint: "avere + i capelli + adjective; capelli is plural → lunghi",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-100",
      type: "produce",
      prompt: "My stomach hurts.",
      accepted: ["Mi fa male lo stomaco.", "Ho mal di stomaco."],
      prompts: { "es": "Me duele el estómago." },
      hint: "mi fa male + body part",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-101",
      type: "produce",
      prompt: "My feet hurt.",
      accepted: ["Mi fanno male i piedi."],
      prompts: { "es": "Me duelen los pies." },
      hint: "fanno = plural of fa (fare) — i piedi is plural",
      tags: ["chunk", "body", "health", "plural", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-102",
      type: "produce",
      prompt: "She has brown eyes.",
      accepted: ["Ha gli occhi marroni.", "Ha gli occhi castani."],
      prompts: { "es": "Ella tiene los ojos marrones." },
      hint: "castani = chestnut brown (for eyes/hair); marroni also works",
      tags: ["chunk", "body", "color", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-103",
      type: "produce",
      prompt: "He has a big nose.",
      accepted: ["Ha il naso grande."],
      prompts: { "es": "Él tiene la nariz grande." },
      hint: "avere + il naso + adjective; grande = big",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-104",
      type: "produce",
      prompt: "I have cold hands.",
      accepted: ["Ho le mani fredde."],
      prompts: { "es": "Tengo las manos frías." },
      hint: "avere + le mani + adjective; mani (f. pl.) → fredde",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-105",
      type: "produce",
      prompt: "She has curly hair.",
      accepted: ["Ha i capelli ricci."],
      prompts: { "es": "Ella tiene el pelo rizado." },
      hint: "ricci = curly (m. pl.); capelli is masculine plural",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-106",
      type: "produce",
      prompt: "Open your mouth.",
      accepted: ["Apri la bocca.", "Apra la bocca."],
      prompts: { "es": "Abre la boca." },
      hint: "apri = informal imperative; apra = formal imperative",
      tags: ["chunk", "body", "imperative", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-107",
      type: "produce",
      prompt: "My arms are tired.",
      accepted: ["Ho le braccia stanche."],
      prompts: { "es": "Tengo los brazos cansados." },
      hint: "le braccia (f. pl.) → stanche; avere = to have/feel",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-108",
      type: "produce",
      prompt: "My neck is stiff.",
      accepted: ["Ho il collo rigido.", "Mi fa male il collo."],
      prompts: { "es": "Tengo el cuello rígido." },
      hint: "rigido = stiff/rigid; il collo (m.) → rigido",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-109",
      type: "produce",
      prompt: "He has strong shoulders.",
      accepted: ["Ha le spalle forti."],
      prompts: { "es": "Él tiene los hombros fuertes." },
      hint: "le spalle (f. pl.) → forti; forti = strong (pl.)",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-110",
      type: "produce",
      prompt: "Good luck!",
      accepted: ["In bocca al lupo!"],
      prompts: { "es": "¡Buena suerte!" },
      hint: "literally 'in the mouth of the wolf' — traditional reply: Crepi!",
      tags: ["chunk", "body", "idiom", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-111",
      type: "produce",
      prompt: "He has his head in the clouds.",
      accepted: ["Ha la testa tra le nuvole."],
      prompts: { "es": "Tiene la cabeza en las nubes." },
      hint: "idiom for absent-minded or distracted",
      tags: ["chunk", "body", "idiom", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-112",
      type: "produce",
      prompt: "This dress costs an arm and a leg.",
      accepted: ["Questo vestito costa un occhio della testa."],
      prompts: { "es": "Este vestido cuesta un ojo de la cara." },
      hint: "literally 'costs an eye of the head' — very expensive",
      tags: ["chunk", "body", "idiom", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-113",
      type: "produce",
      prompt: "Keep an eye on the children.",
      accepted: ["Tieni d'occhio i bambini."],
      prompts: { "es": "Vigila a los niños." },
      hint: "tenere d'occhio = to keep an eye on; tieni = informal imperative",
      tags: ["chunk", "body", "idiom", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-114",
      type: "produce",
      prompt: "I vouch for him completely.",
      accepted: ["Metto la mano sul fuoco per lui."],
      prompts: { "es": "Pongo la mano en el fuego por él." },
      hint: "literally 'I put my hand in the fire for him' — I'm certain about him",
      tags: ["chunk", "body", "idiom", "tier3", "A1"],
      tier: 3,
    },

    // --- Extended body-part sentences (seq 115–129) — coverage for words not yet drilled in context ---
    {
      id: "a110-t3-115",
      type: "produce",
      prompt: "My elbow hurts after tennis.",
      accepted: ["Mi fa male il gomito dopo il tennis."],
      prompts: { "es": "Me duele el codo después del tenis." },
      hint: "mi fa male + il gomito (m., singular)",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-116",
      type: "produce",
      prompt: "My finger hurts, my thumb too.",
      accepted: ["Mi fa male il dito, anche il pollice."],
      prompts: { "es": "Me duele el dedo, también el pulgar." },
      hint: "anche = also/too; both il dito and il pollice are masculine singular",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-117",
      type: "produce",
      prompt: "I cut my nails every week.",
      accepted: ["Taglio le unghie ogni settimana."],
      prompts: { "es": "Me corto las uñas cada semana." },
      hint: "tagliare le unghie = to cut one's nails",
      tags: ["chunk", "body", "grooming", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-118",
      type: "produce",
      prompt: "My chest hurts when I run.",
      accepted: ["Mi fa male il petto quando corro."],
      prompts: { "es": "Me duele el pecho cuando corro." },
      hint: "corro = io form of correre",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-119",
      type: "produce",
      prompt: "The heart beats fast after a run.",
      accepted: ["Il cuore batte forte dopo la corsa."],
      prompts: { "es": "El corazón late fuerte después de correr." },
      hint: "battere = to beat; la corsa = the run (noun)",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-120",
      type: "produce",
      prompt: "I have a full belly and wide hips.",
      accepted: ["Ho la pancia piena e i fianchi larghi."],
      prompts: { "es": "Tengo la barriga llena y las caderas anchas." },
      hint: "piena agrees with la pancia (f.); larghi agrees with i fianchi (m. pl.)",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-121",
      type: "produce",
      prompt: "My right leg hurts.",
      accepted: ["Mi fa male la gamba destra."],
      prompts: { "es": "Me duele la pierna derecha." },
      hint: "destra = right, agrees with la gamba (f.)",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-122",
      type: "produce",
      prompt: "I have a swollen thigh today.",
      accepted: ["Ho la coscia gonfia oggi."],
      prompts: { "es": "Tengo el muslo hinchado hoy." },
      hint: "gonfia = swollen, agrees with la coscia (f.)",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-123",
      type: "produce",
      prompt: "My foot hurts, my heel too.",
      accepted: ["Mi fa male il piede, anche il tallone."],
      prompts: { "es": "Me duele el pie, también el talón." },
      hint: "anche = also/too; both il piede and il tallone are masculine singular",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-124",
      type: "produce",
      prompt: "My tooth has hurt since yesterday.",
      accepted: ["Mi fa male il dente da ieri."],
      prompts: { "es": "Me duele el diente desde ayer." },
      hint: "da ieri = since yesterday",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-125",
      type: "produce",
      prompt: "I have a burnt tongue and dry lips.",
      accepted: ["Ho la lingua bruciata e le labbra secche."],
      prompts: { "es": "Tengo la lengua quemada y los labios secos." },
      hint: "bruciata agrees with la lingua (f.); secche agrees with le labbra (f. pl.)",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-126",
      type: "produce",
      prompt: "The little girl has a red cheek.",
      accepted: ["La bambina ha la guancia rossa."],
      prompts: { "es": "La niña tiene la mejilla roja." },
      hint: "rossa agrees with la guancia (f.)",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-127",
      type: "produce",
      prompt: "He has a small chin and a high forehead.",
      accepted: ["Ha il mento piccolo e la fronte alta."],
      prompts: { "es": "Tiene la barbilla pequeña y la frente alta." },
      hint: "piccolo agrees with il mento (m.); alta agrees with la fronte (f.)",
      tags: ["chunk", "body", "description", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-128",
      type: "produce",
      prompt: "The doctor checks the wrist and the ankle.",
      accepted: ["Il dottore controlla il polso e la caviglia."],
      prompts: { "es": "El médico revisa la muñeca y el tobillo." },
      hint: "controllare = to check/examine",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },
    {
      id: "a110-t3-129",
      type: "produce",
      prompt: "He has an eyebrow scratched by the cat.",
      accepted: ["Ha il sopracciglio graffiato dal gatto."],
      prompts: { "es": "Tiene la ceja arañada por el gato." },
      hint: "graffiato = scratched; dal = da + il",
      tags: ["chunk", "body", "health", "tier3", "A1"],
      tier: 3,
    },

    // -------------------------------------------------------------------------
    // TIER 4 — Sentences
    // -------------------------------------------------------------------------
    {
      id: "a110-t4-100",
      type: "produce",
      prompt: "Marco is tall and has long legs.",
      accepted: ["Marco è alto e ha le gambe lunghe."],
      prompts: { "es": "Marco es alto y tiene las piernas largas." },
      hint: "le gambe (f. pl.) → lunghe",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-033", "a110-t1-034"],
    },
    {
      id: "a110-t4-101",
      type: "produce",
      prompt: "Giulia has black hair and brown eyes.",
      accepted: ["Giulia ha i capelli neri e gli occhi marroni.", "Giulia ha i capelli neri e gli occhi castani."],
      prompts: { "es": "Giulia tiene el pelo negro y los ojos marrones." },
      hint: "capelli (m. pl.) → neri; occhi (m. pl.) → marroni",
      tags: ["sentence", "body", "color", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-005", "a110-t1-043"],
    },
    {
      id: "a110-t4-102",
      type: "produce",
      prompt: "The doctor touches my shoulder.",
      accepted: ["Il medico mi tocca la spalla."],
      prompts: { "es": "El médico me toca el hombro." },
      hint: "mi tocca = touches me; la spalla (f.) — article used with body parts",
      tags: ["sentence", "body", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-015", "a110-t1-016"],
    },
    {
      id: "a110-t4-104",
      type: "produce",
      prompt: "My hands are cold and my feet are tired.",
      accepted: ["Ho le mani fredde e i piedi stanchi."],
      prompts: { "es": "Tengo las manos frías y los pies cansados." },
      hint: "le mani (f. pl.) → fredde; i piedi (m. pl.) → stanchi",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-021", "a110-t1-037", "a110-t3-104"],
    },
    {
      id: "a110-t4-105",
      type: "produce",
      prompt: "Does your back hurt?",
      accepted: ["Ti fa male la schiena?"],
      prompts: { "es": "¿Te duele la espalda?" },
      hint: "ti fa male = hurts you; la schiena (f.)",
      tags: ["sentence", "body", "health", "question", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-027", "a110-t1-028", "a110-t3-001"],
    },
    {
      id: "a110-t4-107",
      type: "produce",
      prompt: "He has a thin face and a wide mouth.",
      accepted: ["Ha la faccia sottile e la bocca larga."],
      prompts: { "es": "Él tiene la cara delgada y la boca ancha." },
      hint: "la faccia (f.) → sottile; la bocca (f.) → larga",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-003", "a110-t1-009"],
    },
    {
      id: "a110-t4-108",
      type: "produce",
      prompt: "My son has dark eyes.",
      accepted: ["Mio figlio ha gli occhi scuri."],
      prompts: { "es": "Mi hijo tiene los ojos oscuros." },
      hint: "gli occhi (m. pl.) → scuri; mio figlio (no article with family)",
      tags: ["sentence", "body", "color", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-005", "a110-t1-006"],
    },
    {
      id: "a110-t4-109",
      type: "produce",
      prompt: "I can't see well — my eyes hurt.",
      accepted: ["Non vedo bene — mi fanno male gli occhi."],
      prompts: { "es": "No veo bien — me duelen los ojos." },
      hint: "non vedo = I don't see; fanno (plural) because gli occhi is plural",
      tags: ["sentence", "body", "health", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-005", "a110-t3-001", "a110-t3-101"],
    },
    {
      id: "a110-t4-110",
      type: "produce",
      prompt: "After the run, my legs and my back hurt.",
      accepted: ["Dopo la corsa, mi fanno male le gambe e la schiena."],
      prompts: { "es": "Después de correr, me duelen las piernas y la espalda." },
      hint: "fanno agrees with the compound plural subject",
      tags: ["sentence", "body", "health", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-033", "a110-t1-027", "a110-t3-101"],
    },
    {
      id: "a110-t4-111",
      type: "produce",
      prompt: "My skin is very sensitive to the sun.",
      accepted: ["La mia pelle è molto sensibile al sole."],
      prompts: { "es": "Mi piel es muy sensible al sol." },
      hint: "la pelle (f.) → sensibile",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-176"],
    },
    {
      id: "a110-t4-112",
      type: "produce",
      prompt: "The doctor checks the bone in my arm.",
      accepted: ["Il medico controlla l'osso del braccio."],
      prompts: { "es": "El médico revisa el hueso del brazo." },
      hint: "l'osso (m. sing.) — irregular plural le ossa",
      tags: ["sentence", "body", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-180", "a110-t1-017"],
    },
    {
      id: "a110-t4-113",
      type: "produce",
      prompt: "She has a thin waist and broad shoulders.",
      accepted: ["Ha la vita sottile e le spalle larghe."],
      prompts: { "es": "Ella tiene la cintura delgada y los hombros anchos." },
      hint: "la vita (f.) → sottile; le spalle (f. pl.) → larghe",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-174", "a110-t1-015"],
    },
    {
      id: "a110-t4-114",
      type: "produce",
      prompt: "I have a strong muscle in my arm.",
      accepted: ["Ho un muscolo forte nel braccio."],
      prompts: { "es": "Tengo un músculo fuerte en el brazo." },
      hint: "un muscolo (m.) → forte; nel = in + il",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-182", "a110-t1-017"],
    },
    {
      id: "a110-t4-115",
      type: "produce",
      prompt: "His eyebrows are thick and dark.",
      accepted: ["Le sue sopracciglia sono spesse e scure."],
      prompts: { "es": "Sus cejas son gruesas y oscuras." },
      hint: "le sopracciglia (irregular f. pl.) → spesse, scure",
      tags: ["sentence", "body", "description", "tier4", "A1"],
      tier: 4,
      prerequisites: ["a110-t1-178"],
    },
  ],
};

export default unit;
