import type { Unit } from "@/content/types";

const unit: Unit = {
  id: "a1-unit-03-family",
  name: "Family & Home",
  level: "A1",
  theme: "Family & Home",
  emoji: "🏠",
  prerequisiteUnits: ["a1-unit-01-greetings"],
  cards: [
    // =========================================================
    // TIER 1 — Vocabulary
    // =========================================================
    {
      id: "u03-t1-001",
      type: "produce",
      prompt: "the mother",
      accepted: ["la madre"],
      hint: "feminine noun",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-002",
      type: "produce",
      prompt: "the father",
      accepted: ["il padre"],
      hint: "masculine noun",
      tags: ["family", "noun", "masculine"],
      tier: 1,
    },
    {
      id: "u03-t1-003",
      type: "produce",
      prompt: "the sister",
      accepted: ["la sorella"],
      hint: "feminine noun",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-004",
      type: "produce",
      prompt: "the brother",
      accepted: ["il fratello"],
      hint: "masculine noun",
      tags: ["family", "noun", "masculine"],
      tier: 1,
    },
    {
      id: "u03-t1-005",
      type: "produce",
      prompt: "the grandmother",
      accepted: ["la nonna"],
      hint: "feminine noun",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-006",
      type: "produce",
      prompt: "the grandfather",
      accepted: ["il nonno"],
      hint: "masculine noun",
      tags: ["family", "noun", "masculine"],
      tier: 1,
    },
    {
      id: "u03-t1-007",
      type: "produce",
      prompt: "the husband",
      accepted: ["il marito"],
      hint: "masculine noun",
      tags: ["family", "noun", "masculine"],
      tier: 1,
    },
    {
      id: "u03-t1-008",
      type: "produce",
      prompt: "the wife",
      accepted: ["la moglie"],
      hint: "feminine noun — irregular plural: mogli",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-009",
      type: "produce",
      prompt: "the son",
      accepted: ["il figlio"],
      hint: "masculine noun",
      tags: ["family", "noun", "masculine"],
      tier: 1,
    },
    {
      id: "u03-t1-010",
      type: "produce",
      prompt: "the daughter",
      accepted: ["la figlia"],
      hint: "feminine noun",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-011",
      type: "produce",
      prompt: "the family",
      accepted: ["la famiglia"],
      hint: "feminine noun",
      tags: ["family", "noun", "feminine"],
      tier: 1,
    },
    {
      id: "u03-t1-012",
      type: "produce",
      prompt: "the house",
      accepted: ["la casa"],
      hint: "feminine noun",
      tags: ["home", "noun", "feminine"],
      tier: 1,
    },

    // =========================================================
    // TIER 2 — Grammar
    // =========================================================

    // Possessives — singular family nouns drop the article
    {
      id: "u03-t2-001",
      type: "produce",
      prompt: "my mother",
      accepted: ["mia madre"],
      hint: "singular family nouns drop the article with possessives: 'mia madre' NOT 'la mia madre'",
      tags: ["possessives", "family", "feminine"],
      tier: 2,
      prerequisites: ["u03-t1-001"],
    },
    {
      id: "u03-t2-002",
      type: "produce",
      prompt: "my brother",
      accepted: ["mio fratello"],
      hint: "singular family nouns drop the article: 'mio fratello' NOT 'il mio fratello'",
      tags: ["possessives", "family", "masculine"],
      tier: 2,
      prerequisites: ["u03-t1-004"],
    },
    {
      id: "u03-t2-003",
      type: "produce",
      prompt: "his/her sister",
      accepted: ["sua sorella"],
      hint: "suo/sua = his or her; singular family nouns drop the article",
      tags: ["possessives", "family", "feminine"],
      tier: 2,
      prerequisites: ["u03-t1-003"],
    },
    {
      id: "u03-t2-004",
      type: "produce",
      prompt: "your father",
      accepted: ["tuo padre"],
      hint: "tuo = your (informal singular); singular family nouns drop the article",
      tags: ["possessives", "family", "masculine"],
      tier: 2,
      prerequisites: ["u03-t1-002"],
    },
    {
      id: "u03-t2-005",
      type: "produce",
      prompt: "our family",
      accepted: ["la nostra famiglia"],
      hint: "nostra = our (feminine); plural and non-singular family nouns KEEP the article",
      tags: ["possessives", "family", "feminine"],
      tier: 2,
      prerequisites: ["u03-t1-011"],
    },

    // avere conjugation
    {
      id: "u03-t2-006",
      type: "conjugate",
      prompt: "Conjugate 'avere' (to have) — io (I)",
      accepted: ["ho", "io ho"],
      hint: "the 'h' is silent; avere is irregular",
      tags: ["avere", "conjugation", "present", "first-person"],
      tier: 2,
    },
    {
      id: "u03-t2-007",
      type: "conjugate",
      prompt: "Conjugate 'avere' (to have) — tu (you, informal)",
      accepted: ["hai", "tu hai"],
      hint: "the 'h' is silent",
      tags: ["avere", "conjugation", "present", "second-person"],
      tier: 2,
    },
    {
      id: "u03-t2-008",
      type: "conjugate",
      prompt: "Conjugate 'avere' (to have) — lui/lei (he/she)",
      accepted: ["ha", "lui ha", "lei ha"],
      hint: "the 'h' is silent",
      tags: ["avere", "conjugation", "present", "third-person"],
      tier: 2,
    },

    // chiamarsi
    {
      id: "u03-t2-009",
      type: "produce",
      prompt: "his/her name is (reflexive verb form)",
      accepted: ["si chiama"],
      hint: "chiamarsi = to be called; si chiama is the third-person singular form",
      tags: ["chiamarsi", "reflexive", "verb", "present"],
      tier: 2,
    },

    // ita_to_eng check for key possessive rule
    {
      id: "u03-t2-010",
      type: "recognize",
      prompt: "mia moglie",
      accepted: ["my wife"],
      hint: "singular family nouns drop the article with possessives",
      tags: ["possessives", "family", "feminine"],
      tier: 2,
      prerequisites: ["u03-t1-008"],
    },

    // =========================================================
    // TIER 3 — Chunks
    // =========================================================
    {
      id: "u03-t3-001",
      type: "produce",
      prompt: "I have a sister",
      accepted: ["Ho una sorella"],
      hint: "use avere (to have); una = a (feminine)",
      tags: ["avere", "family", "chunk"],
      tier: 3,
      prerequisites: ["u03-t1-003", "u03-t2-006"],
    },
    {
      id: "u03-t3-002",
      type: "produce",
      prompt: "I have a brother",
      accepted: ["Ho un fratello"],
      hint: "use avere (to have); un = a (masculine)",
      tags: ["avere", "family", "chunk"],
      tier: 3,
      prerequisites: ["u03-t1-004", "u03-t2-006"],
    },
    {
      id: "u03-t3-003",
      type: "produce",
      prompt: "There are three of us (lit. we are three)",
      accepted: ["Siamo in tre"],
      hint: "siamo = we are; in tre = in three",
      tags: ["essere", "numbers", "family", "chunk"],
      tier: 3,
    },
    {
      id: "u03-t3-004",
      type: "produce",
      prompt: "My family is big",
      accepted: ["La mia famiglia è grande"],
      hint: "famiglia keeps the article because it is modified by 'la mia'; grande = big",
      tags: ["possessives", "essere", "family", "chunk"],
      tier: 3,
      prerequisites: ["u03-t1-011", "u03-t2-005"],
    },
    {
      id: "u03-t3-005",
      type: "produce",
      prompt: "at home",
      accepted: ["a casa"],
      hint: "no article needed with 'a casa'",
      tags: ["home", "preposition", "chunk"],
      tier: 3,
      prerequisites: ["u03-t1-012"],
    },
    {
      id: "u03-t3-006",
      type: "recognize",
      prompt: "si chiama",
      accepted: ["his name is", "her name is", "his/her name is", "they are called", "he is called", "she is called"],
      hint: "third-person singular of chiamarsi",
      tags: ["chiamarsi", "reflexive", "chunk"],
      tier: 3,
      prerequisites: ["u03-t2-009"],
    },
    {
      id: "u03-t3-007",
      type: "produce",
      prompt: "my husband / my wife",
      accepted: ["mio marito", "mia moglie"],
      hint: "singular family nouns drop the article; marito = masculine, moglie = feminine",
      tags: ["possessives", "family", "chunk"],
      tier: 3,
      prerequisites: ["u03-t1-007", "u03-t1-008", "u03-t2-001"],
    },

    // =========================================================
    // TIER 4 — Sentences
    // =========================================================
    {
      id: "u03-t4-001",
      type: "produce",
      prompt: "My mother's name is Anna and my father's name is Luca.",
      accepted: [
        "Mia madre si chiama Anna e mio padre si chiama Luca.",
        "Mia madre si chiama Anna e mio padre si chiama Luca",
      ],
      hint: "use si chiama for 'name is'; madre and padre drop the article with possessives",
      tags: ["sentence", "family", "chiamarsi", "possessives"],
      tier: 4,
      prerequisites: [
        "u03-t1-001",
        "u03-t1-002",
        "u03-t2-001",
        "u03-t2-004",
        "u03-t2-009",
      ],
    },
    {
      id: "u03-t4-002",
      type: "produce",
      prompt: "I have a sister and a brother.",
      accepted: [
        "Ho una sorella e un fratello.",
        "Ho una sorella e un fratello",
      ],
      hint: "use avere; una sorella (feminine), un fratello (masculine)",
      tags: ["sentence", "family", "avere"],
      tier: 4,
      prerequisites: [
        "u03-t1-003",
        "u03-t1-004",
        "u03-t2-006",
      ],
    },
    {
      id: "u03-t4-003",
      type: "produce",
      prompt: "Our family is big.",
      accepted: [
        "La nostra famiglia è grande.",
        "La nostra famiglia è grande",
      ],
      hint: "nostra keeps the article because famiglia is not a strictly singular close-family noun in this construction",
      tags: ["sentence", "family", "possessives", "essere"],
      tier: 4,
      prerequisites: [
        "u03-t1-011",
        "u03-t2-005",
      ],
    },
    {
      id: "u03-t4-004",
      type: "produce",
      prompt: "My grandfather lives at our house.",
      accepted: [
        "Mio nonno abita a casa nostra.",
        "Mio nonno abita a casa nostra",
      ],
      hint: "abita = he lives/resides; 'a casa nostra' = at our house (nostra follows casa here)",
      tags: ["sentence", "family", "home", "possessives"],
      tier: 4,
      prerequisites: [
        "u03-t1-006",
        "u03-t1-012",
        "u03-t3-005",
      ],
    },
    {
      id: "u03-t4-005",
      type: "fill_blank",
      prompt: "Mia ___ si chiama Maria.",
      accepted: ["sorella", "madre", "nonna", "moglie"],
      hint: "think of feminine family members whose name you might share",
      tags: ["sentence", "family", "fill-blank", "chiamarsi"],
      tier: 4,
      prerequisites: [
        "u03-t1-001",
        "u03-t1-003",
        "u03-t1-005",
        "u03-t1-008",
        "u03-t2-009",
      ],
    },
  ],
};

export default unit;
