import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-32-at-the-doctor",
  name: "At the Doctor",
  level: "A2",
  theme: "Health & Medical Visits",
  emoji: "🏥",
  prerequisiteUnits: ["a2-unit-31-passato-vs-imperfetto"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "a232-t1-001", type: "recognize", prompt: "l'appuntamento", accepted: ["appointment"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-002", type: "produce", prompt: "appointment", accepted: ["l'appuntamento"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-003", type: "recognize", prompt: "prendere un appuntamento", accepted: ["to make an appointment"], tags: ["health", "doctor", "verb-phrase"], tier: 1 },
    { id: "a232-t1-004", type: "produce", prompt: "to make an appointment", accepted: ["prendere un appuntamento"], tags: ["health", "doctor", "verb-phrase"], tier: 1 },
    { id: "a232-t1-005", type: "recognize", prompt: "il pronto soccorso", accepted: ["the emergency room"], tags: ["health", "emergency", "noun"], tier: 1 },
    { id: "a232-t1-006", type: "produce", prompt: "the emergency room", accepted: ["il pronto soccorso"], tags: ["health", "emergency", "noun"], tier: 1 },
    { id: "a232-t1-007", type: "recognize", prompt: "l'ambulanza", accepted: ["ambulance"], tags: ["health", "emergency", "noun"], tier: 1 },
    { id: "a232-t1-008", type: "produce", prompt: "ambulance", accepted: ["l'ambulanza"], tags: ["health", "emergency", "noun"], tier: 1 },
    { id: "a232-t1-009", type: "recognize", prompt: "urgente", accepted: ["urgent"], tags: ["health", "emergency", "adjective"], tier: 1 },
    { id: "a232-t1-010", type: "produce", prompt: "urgent", accepted: ["urgente"], tags: ["health", "emergency", "adjective"], tier: 1 },
    { id: "a232-t1-011", type: "recognize", prompt: "la ricetta", accepted: ["prescription"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-012", type: "produce", prompt: "prescription", accepted: ["la ricetta"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-013", type: "recognize", prompt: "il farmaco", accepted: ["medication", "medicine"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-014", type: "produce", prompt: "medication", accepted: ["il farmaco"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-015", type: "recognize", prompt: "la farmacia", accepted: ["pharmacy"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-016", type: "produce", prompt: "pharmacy", accepted: ["la farmacia"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-017", type: "recognize", prompt: "il farmacista", accepted: ["pharmacist"], hint: "feminine form: la farmacista", tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-018", type: "produce", prompt: "pharmacist", accepted: ["il farmacista", "la farmacista"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-019", type: "recognize", prompt: "la febbre", accepted: ["fever"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-020", type: "produce", prompt: "fever", accepted: ["la febbre"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-021", type: "recognize", prompt: "avere la febbre", accepted: ["to have a fever"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-022", type: "produce", prompt: "to have a fever", accepted: ["avere la febbre"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-023", type: "recognize", prompt: "il mal di testa", accepted: ["headache"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-024", type: "produce", prompt: "headache", accepted: ["il mal di testa"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-025", type: "recognize", prompt: "il mal di gola", accepted: ["sore throat"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-026", type: "produce", prompt: "sore throat", accepted: ["il mal di gola"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-027", type: "recognize", prompt: "il mal di stomaco", accepted: ["stomachache"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-028", type: "produce", prompt: "stomachache", accepted: ["il mal di stomaco"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-029", type: "recognize", prompt: "il mal di schiena", accepted: ["backache"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-030", type: "produce", prompt: "backache", accepted: ["il mal di schiena"], tags: ["health", "symptom", "noun-phrase"], tier: 1 },
    { id: "a232-t1-031", type: "recognize", prompt: "la tosse", accepted: ["cough"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-032", type: "produce", prompt: "cough (noun)", accepted: ["la tosse"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-033", type: "recognize", prompt: "avere la tosse", accepted: ["to have a cough"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-034", type: "produce", prompt: "to have a cough", accepted: ["avere la tosse"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-035", type: "recognize", prompt: "il raffreddore", accepted: ["a cold", "the common cold"], tags: ["health", "illness", "noun"], tier: 1 },
    { id: "a232-t1-036", type: "produce", prompt: "a cold (illness)", accepted: ["il raffreddore"], tags: ["health", "illness", "noun"], tier: 1 },
    { id: "a232-t1-037", type: "recognize", prompt: "essere raffreddato", accepted: ["to have a cold"], tags: ["health", "illness", "verb-phrase"], tier: 1 },
    { id: "a232-t1-038", type: "produce", prompt: "to have a cold", accepted: ["essere raffreddato", "essere raffreddata"], tags: ["health", "illness", "verb-phrase"], tier: 1 },
    { id: "a232-t1-039", type: "recognize", prompt: "sentirsi male", accepted: ["to feel sick", "to feel unwell"], tags: ["health", "symptom", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-040", type: "produce", prompt: "to feel sick", accepted: ["sentirsi male"], tags: ["health", "symptom", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-041", type: "recognize", prompt: "sentirsi meglio", accepted: ["to feel better"], tags: ["health", "recovery", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-042", type: "produce", prompt: "to feel better", accepted: ["sentirsi meglio"], tags: ["health", "recovery", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-043", type: "recognize", prompt: "la pressione", accepted: ["blood pressure"], tags: ["health", "checkup", "noun"], tier: 1 },
    { id: "a232-t1-044", type: "produce", prompt: "blood pressure", accepted: ["la pressione"], tags: ["health", "checkup", "noun"], tier: 1 },
    { id: "a232-t1-045", type: "recognize", prompt: "misurare la pressione", accepted: ["to take someone's blood pressure", "to measure blood pressure"], tags: ["health", "checkup", "verb-phrase"], tier: 1 },
    { id: "a232-t1-046", type: "produce", prompt: "to take someone's blood pressure", accepted: ["misurare la pressione"], tags: ["health", "checkup", "verb-phrase"], tier: 1 },
    { id: "a232-t1-047", type: "recognize", prompt: "il sangue", accepted: ["blood"], tags: ["health", "body", "noun"], tier: 1 },
    { id: "a232-t1-048", type: "produce", prompt: "blood", accepted: ["il sangue"], tags: ["health", "body", "noun"], tier: 1 },
    { id: "a232-t1-049", type: "recognize", prompt: "fare un'analisi del sangue", accepted: ["to have a blood test", "to do a blood test"], tags: ["health", "checkup", "verb-phrase"], tier: 1 },
    { id: "a232-t1-050", type: "produce", prompt: "to have a blood test", accepted: ["fare un'analisi del sangue"], tags: ["health", "checkup", "verb-phrase"], tier: 1 },
    { id: "a232-t1-051", type: "recognize", prompt: "la visita medica", accepted: ["medical checkup", "doctor's visit"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-052", type: "produce", prompt: "medical checkup", accepted: ["la visita medica"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-053", type: "recognize", prompt: "il medico di base", accepted: ["primary care doctor", "family doctor"], tags: ["health", "profession", "noun-phrase"], tier: 1 },
    { id: "a232-t1-054", type: "produce", prompt: "primary care doctor", accepted: ["il medico di base"], tags: ["health", "profession", "noun-phrase"], tier: 1 },
    { id: "a232-t1-055", type: "recognize", prompt: "lo specialista", accepted: ["specialist"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-056", type: "produce", prompt: "specialist (doctor)", accepted: ["lo specialista"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-057", type: "recognize", prompt: "il pediatra", accepted: ["pediatrician"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-058", type: "produce", prompt: "pediatrician", accepted: ["il pediatra"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-059", type: "recognize", prompt: "il dentista", accepted: ["dentist"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-060", type: "produce", prompt: "dentist", accepted: ["il dentista", "la dentista"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-061", type: "recognize", prompt: "l'infermiere", accepted: ["nurse"], hint: "feminine form: l'infermiera", tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-062", type: "produce", prompt: "nurse", accepted: ["l'infermiere", "l'infermiera"], tags: ["health", "profession", "noun"], tier: 1 },
    { id: "a232-t1-063", type: "recognize", prompt: "lo studio medico", accepted: ["doctor's office"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-064", type: "produce", prompt: "doctor's office", accepted: ["lo studio medico"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-065", type: "recognize", prompt: "la sala d'aspetto", accepted: ["waiting room"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-066", type: "produce", prompt: "waiting room", accepted: ["la sala d'aspetto"], tags: ["health", "doctor", "noun-phrase"], tier: 1 },
    { id: "a232-t1-067", type: "recognize", prompt: "il cerotto", accepted: ["band-aid", "adhesive bandage"], tags: ["health", "first-aid", "noun"], tier: 1 },
    { id: "a232-t1-068", type: "produce", prompt: "band-aid", accepted: ["il cerotto"], tags: ["health", "first-aid", "noun"], tier: 1 },
    { id: "a232-t1-069", type: "recognize", prompt: "la fasciatura", accepted: ["bandage"], tags: ["health", "first-aid", "noun"], tier: 1 },
    { id: "a232-t1-070", type: "produce", prompt: "bandage", accepted: ["la fasciatura"], tags: ["health", "first-aid", "noun"], tier: 1 },
    { id: "a232-t1-071", type: "recognize", prompt: "l'iniezione", accepted: ["injection", "shot"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-072", type: "produce", prompt: "injection", accepted: ["l'iniezione"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-073", type: "recognize", prompt: "il vaccino", accepted: ["vaccine"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-074", type: "produce", prompt: "vaccine", accepted: ["il vaccino"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-075", type: "recognize", prompt: "vaccinarsi", accepted: ["to get vaccinated"], tags: ["health", "treatment", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-076", type: "produce", prompt: "to get vaccinated", accepted: ["vaccinarsi"], tags: ["health", "treatment", "reflexive-verb"], tier: 1 },
    { id: "a232-t1-077", type: "recognize", prompt: "essere in cura", accepted: ["to be under treatment", "to be undergoing treatment"], tags: ["health", "treatment", "verb-phrase"], tier: 1 },
    { id: "a232-t1-078", type: "produce", prompt: "to be under treatment", accepted: ["essere in cura"], tags: ["health", "treatment", "verb-phrase"], tier: 1 },
    { id: "a232-t1-079", type: "recognize", prompt: "la cura", accepted: ["treatment", "cure"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-080", type: "produce", prompt: "treatment", accepted: ["la cura"], tags: ["health", "treatment", "noun"], tier: 1 },
    { id: "a232-t1-081", type: "recognize", prompt: "guarire", accepted: ["to recover", "to heal", "to get well"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-082", type: "produce", prompt: "to recover (from an illness)", accepted: ["guarire"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-083", type: "recognize", prompt: "peggiorare", accepted: ["to get worse", "to worsen"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-084", type: "produce", prompt: "to get worse", accepted: ["peggiorare"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-085", type: "recognize", prompt: "migliorare", accepted: ["to improve", "to get better"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-086", type: "produce", prompt: "to improve", accepted: ["migliorare"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-087", type: "recognize", prompt: "la malattia", accepted: ["illness", "sickness"], tags: ["health", "illness", "noun"], tier: 1 },
    { id: "a232-t1-088", type: "produce", prompt: "illness", accepted: ["la malattia"], tags: ["health", "illness", "noun"], tier: 1 },
    { id: "a232-t1-089", type: "recognize", prompt: "il sintomo", accepted: ["symptom"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-090", type: "produce", prompt: "symptom", accepted: ["il sintomo"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-091", type: "recognize", prompt: "il dolore", accepted: ["pain"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-092", type: "produce", prompt: "pain", accepted: ["il dolore"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-093", type: "recognize", prompt: "doloroso", accepted: ["painful"], tags: ["health", "symptom", "adjective"], tier: 1 },
    { id: "a232-t1-094", type: "produce", prompt: "painful", accepted: ["doloroso", "dolorosa"], tags: ["health", "symptom", "adjective"], tier: 1 },
    { id: "a232-t1-095", type: "recognize", prompt: "il termometro", accepted: ["thermometer"], tags: ["health", "equipment", "noun"], tier: 1 },
    { id: "a232-t1-096", type: "produce", prompt: "thermometer", accepted: ["il termometro"], tags: ["health", "equipment", "noun"], tier: 1 },
    { id: "a232-t1-097", type: "recognize", prompt: "la pastiglia", accepted: ["pill"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-098", type: "produce", prompt: "pill", accepted: ["la pastiglia", "la compressa"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-099", type: "recognize", prompt: "lo sciroppo", accepted: ["syrup", "cough syrup"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-100", type: "produce", prompt: "cough syrup", accepted: ["lo sciroppo"], tags: ["health", "medication", "noun"], tier: 1 },
    { id: "a232-t1-101", type: "recognize", prompt: "l'allergia", accepted: ["allergy"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-102", type: "produce", prompt: "allergy", accepted: ["l'allergia"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-103", type: "recognize", prompt: "essere allergico a", accepted: ["to be allergic to"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-104", type: "produce", prompt: "to be allergic to", accepted: ["essere allergico a", "essere allergica a"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-105", type: "recognize", prompt: "la diagnosi", accepted: ["diagnosis"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-106", type: "produce", prompt: "diagnosis", accepted: ["la diagnosi"], tags: ["health", "doctor", "noun"], tier: 1 },
    { id: "a232-t1-107", type: "recognize", prompt: "contagioso", accepted: ["contagious"], tags: ["health", "illness", "adjective"], tier: 1 },
    { id: "a232-t1-108", type: "produce", prompt: "contagious", accepted: ["contagioso", "contagiosa"], tags: ["health", "illness", "adjective"], tier: 1 },
    { id: "a232-t1-109", type: "recognize", prompt: "avere le vertigini", accepted: ["to feel dizzy", "to have dizzy spells"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-110", type: "produce", prompt: "to feel dizzy", accepted: ["avere le vertigini"], tags: ["health", "symptom", "verb-phrase"], tier: 1 },
    { id: "a232-t1-111", type: "recognize", prompt: "la nausea", accepted: ["nausea"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-112", type: "produce", prompt: "nausea", accepted: ["la nausea"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-113", type: "recognize", prompt: "vomitare", accepted: ["to vomit", "to throw up"], tags: ["health", "symptom", "verb"], tier: 1 },
    { id: "a232-t1-114", type: "produce", prompt: "to vomit", accepted: ["vomitare"], tags: ["health", "symptom", "verb"], tier: 1 },
    { id: "a232-t1-115", type: "recognize", prompt: "starnutire", accepted: ["to sneeze"], tags: ["health", "symptom", "verb"], tier: 1 },
    { id: "a232-t1-116", type: "produce", prompt: "to sneeze", accepted: ["starnutire"], tags: ["health", "symptom", "verb"], tier: 1 },
    { id: "a232-t1-117", type: "recognize", prompt: "lo starnuto", accepted: ["sneeze"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-118", type: "produce", prompt: "sneeze (noun)", accepted: ["lo starnuto"], tags: ["health", "symptom", "noun"], tier: 1 },
    { id: "a232-t1-119", type: "recognize", prompt: "gonfio", accepted: ["swollen"], tags: ["health", "symptom", "adjective"], tier: 1 },
    { id: "a232-t1-120", type: "produce", prompt: "swollen", accepted: ["gonfio", "gonfia"], tags: ["health", "symptom", "adjective"], tier: 1 },
    { id: "a232-t1-121", type: "recognize", prompt: "la ferita", accepted: ["wound", "injury"], tags: ["health", "injury", "noun"], tier: 1 },
    { id: "a232-t1-122", type: "produce", prompt: "wound", accepted: ["la ferita"], tags: ["health", "injury", "noun"], tier: 1 },
    { id: "a232-t1-123", type: "recognize", prompt: "riposare", accepted: ["to rest"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-124", type: "produce", prompt: "to rest", accepted: ["riposare"], tags: ["health", "recovery", "verb"], tier: 1 },
    { id: "a232-t1-125", type: "recognize", prompt: "il riposo", accepted: ["rest"], tags: ["health", "recovery", "noun"], tier: 1 },
    { id: "a232-t1-126", type: "produce", prompt: "rest (noun)", accepted: ["il riposo"], tags: ["health", "recovery", "noun"], tier: 1 },
    { id: "a232-t1-127", type: "recognize", prompt: "essere ricoverato", accepted: ["to be hospitalized", "to be admitted to hospital"], hint: "feminine form: essere ricoverata", tags: ["health", "hospital", "verb-phrase"], tier: 1 },
    { id: "a232-t1-128", type: "produce", prompt: "to be hospitalized", accepted: ["essere ricoverato", "essere ricoverata"], tags: ["health", "hospital", "verb-phrase"], tier: 1 },
    { id: "a232-t1-129", type: "recognize", prompt: "prendere una medicina", accepted: ["to take a medicine", "to take medication"], tags: ["health", "medication", "verb-phrase"], tier: 1 },
    { id: "a232-t1-130", type: "produce", prompt: "to take a medicine", accepted: ["prendere una medicina"], tags: ["health", "medication", "verb-phrase"], tier: 1 },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    { id: "a232-t2-001", type: "fill_blank", prompt: "Da stamattina mi ___ male la testa e non riesco a concentrarmi.", accepted: ["fa"], hint: "'mi fa male' + singular body part (la testa) — third person singular of fare", tags: ["fill_blank", "symptom", "mi-fa-male"], tier: 2 },
    { id: "a232-t2-002", type: "fill_blank", prompt: "Mi ___ male le gambe dopo la partita di calcio di ieri.", accepted: ["fanno"], hint: "a plural body part (le gambe) takes 'fanno', not 'fa'", tags: ["fill_blank", "symptom", "mi-fa-male"], tier: 2 },
    { id: "a232-t2-003", type: "fill_blank", prompt: "Signora Bruni, ___ riposare a letto per almeno tre giorni.", accepted: ["deve"], hint: "dovere + infinitive gives formal medical advice (Lei form)", tags: ["fill_blank", "dovere", "advice"], tier: 2 },
    { id: "a232-t2-004", type: "fill_blank", prompt: "Deve prendere questa pastiglia due volte ___ giorno, dopo i pasti.", accepted: ["al"], hint: "'al giorno' — per day, using the preposition + article contraction", tags: ["fill_blank", "preposition", "medication"], tier: 2 },
    { id: "a232-t2-005", type: "fill_blank", prompt: "Non deve ___ vino o birra insieme a questo antibiotico.", accepted: ["bere"], hint: "dovere + infinitive — negative advice uses the same construction", tags: ["fill_blank", "dovere", "advice"], tier: 2 },
    { id: "a232-t2-006", type: "fill_blank", prompt: "Ha la febbre ___ trentotto gradi e mezzo da questa mattina.", accepted: ["a"], hint: "'avere la febbre a' + temperature — fixed preposition for stating degrees", tags: ["fill_blank", "preposition", "symptom"], tier: 2 },
    { id: "a232-t2-007", type: "fill_blank", prompt: "Il dottore mi ha detto di stare a letto ___ almeno due giorni.", accepted: ["per"], hint: "'per' + duration expresses how long the rest should last", tags: ["fill_blank", "preposition", "advice"], tier: 2 },
    { id: "a232-t2-008", type: "fill_blank", prompt: "Deve prendere l'antibiotico ___ un bicchiere d'acqua pieno, non a stomaco vuoto.", accepted: ["con"], hint: "'con' introduces what accompanies the medication", tags: ["fill_blank", "preposition", "medication"], tier: 2 },
    { id: "a232-t2-009", type: "fill_blank", prompt: "Mia figlia ___ mal di pancia da ieri sera e non ha voglia di mangiare.", accepted: ["ha"], hint: "'avere' + mal di + body part — third person singular", tags: ["fill_blank", "avere", "symptom"], tier: 2 },
    { id: "a232-t2-010", type: "fill_blank", prompt: "Se i sintomi ___, dovete chiamare subito il pronto soccorso.", accepted: ["peggiorano"], hint: "peggiorare conjugated in the present, third person plural", tags: ["fill_blank", "verb-conjugation", "peggiorare"], tier: 2 },
    { id: "a232-t2-011", type: "fill_blank", prompt: "Il medico mi ha prescritto uno sciroppo ___ la tosse che non passa da una settimana.", accepted: ["per"], hint: "'per' introduces the purpose or target of the medication", tags: ["fill_blank", "preposition", "medication"], tier: 2 },
    { id: "a232-t2-012", type: "fill_blank", prompt: "Dopo l'intervento, il paziente ___ ricoverato in ospedale per una settimana.", accepted: ["è stato"], hint: "essere ricoverato in the passato prossimo — 'è stato ricoverato'", tags: ["fill_blank", "passato-prossimo", "hospital"], tier: 2 },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    { id: "a232-t3-001", type: "produce", prompt: "What are your symptoms?", accepted: ["Quali sono i suoi sintomi?", "Che sintomi ha?"], hint: "formal 'Lei' address — a common opening question at a visit", tags: ["chunk", "doctor-patient", "formal"], tier: 3 },
    { id: "a232-t3-002", type: "produce", prompt: "I don't feel well.", accepted: ["Non mi sento bene.", "Mi sento male."], hint: "sentirsi + adverb/adjective — reflexive verb", tags: ["chunk", "symptom", "reflexive-verb"], tier: 3 },
    { id: "a232-t3-003", type: "produce", prompt: "Take two pills a day, after meals.", accepted: ["Prenda due pastiglie al giorno, dopo i pasti.", "Prenda due compresse al giorno, dopo i pasti."], hint: "formal imperative 'Prenda' (Lei) — how doctors give instructions", tags: ["chunk", "advice", "imperative"], tier: 3 },
    { id: "a232-t3-004", type: "produce", prompt: "I've had a fever since yesterday.", accepted: ["Ho la febbre da ieri.", "Ho la febbre sin da ieri."], hint: "'da' + time expression marks how long a condition has lasted", tags: ["chunk", "symptom", "time-expression"], tier: 3 },
    { id: "a232-t3-005", type: "produce", prompt: "You need to rest for a few days.", accepted: ["Deve riposare per qualche giorno.", "Ha bisogno di riposare per qualche giorno."], hint: "dovere + infinitive, or avere bisogno di + infinitive", tags: ["chunk", "advice", "dovere"], tier: 3 },
    { id: "a232-t3-006", type: "produce", prompt: "Is it contagious?", accepted: ["È contagioso?", "È contagiosa?"], hint: "the adjective agrees with the noun it refers to (il raffreddore vs la malattia)", tags: ["chunk", "illness", "adjective-agreement"], tier: 3 },
    { id: "a232-t3-007", type: "produce", prompt: "I'm allergic to penicillin.", accepted: ["Sono allergico alla penicillina.", "Sono allergica alla penicillina."], hint: "essere allergico/a a + definite article — masculine/feminine agreement", tags: ["chunk", "allergy", "adjective-agreement"], tier: 3 },
    { id: "a232-t3-008", type: "produce", prompt: "Where does it hurt?", accepted: ["Dove le fa male?", "Dove sente dolore?"], hint: "formal indirect object 'le' (to you, Lei) with fare male", tags: ["chunk", "doctor-patient", "formal"], tier: 3 },
    { id: "a232-t3-009", type: "produce", prompt: "The doctor gave me a prescription for antibiotics.", accepted: ["Il medico mi ha dato una ricetta per gli antibiotici.", "Il dottore mi ha fatto una ricetta per gli antibiotici."], hint: "passato prossimo — dare/fare + ricetta", tags: ["chunk", "doctor-patient", "passato-prossimo"], tier: 3 },
    { id: "a232-t3-010", type: "produce", prompt: "Call an ambulance, quickly!", accepted: ["Chiami un'ambulanza, presto!", "Chiamate un'ambulanza, subito!"], hint: "formal imperative 'Chiami' (Lei) or plural 'Chiamate' (voi) in an emergency", tags: ["chunk", "emergency", "imperative"], tier: 3 },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    { id: "a232-t4-001", type: "passage_cloze", prompt: "Da tre giorni Chiara si sente male: le fa male la testa, ha la tosse e stanotte ha misurato trentotto gradi di febbre.\nSuo marito le ha detto di chiamare il medico di base invece di aspettare.\nLa dottoressa ha ascoltato i sintomi al telefono e ha detto che probabilmente è solo un ___ stagionale.\nHa consigliato riposo, molti liquidi e una pastiglia per abbassare la febbre.\nDopo cinque giorni a letto, Chiara si sente finalmente meglio.", accepted: ["raffreddore"], hint: "the mild, common seasonal illness the doctor suspects, not a serious diagnosis", tags: ["passage_cloze", "illness", "symptom"], tier: 4, prerequisites: ["a232-t1-035", "a232-t1-019", "a232-t1-023", "a232-t1-031"] },
    { id: "a232-t4-002", type: "passage_cloze", prompt: "Ieri pomeriggio il piccolo Tommaso è caduto dalla bicicletta davanti a casa nostra.\nSi è fatto una ferita profonda al ginocchio e piangeva forte dal dolore.\nMia sorella lo ha portato subito al ___ dell'ospedale più vicino.\nL'infermiera ha pulito la ferita e il medico ha messo alcuni punti.\nOra Tommaso porta una fasciatura per una settimana, ma sta già meglio.", accepted: ["pronto soccorso"], hint: "where you go for an urgent injury like this, not a scheduled appointment", tags: ["passage_cloze", "emergency", "injury"], tier: 4, prerequisites: ["a232-t1-005", "a232-t1-121", "a232-t1-061", "a232-t1-069"] },
    { id: "a232-t4-003", type: "passage_cloze", prompt: "Dopo la visita medica, il dottore mi ha scritto una ricetta per un antibiotico e uno sciroppo per la tosse.\nSono uscito dallo studio medico e sono andato subito in ___ qui vicino a casa.\nIl farmacista ha controllato la ricetta e mi ha spiegato come prendere le pastiglie.\nMi ha detto di prenderle sempre dopo i pasti, con un bicchiere d'acqua pieno.\nIn pochi giorni il mal di gola è quasi sparito.", accepted: ["farmacia"], hint: "the shop where a pharmacist fills a prescription", tags: ["passage_cloze", "medication", "doctor"], tier: 4, prerequisites: ["a232-t1-015", "a232-t1-011", "a232-t1-017", "a232-t1-099"] },
    { id: "a232-t4-004", type: "passage_cloze", prompt: "Marco è stato ricoverato in ospedale per una polmonite grave, ed è rimasto in cura per due settimane.\nAll'inizio i medici erano preoccupati perché la sua situazione peggiorava ogni giorno.\nPoi, grazie agli antibiotici e a molto riposo, le sue condizioni hanno cominciato a migliorare.\nSua moglie andava a trovarlo ogni pomeriggio e gli portava sempre qualcosa di buono da mangiare.\nDopo un mese difficile, Marco è riuscito finalmente a ___ del tutto.", accepted: ["guarire"], hint: "to recover completely — the opposite of peggiorare", tags: ["passage_cloze", "recovery", "hospital"], tier: 4, prerequisites: ["a232-t1-081", "a232-t1-127", "a232-t1-079", "a232-t1-083", "a232-t1-085"] },
  ],
};
export default unit;
