import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-14-daily-routine",
  name: "Daily Routine",
  level: "A2",
  theme: "Daily Routine & Reflexives",
  emoji: "🪥",
  prerequisiteUnits: ["a2-unit-13-shopping"],
  cards: [
    // ─── Tier 1 – Vocab ───────────────────────────────────────────────────────
    {
      id: "u14-t1-001",
      type: "produce",
      prompt: "the alarm clock",
      accepted: ["la sveglia"],
      hint: "feminine noun",
      tags: ["vocab", "morning", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-002",
      type: "produce",
      prompt: "the bathroom",
      accepted: ["il bagno"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "rooms"],
      tier: 1,
    },
    {
      id: "u14-t1-003",
      type: "produce",
      prompt: "the shower",
      accepted: ["la doccia"],
      hint: "feminine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-004",
      type: "produce",
      prompt: "the toothpaste",
      accepted: ["il dentifricio"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-005",
      type: "produce",
      prompt: "the mirror",
      accepted: ["lo specchio"],
      hint: "masculine noun; uses 'lo'",
      tags: ["vocab", "morning", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-006",
      type: "produce",
      prompt: "the toothbrush",
      accepted: ["lo spazzolino", "lo spazzolino da denti"],
      hint: "masculine noun; uses 'lo'",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-007",
      type: "produce",
      prompt: "the morning",
      accepted: ["la mattina", "il mattino"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-008",
      type: "produce",
      prompt: "the evening",
      accepted: ["la sera"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-009",
      type: "produce",
      prompt: "the night",
      accepted: ["la notte"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-010",
      type: "produce",
      prompt: "the comb",
      accepted: ["il pettine"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },

    // ─── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u14-t2-001",
      type: "conjugate",
      prompt: "alzarsi – io",
      accepted: ["mi alzo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-002",
      type: "conjugate",
      prompt: "alzarsi – tu",
      accepted: ["ti alzi"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-003",
      type: "conjugate",
      prompt: "alzarsi – lui/lei",
      accepted: ["si alza"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-004",
      type: "conjugate",
      prompt: "alzarsi – noi",
      accepted: ["ci alziamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-005",
      type: "conjugate",
      prompt: "alzarsi – voi",
      accepted: ["vi alzate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-006",
      type: "conjugate",
      prompt: "alzarsi – loro",
      accepted: ["si alzano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-007",
      type: "conjugate",
      prompt: "lavarsi – io",
      accepted: ["mi lavo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-008",
      type: "conjugate",
      prompt: "lavarsi – tu",
      accepted: ["ti lavi"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-009",
      type: "conjugate",
      prompt: "lavarsi – lui/lei",
      accepted: ["si lava"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-010",
      type: "conjugate",
      prompt: "svegliarsi – io",
      accepted: ["mi sveglio"],
      hint: "reflexive: mi + verb stem; drop -arsi",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-011",
      type: "conjugate",
      prompt: "vestirsi – io",
      accepted: ["mi vesto"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-012",
      type: "conjugate",
      prompt: "addormentarsi – lui/lei",
      accepted: ["si addormenta"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-013",
      type: "conjugate",
      prompt: "pettinarsi – io",
      accepted: ["mi pettino"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-014",
      type: "conjugate",
      prompt: "mettersi – io",
      accepted: ["mi metto"],
      hint: "reflexive irregular: mettere → metto",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-015",
      type: "conjugate",
      prompt: "stare + gerundio – io (mangiare)",
      accepted: ["sto mangiando"],
      hint: "stare (io) + gerundio of mangiare",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },
    {
      id: "u14-t2-016",
      type: "conjugate",
      prompt: "stare + gerundio – lui/lei (dormire)",
      accepted: ["sta dormendo"],
      hint: "stare (lui/lei) + gerundio of dormire",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },

    // ─── Tier 3 – Chunks ──────────────────────────────────────────────────────
    {
      id: "u14-t3-001",
      type: "produce",
      prompt: "I wake up at seven o'clock.",
      accepted: ["Mi sveglio alle sette.", "Mi sveglio alle sette"],
      hint: "reflexive verb + time expression",
      tags: ["chunk", "routine", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-002",
      type: "produce",
      prompt: "I get up at seven.",
      accepted: ["Mi alzo alle sette.", "Mi alzo alle sette"],
      hint: "alzarsi io form + alle + time",
      tags: ["chunk", "routine", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-003",
      type: "produce",
      prompt: "What are you doing?",
      accepted: ["Cosa stai facendo?", "Cosa stai facendo"],
      hint: "stare + gerundio of fare",
      tags: ["chunk", "stare+gerundio", "question"],
      tier: 3,
    },
    {
      id: "u14-t3-004",
      type: "produce",
      prompt: "I am studying Italian.",
      accepted: ["Sto studiando l'italiano.", "Sto studiando l'italiano"],
      hint: "stare io + gerundio of studiare",
      tags: ["chunk", "stare+gerundio"],
      tier: 3,
    },
    {
      id: "u14-t3-005",
      type: "produce",
      prompt: "She takes a shower every morning.",
      accepted: [
        "Si fa la doccia ogni mattina.",
        "Si fa la doccia ogni mattino.",
        "Lei si fa la doccia ogni mattina.",
      ],
      hint: "farsi la doccia – reflexive chunk",
      tags: ["chunk", "routine", "reflexive"],
      tier: 3,
    },
    {
      id: "u14-t3-006",
      type: "produce",
      prompt: "He gets dressed before breakfast.",
      accepted: [
        "Si veste prima di colazione.",
        "Lui si veste prima di colazione.",
      ],
      hint: "vestirsi lui + prima di colazione",
      tags: ["chunk", "routine", "reflexive"],
      tier: 3,
    },

    // ─── Tier 4 – Production & Passages ───────────────────────────────────────
    {
      id: "u14-t4-001",
      type: "produce",
      prompt: "Every night I brush my teeth and go to sleep.",
      accepted: [
        "Ogni sera mi lavo i denti e mi addormento.",
        "Ogni notte mi lavo i denti e mi addormento.",
      ],
      hint: "lavarsi i denti + addormentarsi",
      tags: ["sentence", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-009", "u14-t2-007", "u14-t2-012"],
    },
    {
      id: "u14-t4-002",
      type: "fill_blank",
      prompt: "La mattina Marco ___ alle sei e poi va in bagno.",
      accepted: ["si sveglia"],
      hint: "svegliarsi lui/lei form",
      tags: ["fill-blank", "reflexive", "routine"],
      tier: 4,
      prerequisites: ["u14-t1-007", "u14-t1-002", "u14-t2-010"],
    },
    {
      id: "u14-t4-003",
      type: "fill_blank",
      prompt: "Sto ___ la doccia adesso — ti chiamo dopo.",
      accepted: ["facendo"],
      hint: "stare + gerundio of fare",
      tags: ["fill-blank", "stare+gerundio"],
      tier: 4,
      prerequisites: ["u14-t1-003", "u14-t2-015"],
    },
    {
      id: "u14-t4-004",
      type: "passage_cloze",
      prompt:
        "Ogni mattina mi sveglio alle sette.\nPrima vado in bagno e mi lavo la faccia.\nPoi mi guardo nello specchio e mi ___.\nDopo colazione mi vesto e esco di casa.",
      accepted: ["pettino"],
      hint: "pettinarsi – io form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-007", "u14-t1-002", "u14-t1-005", "u14-t2-013"],
    },
    {
      id: "u14-t4-005",
      type: "passage_cloze",
      prompt:
        "Luisa ha una routine molto precisa.\nLa sera fa la doccia e usa il dentifricio.\nSi mette il pigiama e legge un libro.\nPoi spegne la luce e ___ lentamente.",
      accepted: ["si addormenta"],
      hint: "addormentarsi – lei form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-003", "u14-t1-004", "u14-t1-008", "u14-t2-012"],
    },

    // ── Tier 1 – Vocabulary (expansion) ─────────────────────────────────────
    {
      id: "u14-t1-011",
      type: "recognize",
      prompt: "la colazione",
      accepted: ["breakfast"],
      hint: "meal",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-012",
      type: "produce",
      prompt: "breakfast",
      accepted: ["la colazione"],
      hint: "feminine noun",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-013",
      type: "recognize",
      prompt: "il pranzo",
      accepted: ["lunch"],
      hint: "meal",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-014",
      type: "produce",
      prompt: "lunch",
      accepted: ["il pranzo"],
      hint: "masculine noun",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-015",
      type: "recognize",
      prompt: "la cena",
      accepted: ["dinner"],
      hint: "meal",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-016",
      type: "produce",
      prompt: "dinner",
      accepted: ["la cena"],
      hint: "feminine noun",
      tags: ["vocab", "meals", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-017",
      type: "recognize",
      prompt: "il pomeriggio",
      accepted: ["the afternoon"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-018",
      type: "produce",
      prompt: "the afternoon",
      accepted: ["il pomeriggio"],
      hint: "masculine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-019",
      type: "recognize",
      prompt: "mezzogiorno",
      accepted: ["noon", "midday"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-020",
      type: "produce",
      prompt: "noon",
      accepted: ["mezzogiorno"],
      hint: "no article: a mezzogiorno",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-021",
      type: "recognize",
      prompt: "mezzanotte",
      accepted: ["midnight"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-022",
      type: "produce",
      prompt: "midnight",
      accepted: ["mezzanotte", "la mezzanotte"],
      hint: "feminine; a mezzanotte",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-023",
      type: "recognize",
      prompt: "l'alba",
      accepted: ["dawn"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-024",
      type: "produce",
      prompt: "dawn",
      accepted: ["l'alba", "alba"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-025",
      type: "recognize",
      prompt: "il tramonto",
      accepted: ["sunset"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-026",
      type: "produce",
      prompt: "sunset",
      accepted: ["il tramonto"],
      hint: "masculine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-027",
      type: "recognize",
      prompt: "il fine settimana",
      accepted: ["the weekend"],
      hint: "time",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-028",
      type: "produce",
      prompt: "the weekend",
      accepted: ["il fine settimana", "il weekend"],
      hint: "masculine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-029",
      type: "recognize",
      prompt: "la settimana",
      accepted: ["the week"],
      hint: "time",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-030",
      type: "produce",
      prompt: "the week",
      accepted: ["la settimana"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-031",
      type: "recognize",
      prompt: "il sapone",
      accepted: ["the soap"],
      hint: "hygiene object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-032",
      type: "produce",
      prompt: "the soap",
      accepted: ["il sapone"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-033",
      type: "recognize",
      prompt: "lo shampoo",
      accepted: ["the shampoo"],
      hint: "hygiene object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-034",
      type: "produce",
      prompt: "the shampoo",
      accepted: ["lo shampoo"],
      hint: "masculine noun; uses 'lo'",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-035",
      type: "recognize",
      prompt: "l'asciugamano",
      accepted: ["the towel"],
      hint: "hygiene object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-036",
      type: "produce",
      prompt: "the towel",
      accepted: ["l'asciugamano", "asciugamano"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-037",
      type: "recognize",
      prompt: "il rasoio",
      accepted: ["the razor"],
      hint: "hygiene object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-038",
      type: "produce",
      prompt: "the razor",
      accepted: ["il rasoio"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-039",
      type: "recognize",
      prompt: "il trucco",
      accepted: ["the makeup"],
      hint: "hygiene/beauty object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-040",
      type: "produce",
      prompt: "the makeup",
      accepted: ["il trucco"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-041",
      type: "recognize",
      prompt: "la crema",
      accepted: ["the cream", "the lotion"],
      hint: "hygiene object",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-042",
      type: "produce",
      prompt: "the lotion",
      accepted: ["la crema"],
      hint: "feminine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-043",
      type: "recognize",
      prompt: "il pigiama",
      accepted: ["the pajamas"],
      hint: "clothing",
      tags: ["vocab", "night", "clothing"],
      tier: 1,
    },
    {
      id: "u14-t1-044",
      type: "produce",
      prompt: "the pajamas",
      accepted: ["il pigiama"],
      hint: "masculine noun, singular in Italian",
      tags: ["vocab", "night", "clothing"],
      tier: 1,
    },
    {
      id: "u14-t1-045",
      type: "recognize",
      prompt: "il letto",
      accepted: ["the bed"],
      hint: "furniture",
      tags: ["vocab", "night", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-046",
      type: "produce",
      prompt: "the bed",
      accepted: ["il letto"],
      hint: "masculine noun",
      tags: ["vocab", "night", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-047",
      type: "recognize",
      prompt: "l'armadio",
      accepted: ["the wardrobe", "the closet"],
      hint: "furniture",
      tags: ["vocab", "night", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-048",
      type: "produce",
      prompt: "the wardrobe",
      accepted: ["l'armadio", "armadio"],
      hint: "masculine noun",
      tags: ["vocab", "night", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-049",
      type: "recognize",
      prompt: "presto",
      accepted: ["early"],
      hint: "adverb",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-050",
      type: "produce",
      prompt: "early",
      accepted: ["presto"],
      hint: "adverb, invariable",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-051",
      type: "recognize",
      prompt: "tardi",
      accepted: ["late"],
      hint: "adverb",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-052",
      type: "produce",
      prompt: "late",
      accepted: ["tardi"],
      hint: "adverb, invariable",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-053",
      type: "recognize",
      prompt: "subito",
      accepted: ["right away", "immediately"],
      hint: "adverb",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-054",
      type: "produce",
      prompt: "right away",
      accepted: ["subito"],
      hint: "adverb, invariable",
      tags: ["vocab", "time", "adverb"],
      tier: 1,
    },
    {
      id: "u14-t1-055",
      type: "recognize",
      prompt: "la routine",
      accepted: ["the routine"],
      hint: "loanword, invariable",
      tags: ["vocab", "routine"],
      tier: 1,
    },
    {
      id: "u14-t1-056",
      type: "produce",
      prompt: "the routine",
      accepted: ["la routine"],
      hint: "feminine, invariable loanword",
      tags: ["vocab", "routine"],
      tier: 1,
    },
    {
      id: "u14-t1-057",
      type: "recognize",
      prompt: "il risveglio",
      accepted: ["the waking up", "the wake-up"],
      hint: "noun form of svegliarsi",
      tags: ["vocab", "morning"],
      tier: 1,
    },
    {
      id: "u14-t1-058",
      type: "produce",
      prompt: "the waking up",
      accepted: ["il risveglio"],
      hint: "masculine noun",
      tags: ["vocab", "morning"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (expansion) ────────────────────────────────────────
    {
      id: "u14-t2-017",
      type: "conjugate",
      prompt: "svegliarsi – tu",
      accepted: ["ti svegli"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-018",
      type: "conjugate",
      prompt: "svegliarsi – lui/lei",
      accepted: ["si sveglia"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-019",
      type: "conjugate",
      prompt: "svegliarsi – noi",
      accepted: ["ci svegliamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-020",
      type: "conjugate",
      prompt: "svegliarsi – voi",
      accepted: ["vi svegliate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-021",
      type: "conjugate",
      prompt: "svegliarsi – loro",
      accepted: ["si svegliano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-022",
      type: "conjugate",
      prompt: "vestirsi – tu",
      accepted: ["ti vesti"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-023",
      type: "conjugate",
      prompt: "vestirsi – lui/lei",
      accepted: ["si veste"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-024",
      type: "conjugate",
      prompt: "vestirsi – noi",
      accepted: ["ci vestiamo"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-025",
      type: "conjugate",
      prompt: "vestirsi – voi",
      accepted: ["vi vestite"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-026",
      type: "conjugate",
      prompt: "vestirsi – loro",
      accepted: ["si vestono"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-027",
      type: "conjugate",
      prompt: "addormentarsi – io",
      accepted: ["mi addormento"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-028",
      type: "conjugate",
      prompt: "addormentarsi – tu",
      accepted: ["ti addormenti"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-029",
      type: "conjugate",
      prompt: "addormentarsi – noi",
      accepted: ["ci addormentiamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-030",
      type: "conjugate",
      prompt: "addormentarsi – voi",
      accepted: ["vi addormentate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-031",
      type: "conjugate",
      prompt: "addormentarsi – loro",
      accepted: ["si addormentano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-032",
      type: "conjugate",
      prompt: "pettinarsi – tu",
      accepted: ["ti pettini"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-033",
      type: "conjugate",
      prompt: "pettinarsi – lui/lei",
      accepted: ["si pettina"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-034",
      type: "conjugate",
      prompt: "pettinarsi – noi",
      accepted: ["ci pettiniamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-035",
      type: "conjugate",
      prompt: "pettinarsi – voi",
      accepted: ["vi pettinate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-036",
      type: "conjugate",
      prompt: "pettinarsi – loro",
      accepted: ["si pettinano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-037",
      type: "conjugate",
      prompt: "mettersi – tu",
      accepted: ["ti metti"],
      hint: "reflexive irregular: mettere → metti",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-038",
      type: "conjugate",
      prompt: "mettersi – lui/lei",
      accepted: ["si mette"],
      hint: "reflexive irregular: mettere → mette",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-039",
      type: "conjugate",
      prompt: "mettersi – noi",
      accepted: ["ci mettiamo"],
      hint: "reflexive irregular: mettere → mettiamo",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-040",
      type: "conjugate",
      prompt: "mettersi – voi",
      accepted: ["vi mettete"],
      hint: "reflexive irregular: mettere → mettete",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-041",
      type: "conjugate",
      prompt: "mettersi – loro",
      accepted: ["si mettono"],
      hint: "reflexive irregular: mettere → mettono",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-042",
      type: "conjugate",
      prompt: "truccarsi – io",
      accepted: ["mi trucco"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-043",
      type: "conjugate",
      prompt: "truccarsi – tu",
      accepted: ["ti trucchi"],
      hint: "reflexive; -care adds 'h' before -i",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-044",
      type: "conjugate",
      prompt: "truccarsi – lui/lei",
      accepted: ["si trucca"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-045",
      type: "conjugate",
      prompt: "truccarsi – noi",
      accepted: ["ci trucchiamo"],
      hint: "reflexive; -care adds 'h' before -iamo",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-046",
      type: "conjugate",
      prompt: "truccarsi – voi",
      accepted: ["vi truccate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-047",
      type: "conjugate",
      prompt: "truccarsi – loro",
      accepted: ["si truccano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "truccarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-048",
      type: "conjugate",
      prompt: "asciugarsi – io",
      accepted: ["mi asciugo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-049",
      type: "conjugate",
      prompt: "asciugarsi – tu",
      accepted: ["ti asciughi"],
      hint: "reflexive; -gare adds 'h' before -i",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-050",
      type: "conjugate",
      prompt: "asciugarsi – lui/lei",
      accepted: ["si asciuga"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-051",
      type: "conjugate",
      prompt: "asciugarsi – noi",
      accepted: ["ci asciughiamo"],
      hint: "reflexive; -gare adds 'h' before -iamo",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-052",
      type: "conjugate",
      prompt: "asciugarsi – voi",
      accepted: ["vi asciugate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-053",
      type: "conjugate",
      prompt: "asciugarsi – loro",
      accepted: ["si asciugano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "asciugarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-054",
      type: "conjugate",
      prompt: "prepararsi – io",
      accepted: ["mi preparo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-055",
      type: "conjugate",
      prompt: "prepararsi – tu",
      accepted: ["ti prepari"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-056",
      type: "conjugate",
      prompt: "prepararsi – lui/lei",
      accepted: ["si prepara"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-057",
      type: "conjugate",
      prompt: "prepararsi – noi",
      accepted: ["ci prepariamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-058",
      type: "conjugate",
      prompt: "prepararsi – voi",
      accepted: ["vi preparate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-059",
      type: "conjugate",
      prompt: "prepararsi – loro",
      accepted: ["si preparano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "prepararsi"],
      tier: 2,
    },
    {
      id: "u14-t2-060",
      type: "conjugate",
      prompt: "stare + gerundio – tu (leggere)",
      accepted: ["stai leggendo"],
      hint: "stare (tu) + gerundio of leggere",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },
    {
      id: "u14-t2-061",
      type: "conjugate",
      prompt: "stare + gerundio – noi (lavorare)",
      accepted: ["stiamo lavorando"],
      hint: "stare (noi) + gerundio of lavorare",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },
    {
      id: "u14-t2-062",
      type: "conjugate",
      prompt: "stare + gerundio – loro (giocare)",
      accepted: ["stanno giocando"],
      hint: "stare (loro) + gerundio of giocare",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },

    // ── Tier 3 – Chunks (expansion) ─────────────────────────────────────────
    {
      id: "u14-t3-007",
      type: "produce",
      prompt: "I have breakfast at eight.",
      accepted: ["Faccio colazione alle otto.", "Faccio colazione alle otto"],
      hint: "fare colazione – collocation",
      tags: ["chunk", "collocation", "meals"],
      tier: 3,
    },
    {
      id: "u14-t3-008",
      type: "produce",
      prompt: "We have lunch at noon.",
      accepted: ["Pranziamo a mezzogiorno.", "Pranziamo a mezzogiorno"],
      hint: "pranzare + a mezzogiorno",
      tags: ["chunk", "meals", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-009",
      type: "produce",
      prompt: "They have dinner late.",
      accepted: ["Cenano tardi.", "Cenano tardi"],
      hint: "cenare + tardi",
      tags: ["chunk", "meals", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-010",
      type: "produce",
      prompt: "I don't want to be late for work.",
      accepted: [
        "Non voglio fare tardi al lavoro.",
        "Non voglio fare tardi al lavoro",
      ],
      hint: "fare tardi – collocation",
      tags: ["chunk", "collocation", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-011",
      type: "produce",
      prompt: "I go to bed early on Sundays.",
      accepted: [
        "Vado a letto presto la domenica.",
        "Vado a letto presto la domenica",
      ],
      hint: "andare a letto + presto",
      tags: ["chunk", "collocation", "routine"],
      tier: 3,
    },
    {
      id: "u14-t3-012",
      type: "produce",
      prompt: "My father shaves every morning.",
      accepted: [
        "Mio padre si fa la barba ogni mattina.",
        "Mio padre si fa la barba ogni mattina",
      ],
      hint: "farsi la barba – collocation",
      tags: ["chunk", "collocation", "reflexive"],
      tier: 3,
    },
    {
      id: "u14-t3-013",
      type: "produce",
      prompt: "She puts on makeup before going out.",
      accepted: ["Si trucca prima di uscire.", "Si trucca prima di uscire"],
      hint: "truccarsi lei + prima di uscire",
      tags: ["chunk", "reflexive", "truccarsi"],
      tier: 3,
    },
    {
      id: "u14-t3-014",
      type: "produce",
      prompt: "I dry my hair after the shower.",
      accepted: [
        "Mi asciugo i capelli dopo la doccia.",
        "Mi asciugo i capelli dopo la doccia",
      ],
      hint: "asciugarsi i capelli – collocation",
      tags: ["chunk", "collocation", "asciugarsi"],
      tier: 3,
    },
    {
      id: "u14-t3-015",
      type: "produce",
      prompt: "He washes his hands before eating.",
      accepted: [
        "Si lava le mani prima di mangiare.",
        "Si lava le mani prima di mangiare",
      ],
      hint: "lavarsi le mani – collocation",
      tags: ["chunk", "collocation", "lavarsi"],
      tier: 3,
    },
    {
      id: "u14-t3-016",
      type: "produce",
      prompt: "I put on my pajamas at night.",
      accepted: [
        "Mi metto il pigiama la notte.",
        "Mi metto il pigiama la notte",
      ],
      hint: "mettersi il pigiama – collocation",
      tags: ["chunk", "collocation", "mettersi"],
      tier: 3,
    },
    {
      id: "u14-t3-017",
      type: "produce",
      prompt: "We leave the house at seven thirty.",
      accepted: [
        "Usciamo di casa alle sette e mezza.",
        "Usciamo di casa alle sette e mezza",
      ],
      hint: "uscire di casa – collocation",
      tags: ["chunk", "collocation", "routine"],
      tier: 3,
    },
    {
      id: "u14-t3-018",
      type: "produce",
      prompt: "He comes back home in the afternoon.",
      accepted: [
        "Torna a casa nel pomeriggio.",
        "Torna a casa nel pomeriggio",
      ],
      hint: "tornare a casa + nel pomeriggio",
      tags: ["chunk", "collocation", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-019",
      type: "produce",
      prompt: "I'm always in a hurry in the morning.",
      accepted: ["Ho sempre fretta la mattina.", "Ho sempre fretta la mattina"],
      hint: "avere fretta – collocation",
      tags: ["chunk", "collocation", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-020",
      type: "produce",
      prompt: "On weekends I wake up late.",
      accepted: [
        "Il fine settimana mi sveglio tardi.",
        "Il fine settimana mi sveglio tardi",
      ],
      hint: "il fine settimana + svegliarsi tardi",
      tags: ["chunk", "reflexive", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-021",
      type: "produce",
      prompt: "She gets ready in twenty minutes.",
      accepted: [
        "Si prepara in venti minuti.",
        "Si prepara in venti minuti",
      ],
      hint: "prepararsi lei form",
      tags: ["chunk", "reflexive", "prepararsi"],
      tier: 3,
    },
    {
      id: "u14-t3-022",
      type: "produce",
      prompt: "We sit down at the table for dinner.",
      accepted: [
        "Ci sediamo a tavola per cena.",
        "Ci sediamo a tavola per cena",
      ],
      hint: "sedersi a tavola – collocation",
      tags: ["chunk", "collocation", "meals"],
      tier: 3,
    },
    {
      id: "u14-t3-023",
      type: "produce",
      prompt: "After lunch I rest for half an hour.",
      accepted: [
        "Dopo pranzo mi riposo per mezz'ora.",
        "Dopo pranzo mi riposo per mezz'ora",
      ],
      hint: "riposarsi io form",
      tags: ["chunk", "reflexive", "riposarsi"],
      tier: 3,
    },
    {
      id: "u14-t3-024",
      type: "produce",
      prompt: "He works from dawn to sunset.",
      accepted: [
        "Lavora dall'alba al tramonto.",
        "Lavora dall'alba al tramonto",
      ],
      hint: "dall'alba al tramonto – fixed expression",
      tags: ["chunk", "time", "collocation"],
      tier: 3,
    },
    {
      id: "u14-t3-025",
      type: "produce",
      prompt: "The party ends at midnight.",
      accepted: ["La festa finisce a mezzanotte.", "La festa finisce a mezzanotte"],
      hint: "a mezzanotte – time expression",
      tags: ["chunk", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-026",
      type: "produce",
      prompt: "I prefer to wake up early, not late.",
      accepted: [
        "Preferisco svegliarmi presto, non tardi.",
        "Preferisco svegliarmi presto, non tardi",
      ],
      hint: "svegliarsi as infinitive after preferisco",
      tags: ["chunk", "reflexive", "time"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passages (expansion) ─────────────────────────
    {
      id: "u14-t4-006",
      type: "produce",
      prompt: "In the afternoon I do my homework and then I rest.",
      accepted: [
        "Nel pomeriggio faccio i compiti e poi mi riposo.",
        "Nel pomeriggio faccio i compiti e poi mi riposo",
      ],
      hint: "nel pomeriggio + riposarsi io",
      tags: ["sentence", "routine", "time"],
      tier: 4,
      prerequisites: ["u14-t1-018"],
    },
    {
      id: "u14-t4-007",
      type: "fill_blank",
      prompt: "Dopo la doccia mi ___ i capelli con l'asciugamano.",
      accepted: ["asciugo"],
      hint: "asciugarsi – io form",
      tags: ["fill-blank", "reflexive", "asciugarsi"],
      tier: 4,
      prerequisites: ["u14-t1-036", "u14-t2-048"],
    },
    {
      id: "u14-t4-008",
      type: "fill_blank",
      prompt: "Ogni sera prima di cena, papà si ___ la barba.",
      accepted: ["fa"],
      hint: "farsi la barba – lui form",
      tags: ["fill-blank", "reflexive", "routine"],
      tier: 4,
      prerequisites: ["u14-t1-016"],
    },
    {
      id: "u14-t4-009",
      type: "fill_blank",
      prompt: "Prima di uscire, Marta si ___ davanti allo specchio.",
      accepted: ["trucca"],
      hint: "truccarsi – lei form",
      tags: ["fill-blank", "reflexive", "truccarsi"],
      tier: 4,
      prerequisites: ["u14-t1-005", "u14-t2-044"],
    },
    {
      id: "u14-t4-010",
      type: "produce",
      prompt: "At midnight, he goes to sleep.",
      accepted: ["A mezzanotte, si addormenta.", "A mezzanotte si addormenta."],
      hint: "a mezzanotte + addormentarsi lui",
      tags: ["sentence", "reflexive", "time"],
      tier: 4,
      prerequisites: ["u14-t1-022", "u14-t2-012"],
    },
    {
      id: "u14-t4-011",
      type: "produce",
      prompt: "From dawn to sunset, the shop stays open.",
      accepted: [
        "Dall'alba al tramonto, il negozio resta aperto.",
        "Dall'alba al tramonto il negozio resta aperto.",
      ],
      hint: "dall'alba al tramonto – fixed expression",
      tags: ["sentence", "time"],
      tier: 4,
      prerequisites: ["u14-t1-023", "u14-t1-025"],
    },
    {
      id: "u14-t4-012",
      type: "passage_cloze",
      prompt:
        "Il sabato mattina mi sveglio tardi, verso le nove.\nFaccio colazione con calma e poi mi vesto.\nA mezzogiorno pranzo con la famiglia.\nLa sera ___ presto perché sono stanco.",
      accepted: ["mi addormento"],
      hint: "addormentarsi – io form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-011", "u14-t1-019", "u14-t2-027"],
    },
    {
      id: "u14-t4-013",
      type: "passage_cloze",
      prompt:
        "Durante la settimana la mia routine è diversa.\nMi alzo alle sei e mi preparo velocemente.\nEsco di casa alle sette e mezza.\nTorno a casa nel pomeriggio e mi ___ per un'ora.",
      accepted: ["riposo"],
      hint: "riposarsi – io form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-029", "u14-t1-018", "u14-t2-054"],
    },

    // ── Tier 3 – Chunks (word-in-context coverage) ──────────────────────────
    {
      id: "u14-t3-027",
      type: "produce",
      prompt: "In the shower I use soap and then shampoo for my hair.",
      accepted: [
        "Sotto la doccia uso il sapone e poi lo shampoo per i capelli.",
        "Sotto la doccia uso il sapone e poi lo shampoo per i capelli",
      ],
      hint: "il sapone + lo shampoo – hygiene collocation",
      tags: ["chunk", "collocation", "hygiene"],
      tier: 3,
    },
    {
      id: "u14-t3-028",
      type: "produce",
      prompt: "First I use the razor, then I put on lotion.",
      accepted: [
        "Prima uso il rasoio, poi metto la crema.",
        "Prima uso il rasoio, poi metto la crema",
      ],
      hint: "il rasoio + la crema – morning hygiene",
      tags: ["chunk", "collocation", "hygiene"],
      tier: 3,
    },
    {
      id: "u14-t3-029",
      type: "produce",
      prompt: "I keep the toothbrush and the comb in the bathroom drawer.",
      accepted: [
        "Tengo lo spazzolino e il pettine nel cassetto del bagno.",
        "Tengo lo spazzolino e il pettine nel cassetto del bagno",
      ],
      hint: "lo spazzolino + il pettine – hygiene objects",
      tags: ["chunk", "collocation", "hygiene"],
      tier: 3,
    },
    {
      id: "u14-t3-030",
      type: "produce",
      prompt: "I open the wardrobe and choose my clothes for work.",
      accepted: [
        "Apro l'armadio e scelgo i vestiti per il lavoro.",
        "Apro l'armadio e scelgo i vestiti per il lavoro",
      ],
      hint: "l'armadio – furniture",
      tags: ["chunk", "routine", "objects"],
      tier: 3,
    },
    {
      id: "u14-t3-031",
      type: "produce",
      prompt: "I have to get up right away, or I'll be late for work.",
      accepted: [
        "Devo alzarmi subito, altrimenti farò tardi al lavoro.",
        "Devo alzarmi subito, altrimenti farò tardi al lavoro",
      ],
      hint: "subito – adverb",
      tags: ["chunk", "time", "adverb"],
      tier: 3,
    },
    {
      id: "u14-t3-032",
      type: "produce",
      prompt: "My waking up is always difficult on Monday mornings.",
      accepted: [
        "Il mio risveglio è sempre difficile il lunedì mattina.",
        "Il mio risveglio è sempre difficile il lunedì mattina",
      ],
      hint: "il risveglio – noun form of svegliarsi",
      tags: ["chunk", "morning", "routine"],
      tier: 3,
    },
  ],
};
export default unit;
