import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-28-travel-transportation",
  name: "Travel & Transportation",
  level: "A2",
  theme: "Travel & Transportation",
  emoji: "✈️",
  prerequisiteUnits: ["a2-unit-27-reflexive-verbs-expanded"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a228-t1-001",
      type: "recognize",
      prompt: "il viaggio",
      accepted: ["the trip", "the journey", "trip", "journey"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-002",
      type: "produce",
      prompt: "the trip",
      accepted: ["il viaggio"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-003",
      type: "recognize",
      prompt: "viaggiare",
      accepted: ["to travel"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-004",
      type: "produce",
      prompt: "to travel",
      accepted: ["viaggiare"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-005",
      type: "recognize",
      prompt: "il treno",
      accepted: ["the train", "train"],
      tags: ["transport", "noun", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-006",
      type: "produce",
      prompt: "the train",
      accepted: ["il treno"],
      tags: ["transport", "noun", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-007",
      type: "recognize",
      prompt: "l'aereo",
      accepted: ["the airplane", "the plane", "airplane", "plane"],
      tags: ["transport", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-008",
      type: "produce",
      prompt: "the plane",
      accepted: ["l'aereo"],
      tags: ["transport", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-009",
      type: "recognize",
      prompt: "la nave",
      accepted: ["the ship", "ship"],
      tags: ["transport", "noun", "sea", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-010",
      type: "produce",
      prompt: "the ship",
      accepted: ["la nave"],
      tags: ["transport", "noun", "sea", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-011",
      type: "recognize",
      prompt: "il traghetto",
      accepted: ["the ferry", "ferry"],
      tags: ["transport", "noun", "sea", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-012",
      type: "produce",
      prompt: "the ferry",
      accepted: ["il traghetto"],
      tags: ["transport", "noun", "sea", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-013",
      type: "recognize",
      prompt: "la metropolitana",
      accepted: ["the subway", "the metro", "subway", "metro"],
      hint: "spoken shorthand: 'la metro'",
      tags: ["transport", "noun", "city", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-014",
      type: "produce",
      prompt: "the subway",
      accepted: ["la metropolitana", "la metro"],
      tags: ["transport", "noun", "city", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-015",
      type: "recognize",
      prompt: "il pullman",
      accepted: ["the coach", "the long-distance bus", "coach", "long-distance bus"],
      hint: "long-distance or tour bus, not a city bus",
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-016",
      type: "produce",
      prompt: "the long-distance bus",
      accepted: ["il pullman"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-017",
      type: "recognize",
      prompt: "l'autobus",
      accepted: ["the bus", "bus"],
      hint: "the city bus, unlike 'il pullman'",
      tags: ["transport", "noun", "city", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-018",
      type: "produce",
      prompt: "the (city) bus",
      accepted: ["l'autobus"],
      tags: ["transport", "noun", "city", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-019",
      type: "recognize",
      prompt: "la bicicletta",
      accepted: ["the bicycle", "bicycle", "the bike", "bike"],
      hint: "often shortened to 'la bici'",
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-020",
      type: "produce",
      prompt: "the bicycle",
      accepted: ["la bicicletta", "la bici"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-021",
      type: "recognize",
      prompt: "il taxi",
      accepted: ["the taxi", "taxi", "the cab", "cab"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-022",
      type: "produce",
      prompt: "the taxi",
      accepted: ["il taxi"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-023",
      type: "recognize",
      prompt: "il tassista",
      accepted: ["the taxi driver", "taxi driver"],
      tags: ["transport", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-024",
      type: "produce",
      prompt: "the taxi driver",
      accepted: ["il tassista"],
      tags: ["transport", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-025",
      type: "recognize",
      prompt: "la macchina",
      accepted: ["the car", "car"],
      hint: "also 'l'automobile', but 'la macchina' is far more common in speech",
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-026",
      type: "produce",
      prompt: "the car",
      accepted: ["la macchina", "l'automobile"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-027",
      type: "recognize",
      prompt: "il motorino",
      accepted: ["the scooter", "the moped", "scooter", "moped"],
      hint: "the classic Italian city vehicle",
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-028",
      type: "produce",
      prompt: "the scooter",
      accepted: ["il motorino"],
      tags: ["transport", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-029",
      type: "recognize",
      prompt: "l'aeroporto",
      accepted: ["the airport", "airport"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-030",
      type: "produce",
      prompt: "the airport",
      accepted: ["l'aeroporto"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-031",
      type: "recognize",
      prompt: "il volo",
      accepted: ["the flight", "flight"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-032",
      type: "produce",
      prompt: "the flight",
      accepted: ["il volo"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-033",
      type: "recognize",
      prompt: "atterrare",
      accepted: ["to land"],
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-034",
      type: "produce",
      prompt: "to land",
      accepted: ["atterrare"],
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-035",
      type: "recognize",
      prompt: "l'atterraggio",
      accepted: ["the landing", "landing"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-036",
      type: "produce",
      prompt: "the landing",
      accepted: ["l'atterraggio"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-037",
      type: "recognize",
      prompt: "decollare",
      accepted: ["to take off"],
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-038",
      type: "produce",
      prompt: "to take off",
      accepted: ["decollare"],
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-039",
      type: "recognize",
      prompt: "il decollo",
      accepted: ["the takeoff", "takeoff"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-040",
      type: "produce",
      prompt: "the takeoff",
      accepted: ["il decollo"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-041",
      type: "recognize",
      prompt: "imbarcarsi",
      accepted: ["to board"],
      hint: "reflexive verb — used for boarding a plane or ship",
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-042",
      type: "produce",
      prompt: "to board (a plane or ship)",
      accepted: ["imbarcarsi"],
      tags: ["travel", "verb", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-043",
      type: "recognize",
      prompt: "l'imbarco",
      accepted: ["the boarding", "boarding"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-044",
      type: "produce",
      prompt: "the boarding",
      accepted: ["l'imbarco"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-045",
      type: "recognize",
      prompt: "la carta d'imbarco",
      accepted: ["the boarding pass", "boarding pass"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-046",
      type: "produce",
      prompt: "the boarding pass",
      accepted: ["la carta d'imbarco"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-047",
      type: "recognize",
      prompt: "il terminal",
      accepted: ["the terminal", "terminal"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-048",
      type: "produce",
      prompt: "the terminal",
      accepted: ["il terminal"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-049",
      type: "recognize",
      prompt: "il pilota",
      accepted: ["the pilot", "pilot"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-050",
      type: "produce",
      prompt: "the pilot",
      accepted: ["il pilota"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-051",
      type: "recognize",
      prompt: "l'assistente di volo",
      accepted: ["the flight attendant", "flight attendant"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-052",
      type: "produce",
      prompt: "the flight attendant",
      accepted: ["l'assistente di volo"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-053",
      type: "recognize",
      prompt: "l'equipaggio",
      accepted: ["the crew", "crew"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-054",
      type: "produce",
      prompt: "the crew",
      accepted: ["l'equipaggio"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-055",
      type: "recognize",
      prompt: "la dogana",
      accepted: ["customs", "the customs"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-056",
      type: "produce",
      prompt: "customs",
      accepted: ["la dogana"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-057",
      type: "recognize",
      prompt: "il controllo di sicurezza",
      accepted: ["the security check", "security check", "the security control"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-058",
      type: "produce",
      prompt: "the security check",
      accepted: ["il controllo di sicurezza"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-059",
      type: "recognize",
      prompt: "il bagaglio a mano",
      accepted: ["the carry-on luggage", "carry-on luggage", "hand luggage"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-060",
      type: "produce",
      prompt: "the carry-on luggage",
      accepted: ["il bagaglio a mano"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-061",
      type: "recognize",
      prompt: "la coincidenza",
      accepted: ["the connection", "the connecting flight", "connection"],
      hint: "a connecting flight or train — not a coincidence in the everyday sense",
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-062",
      type: "produce",
      prompt: "the connection (flight or train)",
      accepted: ["la coincidenza"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-063",
      type: "recognize",
      prompt: "fare scalo",
      accepted: ["to make a stopover", "to stop over", "to have a layover"],
      tags: ["travel", "verb phrase", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-064",
      type: "produce",
      prompt: "to make a stopover",
      accepted: ["fare scalo"],
      tags: ["travel", "verb phrase", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-065",
      type: "recognize",
      prompt: "lo scalo",
      accepted: ["the stopover", "the layover", "stopover", "layover"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-066",
      type: "produce",
      prompt: "the stopover",
      accepted: ["lo scalo"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-067",
      type: "recognize",
      prompt: "la stazione",
      accepted: ["the station", "station"],
      tags: ["travel", "noun", "place", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-068",
      type: "produce",
      prompt: "the station",
      accepted: ["la stazione"],
      tags: ["travel", "noun", "place", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-069",
      type: "recognize",
      prompt: "il binario",
      accepted: ["the platform", "the track", "platform", "track"],
      hint: "the numbered platform where a train arrives",
      tags: ["travel", "noun", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-070",
      type: "produce",
      prompt: "the platform / track",
      accepted: ["il binario"],
      tags: ["travel", "noun", "train", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-071",
      type: "recognize",
      prompt: "la sala d'attesa",
      accepted: ["the waiting room", "waiting room"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-072",
      type: "produce",
      prompt: "the waiting room",
      accepted: ["la sala d'attesa"],
      tags: ["travel", "noun", "place", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-073",
      type: "recognize",
      prompt: "il biglietto",
      accepted: ["the ticket", "ticket"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-074",
      type: "produce",
      prompt: "the ticket",
      accepted: ["il biglietto"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-075",
      type: "recognize",
      prompt: "il biglietto di andata e ritorno",
      accepted: ["the round-trip ticket", "round-trip ticket", "the return ticket", "return ticket"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-076",
      type: "produce",
      prompt: "the round-trip ticket",
      accepted: ["il biglietto di andata e ritorno"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-077",
      type: "recognize",
      prompt: "il biglietto di sola andata",
      accepted: ["the one-way ticket", "one-way ticket"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-078",
      type: "produce",
      prompt: "the one-way ticket",
      accepted: ["il biglietto di sola andata"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-079",
      type: "recognize",
      prompt: "prenotare",
      accepted: ["to book", "to reserve"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-080",
      type: "produce",
      prompt: "to book",
      accepted: ["prenotare"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-081",
      type: "recognize",
      prompt: "la prenotazione",
      accepted: ["the booking", "the reservation", "booking", "reservation"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-082",
      type: "produce",
      prompt: "the reservation",
      accepted: ["la prenotazione"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-083",
      type: "recognize",
      prompt: "il passaporto",
      accepted: ["the passport", "passport"],
      tags: ["travel", "noun", "documents", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-084",
      type: "produce",
      prompt: "the passport",
      accepted: ["il passaporto"],
      tags: ["travel", "noun", "documents", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-085",
      type: "recognize",
      prompt: "la valigia",
      accepted: ["the suitcase", "suitcase"],
      hint: "plural: le valigie",
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-086",
      type: "produce",
      prompt: "the suitcase",
      accepted: ["la valigia"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-087",
      type: "recognize",
      prompt: "il bagaglio",
      accepted: ["the luggage", "the baggage", "luggage", "baggage"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-088",
      type: "produce",
      prompt: "the luggage",
      accepted: ["il bagaglio"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-089",
      type: "recognize",
      prompt: "lo zaino",
      accepted: ["the backpack", "backpack"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-090",
      type: "produce",
      prompt: "the backpack",
      accepted: ["lo zaino"],
      tags: ["travel", "noun", "luggage", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-091",
      type: "recognize",
      prompt: "il ritardo",
      accepted: ["the delay", "delay"],
      hint: "'essere in ritardo' — to be delayed / late",
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-092",
      type: "produce",
      prompt: "the delay",
      accepted: ["il ritardo"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-093",
      type: "recognize",
      prompt: "cancellare",
      accepted: ["to cancel"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-094",
      type: "produce",
      prompt: "to cancel",
      accepted: ["cancellare"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-095",
      type: "recognize",
      prompt: "cancellato",
      accepted: ["cancelled", "canceled"],
      hint: "past participle used as an adjective; feminine: cancellata",
      tags: ["travel", "adjective", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-096",
      type: "produce",
      prompt: "cancelled",
      accepted: ["cancellato"],
      tags: ["travel", "adjective", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-097",
      type: "recognize",
      prompt: "il rimborso",
      accepted: ["the refund", "refund"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-098",
      type: "produce",
      prompt: "the refund",
      accepted: ["il rimborso"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-099",
      type: "recognize",
      prompt: "il posto",
      accepted: ["the seat", "seat"],
      hint: "also means 'place' in general",
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-100",
      type: "produce",
      prompt: "the seat",
      accepted: ["il posto"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-101",
      type: "recognize",
      prompt: "il finestrino",
      accepted: ["the window", "window"],
      hint: "a vehicle window — not 'la finestra' (a building window)",
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-102",
      type: "produce",
      prompt: "the (vehicle) window",
      accepted: ["il finestrino"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-103",
      type: "recognize",
      prompt: "noleggiare",
      accepted: ["to rent", "to hire"],
      hint: "used for vehicles — cars, bikes, scooters",
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-104",
      type: "produce",
      prompt: "to rent (a vehicle)",
      accepted: ["noleggiare"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-105",
      type: "recognize",
      prompt: "il noleggio",
      accepted: ["the rental", "rental"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-106",
      type: "produce",
      prompt: "the rental",
      accepted: ["il noleggio"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-107",
      type: "recognize",
      prompt: "l'autista",
      accepted: ["the driver", "driver"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-108",
      type: "produce",
      prompt: "the driver",
      accepted: ["l'autista"],
      tags: ["travel", "noun", "people", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-109",
      type: "recognize",
      prompt: "la fermata",
      accepted: ["the stop", "stop"],
      hint: "a bus or metro stop",
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-110",
      type: "produce",
      prompt: "the stop (bus/metro)",
      accepted: ["la fermata"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-111",
      type: "recognize",
      prompt: "arrivare",
      accepted: ["to arrive"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-112",
      type: "produce",
      prompt: "to arrive",
      accepted: ["arrivare"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-113",
      type: "recognize",
      prompt: "l'arrivo",
      accepted: ["the arrival", "arrival"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-114",
      type: "produce",
      prompt: "the arrival",
      accepted: ["l'arrivo"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-115",
      type: "recognize",
      prompt: "partire",
      accepted: ["to depart", "to leave"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-116",
      type: "produce",
      prompt: "to depart",
      accepted: ["partire"],
      tags: ["travel", "verb", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-117",
      type: "recognize",
      prompt: "la partenza",
      accepted: ["the departure", "departure"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-118",
      type: "produce",
      prompt: "the departure",
      accepted: ["la partenza"],
      tags: ["travel", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-119",
      type: "recognize",
      prompt: "a piedi",
      accepted: ["on foot", "by foot", "walking"],
      tags: ["travel", "phrase", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-120",
      type: "produce",
      prompt: "on foot",
      accepted: ["a piedi"],
      tags: ["travel", "phrase", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-121",
      type: "recognize",
      prompt: "la classe economica",
      accepted: ["economy class", "the economy class"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-122",
      type: "produce",
      prompt: "economy class",
      accepted: ["la classe economica"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-123",
      type: "recognize",
      prompt: "la classe business",
      accepted: ["business class", "the business class"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    {
      id: "a228-t1-124",
      type: "produce",
      prompt: "business class",
      accepted: ["la classe business"],
      tags: ["travel", "noun", "air", "A2"],
      tier: 1,
    },
    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    {
      id: "a228-t2-001",
      type: "fill_blank",
      prompt: "Da Milano a Roma preferisco viaggiare ___ treno — è comodo e non c'è traffico.",
      accepted: ["in"],
      hint: "'in treno' — means of transport takes 'in' with no article",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-005"],
    },
    {
      id: "a228-t2-002",
      type: "fill_blank",
      prompt: "Mio padre ha paura di volare, quindi non va mai ___ aereo.",
      accepted: ["in"],
      hint: "'in aereo' — same pattern as 'in treno'",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-007"],
    },
    {
      id: "a228-t2-003",
      type: "fill_blank",
      prompt: "Con quattro bambini è più facile spostarsi ___ macchina che sui mezzi pubblici.",
      accepted: ["in"],
      hint: "'in macchina' — no article, like the other means of transport",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-025"],
    },
    {
      id: "a228-t2-004",
      type: "fill_blank",
      prompt: "Ogni mattina vado in ufficio ___ autobus perché non ho la macchina.",
      accepted: ["in"],
      hint: "'in autobus' — public transport follows the same 'in + vehicle' pattern",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-017"],
    },
    {
      id: "a228-t2-005",
      type: "fill_blank",
      prompt: "D'estate vado al lavoro ___ bici — fa bene alla salute e risparmio benzina.",
      accepted: ["in"],
      hint: "'in bici' (shortened from bicicletta) — still 'in', no article",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-019"],
    },
    {
      id: "a228-t2-006",
      type: "fill_blank",
      prompt: "L'albergo è vicinissimo alla stazione: dal binario ci si arriva ___ piedi in cinque minuti.",
      accepted: ["a"],
      hint: "'a piedi' — on foot is the one exception; it takes 'a', not 'in'",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-119"],
    },
    {
      id: "a228-t2-007",
      type: "fill_blank",
      prompt: "A Milano molte persone si spostano ___ metropolitana perché è più veloce del traffico in superficie.",
      accepted: ["in"],
      hint: "'in metropolitana' — same rule as the other vehicles",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-013"],
    },
    {
      id: "a228-t2-008",
      type: "fill_blank",
      prompt: "Dopo la festa era troppo tardi per l'autobus, così siamo tornati a casa ___ taxi.",
      accepted: ["in"],
      hint: "'in taxi' — again 'in' with no article",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-021"],
    },
    {
      id: "a228-t2-009",
      type: "fill_blank",
      prompt: "Per andare in Sardegna abbiamo viaggiato ___ traghetto da Civitavecchia.",
      accepted: ["in"],
      hint: "'in traghetto' — ships and ferries follow the same pattern",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-011"],
    },
    {
      id: "a228-t2-010",
      type: "fill_blank",
      prompt: "Il viaggio in treno costava troppo, così abbiamo prenotato ___ pullman.",
      accepted: ["in"],
      hint: "'in pullman' — the long-distance coach follows the same rule",
      tags: ["fill_blank", "preposition", "transport", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-015"],
    },
    {
      id: "a228-t2-011",
      type: "fill_blank",
      prompt: "Domani sera parto ___ Berlino: ho già fatto il check-in online.",
      accepted: ["per"],
      hint: "'partire per + destinazione' — use 'per' before the destination with 'partire'",
      tags: ["fill_blank", "preposition", "travel", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-115"],
    },
    {
      id: "a228-t2-012",
      type: "fill_blank",
      prompt: "Il volo arriva ___ Napoli con venti minuti di ritardo.",
      accepted: ["a"],
      hint: "'arrivare a + città' — use 'a' before a city with 'arrivare'",
      tags: ["fill_blank", "preposition", "travel", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-111", "a228-t1-091"],
    },
    {
      id: "a228-t2-013",
      type: "fill_blank",
      prompt: "Siamo tornati ___ Lisbona ieri sera, stanchissimi ma felici del viaggio.",
      accepted: ["da"],
      hint: "'tornare da + città' — use 'da' (from) before the place you are returning from",
      tags: ["fill_blank", "preposition", "travel", "A2"],
      tier: 2,
      prerequisites: ["a228-t1-001"],
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a228-t3-001",
      type: "produce",
      prompt: "The flight to Lisbon has been cancelled.",
      accepted: [
        "Il volo per Lisbona è stato cancellato.",
        "Il volo per Lisbona è stato annullato.",
      ],
      hint: "'essere cancellato/annullato' — passato prossimo with 'essere' for the passive-sounding result",
      tags: ["chunk", "air", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-031", "a228-t1-095"],
    },
    {
      id: "a228-t3-002",
      type: "produce",
      prompt: "We missed the connection in Frankfurt.",
      accepted: [
        "Abbiamo perso la coincidenza a Francoforte.",
        "Abbiamo perso la coincidenza a Francoforte per un ritardo.",
      ],
      hint: "'perdere la coincidenza' — the fixed phrase for missing a connecting flight or train",
      tags: ["chunk", "air", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-061"],
    },
    {
      id: "a228-t3-003",
      type: "produce",
      prompt: "We had a three-hour layover in Madrid.",
      accepted: [
        "Abbiamo fatto scalo a Madrid per tre ore.",
        "Abbiamo avuto uno scalo di tre ore a Madrid.",
      ],
      hint: "'fare scalo' (verb) or 'uno scalo di... ore' (noun)",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-063", "a228-t1-065"],
    },
    {
      id: "a228-t3-004",
      type: "produce",
      prompt: "I need to check in two hours before departure.",
      accepted: [
        "Devo fare il check-in due ore prima della partenza.",
        "Devo fare il check-in due ore prima della partenza dell'aereo.",
      ],
      hint: "'fare il check-in' — the fixed phrase, same as in English",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-117"],
    },
    {
      id: "a228-t3-005",
      type: "produce",
      prompt: "My suitcase didn't arrive with the flight.",
      accepted: [
        "La mia valigia non è arrivata con il volo.",
        "La mia valigia non è arrivata con quel volo.",
      ],
      hint: "'arrivare' takes 'essere' in the passato prossimo; feminine agreement: arrivata",
      tags: ["chunk", "luggage", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-085", "a228-t1-031"],
    },
    {
      id: "a228-t3-006",
      type: "produce",
      prompt: "We rented a car at the airport.",
      accepted: [
        "Abbiamo noleggiato una macchina all'aeroporto.",
        "Abbiamo noleggiato un'auto all'aeroporto.",
      ],
      hint: "'noleggiare' + vehicle; passato prossimo with 'avere'",
      tags: ["chunk", "transport", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-103", "a228-t1-029"],
    },
    {
      id: "a228-t3-007",
      type: "produce",
      prompt: "The train is twenty minutes late.",
      accepted: [
        "Il treno è in ritardo di venti minuti.",
        "Il treno ha venti minuti di ritardo.",
      ],
      hint: "'essere in ritardo di + tempo' or 'avere + tempo + di ritardo'",
      tags: ["chunk", "train", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-005", "a228-t1-091"],
    },
    {
      id: "a228-t3-008",
      type: "produce",
      prompt: "Do you have anything to declare?",
      accepted: [
        "Ha qualcosa da dichiarare?",
        "Avete qualcosa da dichiarare?",
      ],
      hint: "the standard question asked at customs ('la dogana')",
      tags: ["chunk", "customs", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-055"],
    },
    {
      id: "a228-t3-009",
      type: "produce",
      prompt: "He forgot his passport at home.",
      accepted: [
        "Ha dimenticato il passaporto a casa.",
        "Si è dimenticato il passaporto a casa.",
      ],
      hint: "'dimenticare' or reflexive 'dimenticarsi' + object; passato prossimo",
      tags: ["chunk", "documents", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-083"],
    },
    {
      id: "a228-t3-010",
      type: "produce",
      prompt: "The gate closes in ten minutes — we have to run.",
      accepted: [
        "Il gate chiude tra dieci minuti — dobbiamo correre.",
        "L'imbarco chiude tra dieci minuti — dobbiamo correre.",
      ],
      hint: "'il gate' is a common loanword at Italian airports, alongside 'l'imbarco'",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-043"],
    },
    {
      id: "a228-t3-011",
      type: "produce",
      prompt: "I sold my bicycle and bought a scooter to get around the city faster.",
      accepted: [
        "Ho venduto la bicicletta e ho comprato un motorino per spostarmi più velocemente in città.",
      ],
      hint: "'la bicicletta' and 'il motorino' — two common city vehicles; passato prossimo with avere",
      tags: ["chunk", "transport", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-019", "a228-t1-027"],
    },
    {
      id: "a228-t3-012",
      type: "produce",
      prompt: "The plane is about to take off; the pilot has announced that the takeoff will be five minutes late.",
      accepted: [
        "L'aereo sta per decollare; il pilota ha annunciato che il decollo avrà cinque minuti di ritardo.",
      ],
      hint: "'stare per + infinito' keeps 'decollare' in its infinitive form; 'il decollo' is the related noun",
      tags: ["chunk", "air", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-037", "a228-t1-039"],
    },
    {
      id: "a228-t3-013",
      type: "produce",
      prompt: "The flight is due to land in Rome in twenty minutes.",
      accepted: ["Il volo deve atterrare a Roma tra venti minuti."],
      hint: "'dovere + infinito' keeps 'atterrare' in its literal infinitive form",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-033"],
    },
    {
      id: "a228-t3-014",
      type: "produce",
      prompt: "The train should arrive at six, but the arrival has been delayed because of a technical problem.",
      accepted: [
        "Il treno dovrebbe arrivare alle sei, ma l'arrivo è stato ritardato per un problema tecnico.",
      ],
      hint: "'dovrebbe arrivare' (conditional + infinito) keeps 'arrivare' intact; 'l'arrivo' is the noun form",
      tags: ["chunk", "train", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-111", "a228-t1-113"],
    },
    {
      id: "a228-t3-015",
      type: "produce",
      prompt: "We decided to leave on foot because there was no bus at that hour.",
      accepted: ["Abbiamo deciso di partire a piedi perché non c'era l'autobus a quell'ora."],
      hint: "'decidere di + infinito' keeps 'partire' literal; 'a piedi' — on foot",
      tags: ["chunk", "travel", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-115", "a228-t1-119"],
    },
    {
      id: "a228-t3-016",
      type: "produce",
      prompt: "Before we could board, the crew checked everyone's boarding pass at the gate.",
      accepted: [
        "Prima di imbarcarsi, l'equipaggio ha controllato la carta d'imbarco di tutti al gate.",
      ],
      hint: "'prima di + infinito' keeps 'imbarcarsi' in its reflexive infinitive form",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-041", "a228-t1-045", "a228-t1-053"],
    },
    {
      id: "a228-t3-017",
      type: "produce",
      prompt: "We wanted a direct flight, but our flight has to make a stopover in Munich.",
      accepted: ["Volevamo un volo diretto, ma il nostro volo deve fare scalo a Monaco."],
      hint: "'dovere + infinito' keeps 'fare scalo' in its literal infinitive form",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-063"],
    },
    {
      id: "a228-t3-018",
      type: "produce",
      prompt: "You can bring only the carry-on luggage — all the rest of the luggage has to go in the hold.",
      accepted: [
        "Puoi portare solo il bagaglio a mano — tutto il resto del bagaglio va messo in stiva.",
      ],
      hint: "'il bagaglio a mano' (carry-on) contains 'il bagaglio' (luggage in general)",
      tags: ["chunk", "luggage", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-059", "a228-t1-087"],
    },
    {
      id: "a228-t3-019",
      type: "produce",
      prompt: "We waited two hours in the waiting room, and then they announced the train's delay.",
      accepted: [
        "Abbiamo aspettato due ore nella sala d'attesa e poi hanno annunciato il ritardo del treno.",
      ],
      hint: "'la sala d'attesa' — the waiting room; passato prossimo throughout",
      tags: ["chunk", "train", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-071"],
    },
    {
      id: "a228-t3-020",
      type: "produce",
      prompt: "I bought the round-trip ticket; the one-way ticket cost almost the same.",
      accepted: [
        "Ho comprato il biglietto di andata e ritorno; il biglietto di sola andata costava quasi lo stesso.",
      ],
      hint: "'il biglietto di andata e ritorno' vs 'il biglietto di sola andata' — round-trip vs one-way",
      tags: ["chunk", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-075", "a228-t1-077"],
    },
    {
      id: "a228-t3-021",
      type: "produce",
      prompt: "I tried to book online, but the booking didn't go through.",
      accepted: ["Ho provato a prenotare online, ma la prenotazione non è andata a buon fine."],
      hint: "'provare a + infinito' keeps 'prenotare' literal; 'la prenotazione' is the noun",
      tags: ["chunk", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-079", "a228-t1-081"],
    },
    {
      id: "a228-t3-022",
      type: "produce",
      prompt: "The airline had to cancel the flight and offered us a full refund.",
      accepted: ["La compagnia aerea ha dovuto cancellare il volo e ci ha offerto il rimborso completo."],
      hint: "'dovere + infinito' keeps 'cancellare' literal; 'il rimborso' is the noun",
      tags: ["chunk", "air", "delay", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-093", "a228-t1-097"],
    },
    {
      id: "a228-t3-023",
      type: "produce",
      prompt: "Excuse me, can I change seats? I'd prefer one near the window.",
      accepted: ["Scusi, posso cambiare il posto? Preferirei uno vicino al finestrino."],
      hint: "'il posto' — seat; here 'posso' (modal) + infinito",
      tags: ["chunk", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-099"],
    },
    {
      id: "a228-t3-024",
      type: "produce",
      prompt: "We decided to rent a car for the whole trip instead of taking the train every day.",
      accepted: [
        "Abbiamo deciso di noleggiare una macchina per tutto il viaggio invece di prendere il treno ogni giorno.",
      ],
      hint: "'decidere di + infinito' keeps 'noleggiare' in its literal infinitive form",
      tags: ["chunk", "transport", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-103"],
    },
    {
      id: "a228-t3-025",
      type: "produce",
      prompt: "The driver was waiting for us outside the airport with a sign that had our name on it.",
      accepted: ["L'autista ci aspettava fuori dall'aeroporto con un cartello con il nostro nome."],
      hint: "'l'autista' — the driver; imperfetto for an ongoing background action",
      tags: ["chunk", "transport", "people", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-107"],
    },
    {
      id: "a228-t3-026",
      type: "produce",
      prompt: "Economy class was full, so we paid extra to sit in business class.",
      accepted: ["La classe economica era piena, così abbiamo pagato in più per la classe business."],
      hint: "'la classe economica' vs 'la classe business' — the two cabin classes",
      tags: ["chunk", "air", "A2"],
      tier: 3,
      prerequisites: ["a228-t1-121", "a228-t1-123"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a228-t4-001",
      type: "passage_cloze",
      prompt: "Ieri dovevo prendere il treno delle sette per Bologna, ma mi sono svegliato tardi.\nSono corso alla stazione senza fare colazione, con la valigia ancora aperta in mano.\nAl binario ho scoperto che il treno era già partito da due minuti.\nHo dovuto comprare un altro biglietto e aspettare in ___ per un'ora, guardando i binari vuoti.\nQuando finalmente sono salito sul treno successivo, ero troppo stanco per leggere il libro che avevo portato.",
      accepted: ["stazione"],
      hint: "the place with platforms where he waited an hour for the next train",
      tags: ["passage_cloze", "train", "A2"],
      tier: 4,
      prerequisites: ["a228-t1-005", "a228-t1-069", "a228-t1-085", "a228-t1-067"],
    },
    {
      id: "a228-t4-002",
      type: "passage_cloze",
      prompt: "All'aeroporto abbiamo fatto il check-in due ore prima della partenza, come sempre.\nDopo il controllo di sicurezza abbiamo aspettato al gate, ma un cartello ha annunciato un ritardo di novanta minuti.\nQuando finalmente abbiamo potuto salire, l'assistente di volo ci ha detto di mettere lo zaino sotto il sedile.\nDurante il volo il pilota ha annunciato che l'___ sarebbe stato più veloce del previsto grazie al vento favorevole.\nSiamo arrivati con solo trenta minuti di ritardo, invece dei novanta temuti.",
      accepted: ["atterraggio"],
      hint: "the moment the plane touches down — the pilot said it would happen faster than expected",
      tags: ["passage_cloze", "air", "delay", "A2"],
      tier: 4,
      prerequisites: ["a228-t1-029", "a228-t1-057", "a228-t1-091", "a228-t1-051", "a228-t1-089", "a228-t1-049"],
    },
    {
      id: "a228-t4-003",
      type: "passage_cloze",
      prompt: "Per andare in Sardegna quest'anno abbiamo scelto la nave invece dell'aereo.\nAbbiamo prenotato una cabina con finestrino per vedere il mare durante la notte.\nAl porto la fila per l'imbarco era lunghissima, e i miei figli non vedevano l'ora di salire a bordo.\nDurante il ___ di otto ore abbiamo giocato a carte e mangiato un panino sul ponte superiore.\nSiamo arrivati a Olbia all'alba, con il sole che si alzava sull'acqua.",
      accepted: ["viaggio"],
      hint: "the eight-hour crossing itself, not the ship — 'the trip/journey' lasted eight hours",
      tags: ["passage_cloze", "sea", "A2"],
      tier: 4,
      prerequisites: ["a228-t1-001", "a228-t1-011", "a228-t1-009", "a228-t1-101", "a228-t1-043"],
    },
    {
      id: "a228-t4-004",
      type: "passage_cloze",
      prompt: "Arrivati all'aeroporto di Catania, abbiamo noleggiato una macchina per girare la Sicilia in libertà.\nAlla dogana non c'era niente da dichiarare, così siamo usciti in pochi minuti.\nIl tassista fuori dal terminal ci ha indicato l'ufficio del noleggio, proprio accanto alla fermata dell'autobus.\nAbbiamo firmato i documenti e ritirato le chiavi, ma l'ufficio del ___ non ci ha spiegato bene l'assicurazione.\nAbbiamo dovuto richiamare più tardi per capire cosa era davvero incluso nel prezzo.",
      accepted: ["noleggio"],
      hint: "the rental office — 'l'ufficio del noleggio' didn't explain the insurance clearly",
      tags: ["passage_cloze", "transport", "A2"],
      tier: 4,
      prerequisites: ["a228-t1-103", "a228-t1-105", "a228-t1-055", "a228-t1-023", "a228-t1-047", "a228-t1-109"],
    },
  ],
};
export default unit;
