import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-38-time-expressions",
  name: "Time Expressions — Past & Future",
  level: "A2",
  theme: "Time Expressions — Past & Future",
  emoji: "🕰️",
  prerequisiteUnits: ["a2-unit-37-money-banking"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "a238-t1-001", type: "recognize", prompt: "l'anno scorso", accepted: ["last year"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-002", type: "produce", prompt: "last year", accepted: ["l'anno scorso"], hint: "a completed past year → passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-003", type: "recognize", prompt: "il mese scorso", accepted: ["last month"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-004", type: "produce", prompt: "last month", accepted: ["il mese scorso"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-005", type: "recognize", prompt: "la settimana scorsa", accepted: ["last week"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-006", type: "produce", prompt: "last week", accepted: ["la settimana scorsa"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-007", type: "recognize", prompt: "due giorni fa", accepted: ["two days ago"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-008", type: "produce", prompt: "two days ago", accepted: ["due giorni fa"], hint: "'fa' = ago, counts back from today → passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-009", type: "recognize", prompt: "due settimane fa", accepted: ["two weeks ago"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-010", type: "produce", prompt: "two weeks ago", accepted: ["due settimane fa"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-011", type: "recognize", prompt: "tempo fa", accepted: ["a while ago"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-012", type: "produce", prompt: "a while ago", accepted: ["tempo fa"], hint: "a vague distance into the past → passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-013", type: "recognize", prompt: "tanto tempo fa", accepted: ["a long time ago"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-014", type: "produce", prompt: "a long time ago", accepted: ["tanto tempo fa"], hint: "further back than 'tempo fa' → passato prossimo, or imperfetto for a lasting state", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-015", type: "recognize", prompt: "una volta", accepted: ["once", "at one time", "in the old days"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-016", type: "produce", prompt: "once, in the old days", accepted: ["una volta"], hint: "opens a past scene or habit → imperfetto", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-017", type: "recognize", prompt: "da bambino/a", accepted: ["as a child"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-018", type: "produce", prompt: "as a child", accepted: ["da bambino", "da bambina"], hint: "describes a childhood habit → imperfetto", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-019", type: "recognize", prompt: "da giovane", accepted: ["in my youth", "as a young person"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-020", type: "produce", prompt: "in my youth", accepted: ["da giovane"], hint: "describes a period of one's life → imperfetto", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-021", type: "recognize", prompt: "ai tempi di", accepted: ["back in the days of", "in the time of"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-022", type: "produce", prompt: "back in the days of", accepted: ["ai tempi di"], hint: "+ noun/person; describes how things used to be → imperfetto", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-023", type: "recognize", prompt: "quand'ero piccolo/a", accepted: ["when I was little", "when I was young"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-024", type: "produce", prompt: "when I was little", accepted: ["quand'ero piccolo", "quand'ero piccola"], hint: "'ero' is already imperfetto of essere", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-025", type: "recognize", prompt: "l'altro ieri", accepted: ["the day before yesterday"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-026", type: "produce", prompt: "the day before yesterday", accepted: ["l'altro ieri"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-027", type: "recognize", prompt: "ieri sera", accepted: ["last night"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-028", type: "produce", prompt: "last night", accepted: ["ieri sera"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-029", type: "recognize", prompt: "l'estate scorsa", accepted: ["last summer"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-030", type: "produce", prompt: "last summer", accepted: ["l'estate scorsa"], hint: "→ passato prossimo, or imperfetto for a repeated summer habit", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-031", type: "recognize", prompt: "di recente", accepted: ["recently"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-032", type: "produce", prompt: "recently", accepted: ["di recente"], hint: "→ passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-033", type: "recognize", prompt: "da allora", accepted: ["since then"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-034", type: "produce", prompt: "since then", accepted: ["da allora"], hint: "marks the start of a state that continues → passato prossimo + presente", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-035", type: "recognize", prompt: "finora", accepted: ["until now", "so far"], tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-036", type: "produce", prompt: "until now, so far", accepted: ["finora"], hint: "often with a negative verb, up to this moment → passato prossimo", tags: ["time-expression", "past"], tier: 1 },
    { id: "a238-t1-037", type: "recognize", prompt: "tra una settimana", accepted: ["in a week"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-038", type: "produce", prompt: "in a week", accepted: ["tra una settimana", "fra una settimana"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-039", type: "recognize", prompt: "fra un'ora", accepted: ["in an hour"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-040", type: "produce", prompt: "in an hour", accepted: ["fra un'ora", "tra un'ora"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-041", type: "recognize", prompt: "dopodomani", accepted: ["the day after tomorrow"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-042", type: "produce", prompt: "the day after tomorrow", accepted: ["dopodomani"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-043", type: "recognize", prompt: "il prossimo anno", accepted: ["next year"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-044", type: "produce", prompt: "next year", accepted: ["il prossimo anno", "l'anno prossimo"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-045", type: "recognize", prompt: "il mese prossimo", accepted: ["next month"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-046", type: "produce", prompt: "next month", accepted: ["il mese prossimo"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-047", type: "recognize", prompt: "la settimana prossima", accepted: ["next week"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-048", type: "produce", prompt: "next week", accepted: ["la settimana prossima"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-049", type: "recognize", prompt: "l'inverno prossimo", accepted: ["next winter"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-050", type: "produce", prompt: "next winter", accepted: ["l'inverno prossimo"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-051", type: "recognize", prompt: "fra poco", accepted: ["shortly", "in a little while"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-052", type: "produce", prompt: "shortly", accepted: ["fra poco", "tra poco"], hint: "imminent future → futuro semplice or present", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-053", type: "recognize", prompt: "presto", accepted: ["soon"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-054", type: "produce", prompt: "soon", accepted: ["presto"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-055", type: "recognize", prompt: "più tardi", accepted: ["later"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-056", type: "produce", prompt: "later", accepted: ["più tardi"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-057", type: "recognize", prompt: "a partire da", accepted: ["starting from"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-058", type: "produce", prompt: "starting from", accepted: ["a partire da"], hint: "+ date/moment, marks a starting point → futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-059", type: "recognize", prompt: "d'ora in poi", accepted: ["from now on"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-060", type: "produce", prompt: "from now on", accepted: ["d'ora in poi"], hint: "marks a new habit beginning now → futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-061", type: "recognize", prompt: "prima o poi", accepted: ["sooner or later"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-062", type: "produce", prompt: "sooner or later", accepted: ["prima o poi"], hint: "unspecified future moment → futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-063", type: "recognize", prompt: "quanto prima", accepted: ["as soon as possible"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-064", type: "produce", prompt: "as soon as possible", accepted: ["quanto prima"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-065", type: "recognize", prompt: "in futuro", accepted: ["in the future"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-066", type: "produce", prompt: "in the future", accepted: ["in futuro"], hint: "→ futuro semplice", tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-067", type: "recognize", prompt: "nel frattempo", accepted: ["in the meantime"], tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-068", type: "produce", prompt: "in the meantime", accepted: ["nel frattempo"], hint: "describes what happens alongside another action → presente or futuro semplice", tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-069", type: "recognize", prompt: "a lungo andare", accepted: ["in the long run"], tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-070", type: "produce", prompt: "in the long run", accepted: ["a lungo andare"], hint: "describes a long-term consequence → futuro semplice or condizionale", tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-071", type: "recognize", prompt: "ormai", accepted: ["by now", "at this point"], tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-072", type: "produce", prompt: "by now, at this point", accepted: ["ormai"], hint: "signals a completed change of state → presente or passato prossimo", tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-073", type: "recognize", prompt: "col tempo", accepted: ["over time", "with time"], tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-074", type: "produce", prompt: "over time", accepted: ["col tempo", "con il tempo"], hint: "describes gradual change → presente or futuro semplice", tags: ["time-expression", "neutral"], tier: 1 },
    { id: "a238-t1-075", type: "recognize", prompt: "da qui in avanti", accepted: ["from here on"], tags: ["time-expression", "future"], tier: 1 },
    { id: "a238-t1-076", type: "produce", prompt: "from here on", accepted: ["da qui in avanti"], hint: "marks a new starting point → futuro semplice", tags: ["time-expression", "future"], tier: 1 },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    { id: "a238-t2-001", type: "fill_blank", prompt: "La settimana scorsa (io) ___ (perdere) le chiavi di casa e non le ho più ritrovate.", accepted: ["ho perso"], hint: "'la settimana scorsa' = a specific past moment → passato prossimo", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-002", type: "fill_blank", prompt: "Da bambina, Sara ___ (avere) sempre paura del buio.", accepted: ["aveva"], hint: "'da bambina' describes a habitual past state → imperfetto", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-003", type: "fill_blank", prompt: "Tra una settimana (noi) ___ (partire) per la Sicilia.", accepted: ["partiremo"], hint: "'tra una settimana' points to the future → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-004", type: "fill_blank", prompt: "Dopodomani Luca ___ (compiere) trent'anni.", accepted: ["compirà"], hint: "'dopodomani' = the day after tomorrow → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-005", type: "fill_blank", prompt: "Ai tempi di mio nonno, in paese non ___ (esserci) l'elettricità.", accepted: ["c'era"], hint: "'ai tempi di' describes how things used to be → imperfetto", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-006", type: "fill_blank", prompt: "Tempo fa (io) ___ (lavorare) in un ristorante del centro.", accepted: ["ho lavorato"], hint: "'tempo fa' = a specific while ago → passato prossimo", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-007", type: "fill_blank", prompt: "Il prossimo anno Giulia ___ (laurearsi) in medicina.", accepted: ["si laureerà"], hint: "'il prossimo anno' → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-008", type: "fill_blank", prompt: "Presto (tu) ___ (capire) perché ti ho detto di no.", accepted: ["capirai"], hint: "'presto' signals the near future → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-009", type: "fill_blank", prompt: "Prima o poi (loro) ci ___ (ringraziare) per questo consiglio.", accepted: ["ringrazieranno"], hint: "'prima o poi' = sooner or later, still unrealized → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-010", type: "fill_blank", prompt: "Finora non ___ (ricevere) nessuna risposta dall'ufficio.", accepted: ["ho ricevuto"], hint: "'finora' + negation of an action up to this moment → passato prossimo", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-011", type: "fill_blank", prompt: "D'ora in poi (io) ___ (controllare) sempre la posta prima di uscire.", accepted: ["controllerò"], hint: "'d'ora in poi' marks a new habit starting now → futuro semplice", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-012", type: "fill_blank", prompt: "Una volta, in questa piazza, ___ (esserci) un mercato ogni sabato.", accepted: ["c'era"], hint: "'una volta' describes a recurring past scene → imperfetto", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },
    { id: "a238-t2-013", type: "fill_blank", prompt: "Fra poco il treno ___ (arrivare) al binario due.", accepted: ["arriverà", "arriva"], hint: "'fra poco' = shortly, an imminent event → futuro semplice (or present for near-certainty)", tags: ["fill_blank", "tense-selection", "time-expression"], tier: 2 },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    { id: "a238-t3-001", type: "produce", prompt: "I'll call you back later.", accepted: ["Ti richiamo più tardi.", "Ti richiamerò più tardi."], hint: "'più tardi' + richiamare", tags: ["chunk", "time-expression", "future"], tier: 3 },
    { id: "a238-t3-002", type: "produce", prompt: "As a child, we used to spend every summer at my grandparents' house.", accepted: ["Da bambini passavamo ogni estate a casa dei nonni.", "Da bambini passavamo ogni estate dai nonni."], hint: "'da bambini' + imperfetto for a repeated habit", tags: ["chunk", "time-expression", "past"], tier: 3 },
    { id: "a238-t3-003", type: "produce", prompt: "Two days ago I lost my wallet on the bus.", accepted: ["Due giorni fa ho perso il portafoglio sull'autobus."], hint: "'due giorni fa' + passato prossimo", tags: ["chunk", "time-expression", "past"], tier: 3 },
    { id: "a238-t3-004", type: "produce", prompt: "Starting next month, I'm going to the gym every morning.", accepted: ["A partire dal mese prossimo vado in palestra ogni mattina.", "Dal mese prossimo vado in palestra ogni mattina."], hint: "'a partire da' + il mese prossimo", tags: ["chunk", "time-expression", "future"], tier: 3 },
    { id: "a238-t3-005", type: "produce", prompt: "Sooner or later you'll have to tell her the truth.", accepted: ["Prima o poi dovrai dirle la verità.", "Prima o poi le dovrai dire la verità."], hint: "'prima o poi' + futuro semplice", tags: ["chunk", "time-expression", "future"], tier: 3 },
    { id: "a238-t3-006", type: "produce", prompt: "Back in my grandmother's day, people wrote letters by hand.", accepted: ["Ai tempi di mia nonna, la gente scriveva le lettere a mano."], hint: "'ai tempi di' + imperfetto", tags: ["chunk", "time-expression", "past"], tier: 3 },
    { id: "a238-t3-007", type: "produce", prompt: "From now on, I'm turning off my phone after dinner.", accepted: ["D'ora in poi spengo il telefono dopo cena.", "D'ora in poi spegnerò il telefono dopo cena."], hint: "'d'ora in poi' + a new habit", tags: ["chunk", "time-expression", "future"], tier: 3 },
    { id: "a238-t3-008", type: "produce", prompt: "In the meantime, let's finish the report.", accepted: ["Nel frattempo finiamo la relazione.", "Nel frattempo finiamo il rapporto."], hint: "'nel frattempo' + imperativo/presente", tags: ["chunk", "time-expression", "neutral"], tier: 3 },
    { id: "a238-t3-009", type: "produce", prompt: "Until now, everything has gone well.", accepted: ["Finora è andato tutto bene.", "Finora tutto è andato bene."], hint: "'finora' + passato prossimo", tags: ["chunk", "time-expression", "past"], tier: 3 },
    { id: "a238-t3-010", type: "produce", prompt: "The day after tomorrow we're moving into the new apartment.", accepted: ["Dopodomani ci trasferiamo nel nuovo appartamento.", "Dopodomani traslochiamo nel nuovo appartamento."], hint: "'dopodomani' + presente per il futuro prossimo", tags: ["chunk", "time-expression", "future"], tier: 3 },
    { id: "a238-t3-011", type: "produce", prompt: "Over time, things change.", accepted: ["Con il tempo le cose cambiano.", "Col tempo le cose cambiano."], hint: "'col tempo' + presente", tags: ["chunk", "time-expression", "neutral"], tier: 3 },
    { id: "a238-t3-012", type: "produce", prompt: "As a young man, my father worked at the port.", accepted: ["Da giovane, mio padre lavorava al porto."], hint: "'da giovane' + imperfetto", tags: ["chunk", "time-expression", "past"], tier: 3 },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    { id: "a238-t4-001", type: "passage_cloze", prompt: "Elena è cresciuta in un paese piccolo vicino a Bologna.\n___, passava le estati in bicicletta con i cugini e tornava a casa solo per cena.\nOggi vive a Milano e lavora in un ufficio del centro.\nIl prossimo anno si trasferirà a Torino per un nuovo lavoro.\nDice che non vede l'ora di ricominciare.", accepted: ["Da bambina"], hint: "the missing phrase introduces a childhood habit, matching the imperfetto verbs that follow", tags: ["passage_cloze", "time-expression", "life-story"], tier: 4, prerequisites: ["a238-t1-017", "a238-t1-018"] },
    { id: "a238-t4-002", type: "passage_cloze", prompt: "Marco ha lasciato il suo paese natale a diciotto anni.\n___ ha deciso di tornare per rivedere la casa dei nonni.\nHa trovato tutto cambiato: negozi nuovi, strade diverse.\nFra qualche giorno ripartirà per Milano, dove lo aspetta il lavoro.\nMa questa volta porta con sé qualche fotografia in più.", accepted: ["Tempo fa"], hint: "the missing phrase marks a vague past moment before the trip, paired with passato prossimo", tags: ["passage_cloze", "time-expression", "life-story"], tier: 4, prerequisites: ["a238-t1-011", "a238-t1-012"] },
    { id: "a238-t4-003", type: "passage_cloze", prompt: "Mia nonna racconta spesso della sua giovinezza in campagna.\n___ mia nonna, le famiglie coltivavano tutto quello che mangiavano.\nOggi il paese è quasi vuoto, e i campi sono abbandonati.\nFra qualche anno vogliamo aprire una piccola fattoria didattica proprio lì.\nSarebbe un modo per non perdere quella memoria.", accepted: ["Ai tempi di"], hint: "the missing phrase + a person's name introduces how things used to be, matching the imperfetto verb", tags: ["passage_cloze", "time-expression", "life-story"], tier: 4, prerequisites: ["a238-t1-021", "a238-t1-022"] },
    { id: "a238-t4-004", type: "passage_cloze", prompt: "Da giovane, Luca fumava due pacchetti di sigarette al giorno.\nDue mesi fa il medico gli ha detto di smettere subito.\n___ ha deciso di non toccare più una sigaretta.\nOgni sera esce a correre invece di accendersi una sigaretta.\nPrima o poi, dice, correrà anche una mezza maratona.", accepted: ["D'ora in poi"], hint: "the missing phrase marks the new habit that begins right after the doctor's warning", tags: ["passage_cloze", "time-expression", "life-story"], tier: 4, prerequisites: ["a238-t1-059", "a238-t1-060"] },
  ],
};
export default unit;
