import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-16-conditional",
  name: "Wishes & Politeness",
  level: "A2",
  theme: "Conditional Tense",
  emoji: "🙏",
  prerequisiteUnits: ["a2-unit-15-future"],
  cards: [
    // Tier 1 — Vocabulary
    {
      id: "u16-t1-001",
      type: "produce",
      prompt: "the wish",
      accepted: ["il desiderio"],
      hint: "What you hope for",
      tags: ["noun", "feelings", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-002",
      type: "produce",
      prompt: "the request",
      accepted: ["la richiesta"],
      hint: "When you ask for something",
      tags: ["noun", "politeness", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-003",
      type: "produce",
      prompt: "the table",
      accepted: ["il tavolo"],
      hint: "Where you sit in a restaurant",
      tags: ["noun", "restaurant", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-004",
      type: "produce",
      prompt: "the reservation",
      accepted: ["la prenotazione"],
      hint: "You make this before arriving",
      tags: ["noun", "restaurant", "hotel", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-005",
      type: "produce",
      prompt: "the room",
      accepted: ["la camera"],
      hint: "In a hotel",
      tags: ["noun", "hotel", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-006",
      type: "produce",
      prompt: "the menu",
      accepted: ["il menù", "il menu"],
      hint: "List of food options",
      tags: ["noun", "restaurant", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-007",
      type: "recognize",
      prompt: "purtroppo",
      accepted: ["unfortunately", "sadly"],
      hint: "Used when giving bad news",
      tags: ["adverb", "politeness", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-008",
      type: "recognize",
      prompt: "volentieri",
      accepted: ["gladly", "willingly", "with pleasure"],
      hint: "Said when happily agreeing",
      tags: ["adverb", "politeness", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-009",
      type: "produce",
      prompt: "the help",
      accepted: ["l'aiuto"],
      hint: "What you give when someone is in difficulty",
      tags: ["noun", "politeness", "conditional"],
      tier: 1,
    },
    {
      id: "u16-t1-010",
      type: "recognize",
      prompt: "se potessi",
      accepted: ["if I could", "if I were able to"],
      hint: "Hypothetical condition in the past subjunctive",
      tags: ["phrase", "hypothetical", "conditional"],
      tier: 1,
    },

    // Tier 2 — Grammar
    {
      id: "u16-t2-001",
      type: "conjugate",
      prompt: "volere – io",
      accepted: ["vorrei"],
      hint: "Irregular condizionale; express 'I would like'",
      tags: ["verb", "volere", "condizionale", "io"],
      tier: 2,
    },
    {
      id: "u16-t2-002",
      type: "conjugate",
      prompt: "volere – tu",
      accepted: ["vorresti"],
      hint: "Irregular condizionale of volere",
      tags: ["verb", "volere", "condizionale", "tu"],
      tier: 2,
    },
    {
      id: "u16-t2-003",
      type: "conjugate",
      prompt: "volere – lui/lei",
      accepted: ["vorrebbe"],
      hint: "Irregular condizionale of volere, third person singular",
      tags: ["verb", "volere", "condizionale", "lui", "lei"],
      tier: 2,
    },
    {
      id: "u16-t2-004",
      type: "conjugate",
      prompt: "potere – io",
      accepted: ["potrei"],
      hint: "Irregular condizionale; 'I could / I would be able to'",
      tags: ["verb", "potere", "condizionale", "io"],
      tier: 2,
    },
    {
      id: "u16-t2-005",
      type: "conjugate",
      prompt: "potere – tu",
      accepted: ["potresti"],
      hint: "Used for polite requests: 'could you…?'",
      tags: ["verb", "potere", "condizionale", "tu"],
      tier: 2,
    },
    {
      id: "u16-t2-006",
      type: "conjugate",
      prompt: "dovere – io",
      accepted: ["dovrei"],
      hint: "Irregular condizionale; 'I should / I ought to'",
      tags: ["verb", "dovere", "condizionale", "io"],
      tier: 2,
    },
    {
      id: "u16-t2-007",
      type: "conjugate",
      prompt: "dovere – tu",
      accepted: ["dovresti"],
      hint: "Giving advice: 'you should…'",
      tags: ["verb", "dovere", "condizionale", "tu"],
      tier: 2,
    },
    {
      id: "u16-t2-008",
      type: "conjugate",
      prompt: "essere – io",
      accepted: ["sarei"],
      hint: "Irregular condizionale of essere",
      tags: ["verb", "essere", "condizionale", "io"],
      tier: 2,
    },

    // Tier 3 — Chunks & Phrases
    {
      id: "u16-t3-001",
      type: "produce",
      prompt: "I would like a table for two.",
      accepted: ["Vorrei un tavolo per due."],
      hint: "Classic restaurant request",
      tags: ["chunk", "restaurant", "condizionale", "vorrei"],
      tier: 3,
    },
    {
      id: "u16-t3-002",
      type: "produce",
      prompt: "Could you help me?",
      accepted: ["Potresti aiutarmi?", "Potrebbe aiutarmi?"],
      hint: "Polite request using condizionale of potere",
      tags: ["chunk", "politeness", "condizionale", "potere"],
      tier: 3,
    },
    {
      id: "u16-t3-003",
      type: "produce",
      prompt: "I would like to visit Rome.",
      accepted: ["Mi piacerebbe visitare Roma.", "Vorrei visitare Roma."],
      hint: "Use mi piacerebbe or vorrei",
      tags: ["chunk", "wishes", "condizionale", "piacere"],
      tier: 3,
    },
    {
      id: "u16-t3-004",
      type: "produce",
      prompt: "You should study more.",
      accepted: ["Dovresti studiare di più.", "Dovresti studiare di piu."],
      hint: "Advice with dovere in condizionale",
      tags: ["chunk", "advice", "condizionale", "dovere"],
      tier: 3,
    },
    {
      id: "u16-t3-005",
      type: "recognize",
      prompt: "Sarei felice di venire.",
      accepted: ["I would be happy to come.", "I would be glad to come."],
      hint: "essere in condizionale",
      tags: ["chunk", "wishes", "condizionale", "essere"],
      tier: 3,
    },
    {
      id: "u16-t3-006",
      type: "produce",
      prompt: "I would like so much to travel.",
      accepted: ["Vorrei tanto viaggiare."],
      hint: "Tanto adds emphasis to the wish",
      tags: ["chunk", "wishes", "condizionale", "vorrei"],
      tier: 3,
    },

    // Tier 4 — Sentences & Passage Cloze
    {
      id: "u16-t4-001",
      type: "produce",
      prompt: "Unfortunately, I would not be able to come to the reservation.",
      accepted: [
        "Purtroppo, non potrei venire alla prenotazione.",
        "Purtroppo non potrei venire alla prenotazione.",
      ],
      hint: "Combine purtroppo with potere in condizionale",
      tags: ["sentence", "condizionale", "potere", "negation"],
      tier: 4,
      prerequisites: ["u16-t1-004", "u16-t1-007", "u16-t2-004"],
    },
    {
      id: "u16-t4-002",
      type: "fill_blank",
      prompt: "Al ristorante, Marco dice al cameriere: '___ un tavolo per due persone, per favore.'",
      accepted: ["Vorrei"],
      hint: "Polite way to say 'I would like' — condizionale of volere, first person",
      tags: ["fill_blank", "restaurant", "condizionale", "vorrei"],
      tier: 4,
      prerequisites: ["u16-t1-003", "u16-t2-001"],
    },
    {
      id: "u16-t4-003",
      type: "fill_blank",
      prompt: "Se potessi scegliere, ___ molto felice di stare in una bella camera d'albergo.",
      accepted: ["sarei"],
      hint: "essere in condizionale, first person singular",
      tags: ["fill_blank", "hotel", "condizionale", "essere"],
      tier: 4,
      prerequisites: ["u16-t1-005", "u16-t1-010", "u16-t2-008"],
    },
    {
      id: "u16-t4-004",
      type: "passage_cloze",
      prompt: "Luca entra in un ristorante elegante e si avvicina al cameriere.\nDice educatamente: 'Buonasera, ___ un tavolo per due persone.'\nIl cameriere sorride e risponde: 'Certamente, signore. Ha una prenotazione?'\nLuca risponde: 'No, purtroppo non ho una prenotazione, ma aspettiamo volentieri.'",
      accepted: ["vorrei"],
      hint: "Polite first-person condizionale of volere",
      tags: ["passage_cloze", "restaurant", "condizionale", "vorrei"],
      tier: 4,
      prerequisites: ["u16-t1-003", "u16-t1-004", "u16-t1-007", "u16-t1-008", "u16-t2-001"],
    },
    {
      id: "u16-t4-005",
      type: "passage_cloze",
      prompt: "Anna telefona a un albergo per fare una prenotazione.\nDice: 'Buongiorno, ___ prenotare una camera per due notti.'\nL'impiegato risponde: 'Certo, che tipo di camera desidera?'\nAnna spiega: 'Mi piacerebbe una camera tranquilla con vista sul mare, se possibile.\nPurtroppo ho un budget limitato, quindi preferirei qualcosa di semplice.'",
      accepted: ["vorrei"],
      hint: "First-person condizionale of volere, expressing a polite request",
      tags: ["passage_cloze", "hotel", "condizionale", "vorrei"],
      tier: 4,
      prerequisites: ["u16-t1-002", "u16-t1-005", "u16-t1-007", "u16-t2-001"],
    },
  ],
};
export default unit;
