import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-11-past-essere",
  name: "The Past (essere)",
  level: "A2",
  theme: "Past Tense with essere",
  emoji: "🚶",
  prerequisiteUnits: ["a2-unit-10-past-avere"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u11-t1-001",
      type: "recognize",
      prompt: "andare",
      accepted: ["to go"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-002",
      type: "recognize",
      prompt: "venire",
      accepted: ["to come"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-003",
      type: "recognize",
      prompt: "uscire",
      accepted: ["to go out", "to leave"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-004",
      type: "recognize",
      prompt: "arrivare",
      accepted: ["to arrive"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-005",
      type: "recognize",
      prompt: "partire",
      accepted: ["to leave", "to depart"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-006",
      type: "recognize",
      prompt: "tornare",
      accepted: ["to return", "to come back"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-007",
      type: "recognize",
      prompt: "rimanere",
      accepted: ["to stay", "to remain"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-008",
      type: "recognize",
      prompt: "nascere",
      accepted: ["to be born"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-009",
      type: "produce",
      prompt: "the station",
      accepted: ["la stazione"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-010",
      type: "produce",
      prompt: "the airport",
      accepted: ["l'aeroporto"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-011",
      type: "produce",
      prompt: "the city centre",
      accepted: ["il centro"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-012",
      type: "produce",
      prompt: "the house",
      accepted: ["la casa"],
      tags: ["noun", "place"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (conjugation) ──────────────────────────────────────
    {
      id: "u11-t2-001",
      type: "conjugate",
      prompt: "andare (passato prossimo) – io (maschile)",
      accepted: ["sono andato"],
      hint: "participio agrees with subject gender",
      tags: ["essere", "passato-prossimo", "conjugation", "andare"],
      tier: 2,
    },
    {
      id: "u11-t2-002",
      type: "conjugate",
      prompt: "andare (passato prossimo) – io (femminile)",
      accepted: ["sono andata"],
      hint: "participio agrees with subject gender",
      tags: ["essere", "passato-prossimo", "conjugation", "andare"],
      tier: 2,
    },
    {
      id: "u11-t2-003",
      type: "conjugate",
      prompt: "venire (passato prossimo) – lui",
      accepted: ["è venuto"],
      tags: ["essere", "passato-prossimo", "conjugation", "venire"],
      tier: 2,
    },
    {
      id: "u11-t2-004",
      type: "conjugate",
      prompt: "venire (passato prossimo) – lei",
      accepted: ["è venuta"],
      tags: ["essere", "passato-prossimo", "conjugation", "venire"],
      tier: 2,
    },
    {
      id: "u11-t2-005",
      type: "conjugate",
      prompt: "arrivare (passato prossimo) – noi",
      accepted: ["siamo arrivati", "siamo arrivate"],
      hint: "noi group: -i (mixed/male) or -e (all female)",
      tags: ["essere", "passato-prossimo", "conjugation", "arrivare"],
      tier: 2,
    },
    {
      id: "u11-t2-006",
      type: "conjugate",
      prompt: "partire (passato prossimo) – loro (maschile/misto)",
      accepted: ["sono partiti"],
      tags: ["essere", "passato-prossimo", "conjugation", "partire"],
      tier: 2,
    },
    {
      id: "u11-t2-007",
      type: "conjugate",
      prompt: "tornare (passato prossimo) – tu (maschile)",
      accepted: ["sei tornato"],
      tags: ["essere", "passato-prossimo", "conjugation", "tornare"],
      tier: 2,
    },
    {
      id: "u11-t2-008",
      type: "conjugate",
      prompt: "rimanere (passato prossimo) – io (femminile)",
      accepted: ["sono rimasta"],
      hint: "rimanere → rimasto/a",
      tags: ["essere", "passato-prossimo", "conjugation", "rimanere"],
      tier: 2,
    },
    {
      id: "u11-t2-009",
      type: "conjugate",
      prompt: "nascere (passato prossimo) – lui",
      accepted: ["è nato"],
      hint: "nascere → nato/a",
      tags: ["essere", "passato-prossimo", "conjugation", "nascere"],
      tier: 2,
    },
    {
      id: "u11-t2-010",
      type: "fill_blank",
      prompt: "Mia nonna ___ morta l'anno scorso. (morire – lei)",
      accepted: ["è morta"],
      hint: "morire → morto/a; uses essere",
      tags: ["essere", "passato-prossimo", "morire", "agreement"],
      tier: 2,
    },

    // ── Tier 3 – Chunks / Short sentences ───────────────────────────────────
    {
      id: "u11-t3-001",
      type: "produce",
      prompt: "I went to Rome. (male speaker)",
      accepted: ["Sono andato a Roma."],
      hint: "andare → sono andato",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-002",
      type: "produce",
      prompt: "We arrived yesterday. (mixed group)",
      accepted: ["Siamo arrivati ieri."],
      hint: "arrivare → siamo arrivati",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-003",
      type: "produce",
      prompt: "Where did you come from? (female addressee)",
      accepted: ["Da dove sei venuta?"],
      hint: "venire → sei venuta",
      tags: ["chunk", "essere", "passato-prossimo", "question"],
      tier: 3,
    },
    {
      id: "u11-t3-004",
      type: "fill_blank",
      prompt: "Marco e Giulia ___ usciti insieme stasera.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-005",
      type: "produce",
      prompt: "She returned home late. (female)",
      accepted: ["È tornata a casa tardi."],
      hint: "tornare → è tornata",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-006",
      type: "fill_blank",
      prompt: "I ragazzi ___ partiti dalla stazione alle otto.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo", "stazione"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze ─────────────────────────────────
    {
      id: "u11-t4-001",
      type: "produce",
      prompt: "My friends left from the airport at noon. (male friends)",
      accepted: ["I miei amici sono partiti dall'aeroporto a mezzogiorno."],
      hint: "partire → sono partiti; aeroporto needs dall'",
      tags: ["production", "essere", "passato-prossimo"],
      tier: 4,
      prerequisites: ["u11-t1-005", "u11-t1-010", "u11-t2-006"],
    },
    {
      id: "u11-t4-002",
      type: "produce",
      prompt: "I stayed at home all day. (female speaker)",
      accepted: ["Sono rimasta a casa tutto il giorno."],
      hint: "rimanere → sono rimasta",
      tags: ["production", "essere", "passato-prossimo"],
      tier: 4,
      prerequisites: ["u11-t1-007", "u11-t1-012", "u11-t2-008"],
    },
    {
      id: "u11-t4-003",
      type: "passage_cloze",
      prompt:
        "L'estate scorsa ho fatto un viaggio in Italia con la mia famiglia.\nSiamo partiti da Londra e ___ arrivati a Roma in aereo.\nIl primo giorno siamo andati al centro e abbiamo visitato il Colosseo.\nLa sera siamo tornati all'albergo molto stanchi ma felici.",
      accepted: ["siamo"],
      hint: "essere auxiliary — noi form",
      tags: ["passage-cloze", "essere", "passato-prossimo", "arrivare"],
      tier: 4,
      prerequisites: ["u11-t1-004", "u11-t1-011", "u11-t2-005"],
    },
    {
      id: "u11-t4-004",
      type: "passage_cloze",
      prompt:
        "Ieri mattina Maria si è svegliata presto e è uscita di casa alle sette.\nÈ andata alla stazione e ha preso il treno per Milano.\nQuando è ___ a Milano, ha telefonato alla sua amica.\nInsieme sono andate al centro per fare shopping.",
      accepted: ["arrivata"],
      hint: "arrivare → arrivata (lei, femminile)",
      tags: ["passage-cloze", "essere", "passato-prossimo", "arrivare", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-004", "u11-t1-009", "u11-t2-004"],
    },
    {
      id: "u11-t4-005",
      type: "fill_blank",
      prompt:
        "Gianni è ___ a Napoli nel 1990 e ci ha vissuto fino all'età di vent'anni.",
      accepted: ["nato"],
      hint: "nascere → nato (lui)",
      tags: ["production", "essere", "passato-prossimo", "nascere"],
      tier: 4,
      prerequisites: ["u11-t1-008", "u11-t2-009"],
    },

    // ── Tier 1 – Vocabulary (expansion) ───────────────────────────────────────
    {
      id: "u11-t1-013",
      type: "recognize",
      prompt: "entrare",
      accepted: ["to enter", "to go in"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-014",
      type: "recognize",
      prompt: "salire",
      accepted: ["to go up", "to get on"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-015",
      type: "recognize",
      prompt: "scendere",
      accepted: ["to go down", "to get off"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-016",
      type: "recognize",
      prompt: "cadere",
      accepted: ["to fall"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-017",
      type: "recognize",
      prompt: "diventare",
      accepted: ["to become"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-018",
      type: "recognize",
      prompt: "morire",
      accepted: ["to die"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-019",
      type: "recognize",
      prompt: "restare",
      accepted: ["to stay", "to remain"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-020",
      type: "recognize",
      prompt: "passare",
      accepted: ["to pass by", "to stop by"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-021",
      type: "recognize",
      prompt: "crescere",
      accepted: ["to grow up"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-022",
      type: "recognize",
      prompt: "svegliarsi",
      accepted: ["to wake up"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-023",
      type: "recognize",
      prompt: "alzarsi",
      accepted: ["to get up"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-024",
      type: "recognize",
      prompt: "vestirsi",
      accepted: ["to get dressed"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-025",
      type: "recognize",
      prompt: "lavarsi",
      accepted: ["to wash oneself"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-026",
      type: "recognize",
      prompt: "fermarsi",
      accepted: ["to stop"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-027",
      type: "recognize",
      prompt: "sposarsi",
      accepted: ["to get married"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-028",
      type: "recognize",
      prompt: "addormentarsi",
      accepted: ["to fall asleep"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-029",
      type: "recognize",
      prompt: "perdersi",
      accepted: ["to get lost"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-030",
      type: "recognize",
      prompt: "trasferirsi",
      accepted: ["to move", "to relocate"],
      hint: "reflexive verb — always uses essere",
      tags: ["verb", "reflexive", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-031",
      type: "produce",
      prompt: "the village",
      accepted: ["il paese"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-032",
      type: "produce",
      prompt: "the school",
      accepted: ["la scuola"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-033",
      type: "produce",
      prompt: "the office",
      accepted: ["l'ufficio"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-034",
      type: "produce",
      prompt: "the sea",
      accepted: ["il mare"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-035",
      type: "produce",
      prompt: "the mountain",
      accepted: ["la montagna"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-036",
      type: "produce",
      prompt: "abroad",
      accepted: ["l'estero"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-037",
      type: "produce",
      prompt: "the bus stop",
      accepted: ["la fermata"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-038",
      type: "produce",
      prompt: "the neighbourhood",
      accepted: ["il quartiere"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-039",
      type: "produce",
      prompt: "the bridge",
      accepted: ["il ponte"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-040",
      type: "produce",
      prompt: "the door",
      accepted: ["la porta"],
      tags: ["noun", "object"],
      tier: 1,
    },
    {
      id: "u11-t1-041",
      type: "produce",
      prompt: "the party",
      accepted: ["la festa"],
      tags: ["noun", "event"],
      tier: 1,
    },
    {
      id: "u11-t1-042",
      type: "produce",
      prompt: "the beach",
      accepted: ["la spiaggia"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-043",
      type: "produce",
      prompt: "the bed",
      accepted: ["il letto"],
      tags: ["noun", "object"],
      tier: 1,
    },
    {
      id: "u11-t1-044",
      type: "produce",
      prompt: "the mirror",
      accepted: ["lo specchio"],
      tags: ["noun", "object"],
      tier: 1,
    },
    {
      id: "u11-t1-045",
      type: "produce",
      prompt: "the bus",
      accepted: ["l'autobus"],
      tags: ["noun", "transport"],
      tier: 1,
    },
    {
      id: "u11-t1-046",
      type: "produce",
      prompt: "the train",
      accepted: ["il treno"],
      tags: ["noun", "transport"],
      tier: 1,
    },
    {
      id: "u11-t1-047",
      type: "produce",
      prompt: "the stairs",
      accepted: ["le scale"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-048",
      type: "produce",
      prompt: "the wedding",
      accepted: ["il matrimonio"],
      tags: ["noun", "event"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (conjugation, expansion) ─────────────────────────────
    {
      id: "u11-t2-011",
      type: "conjugate",
      prompt: "entrare (passato prossimo) – io (maschile)",
      accepted: ["sono entrato"],
      tags: ["essere", "passato-prossimo", "conjugation", "entrare"],
      tier: 2,
    },
    {
      id: "u11-t2-012",
      type: "conjugate",
      prompt: "entrare (passato prossimo) – tu (femminile)",
      accepted: ["sei entrata"],
      tags: ["essere", "passato-prossimo", "conjugation", "entrare"],
      tier: 2,
    },
    {
      id: "u11-t2-013",
      type: "conjugate",
      prompt: "entrare (passato prossimo) – loro (femminile)",
      accepted: ["sono entrate"],
      tags: ["essere", "passato-prossimo", "conjugation", "entrare"],
      tier: 2,
    },
    {
      id: "u11-t2-014",
      type: "conjugate",
      prompt: "salire (passato prossimo) – lei",
      accepted: ["è salita"],
      tags: ["essere", "passato-prossimo", "conjugation", "salire"],
      tier: 2,
    },
    {
      id: "u11-t2-015",
      type: "conjugate",
      prompt: "salire (passato prossimo) – noi (maschile/misto)",
      accepted: ["siamo saliti"],
      tags: ["essere", "passato-prossimo", "conjugation", "salire"],
      tier: 2,
    },
    {
      id: "u11-t2-016",
      type: "conjugate",
      prompt: "salire (passato prossimo) – voi (femminile)",
      accepted: ["siete salite"],
      tags: ["essere", "passato-prossimo", "conjugation", "salire"],
      tier: 2,
    },
    {
      id: "u11-t2-017",
      type: "conjugate",
      prompt: "scendere (passato prossimo) – lui",
      accepted: ["è sceso"],
      hint: "scendere → sceso/a (irregular)",
      tags: ["essere", "passato-prossimo", "conjugation", "scendere"],
      tier: 2,
    },
    {
      id: "u11-t2-018",
      type: "conjugate",
      prompt: "scendere (passato prossimo) – io (femminile)",
      accepted: ["sono scesa"],
      tags: ["essere", "passato-prossimo", "conjugation", "scendere"],
      tier: 2,
    },
    {
      id: "u11-t2-019",
      type: "conjugate",
      prompt: "scendere (passato prossimo) – loro (maschile/misto)",
      accepted: ["sono scesi"],
      tags: ["essere", "passato-prossimo", "conjugation", "scendere"],
      tier: 2,
    },
    {
      id: "u11-t2-020",
      type: "conjugate",
      prompt: "cadere (passato prossimo) – lei",
      accepted: ["è caduta"],
      tags: ["essere", "passato-prossimo", "conjugation", "cadere"],
      tier: 2,
    },
    {
      id: "u11-t2-021",
      type: "conjugate",
      prompt: "cadere (passato prossimo) – tu (maschile)",
      accepted: ["sei caduto"],
      tags: ["essere", "passato-prossimo", "conjugation", "cadere"],
      tier: 2,
    },
    {
      id: "u11-t2-022",
      type: "conjugate",
      prompt: "cadere (passato prossimo) – noi (femminile)",
      accepted: ["siamo cadute"],
      tags: ["essere", "passato-prossimo", "conjugation", "cadere"],
      tier: 2,
    },
    {
      id: "u11-t2-023",
      type: "conjugate",
      prompt: "diventare (passato prossimo) – lui",
      accepted: ["è diventato"],
      tags: ["essere", "passato-prossimo", "conjugation", "diventare"],
      tier: 2,
    },
    {
      id: "u11-t2-024",
      type: "conjugate",
      prompt: "diventare (passato prossimo) – io (femminile)",
      accepted: ["sono diventata"],
      tags: ["essere", "passato-prossimo", "conjugation", "diventare"],
      tier: 2,
    },
    {
      id: "u11-t2-025",
      type: "conjugate",
      prompt: "diventare (passato prossimo) – loro (femminile)",
      accepted: ["sono diventate"],
      tags: ["essere", "passato-prossimo", "conjugation", "diventare"],
      tier: 2,
    },
    {
      id: "u11-t2-026",
      type: "conjugate",
      prompt: "morire (passato prossimo) – lui",
      accepted: ["è morto"],
      hint: "morire → morto/a (irregular)",
      tags: ["essere", "passato-prossimo", "conjugation", "morire"],
      tier: 2,
    },
    {
      id: "u11-t2-027",
      type: "conjugate",
      prompt: "morire (passato prossimo) – loro (maschile/misto)",
      accepted: ["sono morti"],
      tags: ["essere", "passato-prossimo", "conjugation", "morire"],
      tier: 2,
    },
    {
      id: "u11-t2-028",
      type: "conjugate",
      prompt: "morire (passato prossimo) – tu (femminile)",
      accepted: ["sei morta"],
      tags: ["essere", "passato-prossimo", "conjugation", "morire"],
      tier: 2,
    },
    {
      id: "u11-t2-029",
      type: "conjugate",
      prompt: "restare (passato prossimo) – noi (maschile/misto)",
      accepted: ["siamo restati"],
      tags: ["essere", "passato-prossimo", "conjugation", "restare"],
      tier: 2,
    },
    {
      id: "u11-t2-030",
      type: "conjugate",
      prompt: "restare (passato prossimo) – lei",
      accepted: ["è restata"],
      tags: ["essere", "passato-prossimo", "conjugation", "restare"],
      tier: 2,
    },
    {
      id: "u11-t2-031",
      type: "conjugate",
      prompt: "restare (passato prossimo) – voi (maschile)",
      accepted: ["siete restati"],
      tags: ["essere", "passato-prossimo", "conjugation", "restare"],
      tier: 2,
    },
    {
      id: "u11-t2-032",
      type: "conjugate",
      prompt: "passare (passato prossimo) – lui",
      accepted: ["è passato"],
      tags: ["essere", "passato-prossimo", "conjugation", "passare"],
      tier: 2,
    },
    {
      id: "u11-t2-033",
      type: "conjugate",
      prompt: "passare (passato prossimo) – io (femminile)",
      accepted: ["sono passata"],
      tags: ["essere", "passato-prossimo", "conjugation", "passare"],
      tier: 2,
    },
    {
      id: "u11-t2-034",
      type: "conjugate",
      prompt: "passare (passato prossimo) – loro (femminile)",
      accepted: ["sono passate"],
      tags: ["essere", "passato-prossimo", "conjugation", "passare"],
      tier: 2,
    },
    {
      id: "u11-t2-035",
      type: "conjugate",
      prompt: "crescere (passato prossimo) – lei",
      accepted: ["è cresciuta"],
      hint: "crescere → cresciuto/a (irregular)",
      tags: ["essere", "passato-prossimo", "conjugation", "crescere"],
      tier: 2,
    },
    {
      id: "u11-t2-036",
      type: "conjugate",
      prompt: "crescere (passato prossimo) – noi (femminile)",
      accepted: ["siamo cresciute"],
      tags: ["essere", "passato-prossimo", "conjugation", "crescere"],
      tier: 2,
    },
    {
      id: "u11-t2-037",
      type: "conjugate",
      prompt: "crescere (passato prossimo) – loro (maschile/misto)",
      accepted: ["sono cresciuti"],
      tags: ["essere", "passato-prossimo", "conjugation", "crescere"],
      tier: 2,
    },
    {
      id: "u11-t2-038",
      type: "conjugate",
      prompt: "svegliarsi (passato prossimo) – io (maschile)",
      accepted: ["mi sono svegliato"],
      hint: "reflexive verb: pronoun + essere + participio",
      tags: ["essere", "passato-prossimo", "conjugation", "svegliarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-039",
      type: "conjugate",
      prompt: "svegliarsi (passato prossimo) – tu (femminile)",
      accepted: ["ti sei svegliata"],
      tags: ["essere", "passato-prossimo", "conjugation", "svegliarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-040",
      type: "conjugate",
      prompt: "svegliarsi (passato prossimo) – noi (femminile)",
      accepted: ["ci siamo svegliate"],
      tags: ["essere", "passato-prossimo", "conjugation", "svegliarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-041",
      type: "conjugate",
      prompt: "alzarsi (passato prossimo) – lui",
      accepted: ["si è alzato"],
      tags: ["essere", "passato-prossimo", "conjugation", "alzarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-042",
      type: "conjugate",
      prompt: "alzarsi (passato prossimo) – io (femminile)",
      accepted: ["mi sono alzata"],
      tags: ["essere", "passato-prossimo", "conjugation", "alzarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-043",
      type: "conjugate",
      prompt: "alzarsi (passato prossimo) – loro (maschile/misto)",
      accepted: ["si sono alzati"],
      tags: ["essere", "passato-prossimo", "conjugation", "alzarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-044",
      type: "conjugate",
      prompt: "vestirsi (passato prossimo) – lei",
      accepted: ["si è vestita"],
      tags: ["essere", "passato-prossimo", "conjugation", "vestirsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-045",
      type: "conjugate",
      prompt: "vestirsi (passato prossimo) – tu (maschile)",
      accepted: ["ti sei vestito"],
      tags: ["essere", "passato-prossimo", "conjugation", "vestirsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-046",
      type: "conjugate",
      prompt: "vestirsi (passato prossimo) – voi (femminile)",
      accepted: ["vi siete vestite"],
      tags: ["essere", "passato-prossimo", "conjugation", "vestirsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-047",
      type: "conjugate",
      prompt: "lavarsi (passato prossimo) – io (maschile)",
      accepted: ["mi sono lavato"],
      tags: ["essere", "passato-prossimo", "conjugation", "lavarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-048",
      type: "conjugate",
      prompt: "lavarsi (passato prossimo) – noi (maschile/misto)",
      accepted: ["ci siamo lavati"],
      tags: ["essere", "passato-prossimo", "conjugation", "lavarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-049",
      type: "conjugate",
      prompt: "lavarsi (passato prossimo) – loro (femminile)",
      accepted: ["si sono lavate"],
      tags: ["essere", "passato-prossimo", "conjugation", "lavarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-050",
      type: "conjugate",
      prompt: "fermarsi (passato prossimo) – lui",
      accepted: ["si è fermato"],
      tags: ["essere", "passato-prossimo", "conjugation", "fermarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-051",
      type: "conjugate",
      prompt: "fermarsi (passato prossimo) – noi (femminile)",
      accepted: ["ci siamo fermate"],
      tags: ["essere", "passato-prossimo", "conjugation", "fermarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-052",
      type: "conjugate",
      prompt: "sposarsi (passato prossimo) – lei",
      accepted: ["si è sposata"],
      tags: ["essere", "passato-prossimo", "conjugation", "sposarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-053",
      type: "conjugate",
      prompt: "sposarsi (passato prossimo) – loro (maschile/misto)",
      accepted: ["si sono sposati"],
      tags: ["essere", "passato-prossimo", "conjugation", "sposarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-054",
      type: "conjugate",
      prompt: "sposarsi (passato prossimo) – io (femminile)",
      accepted: ["mi sono sposata"],
      tags: ["essere", "passato-prossimo", "conjugation", "sposarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-055",
      type: "conjugate",
      prompt: "addormentarsi (passato prossimo) – tu (femminile)",
      accepted: ["ti sei addormentata"],
      tags: ["essere", "passato-prossimo", "conjugation", "addormentarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-056",
      type: "conjugate",
      prompt: "addormentarsi (passato prossimo) – lui",
      accepted: ["si è addormentato"],
      tags: ["essere", "passato-prossimo", "conjugation", "addormentarsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-057",
      type: "conjugate",
      prompt: "perdersi (passato prossimo) – lei",
      accepted: ["si è persa"],
      hint: "perdersi → perso/a (irregular)",
      tags: ["essere", "passato-prossimo", "conjugation", "perdersi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-058",
      type: "conjugate",
      prompt: "perdersi (passato prossimo) – loro (maschile/misto)",
      accepted: ["si sono persi"],
      tags: ["essere", "passato-prossimo", "conjugation", "perdersi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-059",
      type: "conjugate",
      prompt: "trasferirsi (passato prossimo) – noi (maschile/misto)",
      accepted: ["ci siamo trasferiti"],
      tags: ["essere", "passato-prossimo", "conjugation", "trasferirsi", "reflexive"],
      tier: 2,
    },
    {
      id: "u11-t2-060",
      type: "conjugate",
      prompt: "trasferirsi (passato prossimo) – io (femminile)",
      accepted: ["mi sono trasferita"],
      tags: ["essere", "passato-prossimo", "conjugation", "trasferirsi", "reflexive"],
      tier: 2,
    },

    // ── Tier 3 – Chunks / Short sentences (expansion) ─────────────────────────
    {
      id: "u11-t3-007",
      type: "produce",
      prompt: "I entered the school at eight.",
      accepted: ["Sono entrato a scuola alle otto."],
      hint: "entrare a scuola — no article after a scuola",
      tags: ["chunk", "essere", "passato-prossimo", "collocation"],
      tier: 3,
    },
    {
      id: "u11-t3-008",
      type: "produce",
      prompt: "She got off the bus in the neighbourhood. (female)",
      accepted: ["È scesa dall'autobus nel quartiere."],
      hint: "scendere da → dall'autobus",
      tags: ["chunk", "essere", "passato-prossimo", "scendere"],
      tier: 3,
    },
    {
      id: "u11-t3-009",
      type: "produce",
      prompt: "We fell on the stairs. (mixed group)",
      accepted: ["Siamo caduti sulle scale."],
      tags: ["chunk", "essere", "passato-prossimo", "cadere"],
      tier: 3,
    },
    {
      id: "u11-t3-010",
      type: "produce",
      prompt: "He became a doctor after five years.",
      accepted: ["È diventato medico dopo cinque anni."],
      tags: ["chunk", "essere", "passato-prossimo", "diventare"],
      tier: 3,
    },
    {
      id: "u11-t3-011",
      type: "fill_blank",
      prompt: "Mia zia ___ morta due anni fa.",
      accepted: ["è"],
      hint: "essere auxiliary — lei form",
      tags: ["chunk", "essere", "passato-prossimo", "morire"],
      tier: 3,
    },
    {
      id: "u11-t3-012",
      type: "produce",
      prompt: "They got married at the beach. (mixed group)",
      accepted: ["Si sono sposati in spiaggia."],
      tags: ["chunk", "essere", "passato-prossimo", "sposarsi", "collocation"],
      tier: 3,
    },
    {
      id: "u11-t3-013",
      type: "fill_blank",
      prompt: "Luca e Sara ___ trasferiti a Milano il mese scorso.",
      accepted: ["si sono"],
      hint: "reflexive essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo", "trasferirsi"],
      tier: 3,
    },
    {
      id: "u11-t3-014",
      type: "produce",
      prompt: "I woke up late and I got up in a hurry. (male speaker)",
      accepted: ["Mi sono svegliato tardi e mi sono alzato in fretta."],
      tags: ["chunk", "essere", "passato-prossimo", "svegliarsi", "alzarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-015",
      type: "produce",
      prompt: "She got dressed quickly and left the house. (female)",
      accepted: ["Si è vestita in fretta ed è uscita di casa."],
      tags: ["chunk", "essere", "passato-prossimo", "vestirsi"],
      tier: 3,
    },
    {
      id: "u11-t3-016",
      type: "fill_blank",
      prompt: "Non ___ mai persa in questa città, conosco tutte le strade.",
      accepted: ["mi sono"],
      hint: "reflexive essere auxiliary — io form",
      tags: ["chunk", "essere", "passato-prossimo", "perdersi"],
      tier: 3,
    },
    {
      id: "u11-t3-017",
      type: "produce",
      prompt: "We stopped for a coffee near the bridge. (mixed group)",
      accepted: ["Ci siamo fermati per un caffè vicino al ponte."],
      hint: "fermarsi per un caffè — common collocation",
      tags: ["chunk", "essere", "passato-prossimo", "fermarsi", "collocation"],
      tier: 3,
    },
    {
      id: "u11-t3-018",
      type: "produce",
      prompt: "My grandfather grew up in a small village.",
      accepted: ["Mio nonno è cresciuto in un piccolo paese."],
      tags: ["chunk", "essere", "passato-prossimo", "crescere"],
      tier: 3,
    },
    {
      id: "u11-t3-019",
      type: "fill_blank",
      prompt: "Il gatto ___ caduto dal letto stanotte.",
      accepted: ["è"],
      hint: "essere auxiliary — lui form",
      tags: ["chunk", "essere", "passato-prossimo", "cadere"],
      tier: 3,
    },
    {
      id: "u11-t3-020",
      type: "produce",
      prompt: "I fell asleep on the sofa watching TV. (male speaker)",
      accepted: ["Mi sono addormentato sul divano guardando la TV."],
      tags: ["chunk", "essere", "passato-prossimo", "addormentarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-021",
      type: "produce",
      prompt: "He went up to the third floor by the stairs.",
      accepted: ["È salito al terzo piano per le scale."],
      hint: "salire without a direct object takes essere; per le scale = via the stairs",
      tags: ["chunk", "essere", "passato-prossimo", "salire"],
      tier: 3,
    },
    {
      id: "u11-t3-022",
      type: "produce",
      prompt: "The children got off the bus in front of the school.",
      accepted: ["I bambini sono scesi dall'autobus davanti alla scuola."],
      tags: ["chunk", "essere", "passato-prossimo", "scendere"],
      tier: 3,
    },
    {
      id: "u11-t3-023",
      type: "fill_blank",
      prompt: "Anna e Paolo ___ svegliati alle sei per prendere il treno.",
      accepted: ["si sono"],
      hint: "reflexive essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo", "svegliarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-024",
      type: "produce",
      prompt: "I moved abroad to study. (female speaker)",
      accepted: ["Mi sono trasferita all'estero per studiare."],
      tags: ["chunk", "essere", "passato-prossimo", "trasferirsi"],
      tier: 3,
    },
    {
      id: "u11-t3-025",
      type: "produce",
      prompt: "We got lost in the neighbourhood at night. (mixed group)",
      accepted: ["Ci siamo persi nel quartiere di notte."],
      tags: ["chunk", "essere", "passato-prossimo", "perdersi"],
      tier: 3,
    },
    {
      id: "u11-t3-026",
      type: "fill_blank",
      prompt: "Il bambino ___ cresciuto molto quest'anno.",
      accepted: ["è"],
      hint: "essere auxiliary — lui form",
      tags: ["chunk", "essere", "passato-prossimo", "crescere"],
      tier: 3,
    },
    {
      id: "u11-t3-027",
      type: "produce",
      prompt: "She stopped at the office for five minutes.",
      accepted: ["Si è fermata in ufficio per cinque minuti."],
      tags: ["chunk", "essere", "passato-prossimo", "fermarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-028",
      type: "produce",
      prompt: "My parents got married thirty years ago. (mixed group)",
      accepted: ["I miei genitori si sono sposati trent'anni fa."],
      tags: ["chunk", "essere", "passato-prossimo", "sposarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-029",
      type: "fill_blank",
      prompt: "Le mie amiche ___ entrate in ritardo.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro (femminile) form",
      tags: ["chunk", "essere", "passato-prossimo", "entrare"],
      tier: 3,
    },
    {
      id: "u11-t3-030",
      type: "produce",
      prompt: "I passed by your house yesterday but you weren't there. (male speaker)",
      accepted: ["Sono passato da casa tua ieri ma non c'eri."],
      tags: ["chunk", "essere", "passato-prossimo", "passare", "collocation"],
      tier: 3,
    },
    {
      id: "u11-t3-031",
      type: "produce",
      prompt: "I got up early to go to the mountains. (female speaker)",
      accepted: ["Mi sono alzata presto per andare in montagna."],
      tags: ["chunk", "essere", "passato-prossimo", "alzarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-032",
      type: "fill_blank",
      prompt: "Quando è ___ il treno, tutti sono scesi in fretta.",
      accepted: ["arrivato"],
      hint: "arrivare → arrivato (il treno, maschile)",
      tags: ["chunk", "essere", "passato-prossimo", "arrivare", "agreement"],
      tier: 3,
    },
    {
      id: "u11-t3-033",
      type: "produce",
      prompt: "They got married near the bridge, in front of all their friends. (mixed group)",
      accepted: ["Si sono sposati vicino al ponte, davanti a tutti gli amici."],
      tags: ["chunk", "essere", "passato-prossimo", "sposarsi"],
      tier: 3,
    },
    {
      id: "u11-t3-034",
      type: "produce",
      prompt: "He was born in a small village and grew up in the city.",
      accepted: ["È nato in un piccolo paese ed è cresciuto in città."],
      tags: ["chunk", "essere", "passato-prossimo", "nascere", "crescere"],
      tier: 3,
    },
    {
      id: "u11-t3-035",
      type: "produce",
      prompt: "Before going out, she looked at herself in the mirror.",
      accepted: ["Prima di uscire, si è guardata allo specchio."],
      hint: "uscire (infinitive after prima di) + si è guardata (reflexive, lei) + allo specchio",
      tags: ["chunk", "essere", "passato-prossimo", "uscire", "specchio", "reflexive"],
      tier: 3,
    },
    {
      id: "u11-t3-036",
      type: "produce",
      prompt: "Last summer we went to the sea. (mixed group)",
      accepted: ["L'estate scorsa siamo andati al mare."],
      hint: "andare → siamo andati (noi, maschile/misto); al mare = a + il mare",
      tags: ["chunk", "essere", "passato-prossimo", "andare", "mare"],
      tier: 3,
    },
    {
      id: "u11-t3-037",
      type: "produce",
      prompt: "We came back from the sea very tired. (mixed group)",
      accepted: ["Siamo tornati dal mare molto stanchi."],
      hint: "tornare → siamo tornati; dal mare = da + il mare",
      tags: ["chunk", "essere", "passato-prossimo", "tornare", "mare"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze (expansion) ───────────────────────
    {
      id: "u11-t4-006",
      type: "produce",
      prompt: "My sister woke up, got dressed, and left the house before seven. (female)",
      accepted: ["Mia sorella si è svegliata, si è vestita ed è uscita di casa prima delle sette."],
      hint: "chain three essere verbs, all agreeing with a feminine subject",
      tags: ["production", "essere", "passato-prossimo", "svegliarsi", "vestirsi"],
      tier: 4,
      prerequisites: ["u11-t1-022", "u11-t1-024", "u11-t1-003"],
    },
    {
      id: "u11-t4-007",
      type: "produce",
      prompt: "My brothers got up late and arrived late to school. (male)",
      accepted: ["I miei fratelli si sono alzati tardi e sono arrivati tardi a scuola."],
      tags: ["production", "essere", "passato-prossimo", "alzarsi", "arrivare"],
      tier: 4,
      prerequisites: ["u11-t1-023", "u11-t1-004", "u11-t1-032"],
    },
    {
      id: "u11-t4-008",
      type: "produce",
      prompt: "The old man fell on the stairs and went straight to the emergency room.",
      accepted: ["L'anziano è caduto sulle scale ed è andato subito al pronto soccorso."],
      tags: ["production", "essere", "passato-prossimo", "cadere"],
      tier: 4,
      prerequisites: ["u11-t1-016", "u11-t1-047", "u11-t1-001"],
    },
    {
      id: "u11-t4-009",
      type: "produce",
      prompt: "The two sisters got married on the same day.",
      accepted: ["Le due sorelle si sono sposate lo stesso giorno."],
      hint: "sposate agrees with the feminine plural subject",
      tags: ["production", "essere", "passato-prossimo", "sposarsi", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-027", "u11-t2-052"],
    },
    {
      id: "u11-t4-010",
      type: "produce",
      prompt: "I grew up in the mountains and I moved to the city at twenty. (female speaker)",
      accepted: ["Sono cresciuta in montagna e mi sono trasferita in città a vent'anni."],
      tags: ["production", "essere", "passato-prossimo", "crescere", "trasferirsi"],
      tier: 4,
      prerequisites: ["u11-t1-021", "u11-t1-035", "u11-t1-030"],
    },
    {
      id: "u11-t4-011",
      type: "produce",
      prompt: "We stopped at the beach and fell asleep in the sun. (mixed group)",
      accepted: ["Ci siamo fermati in spiaggia e ci siamo addormentati al sole."],
      tags: ["production", "essere", "passato-prossimo", "fermarsi", "addormentarsi"],
      tier: 4,
      prerequisites: ["u11-t1-026", "u11-t1-042", "u11-t1-028"],
    },
    {
      id: "u11-t4-012",
      type: "produce",
      prompt: "My grandmother was born in a village and died in the same house.",
      accepted: ["Mia nonna è nata in un paese ed è morta nella stessa casa."],
      tags: ["production", "essere", "passato-prossimo", "nascere", "morire"],
      tier: 4,
      prerequisites: ["u11-t1-008", "u11-t1-031", "u11-t1-018"],
    },
    {
      id: "u11-t4-013",
      type: "produce",
      prompt: "The girls got lost in the neighbourhood and arrived late to the party.",
      accepted: ["Le ragazze si sono perse nel quartiere e sono arrivate tardi alla festa."],
      hint: "perse and arrivate both agree with a feminine plural subject",
      tags: ["production", "essere", "passato-prossimo", "perdersi", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-029", "u11-t1-038", "u11-t1-041"],
    },
    {
      id: "u11-t4-014",
      type: "passage_cloze",
      prompt:
        "Il giorno del matrimonio, Elena si è svegliata all'alba ed è subito entrata in bagno.\nSi è lavata e si è vestita con cura.\nGli invitati ___ arrivati in chiesa alle undici, tutti eleganti.\nElena e Marco si sono sposati davanti a tutta la famiglia.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro form (gli invitati, maschile)",
      tags: ["passage-cloze", "essere", "passato-prossimo", "sposarsi", "arrivare"],
      tier: 4,
      prerequisites: ["u11-t1-022", "u11-t1-027", "u11-t1-048"],
    },
    {
      id: "u11-t4-015",
      type: "passage_cloze",
      prompt:
        "Due anni fa, Sofia si è trasferita all'estero per lavoro.\nÈ arrivata a Berlino con due valigie pesanti.\nAll'inizio si è persa spesso perché non conosceva il quartiere.\nDopo qualche mese, però, non si è più ___ e ora conosce la città a memoria.",
      accepted: ["persa"],
      hint: "perdersi → persa (lei, femminile)",
      tags: ["passage-cloze", "essere", "passato-prossimo", "perdersi", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-030", "u11-t1-036", "u11-t1-029"],
    },
    {
      id: "u11-t4-016",
      type: "passage_cloze",
      prompt:
        "Paolo è nato in un piccolo paese di montagna.\nÈ cresciuto insieme ai suoi tre fratelli in una casa vicino alla chiesa.\nA diciotto anni ___ trasferito in città per studiare all'università.\nOggi torna al paese solo per le feste importanti.",
      accepted: ["si è"],
      hint: "reflexive essere auxiliary — lui form",
      tags: ["passage-cloze", "essere", "passato-prossimo", "trasferirsi"],
      tier: 4,
      prerequisites: ["u11-t1-021", "u11-t1-031", "u11-t1-030"],
    },
    {
      id: "u11-t4-017",
      type: "produce",
      prompt: "The bus stopped in front of the bridge and everyone got off.",
      accepted: ["L'autobus si è fermato davanti al ponte e tutti sono scesi."],
      tags: ["production", "essere", "passato-prossimo", "fermarsi", "scendere"],
      tier: 4,
      prerequisites: ["u11-t1-026", "u11-t1-045", "u11-t1-015"],
    },
    {
      id: "u11-t4-018",
      type: "produce",
      prompt: "I fell asleep early because I woke up before dawn. (male speaker)",
      accepted: ["Mi sono addormentato presto perché mi sono svegliato prima dell'alba."],
      tags: ["production", "essere", "passato-prossimo", "addormentarsi", "svegliarsi"],
      tier: 4,
      prerequisites: ["u11-t1-028", "u11-t1-022"],
    },
    {
      id: "u11-t4-019",
      type: "produce",
      prompt: "Her grandparents grew up in the same village and got married very young.",
      accepted: ["I suoi nonni sono cresciuti nello stesso paese e si sono sposati molto giovani."],
      tags: ["production", "essere", "passato-prossimo", "crescere", "sposarsi"],
      tier: 4,
      prerequisites: ["u11-t1-021", "u11-t1-031", "u11-t1-027"],
    },
    {
      id: "u11-t4-020",
      type: "produce",
      prompt: "We entered the office, went up to the third floor, and stopped in front of the door. (mixed group)",
      accepted: ["Siamo entrati in ufficio, siamo saliti al terzo piano e ci siamo fermati davanti alla porta."],
      hint: "three essere verbs in sequence — watch the agreement on each",
      tags: ["production", "essere", "passato-prossimo", "entrare", "salire", "fermarsi"],
      tier: 4,
      prerequisites: ["u11-t1-013", "u11-t1-033", "u11-t1-014", "u11-t1-040"],
    },
    {
      id: "u11-t4-021",
      type: "produce",
      prompt: "The girl fell down the stairs but got up immediately.",
      accepted: ["La bambina è caduta dalle scale ma si è alzata subito."],
      hint: "caduta and alzata both agree with a feminine singular subject",
      tags: ["production", "essere", "passato-prossimo", "cadere", "alzarsi", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-016", "u11-t1-047", "u11-t1-023"],
    },
  ],
};
export default unit;
