import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-20-adverbs",
  name: "Adverbs",
  level: "A2",
  theme: "Adverbs",
  emoji: "💬",
  prerequisiteUnits: ["a2-unit-10-past-avere", "a2-unit-11-past-essere"],
  cards: [
    // ── Tier 1 – Vocabulary (ita_to_eng) ────────────────────────────────
    {
      id: "a220-t1-001",
      type: "recognize",
      prompt: "ancora",
      accepted: ["still", "yet", "again"],
      hint: "Three meanings: 'ancora?' = again; 'non ancora' = not yet; 'ancora qui' = still here. Context decides.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-002",
      type: "recognize",
      prompt: "già",
      accepted: ["already"],
      hint: "In compound tenses già slots between auxiliary and past participle: ho già mangiato.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-003",
      type: "recognize",
      prompt: "mai",
      accepted: ["never", "ever"],
      hint: "With non it means 'never' (non mangio mai). Without non in a question it means 'ever' (hai mai visto?).",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-004",
      type: "recognize",
      prompt: "sempre",
      accepted: ["always"],
      hint: "Position is flexible but most natural before the main verb or after the auxiliary in compound tenses.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-005",
      type: "recognize",
      prompt: "spesso",
      accepted: ["often"],
      hint: "Usually placed after the verb: esco spesso la sera.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-006",
      type: "recognize",
      prompt: "raramente",
      accepted: ["rarely", "seldom"],
      hint: "Formed by adding -mente to the adjective rara. Can open or close a sentence.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-007",
      type: "recognize",
      prompt: "subito",
      accepted: ["immediately", "right away", "at once"],
      hint: "Often follows the verb: vieni subito! Strong urgency.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-008",
      type: "recognize",
      prompt: "presto",
      accepted: ["soon", "early", "quickly"],
      hint: "Temporal (soon/early) or manner (quickly). Ci vediamo presto = see you soon.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-009",
      type: "recognize",
      prompt: "tardi",
      accepted: ["late"],
      hint: "Opposite of presto when referring to time. È tardi = it is late.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-010",
      type: "recognize",
      prompt: "adesso",
      accepted: ["now"],
      hint: "Interchangeable with ora in most contexts; adesso can feel slightly more emphatic.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-011",
      type: "recognize",
      prompt: "ora",
      accepted: ["now"],
      hint: "Synonymous with adesso. Also means 'hour' as a noun — context distinguishes the two.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-012",
      type: "recognize",
      prompt: "poi",
      accepted: ["then", "afterwards", "later"],
      hint: "Sequences events: prima… poi… = first… then… Common in narrating steps.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-013",
      type: "recognize",
      prompt: "prima",
      accepted: ["before", "first", "earlier"],
      hint: "As an adverb: prima fai i compiti = do homework first. As a preposition needs 'di': prima di mangiare.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-014",
      type: "recognize",
      prompt: "dopo",
      accepted: ["after", "afterwards", "later"],
      hint: "Standalone adverb: ci vediamo dopo. As preposition: dopo la cena. Do not confuse with poi.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-015",
      type: "recognize",
      prompt: "forse",
      accepted: ["maybe", "perhaps"],
      hint: "Typically sentence-initial but can appear anywhere. Does not change verb mood at A2 level.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-016",
      type: "recognize",
      prompt: "quasi",
      accepted: ["almost", "nearly"],
      hint: "Modifies adjectives, verbs, or other adverbs: quasi pronto = almost ready; quasi sempre = almost always.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-017",
      type: "recognize",
      prompt: "molto",
      accepted: ["very", "a lot", "much"],
      hint: "As an adverb it is invariable: molto bello, molto bene. As an adjective it agrees with the noun.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-018",
      type: "recognize",
      prompt: "poco",
      accepted: ["a little", "not much", "few"],
      hint: "Adverb (invariable): parlo poco. Adjective: poca acqua. Do not confuse the two uses.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-019",
      type: "recognize",
      prompt: "abbastanza",
      accepted: ["enough", "quite", "fairly"],
      hint: "Abbastanza + adjective = quite/fairly. Abbastanza + noun = enough. It is always invariable.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-020",
      type: "recognize",
      prompt: "troppo",
      accepted: ["too much", "too"],
      hint: "Adverb (invariable): mangi troppo. Adjective: troppa pizza. Used like molto but implies excess.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-021",
      type: "recognize",
      prompt: "piano",
      accepted: ["slowly", "softly", "quietly", "gently"],
      hint: "Manner adverb. Parla piano = speak quietly/slowly. Opposite of forte in the sense of volume.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-022",
      type: "recognize",
      prompt: "forte",
      accepted: ["loudly", "hard", "strongly"],
      hint: "As manner adverb: parla forte = speak loudly; colpisci forte = hit hard. Also an adjective meaning 'strong'.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-023",
      type: "recognize",
      prompt: "purtroppo",
      accepted: ["unfortunately"],
      hint: "Sentence adverb; typically sentence-initial. Purtroppo non posso venire = unfortunately I can't come.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-024",
      type: "recognize",
      prompt: "perfino",
      accepted: ["even"],
      hint: "Focus particle that highlights the surprising element: perfino lui ha capito = even he understood. Synonymous with persino.",
      tags: ["adverb", "focus", "A2"],
      tier: 1,
    },

    // ── Tier 1 – Vocabulary (expansion) ──────────────────────────────────
    {
      id: "a220-t1-025",
      type: "recognize",
      prompt: "bene",
      accepted: ["well"],
      hint: "Manner adverb pairing with stare and andare: sto bene, va bene. Irregular comparative: meglio (better).",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-026",
      type: "recognize",
      prompt: "male",
      accepted: ["badly", "poorly"],
      hint: "Opposite of bene. Sto male = I feel bad. Irregular comparative: peggio (worse).",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-027",
      type: "recognize",
      prompt: "volentieri",
      accepted: ["gladly", "willingly"],
      hint: "Common reply to an invitation: Vieni con noi? — Volentieri! Marks enthusiastic agreement.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-028",
      type: "recognize",
      prompt: "insieme",
      accepted: ["together"],
      hint: "Usually follows the verb: usciamo insieme = we go out together. Invariable regardless of number or gender.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-029",
      type: "recognize",
      prompt: "velocemente",
      accepted: ["quickly", "fast"],
      hint: "-mente adverb from veloce (fast). Follows the verb: guida velocemente.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-030",
      type: "recognize",
      prompt: "lentamente",
      accepted: ["slowly"],
      hint: "-mente adverb from lento. Alternative to piano when emphasizing gradual pace rather than quiet.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-031",
      type: "recognize",
      prompt: "facilmente",
      accepted: ["easily"],
      hint: "-mente adverb from facile; adjectives in -le drop the final e before adding -mente.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-032",
      type: "recognize",
      prompt: "chiaramente",
      accepted: ["clearly"],
      hint: "-mente adverb from chiaro. Often opens a sentence to frame an opinion: chiaramente non è facile.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-033",
      type: "recognize",
      prompt: "sicuramente",
      accepted: ["certainly", "surely"],
      hint: "-mente adverb from sicuro. Expresses strong confidence, stronger than forse or probabilmente.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-034",
      type: "recognize",
      prompt: "probabilmente",
      accepted: ["probably"],
      hint: "-mente adverb from probabile; adjectives in -le drop the final e. Weaker certainty than sicuramente.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-035",
      type: "recognize",
      prompt: "generalmente",
      accepted: ["generally"],
      hint: "-mente adverb from generale. Often sentence-initial to frame a general truth before a specific exception.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-036",
      type: "recognize",
      prompt: "normalmente",
      accepted: ["normally", "usually"],
      hint: "-mente adverb from normale. Near-synonym of di solito for describing habitual actions.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-037",
      type: "recognize",
      prompt: "specialmente",
      accepted: ["especially"],
      hint: "-mente adverb from speciale. Singles out one element from a broader group: mi piace la frutta, specialmente le fragole.",
      tags: ["adverb", "focus", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-038",
      type: "recognize",
      prompt: "particolarmente",
      accepted: ["particularly"],
      hint: "-mente adverb from particolare. Similar to specialmente but slightly more formal register.",
      tags: ["adverb", "focus", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-039",
      type: "recognize",
      prompt: "esattamente",
      accepted: ["exactly"],
      hint: "-mente adverb from esatto. Confirms precision: è esattamente quello che pensavo.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-040",
      type: "recognize",
      prompt: "assolutamente",
      accepted: ["absolutely"],
      hint: "-mente adverb from assoluto. Strong agreement or refusal: assolutamente sì / assolutamente no.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-041",
      type: "recognize",
      prompt: "veramente",
      accepted: ["really", "truly"],
      hint: "-mente adverb from vero. Softer than assolutamente; adds emphasis without extremity.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-042",
      type: "recognize",
      prompt: "sinceramente",
      accepted: ["honestly", "sincerely"],
      hint: "-mente adverb from sincero. Often opens a sentence to signal a candid opinion: sinceramente, non mi piace.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-043",
      type: "recognize",
      prompt: "gentilmente",
      accepted: ["kindly", "politely"],
      hint: "-mente adverb from gentile. Common in polite requests: mi passi il sale, gentilmente?",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-044",
      type: "recognize",
      prompt: "attentamente",
      accepted: ["carefully", "attentively"],
      hint: "-mente adverb from attento. Pairs naturally with ascoltare and leggere: ascolta attentamente.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-045",
      type: "recognize",
      prompt: "improvvisamente",
      accepted: ["suddenly"],
      hint: "-mente adverb from improvviso. Marks an abrupt change, often opening a new narrative beat.",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-046",
      type: "recognize",
      prompt: "finalmente",
      accepted: ["finally"],
      hint: "-mente adverb from finale. Expresses relief after waiting: finalmente sei arrivato!",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-047",
      type: "recognize",
      prompt: "naturalmente",
      accepted: ["naturally", "of course"],
      hint: "-mente adverb from naturale. Often used like 'of course' to confirm something expected.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-048",
      type: "recognize",
      prompt: "ovviamente",
      accepted: ["obviously"],
      hint: "-mente adverb from ovvio. Marks a claim as self-evident, sometimes with a hint of impatience.",
      tags: ["adverb", "modal", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-049",
      type: "recognize",
      prompt: "direttamente",
      accepted: ["directly"],
      hint: "-mente adverb from diretto. Describes a straight path or straightforward manner: vai direttamente a casa.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-050",
      type: "recognize",
      prompt: "semplicemente",
      accepted: ["simply"],
      hint: "-mente adverb from semplice. Understates an action: è semplicemente perfetto.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-051",
      type: "recognize",
      prompt: "completamente",
      accepted: ["completely"],
      hint: "-mente adverb from completo. Intensifies totality: completamente d'accordo.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-052",
      type: "recognize",
      prompt: "perfettamente",
      accepted: ["perfectly"],
      hint: "-mente adverb from perfetto. Confirms an ideal outcome: capisco perfettamente.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-053",
      type: "recognize",
      prompt: "diversamente",
      accepted: ["differently", "otherwise"],
      hint: "-mente adverb from diverso. Contrasts an alternative outcome: diversamente da te, io preferisco il tè.",
      tags: ["adverb", "manner", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-054",
      type: "recognize",
      prompt: "ugualmente",
      accepted: ["equally", "all the same"],
      hint: "-mente adverb from uguale. Can mean 'equally' or, at the end of a sentence, 'all the same / anyway'.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-055",
      type: "recognize",
      prompt: "soltanto",
      accepted: ["only"],
      hint: "Synonym of solo/solamente restricting scope: ho soltanto due euro.",
      tags: ["adverb", "focus", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-056",
      type: "recognize",
      prompt: "appena",
      accepted: ["just", "barely", "as soon as"],
      hint: "Three senses: temporal ('sono appena arrivato' = I just arrived), degree ('appena sufficiente' = barely enough), conjunction ('appena arrivi, chiamami' = as soon as you arrive).",
      tags: ["adverb", "time", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-057",
      type: "recognize",
      prompt: "proprio",
      accepted: ["really", "exactly", "precisely"],
      hint: "Intensifier close to 'really/exactly': è proprio quello che volevo. Do not confuse with the possessive adjective proprio (one's own).",
      tags: ["adverb", "focus", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-058",
      type: "recognize",
      prompt: "davvero",
      accepted: ["really", "truly"],
      hint: "Confirms sincerity, often standalone as a reply: Davvero? = Really? Or intensifying: sei davvero bravo.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-059",
      type: "recognize",
      prompt: "comunque",
      accepted: ["anyway", "however", "in any case"],
      hint: "Connects ideas despite a contrast, or closes a thought: comunque, ci vediamo domani.",
      tags: ["adverb", "connector", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-060",
      type: "recognize",
      prompt: "invece",
      accepted: ["instead"],
      hint: "Marks contrast between two options: io vado al mare, lui invece resta a casa.",
      tags: ["adverb", "connector", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-061",
      type: "recognize",
      prompt: "però",
      accepted: ["however", "but", "though"],
      hint: "Softer contrast than ma; can appear mid-sentence or at the end: mi piace, però è caro.",
      tags: ["adverb", "connector", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-062",
      type: "recognize",
      prompt: "infatti",
      accepted: ["in fact", "indeed"],
      hint: "Confirms a previous statement with supporting evidence: infatti, aveva ragione lui.",
      tags: ["adverb", "connector", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-063",
      type: "recognize",
      prompt: "inoltre",
      accepted: ["moreover", "furthermore"],
      hint: "Adds a further point in formal or written register: inoltre, il prezzo include la colazione.",
      tags: ["adverb", "connector", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-064",
      type: "recognize",
      prompt: "di solito",
      accepted: ["usually"],
      hint: "Two-word frequency adverb, typically sentence-initial: di solito mi sveglio alle sette.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-065",
      type: "recognize",
      prompt: "ogni tanto",
      accepted: ["every now and then", "sometimes", "once in a while"],
      hint: "Marks irregular, occasional frequency: vado in palestra ogni tanto.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-066",
      type: "recognize",
      prompt: "qualche volta",
      accepted: ["sometimes"],
      hint: "Near-synonym of ogni tanto for occasional frequency: qualche volta cucino io.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-067",
      type: "recognize",
      prompt: "continuamente",
      accepted: ["continuously", "constantly"],
      hint: "-mente adverb from continuo. Emphasizes an action without interruption: piove continuamente.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-068",
      type: "recognize",
      prompt: "frequentemente",
      accepted: ["frequently"],
      hint: "-mente adverb from frequente. More formal register than spesso.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-069",
      type: "recognize",
      prompt: "occasionalmente",
      accepted: ["occasionally"],
      hint: "-mente adverb from occasionale. Formal synonym of ogni tanto.",
      tags: ["adverb", "frequency", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-070",
      type: "recognize",
      prompt: "tanto",
      accepted: ["so much", "a lot"],
      hint: "Degree adverb intensifying a verb or adjective: ti voglio tanto bene. Invariable in this use.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-071",
      type: "recognize",
      prompt: "così",
      accepted: ["so", "this way", "like this"],
      hint: "Degree/manner adverb: così bello = so beautiful; fai così = do it this way.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },
    {
      id: "a220-t1-072",
      type: "recognize",
      prompt: "piuttosto",
      accepted: ["rather", "quite"],
      hint: "Signals preference or moderate degree: piuttosto stanco = rather tired; preferisco piuttosto il tè al caffè.",
      tags: ["adverb", "degree", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (fill_blank) ───────────────────────────────────
    {
      id: "a220-t2-001",
      type: "fill_blank",
      prompt: "In compound tenses, già goes between the auxiliary and the past participle. Complete: Ho ___ mangiato.",
      accepted: ["già"],
      hint: "già sits between ho/hai/ha… and the past participle, not at the end.",
      tags: ["adverb", "position", "compound-tense", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-002"],
    },
    {
      id: "a220-t2-002",
      type: "fill_blank",
      prompt: "Form the 'never' construction: Non vado ___ al cinema da solo.",
      accepted: ["mai"],
      hint: "non + verb + mai = never. Both non and mai are required.",
      tags: ["adverb", "negation", "mai", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-003"],
    },
    {
      id: "a220-t2-003",
      type: "fill_blank",
      prompt: "Express 'not yet' with non and ancora: Non ho ___ finito i compiti.",
      accepted: ["ancora"],
      hint: "non + auxiliary + ancora + past participle = not yet done. ancora here means 'yet'.",
      tags: ["adverb", "negation", "ancora", "compound-tense", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-001"],
    },
    {
      id: "a220-t2-004",
      type: "fill_blank",
      prompt: "Choose già or ancora: Sei ___ andato via? — Sì, sono partito cinque minuti fa.",
      accepted: ["già"],
      hint: "già = already (action completed); ancora = still (action ongoing). Here the action is done.",
      tags: ["adverb", "già", "ancora", "contrast", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-001", "a220-t1-002"],
    },

    // ── Tier 2 – Grammar (expansion: -mente formation and placement drills) ──
    {
      id: "a220-t2-005",
      type: "fill_blank",
      prompt: "Form the adverb from the adjective lento (slow): Il treno viaggia molto ___.",
      accepted: ["lentamente"],
      hint: "Adjectives ending in -o change to -a then add -mente: lento → lenta → lentamente.",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-030"],
    },
    {
      id: "a220-t2-006",
      type: "fill_blank",
      prompt: "Form the adverb from facile (easy): Risolvo il problema ___.",
      accepted: ["facilmente"],
      hint: "Adjectives ending in -le or -re drop the final e before adding -mente: facile → facil + mente.",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-031"],
    },
    {
      id: "a220-t2-007",
      type: "fill_blank",
      prompt: "Form the adverb from veloce (fast): Il gatto corre ___ verso la porta.",
      accepted: ["velocemente"],
      hint: "Adjectives ending in -e (not -le/-re) simply add -mente: veloce + mente.",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-029"],
    },
    {
      id: "a220-t2-008",
      type: "fill_blank",
      prompt: "Transform sincero (sincere) into an adverb inserted mid-sentence: Ti dico, ___, che non mi piace il piano.",
      accepted: ["sinceramente"],
      hint: "sinceramente can be inserted mid-sentence to signal a candid opinion, set off by commas.",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-042"],
    },
    {
      id: "a220-t2-009",
      type: "fill_blank",
      prompt: "Form the adverb from chiaro (clear): Non capisco: puoi spiegare ___?",
      accepted: ["chiaramente"],
      hint: "chiaro → chiara → chiaramente, placed after the verb it modifies (spiegare).",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-032"],
    },
    {
      id: "a220-t2-010",
      type: "fill_blank",
      prompt: "Form the adverb from attento (careful): Ascolta ___ le istruzioni.",
      accepted: ["attentamente"],
      hint: "attento → attenta → attentamente, placed right after the imperative verb ascolta.",
      tags: ["adverb", "formation", "-mente", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-044"],
    },
    {
      id: "a220-t2-011",
      type: "fill_blank",
      prompt: "Insert bene or male after the verb: Marco parla italiano molto ___ (very well).",
      accepted: ["bene"],
      hint: "Manner adverbs like bene/male typically follow the verb they modify, here reinforced by molto.",
      tags: ["adverb", "position", "manner", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-025"],
    },
    {
      id: "a220-t2-012",
      type: "fill_blank",
      prompt: "Insert bene or male: Ho dormito ___ stanotte, mi fa male la schiena (badly).",
      accepted: ["male"],
      hint: "male follows the verb dormire, describing how the action went.",
      tags: ["adverb", "position", "manner", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-026"],
    },
    {
      id: "a220-t2-013",
      type: "fill_blank",
      prompt: "Reply enthusiastically to an invitation: Vieni alla festa stasera? — ___!",
      accepted: ["Volentieri", "volentieri"],
      hint: "volentieri is invariable and works as a full, enthusiastic reply on its own.",
      tags: ["adverb", "manner", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-027"],
    },
    {
      id: "a220-t2-014",
      type: "fill_blank",
      prompt: "Complete: Preferisci uscire ___, tutti e due? (together)",
      accepted: ["insieme"],
      hint: "insieme follows the verb it modifies and is invariable regardless of number or gender.",
      tags: ["adverb", "position", "manner", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-028"],
    },
    {
      id: "a220-t2-015",
      type: "fill_blank",
      prompt: "Use appena to mean 'as soon as': ___ arrivi, chiamami.",
      accepted: ["Appena", "appena"],
      hint: "appena can open a time clause meaning 'as soon as', followed by the present tense even for future meaning.",
      tags: ["adverb", "time", "appena", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-056"],
    },
    {
      id: "a220-t2-016",
      type: "fill_blank",
      prompt: "Use appena to mean 'just': Sono ___ arrivato, dammi un minuto.",
      accepted: ["appena"],
      hint: "appena between essere and the past participle marks an action just completed.",
      tags: ["adverb", "time", "appena", "compound-tense", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-056"],
    },
    {
      id: "a220-t2-017",
      type: "fill_blank",
      prompt: "Complete with tanto: Ti voglio ___ bene, sai?",
      accepted: ["tanto"],
      hint: "tanto intensifies bene here, meaning 'I love you so much'. Invariable in this idiomatic use.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-070"],
    },
    {
      id: "a220-t2-018",
      type: "fill_blank",
      prompt: "Complete with così: Non ho mai visto una vista ___ bella.",
      accepted: ["così"],
      hint: "così intensifies the adjective bella, meaning 'so beautiful', placed directly before it.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-071"],
    },
    {
      id: "a220-t2-019",
      type: "fill_blank",
      prompt: "Complete with piuttosto: Il film era ___ noioso, non l'ho finito.",
      accepted: ["piuttosto"],
      hint: "piuttosto softens a negative judgment, meaning 'rather boring', placed before the adjective.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-072"],
    },
    {
      id: "a220-t2-020",
      type: "fill_blank",
      prompt: "Complete with invece to mark contrast: Io bevo il caffè, mio fratello ___ preferisce il tè.",
      accepted: ["invece"],
      hint: "invece follows the contrasted subject, highlighting an opposite choice.",
      tags: ["adverb", "connector", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-060"],
    },
    {
      id: "a220-t2-021",
      type: "fill_blank",
      prompt: "Complete with però to soften a contrast: Il vestito è bello, ___ costa troppo.",
      accepted: ["però"],
      hint: "però can open the second clause, similar to ma but slightly softer.",
      tags: ["adverb", "connector", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-061"],
    },
    {
      id: "a220-t2-022",
      type: "fill_blank",
      prompt: "Complete with infatti to confirm a claim: Pensavo che fosse tardi, e ___ l'orologio segna le undici.",
      accepted: ["infatti"],
      hint: "infatti introduces confirming evidence for a previous statement.",
      tags: ["adverb", "connector", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-062"],
    },
    {
      id: "a220-t2-023",
      type: "fill_blank",
      prompt: "Complete with inoltre to add a formal point: Il corso è gratuito; ___, include tutti i materiali.",
      accepted: ["inoltre"],
      hint: "inoltre adds a further point, common in written or formal register.",
      tags: ["adverb", "connector", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-063"],
    },
    {
      id: "a220-t2-024",
      type: "fill_blank",
      prompt: "Complete with di solito for habitual frequency: ___ ceno alle otto, ma stasera è diverso.",
      accepted: ["Di solito", "di solito"],
      hint: "di solito is typically sentence-initial when describing a habitual routine.",
      tags: ["adverb", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-064"],
    },
    {
      id: "a220-t2-025",
      type: "fill_blank",
      prompt: "Complete with ogni tanto for irregular frequency: Non vado in palestra spesso, solo ___.",
      accepted: ["ogni tanto"],
      hint: "ogni tanto describes occasional, irregular frequency, weaker than spesso.",
      tags: ["adverb", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-065"],
    },
    {
      id: "a220-t2-026",
      type: "fill_blank",
      prompt: "Complete with qualche volta: ___ mi dimentico le chiavi di casa.",
      accepted: ["Qualche volta", "qualche volta"],
      hint: "qualche volta is a near-synonym of ogni tanto, often sentence-initial.",
      tags: ["adverb", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-066"],
    },
    {
      id: "a220-t2-027",
      type: "fill_blank",
      prompt: "Form the adverb from continuo (continuous): Il bambino piange ___, non si ferma mai.",
      accepted: ["continuamente"],
      hint: "continuo → continua → continuamente, describing an action without interruption.",
      tags: ["adverb", "formation", "-mente", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-067"],
    },
    {
      id: "a220-t2-028",
      type: "fill_blank",
      prompt: "Form the adverb from frequente (frequent), more formal than spesso: I treni sono in ritardo ___.",
      accepted: ["frequentemente"],
      hint: "frequente ends in -e, so simply add -mente: frequente + mente.",
      tags: ["adverb", "formation", "-mente", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-068"],
    },
    {
      id: "a220-t2-029",
      type: "fill_blank",
      prompt: "Form the adverb from occasionale (occasional): Lavoro da casa solo ___.",
      accepted: ["occasionalmente"],
      hint: "occasionale ends in -le, so drop the final e before adding -mente: occasional + mente.",
      tags: ["adverb", "formation", "-mente", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-069"],
    },
    {
      id: "a220-t2-030",
      type: "fill_blank",
      prompt: "Complete with proprio for emphasis: Questo è ___ il regalo che volevo.",
      accepted: ["proprio"],
      hint: "proprio intensifies 'exactly/really', placed directly before the noun phrase it emphasizes.",
      tags: ["adverb", "focus", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-057"],
    },
    {
      id: "a220-t2-031",
      type: "fill_blank",
      prompt: "Complete with davvero: Sei ___ sicuro di questa decisione?",
      accepted: ["davvero"],
      hint: "davvero intensifies the adjective sicuro, meaning 'really sure'.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-058"],
    },
    {
      id: "a220-t2-032",
      type: "fill_blank",
      prompt: "Complete with veramente: Questo libro è ___ interessante.",
      accepted: ["veramente"],
      hint: "veramente intensifies interessante, similar to davvero but slightly softer.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-041"],
    },
    {
      id: "a220-t2-033",
      type: "fill_blank",
      prompt: "Reply with a strong refusal using assolutamente: Ti piace il suo comportamento? — ___ no.",
      accepted: ["Assolutamente", "assolutamente"],
      hint: "assolutamente no is a firm, complete refusal, stronger than a plain no.",
      tags: ["adverb", "degree", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-040"],
    },
    {
      id: "a220-t2-034",
      type: "fill_blank",
      prompt: "Complete with finalmente to express relief: ___ hai finito i compiti!",
      accepted: ["Finalmente", "finalmente"],
      hint: "finalmente opens the sentence to express relief after a wait.",
      tags: ["adverb", "time", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-046"],
    },
    {
      id: "a220-t2-035",
      type: "fill_blank",
      prompt: "Complete with improvvisamente to mark a sudden change: Stava piovendo poco, poi, ___, è arrivato un temporale.",
      accepted: ["improvvisamente"],
      hint: "improvvisamente marks an abrupt shift, often placed mid-sentence after poi.",
      tags: ["adverb", "time", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-045"],
    },
    {
      id: "a220-t2-036",
      type: "fill_blank",
      prompt: "Complete with ovviamente to mark something self-evident: ___, non potevo dire di no.",
      accepted: ["Ovviamente", "ovviamente"],
      hint: "ovviamente opens the sentence, framing the claim as self-evident.",
      tags: ["adverb", "modal", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-048"],
    },
    {
      id: "a220-t2-037",
      type: "fill_blank",
      prompt: "Complete with soltanto to restrict scope: Ho ___ due euro nel portafoglio.",
      accepted: ["soltanto"],
      hint: "soltanto restricts scope like solo/solamente, placed directly before the quantity.",
      tags: ["adverb", "focus", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-055"],
    },
    {
      id: "a220-t2-038",
      type: "fill_blank",
      prompt: "Complete with diversamente to contrast an alternative: ___ da te, io non mangio la carne.",
      accepted: ["Diversamente", "diversamente"],
      hint: "diversamente da + person contrasts one person's behavior with another's, sentence-initial.",
      tags: ["adverb", "manner", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-053"],
    },
    {
      id: "a220-t2-039",
      type: "fill_blank",
      prompt: "Complete with generalmente to frame a general truth: ___, i negozi chiudono presto la domenica, ma oggi sono aperti.",
      accepted: ["Generalmente", "generalmente"],
      hint: "generalmente is sentence-initial here, framing a general rule before the following exception.",
      tags: ["adverb", "frequency", "A2"],
      tier: 2,
      prerequisites: ["a220-t1-035"],
    },

    // ── Tier 3 – Sentence Production (eng_to_ita) ───────────────────────
    {
      id: "a220-t3-001",
      type: "produce",
      prompt: "I have already eaten.",
      accepted: [
        "Ho già mangiato.",
        "ho già mangiato.",
        "Ho già mangiato",
        "ho già mangiato",
      ],
      hint: "già between auxiliary and past participle",
      tags: ["sentence", "già", "compound-tense", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-002", "a220-t2-001"],
    },
    {
      id: "a220-t3-002",
      type: "produce",
      prompt: "She has never been to Rome.",
      accepted: [
        "Non è mai stata a Roma.",
        "non è mai stata a Roma.",
        "Non è mai stata a Roma",
        "non è mai stata a Roma",
      ],
      hint: "non + essere (compound) + mai + past participle (stata for lei)",
      tags: ["sentence", "mai", "negation", "compound-tense", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-003", "a220-t2-002"],
    },
    {
      id: "a220-t3-003",
      type: "produce",
      prompt: "We haven't finished yet.",
      accepted: [
        "Non abbiamo ancora finito.",
        "non abbiamo ancora finito.",
        "Non abbiamo ancora finito",
        "non abbiamo ancora finito",
      ],
      hint: "non + auxiliary + ancora + past participle",
      tags: ["sentence", "ancora", "negation", "compound-tense", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-001", "a220-t2-003"],
    },
    {
      id: "a220-t3-004",
      type: "produce",
      prompt: "Unfortunately, I can't come.",
      accepted: [
        "Purtroppo, non posso venire.",
        "purtroppo, non posso venire.",
        "Purtroppo non posso venire.",
        "purtroppo non posso venire.",
        "Purtroppo, non posso venire",
        "Purtroppo non posso venire",
      ],
      hint: "purtroppo opens the sentence; non + potere + infinitive",
      tags: ["sentence", "purtroppo", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-023"],
    },
    {
      id: "a220-t3-005",
      type: "produce",
      prompt: "Even the teacher made a mistake.",
      accepted: [
        "Perfino il professore ha fatto un errore.",
        "perfino il professore ha fatto un errore.",
        "Perfino il professore ha fatto un errore",
        "perfino il professore ha fatto un errore",
        "Perfino la professoressa ha fatto un errore.",
        "perfino la professoressa ha fatto un errore.",
        "Perfino la professoressa ha fatto un errore",
        "perfino la professoressa ha fatto un errore",
        "Persino il professore ha fatto un errore.",
        "Persino il professore ha fatto un errore",
      ],
      hint: "perfino/persino + subject highlights surprise; fare un errore = to make a mistake",
      tags: ["sentence", "perfino", "focus", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-024"],
    },

    // ── Tier 3 – Sentence Production (expansion) ─────────────────────────
    {
      id: "a220-t3-006",
      type: "produce",
      prompt: "My grandmother cooks very well.",
      accepted: [
        "Mia nonna cucina molto bene.",
        "mia nonna cucina molto bene.",
        "Mia nonna cucina molto bene",
        "mia nonna cucina molto bene",
      ],
      hint: "bene follows the verb cucina; molto intensifies bene",
      tags: ["sentence", "bene", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-025"],
    },
    {
      id: "a220-t3-007",
      type: "produce",
      prompt: "The team played badly, but we still won.",
      accepted: [
        "La squadra ha giocato male, ma abbiamo vinto lo stesso.",
        "la squadra ha giocato male, ma abbiamo vinto lo stesso.",
        "La squadra ha giocato male, ma abbiamo vinto lo stesso",
        "la squadra ha giocato male, ma abbiamo vinto lo stesso",
      ],
      hint: "giocare male = to play badly; male follows the verb",
      tags: ["sentence", "male", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-026"],
    },
    {
      id: "a220-t3-008",
      type: "produce",
      prompt: "Yes, gladly, I'll help you move.",
      accepted: [
        "Sì, volentieri, ti aiuto a traslocare.",
        "sì, volentieri, ti aiuto a traslocare.",
        "Sì, volentieri, ti aiuto a traslocare",
        "sì, volentieri, ti aiuto a traslocare",
      ],
      hint: "volentieri marks enthusiastic agreement, set off by commas",
      tags: ["sentence", "volentieri", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-027"],
    },
    {
      id: "a220-t3-009",
      type: "produce",
      prompt: "We always study together in the library.",
      accepted: [
        "Studiamo sempre insieme in biblioteca.",
        "studiamo sempre insieme in biblioteca.",
        "Studiamo sempre insieme in biblioteca",
        "studiamo sempre insieme in biblioteca",
      ],
      hint: "insieme follows the verb; sempre reinforces the habitual frequency",
      tags: ["sentence", "insieme", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-028"],
    },
    {
      id: "a220-t3-010",
      type: "produce",
      prompt: "The waiter answered very quickly.",
      accepted: [
        "Il cameriere ha risposto molto velocemente.",
        "il cameriere ha risposto molto velocemente.",
        "Il cameriere ha risposto molto velocemente",
        "il cameriere ha risposto molto velocemente",
      ],
      hint: "velocemente follows the past participle risposto",
      tags: ["sentence", "velocemente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-029"],
    },
    {
      id: "a220-t3-011",
      type: "produce",
      prompt: "Grandpa walks slowly but never stops.",
      accepted: [
        "Il nonno cammina lentamente ma non si ferma mai.",
        "il nonno cammina lentamente ma non si ferma mai.",
        "Il nonno cammina lentamente ma non si ferma mai",
        "il nonno cammina lentamente ma non si ferma mai",
      ],
      hint: "lentamente follows cammina; non + fermarsi + mai = never stops",
      tags: ["sentence", "lentamente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-030"],
    },
    {
      id: "a220-t3-012",
      type: "produce",
      prompt: "This exercise can be solved easily.",
      accepted: [
        "Questo esercizio si risolve facilmente.",
        "questo esercizio si risolve facilmente.",
        "Questo esercizio si risolve facilmente",
        "questo esercizio si risolve facilmente",
      ],
      hint: "facilmente follows the reflexive verb si risolve",
      tags: ["sentence", "facilmente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-031"],
    },
    {
      id: "a220-t3-013",
      type: "produce",
      prompt: "The teacher explained the rule clearly.",
      accepted: [
        "L'insegnante ha spiegato la regola chiaramente.",
        "l'insegnante ha spiegato la regola chiaramente.",
        "L'insegnante ha spiegato la regola chiaramente",
        "l'insegnante ha spiegato la regola chiaramente",
      ],
      hint: "chiaramente typically follows the object of the verb spiegare",
      tags: ["sentence", "chiaramente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-032"],
    },
    {
      id: "a220-t3-014",
      type: "produce",
      prompt: "I will surely call you tomorrow.",
      accepted: [
        "Ti chiamerò sicuramente domani.",
        "ti chiamerò sicuramente domani.",
        "Ti chiamerò sicuramente domani",
        "ti chiamerò sicuramente domani",
      ],
      hint: "sicuramente can follow the verb, before the time expression domani",
      tags: ["sentence", "sicuramente", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-033"],
    },
    {
      id: "a220-t3-015",
      type: "produce",
      prompt: "It will probably rain this afternoon.",
      accepted: [
        "Probabilmente pioverà nel pomeriggio.",
        "probabilmente pioverà nel pomeriggio.",
        "Probabilmente pioverà nel pomeriggio",
        "probabilmente pioverà nel pomeriggio",
      ],
      hint: "probabilmente opens the sentence, before the future tense verb",
      tags: ["sentence", "probabilmente", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-034"],
    },
    {
      id: "a220-t3-016",
      type: "produce",
      prompt: "Generally, shops close at eight in the evening.",
      accepted: [
        "Generalmente i negozi chiudono alle otto di sera.",
        "generalmente i negozi chiudono alle otto di sera.",
        "Generalmente i negozi chiudono alle otto di sera",
        "generalmente i negozi chiudono alle otto di sera",
      ],
      hint: "generalmente opens the sentence to frame a general truth",
      tags: ["sentence", "generalmente", "frequency", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-035"],
    },
    {
      id: "a220-t3-017",
      type: "produce",
      prompt: "I normally wake up before seven.",
      accepted: [
        "Normalmente mi sveglio prima delle sette.",
        "normalmente mi sveglio prima delle sette.",
        "Normalmente mi sveglio prima delle sette",
        "normalmente mi sveglio prima delle sette",
      ],
      hint: "normalmente opens the sentence, before the reflexive verb svegliarsi",
      tags: ["sentence", "normalmente", "frequency", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-036"],
    },
    {
      id: "a220-t3-018",
      type: "produce",
      prompt: "I love fruit, especially strawberries.",
      accepted: [
        "Adoro la frutta, specialmente le fragole.",
        "adoro la frutta, specialmente le fragole.",
        "Adoro la frutta, specialmente le fragole",
        "adoro la frutta, specialmente le fragole",
      ],
      hint: "specialmente introduces the singled-out example after a comma",
      tags: ["sentence", "specialmente", "focus", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-037"],
    },
    {
      id: "a220-t3-019",
      type: "produce",
      prompt: "This year has been particularly difficult.",
      accepted: [
        "Quest'anno è stato particolarmente difficile.",
        "quest'anno è stato particolarmente difficile.",
        "Quest'anno è stato particolarmente difficile",
        "quest'anno è stato particolarmente difficile",
      ],
      hint: "particolarmente precedes the adjective difficile",
      tags: ["sentence", "particolarmente", "focus", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-038"],
    },
    {
      id: "a220-t3-020",
      type: "produce",
      prompt: "That's exactly what I meant.",
      accepted: [
        "Questo è esattamente quello che intendevo.",
        "questo è esattamente quello che intendevo.",
        "Questo è esattamente quello che intendevo",
        "questo è esattamente quello che intendevo",
      ],
      hint: "esattamente precedes quello che, confirming precision",
      tags: ["sentence", "esattamente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-039"],
    },
    {
      id: "a220-t3-021",
      type: "produce",
      prompt: "This trip is absolutely worth it.",
      accepted: [
        "Questo viaggio vale assolutamente la pena.",
        "questo viaggio vale assolutamente la pena.",
        "Questo viaggio vale assolutamente la pena",
        "questo viaggio vale assolutamente la pena",
      ],
      hint: "assolutamente sits between the verb vale and the object la pena",
      tags: ["sentence", "assolutamente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-040"],
    },
    {
      id: "a220-t3-022",
      type: "produce",
      prompt: "This soup is really good.",
      accepted: [
        "Questa zuppa è veramente buona.",
        "questa zuppa è veramente buona.",
        "Questa zuppa è veramente buona",
        "questa zuppa è veramente buona",
      ],
      hint: "veramente precedes the adjective buona",
      tags: ["sentence", "veramente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-041"],
    },
    {
      id: "a220-t3-023",
      type: "produce",
      prompt: "Honestly, I don't understand his choice.",
      accepted: [
        "Sinceramente, non capisco la sua scelta.",
        "sinceramente, non capisco la sua scelta.",
        "Sinceramente, non capisco la sua scelta",
        "sinceramente, non capisco la sua scelta",
      ],
      hint: "sinceramente opens the sentence, set off by a comma",
      tags: ["sentence", "sinceramente", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-042"],
    },
    {
      id: "a220-t3-024",
      type: "produce",
      prompt: "Could you kindly close the window?",
      accepted: [
        "Potresti chiudere gentilmente la finestra?",
        "potresti chiudere gentilmente la finestra?",
        "Potresti chiudere gentilmente la finestra",
        "potresti chiudere gentilmente la finestra",
      ],
      hint: "gentilmente softens the request, placed after the infinitive chiudere",
      tags: ["sentence", "gentilmente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-043"],
    },
    {
      id: "a220-t3-025",
      type: "produce",
      prompt: "Read the contract carefully before signing.",
      accepted: [
        "Leggi il contratto attentamente prima di firmare.",
        "leggi il contratto attentamente prima di firmare.",
        "Leggi il contratto attentamente prima di firmare",
        "leggi il contratto attentamente prima di firmare",
      ],
      hint: "attentamente follows the object il contratto; prima di + infinitive = before doing something",
      tags: ["sentence", "attentamente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-044"],
    },
    {
      id: "a220-t3-026",
      type: "produce",
      prompt: "Suddenly the lights went out.",
      accepted: [
        "Improvvisamente le luci si sono spente.",
        "improvvisamente le luci si sono spente.",
        "Improvvisamente le luci si sono spente",
        "improvvisamente le luci si sono spente",
      ],
      hint: "improvvisamente opens the sentence to mark the abrupt event",
      tags: ["sentence", "improvvisamente", "time", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-045"],
    },
    {
      id: "a220-t3-027",
      type: "produce",
      prompt: "Finally the exam is over.",
      accepted: [
        "Finalmente l'esame è finito.",
        "finalmente l'esame è finito.",
        "Finalmente l'esame è finito",
        "finalmente l'esame è finito",
      ],
      hint: "finalmente opens the sentence to express relief",
      tags: ["sentence", "finalmente", "time", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-046"],
    },
    {
      id: "a220-t3-028",
      type: "produce",
      prompt: "Naturally, we will help each other.",
      accepted: [
        "Naturalmente ci aiuteremo a vicenda.",
        "naturalmente ci aiuteremo a vicenda.",
        "Naturalmente ci aiuteremo a vicenda",
        "naturalmente ci aiuteremo a vicenda",
      ],
      hint: "naturalmente opens the sentence, confirming an expected outcome",
      tags: ["sentence", "naturalmente", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-047"],
    },
    {
      id: "a220-t3-029",
      type: "produce",
      prompt: "Obviously the plan needs some changes.",
      accepted: [
        "Ovviamente il piano ha bisogno di qualche modifica.",
        "ovviamente il piano ha bisogno di qualche modifica.",
        "Ovviamente il piano ha bisogno di qualche modifica",
        "ovviamente il piano ha bisogno di qualche modifica",
      ],
      hint: "ovviamente opens the sentence, framing the claim as self-evident",
      tags: ["sentence", "ovviamente", "modal", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-048"],
    },
    {
      id: "a220-t3-030",
      type: "produce",
      prompt: "You can write directly to the director.",
      accepted: [
        "Puoi scrivere direttamente al direttore.",
        "puoi scrivere direttamente al direttore.",
        "Puoi scrivere direttamente al direttore",
        "puoi scrivere direttamente al direttore",
      ],
      hint: "direttamente follows the infinitive scrivere",
      tags: ["sentence", "direttamente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-049"],
    },
    {
      id: "a220-t3-031",
      type: "produce",
      prompt: "The recipe is simply delicious.",
      accepted: [
        "La ricetta è semplicemente deliziosa.",
        "la ricetta è semplicemente deliziosa.",
        "La ricetta è semplicemente deliziosa",
        "la ricetta è semplicemente deliziosa",
      ],
      hint: "semplicemente precedes the adjective deliziosa",
      tags: ["sentence", "semplicemente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-050"],
    },
    {
      id: "a220-t3-032",
      type: "produce",
      prompt: "I completely forgot the appointment.",
      accepted: [
        "Ho completamente dimenticato l'appuntamento.",
        "ho completamente dimenticato l'appuntamento.",
        "Ho completamente dimenticato l'appuntamento",
        "ho completamente dimenticato l'appuntamento",
      ],
      hint: "completamente slots between the auxiliary ho and the past participle dimenticato",
      tags: ["sentence", "completamente", "degree", "compound-tense", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-051"],
    },
    {
      id: "a220-t3-033",
      type: "produce",
      prompt: "I understand your point of view perfectly.",
      accepted: [
        "Capisco perfettamente il tuo punto di vista.",
        "capisco perfettamente il tuo punto di vista.",
        "Capisco perfettamente il tuo punto di vista",
        "capisco perfettamente il tuo punto di vista",
      ],
      hint: "perfettamente follows the verb capisco",
      tags: ["sentence", "perfettamente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-052"],
    },
    {
      id: "a220-t3-034",
      type: "produce",
      prompt: "Unlike you, I prefer the mountains to the sea.",
      accepted: [
        "Diversamente da te, preferisco la montagna al mare.",
        "diversamente da te, preferisco la montagna al mare.",
        "Diversamente da te, preferisco la montagna al mare",
        "diversamente da te, preferisco la montagna al mare",
      ],
      hint: "diversamente da + person opens the sentence to contrast a preference",
      tags: ["sentence", "diversamente", "manner", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-053"],
    },
    {
      id: "a220-t3-035",
      type: "produce",
      prompt: "I don't agree, but I'll come anyway.",
      accepted: [
        "Non sono d'accordo, ma vengo ugualmente.",
        "non sono d'accordo, ma vengo ugualmente.",
        "Non sono d'accordo, ma vengo ugualmente",
        "non sono d'accordo, ma vengo ugualmente",
      ],
      hint: "ugualmente closes the sentence, meaning 'all the same / anyway'",
      tags: ["sentence", "ugualmente", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-054"],
    },
    {
      id: "a220-t3-036",
      type: "produce",
      prompt: "I have only ten minutes left.",
      accepted: [
        "Mi restano soltanto dieci minuti.",
        "mi restano soltanto dieci minuti.",
        "Mi restano soltanto dieci minuti",
        "mi restano soltanto dieci minuti",
      ],
      hint: "soltanto precedes the quantity dieci minuti",
      tags: ["sentence", "soltanto", "focus", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-055"],
    },
    {
      id: "a220-t3-037",
      type: "produce",
      prompt: "I have barely enough money for the ticket.",
      accepted: [
        "Ho appena abbastanza soldi per il biglietto.",
        "ho appena abbastanza soldi per il biglietto.",
        "Ho appena abbastanza soldi per il biglietto",
        "ho appena abbastanza soldi per il biglietto",
      ],
      hint: "appena here expresses degree (barely), placed directly before abbastanza",
      tags: ["sentence", "appena", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-056", "a220-t1-019"],
    },
    {
      id: "a220-t3-038",
      type: "produce",
      prompt: "This restaurant is exactly what I was looking for.",
      accepted: [
        "Questo ristorante è proprio quello che cercavo.",
        "questo ristorante è proprio quello che cercavo.",
        "Questo ristorante è proprio quello che cercavo",
        "questo ristorante è proprio quello che cercavo",
      ],
      hint: "proprio precedes quello che, intensifying the match",
      tags: ["sentence", "proprio", "focus", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-057"],
    },
    {
      id: "a220-t3-039",
      type: "produce",
      prompt: "Are you really leaving tomorrow?",
      accepted: [
        "Parti davvero domani?",
        "parti davvero domani?",
        "Parti davvero domani",
        "parti davvero domani",
      ],
      hint: "davvero follows the verb parti, before the time expression domani",
      tags: ["sentence", "davvero", "degree", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-058"],
    },
    {
      id: "a220-t3-040",
      type: "produce",
      prompt: "It's raining, but we'll go for a walk anyway.",
      accepted: [
        "Piove, ma usciamo comunque a fare una passeggiata.",
        "piove, ma usciamo comunque a fare una passeggiata.",
        "Piove, ma usciamo comunque a fare una passeggiata",
        "piove, ma usciamo comunque a fare una passeggiata",
      ],
      hint: "comunque follows the verb usciamo, meaning 'anyway / regardless'",
      tags: ["sentence", "comunque", "connector", "A2"],
      tier: 3,
      prerequisites: ["a220-t1-059"],
    },

    // ── Tier 4 – Passage Cloze ───────────────────────────────────────────
    {
      id: "a220-t4-001",
      type: "passage_cloze",
      prompt:
        "Stamattina mi sono alzato tardi. Purtroppo ho perso il treno e sono arrivato in ufficio quasi alle dieci. Fortunatamente il mio capo non era ancora arrivato. Ho acceso il computer piano piano per non fare rumore. Forse i colleghi non hanno sentito niente. Ho aperto la posta elettronica e ho visto che il capo aveva ___ scritto un messaggio alle nove.",
      accepted: ["già"],
      hint: "The blank is in a compound tense (aveva + ___  + scritto). The adverb goes between the auxiliary and the past participle and expresses that the action was completed before another past moment.",
      tags: ["passage_cloze", "già", "compound-tense", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-001",
        "a220-t1-002",
        "a220-t1-007",
        "a220-t1-015",
        "a220-t1-016",
        "a220-t1-021",
        "a220-t1-023",
        "a220-t1-025",
        "a220-t2-001",
        "a220-t2-004",
      ],
    },

    // ── Tier 4 – Passage Cloze (expansion) ────────────────────────────────
    {
      id: "a220-t4-002",
      type: "passage_cloze",
      prompt:
        "Ogni mattina mi alzo presto e vado in palestra prima di andare al lavoro. Di solito arrivo in ufficio verso le otto e mezza. Oggi però il traffico era terribile e sono arrivato quasi in ritardo. Ho aspettato l'ascensore per dieci minuti, ma non si muoveva. Ho deciso di salire le scale velocemente, anche se erano sei piani. Ero completamente senza fiato quando sono arrivato alla mia scrivania. ___, il capo non aveva ancora notato il ritardo, e la giornata è cominciata normalmente.",
      accepted: ["Comunque", "comunque"],
      hint: "The blank opens the final sentence, connecting the tiring climb to a reassuring outcome. comunque here means 'anyway / in any case' and typically opens a sentence that closes a small drama.",
      tags: ["passage_cloze", "comunque", "connector", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-001",
        "a220-t1-029",
        "a220-t1-036",
        "a220-t1-051",
        "a220-t1-059",
        "a220-t1-064",
      ],
    },
    {
      id: "a220-t4-003",
      type: "passage_cloze",
      prompt:
        "Il sabato mattina di solito dormo fino a tardi, ma oggi mi sono svegliata presto senza motivo. Vado quasi sempre al mercato con mia sorella, anche se lei si lamenta sempre del prezzo della frutta. Raramente compriamo il pesce, perché non sappiamo cucinarlo bene. ___ però proviamo una ricetta nuova, e stavolta il risultato è stato sorprendentemente buono.",
      accepted: ["Ogni tanto", "ogni tanto"],
      hint: "The blank opens the last sentence, marking an irregular exception after raramente in the previous sentence. ogni tanto describes occasional frequency, weaker in regularity than sempre but stronger than raramente's near-absence.",
      tags: ["passage_cloze", "ogni tanto", "frequency", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-004",
        "a220-t1-006",
        "a220-t1-016",
        "a220-t1-025",
        "a220-t1-064",
        "a220-t1-065",
      ],
    },
    {
      id: "a220-t4-004",
      type: "passage_cloze",
      prompt:
        "Quando studio per un esame, cerco di leggere ogni pagina lentamente, senza saltare le parti difficili. Sottolineo le frasi importanti e provo a spiegarle chiaramente a voce alta, come se insegnassi a qualcuno. All'inizio sembra tutto complicato, ma dopo qualche ripetizione capisco le cose più facilmente. La professoressa dice sempre che bisogna leggere ___ le domande dell'esame, perché un errore di distrazione costa punti preziosi.",
      accepted: ["attentamente"],
      hint: "The blank follows the infinitive leggere and precedes its object le domande dell'esame. The adverb needed emphasizes careful, attentive reading, matching the passage's warning about distraction.",
      tags: ["passage_cloze", "attentamente", "manner", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-004",
        "a220-t1-030",
        "a220-t1-031",
        "a220-t1-032",
        "a220-t1-044",
      ],
    },
    {
      id: "a220-t4-005",
      type: "passage_cloze",
      prompt:
        "Ieri sera eravamo seduti in cucina a parlare del più e del meno, tranquilli come sempre. ___, qualcuno ha bussato alla porta con forza. Ci siamo guardati sorpresi: non aspettavamo nessuno. Ho aperto piano piano, pronta a tutto, ma era soltanto il vicino che cercava il suo gatto. Alla fine abbiamo riso tutti insieme, sollevati che non fosse davvero un'emergenza.",
      accepted: ["Improvvisamente", "improvvisamente"],
      hint: "The blank opens the second sentence, marking the abrupt interruption of a calm scene. improvvisamente is the standard narrative marker for a sudden, unexpected event.",
      tags: ["passage_cloze", "improvvisamente", "time", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-004",
        "a220-t1-021",
        "a220-t1-028",
        "a220-t1-045",
        "a220-t1-055",
        "a220-t1-058",
      ],
    },
    {
      id: "a220-t4-006",
      type: "passage_cloze",
      prompt:
        "Gentile signora Bianchi, la ringrazio sinceramente per la sua pazienza durante questi mesi di lavori in ufficio. Il progetto procede bene, anche se abbiamo avuto qualche ritardo dovuto ai materiali. Infatti, il fornitore ci ha comunicato solo ieri la data di consegna definitiva. ___, vorrei informarla che la riunione di venerdì è stata spostata alle undici. Resto a disposizione per qualsiasi chiarimento.",
      accepted: ["Inoltre", "inoltre"],
      hint: "The blank opens a new formal point after the explanation introduced by Infatti. inoltre adds a further, separate item in written or professional register, distinct from confirming evidence.",
      tags: ["passage_cloze", "inoltre", "connector", "adverb-position", "A2"],
      tier: 4,
      prerequisites: [
        "a220-t1-025",
        "a220-t1-042",
        "a220-t1-062",
        "a220-t1-063",
      ],
    },
  ],
};
export default unit;
