import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-21-verbs-ii",
  name: "Essential Verbs II",
  level: "A2",
  theme: "High-Frequency Action Verbs",
  emoji: "🎯",
  prerequisiteUnits: ["a2-unit-20-adverbs"],
  cards: [
    // ── Tier 1 – Vocabulary (verbs as lexical items) ─────────────────────────
    {
      id: "a221-t1-001",
      type: "produce",
      prompt: "to buy (infinitive)",
      accepted: ["comprare"],
      hint: "regular -are verb",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-002",
      type: "produce",
      prompt: "to sell (infinitive)",
      accepted: ["vendere"],
      hint: "regular -ere verb",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-003",
      type: "produce",
      prompt: "to open (infinitive)",
      accepted: ["aprire"],
      hint: "regular -ire verb; past participle: aperto (irregular)",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-004",
      type: "produce",
      prompt: "to close (infinitive)",
      accepted: ["chiudere"],
      hint: "past participle: chiuso (irregular)",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-005",
      type: "produce",
      prompt: "to find (infinitive)",
      accepted: ["trovare"],
      hint: "regular -are verb; also means 'to think / consider'",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-006",
      type: "recognize",
      prompt: "perdere",
      accepted: ["to lose", "to miss", "to waste"],
      hint: "past participle: perso or perduto",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-007",
      type: "produce",
      prompt: "to remember (infinitive)",
      accepted: ["ricordare"],
      hint: "regular -are verb; also ricordarsi (reflexive)",
      tags: ["verb", "memory", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-008",
      type: "recognize",
      prompt: "dimenticare",
      accepted: ["to forget"],
      hint: "also dimentarsi (reflexive) — both are common",
      tags: ["verb", "memory", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-009",
      type: "recognize",
      prompt: "sperare",
      accepted: ["to hope"],
      hint: "followed by 'di + infinitive' or 'che + subjunctive'",
      tags: ["verb", "feeling", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-010",
      type: "recognize",
      prompt: "credere",
      accepted: ["to believe", "to think", "to trust"],
      hint: "credere a qualcuno = to believe someone",
      tags: ["verb", "cognition", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-011",
      type: "produce",
      prompt: "to hear / to feel / to listen (infinitive)",
      accepted: ["sentire"],
      hint: "context decides: sentire un rumore = hear a noise; sentirsi = to feel (reflexive)",
      tags: ["verb", "perception", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-012",
      type: "recognize",
      prompt: "cambiare",
      accepted: ["to change", "to exchange", "to switch"],
      hint: "regular -are verb; cambiare idea = to change one's mind",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-013",
      type: "recognize",
      prompt: "diventare",
      accepted: ["to become"],
      hint: "takes essere in passato prossimo: sono diventato/a",
      tags: ["verb", "change", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-014",
      type: "recognize",
      prompt: "succedere",
      accepted: ["to happen", "to occur"],
      hint: "impersonal use is common: cosa è successo? — what happened?",
      tags: ["verb", "event", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-015",
      type: "produce",
      prompt: "to choose (infinitive)",
      accepted: ["scegliere"],
      hint: "irregular; past participle: scelto",
      tags: ["verb", "decision", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-016",
      type: "produce",
      prompt: "to decide (infinitive)",
      accepted: ["decidere"],
      hint: "past participle: deciso; followed by 'di + infinitive'",
      tags: ["verb", "decision", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-017",
      type: "recognize",
      prompt: "smettere",
      accepted: ["to stop (doing something)", "to quit", "to stop"],
      hint: "smettere di + infinitive: smetto di fumare — I'm quitting smoking",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-018",
      type: "recognize",
      prompt: "provare",
      accepted: ["to try", "to attempt", "to prove", "to test"],
      hint: "most commonly 'to try'; provare a + infinitive",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-019",
      type: "produce",
      prompt: "to help (infinitive)",
      accepted: ["aiutare"],
      hint: "regular -are verb; aiutare qualcuno a fare qualcosa",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },
    {
      id: "a221-t1-020",
      type: "produce",
      prompt: "to bring / to carry / to take (infinitive)",
      accepted: ["portare"],
      hint: "regular -are verb; portare also means 'to wear' with clothing",
      tags: ["verb", "action", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Fill Blank (passato prossimo or presente in context) ─────────
    {
      id: "a221-t2-001",
      type: "fill_blank",
      prompt: "Ieri Marco ___ le chiavi di casa e ha dovuto chiamare il fabbro. (perdere — passato prossimo)",
      accepted: ["ha perso", "ha perduto"],
      hint: "perdere uses avere in passato prossimo; past participle: perso",
      tags: ["verb", "passato prossimo", "A2"],
      tier: 2,
      prerequisites: ["a221-t1-006"],
    },
    {
      id: "a221-t2-002",
      type: "fill_blank",
      prompt: "Dopo tanti anni di lavoro noiosi, Anna ___ medico. (diventare — passato prossimo)",
      accepted: ["è diventata"],
      hint: "diventare uses essere in passato prossimo; agree with feminine subject",
      tags: ["verb", "passato prossimo", "essere", "A2"],
      tier: 2,
      prerequisites: ["a221-t1-013"],
    },
    {
      id: "a221-t2-003",
      type: "fill_blank",
      prompt: "Scusa, non ___ il tuo compleanno! Ti faccio tanti auguri lo stesso. (dimenticare — passato prossimo)",
      accepted: ["ho dimenticato"],
      hint: "dimenticare uses avere in passato prossimo",
      tags: ["verb", "passato prossimo", "A2"],
      tier: 2,
      prerequisites: ["a221-t1-008"],
    },
    {
      id: "a221-t2-004",
      type: "fill_blank",
      prompt: "Alla fine ___ di andare in vacanza in Sardegna invece che in Sicilia. (decidere — passato prossimo)",
      accepted: ["abbiamo deciso", "hanno deciso", "ho deciso"],
      hint: "decidere uses avere; past participle: deciso",
      tags: ["verb", "passato prossimo", "A2"],
      tier: 2,
      prerequisites: ["a221-t1-016"],
    },

    // ── Tier 3 – Sentence Production ─────────────────────────────────────────
    {
      id: "a221-t3-001",
      type: "produce",
      prompt: "I can't find my keys.",
      accepted: [
        "Non trovo le mie chiavi.",
        "Non riesco a trovare le mie chiavi.",
        "Non trovo le chiavi.",
      ],
      hint: "'trovare' in presente; 'mie' is optional when context is clear",
      tags: ["verb", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a221-t1-005"],
    },
    {
      id: "a221-t3-002",
      type: "produce",
      prompt: "She decided to stay.",
      accepted: [
        "Ha deciso di restare.",
        "Ha deciso di rimanere.",
        "Lei ha deciso di restare.",
        "Lei ha deciso di rimanere.",
      ],
      hint: "decidere + di + infinitive; passato prossimo with avere",
      tags: ["verb", "sentence", "passato prossimo", "A2"],
      tier: 3,
      prerequisites: ["a221-t1-016", "a221-t2-004"],
    },
    {
      id: "a221-t3-003",
      type: "produce",
      prompt: "Help me please!",
      accepted: [
        "Aiutami, per favore!",
        "Aiutami per favore!",
        "Mi aiuti, per favore!",
        "Mi aiuta, per favore!",
      ],
      hint: "imperative of aiutare; 'mi' can be enclitic (aiutami) or pre-verbal",
      tags: ["verb", "imperative", "A2"],
      tier: 3,
      prerequisites: ["a221-t1-019"],
    },
    {
      id: "a221-t3-004",
      type: "produce",
      prompt: "He forgot her birthday.",
      accepted: [
        "Ha dimenticato il suo compleanno.",
        "Lui ha dimenticato il suo compleanno.",
        "Si è dimenticato del suo compleanno.",
        "Lui si è dimenticato del suo compleanno.",
      ],
      hint: "dimenticare (avere) or dimentarsi (essere + reflexive); 'il suo' for 'her' with compleanno",
      tags: ["verb", "sentence", "passato prossimo", "A2"],
      tier: 3,
      prerequisites: ["a221-t1-008", "a221-t2-003"],
    },
    {
      id: "a221-t3-005",
      type: "produce",
      prompt: "I hope to see you soon.",
      accepted: [
        "Spero di vederti presto.",
        "Spero di vederLa presto.",
        "Spero di rivederti presto.",
      ],
      hint: "sperare di + infinitive; 'ti' (informal) or 'La' (formal) attached to the infinitive",
      tags: ["verb", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a221-t1-009"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a221-t4-001",
      type: "passage_cloze",
      prompt: "Stamattina mi sono svegliato tardi e non riuscivo a trovare le chiavi. Le ho cercate dappertutto — ho aperto tutti i cassetti, ho chiuso e riaperto la borsa tre volte — ma niente. Alla fine mia sorella mi ha aiutato: le ha trovate sotto il divano!\nMentre cercavo, ho deciso di ___ di correre la mattina: mi fa perdere troppo tempo. Mia sorella invece dice che devo provare a essere più organizzato.",
      accepted: ["smettere"],
      hint: "decide 'to stop doing' something — decidere di ___ di + infinitive",
      tags: ["verb", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: [
        "a221-t1-003",
        "a221-t1-004",
        "a221-t1-005",
        "a221-t1-006",
        "a221-t1-016",
        "a221-t1-017",
        "a221-t1-018",
        "a221-t1-019",
        "a221-t2-001",
        "a221-t2-004",
      ],
    },
  ],
};
export default unit;
