import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-22-professions",
  name: "Professions",
  level: "A2",
  theme: "Jobs & Careers",
  emoji: "👩‍⚕️",
  prerequisiteUnits: ["a2-unit-21-verbs-ii"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a222-t1-001",
      type: "recognize",
      prompt: "il medico / la dottoressa",
      accepted: ["the doctor", "doctor"],
      hint: "'il medico' is used for both genders in formal contexts; 'la dottoressa' for a female doctor",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-002",
      type: "recognize",
      prompt: "l'infermiere / l'infermiera",
      accepted: ["the nurse", "nurse"],
      hint: "male: l'infermiere — female: l'infermiera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-003",
      type: "recognize",
      prompt: "l'insegnante",
      accepted: ["the teacher", "teacher"],
      hint: "invariable — same form for male and female; use 'il/la' to show gender",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-004",
      type: "recognize",
      prompt: "l'avvocato / l'avvocatessa",
      accepted: ["the lawyer", "the solicitor", "the attorney", "lawyer"],
      hint: "male: l'avvocato — female: l'avvocatessa (though 'l'avvocato' is also used for women in formal contexts)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-005",
      type: "recognize",
      prompt: "l'ingegnere",
      accepted: ["the engineer", "engineer"],
      hint: "invariable form; female: l'ingegnera (informal) or l'ingegnere",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-006",
      type: "recognize",
      prompt: "l'architetto / l'architetta",
      accepted: ["the architect", "architect"],
      hint: "male: l'architetto — female: l'architetta",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-007",
      type: "recognize",
      prompt: "il cuoco / la cuoca",
      accepted: ["the cook", "the chef", "cook", "chef"],
      hint: "male: il cuoco — female: la cuoca; 'lo chef' is also used (borrowed from French)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-008",
      type: "recognize",
      prompt: "il cameriere / la cameriera",
      accepted: ["the waiter", "the waitress", "the server", "waiter", "waitress"],
      hint: "male: il cameriere — female: la cameriera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-009",
      type: "recognize",
      prompt: "il meccanico",
      accepted: ["the mechanic", "mechanic"],
      hint: "typically male form used; female: la meccanica",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-010",
      type: "recognize",
      prompt: "l'idraulico",
      accepted: ["the plumber", "plumber"],
      hint: "from 'idraulica' (hydraulics)",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-011",
      type: "recognize",
      prompt: "l'elettricista",
      accepted: ["the electrician", "electrician"],
      hint: "invariable ending in -ista; il/la elettricista",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-012",
      type: "recognize",
      prompt: "il/la farmacista",
      accepted: ["the pharmacist", "the chemist", "pharmacist", "chemist"],
      hint: "invariable -ista ending; gender shown by article: il farmacista / la farmacista",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-013",
      type: "recognize",
      prompt: "il poliziotto / la poliziotta",
      accepted: ["the police officer", "the policeman", "the policewoman", "police officer"],
      hint: "male: il poliziotto — female: la poliziotta",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-014",
      type: "recognize",
      prompt: "il pompiere / la pompiera",
      accepted: ["the firefighter", "the fireman", "the firewoman", "firefighter"],
      hint: "male: il pompiere — female: la pompiera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-015",
      type: "recognize",
      prompt: "lo scrittore / la scrittrice",
      accepted: ["the writer", "the author", "writer", "author"],
      hint: "male: lo scrittore — female: la scrittrice (note the -trice ending for female)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-016",
      type: "recognize",
      prompt: "il/la giornalista",
      accepted: ["the journalist", "journalist", "the reporter", "reporter"],
      hint: "invariable -ista ending; il giornalista (male) / la giornalista (female)",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-017",
      type: "recognize",
      prompt: "il/la musicista",
      accepted: ["the musician", "musician"],
      hint: "invariable -ista ending; gender shown by article",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-018",
      type: "recognize",
      prompt: "l'attore / l'attrice",
      accepted: ["the actor", "the actress", "actor", "actress"],
      hint: "male: l'attore — female: l'attrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-019",
      type: "recognize",
      prompt: "il pittore / la pittrice",
      accepted: ["the painter", "the artist", "painter", "artist"],
      hint: "male: il pittore — female: la pittrice; refers to a visual artist who paints",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-020",
      type: "recognize",
      prompt: "il/la commerciante",
      accepted: ["the shopkeeper", "the merchant", "the trader", "shopkeeper", "merchant", "trader"],
      hint: "invariable -ante ending; someone who runs a business or shop",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-021",
      type: "recognize",
      prompt: "il/la contabile",
      accepted: ["the accountant", "accountant"],
      hint: "invariable; both genders use the same form",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-022",
      type: "recognize",
      prompt: "il programmatore / la programmatrice",
      accepted: ["the programmer", "the developer", "the software developer", "programmer", "developer"],
      hint: "male: il programmatore — female: la programmatrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Fill in the Blank ───────────────────────────────────────────
    {
      id: "a222-t2-001",
      type: "fill_blank",
      prompt: "Lavoro in ospedale. Faccio il ___ — opero i pazienti ogni giorno.",
      accepted: ["medico", "chirurgo"],
      hint: "a doctor who performs operations; 'il medico' works here too",
      tags: ["professions", "fill_blank", "faccio il", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-001"],
    },
    {
      id: "a222-t2-002",
      type: "fill_blank",
      prompt: "Mio fratello ha studiato giurisprudenza. Ora lavora come ___ in uno studio legale.",
      accepted: ["avvocato", "avvocatessa"],
      hint: "a legal professional; 'lavora come' is followed by the profession without an article",
      tags: ["professions", "fill_blank", "lavora come", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-004"],
    },
    {
      id: "a222-t2-003",
      type: "fill_blank",
      prompt: "Mi chiamo Sofia, sono ___. Insegno matematica in una scuola media.",
      accepted: ["insegnante"],
      hint: "'sono' + profession (no article in Italian); invariable noun",
      tags: ["professions", "fill_blank", "sono", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-003"],
    },
    {
      id: "a222-t2-004",
      type: "fill_blank",
      prompt: "Il rubinetto è rotto! Devo chiamare un ___.",
      accepted: ["idraulico"],
      hint: "the tradesperson who fixes pipes and water systems",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-010"],
    },

    // ── Tier 3 – English to Italian ──────────────────────────────────────────
    {
      id: "a222-t3-001",
      type: "produce",
      prompt: "My mother is a doctor.",
      accepted: ["Mia madre è medico.", "Mia madre è dottoressa.", "Mia madre fa il medico.", "Mia madre fa la dottoressa."],
      hint: "in Italian, profession after 'essere' takes no article — just 'è medico', not 'è una medico'",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-001"],
    },
    {
      id: "a222-t3-002",
      type: "produce",
      prompt: "He wants to be an engineer.",
      accepted: ["Vuole fare l'ingegnere.", "Vuole diventare ingegnere.", "Lui vuole fare l'ingegnere.", "Lui vuole diventare ingegnere."],
      hint: "'fare' + definite article + profession, or 'diventare' + profession without article",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-005"],
    },
    {
      id: "a222-t3-003",
      type: "produce",
      prompt: "She works as a journalist.",
      accepted: ["Lei lavora come giornalista.", "Lavora come giornalista."],
      hint: "'lavorare come' + profession — no article after 'come'",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-016"],
    },
    {
      id: "a222-t3-004",
      type: "produce",
      prompt: "What do you do for work?",
      accepted: [
        "Che lavoro fai?",
        "Cosa fai di lavoro?",
        "Che cosa fai di lavoro?",
        "Che lavoro fa?",
        "Cosa fa di lavoro?",
      ],
      hint: "'Che lavoro fai?' is the most common; 'fa' is the Lei (formal) form",
      tags: ["professions", "question", "phrase", "A2"],
      tier: 3,
    },
    {
      id: "a222-t3-005",
      type: "produce",
      prompt: "I am an accountant.",
      accepted: ["Sono contabile.", "Faccio il contabile.", "Faccio la contabile."],
      hint: "'sono' + profession without article; or 'faccio il/la' + profession",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-021"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a222-t4-001",
      type: "passage_cloze",
      prompt: "Mi chiamo Lorenzo Ferretti e ho trentadue anni.\nSono ___ — lavoro in uno studio di architettura a Milano da quattro anni.\nOgni giorno disegno edifici e creo progetti per i nostri clienti.\nPrima di diventare ___, ho studiato architettura all'università per cinque anni.\nIl mio sogno è costruire una biblioteca pubblica nel mio quartiere.\nNel tempo libero suono la chitarra, perché la musica è la mia seconda passione.",
      accepted: ["architetto", "architetta"],
      hint: "Lorenzo designs buildings — what is his profession? (male form)",
      tags: ["professions", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: [
        "a222-t1-006",
        "a222-t1-003",
        "a222-t1-017",
        "a222-t3-002",
      ],
    },

    // ── Tier 1 – Vocabulary (expansion) ───────────────────────────────────────
    {
      id: "a222-t1-023",
      type: "recognize",
      prompt: "il/la dentista",
      accepted: ["the dentist", "dentist"],
      hint: "invariable -ista ending; gender shown by article",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-024",
      type: "recognize",
      prompt: "il veterinario / la veterinaria",
      accepted: ["the vet", "the veterinarian", "vet", "veterinarian"],
      hint: "male: il veterinario — female: la veterinaria; treats sick animals",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-025",
      type: "recognize",
      prompt: "l'agricoltore / l'agricoltrice",
      accepted: ["the farmer", "farmer"],
      hint: "male: l'agricoltore — female: l'agricoltrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-026",
      type: "recognize",
      prompt: "il pescatore / la pescatrice",
      accepted: ["the fisherman", "the fisher", "fisherman"],
      hint: "male: il pescatore — female: la pescatrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-027",
      type: "recognize",
      prompt: "il fotografo / la fotografa",
      accepted: ["the photographer", "photographer"],
      hint: "male: il fotografo — female: la fotografa",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-028",
      type: "recognize",
      prompt: "il parrucchiere / la parrucchiera",
      accepted: ["the hairdresser", "the hairstylist", "hairdresser"],
      hint: "male: il parrucchiere — female: la parrucchiera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-029",
      type: "recognize",
      prompt: "l'estetista",
      accepted: ["the beautician", "the esthetician", "beautician"],
      hint: "invariable -ista ending; works in a beauty salon",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-030",
      type: "recognize",
      prompt: "il fornaio / la fornaia",
      accepted: ["the baker", "baker"],
      hint: "male: il fornaio — female: la fornaia; from 'forno' (oven)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-031",
      type: "recognize",
      prompt: "il macellaio / la macellaia",
      accepted: ["the butcher", "butcher"],
      hint: "male: il macellaio — female: la macellaia",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-032",
      type: "recognize",
      prompt: "il/la barista",
      accepted: ["the barista", "the bartender", "barista", "bartender"],
      hint: "invariable -ista ending; works at a bar making coffee and drinks",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-033",
      type: "recognize",
      prompt: "il/la tassista",
      accepted: ["the taxi driver", "taxi driver"],
      hint: "invariable -ista ending; drives a taxi",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-034",
      type: "recognize",
      prompt: "l'autista",
      accepted: ["the driver", "driver"],
      hint: "invariable -ista ending; a general driver (bus, private car, etc.)",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-035",
      type: "recognize",
      prompt: "il/la pilota",
      accepted: ["the pilot", "pilot"],
      hint: "invariable -ota ending; flies planes",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-036",
      type: "recognize",
      prompt: "l'assistente di volo",
      accepted: ["the flight attendant", "flight attendant"],
      hint: "invariable; literally 'flight assistant'",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-037",
      type: "recognize",
      prompt: "il traduttore / la traduttrice",
      accepted: ["the translator", "translator"],
      hint: "male: il traduttore — female: la traduttrice; translates written text",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-038",
      type: "recognize",
      prompt: "l'interprete",
      accepted: ["the interpreter", "interpreter"],
      hint: "invariable; translates spoken language in real time",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-039",
      type: "recognize",
      prompt: "il segretario / la segretaria",
      accepted: ["the secretary", "secretary"],
      hint: "male: il segretario — female: la segretaria",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-040",
      type: "recognize",
      prompt: "il/la receptionist",
      accepted: ["the receptionist", "receptionist"],
      hint: "borrowed from English; invariable, used with il/la",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-041",
      type: "recognize",
      prompt: "il direttore / la direttrice",
      accepted: ["the manager", "the director", "manager", "director"],
      hint: "male: il direttore — female: la direttrice; heads a company or department",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-042",
      type: "recognize",
      prompt: "il capo / la capa",
      accepted: ["the boss", "boss"],
      hint: "male: il capo — female: la capa; informal word for a supervisor",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-043",
      type: "recognize",
      prompt: "il/la collega",
      accepted: ["the colleague", "the coworker", "colleague", "coworker"],
      hint: "invariable; il collega (male) / la collega (female)",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-044",
      type: "recognize",
      prompt: "il/la dipendente",
      accepted: ["the employee", "employee"],
      hint: "invariable; both genders use the same form",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-045",
      type: "recognize",
      prompt: "il datore di lavoro / la datrice di lavoro",
      accepted: ["the employer", "employer"],
      hint: "male: il datore di lavoro — female: la datrice di lavoro",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-046",
      type: "recognize",
      prompt: "il soldato / la soldatessa",
      accepted: ["the soldier", "soldier"],
      hint: "male: il soldato — female: la soldatessa",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-047",
      type: "recognize",
      prompt: "il postino / la postina",
      accepted: ["the mail carrier", "the postman", "the mailman", "mail carrier"],
      hint: "male: il postino — female: la postina",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-048",
      type: "recognize",
      prompt: "il bibliotecario / la bibliotecaria",
      accepted: ["the librarian", "librarian"],
      hint: "male: il bibliotecario — female: la bibliotecaria",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-049",
      type: "recognize",
      prompt: "il commesso / la commessa",
      accepted: ["the shop assistant", "the sales assistant", "the clerk", "shop assistant"],
      hint: "male: il commesso — female: la commessa; works in a shop helping customers",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-050",
      type: "recognize",
      prompt: "l'agente immobiliare",
      accepted: ["the real estate agent", "the estate agent", "real estate agent"],
      hint: "invariable; il/la agente immobiliare; sells and rents properties",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-051",
      type: "recognize",
      prompt: "il notaio",
      accepted: ["the notary", "notary"],
      hint: "usually kept in the masculine form even for a woman; handles legal documents like property sales",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-052",
      type: "recognize",
      prompt: "il giudice",
      accepted: ["the judge", "judge"],
      hint: "traditionally masculine form used for both genders; decides cases in court",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-053",
      type: "recognize",
      prompt: "lo psicologo / la psicologa",
      accepted: ["the psychologist", "psychologist"],
      hint: "male: lo psicologo — female: la psicologa",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-054",
      type: "recognize",
      prompt: "l'operaio / l'operaia",
      accepted: ["the factory worker", "the laborer", "the labourer", "factory worker"],
      hint: "male: l'operaio — female: l'operaia; works in a factory or on a production line",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-055",
      type: "recognize",
      prompt: "il tecnico / la tecnica",
      accepted: ["the technician", "technician"],
      hint: "male: il tecnico — female: la tecnica; repairs machines and equipment",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-056",
      type: "recognize",
      prompt: "l'analista",
      accepted: ["the analyst", "analyst"],
      hint: "invariable -ista ending; studies data, markets, or systems",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-057",
      type: "recognize",
      prompt: "il/la consulente",
      accepted: ["the consultant", "consultant"],
      hint: "invariable; gives professional advice to companies",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-058",
      type: "recognize",
      prompt: "il/la manager",
      accepted: ["the manager", "manager"],
      hint: "borrowed from English; invariable, used with il/la",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-059",
      type: "recognize",
      prompt: "il socio / la socia",
      accepted: ["the business partner", "the partner", "business partner"],
      hint: "male: il socio — female: la socia; co-owns a business",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-060",
      type: "recognize",
      prompt: "il/la tirocinante",
      accepted: ["the intern", "the trainee", "intern", "trainee"],
      hint: "invariable; someone training on the job, often unpaid or low-paid",
      tags: ["professions", "noun", "invariable", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-061",
      type: "recognize",
      prompt: "il disoccupato / la disoccupata",
      accepted: ["the unemployed person", "unemployed"],
      hint: "male: il disoccupato — female: la disoccupata; from 'occupare' (to occupy/employ)",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-062",
      type: "recognize",
      prompt: "il pensionato / la pensionata",
      accepted: ["the retiree", "the pensioner", "retiree"],
      hint: "male: il pensionato — female: la pensionata; no longer works, receives a pension",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-063",
      type: "recognize",
      prompt: "il lavoratore autonomo / la lavoratrice autonoma",
      accepted: ["the freelancer", "the self-employed worker", "freelancer", "self-employed"],
      hint: "male: il lavoratore autonomo — female: la lavoratrice autonoma; works for themselves",
      tags: ["professions", "noun", "gender", "workplace", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-064",
      type: "recognize",
      prompt: "lo stipendio",
      accepted: ["the salary", "the pay", "salary"],
      hint: "masculine noun; the money paid regularly for a job",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-065",
      type: "recognize",
      prompt: "il colloquio di lavoro",
      accepted: ["the job interview", "job interview"],
      hint: "masculine noun; a meeting to evaluate a candidate for a job",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-066",
      type: "recognize",
      prompt: "il curriculum",
      accepted: ["the resume", "the CV", "the résumé", "resume", "CV"],
      hint: "masculine noun, invariable plural; a summary of education and work experience",
      tags: ["professions", "workplace", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-067",
      type: "recognize",
      prompt: "l'ufficio",
      accepted: ["the office", "office"],
      hint: "masculine noun; the place where someone works, especially at a desk",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-068",
      type: "recognize",
      prompt: "l'azienda",
      accepted: ["the company", "the firm", "the business", "company"],
      hint: "feminine noun; a business organization",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-069",
      type: "recognize",
      prompt: "lo stage",
      accepted: ["the internship", "internship"],
      hint: "borrowed from French, pronounced 'stazh'; masculine noun, invariable plural",
      tags: ["professions", "workplace", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-070",
      type: "recognize",
      prompt: "il turno",
      accepted: ["the shift", "shift"],
      hint: "masculine noun; a scheduled block of working hours",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-071",
      type: "recognize",
      prompt: "l'orario di lavoro",
      accepted: ["the work schedule", "the working hours", "work schedule"],
      hint: "masculine noun; the hours during which someone works",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-072",
      type: "recognize",
      prompt: "la scadenza",
      accepted: ["the deadline", "deadline"],
      hint: "feminine noun; the date by which something must be finished",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-073",
      type: "recognize",
      prompt: "la riunione",
      accepted: ["the meeting", "meeting"],
      hint: "feminine noun; people gathering to discuss work",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-074",
      type: "recognize",
      prompt: "il contratto",
      accepted: ["the contract", "contract"],
      hint: "masculine noun; a signed agreement between employer and employee",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-075",
      type: "recognize",
      prompt: "le ferie",
      accepted: ["the vacation", "the paid leave", "vacation", "paid leave"],
      hint: "feminine plural noun, always plural in this meaning; paid time off from work",
      tags: ["professions", "workplace", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-076",
      type: "recognize",
      prompt: "lo sciopero",
      accepted: ["the strike", "strike"],
      hint: "masculine noun; workers stopping work to protest",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-077",
      type: "recognize",
      prompt: "la busta paga",
      accepted: ["the paycheck", "the payslip", "paycheck", "payslip"],
      hint: "feminine noun; literally 'pay envelope', the document showing salary and deductions",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-078",
      type: "recognize",
      prompt: "la pensione",
      accepted: ["the retirement", "the pension", "retirement", "pension"],
      hint: "feminine noun; used in 'andare in pensione' (to retire)",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-079",
      type: "recognize",
      prompt: "la carriera",
      accepted: ["the career", "career"],
      hint: "feminine noun; the progression of someone's working life",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-080",
      type: "recognize",
      prompt: "la promozione",
      accepted: ["the promotion", "promotion"],
      hint: "feminine noun; a move to a higher position at work",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-081",
      type: "recognize",
      prompt: "le dimissioni",
      accepted: ["the resignation", "resignation"],
      hint: "feminine plural noun, always plural; used in 'dare le dimissioni' (to resign)",
      tags: ["professions", "workplace", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-082",
      type: "recognize",
      prompt: "lo straordinario",
      accepted: ["the overtime", "overtime"],
      hint: "masculine noun; extra hours worked beyond the normal schedule",
      tags: ["professions", "workplace", "noun", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Fill in the Blank (expansion) ────────────────────────────────
    {
      id: "a222-t2-005",
      type: "fill_blank",
      prompt: "Lavoro con gli animali malati. Faccio ___ in una clinica fuori città.",
      accepted: ["il veterinario", "la veterinaria", "veterinario", "veterinaria"],
      hint: "the professional who treats sick animals",
      tags: ["professions", "fill_blank", "faccio il", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-024"],
    },
    {
      id: "a222-t2-006",
      type: "fill_blank",
      prompt: "Sofia scatta foto per un giornale locale. Fa ___ da cinque anni.",
      accepted: ["la fotografa", "fotografa"],
      hint: "someone who takes photos for a living (female form)",
      tags: ["professions", "fill_blank", "fa", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-027"],
    },
    {
      id: "a222-t2-007",
      type: "fill_blank",
      prompt: "Devo tagliarmi i capelli prima del matrimonio. Vado dal ___ sabato mattina.",
      accepted: ["parrucchiere"],
      hint: "the professional who cuts and styles hair",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-028"],
    },
    {
      id: "a222-t2-008",
      type: "fill_blank",
      prompt: "Il pane di questo negozio è sempre caldo. Il ___ lo prepara ogni mattina alle quattro.",
      accepted: ["fornaio"],
      hint: "the person who bakes bread, from 'forno' (oven)",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-030"],
    },
    {
      id: "a222-t2-009",
      type: "fill_blank",
      prompt: "Prendo sempre lo stesso taxi la mattina: il ___ conosce tutte le strade del centro.",
      accepted: ["tassista"],
      hint: "the driver of a taxi",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-033"],
    },
    {
      id: "a222-t2-010",
      type: "fill_blank",
      prompt: "Il volo per Londra è in ritardo. L'___ ha annunciato il ritardo ai passeggeri.",
      accepted: ["assistente di volo"],
      hint: "the crew member who takes care of passengers on a plane",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-036"],
    },
    {
      id: "a222-t2-011",
      type: "fill_blank",
      prompt: "Non parlo francese. Mi serve un ___ per capire la riunione di domani.",
      accepted: ["interprete"],
      hint: "someone who translates spoken language in real time",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-038"],
    },
    {
      id: "a222-t2-012",
      type: "fill_blank",
      prompt: "In albergo, il ___ mi ha dato le chiavi della camera e le informazioni sul ristorante.",
      accepted: ["receptionist"],
      hint: "the person at the front desk of a hotel",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-040"],
    },
    {
      id: "a222-t2-013",
      type: "fill_blank",
      prompt: "Il mio ___ mi ha dato un aumento di stipendio dopo la promozione.",
      accepted: ["capo"],
      hint: "the person who supervises you at work",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-042"],
    },
    {
      id: "a222-t2-014",
      type: "fill_blank",
      prompt: "Ho lavorato con la stessa ___ per dieci anni: siamo diventate amiche.",
      accepted: ["collega"],
      hint: "a person you work with (female form)",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-043"],
    },
    {
      id: "a222-t2-015",
      type: "fill_blank",
      prompt: "L'azienda ha assunto duecento nuovi ___ quest'anno.",
      accepted: ["dipendenti"],
      hint: "people who work for a company",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-044"],
    },
    {
      id: "a222-t2-016",
      type: "fill_blank",
      prompt: "Devo parlare con il mio ___ per chiedere due giorni di ferie.",
      accepted: ["datore di lavoro"],
      hint: "the person or company that pays your salary",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-045"],
    },
    {
      id: "a222-t2-017",
      type: "fill_blank",
      prompt: "Mio nonno ha fatto il ___ durante la guerra, poi è tornato a lavorare in campagna.",
      accepted: ["soldato"],
      hint: "a member of the army",
      tags: ["professions", "fill_blank", "faccio il", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-046"],
    },
    {
      id: "a222-t2-018",
      type: "fill_blank",
      prompt: "Il ___ porta le lettere e i pacchi nel nostro quartiere ogni giorno alle undici.",
      accepted: ["postino"],
      hint: "delivers mail and packages",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-047"],
    },
    {
      id: "a222-t2-019",
      type: "fill_blank",
      prompt: "In biblioteca, la ___ mi ha consigliato un romanzo storico bellissimo.",
      accepted: ["bibliotecaria"],
      hint: "works in a library and helps readers find books (female form)",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-048"],
    },
    {
      id: "a222-t2-020",
      type: "fill_blank",
      prompt: "Vorrei provare questa giacca: chiedo aiuto alla ___ del negozio.",
      accepted: ["commessa"],
      hint: "helps customers in a shop (female form)",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-049"],
    },
    {
      id: "a222-t2-021",
      type: "fill_blank",
      prompt: "Per vendere l'appartamento di mia nonna, ho contattato un ___.",
      accepted: ["agente immobiliare"],
      hint: "helps people buy, sell, or rent properties",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-050"],
    },
    {
      id: "a222-t2-022",
      type: "fill_blank",
      prompt: "Per firmare il contratto della casa, dobbiamo andare dal ___.",
      accepted: ["notaio"],
      hint: "certifies official legal documents, like a property sale",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-051"],
    },
    {
      id: "a222-t2-023",
      type: "fill_blank",
      prompt: "Il ___ ha letto la sentenza davanti a tutta l'aula del tribunale.",
      accepted: ["giudice"],
      hint: "decides the outcome of a legal case",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-052"],
    },
    {
      id: "a222-t2-024",
      type: "fill_blank",
      prompt: "Vado dallo ___ ogni martedì per parlare dei miei problemi.",
      accepted: ["psicologo"],
      hint: "a professional who helps with mental and emotional wellbeing",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-053"],
    },
    {
      id: "a222-t2-025",
      type: "fill_blank",
      prompt: "Mio zio lavora in fabbrica: è ___ da vent'anni.",
      accepted: ["operaio"],
      hint: "works on a factory production line",
      tags: ["professions", "fill_blank", "sono", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-054"],
    },
    {
      id: "a222-t2-026",
      type: "fill_blank",
      prompt: "Il computer dell'ufficio non funziona più: chiamiamo il ___.",
      accepted: ["tecnico"],
      hint: "fixes machines and equipment",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-055", "a222-t1-067"],
    },
    {
      id: "a222-t2-027",
      type: "fill_blank",
      prompt: "Lavoro come ___ per una società di consulenza finanziaria: studio i mercati ogni giorno.",
      accepted: ["analista"],
      hint: "studies data, numbers, or markets professionally",
      tags: ["professions", "fill_blank", "lavora come", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-056"],
    },
    {
      id: "a222-t2-028",
      type: "fill_blank",
      prompt: "Non ho un capo: sono un ___ e scelgo i miei progetti da solo.",
      accepted: ["lavoratore autonomo"],
      hint: "works for themselves rather than for an employer",
      tags: ["professions", "fill_blank", "sono", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-063"],
    },
    {
      id: "a222-t2-029",
      type: "fill_blank",
      prompt: "Quest'estate ho fatto uno ___ di tre mesi in un'azienda di moda.",
      accepted: ["stage"],
      hint: "a short, often unpaid work placement",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-069"],
    },
    {
      id: "a222-t2-030",
      type: "fill_blank",
      prompt: "Il mio ___ inizia alle sei del mattino e finisce alle due del pomeriggio.",
      accepted: ["turno"],
      hint: "a scheduled block of working hours",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-070"],
    },
    {
      id: "a222-t2-031",
      type: "fill_blank",
      prompt: "Ho una ___ importante con i clienti stranieri alle dieci di mattina.",
      accepted: ["riunione"],
      hint: "people gathering to discuss work",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-073"],
    },
    {
      id: "a222-t2-032",
      type: "fill_blank",
      prompt: "Devo firmare il ___ prima di iniziare il nuovo lavoro lunedì.",
      accepted: ["contratto"],
      hint: "the signed agreement between employer and employee",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-074"],
    },
    {
      id: "a222-t2-033",
      type: "fill_blank",
      prompt: "Finalmente vado in ___: dopo quarant'anni di lavoro, mi riposo.",
      accepted: ["pensione"],
      hint: "used in the phrase 'andare in ___' (to retire)",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-078"],
    },
    {
      id: "a222-t2-034",
      type: "fill_blank",
      prompt: "Dopo anni di duro lavoro in azienda, ho finalmente ricevuto una ___.",
      accepted: ["promozione"],
      hint: "a move to a higher position at work",
      tags: ["professions", "fill_blank", "workplace", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-080"],
    },

    // ── Tier 3 – English to Italian (expansion) ───────────────────────────────
    {
      id: "a222-t3-006",
      type: "produce",
      prompt: "I have a job interview tomorrow.",
      accepted: ["Ho un colloquio di lavoro domani.", "Domani ho un colloquio di lavoro."],
      hint: "collocation: avere/fare un colloquio di lavoro",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-065"],
    },
    {
      id: "a222-t3-007",
      type: "produce",
      prompt: "She works part-time.",
      accepted: ["Lei lavora part-time.", "Lavora part-time.", "Lei lavora a tempo parziale.", "Lavora a tempo parziale."],
      hint: "'a tempo parziale' is the full Italian phrase for 'part-time'",
      tags: ["professions", "phrase", "workplace", "A2"],
      tier: 3,
    },
    {
      id: "a222-t3-008",
      type: "produce",
      prompt: "He works full-time.",
      accepted: ["Lui lavora a tempo pieno.", "Lavora a tempo pieno."],
      hint: "'a tempo pieno' = full-time",
      tags: ["professions", "phrase", "workplace", "A2"],
      tier: 3,
    },
    {
      id: "a222-t3-009",
      type: "produce",
      prompt: "I am looking for a job.",
      accepted: ["Sto cercando lavoro.", "Cerco lavoro."],
      hint: "'cercare lavoro' — no article before 'lavoro' here",
      tags: ["professions", "phrase", "workplace", "A2"],
      tier: 3,
    },
    {
      id: "a222-t3-010",
      type: "produce",
      prompt: "My salary is not very high.",
      accepted: ["Il mio stipendio non è molto alto.", "Il mio stipendio non è alto."],
      hint: "collocation: uno stipendio alto/basso",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-064"],
    },
    {
      id: "a222-t3-011",
      type: "produce",
      prompt: "I take two weeks of vacation every year.",
      accepted: ["Prendo due settimane di ferie ogni anno.", "Ogni anno prendo due settimane di ferie."],
      hint: "collocation: prendere le ferie",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-075"],
    },
    {
      id: "a222-t3-012",
      type: "produce",
      prompt: "He signed the contract yesterday.",
      accepted: ["Ha firmato il contratto ieri.", "Ieri ha firmato il contratto."],
      hint: "collocation: firmare un contratto",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-074"],
    },
    {
      id: "a222-t3-013",
      type: "produce",
      prompt: "The factory workers are on strike.",
      accepted: ["Gli operai sono in sciopero.", "Gli operai della fabbrica sono in sciopero."],
      hint: "collocation: essere in sciopero",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-054", "a222-t1-076"],
    },
    {
      id: "a222-t3-014",
      type: "produce",
      prompt: "I want to update my resume before the interview.",
      accepted: ["Voglio aggiornare il mio curriculum prima del colloquio.", "Voglio aggiornare il curriculum prima del colloquio."],
      hint: "collocation: aggiornare il curriculum",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-066"],
    },
    {
      id: "a222-t3-015",
      type: "produce",
      prompt: "She got a promotion last month.",
      accepted: ["Ha ricevuto una promozione il mese scorso.", "Il mese scorso ha ricevuto una promozione."],
      hint: "collocation: ricevere una promozione",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-080"],
    },
    {
      id: "a222-t3-016",
      type: "produce",
      prompt: "My boss is very demanding.",
      accepted: ["Il mio capo è molto esigente."],
      hint: "'esigente' = demanding, hard to please",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-042"],
    },
    {
      id: "a222-t3-017",
      type: "produce",
      prompt: "We have a meeting at three o'clock.",
      accepted: ["Abbiamo una riunione alle tre."],
      hint: "collocation: avere una riunione",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-073"],
    },
    {
      id: "a222-t3-018",
      type: "produce",
      prompt: "He is a self-employed translator.",
      accepted: ["È un traduttore autonomo.", "Lui è un traduttore autonomo."],
      hint: "combines 'traduttore' with 'autonomo' (self-employed)",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-037", "a222-t1-063"],
    },
    {
      id: "a222-t3-019",
      type: "produce",
      prompt: "The company hired ten new employees.",
      accepted: ["L'azienda ha assunto dieci nuovi dipendenti."],
      hint: "collocation: assumere un dipendente",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-044", "a222-t1-068"],
    },
    {
      id: "a222-t3-020",
      type: "produce",
      prompt: "I retired last year.",
      accepted: ["Sono andato in pensione l'anno scorso.", "Sono andata in pensione l'anno scorso."],
      hint: "collocation: andare in pensione",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-078"],
    },
    {
      id: "a222-t3-021",
      type: "produce",
      prompt: "She resigned from her job.",
      accepted: ["Ha dato le dimissioni dal suo lavoro.", "Ha dato le dimissioni."],
      hint: "collocation: dare le dimissioni",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-081"],
    },
    {
      id: "a222-t3-022",
      type: "produce",
      prompt: "I work overtime on Fridays.",
      accepted: ["Faccio gli straordinari il venerdì."],
      hint: "collocation: fare gli straordinari",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-082"],
    },
    {
      id: "a222-t3-023",
      type: "produce",
      prompt: "The technician fixed the printer in ten minutes.",
      accepted: ["Il tecnico ha riparato la stampante in dieci minuti."],
      hint: "collocation: riparare qualcosa",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-055"],
    },
    {
      id: "a222-t3-024",
      type: "produce",
      prompt: "I need to see a psychologist.",
      accepted: ["Ho bisogno di vedere uno psicologo."],
      hint: "'avere bisogno di' + infinitive",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-053"],
    },
    {
      id: "a222-t3-025",
      type: "produce",
      prompt: "The judge read the verdict slowly.",
      accepted: ["Il giudice ha letto la sentenza lentamente."],
      hint: "'la sentenza' = the verdict",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-052"],
    },
    {
      id: "a222-t3-026",
      type: "produce",
      prompt: "My colleague helped me with the project.",
      accepted: ["La mia collega mi ha aiutato con il progetto.", "Il mio collega mi ha aiutato con il progetto."],
      hint: "'aiutare qualcuno con qualcosa'",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-043"],
    },
    {
      id: "a222-t3-027",
      type: "produce",
      prompt: "The baker starts work at four in the morning.",
      accepted: ["Il fornaio inizia a lavorare alle quattro del mattino."],
      hint: "'iniziare a lavorare' = to start working",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-030"],
    },
    {
      id: "a222-t3-028",
      type: "produce",
      prompt: "The flight attendant explained the safety rules.",
      accepted: ["L'assistente di volo ha spiegato le regole di sicurezza."],
      hint: "'le regole di sicurezza' = the safety rules",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-036"],
    },
    {
      id: "a222-t3-029",
      type: "produce",
      prompt: "I made an appointment with the notary.",
      accepted: ["Ho preso un appuntamento con il notaio."],
      hint: "collocation: prendere un appuntamento",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-051"],
    },
    {
      id: "a222-t3-030",
      type: "produce",
      prompt: "The librarian recommended a good book.",
      accepted: ["La bibliotecaria ha consigliato un buon libro.", "Il bibliotecario ha consigliato un buon libro."],
      hint: "collocation: consigliare un libro",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-048"],
    },
    {
      id: "a222-t3-031",
      type: "produce",
      prompt: "The mechanic and the electrician work together in this shop.",
      accepted: ["Il meccanico e l'elettricista lavorano insieme in questa officina."],
      hint: "'lavorare insieme' = to work together",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-009", "a222-t1-011"],
    },
    {
      id: "a222-t3-032",
      type: "produce",
      prompt: "The consultant gave good advice to the company.",
      accepted: ["Il consulente ha dato buoni consigli all'azienda."],
      hint: "collocation: dare consigli",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-057"],
    },
    {
      id: "a222-t3-033",
      type: "produce",
      prompt: "He works as an analyst for a bank.",
      accepted: ["Lavora come analista per una banca.", "Lui lavora come analista per una banca."],
      hint: "'lavorare come' + profession, no article",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-056"],
    },
    {
      id: "a222-t3-034",
      type: "produce",
      prompt: "The intern learns a lot in this office.",
      accepted: ["Il tirocinante impara molto in questo ufficio.", "La tirocinante impara molto in questo ufficio."],
      hint: "'imparare molto' = to learn a lot",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-060", "a222-t1-067"],
    },
    {
      id: "a222-t3-035",
      type: "produce",
      prompt: "I lost my job and now I am unemployed.",
      accepted: ["Ho perso il lavoro e ora sono disoccupato.", "Ho perso il lavoro e ora sono disoccupata."],
      hint: "collocation: perdere il lavoro",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-061"],
    },
    {
      id: "a222-t3-036",
      type: "produce",
      prompt: "The farmer wakes up before dawn.",
      accepted: ["L'agricoltore si sveglia prima dell'alba."],
      hint: "'svegliarsi' = to wake up (reflexive)",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-025"],
    },
    {
      id: "a222-t3-037",
      type: "produce",
      prompt: "The fisherman sells fresh fish at the market.",
      accepted: ["Il pescatore vende il pesce fresco al mercato."],
      hint: "collocation: pesce fresco",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-026"],
    },
    {
      id: "a222-t3-038",
      type: "produce",
      prompt: "The real estate agent showed us three apartments.",
      accepted: ["L'agente immobiliare ci ha mostrato tre appartamenti."],
      hint: "'mostrare qualcosa a qualcuno' = to show something to someone",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-050"],
    },
    {
      id: "a222-t3-039",
      type: "produce",
      prompt: "My career has changed a lot in ten years.",
      accepted: ["La mia carriera è cambiata molto in dieci anni."],
      hint: "'cambiare' takes 'essere' in the passato prossimo when intransitive",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-079"],
    },
    {
      id: "a222-t3-040",
      type: "produce",
      prompt: "The company pays a good salary but the hours are long.",
      accepted: ["L'azienda paga uno stipendio buono ma l'orario è lungo."],
      hint: "collocation: pagare uno stipendio",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-068", "a222-t1-071", "a222-t1-064"],
    },

    // ── Tier 3 – Collocations (word-coverage expansion) ───────────────────────
    {
      id: "a222-t3-041",
      type: "produce",
      prompt: "The cook prepares the dishes, the waiter carries them to the tables, and the barista makes the coffees.",
      accepted: ["Il cuoco prepara i piatti, il cameriere li porta ai tavoli e il barista fa i caffè."],
      hint: "three restaurant roles in one sentence — cuoco, cameriere, barista",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-007", "a222-t1-008", "a222-t1-032"],
    },
    {
      id: "a222-t3-042",
      type: "produce",
      prompt: "After the accident, a police officer and a firefighter arrived together within minutes.",
      accepted: ["Dopo l'incidente, un poliziotto e un pompiere sono arrivati insieme in pochi minuti."],
      hint: "'sono arrivati' agrees with the plural subject (poliziotto + pompiere together)",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-013", "a222-t1-014"],
    },
    {
      id: "a222-t3-043",
      type: "produce",
      prompt: "For a toothache I go to the dentist, but for medicine I go to the pharmacist.",
      accepted: ["Per il mal di denti vado dal dentista, ma per le medicine vado dal farmacista."],
      hint: "'vado dal' + profession — dal = da + il, used for someone's place of work",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-023", "a222-t1-012"],
    },
    {
      id: "a222-t3-044",
      type: "produce",
      prompt: "The nurse checked the patient's blood pressure before the operation.",
      accepted: [
        "L'infermiere ha controllato la pressione del paziente prima dell'operazione.",
        "L'infermiera ha controllato la pressione del paziente prima dell'operazione.",
      ],
      hint: "'controllare la pressione' = to check someone's blood pressure",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-002"],
    },
    {
      id: "a222-t3-045",
      type: "produce",
      prompt: "At the festival we met a writer, a musician, and a very famous actor.",
      accepted: ["Al festival abbiamo incontrato uno scrittore, un musicista e un attore molto famosi."],
      hint: "'incontrare' + profession list — no article is dropped here since each noun is indefinite",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-015", "a222-t1-017", "a222-t1-018"],
    },
    {
      id: "a222-t3-046",
      type: "produce",
      prompt: "The painter displayed his paintings in a small gallery downtown.",
      accepted: ["Il pittore ha esposto i suoi quadri in una piccola galleria del centro."],
      hint: "'esporre i quadri' = to display paintings",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-019"],
    },
    {
      id: "a222-t3-047",
      type: "produce",
      prompt: "The shopkeeper at the market sells fruit and vegetables, while the butcher sells meat.",
      accepted: ["Il commerciante del mercato vende frutta e verdura, mentre il macellaio vende la carne."],
      hint: "'mentre' = while, contrasting two vendors",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-020", "a222-t1-031"],
    },
    {
      id: "a222-t3-048",
      type: "produce",
      prompt: "The programmer has been an employee of the company for three years.",
      accepted: ["Il programmatore è un dipendente dell'azienda da tre anni."],
      hint: "'essere un dipendente di' + company — 'da tre anni' = for three years",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-022", "a222-t1-044"],
    },
    {
      id: "a222-t3-049",
      type: "produce",
      prompt: "The beautician gave me a relaxing facial treatment.",
      accepted: ["L'estetista mi ha fatto un trattamento rilassante al viso."],
      hint: "'fare un trattamento' = to give/do a treatment",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-029"],
    },
    {
      id: "a222-t3-050",
      type: "produce",
      prompt: "The driver drives the bus in the city, while the pilot flies over the ocean.",
      accepted: ["L'autista guida l'autobus in città, mentre il pilota vola sopra l'oceano."],
      hint: "'guidare' = to drive; 'volare sopra' = to fly over",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-034", "a222-t1-035"],
    },
    {
      id: "a222-t3-051",
      type: "produce",
      prompt: "The secretary prepares the documents for the director, who is the manager of the whole department.",
      accepted: ["Il segretario prepara i documenti per il direttore, che è il manager di tutto il reparto."],
      hint: "'che' introduces a relative clause describing il direttore",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-039", "a222-t1-041", "a222-t1-058"],
    },
    {
      id: "a222-t3-052",
      type: "produce",
      prompt: "My business partner retires next year and will become a happy retiree.",
      accepted: ["Il mio socio va in pensione l'anno prossimo e diventerà un pensionato felice."],
      hint: "'andare in pensione' = to retire; 'diventare' + profession, no article",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-059", "a222-t1-062"],
    },
    {
      id: "a222-t3-053",
      type: "produce",
      prompt: "My work schedule is long, and often I also have to work overtime.",
      accepted: ["Il mio orario di lavoro è lungo, e spesso devo fare anche lo straordinario."],
      hint: "'fare lo straordinario' = to work overtime (singular here, unlike 'fare gli straordinari')",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-071", "a222-t1-082"],
    },
    {
      id: "a222-t3-054",
      type: "produce",
      prompt: "I received my paycheck on the very day of the contract's deadline.",
      accepted: ["Ho ricevuto la busta paga proprio il giorno della scadenza del contratto."],
      hint: "'la scadenza di' = the deadline of; 'proprio' emphasizes exact timing",
      tags: ["professions", "sentence", "workplace", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-077", "a222-t1-072"],
    },

    // ── Tier 4 – Passage Cloze (expansion) ────────────────────────────────────
    {
      id: "a222-t4-002",
      type: "passage_cloze",
      prompt: "Mi chiamo Chiara Bruno e ho ventotto anni.\nSono ___ — lavoro in una clinica per animali fuori Torino da tre anni.\nOgni mattina visito cani, gatti e a volte anche qualche coniglio.\nIeri un cane si è rotto una zampa e ho dovuto operarlo subito.\nPrima di diventare ___, ho studiato veterinaria per sei anni all'università di Bologna.\nLa parte più difficile del mio lavoro è dare brutte notizie ai proprietari degli animali.",
      accepted: ["veterinaria", "veterinario"],
      hint: "Chiara treats sick animals in a clinic — what is her profession? (female form)",
      tags: ["professions", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: ["a222-t1-024", "a222-t2-005"],
    },
    {
      id: "a222-t4-003",
      type: "passage_cloze",
      prompt: "Mi chiamo Davide Conti e ho quarantacinque anni.\nFaccio il ___ nel mio quartiere da vent'anni: tutti mi conoscono per nome.\nOgni giorno porto lettere e pacchi con la mia bicicletta gialla, anche quando piove.\nLa signora Rossi mi offre sempre un caffè quando passo davanti a casa sua.\nFare il ___ non è un lavoro facile, ma mi piace stare all'aria aperta.\nTra due anni vado in pensione, e mi mancherà molto questo lavoro.",
      accepted: ["postino"],
      hint: "Davide delivers letters and packages by bicycle — what is his job?",
      tags: ["professions", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: ["a222-t1-047", "a222-t1-078"],
    },
    {
      id: "a222-t4-004",
      type: "passage_cloze",
      prompt: "Mi chiamo Elena Marchetti e ho trentaquattro anni.\nLavoro come ___ in una banca di Milano: studio i mercati finanziari ogni giorno.\nSpesso guardo grafici e numeri per capire se un'azienda merita un investimento.\nIl mio capo mi ha chiesto di diventare ___ senior entro la fine dell'anno.\nPer questo devo studiare ancora molto e frequentare corsi di finanza avanzata.\nNel tempo libero leggo romanzi gialli per rilassarmi dopo una giornata intensa in ufficio.",
      accepted: ["analista"],
      hint: "Elena studies markets and financial numbers at a bank — what is her job?",
      tags: ["professions", "passage_cloze", "workplace", "A2"],
      tier: 4,
      prerequisites: ["a222-t1-056", "a222-t1-042", "a222-t1-067"],
    },
    {
      id: "a222-t4-005",
      type: "passage_cloze",
      prompt: "Mi chiamo Giulia Esposito e ho ventisei anni.\nFaccio la ___ in un negozio di abbigliamento nel centro di Napoli.\nAiuto i clienti a scegliere vestiti e scarpe, e a volte consiglio anche gli accessori giusti.\nIl sabato il negozio è pieno di gente, e faccio la ___ dalla mattina alla sera senza pausa.\nMi piace questo lavoro perché parlo con persone diverse ogni giorno.\nUn giorno vorrei aprire un negozio tutto mio, con vestiti disegnati da me.",
      accepted: ["commessa"],
      hint: "Giulia helps customers choose clothes in a shop — what is her job? (female form)",
      tags: ["professions", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: ["a222-t1-049"],
    },
  ],
};
export default unit;
