import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-11-past-essere",
  name: "The Past (essere)",
  level: "A2",
  theme: "Past Tense with essere",
  emoji: "🚶",
  prerequisiteUnits: ["a2-unit-10-past-avere"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u11-t1-001",
      type: "recognize",
      prompt: "andare",
      accepted: ["to go"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-002",
      type: "recognize",
      prompt: "venire",
      accepted: ["to come"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-003",
      type: "recognize",
      prompt: "uscire",
      accepted: ["to go out", "to leave"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-004",
      type: "recognize",
      prompt: "arrivare",
      accepted: ["to arrive"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-005",
      type: "recognize",
      prompt: "partire",
      accepted: ["to leave", "to depart"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-006",
      type: "recognize",
      prompt: "tornare",
      accepted: ["to return", "to come back"],
      hint: "movement verb — uses essere",
      tags: ["verb", "movement", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-007",
      type: "recognize",
      prompt: "rimanere",
      accepted: ["to stay", "to remain"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-008",
      type: "recognize",
      prompt: "nascere",
      accepted: ["to be born"],
      hint: "state verb — uses essere",
      tags: ["verb", "state", "essere"],
      tier: 1,
    },
    {
      id: "u11-t1-009",
      type: "produce",
      prompt: "the station",
      accepted: ["la stazione"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-010",
      type: "produce",
      prompt: "the airport",
      accepted: ["l'aeroporto"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-011",
      type: "produce",
      prompt: "the city centre",
      accepted: ["il centro"],
      tags: ["noun", "place"],
      tier: 1,
    },
    {
      id: "u11-t1-012",
      type: "produce",
      prompt: "the house",
      accepted: ["la casa"],
      tags: ["noun", "place"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (conjugation) ──────────────────────────────────────
    {
      id: "u11-t2-001",
      type: "conjugate",
      prompt: "andare (passato prossimo) – io (maschile)",
      accepted: ["sono andato"],
      hint: "participio agrees with subject gender",
      tags: ["essere", "passato-prossimo", "conjugation", "andare"],
      tier: 2,
    },
    {
      id: "u11-t2-002",
      type: "conjugate",
      prompt: "andare (passato prossimo) – io (femminile)",
      accepted: ["sono andata"],
      hint: "participio agrees with subject gender",
      tags: ["essere", "passato-prossimo", "conjugation", "andare"],
      tier: 2,
    },
    {
      id: "u11-t2-003",
      type: "conjugate",
      prompt: "venire (passato prossimo) – lui",
      accepted: ["è venuto"],
      tags: ["essere", "passato-prossimo", "conjugation", "venire"],
      tier: 2,
    },
    {
      id: "u11-t2-004",
      type: "conjugate",
      prompt: "venire (passato prossimo) – lei",
      accepted: ["è venuta"],
      tags: ["essere", "passato-prossimo", "conjugation", "venire"],
      tier: 2,
    },
    {
      id: "u11-t2-005",
      type: "conjugate",
      prompt: "arrivare (passato prossimo) – noi",
      accepted: ["siamo arrivati", "siamo arrivate"],
      hint: "noi group: -i (mixed/male) or -e (all female)",
      tags: ["essere", "passato-prossimo", "conjugation", "arrivare"],
      tier: 2,
    },
    {
      id: "u11-t2-006",
      type: "conjugate",
      prompt: "partire (passato prossimo) – loro (maschile/misto)",
      accepted: ["sono partiti"],
      tags: ["essere", "passato-prossimo", "conjugation", "partire"],
      tier: 2,
    },
    {
      id: "u11-t2-007",
      type: "conjugate",
      prompt: "tornare (passato prossimo) – tu (maschile)",
      accepted: ["sei tornato"],
      tags: ["essere", "passato-prossimo", "conjugation", "tornare"],
      tier: 2,
    },
    {
      id: "u11-t2-008",
      type: "conjugate",
      prompt: "rimanere (passato prossimo) – io (femminile)",
      accepted: ["sono rimasta"],
      hint: "rimanere → rimasto/a",
      tags: ["essere", "passato-prossimo", "conjugation", "rimanere"],
      tier: 2,
    },
    {
      id: "u11-t2-009",
      type: "conjugate",
      prompt: "nascere (passato prossimo) – lui",
      accepted: ["è nato"],
      hint: "nascere → nato/a",
      tags: ["essere", "passato-prossimo", "conjugation", "nascere"],
      tier: 2,
    },
    {
      id: "u11-t2-010",
      type: "fill_blank",
      prompt: "Mia nonna ___ morta l'anno scorso. (morire – lei)",
      accepted: ["è morta"],
      hint: "morire → morto/a; uses essere",
      tags: ["essere", "passato-prossimo", "morire", "agreement"],
      tier: 2,
    },

    // ── Tier 3 – Chunks / Short sentences ───────────────────────────────────
    {
      id: "u11-t3-001",
      type: "produce",
      prompt: "I went to Rome. (male speaker)",
      accepted: ["Sono andato a Roma."],
      hint: "andare → sono andato",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-002",
      type: "produce",
      prompt: "We arrived yesterday. (mixed group)",
      accepted: ["Siamo arrivati ieri."],
      hint: "arrivare → siamo arrivati",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-003",
      type: "produce",
      prompt: "Where did you come from? (female addressee)",
      accepted: ["Da dove sei venuta?"],
      hint: "venire → sei venuta",
      tags: ["chunk", "essere", "passato-prossimo", "question"],
      tier: 3,
    },
    {
      id: "u11-t3-004",
      type: "fill_blank",
      prompt: "Marco e Giulia ___ usciti insieme stasera.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-005",
      type: "produce",
      prompt: "She returned home late. (female)",
      accepted: ["È tornata a casa tardi."],
      hint: "tornare → è tornata",
      tags: ["chunk", "essere", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "u11-t3-006",
      type: "fill_blank",
      prompt: "I ragazzi ___ partiti dalla stazione alle otto.",
      accepted: ["sono"],
      hint: "essere auxiliary — loro form",
      tags: ["chunk", "essere", "passato-prossimo", "stazione"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze ─────────────────────────────────
    {
      id: "u11-t4-001",
      type: "produce",
      prompt: "My friends left from the airport at noon. (male friends)",
      accepted: ["I miei amici sono partiti dall'aeroporto a mezzogiorno."],
      hint: "partire → sono partiti; aeroporto needs dall'",
      tags: ["production", "essere", "passato-prossimo"],
      tier: 4,
      prerequisites: ["u11-t1-005", "u11-t1-010", "u11-t2-006"],
    },
    {
      id: "u11-t4-002",
      type: "produce",
      prompt: "I stayed at home all day. (female speaker)",
      accepted: ["Sono rimasta a casa tutto il giorno."],
      hint: "rimanere → sono rimasta",
      tags: ["production", "essere", "passato-prossimo"],
      tier: 4,
      prerequisites: ["u11-t1-007", "u11-t1-012", "u11-t2-008"],
    },
    {
      id: "u11-t4-003",
      type: "passage_cloze",
      prompt:
        "L'estate scorsa ho fatto un viaggio in Italia con la mia famiglia.\nSiamo partiti da Londra e ___ arrivati a Roma in aereo.\nIl primo giorno siamo andati al centro e abbiamo visitato il Colosseo.\nLa sera siamo tornati all'albergo molto stanchi ma felici.",
      accepted: ["siamo"],
      hint: "essere auxiliary — noi form",
      tags: ["passage-cloze", "essere", "passato-prossimo", "arrivare"],
      tier: 4,
      prerequisites: ["u11-t1-004", "u11-t1-011", "u11-t2-005"],
    },
    {
      id: "u11-t4-004",
      type: "passage_cloze",
      prompt:
        "Ieri mattina Maria si è svegliata presto e è uscita di casa alle sette.\nÈ andata alla stazione e ha preso il treno per Milano.\nQuando è ___ a Milano, ha telefonato alla sua amica.\nInsieme sono andate al centro per fare shopping.",
      accepted: ["arrivata"],
      hint: "arrivare → arrivata (lei, femminile)",
      tags: ["passage-cloze", "essere", "passato-prossimo", "arrivare", "agreement"],
      tier: 4,
      prerequisites: ["u11-t1-004", "u11-t1-009", "u11-t2-004"],
    },
    {
      id: "u11-t4-005",
      type: "fill_blank",
      prompt:
        "Gianni è ___ a Napoli nel 1990 e ci ha vissuto fino all'età di vent'anni.",
      accepted: ["nato"],
      hint: "nascere → nato (lui)",
      tags: ["production", "essere", "passato-prossimo", "nascere"],
      tier: 4,
      prerequisites: ["u11-t1-008", "u11-t2-009"],
    },
  ],
};
export default unit;
