import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-27-reflexive-verbs-expanded",
  name: "Reflexive Verbs (Expanded)",
  level: "A2",
  theme: "Emotional & Social Reflexive Verbs",
  emoji: "💞",
  prerequisiteUnits: ["a2-unit-26-irregular-participles"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a227-t1-001",
      type: "recognize",
      prompt: "divertirsi",
      accepted: ["to have fun", "to enjoy oneself"],
      hint: "reflexive — io mi diverto, tu ti diverti, lui/lei si diverte",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-002",
      type: "produce",
      prompt: "to have fun / to enjoy oneself",
      accepted: ["divertirsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-003",
      type: "recognize",
      prompt: "annoiarsi",
      accepted: ["to get bored", "to become bored"],
      hint: "reflexive — io mi annoio",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-004",
      type: "produce",
      prompt: "to get bored",
      accepted: ["annoiarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-005",
      type: "recognize",
      prompt: "innamorarsi (di)",
      accepted: ["to fall in love (with)", "to fall in love"],
      hint: "takes the preposition 'di' before the person",
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-006",
      type: "produce",
      prompt: "to fall in love (with someone)",
      accepted: ["innamorarsi (di)", "innamorarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-007",
      type: "recognize",
      prompt: "arrabbiarsi (con)",
      accepted: ["to get angry (with)", "to get angry"],
      hint: "takes the preposition 'con' before the person",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-008",
      type: "produce",
      prompt: "to get angry (with someone)",
      accepted: ["arrabbiarsi (con)", "arrabbiarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-009",
      type: "recognize",
      prompt: "preoccuparsi (per)",
      accepted: ["to worry (about)", "to worry"],
      hint: "takes the preposition 'per' before the cause of worry",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-010",
      type: "produce",
      prompt: "to worry (about something)",
      accepted: ["preoccuparsi (per)", "preoccuparsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-011",
      type: "recognize",
      prompt: "rilassarsi",
      accepted: ["to relax"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-012",
      type: "produce",
      prompt: "to relax",
      accepted: ["rilassarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-013",
      type: "recognize",
      prompt: "sentirsi",
      accepted: ["to feel"],
      hint: "used with an adjective: mi sento stanco = I feel tired",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-014",
      type: "produce",
      prompt: "to feel (+ adjective)",
      accepted: ["sentirsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-015",
      type: "recognize",
      prompt: "stancarsi (di)",
      accepted: ["to get tired (of)", "to get tired"],
      hint: "takes the preposition 'di'",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-016",
      type: "produce",
      prompt: "to get tired (of something)",
      accepted: ["stancarsi (di)", "stancarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-017",
      type: "recognize",
      prompt: "abituarsi (a)",
      accepted: ["to get used to", "to become accustomed to"],
      hint: "takes the preposition 'a'",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-018",
      type: "produce",
      prompt: "to get used to (something)",
      accepted: ["abituarsi (a)", "abituarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-019",
      type: "recognize",
      prompt: "sbagliarsi",
      accepted: ["to be wrong", "to make a mistake"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-020",
      type: "produce",
      prompt: "to be wrong / to make a mistake",
      accepted: ["sbagliarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-021",
      type: "recognize",
      prompt: "rendersi conto (di)",
      accepted: ["to realize", "to become aware (of)"],
      hint: "takes the preposition 'di'",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-022",
      type: "produce",
      prompt: "to realize",
      accepted: ["rendersi conto (di)", "rendersi conto"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-023",
      type: "recognize",
      prompt: "trovarsi (bene/male)",
      accepted: ["to feel comfortable (somewhere)", "to get along (in a situation)"],
      hint: "trovarsi bene = to feel at home/comfortable; trovarsi male = the opposite",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-024",
      type: "produce",
      prompt: "to feel at ease (in a place)",
      accepted: ["trovarsi bene", "trovarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-025",
      type: "recognize",
      prompt: "sposarsi (con)",
      accepted: ["to get married (to)", "to marry"],
      hint: "takes the preposition 'con' before the person",
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-026",
      type: "produce",
      prompt: "to get married (to someone)",
      accepted: ["sposarsi (con)", "sposarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-027",
      type: "recognize",
      prompt: "laurearsi (in)",
      accepted: ["to graduate (university, in a subject)", "to graduate"],
      hint: "takes the preposition 'in' before the subject studied",
      tags: ["reflexive", "verb", "education", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-028",
      type: "produce",
      prompt: "to graduate (in a subject)",
      accepted: ["laurearsi (in)", "laurearsi"],
      tags: ["reflexive", "verb", "education", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-029",
      type: "recognize",
      prompt: "ritrovarsi",
      accepted: ["to meet up again", "to find oneself"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-030",
      type: "produce",
      prompt: "to meet up again",
      accepted: ["ritrovarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-031",
      type: "recognize",
      prompt: "incontrarsi",
      accepted: ["to meet (each other)", "to meet up"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-032",
      type: "produce",
      prompt: "to meet (each other)",
      accepted: ["incontrarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-033",
      type: "recognize",
      prompt: "allontanarsi (da)",
      accepted: ["to move away (from)", "to distance oneself (from)"],
      hint: "takes the preposition 'da'",
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-034",
      type: "produce",
      prompt: "to move away (from) / to distance oneself (from)",
      accepted: ["allontanarsi (da)", "allontanarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-035",
      type: "recognize",
      prompt: "ricordarsi (di)",
      accepted: ["to remember"],
      hint: "takes the preposition 'di'",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-036",
      type: "produce",
      prompt: "to remember",
      accepted: ["ricordarsi (di)", "ricordarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-037",
      type: "recognize",
      prompt: "lamentarsi (di)",
      accepted: ["to complain (about)", "to complain"],
      hint: "takes the preposition 'di'",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-038",
      type: "produce",
      prompt: "to complain (about something)",
      accepted: ["lamentarsi (di)", "lamentarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-039",
      type: "recognize",
      prompt: "vergognarsi (di)",
      accepted: ["to be ashamed (of)", "to be embarrassed (about)"],
      hint: "takes the preposition 'di'",
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-040",
      type: "produce",
      prompt: "to be ashamed / embarrassed (about something)",
      accepted: ["vergognarsi (di)", "vergognarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-041",
      type: "recognize",
      prompt: "accorgersi (di)",
      accepted: ["to notice", "to realize"],
      hint: "irregular past participle: mi sono accorto/a; takes 'di'",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-042",
      type: "produce",
      prompt: "to notice / to realize",
      accepted: ["accorgersi (di)", "accorgersi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-043",
      type: "recognize",
      prompt: "lasciarsi",
      accepted: ["to break up (with each other)", "to split up"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-044",
      type: "produce",
      prompt: "to break up (with each other)",
      accepted: ["lasciarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-045",
      type: "recognize",
      prompt: "baciarsi",
      accepted: ["to kiss (each other)"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-046",
      type: "produce",
      prompt: "to kiss (each other)",
      accepted: ["baciarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-047",
      type: "recognize",
      prompt: "abbracciarsi",
      accepted: ["to hug (each other)"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-048",
      type: "produce",
      prompt: "to hug (each other)",
      accepted: ["abbracciarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-049",
      type: "recognize",
      prompt: "scusarsi (per)",
      accepted: ["to apologize (for)", "to apologize"],
      hint: "takes the preposition 'per'",
      tags: ["reflexive", "verb", "social", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-050",
      type: "produce",
      prompt: "to apologize (for something)",
      accepted: ["scusarsi (per)", "scusarsi"],
      tags: ["reflexive", "verb", "social", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-051",
      type: "recognize",
      prompt: "fidanzarsi (con)",
      accepted: ["to get engaged (to)", "to get engaged"],
      hint: "takes the preposition 'con'",
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-052",
      type: "produce",
      prompt: "to get engaged (to someone)",
      accepted: ["fidanzarsi (con)", "fidanzarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-053",
      type: "recognize",
      prompt: "separarsi (da)",
      accepted: ["to separate (from)"],
      hint: "takes the preposition 'da'",
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-054",
      type: "produce",
      prompt: "to separate (from someone)",
      accepted: ["separarsi (da)", "separarsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-055",
      type: "recognize",
      prompt: "conoscersi",
      accepted: ["to meet for the first time", "to get to know each other"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-056",
      type: "produce",
      prompt: "to get to know each other",
      accepted: ["conoscersi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-057",
      type: "recognize",
      prompt: "capirsi",
      accepted: ["to understand each other"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-058",
      type: "produce",
      prompt: "to understand each other",
      accepted: ["capirsi"],
      tags: ["reflexive", "verb", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-059",
      type: "recognize",
      prompt: "spaventarsi",
      accepted: ["to get scared", "to be frightened"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-060",
      type: "produce",
      prompt: "to get scared",
      accepted: ["spaventarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-061",
      type: "recognize",
      prompt: "calmarsi",
      accepted: ["to calm down"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-062",
      type: "produce",
      prompt: "to calm down",
      accepted: ["calmarsi"],
      tags: ["reflexive", "verb", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-063",
      type: "recognize",
      prompt: "confondersi",
      accepted: ["to get confused"],
      hint: "irregular past participle: mi sono confuso/a",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-064",
      type: "produce",
      prompt: "to get confused",
      accepted: ["confondersi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-065",
      type: "recognize",
      prompt: "distrarsi",
      accepted: ["to get distracted", "to take one's mind off things"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-066",
      type: "produce",
      prompt: "to get distracted / to take one's mind off things",
      accepted: ["distrarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-067",
      type: "recognize",
      prompt: "impegnarsi (in/a)",
      accepted: ["to commit oneself", "to make an effort"],
      hint: "takes 'in' before a project, 'a' before an infinitive",
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-068",
      type: "produce",
      prompt: "to commit oneself / to make an effort",
      accepted: ["impegnarsi (in/a)", "impegnarsi"],
      tags: ["reflexive", "verb", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-069",
      type: "recognize",
      prompt: "divertente",
      accepted: ["fun", "entertaining"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-070",
      type: "produce",
      prompt: "fun / entertaining",
      accepted: ["divertente"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-071",
      type: "recognize",
      prompt: "il divertimento",
      accepted: ["fun", "entertainment"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-072",
      type: "produce",
      prompt: "fun / entertainment (noun)",
      accepted: ["il divertimento"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-073",
      type: "recognize",
      prompt: "noioso/a",
      accepted: ["boring"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-074",
      type: "produce",
      prompt: "boring",
      accepted: ["noioso"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-075",
      type: "recognize",
      prompt: "la noia",
      accepted: ["boredom"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-076",
      type: "produce",
      prompt: "boredom",
      accepted: ["la noia"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-077",
      type: "recognize",
      prompt: "innamorato/a",
      accepted: ["in love"],
      tags: ["adjective", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-078",
      type: "produce",
      prompt: "in love",
      accepted: ["innamorato"],
      tags: ["adjective", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-079",
      type: "recognize",
      prompt: "arrabbiato/a",
      accepted: ["angry"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-080",
      type: "produce",
      prompt: "angry",
      accepted: ["arrabbiato"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-081",
      type: "recognize",
      prompt: "la rabbia",
      accepted: ["anger"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-082",
      type: "produce",
      prompt: "anger",
      accepted: ["la rabbia"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-083",
      type: "recognize",
      prompt: "preoccupato/a",
      accepted: ["worried"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-084",
      type: "produce",
      prompt: "worried",
      accepted: ["preoccupato"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-085",
      type: "recognize",
      prompt: "la preoccupazione",
      accepted: ["worry", "concern"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-086",
      type: "produce",
      prompt: "worry / concern",
      accepted: ["la preoccupazione"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-087",
      type: "recognize",
      prompt: "rilassato/a",
      accepted: ["relaxed"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-088",
      type: "produce",
      prompt: "relaxed",
      accepted: ["rilassato"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-089",
      type: "recognize",
      prompt: "rilassante",
      accepted: ["relaxing"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-090",
      type: "produce",
      prompt: "relaxing",
      accepted: ["rilassante"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-091",
      type: "recognize",
      prompt: "stanco/a",
      accepted: ["tired"],
      tags: ["adjective", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-092",
      type: "produce",
      prompt: "tired",
      accepted: ["stanco"],
      tags: ["adjective", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-093",
      type: "recognize",
      prompt: "la stanchezza",
      accepted: ["tiredness", "fatigue"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-094",
      type: "produce",
      prompt: "tiredness / fatigue",
      accepted: ["la stanchezza"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-095",
      type: "recognize",
      prompt: "lo sbaglio",
      accepted: ["mistake", "error"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-096",
      type: "produce",
      prompt: "mistake / error",
      accepted: ["lo sbaglio"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-097",
      type: "recognize",
      prompt: "il matrimonio",
      accepted: ["marriage", "wedding"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-098",
      type: "produce",
      prompt: "marriage / wedding",
      accepted: ["il matrimonio"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-099",
      type: "recognize",
      prompt: "la laurea",
      accepted: ["university degree", "degree"],
      tags: ["noun", "education", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-100",
      type: "produce",
      prompt: "university degree",
      accepted: ["la laurea"],
      tags: ["noun", "education", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-101",
      type: "recognize",
      prompt: "il ricordo",
      accepted: ["memory", "recollection"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-102",
      type: "produce",
      prompt: "memory (a recollection)",
      accepted: ["il ricordo"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-103",
      type: "recognize",
      prompt: "vergognoso/a",
      accepted: ["shy", "embarrassing"],
      hint: "context decides: shy (of a person) or embarrassing (of a situation)",
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-104",
      type: "produce",
      prompt: "shy / embarrassing",
      accepted: ["vergognoso"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-105",
      type: "recognize",
      prompt: "la vergogna",
      accepted: ["shame", "embarrassment"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-106",
      type: "produce",
      prompt: "shame / embarrassment",
      accepted: ["la vergogna"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-107",
      type: "recognize",
      prompt: "il bacio",
      accepted: ["kiss"],
      hint: "plural: i baci",
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-108",
      type: "produce",
      prompt: "kiss",
      accepted: ["il bacio"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-109",
      type: "recognize",
      prompt: "l'abbraccio",
      accepted: ["hug"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-110",
      type: "produce",
      prompt: "hug",
      accepted: ["l'abbraccio"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-111",
      type: "recognize",
      prompt: "la coppia",
      accepted: ["couple"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-112",
      type: "produce",
      prompt: "couple",
      accepted: ["la coppia"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-113",
      type: "recognize",
      prompt: "la lite",
      accepted: ["quarrel", "argument"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-114",
      type: "produce",
      prompt: "quarrel / argument",
      accepted: ["la lite"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-115",
      type: "recognize",
      prompt: "il fidanzato / la fidanzata",
      accepted: ["boyfriend / fiancé", "girlfriend / fiancée", "boyfriend", "girlfriend"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-116",
      type: "produce",
      prompt: "boyfriend/girlfriend (or fiancé/fiancée)",
      accepted: ["il fidanzato", "la fidanzata"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-117",
      type: "recognize",
      prompt: "la separazione",
      accepted: ["separation"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-118",
      type: "produce",
      prompt: "separation",
      accepted: ["la separazione"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-119",
      type: "recognize",
      prompt: "il divorzio",
      accepted: ["divorce"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-120",
      type: "produce",
      prompt: "divorce",
      accepted: ["il divorzio"],
      tags: ["noun", "relationship", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-121",
      type: "recognize",
      prompt: "la paura",
      accepted: ["fear"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-122",
      type: "produce",
      prompt: "fear",
      accepted: ["la paura"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-123",
      type: "recognize",
      prompt: "calmo/a",
      accepted: ["calm"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-124",
      type: "produce",
      prompt: "calm",
      accepted: ["calmo"],
      tags: ["adjective", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-125",
      type: "recognize",
      prompt: "la solitudine",
      accepted: ["loneliness", "solitude"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-126",
      type: "produce",
      prompt: "loneliness / solitude",
      accepted: ["la solitudine"],
      tags: ["noun", "emotion", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-127",
      type: "recognize",
      prompt: "la confusione",
      accepted: ["confusion"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-128",
      type: "produce",
      prompt: "confusion",
      accepted: ["la confusione"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-129",
      type: "recognize",
      prompt: "l'impegno",
      accepted: ["commitment", "effort"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },
    {
      id: "a227-t1-130",
      type: "produce",
      prompt: "commitment / effort",
      accepted: ["l'impegno"],
      tags: ["noun", "state", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (reflexive pronoun & preposition drills) ────────────
    {
      id: "a227-t2-001",
      type: "fill_blank",
      prompt: "___ diverto molto quando esco con gli amici il sabato sera.",
      accepted: ["Mi"],
      hint: "reflexive pronoun for 'io' — divertirsi conjugates as mi diverto, ti diverti, si diverte",
      tags: ["fill_blank", "reflexive-pronoun", "divertirsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-001"],
    },
    {
      id: "a227-t2-002",
      type: "fill_blank",
      prompt: "Quando piove per tutto il weekend, ___ annoiamo a stare sempre in casa.",
      accepted: ["ci"],
      hint: "reflexive pronoun for 'noi' — ci annoiamo",
      tags: ["fill_blank", "reflexive-pronoun", "annoiarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-003"],
    },
    {
      id: "a227-t2-003",
      type: "fill_blank",
      prompt: "Si è innamorato ___ una ragazza conosciuta durante il viaggio in treno.",
      accepted: ["di"],
      hint: "innamorarsi di qualcuno — the preposition is always 'di'",
      tags: ["fill_blank", "preposition", "innamorarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-005"],
    },
    {
      id: "a227-t2-004",
      type: "fill_blank",
      prompt: "Mio padre si arrabbia sempre ___ me quando torno a casa dopo mezzanotte.",
      accepted: ["con"],
      hint: "arrabbiarsi con qualcuno — angry with someone takes 'con'",
      tags: ["fill_blank", "preposition", "arrabbiarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-007"],
    },
    {
      id: "a227-t2-005",
      type: "fill_blank",
      prompt: "I miei genitori si preoccupano troppo ___ il mio futuro lavorativo.",
      accepted: ["per"],
      hint: "preoccuparsi per qualcosa — worry about something takes 'per'",
      tags: ["fill_blank", "preposition", "preoccuparsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-009"],
    },
    {
      id: "a227-t2-006",
      type: "fill_blank",
      prompt: "___ sei già abituato al caos del centro città?",
      accepted: ["Ti"],
      hint: "reflexive pronoun for 'tu' — ti abitui, ti sei abituato",
      tags: ["fill_blank", "reflexive-pronoun", "abituarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-017"],
    },
    {
      id: "a227-t2-007",
      type: "fill_blank",
      prompt: "Dopo un anno mi sono abituata ___ nuovo orario di lavoro notturno.",
      accepted: ["al"],
      hint: "abituarsi a + noun; a + il = al",
      tags: ["fill_blank", "preposition", "abituarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-017"],
    },
    {
      id: "a227-t2-008",
      type: "fill_blank",
      prompt: "Ci siamo stancati ___ aspettare l'autobus in ritardo ogni singola mattina.",
      accepted: ["di"],
      hint: "stancarsi di qualcosa — to get tired of something takes 'di'",
      tags: ["fill_blank", "preposition", "stancarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-015"],
    },
    {
      id: "a227-t2-009",
      type: "fill_blank",
      prompt: "Mi sono reso conto ___ aver sbagliato solo quando ho visto la sua faccia.",
      accepted: ["di"],
      hint: "rendersi conto di qualcosa — to realize something takes 'di'",
      tags: ["fill_blank", "preposition", "rendersi-conto", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-021"],
    },
    {
      id: "a227-t2-010",
      type: "fill_blank",
      prompt: "Mia sorella si è laureata ___ Economia lo scorso giugno, con il massimo dei voti.",
      accepted: ["in"],
      hint: "laurearsi in + subject — to graduate in a field takes 'in'",
      tags: ["fill_blank", "preposition", "laurearsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-027"],
    },
    {
      id: "a227-t2-011",
      type: "fill_blank",
      prompt: "Alla fine si è sposato ___ la sua compagna di banco delle superiori.",
      accepted: ["con"],
      hint: "sposarsi con qualcuno — to marry someone takes 'con'",
      tags: ["fill_blank", "preposition", "sposarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-025"],
    },
    {
      id: "a227-t2-012",
      type: "fill_blank",
      prompt: "___ trovate bene nella nuova casa o preferivate quella vecchia?",
      accepted: ["Vi"],
      hint: "reflexive pronoun for 'voi' — vi trovate bene",
      tags: ["fill_blank", "reflexive-pronoun", "trovarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-023"],
    },
    {
      id: "a227-t2-013",
      type: "fill_blank",
      prompt: "Negli ultimi mesi si è allontanata ___ tutte le sue vecchie amicizie.",
      accepted: ["da"],
      hint: "allontanarsi da qualcosa/qualcuno — to move away from takes 'da'",
      tags: ["fill_blank", "preposition", "allontanarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-033"],
    },
    {
      id: "a227-t2-014",
      type: "fill_blank",
      prompt: "Luca e Sara ___ incontrano ogni venerdì sera per studiare insieme in biblioteca.",
      accepted: ["si"],
      hint: "reflexive pronoun for 'loro' — si incontrano",
      tags: ["fill_blank", "reflexive-pronoun", "incontrarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-031"],
    },
    {
      id: "a227-t2-015",
      type: "fill_blank",
      prompt: "Si è impegnato molto ___ questo progetto durante tutta l'estate.",
      accepted: ["in"],
      hint: "impegnarsi in qualcosa — to commit to something takes 'in'",
      tags: ["fill_blank", "preposition", "impegnarsi", "A2"],
      tier: 2,
      prerequisites: ["a227-t1-067"],
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a227-t3-001",
      type: "produce",
      prompt: "We broke up after three years together.",
      accepted: ["Ci siamo lasciati dopo tre anni insieme.", "Ci siamo lasciate dopo tre anni insieme."],
      hint: "lasciarsi (reciprocal reflexive) + passato prossimo with essere; agreement follows the subject's gender",
      tags: ["chunk", "relationship", "breakup", "passato-prossimo", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-043"],
    },
    {
      id: "a227-t3-002",
      type: "produce",
      prompt: "I didn't realize it was already so late.",
      accepted: [
        "Non mi sono reso conto che era già così tardi.",
        "Non mi sono resa conto che era già così tardi.",
        "Non mi sono accorto che era già così tardi.",
        "Non mi sono accorta che era già così tardi.",
      ],
      hint: "rendersi conto che / accorgersi che + imperfetto (era) for a background fact — no subjunctive needed after 'che' here",
      tags: ["chunk", "realization", "imperfetto", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-021", "a227-t1-041"],
    },
    {
      id: "a227-t3-003",
      type: "produce",
      prompt: "They got engaged last summer and will marry in the spring.",
      accepted: [
        "Si sono fidanzati l'estate scorsa e si sposeranno in primavera.",
        "Si sono fidanzati la scorsa estate e si sposeranno in primavera.",
      ],
      hint: "fidanzarsi (passato prossimo) + sposarsi (futuro semplice)",
      tags: ["chunk", "relationship", "future", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-051", "a227-t1-025"],
    },
    {
      id: "a227-t3-004",
      type: "produce",
      prompt: "I always get bored during long meetings at work.",
      accepted: [
        "Mi annoio sempre durante le riunioni lunghe al lavoro.",
        "Mi annoio sempre nelle riunioni lunghe al lavoro.",
      ],
      hint: "present tense for habitual actions; 'durante' or 'in/nelle' both work for 'during'",
      tags: ["chunk", "boredom", "habit", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-003"],
    },
    {
      id: "a227-t3-005",
      type: "produce",
      prompt: "You should apologize to your sister instead of complaining all the time.",
      accepted: [
        "Dovresti scusarti con tua sorella invece di lamentarti sempre.",
        "Dovresti scusarti con tua sorella invece di lamentarti in continuazione.",
      ],
      hint: "scusarsi con qualcuno; condizionale of dovere + infinitive",
      tags: ["chunk", "apology", "conditional", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-049", "a227-t1-037"],
    },
    {
      id: "a227-t3-006",
      type: "produce",
      prompt: "We've known each other since we were children.",
      accepted: ["Ci conosciamo da quando eravamo bambini.", "Ci conosciamo fin da quando eravamo bambini."],
      hint: "conoscersi (reciprocal, present) + da quando + imperfetto",
      tags: ["chunk", "friendship", "imperfetto", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-055"],
    },
    {
      id: "a227-t3-007",
      type: "produce",
      prompt: "He never gets used to the cold winters here.",
      accepted: ["Non si abitua mai agli inverni freddi qui.", "Non si abitua mai al freddo inverno qui."],
      hint: "abituarsi a + noun; a + gli = agli",
      tags: ["chunk", "preposition", "weather", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-017"],
    },
    {
      id: "a227-t3-008",
      type: "produce",
      prompt: "I'm embarrassed about what happened at the party.",
      accepted: [
        "Mi vergogno di quello che è successo alla festa.",
        "Mi vergogno per quello che è successo alla festa.",
      ],
      hint: "vergognarsi di/per + relative clause",
      tags: ["chunk", "embarrassment", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-039"],
    },
    {
      id: "a227-t3-009",
      type: "produce",
      prompt: "After the divorce, they still see each other for the kids' sake.",
      accepted: [
        "Dopo il divorzio, si vedono ancora per il bene dei figli.",
        "Dopo il divorzio, si incontrano ancora per il bene dei figli.",
      ],
      hint: "'per il bene di' = for the sake of; reciprocal verb + present tense",
      tags: ["chunk", "family", "divorce", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-119", "a227-t1-031"],
    },
    {
      id: "a227-t3-010",
      type: "produce",
      prompt: "My grandparents have never separated, not even once.",
      accepted: [
        "I miei nonni non si sono mai separati, nemmeno una volta.",
        "I miei nonni non si sono mai separati, neanche una volta.",
      ],
      hint: "separarsi (passato prossimo) + mai + nemmeno/neanche una volta",
      tags: ["chunk", "family", "passato-prossimo", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-053"],
    },
    {
      id: "a227-t3-011",
      type: "produce",
      prompt: "She gets scared every time she watches a horror film alone.",
      accepted: [
        "Si spaventa ogni volta che guarda un film horror da sola.",
        "Si spaventa ogni volta che vede un film horror da sola.",
      ],
      hint: "spaventarsi (present, reflexive) + ogni volta che",
      tags: ["chunk", "fear", "habit", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-059"],
    },
    {
      id: "a227-t3-012",
      type: "produce",
      prompt: "Take a deep breath and try to calm down.",
      accepted: ["Fai un respiro profondo e cerca di calmarti.", "Respira profondamente e cerca di calmarti."],
      hint: "calmarsi in the infinitive after 'cercare di'; imperative fai/respira for 'tu'",
      tags: ["chunk", "calm", "imperative", "A2"],
      tier: 3,
      prerequisites: ["a227-t1-061"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a227-t4-001",
      type: "passage_cloze",
      prompt:
        "Elena e Marco si sono conosciuti a una festa di compleanno tre anni fa.\nAll'inizio erano solo amici, ma dopo qualche mese si sono resi conto di provare qualcosa di più forte.\nSi sono innamorati piano piano, parlando ogni sera al telefono fino a tardi.\nL'anno scorso Marco si è inginocchiato in riva al mare e Elena ha detto sì subito.\nAdesso si stanno preparando per il grande giorno: il ___ sarà a settembre, in un piccolo paese in Toscana.\nTutti i loro amici non vedono l'ora di festeggiare insieme a loro.",
      accepted: ["matrimonio"],
      hint: "the ceremony they are preparing for in September — not the ring, the event itself",
      tags: ["passage_cloze", "relationship", "wedding", "A2"],
      tier: 4,
      prerequisites: ["a227-t1-055", "a227-t1-005", "a227-t1-021", "a227-t1-097"],
    },
    {
      id: "a227-t4-002",
      type: "passage_cloze",
      prompt:
        "Da qualche settimana Giulia si sente sempre stanca quando torna dall'ufficio.\nSi preoccupa troppo per le scadenze e si arrabbia facilmente con i colleghi.\nUna sera si rende conto che ha bisogno di una pausa vera, non solo di un weekend.\nDecide di prenotare una settimana in montagna, lontano dal computer e dal telefono.\nLì cammina tra i boschi ogni mattina e la sera legge un libro davanti al camino.\nÈ una vacanza incredibilmente ___: torna a casa con più energia di prima.",
      accepted: ["rilassante"],
      hint: "an adjective describing the kind of vacation that calms you down and restores energy",
      tags: ["passage_cloze", "stress", "relax", "A2"],
      tier: 4,
      prerequisites: ["a227-t1-091", "a227-t1-009", "a227-t1-007", "a227-t1-089"],
    },
    {
      id: "a227-t4-003",
      type: "passage_cloze",
      prompt:
        "Sofia e Chiara erano compagne di stanza all'università e sembravano inseparabili.\nPoi hanno cominciato a lamentarsi continuamente l'una dell'altra per le piccole cose di casa.\nDopo una lite furiosa per i piatti sporchi, Sofia si è allontanata da Chiara per mesi.\nOgni volta che pensava a quella sera, sentiva ancora la ___ salire dentro di sé.\nUn giorno, per caso, si sono incontrate a un matrimonio di un'amica comune e hanno parlato per ore.\nAlla fine si sono abbracciate e hanno deciso di ricominciare da capo.",
      accepted: ["rabbia"],
      hint: "the emotion Sofia still felt when she thought about that night — anger",
      tags: ["passage_cloze", "friendship", "conflict", "emotion", "A2"],
      tier: 4,
      prerequisites: ["a227-t1-037", "a227-t1-033", "a227-t1-113", "a227-t1-047", "a227-t1-081"],
    },
    {
      id: "a227-t4-004",
      type: "passage_cloze",
      prompt:
        "Dopo la laurea in Ingegneria, Marta si è trasferita da sola in una città che non conosceva.\nI primi mesi sono stati difficili: non conosceva nessuno e si sentiva persa nel nuovo appartamento vuoto.\nLa sera, tornando dal lavoro, sentiva un peso pesante di ___ che non riusciva a scacciare.\nPoco alla volta si è iscritta a un corso di ceramica e ha conosciuto altre persone.\nAdesso si è abituata al ritmo della città e ha anche trovato un gruppo di amici veri.\nGuardando indietro, capisce che quel periodo difficile l'ha resa più forte.",
      accepted: ["solitudine"],
      hint: "the heavy feeling Marta couldn't shake off in the evenings — loneliness",
      tags: ["passage_cloze", "loneliness", "new-city", "A2"],
      tier: 4,
      prerequisites: ["a227-t1-027", "a227-t1-017", "a227-t1-125"],
    },
    {
      id: "a227-t4-005",
      type: "passage_cloze",
      prompt:
        "Prima dell'esame di stato, Davide non riusciva a dormire per l'ansia.\nOgni notte si svegliava di colpo, con il cuore che batteva forte e la mente piena di dubbi.\nSua sorella, che aveva già superato lo stesso esame, gli ha detto di fare un respiro profondo e calmarsi.\nLa mattina dell'esame, seduto fuori dall'aula, sentiva ancora una ___ enorme, ma ha deciso di entrare comunque.\nAlla fine è andato tutto bene, molto meglio di quello che pensava.\nOggi Davide ride ricordando quanto si era spaventato per niente.",
      accepted: ["paura"],
      hint: "the emotion Davide still felt while sitting outside the exam room — fear",
      tags: ["passage_cloze", "fear", "exam", "A2"],
      tier: 4,
      prerequisites: ["a227-t1-061", "a227-t1-059", "a227-t1-121"],
    },
  ],
};
export default unit;
