import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-24-adjectives-ii",
  name: "Descriptive Adjectives",
  level: "A2",
  theme: "Qualities, States & Descriptions",
  emoji: "✨",
  prerequisiteUnits: ["a2-unit-23-numbers-ii"],
  cards: [
    // ── Tier 1 – Vocabulary (antonym pairs & standalone) ─────────────────────
    {
      id: "a224-t1-001",
      type: "recognize",
      prompt: "sporco",
      accepted: ["dirty", "filthy"],
      hint: "opposite of pulito",
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "a224-t1-002",
      type: "recognize",
      prompt: "pulito",
      accepted: ["clean"],
      hint: "opposite of sporco",
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "a224-t1-003",
      type: "recognize",
      prompt: "caldo",
      accepted: ["hot", "warm"],
      hint: "opposite of freddo",
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "a224-t1-004",
      type: "recognize",
      prompt: "freddo",
      accepted: ["cold"],
      hint: "opposite of caldo",
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "a224-t1-005",
      type: "recognize",
      prompt: "bagnato",
      accepted: ["wet", "soaked", "damp"],
      hint: "opposite of asciutto",
      tags: ["adjective", "moisture"],
      tier: 1,
    },
    {
      id: "a224-t1-006",
      type: "recognize",
      prompt: "asciutto",
      accepted: ["dry"],
      hint: "opposite of bagnato",
      tags: ["adjective", "moisture"],
      tier: 1,
    },
    {
      id: "a224-t1-007",
      type: "recognize",
      prompt: "rotto",
      accepted: ["broken"],
      hint: "opposite of integro",
      tags: ["adjective", "condition"],
      tier: 1,
    },
    {
      id: "a224-t1-008",
      type: "recognize",
      prompt: "integro",
      accepted: ["intact", "whole", "undamaged"],
      hint: "opposite of rotto",
      tags: ["adjective", "condition"],
      tier: 1,
    },
    {
      id: "a224-t1-009",
      type: "recognize",
      prompt: "morbido",
      accepted: ["soft"],
      hint: "opposite of duro",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-010",
      type: "recognize",
      prompt: "duro",
      accepted: ["hard", "tough", "firm"],
      hint: "opposite of morbido",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-011",
      type: "recognize",
      prompt: "dolce",
      accepted: ["sweet"],
      hint: "opposite of amaro; also means 'gentle'",
      tags: ["adjective", "taste"],
      tier: 1,
    },
    {
      id: "a224-t1-012",
      type: "recognize",
      prompt: "amaro",
      accepted: ["bitter"],
      hint: "opposite of dolce",
      tags: ["adjective", "taste"],
      tier: 1,
    },
    {
      id: "a224-t1-013",
      type: "recognize",
      prompt: "salato",
      accepted: ["salty", "salted"],
      hint: "from 'sale' (salt)",
      tags: ["adjective", "taste"],
      tier: 1,
    },
    {
      id: "a224-t1-014",
      type: "recognize",
      prompt: "giovane",
      accepted: ["young"],
      hint: "opposite of anziano; same form m/f",
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "a224-t1-015",
      type: "recognize",
      prompt: "anziano",
      accepted: ["elderly", "old", "aged"],
      hint: "opposite of giovane; used for people",
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "a224-t1-016",
      type: "recognize",
      prompt: "forte",
      accepted: ["strong", "loud"],
      hint: "opposite of debole; same form m/f",
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "a224-t1-017",
      type: "recognize",
      prompt: "debole",
      accepted: ["weak"],
      hint: "opposite of forte; same form m/f",
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "a224-t1-018",
      type: "recognize",
      prompt: "grasso",
      accepted: ["fat", "fatty", "greasy"],
      hint: "opposite of magro",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-019",
      type: "recognize",
      prompt: "magro",
      accepted: ["thin", "slim", "lean"],
      hint: "opposite of grasso",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-020",
      type: "recognize",
      prompt: "lungo",
      accepted: ["long"],
      hint: "opposite of corto",
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "a224-t1-021",
      type: "recognize",
      prompt: "corto",
      accepted: ["short (in length)"],
      hint: "opposite of lungo; not used for height",
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "a224-t1-022",
      type: "recognize",
      prompt: "stretto",
      accepted: ["narrow", "tight"],
      hint: "opposite of largo",
      tags: ["adjective", "width"],
      tier: 1,
    },
    {
      id: "a224-t1-023",
      type: "recognize",
      prompt: "largo",
      accepted: ["wide", "broad"],
      hint: "opposite of stretto",
      tags: ["adjective", "width"],
      tier: 1,
    },
    {
      id: "a224-t1-024",
      type: "recognize",
      prompt: "pieno",
      accepted: ["full"],
      hint: "opposite of vuoto",
      tags: ["adjective", "volume"],
      tier: 1,
    },
    {
      id: "a224-t1-025",
      type: "recognize",
      prompt: "vuoto",
      accepted: ["empty"],
      hint: "opposite of pieno",
      tags: ["adjective", "volume"],
      tier: 1,
    },
    {
      id: "a224-t1-026",
      type: "recognize",
      prompt: "utile",
      accepted: ["useful", "helpful"],
      hint: "same form m/f",
      tags: ["adjective", "utility"],
      tier: 1,
    },
    {
      id: "a224-t1-027",
      type: "recognize",
      prompt: "necessario",
      accepted: ["necessary"],
      hint: "necessario/necessaria",
      tags: ["adjective", "utility"],
      tier: 1,
    },
    {
      id: "a224-t1-028",
      type: "recognize",
      prompt: "possibile",
      accepted: ["possible"],
      hint: "same form m/f; opposite: impossibile",
      tags: ["adjective", "possibility"],
      tier: 1,
    },
    {
      id: "a224-t1-029",
      type: "recognize",
      prompt: "impossibile",
      accepted: ["impossible"],
      hint: "same form m/f",
      tags: ["adjective", "possibility"],
      tier: 1,
    },
    {
      id: "a224-t1-030",
      type: "recognize",
      prompt: "ovvio",
      accepted: ["obvious"],
      hint: "ovvio/ovvia",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-031",
      type: "recognize",
      prompt: "strano",
      accepted: ["strange", "weird", "odd"],
      hint: "strano/strana",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-032",
      type: "recognize",
      prompt: "normale",
      accepted: ["normal", "ordinary"],
      hint: "same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },

    // ── Tier 1 – Vocabulary (expansion: texture, quality & size) ────────────
    {
      id: "a224-t1-033",
      type: "recognize",
      prompt: "liscio",
      accepted: ["smooth"],
      hint: "opposite of ruvido",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-034",
      type: "recognize",
      prompt: "ruvido",
      accepted: ["rough"],
      hint: "opposite of liscio",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-035",
      type: "recognize",
      prompt: "pesante",
      accepted: ["heavy"],
      hint: "opposite of leggero; same form m/f",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "a224-t1-036",
      type: "recognize",
      prompt: "leggero",
      accepted: ["light", "lightweight"],
      hint: "opposite of pesante",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "a224-t1-037",
      type: "recognize",
      prompt: "spesso",
      accepted: ["thick"],
      hint: "opposite of sottile; also means 'often' as an adverb",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-038",
      type: "recognize",
      prompt: "sottile",
      accepted: ["thin", "slim (flat objects)"],
      hint: "opposite of spesso; same form m/f",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-039",
      type: "recognize",
      prompt: "alto",
      accepted: ["tall", "high"],
      hint: "opposite of basso",
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "a224-t1-040",
      type: "recognize",
      prompt: "basso",
      accepted: ["short (in height)", "low"],
      hint: "opposite of alto",
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "a224-t1-041",
      type: "recognize",
      prompt: "grande",
      accepted: ["big", "large"],
      hint: "opposite of piccolo; same form m/f",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-042",
      type: "recognize",
      prompt: "piccolo",
      accepted: ["small", "little"],
      hint: "opposite of grande",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-043",
      type: "recognize",
      prompt: "profondo",
      accepted: ["deep"],
      hint: "opposite of superficiale",
      tags: ["adjective", "depth"],
      tier: 1,
    },
    {
      id: "a224-t1-044",
      type: "recognize",
      prompt: "superficiale",
      accepted: ["shallow", "superficial"],
      hint: "opposite of profondo; same form m/f",
      tags: ["adjective", "depth"],
      tier: 1,
    },
    {
      id: "a224-t1-045",
      type: "recognize",
      prompt: "robusto",
      accepted: ["sturdy", "robust"],
      hint: "opposite of fragile",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-046",
      type: "recognize",
      prompt: "fragile",
      accepted: ["fragile"],
      hint: "opposite of robusto; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-047",
      type: "recognize",
      prompt: "ricco",
      accepted: ["rich", "wealthy"],
      hint: "opposite of povero",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-048",
      type: "recognize",
      prompt: "povero",
      accepted: ["poor"],
      hint: "opposite of ricco",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-049",
      type: "recognize",
      prompt: "semplice",
      accepted: ["simple"],
      hint: "opposite of complicato; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-050",
      type: "recognize",
      prompt: "complicato",
      accepted: ["complicated"],
      hint: "opposite of semplice",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-051",
      type: "recognize",
      prompt: "fresco",
      accepted: ["fresh", "cool"],
      hint: "opposite of stantio",
      tags: ["adjective", "freshness"],
      tier: 1,
    },
    {
      id: "a224-t1-052",
      type: "recognize",
      prompt: "stantio",
      accepted: ["stale"],
      hint: "opposite of fresco; used for bread, air",
      tags: ["adjective", "freshness"],
      tier: 1,
    },
    {
      id: "a224-t1-053",
      type: "recognize",
      prompt: "nuovo",
      accepted: ["new"],
      hint: "opposite of vecchio",
      tags: ["adjective", "condition"],
      tier: 1,
    },
    {
      id: "a224-t1-054",
      type: "recognize",
      prompt: "vecchio",
      accepted: ["old"],
      hint: "opposite of nuovo; used for objects and people",
      tags: ["adjective", "condition"],
      tier: 1,
    },
    {
      id: "a224-t1-055",
      type: "recognize",
      prompt: "moderno",
      accepted: ["modern"],
      hint: "opposite of antico",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-056",
      type: "recognize",
      prompt: "antico",
      accepted: ["ancient", "antique"],
      hint: "opposite of moderno",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-057",
      type: "recognize",
      prompt: "comodo",
      accepted: ["comfortable"],
      hint: "opposite of scomodo",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-058",
      type: "recognize",
      prompt: "scomodo",
      accepted: ["uncomfortable"],
      hint: "opposite of comodo",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-059",
      type: "recognize",
      prompt: "chiaro",
      accepted: ["light (color)", "bright", "clear"],
      hint: "opposite of scuro",
      tags: ["adjective", "color"],
      tier: 1,
    },
    {
      id: "a224-t1-060",
      type: "recognize",
      prompt: "scuro",
      accepted: ["dark"],
      hint: "opposite of chiaro",
      tags: ["adjective", "color"],
      tier: 1,
    },
    {
      id: "a224-t1-061",
      type: "recognize",
      prompt: "rumoroso",
      accepted: ["noisy"],
      hint: "opposite of silenzioso",
      tags: ["adjective", "sound"],
      tier: 1,
    },
    {
      id: "a224-t1-062",
      type: "recognize",
      prompt: "silenzioso",
      accepted: ["silent", "quiet"],
      hint: "opposite of rumoroso",
      tags: ["adjective", "sound"],
      tier: 1,
    },
    {
      id: "a224-t1-063",
      type: "recognize",
      prompt: "trasparente",
      accepted: ["transparent", "clear"],
      hint: "opposite of opaco; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-064",
      type: "recognize",
      prompt: "opaco",
      accepted: ["opaque"],
      hint: "opposite of trasparente",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-065",
      type: "recognize",
      prompt: "tondo",
      accepted: ["round"],
      hint: "opposite of quadrato",
      tags: ["adjective", "shape"],
      tier: 1,
    },
    {
      id: "a224-t1-066",
      type: "recognize",
      prompt: "quadrato",
      accepted: ["square"],
      hint: "opposite of tondo",
      tags: ["adjective", "shape"],
      tier: 1,
    },
    {
      id: "a224-t1-067",
      type: "recognize",
      prompt: "elastico",
      accepted: ["elastic", "stretchy"],
      hint: "opposite of rigido",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-068",
      type: "recognize",
      prompt: "rigido",
      accepted: ["rigid", "stiff"],
      hint: "opposite of elastico",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-069",
      type: "recognize",
      prompt: "delicato",
      accepted: ["delicate"],
      hint: "opposite of resistente",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-070",
      type: "recognize",
      prompt: "resistente",
      accepted: ["resistant", "sturdy", "durable"],
      hint: "opposite of delicato; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-071",
      type: "recognize",
      prompt: "spazioso",
      accepted: ["spacious"],
      hint: "opposite of angusto",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-072",
      type: "recognize",
      prompt: "angusto",
      accepted: ["cramped", "narrow (space)"],
      hint: "opposite of spazioso",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-073",
      type: "recognize",
      prompt: "ordinato",
      accepted: ["tidy", "organized"],
      hint: "opposite of disordinato",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-074",
      type: "recognize",
      prompt: "disordinato",
      accepted: ["messy", "disorganized"],
      hint: "opposite of ordinato",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-075",
      type: "recognize",
      prompt: "veloce",
      accepted: ["fast", "quick"],
      hint: "opposite of lento; same form m/f",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "a224-t1-076",
      type: "recognize",
      prompt: "lento",
      accepted: ["slow"],
      hint: "opposite of veloce",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "a224-t1-077",
      type: "recognize",
      prompt: "facile",
      accepted: ["easy"],
      hint: "opposite of difficile; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-078",
      type: "recognize",
      prompt: "difficile",
      accepted: ["difficult", "hard"],
      hint: "opposite of facile; same form m/f",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-079",
      type: "recognize",
      prompt: "caro",
      accepted: ["expensive", "dear"],
      hint: "opposite of economico",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "a224-t1-080",
      type: "recognize",
      prompt: "economico",
      accepted: ["cheap", "economical", "inexpensive"],
      hint: "opposite of caro",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "a224-t1-081",
      type: "recognize",
      prompt: "denso",
      accepted: ["dense", "thick (liquid)"],
      hint: "opposite of fluido",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-082",
      type: "recognize",
      prompt: "fluido",
      accepted: ["fluid", "runny"],
      hint: "opposite of denso",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-083",
      type: "recognize",
      prompt: "croccante",
      accepted: ["crunchy", "crispy"],
      hint: "opposite of spugnoso; same form m/f",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-084",
      type: "recognize",
      prompt: "spugnoso",
      accepted: ["spongy"],
      hint: "opposite of croccante",
      tags: ["adjective", "texture"],
      tier: 1,
    },
    {
      id: "a224-t1-085",
      type: "recognize",
      prompt: "liquido",
      accepted: ["liquid"],
      hint: "opposite of solido",
      tags: ["adjective", "state"],
      tier: 1,
    },
    {
      id: "a224-t1-086",
      type: "recognize",
      prompt: "solido",
      accepted: ["solid"],
      hint: "opposite of liquido",
      tags: ["adjective", "state"],
      tier: 1,
    },
    {
      id: "a224-t1-087",
      type: "recognize",
      prompt: "minuscolo",
      accepted: ["tiny"],
      hint: "opposite of enorme",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-088",
      type: "recognize",
      prompt: "enorme",
      accepted: ["enormous", "huge"],
      hint: "opposite of minuscolo; same form m/f",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "a224-t1-089",
      type: "recognize",
      prompt: "sano",
      accepted: ["healthy"],
      hint: "opposite of malsano",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-090",
      type: "recognize",
      prompt: "malsano",
      accepted: ["unhealthy"],
      hint: "opposite of sano",
      tags: ["adjective", "quality"],
      tier: 1,
    },
    {
      id: "a224-t1-091",
      type: "recognize",
      prompt: "acceso",
      accepted: ["turned on", "lit"],
      hint: "opposite of spento",
      tags: ["adjective", "state"],
      tier: 1,
    },
    {
      id: "a224-t1-092",
      type: "recognize",
      prompt: "spento",
      accepted: ["turned off", "extinguished"],
      hint: "opposite of acceso",
      tags: ["adjective", "state"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "a224-t2-001",
      type: "fill_blank",
      prompt: "Choose the correct agreement: Ho comprato una borsa ___. (narrow / tight)\na) stretto  b) stretti  c) stretta",
      accepted: ["c", "stretta"],
      hint: "borsa is feminine singular",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-002",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'pieno':\nI bicchieri sono ___ d'acqua.",
      accepted: ["pieni"],
      hint: "bicchieri = masculine plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-003",
      type: "fill_blank",
      prompt: "Complete using 'abbastanza':\nNon mi piace questo caffè — è ___ amaro per me.",
      accepted: ["abbastanza"],
      hint: "abbastanza + adjective = quite / fairly + adjective",
      tags: ["degree", "abbastanza", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-004",
      type: "fill_blank",
      prompt: "Form the comparative:\nIl pane di ieri è ___ duro di quello fresco. (harder)",
      accepted: ["più"],
      hint: "più + adjective + di = more … than",
      tags: ["comparative", "grammar"],
      tier: 2,
    },

    // ── Tier 2 – Grammar (expansion) ─────────────────────────────────────────
    {
      id: "a224-t2-005",
      type: "fill_blank",
      prompt: "Choose the correct agreement: Questi vestiti sono troppo ___. (expensive)\na) caro  b) cari  c) care",
      accepted: ["b", "cari"],
      hint: "vestiti is masculine plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-006",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'sottile':\nLe fette di prosciutto erano molto ___.",
      accepted: ["sottili"],
      hint: "fette is feminine plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-007",
      type: "fill_blank",
      prompt: "Form the comparative:\nQuesta valigia è ___ pesante di quella. (more)",
      accepted: ["più"],
      hint: "più + adjective + di = more … than",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-008",
      type: "fill_blank",
      prompt: "Form the comparative:\nIl secondo problema è ___ complicato del primo. (less)",
      accepted: ["meno"],
      hint: "meno + adjective + di = less … than",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-009",
      type: "fill_blank",
      prompt: "Complete the equal comparison:\nQuesto zaino è pesante ___ una valigia. (as … as)",
      accepted: ["quanto", "come"],
      hint: "pesante quanto / pesante come = as heavy as",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-010",
      type: "fill_blank",
      prompt: "Choose the correct agreement: La cucina è troppo ___.\na) piccolo  b) piccola  c) piccoli",
      accepted: ["b", "piccola"],
      hint: "cucina is feminine singular",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-011",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'comodo':\nI divani nuovi sono molto ___.",
      accepted: ["comodi"],
      hint: "divani is masculine plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-012",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'veloce' (invariable -e/-i):\nLe macchine sportive sono molto ___.",
      accepted: ["veloci"],
      hint: "-e adjectives take -i in the plural, regardless of gender",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-013",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'facile':\nQueste domande sono ___ per me.",
      accepted: ["facili"],
      hint: "domande is feminine plural; facile → facili",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-014",
      type: "fill_blank",
      prompt: "Complete using 'abbastanza':\nLa stanza non è ___ spaziosa per un letto matrimoniale.",
      accepted: ["abbastanza"],
      hint: "abbastanza + adjective = enough / sufficiently + adjective",
      tags: ["degree", "abbastanza", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-015",
      type: "fill_blank",
      prompt: "Choose the correct agreement: I bicchieri erano ___. (transparent)\na) trasparente  b) trasparenti  c) trasparenta",
      accepted: ["b", "trasparenti"],
      hint: "-e adjectives take -i in the plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-016",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'rigido':\nLe regole della scuola sono troppo ___.",
      accepted: ["rigide"],
      hint: "regole is feminine plural",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-017",
      type: "fill_blank",
      prompt: "Form the superlative:\nQuesto è il tessuto ___ elastico di tutti. (most)",
      accepted: ["più"],
      hint: "il più + adjective + di = the most … of",
      tags: ["superlative", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-018",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'ordinato':\nLa sua camera è sempre ___.",
      accepted: ["ordinata"],
      hint: "camera is feminine singular",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-019",
      type: "fill_blank",
      prompt: "Fill in with the correct form of 'enorme' (invariable -e/-i):\nQuesti palazzi sono ___.",
      accepted: ["enormi"],
      hint: "palazzi is masculine plural; enorme → enormi",
      tags: ["adjective-agreement", "grammar"],
      tier: 2,
    },
    {
      id: "a224-t2-020",
      type: "fill_blank",
      prompt: "Complete using 'troppo':\nQuesto ristorante è ___ caro per noi.",
      accepted: ["troppo"],
      hint: "troppo + adjective = too + adjective",
      tags: ["degree", "grammar"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "a224-t3-001",
      type: "produce",
      prompt: "This bread is stale.",
      accepted: [
        "Questo pane è raffermo.",
        "questo pane è raffermo",
        "Questo pane è secco.",
        "questo pane è secco",
      ],
      hint: "raffermo = stale (bread); secco also works",
      tags: ["chunk", "adjective", "food"],
      tier: 3,
    },
    {
      id: "a224-t3-002",
      type: "produce",
      prompt: "The water is cold.",
      accepted: [
        "L'acqua è fredda.",
        "l'acqua è fredda",
      ],
      hint: "acqua is feminine — remember agreement",
      tags: ["chunk", "adjective", "temperature"],
      tier: 3,
    },
    {
      id: "a224-t3-003",
      type: "produce",
      prompt: "That's a strange idea.",
      accepted: [
        "È un'idea strana.",
        "è un'idea strana",
        "Quella è un'idea strana.",
        "quella è un'idea strana",
      ],
      hint: "idea is feminine; adjective follows the noun",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-004",
      type: "produce",
      prompt: "The bag is too heavy.",
      accepted: [
        "La borsa è troppo pesante.",
        "la borsa è troppo pesante",
      ],
      hint: "troppo + adjective = too + adjective; pesante is invariable",
      tags: ["chunk", "adjective", "weight"],
      tier: 3,
    },
    {
      id: "a224-t3-005",
      type: "produce",
      prompt: "Is it possible to change?",
      accepted: [
        "È possibile cambiare?",
        "è possibile cambiare?",
        "È possibile cambiare",
      ],
      hint: "possibile is invariable; use infinitive after it",
      tags: ["chunk", "adjective", "possibility"],
      tier: 3,
    },

    // ── Tier 3 – Chunks & Phrases (expansion) ────────────────────────────────
    {
      id: "a224-t3-006",
      type: "produce",
      prompt: "The floor is smooth.",
      accepted: ["Il pavimento è liscio.", "il pavimento è liscio"],
      hint: "pavimento is masculine",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-007",
      type: "produce",
      prompt: "This towel feels rough.",
      accepted: ["Questo asciugamano è ruvido.", "questo asciugamano è ruvido"],
      hint: "asciugamano is masculine",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-008",
      type: "produce",
      prompt: "My backpack is too heavy.",
      accepted: ["Il mio zaino è troppo pesante.", "il mio zaino è troppo pesante"],
      hint: "zaino is masculine; pesante is invariable",
      tags: ["chunk", "adjective", "weight"],
      tier: 3,
    },
    {
      id: "a224-t3-009",
      type: "produce",
      prompt: "This jacket is very light.",
      accepted: ["Questa giacca è molto leggera.", "questa giacca è molto leggera"],
      hint: "giacca is feminine",
      tags: ["chunk", "adjective", "weight"],
      tier: 3,
    },
    {
      id: "a224-t3-010",
      type: "produce",
      prompt: "The walls are thick.",
      accepted: ["I muri sono spessi.", "i muri sono spessi"],
      hint: "muri is masculine plural",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-011",
      type: "produce",
      prompt: "The sheet of paper is thin.",
      accepted: ["Il foglio di carta è sottile.", "il foglio di carta è sottile"],
      hint: "foglio is masculine",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-012",
      type: "produce",
      prompt: "He is very tall for his age.",
      accepted: ["È molto alto per la sua età.", "è molto alto per la sua età"],
      hint: "per la sua età = for his/her age",
      tags: ["chunk", "adjective", "height"],
      tier: 3,
    },
    {
      id: "a224-t3-013",
      type: "produce",
      prompt: "The ceiling is low.",
      accepted: ["Il soffitto è basso.", "il soffitto è basso"],
      hint: "soffitto is masculine",
      tags: ["chunk", "adjective", "height"],
      tier: 3,
    },
    {
      id: "a224-t3-014",
      type: "produce",
      prompt: "The lake is deep.",
      accepted: ["Il lago è profondo.", "il lago è profondo"],
      hint: "lago is masculine",
      tags: ["chunk", "adjective", "depth"],
      tier: 3,
    },
    {
      id: "a224-t3-015",
      type: "produce",
      prompt: "The wound is only superficial.",
      accepted: ["La ferita è solo superficiale.", "la ferita è solo superficiale"],
      hint: "ferita is feminine; superficiale is invariable",
      tags: ["chunk", "adjective", "depth"],
      tier: 3,
    },
    {
      id: "a224-t3-016",
      type: "produce",
      prompt: "This old chair is sturdy.",
      accepted: ["Questa vecchia sedia è robusta.", "questa vecchia sedia è robusta"],
      hint: "sedia is feminine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-017",
      type: "produce",
      prompt: "The glass is very fragile.",
      accepted: ["Il vetro è molto fragile.", "il vetro è molto fragile"],
      hint: "vetro is masculine; fragile is invariable",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-018",
      type: "produce",
      prompt: "This family is rich.",
      accepted: ["Questa famiglia è ricca.", "questa famiglia è ricca"],
      hint: "famiglia is feminine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-019",
      type: "produce",
      prompt: "He grew up poor.",
      accepted: ["È cresciuto povero.", "è cresciuto povero"],
      hint: "crescere → cresciuto (irregular past participle)",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-020",
      type: "produce",
      prompt: "The instructions are simple.",
      accepted: ["Le istruzioni sono semplici.", "le istruzioni sono semplici"],
      hint: "istruzioni is feminine plural; semplice → semplici",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-021",
      type: "produce",
      prompt: "The problem is complicated.",
      accepted: ["Il problema è complicato.", "il problema è complicato"],
      hint: "problema is masculine despite ending in -a",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-022",
      type: "produce",
      prompt: "The air in here is stale.",
      accepted: ["L'aria qui dentro è stantia.", "l'aria qui dentro è stantia"],
      hint: "aria is feminine; stantia describes stuffy, stale air",
      tags: ["chunk", "adjective", "freshness"],
      tier: 3,
    },
    {
      id: "a224-t3-023",
      type: "produce",
      prompt: "This building is modern.",
      accepted: ["Questo edificio è moderno.", "questo edificio è moderno"],
      hint: "edificio is masculine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-024",
      type: "produce",
      prompt: "That castle is ancient.",
      accepted: ["Quel castello è antico.", "quel castello è antico"],
      hint: "castello is masculine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-025",
      type: "produce",
      prompt: "These shoes are comfortable.",
      accepted: ["Queste scarpe sono comode.", "queste scarpe sono comode"],
      hint: "scarpe is feminine plural",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-026",
      type: "produce",
      prompt: "This chair is uncomfortable.",
      accepted: ["Questa sedia è scomoda.", "questa sedia è scomoda"],
      hint: "sedia is feminine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-027",
      type: "produce",
      prompt: "The room is bright.",
      accepted: ["La stanza è chiara.", "la stanza è chiara"],
      hint: "stanza is feminine",
      tags: ["chunk", "adjective", "color"],
      tier: 3,
    },
    {
      id: "a224-t3-028",
      type: "produce",
      prompt: "This street is very noisy.",
      accepted: ["Questa strada è molto rumorosa.", "questa strada è molto rumorosa"],
      hint: "strada is feminine",
      tags: ["chunk", "adjective", "sound"],
      tier: 3,
    },
    {
      id: "a224-t3-029",
      type: "produce",
      prompt: "The library is silent.",
      accepted: ["La biblioteca è silenziosa.", "la biblioteca è silenziosa"],
      hint: "biblioteca is feminine",
      tags: ["chunk", "adjective", "sound"],
      tier: 3,
    },
    {
      id: "a224-t3-030",
      type: "produce",
      prompt: "The glass is transparent.",
      accepted: ["Il vetro è trasparente.", "il vetro è trasparente"],
      hint: "vetro is masculine; trasparente is invariable",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-031",
      type: "produce",
      prompt: "This dessert is very crunchy.",
      accepted: ["Questo dolce è molto croccante.", "questo dolce è molto croccante"],
      hint: "dolce (n.) is masculine; croccante is invariable",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-032",
      type: "produce",
      prompt: "The table is round.",
      accepted: ["Il tavolo è tondo.", "il tavolo è tondo"],
      hint: "tavolo is masculine",
      tags: ["chunk", "adjective", "shape"],
      tier: 3,
    },
    {
      id: "a224-t3-033",
      type: "produce",
      prompt: "The box is square.",
      accepted: ["La scatola è quadrata.", "la scatola è quadrata"],
      hint: "scatola is feminine",
      tags: ["chunk", "adjective", "shape"],
      tier: 3,
    },
    {
      id: "a224-t3-034",
      type: "produce",
      prompt: "This fabric is very elastic.",
      accepted: ["Questo tessuto è molto elastico.", "questo tessuto è molto elastico"],
      hint: "tessuto is masculine",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-035",
      type: "produce",
      prompt: "The rules are rigid.",
      accepted: ["Le regole sono rigide.", "le regole sono rigide"],
      hint: "regole is feminine plural",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-036",
      type: "produce",
      prompt: "Handle it gently, it's delicate.",
      accepted: ["Trattalo con cura, è delicato.", "trattalo con cura, è delicato"],
      hint: "con cura = with care",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-037",
      type: "produce",
      prompt: "This material is resistant to water.",
      accepted: [
        "Questo materiale è resistente all'acqua.",
        "questo materiale è resistente all'acqua",
      ],
      hint: "resistente a = resistant to",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-038",
      type: "produce",
      prompt: "The new office is spacious.",
      accepted: ["Il nuovo ufficio è spazioso.", "il nuovo ufficio è spazioso"],
      hint: "ufficio is masculine",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-039",
      type: "produce",
      prompt: "The room felt cramped.",
      accepted: ["La stanza sembrava angusta.", "la stanza sembrava angusta"],
      hint: "sembrare = to seem",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-040",
      type: "produce",
      prompt: "Her desk is always tidy.",
      accepted: ["La sua scrivania è sempre ordinata.", "la sua scrivania è sempre ordinata"],
      hint: "scrivania is feminine",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-041",
      type: "produce",
      prompt: "He is a very fast runner.",
      accepted: ["È un corridore molto veloce.", "è un corridore molto veloce"],
      hint: "corridore is masculine; veloce is invariable",
      tags: ["chunk", "adjective", "speed"],
      tier: 3,
    },
    {
      id: "a224-t3-042",
      type: "produce",
      prompt: "This exercise is easy for me.",
      accepted: ["Questo esercizio è facile per me.", "questo esercizio è facile per me"],
      hint: "esercizio is masculine; facile is invariable",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-043",
      type: "produce",
      prompt: "This hotel is very expensive.",
      accepted: ["Questo hotel è molto caro.", "questo hotel è molto caro"],
      hint: "hotel is masculine",
      tags: ["chunk", "adjective", "price"],
      tier: 3,
    },
    {
      id: "a224-t3-044",
      type: "produce",
      prompt: "The traffic was very dense.",
      accepted: ["Il traffico era molto denso.", "il traffico era molto denso"],
      hint: "traffico is masculine",
      tags: ["chunk", "adjective", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-045",
      type: "produce",
      prompt: "The crowd was enormous.",
      accepted: ["La folla era enorme.", "la folla era enorme"],
      hint: "folla is feminine; enorme is invariable",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },

    // ── Tier 3 – Chunks & Phrases (coverage fixes) ───────────────────────────
    {
      id: "a224-t3-046",
      type: "produce",
      prompt: "The kitchen floor was dirty, but I cleaned it right after dinner.",
      accepted: [
        "Il pavimento della cucina era sporco, ma l'ho pulito subito dopo cena.",
        "il pavimento della cucina era sporco, ma l'ho pulito subito dopo cena.",
      ],
      hint: "sporco = dirty; l'ho pulito = I cleaned it (passato prossimo)",
      tags: ["chunk", "adjective", "cleanliness"],
      tier: 3,
    },
    {
      id: "a224-t3-047",
      type: "produce",
      prompt: "The wind was cold, and my coat was completely wet.",
      accepted: [
        "Il vento era freddo e il mio cappotto era completamente bagnato.",
        "il vento era freddo e il mio cappotto era completamente bagnato.",
      ],
      hint: "freddo = cold; bagnato = wet — il vento and il cappotto are masculine",
      tags: ["chunk", "adjective", "temperature", "moisture"],
      tier: 3,
    },
    {
      id: "a224-t3-048",
      type: "produce",
      prompt: "After the shower, I put on a dry bathrobe right away.",
      accepted: [
        "Dopo la doccia, ho indossato subito un accappatoio asciutto.",
        "dopo la doccia, ho indossato subito un accappatoio asciutto.",
      ],
      hint: "asciutto = dry; accappatoio is masculine",
      tags: ["chunk", "adjective", "moisture"],
      tier: 3,
    },
    {
      id: "a224-t3-049",
      type: "produce",
      prompt: "The bathroom mirror is broken, but the package I received yesterday was still intact.",
      accepted: [
        "Lo specchio in bagno è rotto, ma il pacco che ho ricevuto ieri era ancora integro.",
        "lo specchio in bagno è rotto, ma il pacco che ho ricevuto ieri era ancora integro.",
      ],
      hint: "rotto = broken; integro = intact — both masculine singular here",
      tags: ["chunk", "adjective", "condition"],
      tier: 3,
    },
    {
      id: "a224-t3-050",
      type: "produce",
      prompt: "The cheese I bought was too salty and too fatty; now I prefer a leaner kind.",
      accepted: [
        "Il formaggio che ho comprato era troppo salato e troppo grasso; ora preferisco un tipo più magro.",
        "il formaggio che ho comprato era troppo salato e troppo grasso; ora preferisco un tipo più magro.",
      ],
      hint: "salato = salty; grasso = fatty; magro = lean",
      tags: ["chunk", "adjective", "taste", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-051",
      type: "produce",
      prompt: "When I was young I was strong, but after the illness I felt weak.",
      accepted: [
        "Da giovane ero forte, ma dopo la malattia mi sentivo debole.",
        "da giovane ero forte, ma dopo la malattia mi sentivo debole.",
      ],
      hint: "da giovane = as a young person; ero/sentivo = imperfetto",
      tags: ["chunk", "adjective", "age", "strength"],
      tier: 3,
    },
    {
      id: "a224-t3-052",
      type: "produce",
      prompt: "The train journey was too long and the seat was uncomfortable, so next time we'll take a shorter route.",
      accepted: [
        "Il viaggio in treno era troppo lungo e il sedile era scomodo, così la prossima volta prenderemo un percorso più corto.",
        "il viaggio in treno era troppo lungo e il sedile era scomodo, così la prossima volta prenderemo un percorso più corto.",
      ],
      hint: "lungo = long; scomodo = uncomfortable; corto = short (length)",
      tags: ["chunk", "adjective", "length", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-053",
      type: "produce",
      prompt: "The corridor was wide and completely empty at that hour of the night.",
      accepted: [
        "Il corridoio era largo e completamente vuoto a quell'ora della notte.",
        "il corridoio era largo e completamente vuoto a quell'ora della notte.",
      ],
      hint: "largo = wide; vuoto = empty — corridoio is masculine",
      tags: ["chunk", "adjective", "width", "volume"],
      tier: 3,
    },
    {
      id: "a224-t3-054",
      type: "produce",
      prompt: "Your advice was very useful, but now professional help is also necessary.",
      accepted: [
        "Il tuo consiglio è stato molto utile, ma ora è necessario anche un aiuto professionale.",
        "il tuo consiglio è stato molto utile, ma ora è necessario anche un aiuto professionale.",
      ],
      hint: "utile = useful; necessario = necessary",
      tags: ["chunk", "adjective", "utility"],
      tier: 3,
    },
    {
      id: "a224-t3-055",
      type: "produce",
      prompt: "The task seemed impossible at first, but the reason for the problem was obvious.",
      accepted: [
        "Il compito sembrava impossibile all'inizio, ma il motivo del problema era ovvio.",
        "il compito sembrava impossibile all'inizio, ma il motivo del problema era ovvio.",
      ],
      hint: "impossibile = impossible; ovvio = obvious — sembrava = imperfetto of sembrare",
      tags: ["chunk", "adjective", "possibility", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-056",
      type: "produce",
      prompt: "I heard a strange noise in the kitchen, then I noticed the backpack on the table was too light.",
      accepted: [
        "Ho sentito un rumore strano in cucina, poi ho notato che lo zaino sul tavolo era troppo leggero.",
        "ho sentito un rumore strano in cucina, poi ho notato che lo zaino sul tavolo era troppo leggero.",
      ],
      hint: "strano = strange; leggero = light (weight)",
      tags: ["chunk", "adjective", "quality", "weight"],
      tier: 3,
    },
    {
      id: "a224-t3-057",
      type: "produce",
      prompt: "The new dining table is big and sturdy, while the old one in the kitchen was tiny and always wobbled.",
      accepted: [
        "Il nuovo tavolo da pranzo è grande e robusto, mentre quello vecchio in cucina era minuscolo e traballava sempre.",
        "il nuovo tavolo da pranzo è grande e robusto, mentre quello vecchio in cucina era minuscolo e traballava sempre.",
      ],
      hint: "grande = big; robusto = sturdy; minuscolo = tiny",
      tags: ["chunk", "adjective", "size"],
      tier: 3,
    },
    {
      id: "a224-t3-058",
      type: "produce",
      prompt: "The man was rich, but he lived simply, without luxuries.",
      accepted: [
        "L'uomo era ricco, ma viveva in modo semplice, senza lussi.",
        "l'uomo era ricco, ma viveva in modo semplice, senza lussi.",
      ],
      hint: "ricco = rich; in modo semplice = simply",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-059",
      type: "produce",
      prompt: "I prefer a light color for the living room, while in the bedroom a dark one works well.",
      accepted: [
        "Preferisco un colore chiaro per il soggiorno, mentre in camera da letto va bene uno scuro.",
        "preferisco un colore chiaro per il soggiorno, mentre in camera da letto va bene uno scuro.",
      ],
      hint: "chiaro = light (color); scuro = dark",
      tags: ["chunk", "adjective", "color"],
      tier: 3,
    },
    {
      id: "a224-t3-060",
      type: "produce",
      prompt: "The old engine was noisy, but after the repair it became almost silent.",
      accepted: [
        "Il motore vecchio era rumoroso, ma dopo la riparazione è diventato quasi silenzioso.",
        "il motore vecchio era rumoroso, ma dopo la riparazione è diventato quasi silenzioso.",
      ],
      hint: "rumoroso = noisy; silenzioso = silent — è diventato = passato prossimo of diventare",
      tags: ["chunk", "adjective", "sound"],
      tier: 3,
    },
    {
      id: "a224-t3-061",
      type: "produce",
      prompt: "The window glass is opaque, but the square frame still lets in a bit of light.",
      accepted: [
        "Il vetro della finestra è opaco, ma il telaio quadrato lascia entrare comunque un po' di luce.",
        "il vetro della finestra è opaco, ma il telaio quadrato lascia entrare comunque un po' di luce.",
      ],
      hint: "opaco = opaque; quadrato = square — telaio is masculine",
      tags: ["chunk", "adjective", "quality", "shape"],
      tier: 3,
    },
    {
      id: "a224-t3-062",
      type: "produce",
      prompt: "His office was so messy that finding a document became difficult.",
      accepted: [
        "Il suo ufficio era così disordinato che trovare un documento diventava difficile.",
        "il suo ufficio era così disordinato che trovare un documento diventava difficile.",
      ],
      hint: "disordinato = messy; difficile = difficult — diventava = imperfetto of diventare",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-063",
      type: "produce",
      prompt: "I chose the cheapest ticket, even though traffic on the highway wasn't flowing smoothly at all.",
      accepted: [
        "Ho scelto il biglietto più economico, anche se il traffico in autostrada non era affatto fluido.",
        "ho scelto il biglietto più economico, anche se il traffico in autostrada non era affatto fluido.",
      ],
      hint: "economico = cheap; fluido = fluid/flowing",
      tags: ["chunk", "adjective", "price", "texture"],
      tier: 3,
    },
    {
      id: "a224-t3-064",
      type: "produce",
      prompt: "The wet bread had gone spongy; ice, on the other hand, goes from a liquid state to a solid one when the temperature drops.",
      accepted: [
        "Il pane bagnato è diventato spugnoso; il ghiaccio, invece, passa dallo stato liquido allo stato solido quando la temperatura scende.",
        "il pane bagnato è diventato spugnoso; il ghiaccio, invece, passa dallo stato liquido allo stato solido quando la temperatura scende.",
      ],
      hint: "spugnoso = spongy; liquido/solido = liquid/solid — stato liquido, stato solido",
      tags: ["chunk", "adjective", "texture", "state"],
      tier: 3,
    },
    {
      id: "a224-t3-065",
      type: "produce",
      prompt: "Eating lots of vegetables is healthy, but fast food every day is unhealthy.",
      accepted: [
        "Mangiare tanta verdura è sano, ma il fast food tutti i giorni è malsano.",
        "mangiare tanta verdura è sano, ma il fast food tutti i giorni è malsano.",
      ],
      hint: "sano = healthy; malsano = unhealthy — mangiare (infinitive) takes masculine agreement",
      tags: ["chunk", "adjective", "quality"],
      tier: 3,
    },
    {
      id: "a224-t3-066",
      type: "produce",
      prompt: "I left the TV on all night, but it should have stayed off.",
      accepted: [
        "Ho lasciato il televisore acceso tutta la notte, ma doveva restare spento.",
        "ho lasciato il televisore acceso tutta la notte, ma doveva restare spento.",
      ],
      hint: "acceso = turned on/lit; spento = turned off — doveva restare = should have stayed",
      tags: ["chunk", "adjective", "state"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a224-t4-001",
      type: "passage_cloze",
      prompt: "Oggi sono andato al mercato con mia nonna. Lei conosce tutti i venditori e sa sempre scegliere la frutta migliore.\nHa preso delle pesche morbide e profumate, del pane ancora ___ di forno e un sacchetto di olive salate.\nIl venditore era un uomo anziano e molto gentile — ci ha dato anche qualche ciliegia in omaggio.\nÈ stata una mattinata normale, ma piacevole.",
      accepted: ["caldo", "caldo di forno"],
      hint: "the bread has just come out of the oven — what temperature is it?",
      tags: ["passage_cloze", "adjective", "food", "temperature"],
      tier: 4,
      prerequisites: [
        "a224-t1-003",
        "a224-t1-009",
        "a224-t1-013",
        "a224-t1-015",
        "a224-t1-032",
      ],
    },

    // ── Tier 4 – Passage Cloze (expansion) ───────────────────────────────────
    {
      id: "a224-t4-002",
      type: "passage_cloze",
      prompt: "Il mese scorso abbiamo cambiato casa. Il vecchio appartamento era piccolo e ___, con una sola finestra che dava su un cortile buio.\nQuello nuovo, invece, è più moderno e ha una cucina spaziosa con tanta luce naturale.\nAnche i mobili sono comodi e il divano è morbido al punto giusto.\nMia madre dice che finalmente abbiamo un posto dove respirare.",
      accepted: ["angusto"],
      hint: "the opposite of spazioso — the old place felt small and cramped",
      tags: ["passage_cloze", "adjective", "size", "quality"],
      tier: 4,
      prerequisites: [
        "a224-t1-042",
        "a224-t1-053",
        "a224-t1-054",
        "a224-t1-055",
        "a224-t1-057",
        "a224-t1-071",
        "a224-t1-072",
      ],
    },
    {
      id: "a224-t4-003",
      type: "passage_cloze",
      prompt: "Al mercato della lana, il venditore mostra sempre i tessuti con orgoglio. Il cotone è ___ al tatto, perfetto per l'estate.\nLa lana invece è più ruvida, ma tiene caldo d'inverno.\nAlcuni tessuti sintetici sono elastici e resistenti, ideali per lo sport.\nAltri, come la seta, sono delicati e vanno lavati a mano.",
      accepted: ["liscio"],
      hint: "opposite of ruvido — how does cotton feel to the touch?",
      tags: ["passage_cloze", "adjective", "texture"],
      tier: 4,
      prerequisites: [
        "a224-t1-033",
        "a224-t1-034",
        "a224-t1-067",
        "a224-t1-070",
        "a224-t1-069",
      ],
    },
    {
      id: "a224-t4-004",
      type: "passage_cloze",
      prompt: "Da piccola andavo spesso a trovare mia nonna in campagna. La sua cucina profumava sempre di pane ___ appena sfornato.\nLa crosta era croccante fuori e morbida dentro, mai spugnosa come quella del supermercato.\nBeveva il caffè amaro, ma per me preparava sempre una cioccolata calda e dolce.\nOgni tanto l'aria della credenza sapeva un po' di stantio, ma non m'importava.",
      accepted: ["fresco"],
      hint: "opposite of stantio — bread just out of the oven is...",
      tags: ["passage_cloze", "adjective", "freshness", "food"],
      tier: 4,
      prerequisites: [
        "a224-t1-051",
        "a224-t1-052",
        "a224-t1-083",
        "a224-t1-084",
        "a224-t1-012",
        "a224-t1-011",
        "a224-t1-003",
      ],
    },
    {
      id: "a224-t4-005",
      type: "passage_cloze",
      prompt: "Vivere in centro ha vantaggi e svantaggi. Il traffico è spesso ___ nelle ore di punta, e i clacson non si fermano mai.\nLe strade sono rumorose fino a tarda sera, ma dal terrazzo del mio palazzo, molto alto, si vede tutta la città.\nDi notte, quando il traffico rallenta, la zona diventa quasi silenziosa.\nÈ un quartiere vivace, mai lento.",
      accepted: ["denso"],
      hint: "opposite of fluido — heavy traffic at rush hour is...",
      tags: ["passage_cloze", "adjective", "texture", "sound"],
      tier: 4,
      prerequisites: [
        "a224-t1-081",
        "a224-t1-061",
        "a224-t1-039",
        "a224-t1-062",
        "a224-t1-076",
      ],
    },
  ],
};
export default unit;
