import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-26-irregular-participles",
  name: "Irregular Past Participles",
  level: "A2",
  theme: "Irregular Past Participles",
  emoji: "🧩",
  prerequisiteUnits: ["a2-unit-25-nature"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a226-t1-001",
      type: "recognize",
      prompt: "fare",
      accepted: ["to do", "to make"],
      tags: ["verb", "infinitive", "fare"],
      tier: 1,
    },
    {
      id: "a226-t1-002",
      type: "produce",
      prompt: "to do / to make",
      accepted: ["fare"],
      tags: ["verb", "infinitive", "fare"],
      tier: 1,
    },
    {
      id: "a226-t1-003",
      type: "recognize",
      prompt: "fatto apposta",
      accepted: ["done on purpose"],
      tags: ["verb", "irregular-participle", "fare", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-004",
      type: "produce",
      prompt: "done on purpose",
      accepted: ["fatto apposta"],
      hint: "fare → fatto (irregular participle)",
      tags: ["verb", "irregular-participle", "fare", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-005",
      type: "recognize",
      prompt: "dire",
      accepted: ["to say", "to tell"],
      tags: ["verb", "infinitive", "dire"],
      tier: 1,
    },
    {
      id: "a226-t1-006",
      type: "produce",
      prompt: "to say / to tell",
      accepted: ["dire"],
      tags: ["verb", "infinitive", "dire"],
      tier: 1,
    },
    {
      id: "a226-t1-007",
      type: "recognize",
      prompt: "detto tra noi",
      accepted: ["just between us", "between you and me"],
      tags: ["verb", "irregular-participle", "dire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-008",
      type: "produce",
      prompt: "just between us",
      accepted: ["detto tra noi"],
      hint: "dire → detto (irregular participle)",
      tags: ["verb", "irregular-participle", "dire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-009",
      type: "recognize",
      prompt: "scrivere",
      accepted: ["to write"],
      tags: ["verb", "infinitive", "scrivere"],
      tier: 1,
    },
    {
      id: "a226-t1-010",
      type: "produce",
      prompt: "to write",
      accepted: ["scrivere"],
      tags: ["verb", "infinitive", "scrivere"],
      tier: 1,
    },
    {
      id: "a226-t1-011",
      type: "recognize",
      prompt: "scritto a mano",
      accepted: ["handwritten", "written by hand"],
      tags: ["verb", "irregular-participle", "scrivere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-012",
      type: "produce",
      prompt: "handwritten",
      accepted: ["scritto a mano"],
      hint: "scrivere → scritto (irregular participle)",
      tags: ["verb", "irregular-participle", "scrivere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-013",
      type: "recognize",
      prompt: "leggere",
      accepted: ["to read"],
      tags: ["verb", "infinitive", "leggere"],
      tier: 1,
    },
    {
      id: "a226-t1-014",
      type: "produce",
      prompt: "to read",
      accepted: ["leggere"],
      tags: ["verb", "infinitive", "leggere"],
      tier: 1,
    },
    {
      id: "a226-t1-015",
      type: "recognize",
      prompt: "letto ad alta voce",
      accepted: ["read aloud"],
      tags: ["verb", "irregular-participle", "leggere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-016",
      type: "produce",
      prompt: "read aloud",
      accepted: ["letto ad alta voce"],
      hint: "leggere → letto (irregular participle)",
      tags: ["verb", "irregular-participle", "leggere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-017",
      type: "recognize",
      prompt: "vedere",
      accepted: ["to see"],
      tags: ["verb", "infinitive", "vedere"],
      tier: 1,
    },
    {
      id: "a226-t1-018",
      type: "produce",
      prompt: "to see",
      accepted: ["vedere"],
      tags: ["verb", "infinitive", "vedere"],
      tier: 1,
    },
    {
      id: "a226-t1-019",
      type: "recognize",
      prompt: "mai visto prima",
      accepted: ["never seen before"],
      tags: ["verb", "irregular-participle", "vedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-020",
      type: "produce",
      prompt: "never seen before",
      accepted: ["mai visto prima"],
      hint: "vedere → visto (irregular participle)",
      tags: ["verb", "irregular-participle", "vedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-021",
      type: "recognize",
      prompt: "aprire",
      accepted: ["to open"],
      tags: ["verb", "infinitive", "aprire"],
      tier: 1,
    },
    {
      id: "a226-t1-022",
      type: "produce",
      prompt: "to open",
      accepted: ["aprire"],
      tags: ["verb", "infinitive", "aprire"],
      tier: 1,
    },
    {
      id: "a226-t1-023",
      type: "recognize",
      prompt: "aperto tutta la notte",
      accepted: ["open all night"],
      tags: ["verb", "irregular-participle", "aprire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-024",
      type: "produce",
      prompt: "open all night",
      accepted: ["aperto tutta la notte"],
      hint: "aprire → aperto (irregular participle)",
      tags: ["verb", "irregular-participle", "aprire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-025",
      type: "recognize",
      prompt: "chiudere",
      accepted: ["to close"],
      tags: ["verb", "infinitive", "chiudere"],
      tier: 1,
    },
    {
      id: "a226-t1-026",
      type: "produce",
      prompt: "to close",
      accepted: ["chiudere"],
      tags: ["verb", "infinitive", "chiudere"],
      tier: 1,
    },
    {
      id: "a226-t1-027",
      type: "recognize",
      prompt: "chiuso per ferie",
      accepted: ["closed for the holidays"],
      tags: ["verb", "irregular-participle", "chiudere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-028",
      type: "produce",
      prompt: "closed for the holidays",
      accepted: ["chiuso per ferie"],
      hint: "chiudere → chiuso (irregular participle)",
      tags: ["verb", "irregular-participle", "chiudere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-029",
      type: "recognize",
      prompt: "prendere",
      accepted: ["to take"],
      tags: ["verb", "infinitive", "prendere"],
      tier: 1,
    },
    {
      id: "a226-t1-030",
      type: "produce",
      prompt: "to take",
      accepted: ["prendere"],
      tags: ["verb", "infinitive", "prendere"],
      tier: 1,
    },
    {
      id: "a226-t1-031",
      type: "recognize",
      prompt: "preso al volo",
      accepted: ["caught on the fly", "grabbed quickly"],
      tags: ["verb", "irregular-participle", "prendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-032",
      type: "produce",
      prompt: "caught on the fly",
      accepted: ["preso al volo"],
      hint: "prendere → preso (irregular participle)",
      tags: ["verb", "irregular-participle", "prendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-033",
      type: "recognize",
      prompt: "mettere",
      accepted: ["to put", "to place"],
      tags: ["verb", "infinitive", "mettere"],
      tier: 1,
    },
    {
      id: "a226-t1-034",
      type: "produce",
      prompt: "to put / to place",
      accepted: ["mettere"],
      tags: ["verb", "infinitive", "mettere"],
      tier: 1,
    },
    {
      id: "a226-t1-035",
      type: "recognize",
      prompt: "messo da parte",
      accepted: ["set aside", "put aside"],
      tags: ["verb", "irregular-participle", "mettere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-036",
      type: "produce",
      prompt: "set aside",
      accepted: ["messo da parte"],
      hint: "mettere → messo (irregular participle)",
      tags: ["verb", "irregular-participle", "mettere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-037",
      type: "recognize",
      prompt: "rompere",
      accepted: ["to break"],
      tags: ["verb", "infinitive", "rompere"],
      tier: 1,
    },
    {
      id: "a226-t1-038",
      type: "produce",
      prompt: "to break",
      accepted: ["rompere"],
      tags: ["verb", "infinitive", "rompere"],
      tier: 1,
    },
    {
      id: "a226-t1-039",
      type: "recognize",
      prompt: "rotto in mille pezzi",
      accepted: ["broken into a thousand pieces"],
      tags: ["verb", "irregular-participle", "rompere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-040",
      type: "produce",
      prompt: "broken into a thousand pieces",
      accepted: ["rotto in mille pezzi"],
      hint: "rompere → rotto (irregular participle)",
      tags: ["verb", "irregular-participle", "rompere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-041",
      type: "recognize",
      prompt: "morire",
      accepted: ["to die"],
      tags: ["verb", "infinitive", "morire"],
      tier: 1,
    },
    {
      id: "a226-t1-042",
      type: "produce",
      prompt: "to die",
      accepted: ["morire"],
      tags: ["verb", "infinitive", "morire"],
      tier: 1,
    },
    {
      id: "a226-t1-043",
      type: "recognize",
      prompt: "morto di paura",
      accepted: ["scared to death", "frightened to death"],
      tags: ["verb", "irregular-participle", "morire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-044",
      type: "produce",
      prompt: "scared to death",
      accepted: ["morto di paura"],
      hint: "morire → morto (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "morire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-045",
      type: "recognize",
      prompt: "nascere",
      accepted: ["to be born"],
      tags: ["verb", "infinitive", "nascere"],
      tier: 1,
    },
    {
      id: "a226-t1-046",
      type: "produce",
      prompt: "to be born",
      accepted: ["nascere"],
      tags: ["verb", "infinitive", "nascere"],
      tier: 1,
    },
    {
      id: "a226-t1-047",
      type: "recognize",
      prompt: "nato a Roma",
      accepted: ["born in Rome"],
      tags: ["verb", "irregular-participle", "nascere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-048",
      type: "produce",
      prompt: "born in Rome",
      accepted: ["nato a Roma"],
      hint: "nascere → nato (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "nascere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-049",
      type: "recognize",
      prompt: "venire",
      accepted: ["to come"],
      tags: ["verb", "infinitive", "venire"],
      tier: 1,
    },
    {
      id: "a226-t1-050",
      type: "produce",
      prompt: "to come",
      accepted: ["venire"],
      tags: ["verb", "infinitive", "venire"],
      tier: 1,
    },
    {
      id: "a226-t1-051",
      type: "recognize",
      prompt: "venuto da lontano",
      accepted: ["come from far away"],
      tags: ["verb", "irregular-participle", "venire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-052",
      type: "produce",
      prompt: "come from far away",
      accepted: ["venuto da lontano"],
      hint: "venire → venuto (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "venire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-053",
      type: "recognize",
      prompt: "rimanere",
      accepted: ["to remain", "to stay"],
      tags: ["verb", "infinitive", "rimanere"],
      tier: 1,
    },
    {
      id: "a226-t1-054",
      type: "produce",
      prompt: "to remain / to stay",
      accepted: ["rimanere"],
      tags: ["verb", "infinitive", "rimanere"],
      tier: 1,
    },
    {
      id: "a226-t1-055",
      type: "recognize",
      prompt: "rimasto solo",
      accepted: ["left alone", "remained alone"],
      tags: ["verb", "irregular-participle", "rimanere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-056",
      type: "produce",
      prompt: "left alone",
      accepted: ["rimasto solo"],
      hint: "rimanere → rimasto (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "rimanere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-057",
      type: "recognize",
      prompt: "scendere",
      accepted: ["to go down", "to get off"],
      tags: ["verb", "infinitive", "scendere"],
      tier: 1,
    },
    {
      id: "a226-t1-058",
      type: "produce",
      prompt: "to go down / to get off",
      accepted: ["scendere"],
      tags: ["verb", "infinitive", "scendere"],
      tier: 1,
    },
    {
      id: "a226-t1-059",
      type: "recognize",
      prompt: "sceso dal treno",
      accepted: ["got off the train"],
      tags: ["verb", "irregular-participle", "scendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-060",
      type: "produce",
      prompt: "got off the train",
      accepted: ["sceso dal treno"],
      hint: "scendere → sceso (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "scendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-061",
      type: "recognize",
      prompt: "chiedere",
      accepted: ["to ask"],
      tags: ["verb", "infinitive", "chiedere"],
      tier: 1,
    },
    {
      id: "a226-t1-062",
      type: "produce",
      prompt: "to ask",
      accepted: ["chiedere"],
      tags: ["verb", "infinitive", "chiedere"],
      tier: 1,
    },
    {
      id: "a226-t1-063",
      type: "recognize",
      prompt: "chiesto scusa",
      accepted: ["said sorry", "apologized"],
      tags: ["verb", "irregular-participle", "chiedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-064",
      type: "produce",
      prompt: "said sorry",
      accepted: ["chiesto scusa"],
      hint: "chiedere → chiesto (irregular participle)",
      tags: ["verb", "irregular-participle", "chiedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-065",
      type: "recognize",
      prompt: "rispondere",
      accepted: ["to answer", "to reply"],
      tags: ["verb", "infinitive", "rispondere"],
      tier: 1,
    },
    {
      id: "a226-t1-066",
      type: "produce",
      prompt: "to answer / to reply",
      accepted: ["rispondere"],
      tags: ["verb", "infinitive", "rispondere"],
      tier: 1,
    },
    {
      id: "a226-t1-067",
      type: "recognize",
      prompt: "risposto subito",
      accepted: ["answered right away"],
      tags: ["verb", "irregular-participle", "rispondere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-068",
      type: "produce",
      prompt: "answered right away",
      accepted: ["risposto subito"],
      hint: "rispondere → risposto (irregular participle)",
      tags: ["verb", "irregular-participle", "rispondere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-069",
      type: "recognize",
      prompt: "decidere",
      accepted: ["to decide"],
      tags: ["verb", "infinitive", "decidere"],
      tier: 1,
    },
    {
      id: "a226-t1-070",
      type: "produce",
      prompt: "to decide",
      accepted: ["decidere"],
      tags: ["verb", "infinitive", "decidere"],
      tier: 1,
    },
    {
      id: "a226-t1-071",
      type: "recognize",
      prompt: "deciso all'ultimo momento",
      accepted: ["decided at the last moment"],
      tags: ["verb", "irregular-participle", "decidere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-072",
      type: "produce",
      prompt: "decided at the last moment",
      accepted: ["deciso all'ultimo momento"],
      hint: "decidere → deciso (irregular participle)",
      tags: ["verb", "irregular-participle", "decidere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-073",
      type: "recognize",
      prompt: "offrire",
      accepted: ["to offer"],
      tags: ["verb", "infinitive", "offrire"],
      tier: 1,
    },
    {
      id: "a226-t1-074",
      type: "produce",
      prompt: "to offer",
      accepted: ["offrire"],
      tags: ["verb", "infinitive", "offrire"],
      tier: 1,
    },
    {
      id: "a226-t1-075",
      type: "recognize",
      prompt: "offerto volentieri",
      accepted: ["offered willingly", "gladly offered"],
      tags: ["verb", "irregular-participle", "offrire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-076",
      type: "produce",
      prompt: "offered willingly",
      accepted: ["offerto volentieri"],
      hint: "offrire → offerto (irregular participle)",
      tags: ["verb", "irregular-participle", "offrire", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-077",
      type: "recognize",
      prompt: "spendere",
      accepted: ["to spend"],
      tags: ["verb", "infinitive", "spendere"],
      tier: 1,
    },
    {
      id: "a226-t1-078",
      type: "produce",
      prompt: "to spend",
      accepted: ["spendere"],
      tags: ["verb", "infinitive", "spendere"],
      tier: 1,
    },
    {
      id: "a226-t1-079",
      type: "recognize",
      prompt: "speso tutto",
      accepted: ["spent everything"],
      tags: ["verb", "irregular-participle", "spendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-080",
      type: "produce",
      prompt: "spent everything",
      accepted: ["speso tutto"],
      hint: "spendere → speso (irregular participle)",
      tags: ["verb", "irregular-participle", "spendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-081",
      type: "recognize",
      prompt: "vincere",
      accepted: ["to win"],
      tags: ["verb", "infinitive", "vincere"],
      tier: 1,
    },
    {
      id: "a226-t1-082",
      type: "produce",
      prompt: "to win",
      accepted: ["vincere"],
      tags: ["verb", "infinitive", "vincere"],
      tier: 1,
    },
    {
      id: "a226-t1-083",
      type: "recognize",
      prompt: "vinto per un pelo",
      accepted: ["won by a hair", "won narrowly"],
      tags: ["verb", "irregular-participle", "vincere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-084",
      type: "produce",
      prompt: "won by a hair",
      accepted: ["vinto per un pelo"],
      hint: "vincere → vinto (irregular participle)",
      tags: ["verb", "irregular-participle", "vincere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-085",
      type: "recognize",
      prompt: "perdere",
      accepted: ["to lose"],
      tags: ["verb", "infinitive", "perdere"],
      tier: 1,
    },
    {
      id: "a226-t1-086",
      type: "produce",
      prompt: "to lose",
      accepted: ["perdere"],
      tags: ["verb", "infinitive", "perdere"],
      tier: 1,
    },
    {
      id: "a226-t1-087",
      type: "recognize",
      prompt: "perso tempo",
      accepted: ["wasted time"],
      tags: ["verb", "irregular-participle", "perdere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-088",
      type: "produce",
      prompt: "wasted time",
      accepted: ["perso tempo"],
      hint: "perdere → perso (irregular participle)",
      tags: ["verb", "irregular-participle", "perdere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-089",
      type: "recognize",
      prompt: "succedere",
      accepted: ["to happen"],
      tags: ["verb", "infinitive", "succedere"],
      tier: 1,
    },
    {
      id: "a226-t1-090",
      type: "produce",
      prompt: "to happen",
      accepted: ["succedere"],
      tags: ["verb", "infinitive", "succedere"],
      tier: 1,
    },
    {
      id: "a226-t1-091",
      type: "recognize",
      prompt: "successo per caso",
      accepted: ["happened by chance"],
      tags: ["verb", "irregular-participle", "succedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-092",
      type: "produce",
      prompt: "happened by chance",
      accepted: ["successo per caso"],
      hint: "succedere → successo (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "succedere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-093",
      type: "recognize",
      prompt: "correre",
      accepted: ["to run"],
      tags: ["verb", "infinitive", "correre"],
      tier: 1,
    },
    {
      id: "a226-t1-094",
      type: "produce",
      prompt: "to run",
      accepted: ["correre"],
      tags: ["verb", "infinitive", "correre"],
      tier: 1,
    },
    {
      id: "a226-t1-095",
      type: "recognize",
      prompt: "corso a perdifiato",
      accepted: ["ran out of breath"],
      tags: ["verb", "irregular-participle", "correre", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-096",
      type: "produce",
      prompt: "ran out of breath",
      accepted: ["corso a perdifiato"],
      hint: "correre → corso (irregular participle)",
      tags: ["verb", "irregular-participle", "correre", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-097",
      type: "recognize",
      prompt: "bere",
      accepted: ["to drink"],
      tags: ["verb", "infinitive", "bere"],
      tier: 1,
    },
    {
      id: "a226-t1-098",
      type: "produce",
      prompt: "to drink",
      accepted: ["bere"],
      tags: ["verb", "infinitive", "bere"],
      tier: 1,
    },
    {
      id: "a226-t1-099",
      type: "recognize",
      prompt: "bevuto tutto d'un fiato",
      accepted: ["drank in one gulp"],
      tags: ["verb", "irregular-participle", "bere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-100",
      type: "produce",
      prompt: "drank in one gulp",
      accepted: ["bevuto tutto d'un fiato"],
      hint: "bere → bevuto (irregular participle)",
      tags: ["verb", "irregular-participle", "bere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-101",
      type: "recognize",
      prompt: "conoscere",
      accepted: ["to know", "to meet"],
      tags: ["verb", "infinitive", "conoscere"],
      tier: 1,
    },
    {
      id: "a226-t1-102",
      type: "produce",
      prompt: "to know / to meet",
      accepted: ["conoscere"],
      tags: ["verb", "infinitive", "conoscere"],
      tier: 1,
    },
    {
      id: "a226-t1-103",
      type: "recognize",
      prompt: "conosciuto per caso",
      accepted: ["met by chance"],
      tags: ["verb", "irregular-participle", "conoscere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-104",
      type: "produce",
      prompt: "met by chance",
      accepted: ["conosciuto per caso"],
      hint: "conoscere → conosciuto (irregular participle)",
      tags: ["verb", "irregular-participle", "conoscere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-105",
      type: "recognize",
      prompt: "piacere",
      accepted: ["to like", "to please"],
      tags: ["verb", "infinitive", "piacere"],
      tier: 1,
    },
    {
      id: "a226-t1-106",
      type: "produce",
      prompt: "to like / to please",
      accepted: ["piacere"],
      tags: ["verb", "infinitive", "piacere"],
      tier: 1,
    },
    {
      id: "a226-t1-107",
      type: "recognize",
      prompt: "piaciuto subito",
      accepted: ["liked right away"],
      tags: ["verb", "irregular-participle", "piacere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-108",
      type: "produce",
      prompt: "liked right away",
      accepted: ["piaciuto subito"],
      hint: "piacere → piaciuto (irregular participle) (uses essere)",
      tags: ["verb", "irregular-participle", "piacere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-109",
      type: "recognize",
      prompt: "dare",
      accepted: ["to give"],
      tags: ["verb", "infinitive", "dare"],
      tier: 1,
    },
    {
      id: "a226-t1-110",
      type: "produce",
      prompt: "to give",
      accepted: ["dare"],
      tags: ["verb", "infinitive", "dare"],
      tier: 1,
    },
    {
      id: "a226-t1-111",
      type: "recognize",
      prompt: "dato per scontato",
      accepted: ["taken for granted"],
      tags: ["verb", "irregular-participle", "dare", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-112",
      type: "produce",
      prompt: "taken for granted",
      accepted: ["dato per scontato"],
      hint: "dare → dato (irregular participle)",
      tags: ["verb", "irregular-participle", "dare", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-113",
      type: "recognize",
      prompt: "scegliere",
      accepted: ["to choose"],
      tags: ["verb", "infinitive", "scegliere"],
      tier: 1,
    },
    {
      id: "a226-t1-114",
      type: "produce",
      prompt: "to choose",
      accepted: ["scegliere"],
      tags: ["verb", "infinitive", "scegliere"],
      tier: 1,
    },
    {
      id: "a226-t1-115",
      type: "recognize",
      prompt: "scelto con cura",
      accepted: ["chosen carefully"],
      tags: ["verb", "irregular-participle", "scegliere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-116",
      type: "produce",
      prompt: "chosen carefully",
      accepted: ["scelto con cura"],
      hint: "scegliere → scelto (irregular participle)",
      tags: ["verb", "irregular-participle", "scegliere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-117",
      type: "recognize",
      prompt: "accendere",
      accepted: ["to turn on", "to light"],
      tags: ["verb", "infinitive", "accendere"],
      tier: 1,
    },
    {
      id: "a226-t1-118",
      type: "produce",
      prompt: "to turn on / to light",
      accepted: ["accendere"],
      tags: ["verb", "infinitive", "accendere"],
      tier: 1,
    },
    {
      id: "a226-t1-119",
      type: "recognize",
      prompt: "acceso per sbaglio",
      accepted: ["turned on by mistake"],
      tags: ["verb", "irregular-participle", "accendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-120",
      type: "produce",
      prompt: "turned on by mistake",
      accepted: ["acceso per sbaglio"],
      hint: "accendere → acceso (irregular participle)",
      tags: ["verb", "irregular-participle", "accendere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-121",
      type: "recognize",
      prompt: "spegnere",
      accepted: ["to turn off"],
      tags: ["verb", "infinitive", "spegnere"],
      tier: 1,
    },
    {
      id: "a226-t1-122",
      type: "produce",
      prompt: "to turn off",
      accepted: ["spegnere"],
      tags: ["verb", "infinitive", "spegnere"],
      tier: 1,
    },
    {
      id: "a226-t1-123",
      type: "recognize",
      prompt: "spento apposta",
      accepted: ["turned off on purpose"],
      tags: ["verb", "irregular-participle", "spegnere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-124",
      type: "produce",
      prompt: "turned off on purpose",
      accepted: ["spento apposta"],
      hint: "spegnere → spento (irregular participle)",
      tags: ["verb", "irregular-participle", "spegnere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-125",
      type: "recognize",
      prompt: "nascondere",
      accepted: ["to hide"],
      tags: ["verb", "infinitive", "nascondere"],
      tier: 1,
    },
    {
      id: "a226-t1-126",
      type: "produce",
      prompt: "to hide",
      accepted: ["nascondere"],
      tags: ["verb", "infinitive", "nascondere"],
      tier: 1,
    },
    {
      id: "a226-t1-127",
      type: "recognize",
      prompt: "nascosto sotto il letto",
      accepted: ["hidden under the bed"],
      tags: ["verb", "irregular-participle", "nascondere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-128",
      type: "produce",
      prompt: "hidden under the bed",
      accepted: ["nascosto sotto il letto"],
      hint: "nascondere → nascosto (irregular participle)",
      tags: ["verb", "irregular-participle", "nascondere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-129",
      type: "recognize",
      prompt: "permettere",
      accepted: ["to allow", "to permit"],
      tags: ["verb", "infinitive", "permettere"],
      tier: 1,
    },
    {
      id: "a226-t1-130",
      type: "produce",
      prompt: "to allow / to permit",
      accepted: ["permettere"],
      tags: ["verb", "infinitive", "permettere"],
      tier: 1,
    },
    {
      id: "a226-t1-131",
      type: "recognize",
      prompt: "permesso solo una volta",
      accepted: ["allowed only once"],
      tags: ["verb", "irregular-participle", "permettere", "collocation"],
      tier: 1,
    },
    {
      id: "a226-t1-132",
      type: "produce",
      prompt: "allowed only once",
      accepted: ["permesso solo una volta"],
      hint: "permettere → permesso (irregular participle)",
      tags: ["verb", "irregular-participle", "permettere", "collocation"],
      tier: 1,
    },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    {
      id: "a226-t2-001",
      type: "fill_blank",
      prompt: "Ieri sera ho ___ una torta per il compleanno di mia sorella.",
      accepted: ["fatto"],
      hint: "fare → fatto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "fare"],
      tier: 2,
    },
    {
      id: "a226-t2-002",
      type: "fill_blank",
      prompt: "Non ho ___ niente perché non volevo litigare.",
      accepted: ["detto"],
      hint: "dire → detto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "dire"],
      tier: 2,
    },
    {
      id: "a226-t2-003",
      type: "fill_blank",
      prompt: "Mio nonno ha ___ una lettera a mano ogni Natale.",
      accepted: ["scritto"],
      hint: "scrivere → scritto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "scrivere"],
      tier: 2,
    },
    {
      id: "a226-t2-004",
      type: "fill_blank",
      prompt: "Hai già ___ l'articolo che ti ho mandato?",
      accepted: ["letto"],
      hint: "leggere → letto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "leggere"],
      tier: 2,
    },
    {
      id: "a226-t2-005",
      type: "fill_blank",
      prompt: "Abbiamo ___ un film bellissimo al cinema sabato.",
      accepted: ["visto"],
      hint: "vedere → visto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "vedere"],
      tier: 2,
    },
    {
      id: "a226-t2-006",
      type: "fill_blank",
      prompt: "Il negozio ha ___ le porte alle nove in punto.",
      accepted: ["aperto"],
      hint: "aprire → aperto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "aprire"],
      tier: 2,
    },
    {
      id: "a226-t2-007",
      type: "fill_blank",
      prompt: "Hanno ___ la fabbrica dopo trent'anni di attività.",
      accepted: ["chiuso"],
      hint: "chiudere → chiuso (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "chiudere"],
      tier: 2,
    },
    {
      id: "a226-t2-008",
      type: "fill_blank",
      prompt: "Ho ___ l'autobus sbagliato e sono arrivato tardi.",
      accepted: ["preso"],
      hint: "prendere → preso (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "prendere"],
      tier: 2,
    },
    {
      id: "a226-t2-009",
      type: "fill_blank",
      prompt: "Dove hai ___ le chiavi della macchina?",
      accepted: ["messo"],
      hint: "mettere → messo (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "mettere"],
      tier: 2,
    },
    {
      id: "a226-t2-010",
      type: "fill_blank",
      prompt: "Il bambino ha ___ il bicchiere per sbaglio.",
      accepted: ["rotto"],
      hint: "rompere → rotto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "rompere"],
      tier: 2,
    },
    {
      id: "a226-t2-011",
      type: "fill_blank",
      prompt: "Mia figlia è ___ il tre marzo.",
      accepted: ["nata"],
      hint: "nascere → nato/a (uses essere; the participle agrees with the subject)",
      tags: ["fill_blank", "passato-prossimo", "nascere", "essere-agreement"],
      tier: 2,
    },
    {
      id: "a226-t2-012",
      type: "fill_blank",
      prompt: "I miei cugini sono ___ dall'Australia per il matrimonio.",
      accepted: ["venuti"],
      hint: "venire → venuto (uses essere; agrees in gender and number)",
      tags: ["fill_blank", "passato-prossimo", "venire", "essere-agreement"],
      tier: 2,
    },
    {
      id: "a226-t2-013",
      type: "fill_blank",
      prompt: "Dopo la discussione, lei è ___ in silenzio per ore.",
      accepted: ["rimasta"],
      hint: "rimanere → rimasto (uses essere; agrees with the subject)",
      tags: ["fill_blank", "passato-prossimo", "rimanere", "essere-agreement"],
      tier: 2,
    },
    {
      id: "a226-t2-014",
      type: "fill_blank",
      prompt: "Siamo ___ alla fermata sbagliata e abbiamo dovuto camminare.",
      accepted: ["scesi", "scese"],
      hint: "scendere → sceso (uses essere; agrees in gender and number)",
      tags: ["fill_blank", "passato-prossimo", "scendere", "essere-agreement"],
      tier: 2,
    },
    {
      id: "a226-t2-015",
      type: "fill_blank",
      prompt: "Le ho ___ scusa subito dopo l'errore.",
      accepted: ["chiesto"],
      hint: "chiedere → chiesto (irregular participle)",
      tags: ["fill_blank", "passato-prossimo", "chiedere"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a226-t3-001",
      type: "produce",
      prompt: "He paid attention to every detail.",
      accepted: ["Ha fatto attenzione a ogni dettaglio.", "Ha prestato attenzione a ogni dettaglio."],
      hint: "fare/prestare attenzione a — to pay attention to",
      tags: ["chunk", "fare", "attenzione"],
      tier: 3,
    },
    {
      id: "a226-t3-002",
      type: "produce",
      prompt: "We made a decision together.",
      accepted: ["Abbiamo preso una decisione insieme.", "Abbiamo deciso insieme."],
      hint: "prendere una decisione — a fixed collocation built on decidere",
      tags: ["chunk", "prendere", "decisione"],
      tier: 3,
    },
    {
      id: "a226-t3-003",
      type: "produce",
      prompt: "She tidied up the whole house before the guests arrived.",
      accepted: ["Ha messo in ordine tutta la casa prima dell'arrivo degli ospiti."],
      hint: "mettere in ordine — to tidy up",
      tags: ["chunk", "mettere", "ordine"],
      tier: 3,
    },
    {
      id: "a226-t3-004",
      type: "produce",
      prompt: "They always tease their little brother.",
      accepted: ["Prendono sempre in giro il fratellino.", "Prendono sempre in giro il loro fratellino."],
      hint: "prendere in giro — to tease, to make fun of",
      tags: ["chunk", "prendere", "idiom"],
      tier: 3,
    },
    {
      id: "a226-t3-005",
      type: "produce",
      prompt: "We said it and it happened right away — no sooner said than done.",
      accepted: ["L'abbiamo detto ed è successo subito: detto fatto."],
      hint: "detto fatto — no sooner said than done",
      tags: ["chunk", "dire", "fare", "idiom"],
      tier: 3,
    },
    {
      id: "a226-t3-006",
      type: "produce",
      prompt: "I took a chance and it paid off.",
      accepted: ["Ho corso un rischio ed è andata bene.", "Ho preso un rischio ed è andata bene."],
      hint: "correre/prendere un rischio — to take a risk",
      tags: ["chunk", "correre", "rischio"],
      tier: 3,
    },
    {
      id: "a226-t3-007",
      type: "produce",
      prompt: "She broke the ice with a joke.",
      accepted: ["Ha rotto il ghiaccio con una battuta."],
      hint: "rompere il ghiaccio — to break the ice",
      tags: ["chunk", "rompere", "idiom"],
      tier: 3,
    },
    {
      id: "a226-t3-008",
      type: "produce",
      prompt: "We took the shop's hours for granted.",
      accepted: ["Abbiamo dato per scontato l'orario del negozio."],
      hint: "dare per scontato — to take for granted",
      tags: ["chunk", "dare", "idiom"],
      tier: 3,
    },
    {
      id: "a226-t3-009",
      type: "produce",
      prompt: "He spent all his savings on the trip.",
      accepted: ["Ha speso tutti i suoi risparmi per il viaggio."],
      hint: "spendere i risparmi — to spend one's savings",
      tags: ["chunk", "spendere"],
      tier: 3,
    },
    {
      id: "a226-t3-010",
      type: "produce",
      prompt: "They won the match by a hair.",
      accepted: ["Hanno vinto la partita per un pelo."],
      hint: "vincere per un pelo — to win by a hair",
      tags: ["chunk", "vincere", "idiom"],
      tier: 3,
    },
    {
      id: "a226-t3-011",
      type: "produce",
      prompt: "I asked him a favor and he said yes right away.",
      accepted: ["Gli ho chiesto un favore e ha detto subito di sì."],
      hint: "chiedere un favore — to ask a favor",
      tags: ["chunk", "chiedere"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a226-t4-001",
      type: "passage_cloze",
      prompt: "Sabato scorso abbiamo organizzato una festa a sorpresa per il compleanno di Elena.\nAbbiamo comprato palloncini e decorazioni per tutta la casa.\nMio fratello ha ___ una torta al cioccolato con tre strati.\nQuando Elena è entrata, tutti hanno gridato \"Buon compleanno!\"\nLei si è messa a piangere dalla gioia.\nÈ stata una delle serate più belle dell'anno.",
      accepted: ["fatto"],
      hint: "fare → fatto — the participle needed here",
      tags: ["passage_cloze", "fare", "festa"],
      tier: 4,
      prerequisites: ["a226-t1-001", "a226-t1-002", "a226-t1-003", "a226-t1-004"],
    },
    {
      id: "a226-t4-002",
      type: "passage_cloze",
      prompt: "Il mese scorso ci siamo trasferiti in un appartamento più grande.\nAbbiamo passato due giorni interi a fare gli scatoloni.\nMio marito ha ___ tutti i libri nella libreria nuova, in ordine alfabetico.\nIo invece mi sono occupata della cucina.\nAlla fine eravamo stanchissimi ma soddisfatti.\nLa prima notte abbiamo dormito benissimo nel letto nuovo.",
      accepted: ["messo"],
      hint: "mettere → messo — the participle needed here",
      tags: ["passage_cloze", "mettere", "trasloco"],
      tier: 4,
      prerequisites: ["a226-t1-033", "a226-t1-034", "a226-t1-035", "a226-t1-036"],
    },
    {
      id: "a226-t4-003",
      type: "passage_cloze",
      prompt: "L'estate scorsa siamo andati in Sicilia in treno.\nDurante il viaggio abbiamo chiacchierato per ore con una coppia di Palermo.\nA un certo punto il treno si è fermato per un guasto tecnico.\nAbbiamo ___ due ore ferme in mezzo alla campagna.\nPer fortuna avevamo dei panini e dell'acqua con noi.\nAlla fine siamo arrivati a destinazione con molto ritardo.",
      accepted: ["perso"],
      hint: "perdere → perso — the participle needed here",
      tags: ["passage_cloze", "perdere", "viaggio"],
      tier: 4,
      prerequisites: ["a226-t1-085", "a226-t1-086", "a226-t1-087", "a226-t1-088"],
    },
    {
      id: "a226-t4-004",
      type: "passage_cloze",
      prompt: "La settimana scorsa ho fatto un colloquio di lavoro molto importante.\nIl direttore mi ha ___ perché volevo cambiare azienda dopo cinque anni.\nGli ho spiegato che cercavo nuove sfide professionali.\nAlla fine del colloquio mi ha stretto la mano con un sorriso.\nDue giorni dopo mi hanno richiamato con una proposta.\nOra aspetto solo di firmare il contratto.",
      accepted: ["chiesto"],
      hint: "chiedere → chiesto — the participle needed here",
      tags: ["passage_cloze", "chiedere", "lavoro"],
      tier: 4,
      prerequisites: ["a226-t1-061", "a226-t1-062", "a226-t1-063", "a226-t1-064"],
    },
  ],
};
export default unit;
