import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-22-professions",
  name: "Professions",
  level: "A2",
  theme: "Jobs & Careers",
  emoji: "👩‍⚕️",
  prerequisiteUnits: ["a2-unit-21-verbs-ii"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a222-t1-001",
      type: "recognize",
      prompt: "il medico / la dottoressa",
      accepted: ["the doctor", "doctor"],
      hint: "'il medico' is used for both genders in formal contexts; 'la dottoressa' for a female doctor",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-002",
      type: "recognize",
      prompt: "l'infermiere / l'infermiera",
      accepted: ["the nurse", "nurse"],
      hint: "male: l'infermiere — female: l'infermiera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-003",
      type: "recognize",
      prompt: "l'insegnante",
      accepted: ["the teacher", "teacher"],
      hint: "invariable — same form for male and female; use 'il/la' to show gender",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-004",
      type: "recognize",
      prompt: "l'avvocato / l'avvocatessa",
      accepted: ["the lawyer", "the solicitor", "the attorney", "lawyer"],
      hint: "male: l'avvocato — female: l'avvocatessa (though 'l'avvocato' is also used for women in formal contexts)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-005",
      type: "recognize",
      prompt: "l'ingegnere",
      accepted: ["the engineer", "engineer"],
      hint: "invariable form; female: l'ingegnera (informal) or l'ingegnere",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-006",
      type: "recognize",
      prompt: "l'architetto / l'architetta",
      accepted: ["the architect", "architect"],
      hint: "male: l'architetto — female: l'architetta",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-007",
      type: "recognize",
      prompt: "il cuoco / la cuoca",
      accepted: ["the cook", "the chef", "cook", "chef"],
      hint: "male: il cuoco — female: la cuoca; 'lo chef' is also used (borrowed from French)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-008",
      type: "recognize",
      prompt: "il cameriere / la cameriera",
      accepted: ["the waiter", "the waitress", "the server", "waiter", "waitress"],
      hint: "male: il cameriere — female: la cameriera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-009",
      type: "recognize",
      prompt: "il meccanico",
      accepted: ["the mechanic", "mechanic"],
      hint: "typically male form used; female: la meccanica",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-010",
      type: "recognize",
      prompt: "l'idraulico",
      accepted: ["the plumber", "plumber"],
      hint: "from 'idraulica' (hydraulics)",
      tags: ["professions", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-011",
      type: "recognize",
      prompt: "l'elettricista",
      accepted: ["the electrician", "electrician"],
      hint: "invariable ending in -ista; il/la elettricista",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-012",
      type: "recognize",
      prompt: "il/la farmacista",
      accepted: ["the pharmacist", "the chemist", "pharmacist", "chemist"],
      hint: "invariable -ista ending; gender shown by article: il farmacista / la farmacista",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-013",
      type: "recognize",
      prompt: "il poliziotto / la poliziotta",
      accepted: ["the police officer", "the policeman", "the policewoman", "police officer"],
      hint: "male: il poliziotto — female: la poliziotta",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-014",
      type: "recognize",
      prompt: "il pompiere / la pompiera",
      accepted: ["the firefighter", "the fireman", "the firewoman", "firefighter"],
      hint: "male: il pompiere — female: la pompiera",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-015",
      type: "recognize",
      prompt: "lo scrittore / la scrittrice",
      accepted: ["the writer", "the author", "writer", "author"],
      hint: "male: lo scrittore — female: la scrittrice (note the -trice ending for female)",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-016",
      type: "recognize",
      prompt: "il/la giornalista",
      accepted: ["the journalist", "journalist", "the reporter", "reporter"],
      hint: "invariable -ista ending; il giornalista (male) / la giornalista (female)",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-017",
      type: "recognize",
      prompt: "il/la musicista",
      accepted: ["the musician", "musician"],
      hint: "invariable -ista ending; gender shown by article",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-018",
      type: "recognize",
      prompt: "l'attore / l'attrice",
      accepted: ["the actor", "the actress", "actor", "actress"],
      hint: "male: l'attore — female: l'attrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-019",
      type: "recognize",
      prompt: "il pittore / la pittrice",
      accepted: ["the painter", "the artist", "painter", "artist"],
      hint: "male: il pittore — female: la pittrice; refers to a visual artist who paints",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-020",
      type: "recognize",
      prompt: "il/la commerciante",
      accepted: ["the shopkeeper", "the merchant", "the trader", "shopkeeper", "merchant", "trader"],
      hint: "invariable -ante ending; someone who runs a business or shop",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-021",
      type: "recognize",
      prompt: "il/la contabile",
      accepted: ["the accountant", "accountant"],
      hint: "invariable; both genders use the same form",
      tags: ["professions", "noun", "invariable", "A2"],
      tier: 1,
    },
    {
      id: "a222-t1-022",
      type: "recognize",
      prompt: "il programmatore / la programmatrice",
      accepted: ["the programmer", "the developer", "the software developer", "programmer", "developer"],
      hint: "male: il programmatore — female: la programmatrice",
      tags: ["professions", "noun", "gender", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Fill in the Blank ───────────────────────────────────────────
    {
      id: "a222-t2-001",
      type: "fill_blank",
      prompt: "Lavoro in ospedale. Faccio il ___ — opero i pazienti ogni giorno.",
      accepted: ["medico", "chirurgo"],
      hint: "a doctor who performs operations; 'il medico' works here too",
      tags: ["professions", "fill_blank", "faccio il", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-001"],
    },
    {
      id: "a222-t2-002",
      type: "fill_blank",
      prompt: "Mio fratello ha studiato giurisprudenza. Ora lavora come ___ in uno studio legale.",
      accepted: ["avvocato", "avvocatessa"],
      hint: "a legal professional; 'lavora come' is followed by the profession without an article",
      tags: ["professions", "fill_blank", "lavora come", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-004"],
    },
    {
      id: "a222-t2-003",
      type: "fill_blank",
      prompt: "Mi chiamo Sofia, sono ___. Insegno matematica in una scuola media.",
      accepted: ["insegnante"],
      hint: "'sono' + profession (no article in Italian); invariable noun",
      tags: ["professions", "fill_blank", "sono", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-003"],
    },
    {
      id: "a222-t2-004",
      type: "fill_blank",
      prompt: "Il rubinetto è rotto! Devo chiamare un ___.",
      accepted: ["idraulico"],
      hint: "the tradesperson who fixes pipes and water systems",
      tags: ["professions", "fill_blank", "A2"],
      tier: 2,
      prerequisites: ["a222-t1-010"],
    },

    // ── Tier 3 – English to Italian ──────────────────────────────────────────
    {
      id: "a222-t3-001",
      type: "produce",
      prompt: "My mother is a doctor.",
      accepted: ["Mia madre è medico.", "Mia madre è dottoressa.", "Mia madre fa il medico.", "Mia madre fa la dottoressa."],
      hint: "in Italian, profession after 'essere' takes no article — just 'è medico', not 'è una medico'",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-001"],
    },
    {
      id: "a222-t3-002",
      type: "produce",
      prompt: "He wants to be an engineer.",
      accepted: ["Vuole fare l'ingegnere.", "Vuole diventare ingegnere.", "Lui vuole fare l'ingegnere.", "Lui vuole diventare ingegnere."],
      hint: "'fare' + definite article + profession, or 'diventare' + profession without article",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-005"],
    },
    {
      id: "a222-t3-003",
      type: "produce",
      prompt: "She works as a journalist.",
      accepted: ["Lei lavora come giornalista.", "Lavora come giornalista."],
      hint: "'lavorare come' + profession — no article after 'come'",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-016"],
    },
    {
      id: "a222-t3-004",
      type: "produce",
      prompt: "What do you do for work?",
      accepted: [
        "Che lavoro fai?",
        "Cosa fai di lavoro?",
        "Che cosa fai di lavoro?",
        "Che lavoro fa?",
        "Cosa fa di lavoro?",
      ],
      hint: "'Che lavoro fai?' is the most common; 'fa' is the Lei (formal) form",
      tags: ["professions", "question", "phrase", "A2"],
      tier: 3,
    },
    {
      id: "a222-t3-005",
      type: "produce",
      prompt: "I am an accountant.",
      accepted: ["Sono contabile.", "Faccio il contabile.", "Faccio la contabile."],
      hint: "'sono' + profession without article; or 'faccio il/la' + profession",
      tags: ["professions", "sentence", "A2"],
      tier: 3,
      prerequisites: ["a222-t1-021"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a222-t4-001",
      type: "passage_cloze",
      prompt: "Mi chiamo Lorenzo Ferretti e ho trentadue anni.\nSono ___ — lavoro in uno studio di architettura a Milano da quattro anni.\nOgni giorno disegno edifici e creo progetti per i nostri clienti.\nPrima di diventare ___, ho studiato architettura all'università per cinque anni.\nIl mio sogno è costruire una biblioteca pubblica nel mio quartiere.\nNel tempo libero suono la chitarra, perché la musica è la mia seconda passione.",
      accepted: ["architetto", "architetta"],
      hint: "Lorenzo designs buildings — what is his profession? (male form)",
      tags: ["professions", "passage_cloze", "A2"],
      tier: 4,
      prerequisites: [
        "a222-t1-006",
        "a222-t1-003",
        "a222-t1-017",
        "a222-t3-002",
      ],
    },
  ],
};
export default unit;
