import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-17-comparisons",
  name: "Comparisons",
  level: "A2",
  theme: "Comparative & Superlative",
  emoji: "⚖️",
  prerequisiteUnits: ["a2-unit-16-conditional"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u17-t1-001",
      type: "produce",
      prompt: "fast (adjective)",
      accepted: ["veloce"],
      hint: "same form for m/f",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "u17-t1-002",
      type: "produce",
      prompt: "slow (adjective)",
      accepted: ["lento", "lenta"],
      hint: "lento/lenta",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "u17-t1-003",
      type: "produce",
      prompt: "the expensive (thing)",
      accepted: ["il caro", "il costoso"],
      hint: "think of 'dear' in price",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "u17-t1-004",
      type: "produce",
      prompt: "cheap / affordable (adjective)",
      accepted: ["economico", "economica"],
      hint: "sounds like 'economic'",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "u17-t1-005",
      type: "produce",
      prompt: "the heavy (thing)",
      accepted: ["il pesante"],
      hint: "same form for m/f",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "u17-t1-006",
      type: "produce",
      prompt: "light (not heavy) (adjective)",
      accepted: ["leggero", "leggera"],
      hint: "leggero/leggera",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "u17-t1-007",
      type: "produce",
      prompt: "difficult (adjective)",
      accepted: ["difficile"],
      hint: "same form for m/f",
      tags: ["adjective", "difficulty"],
      tier: 1,
    },
    {
      id: "u17-t1-008",
      type: "produce",
      prompt: "easy (adjective)",
      accepted: ["facile"],
      hint: "same form for m/f",
      tags: ["adjective", "difficulty"],
      tier: 1,
    },
    {
      id: "u17-t1-009",
      type: "produce",
      prompt: "important (adjective)",
      accepted: ["importante"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-010",
      type: "produce",
      prompt: "interesting (adjective)",
      accepted: ["interessante"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-011",
      type: "recognize",
      prompt: "molto",
      accepted: ["very", "a lot", "much"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-012",
      type: "recognize",
      prompt: "abbastanza",
      accepted: ["enough", "quite", "fairly"],
      tags: ["adverb", "degree"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u17-t2-001",
      type: "fill_blank",
      prompt: "This car is faster than that one. → Questa macchina è ___ veloce di quella.",
      accepted: ["più"],
      hint: "comparative of superiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-002",
      type: "fill_blank",
      prompt: "This bag is less heavy than mine. → Questa borsa è ___ pesante della mia.",
      accepted: ["meno"],
      hint: "comparative of inferiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-003",
      type: "fill_blank",
      prompt: "Maria is as fast as Luca. → Maria è ___ veloce come Luca.",
      accepted: ["così", "tanto"],
      hint: "equality comparative – così…come or tanto…quanto",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-004",
      type: "fill_blank",
      prompt: "This pizza is as good as that one. → Questa pizza è tanto buona ___ quella.",
      accepted: ["quanto"],
      hint: "tanto…quanto = as…as",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-005",
      type: "produce",
      prompt: "better (irregular comparative of buono)",
      accepted: ["migliore", "migliori"],
      hint: "buono → ___",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-006",
      type: "produce",
      prompt: "worse (irregular comparative of cattivo)",
      accepted: ["peggiore", "peggiori"],
      hint: "cattivo → ___",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-007",
      type: "produce",
      prompt: "greater / older (irregular comparative of grande)",
      accepted: ["maggiore", "maggiori"],
      hint: "grande → ___ (also means 'elder')",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-008",
      type: "produce",
      prompt: "smaller / younger (irregular comparative of piccolo)",
      accepted: ["minore", "minori"],
      hint: "piccolo → ___ (also means 'younger')",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-009",
      type: "fill_blank",
      prompt: "It is the most beautiful city. → È la ___ bella città.",
      accepted: ["più"],
      hint: "relative superlative: il/la più + adjective",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-010",
      type: "fill_blank",
      prompt: "Transform 'difficile' into its absolute superlative (masculine singular).",
      accepted: ["difficilissimo"],
      hint: "drop the final vowel, add -issimo",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-011",
      type: "fill_blank",
      prompt: "Transform 'veloce' into its absolute superlative (feminine singular).",
      accepted: ["velocissima"],
      hint: "drop the final -e, add -issima",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-012",
      type: "recognize",
      prompt: "tanto … quanto (used with adjectives)",
      accepted: ["as … as", "just as … as"],
      hint: "equality: tanto bello quanto…",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u17-t3-001",
      type: "produce",
      prompt: "It is bigger than…",
      accepted: ["È più grande di…", "è più grande di"],
      hint: "use più … di",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-002",
      type: "produce",
      prompt: "It is the most beautiful.",
      accepted: ["È il più bello.", "è il più bello", "È la più bella.", "è la più bella"],
      hint: "relative superlative",
      tags: ["chunk", "superlative"],
      tier: 3,
    },
    {
      id: "u17-t3-003",
      type: "produce",
      prompt: "It is absolutely delicious! (absolute superlative)",
      accepted: ["È buonissimo!", "è buonissimo", "È buonissima!", "è buonissima"],
      hint: "-issimo/-issima suffix",
      tags: ["chunk", "superlative", "absolute"],
      tier: 3,
    },
    {
      id: "u17-t3-004",
      type: "produce",
      prompt: "Less than I thought.",
      accepted: ["Meno di quanto pensavo.", "meno di quanto pensavo"],
      hint: "meno di quanto + imperfect",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-005",
      type: "produce",
      prompt: "This exam is more difficult than the last one.",
      accepted: [
        "Questo esame è più difficile dell'ultimo.",
        "Questo esame è più difficile di quello precedente.",
        "questo esame è più difficile dell'ultimo",
      ],
      hint: "più … di",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-006",
      type: "produce",
      prompt: "Rome is the most important city in Italy.",
      accepted: [
        "Roma è la città più importante d'Italia.",
        "Roma è la più importante città d'Italia.",
        "roma è la città più importante d'italia",
      ],
      hint: "relative superlative: la città più + adj",
      tags: ["chunk", "superlative"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze ──────────────────────────────────
    {
      id: "u17-t4-001",
      type: "produce",
      prompt: "Translate: My brother is younger than me, but he is better at football.",
      accepted: [
        "Mio fratello è più piccolo di me, ma è migliore nel calcio.",
        "Mio fratello è minore di me, ma è migliore a calcio.",
        "Mio fratello è più giovane di me, ma è migliore nel calcio.",
      ],
      hint: "younger = più piccolo / minore; better = migliore",
      tags: ["production", "comparative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-001", "u17-t2-005", "u17-t2-008"],
    },
    {
      id: "u17-t4-002",
      type: "fill_blank",
      prompt: "Complete with the correct comparative or superlative form:\nQuesto ristorante è ___ (the best) della città. Lo conosco da anni e non ho mai mangiato male qui.",
      accepted: ["il migliore", "il più buono"],
      hint: "irregular superlative of buono",
      tags: ["production", "superlative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-005", "u17-t2-009"],
    },
    {
      id: "u17-t4-003",
      type: "passage_cloze",
      prompt: "Ho visitato due musei oggi. Il primo era molto grande e interessante, ma il secondo era ancora ___.\nLe opere d'arte erano bellissime e i prezzi erano meno cari di quanto mi aspettassi.\nSicuramente tornerò: è il museo più importante della regione.",
      accepted: ["migliore"],
      hint: "irregular comparative of buono — 'even better'",
      tags: ["passage_cloze", "comparative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t1-010", "u17-t2-005", "u17-t2-002"],
    },
    {
      id: "u17-t4-004",
      type: "passage_cloze",
      prompt: "Marco e sua sorella sono molto diversi. Marco è alto e veloce, mentre sua sorella è più ___.\nIn compenso, lei studia più di lui: i suoi voti sono migliori e i professori dicono che è la più brava della classe.\nMarco non è triste però — dice che lo sport è più importante dei voti!",
      accepted: ["lenta"],
      hint: "opposite of veloce, feminine singular",
      tags: ["passage_cloze", "comparative", "adjective"],
      tier: 4,
      prerequisites: ["u17-t1-001", "u17-t1-002", "u17-t2-001", "u17-t2-005"],
    },
    {
      id: "u17-t4-005",
      type: "produce",
      prompt: "Translate: Italian grammar is as difficult as I expected, but it is more interesting than I thought.",
      accepted: [
        "La grammatica italiana è tanto difficile quanto mi aspettavo, ma è più interessante di quanto pensavo.",
        "La grammatica italiana è così difficile come mi aspettavo, ma è più interessante di quanto pensassi.",
      ],
      hint: "tanto … quanto for equality; più … di quanto for comparison",
      tags: ["production", "comparative", "equality"],
      tier: 4,
      prerequisites: ["u17-t1-007", "u17-t1-010", "u17-t2-001", "u17-t2-003", "u17-t2-004"],
    },

    // ── Tier 1 – Vocabulary (expansion) ───────────────────────────────────────
    {
      id: "u17-t1-013",
      type: "produce",
      prompt: "big / large (adjective)",
      accepted: ["grande"],
      hint: "same form for m/f",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "u17-t1-014",
      type: "recognize",
      prompt: "grande",
      accepted: ["big", "large"],
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "u17-t1-015",
      type: "produce",
      prompt: "small (adjective)",
      accepted: ["piccolo", "piccola"],
      hint: "piccolo/piccola",
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "u17-t1-016",
      type: "recognize",
      prompt: "piccolo",
      accepted: ["small", "little"],
      tags: ["adjective", "size"],
      tier: 1,
    },
    {
      id: "u17-t1-017",
      type: "produce",
      prompt: "tall (adjective)",
      accepted: ["alto", "alta"],
      hint: "alto/alta",
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "u17-t1-018",
      type: "recognize",
      prompt: "alto",
      accepted: ["tall", "high"],
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "u17-t1-019",
      type: "produce",
      prompt: "short (height) (adjective)",
      accepted: ["basso", "bassa"],
      hint: "basso/bassa",
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "u17-t1-020",
      type: "recognize",
      prompt: "basso",
      accepted: ["short", "low"],
      tags: ["adjective", "height"],
      tier: 1,
    },
    {
      id: "u17-t1-021",
      type: "produce",
      prompt: "long (adjective)",
      accepted: ["lungo", "lunga"],
      hint: "lungo/lunga",
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "u17-t1-022",
      type: "recognize",
      prompt: "lungo",
      accepted: ["long"],
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "u17-t1-023",
      type: "produce",
      prompt: "short (length) (adjective)",
      accepted: ["corto", "corta"],
      hint: "corto/corta",
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "u17-t1-024",
      type: "recognize",
      prompt: "corto",
      accepted: ["short"],
      tags: ["adjective", "length"],
      tier: 1,
    },
    {
      id: "u17-t1-025",
      type: "produce",
      prompt: "old (for people) (adjective)",
      accepted: ["vecchio", "vecchia"],
      hint: "vecchio/vecchia",
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "u17-t1-026",
      type: "recognize",
      prompt: "vecchio",
      accepted: ["old"],
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "u17-t1-027",
      type: "produce",
      prompt: "young (adjective)",
      accepted: ["giovane"],
      hint: "same form for m/f",
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "u17-t1-028",
      type: "recognize",
      prompt: "giovane",
      accepted: ["young"],
      tags: ["adjective", "age"],
      tier: 1,
    },
    {
      id: "u17-t1-029",
      type: "produce",
      prompt: "strong (adjective)",
      accepted: ["forte"],
      hint: "same form for m/f",
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "u17-t1-030",
      type: "recognize",
      prompt: "forte",
      accepted: ["strong"],
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "u17-t1-031",
      type: "produce",
      prompt: "weak (adjective)",
      accepted: ["debole"],
      hint: "same form for m/f",
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "u17-t1-032",
      type: "recognize",
      prompt: "debole",
      accepted: ["weak"],
      tags: ["adjective", "strength"],
      tier: 1,
    },
    {
      id: "u17-t1-033",
      type: "produce",
      prompt: "rich (adjective)",
      accepted: ["ricco", "ricca"],
      hint: "ricco/ricca",
      tags: ["adjective", "wealth"],
      tier: 1,
    },
    {
      id: "u17-t1-034",
      type: "recognize",
      prompt: "ricco",
      accepted: ["rich"],
      tags: ["adjective", "wealth"],
      tier: 1,
    },
    {
      id: "u17-t1-035",
      type: "produce",
      prompt: "poor (adjective)",
      accepted: ["povero", "povera"],
      hint: "povero/povera",
      tags: ["adjective", "wealth"],
      tier: 1,
    },
    {
      id: "u17-t1-036",
      type: "recognize",
      prompt: "povero",
      accepted: ["poor"],
      tags: ["adjective", "wealth"],
      tier: 1,
    },
    {
      id: "u17-t1-037",
      type: "produce",
      prompt: "hot (adjective)",
      accepted: ["caldo", "calda"],
      hint: "caldo/calda",
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "u17-t1-038",
      type: "recognize",
      prompt: "caldo",
      accepted: ["hot", "warm"],
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "u17-t1-039",
      type: "produce",
      prompt: "cold (adjective)",
      accepted: ["freddo", "fredda"],
      hint: "freddo/fredda",
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "u17-t1-040",
      type: "recognize",
      prompt: "freddo",
      accepted: ["cold"],
      tags: ["adjective", "temperature"],
      tier: 1,
    },
    {
      id: "u17-t1-041",
      type: "produce",
      prompt: "clean (adjective)",
      accepted: ["pulito", "pulita"],
      hint: "pulito/pulita",
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "u17-t1-042",
      type: "recognize",
      prompt: "pulito",
      accepted: ["clean"],
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "u17-t1-043",
      type: "produce",
      prompt: "dirty (adjective)",
      accepted: ["sporco", "sporca"],
      hint: "sporco/sporca",
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "u17-t1-044",
      type: "recognize",
      prompt: "sporco",
      accepted: ["dirty"],
      tags: ["adjective", "cleanliness"],
      tier: 1,
    },
    {
      id: "u17-t1-045",
      type: "produce",
      prompt: "safe (adjective)",
      accepted: ["sicuro", "sicura"],
      hint: "sicuro/sicura",
      tags: ["adjective", "safety"],
      tier: 1,
    },
    {
      id: "u17-t1-046",
      type: "recognize",
      prompt: "sicuro",
      accepted: ["safe", "sure", "certain"],
      tags: ["adjective", "safety"],
      tier: 1,
    },
    {
      id: "u17-t1-047",
      type: "produce",
      prompt: "dangerous (adjective)",
      accepted: ["pericoloso", "pericolosa"],
      hint: "pericoloso/pericolosa",
      tags: ["adjective", "safety"],
      tier: 1,
    },
    {
      id: "u17-t1-048",
      type: "recognize",
      prompt: "pericoloso",
      accepted: ["dangerous"],
      tags: ["adjective", "safety"],
      tier: 1,
    },
    {
      id: "u17-t1-049",
      type: "produce",
      prompt: "comfortable (adjective)",
      accepted: ["comodo", "comoda"],
      hint: "comodo/comoda",
      tags: ["adjective", "comfort"],
      tier: 1,
    },
    {
      id: "u17-t1-050",
      type: "recognize",
      prompt: "comodo",
      accepted: ["comfortable"],
      tags: ["adjective", "comfort"],
      tier: 1,
    },
    {
      id: "u17-t1-051",
      type: "produce",
      prompt: "uncomfortable (adjective)",
      accepted: ["scomodo", "scomoda"],
      hint: "scomodo/scomoda",
      tags: ["adjective", "comfort"],
      tier: 1,
    },
    {
      id: "u17-t1-052",
      type: "recognize",
      prompt: "scomodo",
      accepted: ["uncomfortable"],
      tags: ["adjective", "comfort"],
      tier: 1,
    },
    {
      id: "u17-t1-053",
      type: "produce",
      prompt: "popular (adjective)",
      accepted: ["popolare"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-054",
      type: "recognize",
      prompt: "popolare",
      accepted: ["popular"],
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-055",
      type: "produce",
      prompt: "rare / uncommon (adjective)",
      accepted: ["raro", "rara"],
      hint: "raro/rara",
      tags: ["adjective", "frequency"],
      tier: 1,
    },
    {
      id: "u17-t1-056",
      type: "recognize",
      prompt: "raro",
      accepted: ["rare", "uncommon"],
      tags: ["adjective", "frequency"],
      tier: 1,
    },
    {
      id: "u17-t1-057",
      type: "produce",
      prompt: "useful (adjective)",
      accepted: ["utile"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-058",
      type: "recognize",
      prompt: "utile",
      accepted: ["useful"],
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-059",
      type: "produce",
      prompt: "useless (adjective)",
      accepted: ["inutile"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-060",
      type: "recognize",
      prompt: "inutile",
      accepted: ["useless"],
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-061",
      type: "recognize",
      prompt: "troppo",
      accepted: ["too much", "too many", "too"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-062",
      type: "recognize",
      prompt: "poco",
      accepted: ["little", "few", "not much"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-063",
      type: "recognize",
      prompt: "quanto",
      accepted: ["how much", "how many", "as much as"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-064",
      type: "recognize",
      prompt: "altrettanto",
      accepted: ["just as much", "likewise", "equally"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-065",
      type: "recognize",
      prompt: "sempre più",
      accepted: ["more and more"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-066",
      type: "recognize",
      prompt: "sempre meno",
      accepted: ["less and less"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-067",
      type: "recognize",
      prompt: "il doppio",
      accepted: ["double", "twice as much"],
      tags: ["noun", "quantity"],
      tier: 1,
    },
    {
      id: "u17-t1-068",
      type: "recognize",
      prompt: "la metà",
      accepted: ["half"],
      tags: ["noun", "quantity"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (expansion) ──────────────────────────────────────────
    {
      id: "u17-t2-013",
      type: "produce",
      prompt: "better (irregular comparative adverb — modifies verbs, not the adjective migliore)",
      accepted: ["meglio"],
      hint: "canta meglio = sings better",
      tags: ["irregular", "comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-014",
      type: "produce",
      prompt: "worse (irregular comparative adverb — modifies verbs, not the adjective peggiore)",
      accepted: ["peggio"],
      hint: "gioca peggio = plays worse",
      tags: ["irregular", "comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-015",
      type: "produce",
      prompt: "excellent (irregular absolute superlative of buono, stronger than buonissimo)",
      accepted: ["ottimo", "ottima"],
      hint: "buono → ottimo",
      tags: ["irregular", "superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-016",
      type: "produce",
      prompt: "terrible (irregular absolute superlative of cattivo, stronger than cattivissimo)",
      accepted: ["pessimo", "pessima"],
      hint: "cattivo → pessimo",
      tags: ["irregular", "superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-017",
      type: "produce",
      prompt: "maximum (irregular absolute superlative of grande)",
      accepted: ["massimo", "massima"],
      hint: "grande → massimo",
      tags: ["irregular", "superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-018",
      type: "produce",
      prompt: "minimum (irregular absolute superlative of piccolo)",
      accepted: ["minimo", "minima"],
      hint: "piccolo → minimo",
      tags: ["irregular", "superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-019",
      type: "fill_blank",
      prompt: "He sings better than his brother. → Canta ___ di suo fratello.",
      accepted: ["meglio"],
      hint: "modifies the verb 'canta' — use the adverb, not migliore",
      tags: ["comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-020",
      type: "fill_blank",
      prompt: "This wine is better than the one from last year. → Questo vino è ___ di quello dell'anno scorso.",
      accepted: ["migliore"],
      hint: "modifies the noun 'vino' — use the adjective, not meglio",
      tags: ["comparative", "adjective", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-021",
      type: "fill_blank",
      prompt: "The team played worse than in the first half. → La squadra ha giocato ___ del primo tempo.",
      accepted: ["peggio"],
      hint: "modifies the verb 'ha giocato'",
      tags: ["comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-022",
      type: "fill_blank",
      prompt: "His mood is worse today than yesterday. → Il suo umore è ___ oggi che ieri.",
      accepted: ["peggiore"],
      hint: "modifies the noun 'umore'",
      tags: ["comparative", "adjective", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-023",
      type: "fill_blank",
      prompt: "I sleep better in a quiet room. → Dormo ___ in una stanza silenziosa.",
      accepted: ["meglio"],
      hint: "adverb modifying 'dormo'",
      tags: ["comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-024",
      type: "fill_blank",
      prompt: "Her second novel is worse than the first. → Il suo secondo romanzo è ___ del primo.",
      accepted: ["peggiore"],
      hint: "adjective modifying 'romanzo'",
      tags: ["comparative", "adjective", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-025",
      type: "fill_blank",
      prompt: "He drives better after the course. → Guida ___ dopo il corso.",
      accepted: ["meglio"],
      hint: "adverb modifying 'guida'",
      tags: ["comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-026",
      type: "fill_blank",
      prompt: "This hotel is worse than the one we saw yesterday. → Questo hotel è ___ di quello che abbiamo visto ieri.",
      accepted: ["peggiore"],
      hint: "adjective modifying 'hotel'",
      tags: ["comparative", "adjective", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-027",
      type: "fill_blank",
      prompt: "I feel better today than yesterday. → Mi sento ___ oggi rispetto a ieri.",
      accepted: ["meglio"],
      hint: "adverb modifying 'mi sento'",
      tags: ["comparative", "adverb", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-028",
      type: "fill_blank",
      prompt: "The quality of the service is worse than in the past. → La qualità del servizio è ___ rispetto al passato.",
      accepted: ["peggiore"],
      hint: "adjective modifying 'qualità'",
      tags: ["comparative", "adjective", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-029",
      type: "fill_blank",
      prompt: "Transform 'alto' into its absolute superlative (masculine singular).",
      accepted: ["altissimo"],
      hint: "drop final vowel, add -issimo",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-030",
      type: "fill_blank",
      prompt: "Transform 'ricco' into its absolute superlative (masculine singular).",
      accepted: ["ricchissimo"],
      hint: "add -h- before -issimo to keep the hard 'c' sound",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-031",
      type: "fill_blank",
      prompt: "Transform 'lungo' into its absolute superlative (feminine singular).",
      accepted: ["lunghissima"],
      hint: "add -h- before -issima to keep the hard 'g' sound",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-032",
      type: "fill_blank",
      prompt: "Transform 'giovane' into its absolute superlative (masculine singular).",
      accepted: ["giovanissimo"],
      hint: "drop the final -e, add -issimo",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-033",
      type: "fill_blank",
      prompt: "Transform 'utile' into its absolute superlative (feminine singular).",
      accepted: ["utilissima"],
      hint: "drop the final -e, add -issima",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-034",
      type: "fill_blank",
      prompt: "Transform 'sicuro' into its absolute superlative (feminine plural).",
      accepted: ["sicurissime"],
      hint: "add -issime for feminine plural",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-035",
      type: "fill_blank",
      prompt: "Transform 'popolare' into its absolute superlative (masculine plural).",
      accepted: ["popolarissimi"],
      hint: "drop the final -e, add -issimi",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-036",
      type: "fill_blank",
      prompt: "Transform 'pulito' into its absolute superlative (masculine plural).",
      accepted: ["pulitissimi"],
      hint: "add -issimi for masculine plural",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-037",
      type: "fill_blank",
      prompt: "He is the tallest boy in the class. → È il ragazzo ___ alto della classe.",
      accepted: ["più"],
      hint: "relative superlative: il/la più + adjective",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-038",
      type: "fill_blank",
      prompt: "It is the least dangerous route. → È il percorso ___ pericoloso.",
      accepted: ["meno"],
      hint: "relative superlative of inferiority: il/la meno + adjective",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-039",
      type: "fill_blank",
      prompt: "She is the richest woman in the city. → È la donna ___ ricca della città.",
      accepted: ["più"],
      hint: "relative superlative",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-040",
      type: "fill_blank",
      prompt: "This is the most comfortable chair in the house. → Questa è la sedia ___ comoda della casa.",
      accepted: ["più"],
      hint: "relative superlative",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-041",
      type: "fill_blank",
      prompt: "He is the youngest of the group. → È il ___ giovane del gruppo.",
      accepted: ["più"],
      hint: "relative superlative",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-042",
      type: "fill_blank",
      prompt: "It is the least useful tool in the drawer. → È lo strumento ___ utile del cassetto.",
      accepted: ["meno"],
      hint: "relative superlative of inferiority",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-043",
      type: "fill_blank",
      prompt: "This backpack is as light as that one. → Questo zaino è ___ leggero come quello.",
      accepted: ["così"],
      hint: "equality: così…come",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-044",
      type: "fill_blank",
      prompt: "My apartment is as clean as yours. → Il mio appartamento è tanto pulito ___ il tuo.",
      accepted: ["quanto"],
      hint: "tanto…quanto = as…as",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-045",
      type: "fill_blank",
      prompt: "This road is more dangerous than that one. → Questa strada è ___ pericolosa di quella.",
      accepted: ["più"],
      hint: "comparative of superiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-046",
      type: "fill_blank",
      prompt: "The hotel is less comfortable than we expected. → L'hotel è ___ comodo di quanto ci aspettavamo.",
      accepted: ["meno"],
      hint: "comparative of inferiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-047",
      type: "fill_blank",
      prompt: "He is as strong as his father. → È ___ forte quanto suo padre.",
      accepted: ["tanto"],
      hint: "tanto…quanto = as…as",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-048",
      type: "fill_blank",
      prompt: "This neighborhood is safer than the city center. → Questo quartiere è ___ sicuro del centro.",
      accepted: ["più"],
      hint: "comparative of superiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases (expansion) ─────────────────────────────────
    {
      id: "u17-t3-007",
      type: "produce",
      prompt: "my older brother",
      accepted: ["mio fratello maggiore", "il mio fratello maggiore"],
      hint: "maggiore = older, used for siblings",
      tags: ["chunk", "irregular", "family"],
      tier: 3,
    },
    {
      id: "u17-t3-008",
      type: "produce",
      prompt: "my younger sister",
      accepted: ["mia sorella minore", "la mia sorella minore"],
      hint: "minore = younger, used for siblings",
      tags: ["chunk", "irregular", "family"],
      tier: 3,
    },
    {
      id: "u17-t3-009",
      type: "produce",
      prompt: "Better late than never.",
      accepted: ["Meglio tardi che mai.", "meglio tardi che mai"],
      hint: "fixed expression with meglio",
      tags: ["chunk", "idiom", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-010",
      type: "produce",
      prompt: "Too bad for you. / Worse for you.",
      accepted: ["Peggio per te.", "peggio per te"],
      hint: "fixed expression with peggio",
      tags: ["chunk", "idiom", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-011",
      type: "produce",
      prompt: "Things are getting better.",
      accepted: ["Le cose vanno meglio.", "le cose vanno meglio"],
      hint: "andare meglio = to improve",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-012",
      type: "produce",
      prompt: "Things are getting worse.",
      accepted: ["Le cose vanno peggio.", "le cose vanno peggio"],
      hint: "andare peggio = to get worse",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-013",
      type: "produce",
      prompt: "by far the best",
      accepted: ["di gran lunga il migliore", "di gran lunga la migliore"],
      hint: "emphasizes a superlative",
      tags: ["chunk", "superlative", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-014",
      type: "produce",
      prompt: "in the best case",
      accepted: ["nel migliore dei casi"],
      hint: "fixed expression",
      tags: ["chunk", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-015",
      type: "produce",
      prompt: "in the worst case",
      accepted: ["nel peggiore dei casi"],
      hint: "fixed expression",
      tags: ["chunk", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-016",
      type: "produce",
      prompt: "to do one's best",
      accepted: ["fare del proprio meglio"],
      hint: "fixed expression with meglio",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-017",
      type: "produce",
      prompt: "to change for the better",
      accepted: ["cambiare in meglio"],
      hint: "fixed expression",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-018",
      type: "produce",
      prompt: "to change for the worse",
      accepted: ["cambiare in peggio"],
      hint: "fixed expression",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-019",
      type: "produce",
      prompt: "at most",
      accepted: ["al massimo"],
      hint: "fixed expression with massimo",
      tags: ["chunk", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-020",
      type: "produce",
      prompt: "at the very least",
      accepted: ["al minimo"],
      hint: "fixed expression with minimo",
      tags: ["chunk", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-021",
      type: "produce",
      prompt: "the bare minimum",
      accepted: ["il minimo indispensabile"],
      hint: "fixed expression",
      tags: ["chunk", "irregular"],
      tier: 3,
    },
    {
      id: "u17-t3-022",
      type: "produce",
      prompt: "more or less",
      accepted: ["più o meno"],
      hint: "fixed expression",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-023",
      type: "produce",
      prompt: "at most / at best",
      accepted: ["tutt'al più"],
      hint: "fixed expression",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-024",
      type: "produce",
      prompt: "as soon as possible",
      accepted: ["quanto prima"],
      hint: "fixed expression with quanto",
      tags: ["chunk", "adverb"],
      tier: 3,
    },
    {
      id: "u17-t3-025",
      type: "produce",
      prompt: "double the price",
      accepted: ["il doppio del prezzo"],
      hint: "il doppio di + noun",
      tags: ["chunk", "quantity"],
      tier: 3,
    },
    {
      id: "u17-t3-026",
      type: "produce",
      prompt: "half the price",
      accepted: ["la metà del prezzo"],
      hint: "la metà di + noun",
      tags: ["chunk", "quantity"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze (expansion) ───────────────────────
    {
      id: "u17-t4-006",
      type: "produce",
      prompt: "Translate: My older brother cooks better than me, but I dance better than him.",
      accepted: ["Mio fratello maggiore cucina meglio di me, ma io ballo meglio di lui."],
      hint: "maggiore = older (adjective); meglio = better (adverb)",
      tags: ["production", "irregular", "adverb"],
      tier: 4,
      prerequisites: ["u17-t2-007", "u17-t2-013"],
    },
    {
      id: "u17-t4-007",
      type: "produce",
      prompt: "Translate: This restaurant is excellent, but the one next door is terrible.",
      accepted: ["Questo ristorante è ottimo, ma quello accanto è pessimo."],
      hint: "ottimo/pessimo are irregular absolute superlatives",
      tags: ["production", "irregular", "superlative"],
      tier: 4,
      prerequisites: ["u17-t2-015", "u17-t2-016"],
    },
    {
      id: "u17-t4-008",
      type: "passage_cloze",
      prompt: "Ho comprato un computer nuovo la settimana scorsa. Costava il doppio di quello vecchio, ma la qualità è molto ___.\nÈ velocissimo e non si blocca mai, mentre il vecchio era lentissimo e si bloccava spesso.\nAl massimo lo terrò cinque anni, ma spero che duri di più.",
      accepted: ["migliore"],
      hint: "irregular comparative of buono, agrees with 'qualità' (feminine)",
      tags: ["passage_cloze", "irregular", "comparative"],
      tier: 4,
      prerequisites: ["u17-t1-067", "u17-t2-005"],
    },
    {
      id: "u17-t4-009",
      type: "passage_cloze",
      prompt: "Il mio quartiere sta cambiando. Prima era piuttosto pericoloso, ma adesso è molto più ___.\nCi sono meno macchine e le strade sono pulitissime.\nNel peggiore dei casi ci vorranno ancora due anni, ma le cose vanno decisamente meglio.",
      accepted: ["sicuro"],
      hint: "opposite of pericoloso",
      tags: ["passage_cloze", "adjective", "comparative"],
      tier: 4,
      prerequisites: ["u17-t1-047", "u17-t1-045", "u17-t3-015"],
    },
    {
      id: "u17-t4-010",
      type: "produce",
      prompt: "Translate: This apartment is smaller than the last one, but it is much more comfortable.",
      accepted: ["Questo appartamento è più piccolo dell'ultimo, ma è molto più comodo."],
      hint: "più piccolo = smaller; più comodo = more comfortable",
      tags: ["production", "comparative"],
      tier: 4,
      prerequisites: ["u17-t1-049", "u17-t2-001"],
    },
    {
      id: "u17-t4-011",
      type: "fill_blank",
      prompt: "Complete with the correct form:\nQuest'anno la squadra gioca ___ (better) rispetto alla stagione scorsa.",
      accepted: ["meglio"],
      hint: "adverb modifying 'gioca'",
      tags: ["production", "adverb", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-013"],
    },
    {
      id: "u17-t4-012",
      type: "fill_blank",
      prompt: "Complete with the correct form:\nIl servizio in questo hotel è ___ (the worst) che ho mai visto.",
      accepted: ["il peggiore"],
      hint: "irregular superlative, modifies 'servizio'",
      tags: ["production", "superlative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-006", "u17-t2-009"],
    },
    {
      id: "u17-t4-013",
      type: "passage_cloze",
      prompt: "Da giovane, mio nonno era molto povero. Lavorava tantissimo ma guadagnava poco.\nOggi, invece, è uno degli uomini più ___ della città: ha costruito tutto da solo.\nDice sempre che il lavoro onesto vale più di ogni fortuna ereditata.",
      accepted: ["ricchi"],
      hint: "opposite of povero, masculine plural agreeing with 'uomini'",
      tags: ["passage_cloze", "adjective", "superlative"],
      tier: 4,
      prerequisites: ["u17-t1-033", "u17-t1-035", "u17-t2-009"],
    },
    {
      id: "u17-t4-014",
      type: "produce",
      prompt: "Translate: Of the two routes, this one is the most dangerous, but it is also the shortest.",
      accepted: ["Delle due strade, questa è la più pericolosa, ma è anche la più corta."],
      hint: "relative superlative: il/la più + adjective",
      tags: ["production", "superlative"],
      tier: 4,
      prerequisites: ["u17-t1-047", "u17-t1-023", "u17-t2-009"],
    },
    {
      id: "u17-t4-015",
      type: "produce",
      prompt: "Translate: I earn less than my sister, but I work fewer hours.",
      accepted: ["Guadagno meno di mia sorella, ma lavoro meno ore."],
      hint: "meno di + comparison; meno + noun",
      tags: ["production", "comparative"],
      tier: 4,
      prerequisites: ["u17-t2-002"],
    },
  ],
};
export default unit;
