import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-29-restaurants-food-culture",
  name: "Restaurants & Food Culture",
  level: "A2",
  theme: "Restaurants & Food Culture",
  emoji: "🍽️",
  prerequisiteUnits: ["a2-unit-28-travel-transportation"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a229-t1-001",
      type: "recognize",
      prompt: "prenotare un tavolo",
      accepted: ["to book a table", "to reserve a table"],
      tags: ["restaurant", "verb", "reservation"],
      tier: 1,
    },
    {
      id: "a229-t1-002",
      type: "produce",
      prompt: "to reserve a table (at a restaurant)",
      accepted: ["prenotare un tavolo"],
      tags: ["restaurant", "verb", "reservation"],
      tier: 1,
    },
    {
      id: "a229-t1-003",
      type: "recognize",
      prompt: "la prenotazione",
      accepted: ["the reservation", "reservation"],
      tags: ["restaurant", "noun", "reservation"],
      tier: 1,
    },
    {
      id: "a229-t1-004",
      type: "produce",
      prompt: "reservation (booking)",
      accepted: ["la prenotazione"],
      tags: ["restaurant", "noun", "reservation"],
      tier: 1,
    },
    {
      id: "a229-t1-005",
      type: "recognize",
      prompt: "il tavolo",
      accepted: ["the table", "table"],
      tags: ["restaurant", "noun", "furniture"],
      tier: 1,
    },
    {
      id: "a229-t1-006",
      type: "produce",
      prompt: "table",
      accepted: ["il tavolo"],
      tags: ["restaurant", "noun", "furniture"],
      tier: 1,
    },
    {
      id: "a229-t1-007",
      type: "recognize",
      prompt: "il cameriere",
      accepted: ["the waiter", "waiter"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-008",
      type: "produce",
      prompt: "waiter",
      accepted: ["il cameriere"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-009",
      type: "recognize",
      prompt: "la cameriera",
      accepted: ["the waitress", "waitress"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-010",
      type: "produce",
      prompt: "waitress",
      accepted: ["la cameriera"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-011",
      type: "recognize",
      prompt: "il cliente",
      accepted: ["the customer", "customer"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-012",
      type: "produce",
      prompt: "customer (at a restaurant)",
      accepted: ["il cliente", "la cliente"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-013",
      type: "recognize",
      prompt: "il menu",
      accepted: ["the menu", "menu"],
      tags: ["restaurant", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-014",
      type: "produce",
      prompt: "menu",
      accepted: ["il menu"],
      tags: ["restaurant", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-015",
      type: "recognize",
      prompt: "la lista dei vini",
      accepted: ["the wine list", "wine list"],
      tags: ["restaurant", "noun", "wine"],
      tier: 1,
    },
    {
      id: "a229-t1-016",
      type: "produce",
      prompt: "wine list",
      accepted: ["la lista dei vini"],
      tags: ["restaurant", "noun", "wine"],
      tier: 1,
    },
    {
      id: "a229-t1-017",
      type: "recognize",
      prompt: "il conto",
      accepted: ["the bill", "the check"],
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-018",
      type: "produce",
      prompt: "the bill (at a restaurant)",
      accepted: ["il conto"],
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-019",
      type: "recognize",
      prompt: "il coperto",
      accepted: ["the cover charge", "cover charge"],
      hint: "a small per-person fee added to Italian restaurant bills",
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-020",
      type: "produce",
      prompt: "cover charge",
      accepted: ["il coperto"],
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-021",
      type: "recognize",
      prompt: "la mancia",
      accepted: ["the tip", "tip"],
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-022",
      type: "produce",
      prompt: "tip (gratuity)",
      accepted: ["la mancia"],
      tags: ["restaurant", "noun", "payment"],
      tier: 1,
    },
    {
      id: "a229-t1-023",
      type: "recognize",
      prompt: "ordinare",
      accepted: ["to order"],
      tags: ["restaurant", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-024",
      type: "produce",
      prompt: "to order (food)",
      accepted: ["ordinare"],
      tags: ["restaurant", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-025",
      type: "recognize",
      prompt: "l'ordinazione",
      accepted: ["the order"],
      hint: "noun form of ordinare",
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-026",
      type: "produce",
      prompt: "order (what you ordered)",
      accepted: ["l'ordinazione"],
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-027",
      type: "recognize",
      prompt: "portare via",
      accepted: ["to take away", "to take out"],
      hint: "used for food to go",
      tags: ["restaurant", "verb", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-028",
      type: "produce",
      prompt: "to take away (food)",
      accepted: ["portare via"],
      tags: ["restaurant", "verb", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-029",
      type: "recognize",
      prompt: "mangiare fuori",
      accepted: ["to eat out"],
      tags: ["restaurant", "verb", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-030",
      type: "produce",
      prompt: "to eat out",
      accepted: ["mangiare fuori"],
      tags: ["restaurant", "verb", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-031",
      type: "recognize",
      prompt: "l'antipasto",
      accepted: ["the starter", "appetizer"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-032",
      type: "produce",
      prompt: "starter (appetizer)",
      accepted: ["l'antipasto"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-033",
      type: "recognize",
      prompt: "il primo",
      accepted: ["the first course"],
      hint: "typically pasta, rice, or soup",
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-034",
      type: "produce",
      prompt: "first course",
      accepted: ["il primo"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-035",
      type: "recognize",
      prompt: "il secondo",
      accepted: ["the main course"],
      hint: "typically meat or fish",
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-036",
      type: "produce",
      prompt: "main course",
      accepted: ["il secondo"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-037",
      type: "recognize",
      prompt: "il contorno",
      accepted: ["the side dish"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-038",
      type: "produce",
      prompt: "side dish",
      accepted: ["il contorno"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-039",
      type: "recognize",
      prompt: "il dolce",
      accepted: ["the dessert"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-040",
      type: "produce",
      prompt: "dessert",
      accepted: ["il dolce"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-041",
      type: "recognize",
      prompt: "la portata",
      accepted: ["the course"],
      hint: "generic word for a course in a meal",
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-042",
      type: "produce",
      prompt: "course (of a meal)",
      accepted: ["la portata"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-043",
      type: "recognize",
      prompt: "saporito",
      accepted: ["tasty", "flavorful"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-044",
      type: "produce",
      prompt: "tasty",
      accepted: ["saporito"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-045",
      type: "recognize",
      prompt: "piccante",
      accepted: ["spicy"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-046",
      type: "produce",
      prompt: "spicy",
      accepted: ["piccante"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-047",
      type: "recognize",
      prompt: "leggero",
      accepted: ["light"],
      hint: "used for food that's easy to digest",
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-048",
      type: "produce",
      prompt: "light (food)",
      accepted: ["leggero"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-049",
      type: "recognize",
      prompt: "pesante",
      accepted: ["heavy"],
      hint: "used for rich or filling food",
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-050",
      type: "produce",
      prompt: "heavy (food)",
      accepted: ["pesante"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-051",
      type: "recognize",
      prompt: "di stagione",
      accepted: ["seasonal", "in season"],
      tags: ["food", "adjective", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-052",
      type: "produce",
      prompt: "seasonal (produce)",
      accepted: ["di stagione"],
      tags: ["food", "adjective", "phrase"],
      tier: 1,
    },
    {
      id: "a229-t1-053",
      type: "recognize",
      prompt: "fresco",
      accepted: ["fresh"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-054",
      type: "produce",
      prompt: "fresh",
      accepted: ["fresco"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-055",
      type: "recognize",
      prompt: "squisito",
      accepted: ["delicious", "exquisite"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-056",
      type: "produce",
      prompt: "delicious",
      accepted: ["squisito"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-057",
      type: "recognize",
      prompt: "insipido",
      accepted: ["bland", "tasteless"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-058",
      type: "produce",
      prompt: "bland",
      accepted: ["insipido"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-059",
      type: "recognize",
      prompt: "cotto",
      accepted: ["cooked"],
      tags: ["food", "adjective", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-060",
      type: "produce",
      prompt: "cooked",
      accepted: ["cotto"],
      tags: ["food", "adjective", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-061",
      type: "recognize",
      prompt: "crudo",
      accepted: ["raw"],
      tags: ["food", "adjective", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-062",
      type: "produce",
      prompt: "raw",
      accepted: ["crudo"],
      tags: ["food", "adjective", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-063",
      type: "recognize",
      prompt: "al dente",
      accepted: ["firm to the bite", "al dente"],
      hint: "how pasta should be cooked — firm, not soft",
      tags: ["food", "adjective", "phrase", "pasta"],
      tier: 1,
    },
    {
      id: "a229-t1-064",
      type: "produce",
      prompt: "cooked al dente (firm)",
      accepted: ["al dente"],
      tags: ["food", "adjective", "phrase", "pasta"],
      tier: 1,
    },
    {
      id: "a229-t1-065",
      type: "recognize",
      prompt: "alla griglia",
      accepted: ["grilled"],
      tags: ["food", "adjective", "phrase", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-066",
      type: "produce",
      prompt: "grilled",
      accepted: ["alla griglia"],
      tags: ["food", "adjective", "phrase", "preparation"],
      tier: 1,
    },
    {
      id: "a229-t1-067",
      type: "recognize",
      prompt: "la merenda",
      accepted: ["the afternoon snack"],
      hint: "a small snack eaten mid-afternoon, common for kids",
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-068",
      type: "produce",
      prompt: "afternoon snack",
      accepted: ["la merenda"],
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-069",
      type: "recognize",
      prompt: "l'aperitivo",
      accepted: ["the aperitif"],
      hint: "pre-dinner drink with small snacks, a common Italian ritual",
      tags: ["food", "noun", "meal", "culture"],
      tier: 1,
    },
    {
      id: "a229-t1-070",
      type: "produce",
      prompt: "aperitif (pre-dinner drink)",
      accepted: ["l'aperitivo"],
      tags: ["food", "noun", "meal", "culture"],
      tier: 1,
    },
    {
      id: "a229-t1-071",
      type: "recognize",
      prompt: "la pausa pranzo",
      accepted: ["the lunch break"],
      tags: ["food", "noun", "meal", "culture"],
      tier: 1,
    },
    {
      id: "a229-t1-072",
      type: "produce",
      prompt: "lunch break",
      accepted: ["la pausa pranzo"],
      tags: ["food", "noun", "meal", "culture"],
      tier: 1,
    },
    {
      id: "a229-t1-073",
      type: "recognize",
      prompt: "lo spuntino",
      accepted: ["the snack"],
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-074",
      type: "produce",
      prompt: "snack",
      accepted: ["lo spuntino"],
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-075",
      type: "recognize",
      prompt: "il risotto",
      accepted: ["risotto"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-076",
      type: "produce",
      prompt: "risotto",
      accepted: ["il risotto"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-077",
      type: "recognize",
      prompt: "la zuppa",
      accepted: ["the soup"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-078",
      type: "produce",
      prompt: "soup",
      accepted: ["la zuppa"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-079",
      type: "recognize",
      prompt: "il brodo",
      accepted: ["the broth"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-080",
      type: "produce",
      prompt: "broth",
      accepted: ["il brodo"],
      tags: ["food", "noun", "dish"],
      tier: 1,
    },
    {
      id: "a229-t1-081",
      type: "recognize",
      prompt: "il condimento",
      accepted: ["the seasoning", "dressing"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-082",
      type: "produce",
      prompt: "seasoning (dressing)",
      accepted: ["il condimento"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-083",
      type: "recognize",
      prompt: "l'olio d'oliva",
      accepted: ["olive oil"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-084",
      type: "produce",
      prompt: "olive oil",
      accepted: ["l'olio d'oliva"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-085",
      type: "recognize",
      prompt: "l'aceto",
      accepted: ["vinegar"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-086",
      type: "produce",
      prompt: "vinegar",
      accepted: ["l'aceto"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-087",
      type: "recognize",
      prompt: "il pepe",
      accepted: ["pepper"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-088",
      type: "produce",
      prompt: "pepper (spice)",
      accepted: ["il pepe"],
      tags: ["food", "noun", "ingredient"],
      tier: 1,
    },
    {
      id: "a229-t1-089",
      type: "recognize",
      prompt: "la ricetta",
      accepted: ["the recipe"],
      tags: ["food", "noun", "cooking"],
      tier: 1,
    },
    {
      id: "a229-t1-090",
      type: "produce",
      prompt: "recipe",
      accepted: ["la ricetta"],
      tags: ["food", "noun", "cooking"],
      tier: 1,
    },
    {
      id: "a229-t1-091",
      type: "recognize",
      prompt: "l'ingrediente",
      accepted: ["the ingredient"],
      tags: ["food", "noun", "cooking"],
      tier: 1,
    },
    {
      id: "a229-t1-092",
      type: "produce",
      prompt: "ingredient",
      accepted: ["l'ingrediente"],
      tags: ["food", "noun", "cooking"],
      tier: 1,
    },
    {
      id: "a229-t1-093",
      type: "recognize",
      prompt: "il piatto",
      accepted: ["the dish", "the plate"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-094",
      type: "produce",
      prompt: "dish (food)",
      accepted: ["il piatto"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-095",
      type: "recognize",
      prompt: "la porzione",
      accepted: ["the portion"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-096",
      type: "produce",
      prompt: "portion",
      accepted: ["la porzione"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-097",
      type: "recognize",
      prompt: "offrire da bere",
      accepted: ["to buy someone a drink"],
      hint: "offrire + object = to treat someone to something",
      tags: ["restaurant", "verb", "social"],
      tier: 1,
    },
    {
      id: "a229-t1-098",
      type: "produce",
      prompt: "to buy someone a drink",
      accepted: ["offrire da bere"],
      tags: ["restaurant", "verb", "social"],
      tier: 1,
    },
    {
      id: "a229-t1-099",
      type: "recognize",
      prompt: "il locale",
      accepted: ["the venue", "the eatery"],
      hint: "generic word for a bar, restaurant, or club",
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-100",
      type: "produce",
      prompt: "venue (eatery, place)",
      accepted: ["il locale"],
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-101",
      type: "recognize",
      prompt: "la trattoria",
      accepted: ["informal restaurant", "trattoria"],
      hint: "family-run, simpler than a ristorante",
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-102",
      type: "produce",
      prompt: "trattoria (informal restaurant)",
      accepted: ["la trattoria"],
      tags: ["restaurant", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-103",
      type: "recognize",
      prompt: "la specialità della casa",
      accepted: ["the house specialty"],
      tags: ["restaurant", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-104",
      type: "produce",
      prompt: "house specialty",
      accepted: ["la specialità della casa"],
      tags: ["restaurant", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-105",
      type: "recognize",
      prompt: "gustare",
      accepted: ["to savor", "to taste"],
      tags: ["food", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-106",
      type: "produce",
      prompt: "to savor (food)",
      accepted: ["gustare"],
      tags: ["food", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-107",
      type: "recognize",
      prompt: "il gusto",
      accepted: ["the taste", "flavor"],
      tags: ["food", "noun", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-108",
      type: "produce",
      prompt: "taste (flavor)",
      accepted: ["il gusto"],
      tags: ["food", "noun", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-109",
      type: "recognize",
      prompt: "gustoso",
      accepted: ["flavorful"],
      hint: "word family of gustare / il gusto",
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-110",
      type: "produce",
      prompt: "flavorful",
      accepted: ["gustoso"],
      tags: ["food", "adjective", "taste"],
      tier: 1,
    },
    {
      id: "a229-t1-111",
      type: "recognize",
      prompt: "la fame",
      accepted: ["hunger"],
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-112",
      type: "produce",
      prompt: "hunger",
      accepted: ["la fame"],
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-113",
      type: "recognize",
      prompt: "affamato",
      accepted: ["starving", "hungry"],
      hint: "word family of la fame",
      tags: ["food", "adjective", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-114",
      type: "produce",
      prompt: "starving",
      accepted: ["affamato"],
      tags: ["food", "adjective", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-115",
      type: "recognize",
      prompt: "la sete",
      accepted: ["thirst"],
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-116",
      type: "produce",
      prompt: "thirst",
      accepted: ["la sete"],
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-117",
      type: "recognize",
      prompt: "il tovagliolo",
      accepted: ["the napkin"],
      tags: ["restaurant", "noun", "tableware"],
      tier: 1,
    },
    {
      id: "a229-t1-118",
      type: "produce",
      prompt: "napkin",
      accepted: ["il tovagliolo"],
      tags: ["restaurant", "noun", "tableware"],
      tier: 1,
    },
    {
      id: "a229-t1-119",
      type: "recognize",
      prompt: "le posate",
      accepted: ["the cutlery", "silverware"],
      tags: ["restaurant", "noun", "tableware"],
      tier: 1,
    },
    {
      id: "a229-t1-120",
      type: "produce",
      prompt: "cutlery",
      accepted: ["le posate"],
      tags: ["restaurant", "noun", "tableware"],
      tier: 1,
    },
    {
      id: "a229-t1-121",
      type: "recognize",
      prompt: "il pasto",
      accepted: ["the meal"],
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-122",
      type: "produce",
      prompt: "meal",
      accepted: ["il pasto"],
      tags: ["food", "noun", "meal"],
      tier: 1,
    },
    {
      id: "a229-t1-123",
      type: "recognize",
      prompt: "l'appetito",
      accepted: ["appetite"],
      hint: "used in the phrase 'buon appetito'",
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-124",
      type: "produce",
      prompt: "appetite",
      accepted: ["l'appetito"],
      tags: ["food", "noun", "feeling"],
      tier: 1,
    },
    {
      id: "a229-t1-125",
      type: "recognize",
      prompt: "il cuoco",
      accepted: ["the cook", "chef"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-126",
      type: "produce",
      prompt: "cook (chef)",
      accepted: ["il cuoco"],
      tags: ["restaurant", "noun", "people"],
      tier: 1,
    },
    {
      id: "a229-t1-127",
      type: "recognize",
      prompt: "la cucina",
      accepted: ["the cuisine", "kitchen"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-128",
      type: "produce",
      prompt: "cuisine (kitchen)",
      accepted: ["la cucina"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-129",
      type: "recognize",
      prompt: "gradire",
      accepted: ["to like", "to appreciate"],
      hint: "formal verb used by waiters, as in 'Cosa gradisce?'",
      tags: ["restaurant", "verb", "formal"],
      tier: 1,
    },
    {
      id: "a229-t1-130",
      type: "produce",
      prompt: "to appreciate (formal, of food or drink)",
      accepted: ["gradire"],
      tags: ["restaurant", "verb", "formal"],
      tier: 1,
    },
    {
      id: "a229-t1-131",
      type: "recognize",
      prompt: "il boccone",
      accepted: ["the bite", "mouthful"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-132",
      type: "produce",
      prompt: "bite (mouthful)",
      accepted: ["il boccone"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-133",
      type: "recognize",
      prompt: "l'assaggio",
      accepted: ["the taste", "sample"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-134",
      type: "produce",
      prompt: "taste (sample)",
      accepted: ["l'assaggio"],
      tags: ["food", "noun"],
      tier: 1,
    },
    {
      id: "a229-t1-135",
      type: "recognize",
      prompt: "assaggiare",
      accepted: ["to taste", "to sample"],
      hint: "word family of l'assaggio",
      tags: ["food", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-136",
      type: "produce",
      prompt: "to sample (food)",
      accepted: ["assaggiare"],
      tags: ["food", "verb"],
      tier: 1,
    },
    {
      id: "a229-t1-137",
      type: "recognize",
      prompt: "il piatto del giorno",
      accepted: ["the dish of the day"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-138",
      type: "produce",
      prompt: "dish of the day",
      accepted: ["il piatto del giorno"],
      tags: ["food", "noun", "menu"],
      tier: 1,
    },
    {
      id: "a229-t1-139",
      type: "recognize",
      prompt: "il conto alla romana",
      accepted: ["splitting the bill", "going dutch"],
      hint: "idiom: each person pays for their own share",
      tags: ["restaurant", "noun", "payment", "idiom"],
      tier: 1,
    },
    {
      id: "a229-t1-140",
      type: "produce",
      prompt: "splitting the bill (each pays their own share)",
      accepted: ["il conto alla romana"],
      tags: ["restaurant", "noun", "payment", "idiom"],
      tier: 1,
    },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    {
      id: "a229-t2-001",
      type: "fill_blank",
      prompt: "___ prenotare un tavolo per due, per stasera alle otto.",
      accepted: ["Vorrei"],
      hint: "conditional of volere — polite request, 'I would like'",
      tags: ["fill_blank", "conditional", "reservation"],
      tier: 2,
    },
    {
      id: "a229-t2-002",
      type: "fill_blank",
      prompt: "___ avere un bicchiere d'acqua, per favore?",
      accepted: ["Potrei"],
      hint: "conditional of potere — polite request, 'could I'",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-003",
      type: "fill_blank",
      prompt: "Mi ___ un vino da abbinare al pesce?",
      accepted: ["consiglierebbe"],
      hint: "conditional of consigliare, formal 'lei' address to a waiter",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-004",
      type: "fill_blank",
      prompt: "Ci ___ il conto, per favore?",
      accepted: ["porterebbe"],
      hint: "conditional of portare, formal 'lei' address to a waiter",
      tags: ["fill_blank", "conditional", "payment"],
      tier: 2,
    },
    {
      id: "a229-t2-005",
      type: "fill_blank",
      prompt: "Ti ___ di venire a cena con noi sabato?",
      accepted: ["andrebbe"],
      hint: "idiom 'andare bene' in the conditional — 'would you feel like'",
      tags: ["fill_blank", "conditional", "invitation"],
      tier: 2,
    },
    {
      id: "a229-t2-006",
      type: "fill_blank",
      prompt: "Senza il tavolo vicino alla finestra, la cena non ___ così romantica.",
      accepted: ["sarebbe"],
      hint: "conditional of essere, hypothetical situation",
      tags: ["fill_blank", "conditional", "hypothetical"],
      tier: 2,
    },
    {
      id: "a229-t2-007",
      type: "fill_blank",
      prompt: "___ un secondo senza contorno, se possibile.",
      accepted: ["Prenderei"],
      hint: "conditional of prendere — polite ordering",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-008",
      type: "fill_blank",
      prompt: "Mi ___ molto assaggiare il tiramisù della casa.",
      accepted: ["piacerebbe"],
      hint: "conditional of piacere — 'I would like'",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-009",
      type: "fill_blank",
      prompt: "___ chiederle se il pesce è fresco di giornata?",
      accepted: ["Potrebbe"],
      hint: "conditional of potere, formal 'lei' address",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-010",
      type: "fill_blank",
      prompt: "Noi ___ un tavolo vicino alla cucina, se non le dispiace.",
      accepted: ["vorremmo"],
      hint: "conditional of volere, 'noi' form",
      tags: ["fill_blank", "conditional", "reservation"],
      tier: 2,
    },
    {
      id: "a229-t2-011",
      type: "fill_blank",
      prompt: "Scusi, mi ___ un tovagliolo in più?",
      accepted: ["darebbe"],
      hint: "conditional of dare — polite request to a waiter",
      tags: ["fill_blank", "conditional", "ordering"],
      tier: 2,
    },
    {
      id: "a229-t2-012",
      type: "fill_blank",
      prompt: "Senza prenotazione, non ___ mai un posto libero di sabato sera.",
      accepted: ["troveremmo"],
      hint: "conditional of trovare, 'noi' form, hypothetical without a booking",
      tags: ["fill_blank", "conditional", "reservation"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a229-t3-001",
      type: "produce",
      prompt: "I'd like to order now.",
      accepted: ["Vorrei ordinare adesso.", "Vorrei ordinare ora."],
      hint: "conditional of volere + ordinare",
      tags: ["chunk", "restaurant", "ordering"],
      tier: 3,
    },
    {
      id: "a229-t3-002",
      type: "produce",
      prompt: "What do you recommend?",
      accepted: ["Cosa mi consiglia?", "Che cosa mi consiglia?"],
      hint: "formal 'lei' address to a waiter",
      tags: ["chunk", "restaurant", "ordering"],
      tier: 3,
    },
    {
      id: "a229-t3-003",
      type: "produce",
      prompt: "Can we get the bill when you have a moment?",
      accepted: ["Ci porta il conto quando ha un momento?", "Ci porta il conto quando può?"],
      hint: "present tense used as a soft request",
      tags: ["chunk", "restaurant", "payment"],
      tier: 3,
    },
    {
      id: "a229-t3-004",
      type: "produce",
      prompt: "Is the cover charge included in the price?",
      accepted: ["Il coperto è incluso nel prezzo?", "Il coperto è compreso nel prezzo?"],
      tags: ["chunk", "restaurant", "payment"],
      tier: 3,
    },
    {
      id: "a229-t3-005",
      type: "produce",
      prompt: "This dish bursts with flavor.",
      accepted: ["Questo piatto è pieno di sapore.", "Questo piatto è davvero saporito."],
      hint: "collocation with saporito / il sapore",
      tags: ["chunk", "food", "taste"],
      tier: 3,
    },
    {
      id: "a229-t3-006",
      type: "produce",
      prompt: "Let's go eat out tonight — I don't feel like cooking.",
      accepted: [
        "Usciamo a mangiare fuori stasera, non ho voglia di cucinare.",
        "Andiamo a mangiare fuori stasera, non ho voglia di cucinare.",
      ],
      tags: ["chunk", "restaurant", "invitation"],
      tier: 3,
    },
    {
      id: "a229-t3-007",
      type: "produce",
      prompt: "A table for two, away from the kitchen, please.",
      accepted: ["Un tavolo per due, lontano dalla cucina, per favore."],
      tags: ["chunk", "restaurant", "reservation"],
      tier: 3,
    },
    {
      id: "a229-t3-008",
      type: "produce",
      prompt: "Dinner's on me tonight.",
      accepted: ["Offro io la cena stasera.", "Pago io stasera."],
      hint: "collocation with offrire",
      tags: ["chunk", "restaurant", "payment", "social"],
      tier: 3,
    },
    {
      id: "a229-t3-009",
      type: "produce",
      prompt: "I'm starving — I haven't eaten since breakfast.",
      accepted: ["Ho una fame da lupi: non mangio dalla colazione.", "Sono affamato: non mangio dalla colazione."],
      hint: "idiom 'avere una fame da lupi' — to be ravenously hungry",
      tags: ["chunk", "food", "feeling", "idiom"],
      tier: 3,
    },
    {
      id: "a229-t3-010",
      type: "produce",
      prompt: "Could I get this wrapped up to take away?",
      accepted: ["Potrei portarlo via?", "Lo potrei portare via?"],
      hint: "conditional of potere + portare via",
      tags: ["chunk", "restaurant", "ordering"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a229-t4-001",
      type: "passage_cloze",
      prompt:
        "Ieri sera Elena ha deciso di festeggiare il compleanno del marito in un locale nuovo.\nHa chiamato il ristorante nel pomeriggio per chiedere un tavolo vicino alla finestra.\nIl cameriere le ha detto che senza ___ non c'era posto per otto persone.\nElena ha lasciato subito il suo numero e ha confermato l'orario.\nAlla fine la serata è stata perfetta, e il marito non si aspettava nulla.",
      accepted: ["prenotazione", "una prenotazione"],
      hint: "the word refers to booking a table in advance",
      tags: ["passage_cloze", "restaurant", "reservation"],
      tier: 4,
      prerequisites: ["a229-t1-003", "a229-t1-004", "a229-t1-005", "a229-t1-006", "a229-t1-007", "a229-t1-008"],
    },
    {
      id: "a229-t4-002",
      type: "passage_cloze",
      prompt:
        "Marco è entrato in trattoria con molta fame dopo una lunga giornata di lavoro.\nIl cameriere gli ha consigliato di iniziare con un antipasto misto di verdure.\nDopo, Marco ha ordinato il risotto ai funghi come primo.\nPer il ___, ha scelto una bistecca alla griglia con un contorno di patate.\nAlla fine ha lasciato una mancia generosa perché il servizio era stato eccellente.",
      accepted: ["secondo", "il secondo"],
      hint: "the word refers to the main course, after the primo",
      tags: ["passage_cloze", "restaurant", "menu"],
      tier: 4,
      prerequisites: ["a229-t1-031", "a229-t1-032", "a229-t1-033", "a229-t1-034", "a229-t1-035", "a229-t1-036"],
    },
    {
      id: "a229-t4-003",
      type: "passage_cloze",
      prompt:
        "Dopo la cena, Giulia e Paolo hanno chiesto il conto al cameriere.\nIl coperto era già incluso nel prezzo, quindi non hanno pagato extra per quello.\nPaolo ha calcolato quanto lasciare come ___ prima di alzarsi dal tavolo.\nIn Italia non è obbligatorio, ma un piccolo gesto è sempre apprezzato.\nGiulia ha lasciato qualche moneta sul tavolo e sono usciti soddisfatti.",
      accepted: ["mancia", "la mancia"],
      hint: "the word refers to the gratuity left for good service",
      tags: ["passage_cloze", "restaurant", "payment"],
      tier: 4,
      prerequisites: ["a229-t1-017", "a229-t1-018", "a229-t1-019", "a229-t1-020", "a229-t1-021", "a229-t1-022"],
    },
    {
      id: "a229-t4-004",
      type: "passage_cloze",
      prompt:
        "Ogni venerdì Sara si ferma in un bar vicino all'ufficio prima di tornare a casa.\nLì ordina un bicchiere di vino bianco e qualche spuntino gratuito.\nQuesto rito, molto comune in Italia, si chiama ___.\nDura di solito un'ora, tra le sei e le sette di sera.\nPer Sara è il modo migliore per lasciarsi alle spalle la giornata di lavoro.",
      accepted: ["aperitivo", "l'aperitivo"],
      hint: "the word names the pre-dinner drink-and-snack ritual",
      tags: ["passage_cloze", "food", "culture"],
      tier: 4,
      prerequisites: ["a229-t1-069", "a229-t1-070", "a229-t1-073", "a229-t1-074"],
    },
  ],
};
export default unit;
