import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-23-numbers-ii",
  name: "Numbers & Quantities",
  level: "A2",
  theme: "Fractions, Quantities & Approximation",
  emoji: "🔢",
  prerequisiteUnits: ["a2-unit-22-professions"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a223-t1-001",
      type: "recognize",
      prompt: "cento",
      accepted: ["one hundred", "a hundred", "hundred"],
      hint: "the round number before mille",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-002",
      type: "recognize",
      prompt: "mille",
      accepted: ["one thousand", "a thousand", "thousand"],
      hint: "plural: mila (due mila, tre mila)",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-003",
      type: "recognize",
      prompt: "un milione",
      accepted: ["one million", "a million", "million"],
      hint: "takes 'di' before a noun: un milione di euro",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-004",
      type: "recognize",
      prompt: "mezzo / mezza",
      accepted: ["half", "a half"],
      hint: "agrees with the noun: mezzo chilo, mezza bottiglia",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-005",
      type: "recognize",
      prompt: "un quarto",
      accepted: ["a quarter", "one quarter", "one fourth"],
      hint: "literally 'a fourth'",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-006",
      type: "recognize",
      prompt: "un terzo",
      accepted: ["a third", "one third"],
      hint: "un terzo della torta = a third of the cake",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-007",
      type: "recognize",
      prompt: "doppio / doppia",
      accepted: ["double", "twice", "twice as much"],
      hint: "il doppio = twice the amount",
      tags: ["multiplier", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-008",
      type: "recognize",
      prompt: "circa",
      accepted: ["about", "around", "approximately", "roughly"],
      hint: "placed before or after a number",
      tags: ["approximation", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-009",
      type: "recognize",
      prompt: "quasi",
      accepted: ["almost", "nearly"],
      hint: "quasi tutti = almost everyone",
      tags: ["approximation", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-010",
      type: "recognize",
      prompt: "un paio",
      accepted: ["a pair", "a couple", "a couple of"],
      hint: "un paio di giorni = a couple of days",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-011",
      type: "recognize",
      prompt: "una decina",
      accepted: ["about ten", "around ten", "a dozen or so", "ten or so"],
      hint: "una decina di persone ≈ about ten people",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-012",
      type: "recognize",
      prompt: "una dozzina",
      accepted: ["a dozen", "twelve"],
      hint: "una dozzina di uova = a dozen eggs",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-013",
      type: "recognize",
      prompt: "centinaia",
      accepted: ["hundreds"],
      hint: "plural of centinaio; centinaia di persone",
      tags: ["number", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-014",
      type: "recognize",
      prompt: "migliaia",
      accepted: ["thousands"],
      hint: "plural of migliaio; migliaia di turisti",
      tags: ["number", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-015",
      type: "recognize",
      prompt: "abbastanza",
      accepted: ["enough", "quite", "fairly", "rather"],
      hint: "abbastanza freddo = quite cold / cold enough",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-016",
      type: "recognize",
      prompt: "troppo",
      accepted: ["too much", "too many", "too"],
      hint: "troppo caldo = too hot; troppi soldi = too much money",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-017",
      type: "recognize",
      prompt: "appena",
      accepted: ["just", "barely", "hardly", "just enough"],
      hint: "ho appena mangiato = I just ate",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-018",
      type: "recognize",
      prompt: "soltanto",
      accepted: ["only", "just"],
      hint: "soltanto due = only two",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-019",
      type: "recognize",
      prompt: "ogni",
      accepted: ["every", "each"],
      hint: "ogni giorno = every day; invariable",
      tags: ["quantity-adverb", "determiner"],
      tier: 1,
    },
    {
      id: "a223-t1-020",
      type: "recognize",
      prompt: "nessuno",
      accepted: ["no one", "nobody", "none", "no"],
      hint: "nessuno studente = no student",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-021",
      type: "recognize",
      prompt: "qualcuno",
      accepted: ["someone", "somebody", "anyone", "some"],
      hint: "qualcuno ha chiamato = someone called",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-022",
      type: "recognize",
      prompt: "molti / molte",
      accepted: ["many", "a lot of", "lots of"],
      hint: "molti agrees with the noun in gender and number",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-023",
      type: "recognize",
      prompt: "pochi / poche",
      accepted: ["few", "a few", "not many", "little"],
      hint: "pochi amici = few friends",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-024",
      type: "recognize",
      prompt: "tutti / tutte",
      accepted: ["all", "everyone", "everybody", "all of them"],
      hint: "tutti i giorni = every day; tutti = everyone",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-025",
      type: "recognize",
      prompt: "niente",
      accepted: ["nothing", "anything"],
      hint: "non ho niente = I have nothing",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },

    // ── Tier 2 – Grammar & Fill-in-the-blank ─────────────────────────────────
    {
      id: "a223-t2-001",
      type: "fill_blank",
      prompt: "It costs about thirty euros. → Costa ___ trenta euro.",
      accepted: ["circa"],
      hint: "the Italian word for 'approximately'",
      tags: ["approximation", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-002",
      type: "fill_blank",
      prompt: "I need a dozen eggs. → Ho bisogno di ___ uova.",
      accepted: ["una dozzina di", "una dozzina"],
      hint: "the Italian quantity noun for 'twelve'",
      tags: ["quantity-noun", "partitive", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-003",
      type: "fill_blank",
      prompt: "Choose the correct partitive expression:\nVorrei ___ latte per favore. (some milk)\n(Options: del / di il / dei)",
      accepted: ["del"],
      hint: "latte is masculine singular → di + il = del",
      tags: ["partitive", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-004",
      type: "fill_blank",
      prompt: "Contrast these two:\n'___ degli studenti ha superato l'esame' (half) vs '___ degli studenti ha superato l'esame' (double the number).\nFill in the first blank.",
      accepted: ["La metà", "la metà"],
      hint: "la metà di = half of",
      tags: ["fraction", "grammar", "fill_blank"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "a223-t3-001",
      type: "produce",
      prompt: "About a hundred people were at the party.",
      accepted: [
        "C'erano circa cento persone alla festa.",
        "Alla festa c'erano circa cento persone.",
        "c'erano circa cento persone alla festa",
      ],
      hint: "use circa before the number",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-002",
      type: "produce",
      prompt: "Half of the students passed.",
      accepted: [
        "La metà degli studenti ha superato.",
        "La metà degli studenti ha superato l'esame.",
        "la metà degli studenti ha superato",
      ],
      hint: "la metà di + definite article + noun",
      tags: ["fraction", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-003",
      type: "produce",
      prompt: "I have very little time.",
      accepted: [
        "Ho pochissimo tempo.",
        "Ho molto poco tempo.",
        "ho pochissimo tempo",
        "ho molto poco tempo",
      ],
      hint: "pochi/poco + superlative suffix, or molto poco",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-004",
      type: "produce",
      prompt: "Almost everyone agreed.",
      accepted: [
        "Quasi tutti erano d'accordo.",
        "Quasi tutti erano d'accordo.",
        "quasi tutti erano d'accordo",
      ],
      hint: "quasi + tutti",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-005",
      type: "produce",
      prompt: "A dozen eggs, please.",
      accepted: [
        "Una dozzina di uova, per favore.",
        "Una dozzina di uova per favore.",
        "una dozzina di uova, per favore",
      ],
      hint: "quantity noun + di + noun",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a223-t4-001",
      type: "passage_cloze",
      prompt: "Al mercato stamattina ho comprato un chilo di pomodori e ___ mozzarella per la pizza.\nCostava tutto circa otto euro — meno di quanto mi aspettassi!\nHo preso anche una dozzina di uova e quasi un chilo di farina.\nCon questi ingredienti posso cucinare per almeno quattro persone.",
      accepted: ["mezza", "mezzo"],
      hint: "half a mozzarella — feminine noun, so ___",
      tags: ["passage_cloze", "fraction", "shopping"],
      tier: 4,
      prerequisites: ["a223-t1-004", "a223-t1-008", "a223-t1-012"],
    },
  ],
};
export default unit;
