import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-23-numbers-ii",
  name: "Numbers & Quantities",
  level: "A2",
  theme: "Fractions, Quantities & Approximation",
  emoji: "🔢",
  prerequisiteUnits: ["a2-unit-22-professions"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a223-t1-001",
      type: "recognize",
      prompt: "cento",
      accepted: ["one hundred", "a hundred", "hundred"],
      hint: "the round number before mille",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-002",
      type: "recognize",
      prompt: "mille",
      accepted: ["one thousand", "a thousand", "thousand"],
      hint: "plural: mila (due mila, tre mila)",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-003",
      type: "recognize",
      prompt: "un milione",
      accepted: ["one million", "a million", "million"],
      hint: "takes 'di' before a noun: un milione di euro",
      tags: ["number", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-004",
      type: "recognize",
      prompt: "mezzo / mezza",
      accepted: ["half", "a half"],
      hint: "agrees with the noun: mezzo chilo, mezza bottiglia",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-005",
      type: "recognize",
      prompt: "un quarto",
      accepted: ["a quarter", "one quarter", "one fourth"],
      hint: "literally 'a fourth'",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-006",
      type: "recognize",
      prompt: "un terzo",
      accepted: ["a third", "one third"],
      hint: "un terzo della torta = a third of the cake",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-007",
      type: "recognize",
      prompt: "doppio / doppia",
      accepted: ["double", "twice", "twice as much"],
      hint: "il doppio = twice the amount",
      tags: ["multiplier", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-008",
      type: "recognize",
      prompt: "circa",
      accepted: ["about", "around", "approximately", "roughly"],
      hint: "placed before or after a number",
      tags: ["approximation", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-009",
      type: "recognize",
      prompt: "quasi",
      accepted: ["almost", "nearly"],
      hint: "quasi tutti = almost everyone",
      tags: ["approximation", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-010",
      type: "recognize",
      prompt: "un paio",
      accepted: ["a pair", "a couple", "a couple of"],
      hint: "un paio di giorni = a couple of days",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-011",
      type: "recognize",
      prompt: "una decina",
      accepted: ["about ten", "around ten", "a dozen or so", "ten or so"],
      hint: "una decina di persone ≈ about ten people",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-012",
      type: "recognize",
      prompt: "una dozzina",
      accepted: ["a dozen", "twelve"],
      hint: "una dozzina di uova = a dozen eggs",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-013",
      type: "recognize",
      prompt: "centinaia",
      accepted: ["hundreds"],
      hint: "plural of centinaio; centinaia di persone",
      tags: ["number", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-014",
      type: "recognize",
      prompt: "migliaia",
      accepted: ["thousands"],
      hint: "plural of migliaio; migliaia di turisti",
      tags: ["number", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-015",
      type: "recognize",
      prompt: "abbastanza",
      accepted: ["enough", "quite", "fairly", "rather"],
      hint: "abbastanza freddo = quite cold / cold enough",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-016",
      type: "recognize",
      prompt: "troppo",
      accepted: ["too much", "too many", "too"],
      hint: "troppo caldo = too hot; troppi soldi = too much money",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-017",
      type: "recognize",
      prompt: "appena",
      accepted: ["just", "barely", "hardly", "just enough"],
      hint: "ho appena mangiato = I just ate",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-018",
      type: "recognize",
      prompt: "soltanto",
      accepted: ["only", "just"],
      hint: "soltanto due = only two",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-019",
      type: "recognize",
      prompt: "ogni",
      accepted: ["every", "each"],
      hint: "ogni giorno = every day; invariable",
      tags: ["quantity-adverb", "determiner"],
      tier: 1,
    },
    {
      id: "a223-t1-020",
      type: "recognize",
      prompt: "nessuno",
      accepted: ["no one", "nobody", "none", "no"],
      hint: "nessuno studente = no student",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-021",
      type: "recognize",
      prompt: "qualcuno",
      accepted: ["someone", "somebody", "anyone", "some"],
      hint: "qualcuno ha chiamato = someone called",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-022",
      type: "recognize",
      prompt: "molti / molte",
      accepted: ["many", "a lot of", "lots of"],
      hint: "molti agrees with the noun in gender and number",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-023",
      type: "recognize",
      prompt: "pochi / poche",
      accepted: ["few", "a few", "not many", "little"],
      hint: "pochi amici = few friends",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-024",
      type: "recognize",
      prompt: "tutti / tutte",
      accepted: ["all", "everyone", "everybody", "all of them"],
      hint: "tutti i giorni = every day; tutti = everyone",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-025",
      type: "recognize",
      prompt: "niente",
      accepted: ["nothing", "anything"],
      hint: "non ho niente = I have nothing",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },

    // ── Tier 2 – Grammar & Fill-in-the-blank ─────────────────────────────────
    {
      id: "a223-t2-001",
      type: "fill_blank",
      prompt: "It costs about thirty euros. → Costa ___ trenta euro.",
      accepted: ["circa"],
      hint: "the Italian word for 'approximately'",
      tags: ["approximation", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-002",
      type: "fill_blank",
      prompt: "I need a dozen eggs. → Ho bisogno di ___ uova.",
      accepted: ["una dozzina di", "una dozzina"],
      hint: "the Italian quantity noun for 'twelve'",
      tags: ["quantity-noun", "partitive", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-003",
      type: "fill_blank",
      prompt: "Choose the correct partitive expression:\nVorrei ___ latte per favore. (some milk)\n(Options: del / di il / dei)",
      accepted: ["del"],
      hint: "latte is masculine singular → di + il = del",
      tags: ["partitive", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-004",
      type: "fill_blank",
      prompt: "Contrast these two:\n'___ degli studenti ha superato l'esame' (half) vs '___ degli studenti ha superato l'esame' (double the number).\nFill in the first blank.",
      accepted: ["La metà", "la metà"],
      hint: "la metà di = half of",
      tags: ["fraction", "grammar", "fill_blank"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "a223-t3-001",
      type: "produce",
      prompt: "About a hundred people were at the party.",
      accepted: [
        "C'erano circa cento persone alla festa.",
        "Alla festa c'erano circa cento persone.",
        "c'erano circa cento persone alla festa",
      ],
      hint: "use circa before the number",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-002",
      type: "produce",
      prompt: "Half of the students passed.",
      accepted: [
        "La metà degli studenti ha superato.",
        "La metà degli studenti ha superato l'esame.",
        "la metà degli studenti ha superato",
      ],
      hint: "la metà di + definite article + noun",
      tags: ["fraction", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-003",
      type: "produce",
      prompt: "I have very little time.",
      accepted: [
        "Ho pochissimo tempo.",
        "Ho molto poco tempo.",
        "ho pochissimo tempo",
        "ho molto poco tempo",
      ],
      hint: "pochi/poco + superlative suffix, or molto poco",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-004",
      type: "produce",
      prompt: "Almost everyone agreed.",
      accepted: [
        "Quasi tutti erano d'accordo.",
        "Quasi tutti erano d'accordo.",
        "quasi tutti erano d'accordo",
      ],
      hint: "quasi + tutti",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-005",
      type: "produce",
      prompt: "A dozen eggs, please.",
      accepted: [
        "Una dozzina di uova, per favore.",
        "Una dozzina di uova per favore.",
        "una dozzina di uova, per favore",
      ],
      hint: "quantity noun + di + noun",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a223-t4-001",
      type: "passage_cloze",
      prompt: "Al mercato stamattina ho comprato un chilo di pomodori e ___ mozzarella per la pizza.\nCostava tutto circa otto euro — meno di quanto mi aspettassi!\nHo preso anche una dozzina di uova e quasi un chilo di farina.\nCon questi ingredienti posso cucinare per almeno quattro persone.",
      accepted: ["mezza", "mezzo"],
      hint: "half a mozzarella — feminine noun, so ___",
      tags: ["passage_cloze", "fraction", "shopping"],
      tier: 4,
      prerequisites: ["a223-t1-004", "a223-t1-008", "a223-t1-012"],
    },

    // ── Tier 1 – Vocabulary (expansion: ordinals, large numbers, fractions/percentages, quantity expressions) ──
    {
      id: "a223-t1-026",
      type: "recognize",
      prompt: "primo / prima",
      accepted: ["first"],
      hint: "used for dates: il primo maggio (the first of May)",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-027",
      type: "recognize",
      prompt: "secondo (ordinale)",
      accepted: ["second"],
      hint: "as an ordinal number, not 'according to'",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-028",
      type: "recognize",
      prompt: "quinto / quinta",
      accepted: ["fifth"],
      hint: "il quinto piano = the fifth floor",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-029",
      type: "recognize",
      prompt: "sesto / sesta",
      accepted: ["sixth"],
      hint: "ordinal after quinto",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-030",
      type: "recognize",
      prompt: "settimo / settima",
      accepted: ["seventh"],
      hint: "ordinal after sesto",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-031",
      type: "recognize",
      prompt: "ottavo / ottava",
      accepted: ["eighth"],
      hint: "ordinal after settimo",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-032",
      type: "recognize",
      prompt: "nono / nona",
      accepted: ["ninth"],
      hint: "ordinal after ottavo",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-033",
      type: "recognize",
      prompt: "decimo / decima",
      accepted: ["tenth"],
      hint: "ordinal after nono",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-034",
      type: "recognize",
      prompt: "ventesimo / ventesima",
      accepted: ["twentieth"],
      hint: "-esimo forms ordinals above decimo",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-035",
      type: "recognize",
      prompt: "trentesimo / trentesima",
      accepted: ["thirtieth"],
      hint: "il trentesimo anniversario = the thirtieth anniversary",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-036",
      type: "recognize",
      prompt: "centesimo / centesima",
      accepted: ["hundredth"],
      hint: "il centesimo cliente = the hundredth customer",
      tags: ["ordinal", "number"],
      tier: 1,
    },
    {
      id: "a223-t1-037",
      type: "recognize",
      prompt: "ultimo / ultima",
      accepted: ["last"],
      hint: "l'ultimo giorno = the last day",
      tags: ["ordinal", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-038",
      type: "recognize",
      prompt: "penultimo / penultima",
      accepted: ["second-to-last", "second to last", "next-to-last", "penultimate"],
      hint: "one before ultimo",
      tags: ["ordinal", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-039",
      type: "recognize",
      prompt: "duecento",
      accepted: ["two hundred"],
      hint: "cento compounds without a space: duecento, trecento",
      tags: ["number", "large-number"],
      tier: 1,
    },
    {
      id: "a223-t1-040",
      type: "recognize",
      prompt: "cinquecento",
      accepted: ["five hundred"],
      hint: "cinque + cento",
      tags: ["number", "large-number"],
      tier: 1,
    },
    {
      id: "a223-t1-041",
      type: "recognize",
      prompt: "diecimila",
      accepted: ["ten thousand"],
      hint: "dieci + mila (mille becomes -mila after a number)",
      tags: ["number", "large-number"],
      tier: 1,
    },
    {
      id: "a223-t1-042",
      type: "recognize",
      prompt: "centomila",
      accepted: ["one hundred thousand", "a hundred thousand", "hundred thousand"],
      hint: "cento + mila",
      tags: ["number", "large-number"],
      tier: 1,
    },
    {
      id: "a223-t1-043",
      type: "recognize",
      prompt: "un miliardo",
      accepted: ["a billion", "one billion", "billion"],
      hint: "takes 'di' before a noun: un miliardo di euro",
      tags: ["number", "large-number"],
      tier: 1,
    },
    {
      id: "a223-t1-044",
      type: "recognize",
      prompt: "parecchi / parecchie",
      accepted: ["quite a few", "several", "quite a lot of"],
      hint: "stronger than 'alcuni', weaker than 'molti'",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-045",
      type: "recognize",
      prompt: "svariati / svariate",
      accepted: ["various", "several", "numerous"],
      hint: "svariati motivi = various reasons",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-046",
      type: "recognize",
      prompt: "per cento",
      accepted: ["percent", "per cent"],
      hint: "il cinquanta per cento = fifty percent",
      tags: ["fraction", "percentage"],
      tier: 1,
    },
    {
      id: "a223-t1-047",
      type: "recognize",
      prompt: "la percentuale",
      accepted: ["the percentage"],
      hint: "una piccola percentuale = a small percentage",
      tags: ["fraction", "percentage"],
      tier: 1,
    },
    {
      id: "a223-t1-048",
      type: "recognize",
      prompt: "tre quarti",
      accepted: ["three quarters", "three fourths"],
      hint: "quarti is the plural of quarto",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-049",
      type: "recognize",
      prompt: "due terzi",
      accepted: ["two thirds"],
      hint: "terzi is the plural of terzo",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-050",
      type: "recognize",
      prompt: "un quinto",
      accepted: ["a fifth", "one fifth"],
      hint: "un quinto della popolazione = a fifth of the population",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-051",
      type: "recognize",
      prompt: "un decimo",
      accepted: ["a tenth", "one tenth"],
      hint: "un decimo del totale = a tenth of the total",
      tags: ["fraction", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-052",
      type: "recognize",
      prompt: "dimezzare",
      accepted: ["to halve", "to cut in half"],
      hint: "from mezzo (half)",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-053",
      type: "recognize",
      prompt: "raddoppiare",
      accepted: ["to double"],
      hint: "from doppio (double)",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-054",
      type: "recognize",
      prompt: "la totalità",
      accepted: ["the totality", "all of it", "the entirety"],
      hint: "la totalità dei presenti = all of those present",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-055",
      type: "recognize",
      prompt: "la maggioranza",
      accepted: ["the majority"],
      hint: "la maggioranza vota = the majority votes",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-056",
      type: "recognize",
      prompt: "la maggior parte",
      accepted: ["most", "the majority of", "most of"],
      hint: "la maggior parte di + plural noun, singular verb",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-057",
      type: "recognize",
      prompt: "un sacco di",
      accepted: ["a ton of", "loads of", "a lot of"],
      hint: "colloquial: un sacco di gente = loads of people",
      tags: ["quantity-adverb", "colloquial"],
      tier: 1,
    },
    {
      id: "a223-t1-058",
      type: "recognize",
      prompt: "tantissimo / tantissimi",
      accepted: ["a great deal", "so much", "so many"],
      hint: "superlative of tanto",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-059",
      type: "recognize",
      prompt: "pochissimo / pochissimi",
      accepted: ["very little", "very few"],
      hint: "superlative of poco",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-060",
      type: "recognize",
      prompt: "il resto",
      accepted: ["the rest", "the remainder"],
      hint: "spiegherò il resto = I'll explain the rest",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-061",
      type: "recognize",
      prompt: "in tutto",
      accepted: ["in total", "altogether", "all in all"],
      hint: "in tutto costa cento euro = in total it costs a hundred euros",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-062",
      type: "recognize",
      prompt: "al massimo",
      accepted: ["at most"],
      hint: "opposite of almeno",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-063",
      type: "recognize",
      prompt: "almeno",
      accepted: ["at least"],
      hint: "opposite of al massimo",
      tags: ["quantity-adverb", "adverb"],
      tier: 1,
    },
    {
      id: "a223-t1-064",
      type: "recognize",
      prompt: "la minoranza",
      accepted: ["the minority"],
      hint: "opposite of la maggioranza",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-065",
      type: "recognize",
      prompt: "numeroso / numerosa",
      accepted: ["numerous", "large"],
      hint: "una famiglia numerosa = a large family",
      tags: ["quantity-adverb", "adjective"],
      tier: 1,
    },
    {
      id: "a223-t1-066",
      type: "recognize",
      prompt: "entrambi / entrambe",
      accepted: ["both"],
      hint: "entrambi i fratelli = both brothers",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-067",
      type: "recognize",
      prompt: "ciascuno / ciascuna",
      accepted: ["each one", "each"],
      hint: "more formal than ogni; can stand alone",
      tags: ["quantity-adverb", "pronoun"],
      tier: 1,
    },
    {
      id: "a223-t1-068",
      type: "recognize",
      prompt: "l'insieme",
      accepted: ["the whole", "the set", "the collective", "as a whole"],
      hint: "nell'insieme = as a whole",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-069",
      type: "recognize",
      prompt: "una manciata (di)",
      accepted: ["a handful (of)", "a handful"],
      hint: "una manciata di persone = a handful of people",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-070",
      type: "recognize",
      prompt: "una miriade (di)",
      accepted: ["a myriad (of)", "a myriad", "countless"],
      hint: "una miriade di opzioni = a myriad of options",
      tags: ["approximation", "quantity-noun"],
      tier: 1,
    },
    {
      id: "a223-t1-071",
      type: "recognize",
      prompt: "suddividere",
      accepted: ["to divide up", "to split up", "to divide"],
      hint: "suddividere in parti = to divide into parts",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-072",
      type: "recognize",
      prompt: "moltiplicare",
      accepted: ["to multiply"],
      hint: "moltiplicare per due = to multiply by two",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-073",
      type: "recognize",
      prompt: "il triplo",
      accepted: ["triple", "three times as much", "three times the amount"],
      hint: "next multiplier after il doppio",
      tags: ["multiplier", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-074",
      type: "recognize",
      prompt: "superare",
      accepted: ["to exceed", "to surpass", "to go over"],
      hint: "superare un milione = to exceed a million",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-075",
      type: "recognize",
      prompt: "arrotondare",
      accepted: ["to round", "to round off", "to round a number"],
      hint: "arrotondare per eccesso/difetto = to round up/down",
      tags: ["quantity-verb", "verb"],
      tier: 1,
    },
    {
      id: "a223-t1-076",
      type: "recognize",
      prompt: "l'ammontare",
      accepted: ["the total amount", "the sum", "the amount"],
      hint: "l'ammontare del debito = the total amount of the debt",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-077",
      type: "recognize",
      prompt: "la quantità",
      accepted: ["the quantity", "the amount"],
      hint: "una grande quantità di = a large quantity of",
      tags: ["quantity-noun", "quantity"],
      tier: 1,
    },
    {
      id: "a223-t1-078",
      type: "recognize",
      prompt: "approssimativamente",
      accepted: ["approximately"],
      hint: "more formal register than circa",
      tags: ["approximation", "adverb"],
      tier: 1,
    },

    // ── Tier 2 – Grammar & Fill-in-the-blank (expansion) ─────────────────────
    {
      id: "a223-t2-005",
      type: "fill_blank",
      prompt: "The first of May is a national holiday. → ___ maggio è una festa nazionale.",
      accepted: ["Il primo", "il primo"],
      hint: "dates use the ordinal only for the first day of the month",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-006",
      type: "fill_blank",
      prompt: "On the second of June we celebrate the Republic. → Il ___ giugno festeggiamo la Repubblica. (use the number, not the ordinal)",
      accepted: ["due"],
      hint: "after the first, Italian dates use cardinal numbers",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-007",
      type: "fill_blank",
      prompt: "It's the third door on the left. → È la ___ porta a sinistra.",
      accepted: ["terza"],
      hint: "ordinal adjectives agree in gender and number with the noun",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-008",
      type: "fill_blank",
      prompt: "This is the last chapter of the book. → Questo è ___ capitolo del libro.",
      accepted: ["l'ultimo"],
      hint: "ultimo elides the article because it starts with a vowel",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-009",
      type: "fill_blank",
      prompt: "I ate two thirds of the pizza. → Ho mangiato ___ della pizza.",
      accepted: ["due terzi"],
      hint: "the plural of un terzo",
      tags: ["fraction", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-010",
      type: "fill_blank",
      prompt: "Fifty percent of Italians go on vacation in August. → Il cinquanta ___ degli italiani va in vacanza ad agosto.",
      accepted: ["per cento"],
      hint: "the fixed expression for 'percent'",
      tags: ["fraction", "percentage", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-011",
      type: "fill_blank",
      prompt: "The majority of students study English. → ___ degli studenti studia inglese.",
      accepted: ["La maggior parte", "la maggior parte"],
      hint: "this expression takes a singular verb even though the noun after 'di' is plural",
      tags: ["quantity-noun", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-012",
      type: "fill_blank",
      prompt: "Each employee receives a bonus. → ___ impiegato riceve un bonus.",
      accepted: ["Ogni", "ogni"],
      hint: "invariable, always followed by a singular noun",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-013",
      type: "fill_blank",
      prompt: "Each of the students brought a book. → ___ degli studenti ha portato un libro.",
      accepted: ["Ciascuno", "ciascuno"],
      hint: "can stand alone before 'di', unlike ogni",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-014",
      type: "fill_blank",
      prompt: "Both brothers work in Milan. → ___ i fratelli lavorano a Milano.",
      accepted: ["Entrambi", "entrambi"],
      hint: "agrees in gender: entrambi / entrambe",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-015",
      type: "fill_blank",
      prompt: "There are more than a hundred people here. → Ci sono più di ___ persone qui.",
      accepted: ["cento"],
      hint: "più di + number",
      tags: ["number", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-016",
      type: "fill_blank",
      prompt: "We need at least ten volunteers. → Abbiamo bisogno di ___ dieci volontari.",
      accepted: ["almeno"],
      hint: "opposite of al massimo",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-017",
      type: "fill_blank",
      prompt: "You can bring at most two guests. → Puoi portare ___ due ospiti.",
      accepted: ["al massimo"],
      hint: "opposite of almeno",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-018",
      type: "fill_blank",
      prompt: "Prices doubled in ten years. → I prezzi ___ in dieci anni.",
      accepted: ["sono raddoppiati"],
      hint: "raddoppiare used intransitively takes essere",
      tags: ["quantity-verb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-019",
      type: "fill_blank",
      prompt: "The company halved production costs. → L'azienda ___ i costi di produzione.",
      accepted: ["ha dimezzato"],
      hint: "dimezzare used transitively takes avere",
      tags: ["quantity-verb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-020",
      type: "fill_blank",
      prompt: "The population exceeded one million. → La popolazione ___ un milione di abitanti.",
      accepted: ["ha superato"],
      hint: "superare takes avere",
      tags: ["quantity-verb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-021",
      type: "fill_blank",
      prompt: "Round the number to the nearest ten. → ___ il numero alla decina più vicina.",
      accepted: ["Arrotonda", "arrotonda"],
      hint: "tu-form imperative of arrotondare",
      tags: ["quantity-verb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-022",
      type: "fill_blank",
      prompt: "We divided the work among four people. → Abbiamo ___ il lavoro tra quattro persone.",
      accepted: ["suddiviso"],
      hint: "past participle of suddividere",
      tags: ["quantity-verb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-023",
      type: "fill_blank",
      prompt: "Only a handful of people showed up. → Si è presentata solo ___ persone.",
      accepted: ["una manciata di", "una manciata"],
      hint: "approximation noun + di",
      tags: ["approximation", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-024",
      type: "fill_blank",
      prompt: "There's a myriad of possibilities. → C'è ___ di possibilità.",
      accepted: ["una miriade"],
      hint: "approximation noun for an enormous, uncountable number",
      tags: ["approximation", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-025",
      type: "fill_blank",
      prompt: "I have quite a few friends in Rome. → Ho ___ amici a Roma.",
      accepted: ["parecchi"],
      hint: "agrees in gender and number: parecchi / parecchie",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-026",
      type: "fill_blank",
      prompt: "The store sells various types of cheese. → Il negozio vende ___ tipi di formaggio.",
      accepted: ["svariati"],
      hint: "agrees with the plural masculine noun 'tipi'",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-027",
      type: "fill_blank",
      prompt: "He ate very little and then felt sick. → Ha mangiato ___ e poi si è sentito male.",
      accepted: ["pochissimo"],
      hint: "superlative of poco",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-028",
      type: "fill_blank",
      prompt: "I'll explain the rest tomorrow. → Spiegherò ___ domani.",
      accepted: ["il resto"],
      hint: "the leftover part of something",
      tags: ["quantity-noun", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-029",
      type: "fill_blank",
      prompt: "In total, we spent two hundred euros. → ___ abbiamo speso duecento euro.",
      accepted: ["In tutto", "in tutto"],
      hint: "sentence-initial adverbial expression",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-030",
      type: "fill_blank",
      prompt: "This is the hotel's hundredth anniversary. → Questo è il ___ anniversario dell'hotel.",
      accepted: ["centesimo"],
      hint: "ordinal for cento",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-031",
      type: "fill_blank",
      prompt: "This is the second-to-last stop. → Questa è ___ fermata.",
      accepted: ["la penultima"],
      hint: "fermata is feminine, so the ordinal agrees",
      tags: ["ordinal", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-032",
      type: "fill_blank",
      prompt: "The total amount of the invoice is unclear. → ___ della fattura non è chiaro.",
      accepted: ["L'ammontare", "l'ammontare"],
      hint: "masculine noun meaning 'the total sum'",
      tags: ["quantity-noun", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-033",
      type: "fill_blank",
      prompt: "Approximately eighty guests are expected. → Sono attesi ___ ottanta ospiti.",
      accepted: ["approssimativamente"],
      hint: "a more formal synonym of circa",
      tags: ["approximation", "grammar", "fill_blank"],
      tier: 2,
    },
    {
      id: "a223-t2-034",
      type: "fill_blank",
      prompt: "A large family gathered for the holidays. → Una famiglia ___ si è riunita per le feste.",
      accepted: ["numerosa"],
      hint: "agrees with the feminine noun 'famiglia'",
      tags: ["quantity-adverb", "grammar", "fill_blank"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases (expansion) ────────────────────────────────
    {
      id: "a223-t3-006",
      type: "produce",
      prompt: "In the first place, we need a plan.",
      accepted: [
        "In primo luogo, abbiamo bisogno di un piano.",
        "in primo luogo, abbiamo bisogno di un piano",
      ],
      hint: "in primo luogo = in the first place",
      tags: ["ordinal", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-007",
      type: "produce",
      prompt: "At the last moment, she changed her mind.",
      accepted: [
        "All'ultimo momento, ha cambiato idea.",
        "all'ultimo momento, ha cambiato idea",
      ],
      hint: "all'ultimo momento = at the last moment",
      tags: ["ordinal", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-008",
      type: "produce",
      prompt: "Prices increased by ten percent.",
      accepted: [
        "I prezzi sono aumentati del dieci per cento.",
        "i prezzi sono aumentati del dieci per cento",
      ],
      hint: "aumentare del + percentage",
      tags: ["percentage", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-009",
      type: "produce",
      prompt: "Most of the time, he works from home.",
      accepted: [
        "La maggior parte del tempo lavora da casa.",
        "la maggior parte del tempo lavora da casa",
      ],
      hint: "la maggior parte del tempo = most of the time",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-010",
      type: "produce",
      prompt: "There's loads of food at the party.",
      accepted: [
        "C'è un sacco di cibo alla festa.",
        "c'è un sacco di cibo alla festa",
      ],
      hint: "un sacco di = loads of (colloquial)",
      tags: ["quantity-adverb", "chunk", "colloquial"],
      tier: 3,
    },
    {
      id: "a223-t3-011",
      type: "produce",
      prompt: "At most, it will take an hour.",
      accepted: ["Al massimo ci vorrà un'ora.", "al massimo ci vorrà un'ora"],
      hint: "al massimo + verb",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-012",
      type: "produce",
      prompt: "We need at least three witnesses.",
      accepted: [
        "Abbiamo bisogno di almeno tre testimoni.",
        "abbiamo bisogno di almeno tre testimoni",
      ],
      hint: "almeno + number",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-013",
      type: "produce",
      prompt: "Both companies signed the contract.",
      accepted: [
        "Entrambe le aziende hanno firmato il contratto.",
        "entrambe le aziende hanno firmato il contratto",
      ],
      hint: "entrambe agrees with the feminine plural noun",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-014",
      type: "produce",
      prompt: "Each guest received a gift.",
      accepted: [
        "Ciascun ospite ha ricevuto un regalo.",
        "ciascun ospite ha ricevuto un regalo",
      ],
      hint: "ciascuno drops the final vowel before most masculine nouns: ciascun",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-015",
      type: "produce",
      prompt: "Only a handful of tourists visited in winter.",
      accepted: [
        "Solo una manciata di turisti ha visitato in inverno.",
        "solo una manciata di turisti ha visitato in inverno",
      ],
      hint: "una manciata di + plural noun",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-016",
      type: "produce",
      prompt: "There's a myriad of options on the menu.",
      accepted: [
        "C'è una miriade di opzioni nel menu.",
        "c'è una miriade di opzioni nel menu",
      ],
      hint: "una miriade di + plural noun",
      tags: ["approximation", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-017",
      type: "produce",
      prompt: "The team doubled its efforts before the deadline.",
      accepted: [
        "La squadra ha raddoppiato gli sforzi prima della scadenza.",
        "la squadra ha raddoppiato gli sforzi prima della scadenza",
      ],
      hint: "raddoppiare gli sforzi = to double one's efforts",
      tags: ["quantity-verb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-018",
      type: "produce",
      prompt: "The store halved its prices for the sale.",
      accepted: [
        "Il negozio ha dimezzato i prezzi per i saldi.",
        "il negozio ha dimezzato i prezzi per i saldi",
      ],
      hint: "dimezzare i prezzi = to halve the prices",
      tags: ["quantity-verb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-019",
      type: "produce",
      prompt: "Her performance exceeded all expectations.",
      accepted: [
        "La sua prestazione ha superato tutte le aspettative.",
        "la sua prestazione ha superato tutte le aspettative",
      ],
      hint: "superare le aspettative = to exceed expectations",
      tags: ["quantity-verb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-020",
      type: "produce",
      prompt: "Round the total up, please.",
      accepted: [
        "Arrotonda il totale per eccesso, per favore.",
        "arrotonda il totale per eccesso, per favore",
      ],
      hint: "arrotondare per eccesso = to round up",
      tags: ["quantity-verb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-021",
      type: "produce",
      prompt: "Multiply the ingredients by three for a bigger cake.",
      accepted: [
        "Moltiplica gli ingredienti per tre per una torta più grande.",
        "moltiplica gli ingredienti per tre per una torta più grande",
      ],
      hint: "moltiplicare per + number",
      tags: ["quantity-verb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-022",
      type: "produce",
      prompt: "He earns an enormous amount of money.",
      accepted: ["Guadagna tantissimi soldi.", "guadagna tantissimi soldi"],
      hint: "tantissimi agrees with the plural noun soldi",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-023",
      type: "produce",
      prompt: "I'll deal with the rest later.",
      accepted: [
        "Mi occuperò del resto più tardi.",
        "mi occuperò del resto più tardi",
      ],
      hint: "occuparsi di + il resto = del resto",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-024",
      type: "produce",
      prompt: "In total, twenty people signed up.",
      accepted: [
        "In tutto si sono iscritte venti persone.",
        "in tutto si sono iscritte venti persone",
      ],
      hint: "in tutto at the start of the sentence",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-025",
      type: "produce",
      prompt: "This is the second-to-last exercise.",
      accepted: [
        "Questo è il penultimo esercizio.",
        "questo è il penultimo esercizio",
      ],
      hint: "penultimo agrees with the masculine noun esercizio",
      tags: ["ordinal", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-026",
      type: "produce",
      prompt: "The total amount of the debt worries the family.",
      accepted: [
        "L'ammontare del debito preoccupa la famiglia.",
        "l'ammontare del debito preoccupa la famiglia",
      ],
      hint: "l'ammontare di + noun",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-027",
      type: "produce",
      prompt: "There's a large quantity of unsold stock.",
      accepted: [
        "C'è una grande quantità di merce invenduta.",
        "c'è una grande quantità di merce invenduta",
      ],
      hint: "una grande quantità di = a large quantity of",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-028",
      type: "produce",
      prompt: "The museum houses various collections from the region.",
      accepted: [
        "Il museo ospita svariate collezioni della regione.",
        "il museo ospita svariate collezioni della regione",
      ],
      hint: "svariate agrees with the feminine plural noun collezioni",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-029",
      type: "produce",
      prompt: "I have quite a few doubts about this plan.",
      accepted: [
        "Ho parecchi dubbi su questo piano.",
        "ho parecchi dubbi su questo piano",
      ],
      hint: "parecchi agrees with the masculine plural noun dubbi",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-030",
      type: "produce",
      prompt: "A large family needs a bigger house.",
      accepted: [
        "Una famiglia numerosa ha bisogno di una casa più grande.",
        "una famiglia numerosa ha bisogno di una casa più grande",
      ],
      hint: "famiglia numerosa = large family",
      tags: ["quantity-adverb", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-031",
      type: "produce",
      prompt: "Three quarters of the class passed the test.",
      accepted: [
        "Tre quarti della classe hanno superato il test.",
        "tre quarti della classe hanno superato il test",
      ],
      hint: "tre quarti di + noun, plural verb agreement",
      tags: ["fraction", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-032",
      type: "produce",
      prompt: "Two thirds of the population lives in cities.",
      accepted: [
        "Due terzi della popolazione vive in città.",
        "due terzi della popolazione vive in città",
      ],
      hint: "due terzi di + singular collective noun, singular verb",
      tags: ["fraction", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-033",
      type: "produce",
      prompt: "Only a fifth of the applicants were selected.",
      accepted: [
        "Solo un quinto dei candidati è stato selezionato.",
        "solo un quinto dei candidati è stato selezionato",
      ],
      hint: "un quinto dei + plural noun",
      tags: ["fraction", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-034",
      type: "produce",
      prompt: "The totality of the evidence points to one conclusion.",
      accepted: [
        "La totalità delle prove punta a una conclusione.",
        "la totalità delle prove punta a una conclusione",
      ],
      hint: "la totalità di + noun",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },
    {
      id: "a223-t3-035",
      type: "produce",
      prompt: "The minority voted against the proposal.",
      accepted: [
        "La minoranza ha votato contro la proposta.",
        "la minoranza ha votato contro la proposta",
      ],
      hint: "opposite of la maggioranza",
      tags: ["quantity-noun", "chunk"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze (expansion) ───────────────────────────────────
    {
      id: "a223-t4-002",
      type: "passage_cloze",
      prompt: "Il negozio ha dimezzato tutti i prezzi per i saldi di gennaio.\nHo comprato un paio di scarpe e una maglietta, spendendo in tutto solo trenta euro.\nC'erano circa duecento persone in fila fin dalle sette del mattino.\nAlla fine ho trovato anche un maglione a un ___ del prezzo originale.",
      accepted: ["quarto"],
      hint: "un quarto del prezzo = a quarter of the price",
      tags: ["passage_cloze", "fraction", "shopping"],
      tier: 4,
      prerequisites: ["a223-t1-005", "a223-t1-039", "a223-t1-052", "a223-t1-061"],
    },
    {
      id: "a223-t4-003",
      type: "passage_cloze",
      prompt: "Alla maratona di domenica si sono presentati più di diecimila corridori.\nLa maggior parte ___ arrivata al traguardo entro le quattro ore.\nSolo una manciata di atleti ha superato il record precedente.\nGli organizzatori pensano che l'anno prossimo i partecipanti raddoppieranno.",
      accepted: ["è"],
      hint: "la maggior parte takes a singular verb",
      tags: ["passage_cloze", "grammar", "quantity-noun"],
      tier: 4,
      prerequisites: ["a223-t1-041", "a223-t1-056", "a223-t1-069"],
    },
    {
      id: "a223-t4-004",
      type: "passage_cloze",
      prompt: "Secondo l'ultimo censimento, la popolazione della città ha superato il milione di abitanti.\nCirca un ___ dei residenti ha meno di trent'anni.\nLa percentuale di studenti universitari è aumentata del quindici per cento in dieci anni.\nGli esperti prevedono che la città continuerà a crescere.",
      accepted: ["quinto"],
      hint: "un quinto dei residenti = a fifth of the residents",
      tags: ["passage_cloze", "fraction", "statistics"],
      tier: 4,
      prerequisites: ["a223-t1-050", "a223-t1-074", "a223-t1-047"],
    },
    {
      id: "a223-t4-005",
      type: "passage_cloze",
      prompt: "Per preparare la torta per otto persone invece di quattro, devi ___ tutti gli ingredienti.\nUsa duecento grammi di farina invece di cento, e raddoppia anche lo zucchero.\nRicordati di arrotondare le quantità se la bilancia non è precisa.\nIl risultato sarà una torta enorme, perfetta per una festa numerosa.",
      accepted: ["moltiplicare"],
      hint: "infinitive after devi",
      tags: ["passage_cloze", "quantity-verb", "cooking"],
      tier: 4,
      prerequisites: ["a223-t1-072", "a223-t1-053", "a223-t1-075"],
    },
    {
      id: "a223-t4-006",
      type: "passage_cloze",
      prompt: "Le vendite dell'azienda sono aumentate del trenta per cento rispetto all'anno scorso.\nEntrambe le sedi, quella di Milano e quella di Torino, hanno superato gli obiettivi previsti.\nLa direzione ha deciso di ___ il budget per il marketing il prossimo trimestre.\nCon svariati nuovi clienti in arrivo, il futuro sembra promettente.",
      accepted: ["raddoppiare"],
      hint: "infinitive after 'di'",
      tags: ["passage_cloze", "quantity-verb", "business"],
      tier: 4,
      prerequisites: ["a223-t1-066", "a223-t1-053", "a223-t1-045"],
    },
    {
      id: "a223-t4-007",
      type: "passage_cloze",
      prompt: "Su cento studenti che hanno fatto l'esame, solo il venti ___ ha ottenuto il massimo dei voti.\nLa maggioranza ha comunque superato la prova senza problemi.\nCiascuno studente riceverà i risultati entro venerdì.\nQuest'anno il numero di promossi è quasi il doppio rispetto al passato.",
      accepted: ["per cento"],
      hint: "the fixed expression for 'percent'",
      tags: ["passage_cloze", "percentage", "education"],
      tier: 4,
      prerequisites: ["a223-t1-046", "a223-t1-055", "a223-t1-067"],
    },
    {
      id: "a223-t4-008",
      type: "passage_cloze",
      prompt: "Il costo totale della ristrutturazione ammonta a circa centomila euro.\nL'ammontare include materiali, manodopera e un margine per gli imprevisti.\nAbbiamo suddiviso il pagamento in quattro rate uguali.\nSe tutto va bene, i lavori dureranno soltanto ___ mesi.",
      accepted: ["un paio di", "un paio"],
      hint: "an approximate small number — reuse the expression for 'a couple of'",
      tags: ["passage_cloze", "approximation", "renovation"],
      tier: 4,
      prerequisites: ["a223-t1-042", "a223-t1-076", "a223-t1-071"],
    },
    {
      id: "a223-t4-009",
      type: "passage_cloze",
      prompt: "Il museo accoglie ogni anno migliaia di visitatori da tutto il mondo.\nQuest'anno, però, il numero è cresciuto: quasi due ___ di turisti hanno visitato le nuove sale.\nLa totalità delle opere esposte proviene da collezioni private.\nGli organizzatori sperano di superare questo risultato l'anno prossimo.",
      accepted: ["milioni"],
      hint: "plural of milione",
      tags: ["passage_cloze", "number", "museum"],
      tier: 4,
      prerequisites: ["a223-t1-003", "a223-t1-054", "a223-t1-074"],
    },
    {
      id: "a223-t4-010",
      type: "passage_cloze",
      prompt: "Per il compleanno della nonna si sono riuniti quasi tutti i parenti: una famiglia davvero ___.\nErano presenti entrambi gli zii, i cugini e persino qualche vicino di casa.\nIn tutto, a tavola c'erano una trentina di persone.\nÈ stata la festa più grande degli ultimi dieci anni.",
      accepted: ["numerosa"],
      hint: "agrees with the feminine noun famiglia",
      tags: ["passage_cloze", "family", "quantity-adverb"],
      tier: 4,
      prerequisites: ["a223-t1-065", "a223-t1-066", "a223-t1-061"],
    },
  ],
};
export default unit;
