import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-34-relationships-social-life",
  name: "Relationships & Social Life",
  level: "A2",
  theme: "Dating, Friendship & Social Occasions",
  emoji: "🤝",
  prerequisiteUnits: ["a2-unit-33-media-entertainment"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "a234-t1-001", type: "recognize", prompt: "il fidanzato / la fidanzata", accepted: ["boyfriend / girlfriend", "fiancé / fiancée"], hint: "same word covers a steady partner or an engaged one", tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-002", type: "produce", prompt: "boyfriend / girlfriend", accepted: ["il fidanzato / la fidanzata"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-003", type: "recognize", prompt: "fidanzarsi", accepted: ["to get engaged"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-004", type: "produce", prompt: "to get engaged", accepted: ["fidanzarsi"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-005", type: "recognize", prompt: "essere fidanzato/a", accepted: ["to be engaged", "to be in a steady relationship"], hint: "in everyday speech it often just means 'to have a boyfriend/girlfriend'", tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-006", type: "produce", prompt: "to be engaged (to someone)", accepted: ["essere fidanzato/a"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-007", type: "recognize", prompt: "uscire insieme", accepted: ["to go out together", "to date"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-008", type: "produce", prompt: "to go out together", accepted: ["uscire insieme"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-009", type: "recognize", prompt: "il primo appuntamento", accepted: ["the first date"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-010", type: "produce", prompt: "the first date", accepted: ["il primo appuntamento"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-011", type: "recognize", prompt: "conoscersi", accepted: ["to meet each other", "to get to know each other"], tags: ["social", "dating", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-012", type: "produce", prompt: "to get to know each other", accepted: ["conoscersi"], tags: ["social", "dating", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-013", type: "recognize", prompt: "frequentarsi", accepted: ["to see each other regularly", "to date each other"], tags: ["social", "dating", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-014", type: "produce", prompt: "to date each other", accepted: ["frequentarsi"], tags: ["social", "dating", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-015", type: "recognize", prompt: "stare insieme", accepted: ["to be together", "to be a couple"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-016", type: "produce", prompt: "to be together (as a couple)", accepted: ["stare insieme"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-017", type: "recognize", prompt: "mettersi insieme", accepted: ["to get together", "to start dating"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-018", type: "produce", prompt: "to start dating (each other)", accepted: ["mettersi insieme"], tags: ["social", "dating", "verb-phrase"], tier: 1 },
    { id: "a234-t1-019", type: "recognize", prompt: "innamorarsi", accepted: ["to fall in love"], tags: ["social", "dating", "verb", "emotion"], tier: 1 },
    { id: "a234-t1-020", type: "produce", prompt: "to fall in love (with someone)", accepted: ["innamorarsi (di qualcuno)", "innamorarsi"], tags: ["social", "dating", "verb", "emotion"], tier: 1 },
    { id: "a234-t1-021", type: "recognize", prompt: "essere innamorato/a (di)", accepted: ["to be in love","to be in love (with)"], tags: ["social", "dating", "verb-phrase", "emotion"], tier: 1 },
    { id: "a234-t1-022", type: "produce", prompt: "to be in love (with someone)", accepted: ["essere innamorato/a (di qualcuno)", "essere innamorato/a"], tags: ["social", "dating", "verb-phrase", "emotion"], tier: 1 },
    { id: "a234-t1-023", type: "recognize", prompt: "avere una cotta (per)", accepted: ["to have a crush","to have a crush (on someone)"], tags: ["social", "dating", "idiom", "emotion"], tier: 1 },
    { id: "a234-t1-024", type: "produce", prompt: "to have a crush (on someone)", accepted: ["avere una cotta (per qualcuno)", "avere una cotta"], tags: ["social", "dating", "idiom", "emotion"], tier: 1 },
    { id: "a234-t1-025", type: "recognize", prompt: "flirtare", accepted: ["to flirt"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-026", type: "produce", prompt: "to flirt", accepted: ["flirtare"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-027", type: "recognize", prompt: "il primo bacio", accepted: ["the first kiss"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-028", type: "produce", prompt: "the first kiss", accepted: ["il primo bacio"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-029", type: "recognize", prompt: "baciare", accepted: ["to kiss"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-030", type: "produce", prompt: "to kiss", accepted: ["baciare"], tags: ["social", "dating", "verb"], tier: 1 },
    { id: "a234-t1-031", type: "recognize", prompt: "il bacio", accepted: ["a kiss"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-032", type: "produce", prompt: "a kiss", accepted: ["il bacio"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-033", type: "recognize", prompt: "abbracciare", accepted: ["to hug"], tags: ["social", "friendship", "verb"], tier: 1 },
    { id: "a234-t1-034", type: "produce", prompt: "to hug", accepted: ["abbracciare"], tags: ["social", "friendship", "verb"], tier: 1 },
    { id: "a234-t1-035", type: "recognize", prompt: "l'abbraccio", accepted: ["a hug"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-036", type: "produce", prompt: "a hug", accepted: ["l'abbraccio"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-037", type: "recognize", prompt: "lasciarsi", accepted: ["to break up"], tags: ["social", "conflict", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-038", type: "produce", prompt: "to break up (with each other)", accepted: ["lasciarsi"], tags: ["social", "conflict", "verb", "reciprocal"], tier: 1 },
    { id: "a234-t1-039", type: "recognize", prompt: "rompere (una relazione)", accepted: ["to break off","to break off (a relationship)"], tags: ["social", "conflict", "verb-phrase"], tier: 1 },
    { id: "a234-t1-040", type: "produce", prompt: "to break off a relationship", accepted: ["rompere una relazione"], tags: ["social", "conflict", "verb-phrase"], tier: 1 },
    { id: "a234-t1-041", type: "recognize", prompt: "il cuore spezzato", accepted: ["a broken heart"], tags: ["social", "conflict", "noun", "emotion"], tier: 1 },
    { id: "a234-t1-042", type: "produce", prompt: "a broken heart", accepted: ["il cuore spezzato"], tags: ["social", "conflict", "noun", "emotion"], tier: 1 },
    { id: "a234-t1-043", type: "recognize", prompt: "il tradimento", accepted: ["betrayal", "cheating"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-044", type: "produce", prompt: "betrayal", accepted: ["il tradimento"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-045", type: "recognize", prompt: "tradire", accepted: ["to betray", "to cheat (on someone)"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-046", type: "produce", prompt: "to cheat (on someone)", accepted: ["tradire"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-047", type: "recognize", prompt: "geloso/a", accepted: ["jealous"], tags: ["social", "conflict", "adjective", "emotion"], tier: 1 },
    { id: "a234-t1-048", type: "produce", prompt: "jealous", accepted: ["geloso/a"], tags: ["social", "conflict", "adjective", "emotion"], tier: 1 },
    { id: "a234-t1-049", type: "recognize", prompt: "la fiducia", accepted: ["trust"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-050", type: "produce", prompt: "trust", accepted: ["la fiducia"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-051", type: "recognize", prompt: "litigare", accepted: ["to argue", "to fight (verbally)"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-052", type: "produce", prompt: "to argue", accepted: ["litigare"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-053", type: "recognize", prompt: "il litigio", accepted: ["an argument", "a quarrel"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-054", type: "produce", prompt: "an argument", accepted: ["il litigio"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-055", type: "recognize", prompt: "fare pace", accepted: ["to make up", "to make peace"], tags: ["social", "conflict", "verb-phrase"], tier: 1 },
    { id: "a234-t1-056", type: "produce", prompt: "to make up (after a fight)", accepted: ["fare pace"], tags: ["social", "conflict", "verb-phrase"], tier: 1 },
    { id: "a234-t1-057", type: "recognize", prompt: "riconciliarsi", accepted: ["to reconcile"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-058", type: "produce", prompt: "to reconcile", accepted: ["riconciliarsi"], tags: ["social", "conflict", "verb"], tier: 1 },
    { id: "a234-t1-059", type: "recognize", prompt: "la riconciliazione", accepted: ["reconciliation"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-060", type: "produce", prompt: "reconciliation", accepted: ["la riconciliazione"], tags: ["social", "conflict", "noun"], tier: 1 },
    { id: "a234-t1-061", type: "recognize", prompt: "il matrimonio", accepted: ["wedding", "marriage"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-062", type: "produce", prompt: "wedding", accepted: ["il matrimonio"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-063", type: "recognize", prompt: "sposarsi", accepted: ["to get married"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-064", type: "produce", prompt: "to get married", accepted: ["sposarsi"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-065", type: "recognize", prompt: "lo sposo / la sposa", accepted: ["groom / bride"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-066", type: "produce", prompt: "groom / bride", accepted: ["lo sposo / la sposa"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-067", type: "recognize", prompt: "divorziare", accepted: ["to divorce"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-068", type: "produce", prompt: "to divorce", accepted: ["divorziare"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-069", type: "recognize", prompt: "il divorzio", accepted: ["divorce"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-070", type: "produce", prompt: "divorce", accepted: ["il divorzio"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-071", type: "recognize", prompt: "separarsi", accepted: ["to separate","to separate (from a partner)"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-072", type: "produce", prompt: "to separate (from a partner)", accepted: ["separarsi"], tags: ["social", "wedding", "verb"], tier: 1 },
    { id: "a234-t1-073", type: "recognize", prompt: "la separazione", accepted: ["separation"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-074", type: "produce", prompt: "separation", accepted: ["la separazione"], tags: ["social", "wedding", "noun"], tier: 1 },
    { id: "a234-t1-075", type: "recognize", prompt: "la relazione a distanza", accepted: ["long-distance relationship"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-076", type: "produce", prompt: "long-distance relationship", accepted: ["la relazione a distanza"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-077", type: "recognize", prompt: "la relazione", accepted: ["relationship"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-078", type: "produce", prompt: "relationship", accepted: ["la relazione"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-079", type: "recognize", prompt: "il rapporto", accepted: ["relationship", "bond"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-080", type: "produce", prompt: "bond (between people)", accepted: ["il rapporto"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-081", type: "recognize", prompt: "la coppia", accepted: ["couple"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-082", type: "produce", prompt: "couple", accepted: ["la coppia"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-083", type: "recognize", prompt: "single", accepted: ["single","single (not in a relationship)"], tags: ["social", "relationship", "adjective"], tier: 1 },
    { id: "a234-t1-084", type: "produce", prompt: "single (not in a relationship)", accepted: ["single"], tags: ["social", "relationship", "adjective"], tier: 1 },
    { id: "a234-t1-085", type: "recognize", prompt: "il/la partner", accepted: ["partner"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-086", type: "produce", prompt: "partner", accepted: ["il/la partner"], tags: ["social", "relationship", "noun"], tier: 1 },
    { id: "a234-t1-087", type: "recognize", prompt: "il ragazzo / la ragazza", accepted: ["boyfriend / girlfriend (informal)", "boy / girl"], hint: "context decides between 'boy/girl' and 'boyfriend/girlfriend'", tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-088", type: "produce", prompt: "boyfriend (informal)", accepted: ["il ragazzo"], tags: ["social", "dating", "noun"], tier: 1 },
    { id: "a234-t1-089", type: "recognize", prompt: "il/la coinquilino/a", accepted: ["roommate"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-090", type: "produce", prompt: "roommate", accepted: ["il/la coinquilino/a", "il coinquilino", "la coinquilina"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-091", type: "recognize", prompt: "il vicino di casa / la vicina di casa", accepted: ["neighbor"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-092", type: "produce", prompt: "neighbor", accepted: ["il vicino di casa", "la vicina di casa"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-093", type: "recognize", prompt: "l'amico d'infanzia / l'amica d'infanzia", accepted: ["childhood friend"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-094", type: "produce", prompt: "childhood friend", accepted: ["l'amico d'infanzia", "l'amica d'infanzia"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-095", type: "recognize", prompt: "il migliore amico / la migliore amica", accepted: ["best friend"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-096", type: "produce", prompt: "best friend", accepted: ["il migliore amico", "la migliore amica"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-097", type: "recognize", prompt: "il gruppo di amici", accepted: ["friend group", "group of friends"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-098", type: "produce", prompt: "friend group", accepted: ["il gruppo di amici"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-099", type: "recognize", prompt: "la compagnia", accepted: ["company", "companionship"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-100", type: "produce", prompt: "companionship", accepted: ["la compagnia"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-101", type: "recognize", prompt: "fare amicizia", accepted: ["to make friends"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-102", type: "produce", prompt: "to make friends", accepted: ["fare amicizia"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-103", type: "recognize", prompt: "fare conoscenza", accepted: ["to get acquainted"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-104", type: "produce", prompt: "to get acquainted (with someone)", accepted: ["fare conoscenza"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-105", type: "recognize", prompt: "la conoscenza", accepted: ["acquaintance"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-106", type: "produce", prompt: "an acquaintance", accepted: ["una conoscenza"], tags: ["social", "friendship", "noun"], tier: 1 },
    { id: "a234-t1-107", type: "recognize", prompt: "presentare qualcuno", accepted: ["to introduce someone"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-108", type: "produce", prompt: "to introduce someone", accepted: ["presentare qualcuno"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-109", type: "recognize", prompt: "andare d'accordo", accepted: ["to get along"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-110", type: "produce", prompt: "to get along (with someone)", accepted: ["andare d'accordo"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-111", type: "recognize", prompt: "perdere i contatti", accepted: ["to lose touch"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-112", type: "produce", prompt: "to lose touch", accepted: ["perdere i contatti"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-113", type: "recognize", prompt: "restare in contatto", accepted: ["to stay in touch"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-114", type: "produce", prompt: "to stay in touch", accepted: ["restare in contatto", "rimanere in contatto"], tags: ["social", "friendship", "verb-phrase"], tier: 1 },
    { id: "a234-t1-115", type: "recognize", prompt: "la festa", accepted: ["party"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-116", type: "produce", prompt: "party", accepted: ["la festa"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-117", type: "recognize", prompt: "invitare", accepted: ["to invite"], tags: ["social", "party", "verb"], tier: 1 },
    { id: "a234-t1-118", type: "produce", prompt: "to invite", accepted: ["invitare"], tags: ["social", "party", "verb"], tier: 1 },
    { id: "a234-t1-119", type: "recognize", prompt: "essere invitato/a", accepted: ["to be invited"], tags: ["social", "party", "verb-phrase"], tier: 1 },
    { id: "a234-t1-120", type: "produce", prompt: "to be invited", accepted: ["essere invitato/a"], tags: ["social", "party", "verb-phrase"], tier: 1 },
    { id: "a234-t1-121", type: "recognize", prompt: "l'invito", accepted: ["invitation"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-122", type: "produce", prompt: "invitation", accepted: ["l'invito"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-123", type: "recognize", prompt: "organizzare una festa", accepted: ["to organize a party", "to throw a party"], tags: ["social", "party", "verb-phrase"], tier: 1 },
    { id: "a234-t1-124", type: "produce", prompt: "to throw a party", accepted: ["organizzare una festa"], tags: ["social", "party", "verb-phrase"], tier: 1 },
    { id: "a234-t1-125", type: "recognize", prompt: "il compleanno", accepted: ["birthday"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-126", type: "produce", prompt: "birthday", accepted: ["il compleanno"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-127", type: "recognize", prompt: "festeggiare", accepted: ["to celebrate"], tags: ["social", "party", "verb"], tier: 1 },
    { id: "a234-t1-128", type: "produce", prompt: "to celebrate", accepted: ["festeggiare"], tags: ["social", "party", "verb"], tier: 1 },
    { id: "a234-t1-129", type: "recognize", prompt: "il regalo", accepted: ["gift", "present"], tags: ["social", "party", "noun"], tier: 1 },
    { id: "a234-t1-130", type: "produce", prompt: "gift", accepted: ["il regalo"], tags: ["social", "party", "noun"], tier: 1 },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    { id: "a234-t2-001", type: "fill_blank", prompt: "Ci ___ da quando frequentavamo le scuole medie insieme.", accepted: ["conosciamo"], hint: "reciprocal reflexive 'conoscersi' — noi, presente", tags: ["fill_blank", "reciprocal-reflexive", "conoscersi"], tier: 2 },
    { id: "a234-t2-002", type: "fill_blank", prompt: "Da giovani, io e mio fratello ci ___ delle lunghe lettere ogni estate, quando lui andava a trovare i nonni in campagna.", accepted: ["scrivevamo"], hint: "reciprocal reflexive 'scriversi' — noi, imperfetto", tags: ["fill_blank", "reciprocal-reflexive", "scriversi"], tier: 2 },
    { id: "a234-t2-003", type: "fill_blank", prompt: "Marco e Elena si ___ da un mese, ma non sono ancora fidanzati ufficialmente.", accepted: ["frequentano"], hint: "reciprocal reflexive 'frequentarsi' — loro, presente", tags: ["fill_blank", "reciprocal-reflexive", "frequentarsi"], tier: 2 },
    { id: "a234-t2-004", type: "fill_blank", prompt: "Dopo l'università, io e Sara ci siamo ___ di vista per quasi dieci anni.", accepted: ["persi", "perse"], hint: "reciprocal reflexive 'perdersi di vista' — noi, passato prossimo", tags: ["fill_blank", "reciprocal-reflexive", "perdersi"], tier: 2 },
    { id: "a234-t2-005", type: "fill_blank", prompt: "I miei genitori si sono ___ nel 1995, in una piccola chiesa di montagna.", accepted: ["sposati"], hint: "reciprocal reflexive 'sposarsi' — loro, passato prossimo", tags: ["fill_blank", "reciprocal-reflexive", "sposarsi"], tier: 2 },
    { id: "a234-t2-006", type: "fill_blank", prompt: "Prima di lasciarsi, Anna e Paolo si ___ ogni weekend senza eccezioni.", accepted: ["vedevano"], hint: "reciprocal reflexive 'vedersi' — loro, imperfetto", tags: ["fill_blank", "reciprocal-reflexive", "vedersi"], tier: 2 },
    { id: "a234-t2-007", type: "fill_blank", prompt: "Quando vi siete ___, tu e tuo marito?", accepted: ["conosciuti"], hint: "reciprocal reflexive 'conoscersi' — voi, passato prossimo", tags: ["fill_blank", "reciprocal-reflexive", "conoscersi"], tier: 2 },
    { id: "a234-t2-008", type: "fill_blank", prompt: "Le due sorelle si ___ con un solo sguardo, senza bisogno di parlare.", accepted: ["capiscono"], hint: "reciprocal reflexive 'capirsi' — loro, presente", tags: ["fill_blank", "reciprocal-reflexive", "capirsi"], tier: 2 },
    { id: "a234-t2-009", type: "fill_blank", prompt: "Noi due ci ___ al telefono tutte le sere prima di dormire.", accepted: ["sentiamo"], hint: "reciprocal reflexive 'sentirsi' — noi, presente", tags: ["fill_blank", "reciprocal-reflexive", "sentirsi"], tier: 2 },
    { id: "a234-t2-010", type: "fill_blank", prompt: "Dopo il litigio più brutto della loro storia, Marco e Luisa si sono ___ per sempre.", accepted: ["lasciati"], hint: "reciprocal reflexive 'lasciarsi' — loro, passato prossimo", tags: ["fill_blank", "reciprocal-reflexive", "lasciarsi"], tier: 2 },
    { id: "a234-t2-011", type: "fill_blank", prompt: "Da bambini, io e il mio vicino di casa ci ___ con i compiti ogni pomeriggio.", accepted: ["aiutavamo"], hint: "reciprocal reflexive 'aiutarsi' — noi, imperfetto", tags: ["fill_blank", "reciprocal-reflexive", "aiutarsi"], tier: 2 },
    { id: "a234-t2-012", type: "fill_blank", prompt: "I due colleghi si ___ anche quando non sono d'accordo su tutto.", accepted: ["rispettano"], hint: "reciprocal reflexive 'rispettarsi' — loro, presente", tags: ["fill_blank", "reciprocal-reflexive", "rispettarsi"], tier: 2 },
    { id: "a234-t2-013", type: "fill_blank", prompt: "Anche se litigano spesso, i due fratelli si ___ più di chiunque altro.", accepted: ["vogliono bene"], hint: "reciprocal idiom 'volersi bene' (to care about each other) — loro, presente", tags: ["fill_blank", "reciprocal-reflexive", "volersi-bene"], tier: 2 },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    { id: "a234-t3-001", type: "produce", prompt: "Do you want to go out together this weekend?", accepted: ["Vuoi uscire insieme questo weekend?", "Ti va di uscire insieme questo weekend?"], hint: "'uscire insieme' + 'vuoi' or the softer 'ti va di'", tags: ["chunk", "dating", "invitation"], tier: 3 },
    { id: "a234-t3-002", type: "produce", prompt: "We met each other at a party two years ago.", accepted: ["Ci siamo conosciuti a una festa due anni fa.", "Ci siamo incontrati a una festa due anni fa."], hint: "reciprocal 'conoscersi' or 'incontrarsi', passato prossimo", tags: ["chunk", "dating", "passato-prossimo"], tier: 3 },
    { id: "a234-t3-003", type: "produce", prompt: "I'm throwing a party for my birthday next Saturday.", accepted: ["Organizzo una festa per il mio compleanno sabato prossimo.", "Faccio una festa per il mio compleanno sabato prossimo."], hint: "'organizzare' or the more casual 'fare una festa'", tags: ["chunk", "party", "compleanno"], tier: 3 },
    { id: "a234-t3-004", type: "produce", prompt: "They've been together for five years but aren't married yet.", accepted: ["Stanno insieme da cinque anni ma non sono ancora sposati.", "Sono insieme da cinque anni ma non si sono ancora sposati."], hint: "'stare insieme da' + duration; 'ancora' + negative for 'not yet'", tags: ["chunk", "relationship", "duration"], tier: 3 },
    { id: "a234-t3-005", type: "produce", prompt: "We lost touch after high school.", accepted: ["Abbiamo perso i contatti dopo il liceo.", "Ci siamo persi di vista dopo il liceo."], hint: "'perdere i contatti' or the reciprocal 'perdersi di vista'", tags: ["chunk", "friendship", "passato-prossimo"], tier: 3 },
    { id: "a234-t3-006", type: "produce", prompt: "Let's stay in touch.", accepted: ["Restiamo in contatto.", "Teniamoci in contatto."], hint: "'restare in contatto' — noi imperative, or 'tenersi in contatto'", tags: ["chunk", "friendship", "imperative"], tier: 3 },
    { id: "a234-t3-007", type: "produce", prompt: "He introduced me to his best friend at the party.", accepted: ["Mi ha presentato al suo migliore amico alla festa."], hint: "'presentare qualcuno a qualcuno'", tags: ["chunk", "friendship", "presentare"], tier: 3 },
    { id: "a234-t3-008", type: "produce", prompt: "My roommate and I get along really well.", accepted: ["Io e il mio coinquilino andiamo molto d'accordo.", "Io e la mia coinquilina andiamo molto d'accordo."], hint: "'andare d'accordo' + 'molto' for emphasis", tags: ["chunk", "friendship", "coinquilino"], tier: 3 },
    { id: "a234-t3-009", type: "produce", prompt: "They broke up after a huge argument.", accepted: ["Si sono lasciati dopo un litigio enorme.", "Hanno rotto dopo un litigio enorme."], hint: "'lasciarsi' or the colloquial 'rompere' alone", tags: ["chunk", "conflict", "passato-prossimo"], tier: 3 },
    { id: "a234-t3-010", type: "produce", prompt: "I don't trust him anymore — he cheated on me.", accepted: ["Non mi fido più di lui: mi ha tradito.", "Non ho più fiducia in lui: mi ha tradito."], hint: "'fidarsi di' or 'avere fiducia in' + 'tradire'", tags: ["chunk", "conflict", "fiducia"], tier: 3 },
    { id: "a234-t3-011", type: "produce", prompt: "I had a huge crush on my neighbor when I was fifteen.", accepted: ["Avevo una cotta enorme per il mio vicino di casa quando avevo quindici anni.", "Avevo una cotta enorme per la mia vicina di casa quando avevo quindici anni."], hint: "'avere una cotta per' — imperfetto for a past ongoing state", tags: ["chunk", "dating", "imperfetto"], tier: 3 },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    { id: "a234-t4-001", type: "passage_cloze", prompt: "Quando sono arrivata a Bologna per l'università, non conoscevo nessuno in città.\nIl primo giorno ho incontrato Chiara, la mia ___, davanti alla porta dell'appartamento.\nAll'inizio eravamo timide, ma dopo una settimana cucinavamo insieme ogni sera.\nOra, quattro anni dopo, siamo migliori amiche e viviamo ancora nello stesso palazzo.", accepted: ["coinquilina"], hint: "the word for the person she shares the apartment with — feminine, agreeing with 'la mia'", tags: ["passage_cloze", "friendship", "coinquilino"], tier: 4, prerequisites: ["a234-t1-089", "a234-t1-090"] },
    { id: "a234-t4-002", type: "passage_cloze", prompt: "Da bambini, io e Davide eravamo inseparabili: giocavamo insieme ogni pomeriggio dopo la scuola.\nPoi la sua famiglia si è trasferita in un'altra regione e per anni non ci siamo scritti.\nAbbiamo perso i ___ per quasi quindici anni, senza nemmeno un messaggio.\nIl mese scorso l'ho incontrato per caso in stazione e abbiamo parlato per due ore, come se il tempo non fosse mai passato.", accepted: ["contatti"], hint: "the noun in the phrase 'perdere i ___' — to lose touch", tags: ["passage_cloze", "friendship", "contatti"], tier: 4, prerequisites: ["a234-t1-111", "a234-t1-112"] },
    { id: "a234-t4-003", type: "passage_cloze", prompt: "Marta e Luca si sono conosciuti in un piccolo bar del centro, dieci anni fa.\nSi sono frequentati per tre anni prima di andare a vivere insieme.\nIl mese scorso hanno finalmente organizzato il ___: una cerimonia semplice, in giardino, con solo trenta invitati.\nDopo la festa, sono partiti per la Sicilia per la luna di miele.", accepted: ["matrimonio"], hint: "the noun for the wedding ceremony itself", tags: ["passage_cloze", "wedding", "matrimonio"], tier: 4, prerequisites: ["a234-t1-061", "a234-t1-062"] },
    { id: "a234-t4-004", type: "passage_cloze", prompt: "Il compleanno della mia migliore amica cade sempre a fine luglio, quando tutti sono già in vacanza.\nQuest'anno ho deciso di organizzare una ___ a sorpresa, invitando tutto il suo gruppo di amici.\nAbbiamo affittato un piccolo giardino vicino al fiume e abbiamo nascosto i regali sotto un tavolo.\nQuando è arrivata e ha visto tutti quanti, è scoppiata a piangere dalla gioia.", accepted: ["festa"], hint: "the noun for the social gathering being organized", tags: ["passage_cloze", "party", "festa"], tier: 4, prerequisites: ["a234-t1-115", "a234-t1-116"] },

    // ── Tier 3 – Chunks & Phrases (context coverage batch) ────────────────────
    { id: "a234-t3-012", type: "produce", prompt: "She seems to be engaged to someone, even though she hasn't introduced her fiancé to the family yet.", accepted: ["Sembra essere fidanzata con qualcuno, anche se non ha ancora presentato il fidanzato alla famiglia."], hint: "'essere fidanzata' + 'il fidanzato'", tags: ["chunk", "dating", "fidanzato"], tier: 3 },
    { id: "a234-t3-013", type: "produce", prompt: "They want to get engaged officially after the perfect first date they had at the beach.", accepted: ["Vogliono fidanzarsi ufficialmente dopo il primo appuntamento perfetto che hanno avuto in spiaggia."], hint: "'fidanzarsi' + 'il primo appuntamento'", tags: ["chunk", "dating", "fidanzarsi"], tier: 3 },
    { id: "a234-t3-014", type: "produce", prompt: "They want to get to know each other slowly before deciding to date each other seriously.", accepted: ["Vogliono conoscersi con calma prima di decidere di frequentarsi seriamente."], hint: "'conoscersi' + 'frequentarsi'", tags: ["chunk", "dating", "conoscersi"], tier: 3 },
    { id: "a234-t3-015", type: "produce", prompt: "They've been together for a year: they decided to start dating right after university.", accepted: ["Stanno insieme da un anno: hanno deciso di mettersi insieme subito dopo l'università."], hint: "'stare insieme' + 'mettersi insieme'", tags: ["chunk", "dating", "stare-insieme"], tier: 3 },
    { id: "a234-t3-016", type: "produce", prompt: "She didn't want to fall in love again, but she admits she's completely in love with him now.", accepted: ["Non voleva innamorarsi di nuovo, ma ammette di essere innamorata di lui più che mai."], hint: "'innamorarsi' + 'essere innamorato/a (di)'", tags: ["chunk", "dating", "innamorarsi"], tier: 3 },
    { id: "a234-t3-017", type: "produce", prompt: "He seems to have a crush on his coworker, and everyone at the office has noticed — he's even started flirting with her at lunch.", accepted: ["Sembra avere una cotta per la sua collega, e in ufficio se ne sono accorti tutti — ha persino iniziato a flirtare con lei a pranzo."], hint: "'avere una cotta (per)' + 'flirtare'", tags: ["chunk", "dating", "cotta"], tier: 3 },
    { id: "a234-t3-018", type: "produce", prompt: "Their first kiss happened during a summer storm, on the beach, at midnight.", accepted: ["Il primo bacio tra Marco e Giulia è successo durante un temporale d'estate, in spiaggia, a mezzanotte."], hint: "'il primo bacio'", tags: ["chunk", "dating", "bacio"], tier: 3 },
    { id: "a234-t3-019", type: "produce", prompt: "He was never afraid to kiss his girlfriend in front of everyone.", accepted: ["Non ha mai avuto paura di baciare la sua ragazza davanti a tutti."], hint: "'baciare' + 'la ragazza'", tags: ["chunk", "dating", "baciare"], tier: 3 },
    { id: "a234-t3-020", type: "produce", prompt: "The kiss they shared that night was the sweetest of her life.", accepted: ["Il bacio che si sono scambiati quella sera è stato il più dolce della sua vita."], hint: "'il bacio'", tags: ["chunk", "dating", "bacio"], tier: 3 },
    { id: "a234-t3-021", type: "produce", prompt: "He wanted to hug his best friend before leaving, and that hug lasted more than ten minutes.", accepted: ["Voleva abbracciare il suo migliore amico prima di partire, e l'abbraccio è durato più di dieci minuti."], hint: "'abbracciare' + 'l'abbraccio'", tags: ["chunk", "friendship", "abbracciare"], tier: 3 },
    { id: "a234-t3-022", type: "produce", prompt: "After they broke up, he wanted to end a five-year relationship, leaving her with a broken heart.", accepted: ["Dopo che si sono lasciati, lui ha voluto rompere una relazione lunga cinque anni, lasciandole il cuore spezzato."], hint: "'rompere (una relazione)' + 'il cuore spezzato'", tags: ["chunk", "conflict", "rompere"], tier: 3 },
    { id: "a234-t3-023", type: "produce", prompt: "The betrayal was worse than she expected: he had kept cheating on his partner for almost a year.", accepted: ["Il tradimento è stato peggiore di quanto si aspettasse: lui aveva continuato a tradire la sua compagna per quasi un anno."], hint: "'il tradimento' + 'tradire'", tags: ["chunk", "conflict", "tradimento"], tier: 3 },
    { id: "a234-t3-024", type: "produce", prompt: "He's so jealous that he can't stand it when she talks to other men.", accepted: ["Lui è così geloso che non sopporta quando lei parla con altri uomini."], hint: "'geloso/a'", tags: ["chunk", "conflict", "geloso"], tier: 3 },
    { id: "a234-t3-025", type: "produce", prompt: "They don't want to argue about money anymore, so they decided to make up before Christmas.", accepted: ["Non vogliono litigare più per i soldi, così hanno deciso di fare pace prima di Natale."], hint: "'litigare' + 'fare pace'", tags: ["chunk", "conflict", "litigare"], tier: 3 },
    { id: "a234-t3-026", type: "produce", prompt: "After months apart, they finally want to reconcile — the reconciliation won't be easy, but they're trying.", accepted: ["Dopo mesi di lontananza, vogliono finalmente riconciliarsi: la riconciliazione non sarà facile, ma ci stanno provando."], hint: "'riconciliarsi' + 'la riconciliazione'", tags: ["chunk", "conflict", "riconciliarsi"], tier: 3 },
    { id: "a234-t3-027", type: "produce", prompt: "They decided to get married next spring, in the same church where their parents got married.", accepted: ["Hanno deciso di sposarsi la prossima primavera, nella stessa chiesa dove si sono sposati i loro genitori."], hint: "'sposarsi'", tags: ["chunk", "wedding", "sposarsi"], tier: 3 },
    { id: "a234-t3-028", type: "produce", prompt: "They didn't want to divorce quickly, but after the separation, the divorce became official within a year.", accepted: ["Non volevano divorziare in fretta, ma dopo la separazione, il divorzio è diventato ufficiale entro un anno."], hint: "'divorziare' + 'la separazione' + 'il divorzio'", tags: ["chunk", "wedding", "divorzio"], tier: 3 },
    { id: "a234-t3-029", type: "produce", prompt: "They decided to separate for a while before deciding whether to divorce for good.", accepted: ["Hanno deciso di separarsi per un po' prima di decidere se divorziare per sempre."], hint: "'separarsi'", tags: ["chunk", "wedding", "separarsi"], tier: 3 },
    { id: "a234-t3-030", type: "produce", prompt: "Their long-distance relationship lasted two years before he moved to be with her: that story changed them both, and the bond between them only grew stronger.", accepted: ["La relazione a distanza tra Marco e Sofia è durata due anni prima che lui si trasferisse per stare con lei: quella storia li ha cambiati entrambi, e il rapporto tra loro è diventato solo più forte."], hint: "'la relazione a distanza' + 'il rapporto'", tags: ["chunk", "relationship", "relazione"], tier: 3 },
    { id: "a234-t3-031", type: "produce", prompt: "She's been single for three years and says she likes being single, without a partner.", accepted: ["È single da tre anni e dice che le piace essere single, senza un partner."], hint: "'single' + 'il/la partner'", tags: ["chunk", "relationship", "single"], tier: 3 },
    { id: "a234-t3-032", type: "produce", prompt: "My girlfriend and I met at a party organized by my childhood friend.", accepted: ["La mia ragazza e io ci siamo conosciuti a una festa organizzata dal mio amico d'infanzia."], hint: "'la ragazza' + 'l'amico d'infanzia'", tags: ["chunk", "friendship", "amico-infanzia"], tier: 3 },
    { id: "a234-t3-033", type: "produce", prompt: "We enjoy her company, and we always make friends easily when we go out together.", accepted: ["Ci piace la sua compagnia, e facciamo sempre amicizia facilmente quando usciamo insieme."], hint: "'la compagnia' + 'fare amicizia'", tags: ["chunk", "friendship", "compagnia"], tier: 3 },
    { id: "a234-t3-034", type: "produce", prompt: "It's nice to get acquainted with new people, but a real acquaintance takes time to become a real friendship.", accepted: ["È bello fare conoscenza con persone nuove, ma una conoscenza vera ci mette tempo a diventare una vera amicizia."], hint: "'fare conoscenza' + 'la conoscenza'", tags: ["chunk", "friendship", "conoscenza"], tier: 3 },
    { id: "a234-t3-035", type: "produce", prompt: "He doesn't like introducing someone to his parents right away — he prefers to wait — but with my family he wanted to get along with everyone from the very first moment.", accepted: ["Non gli piace presentare qualcuno subito ai suoi genitori — preferisce aspettare — ma con la mia famiglia ha voluto andare d'accordo con tutti fin dal primo momento."], hint: "'presentare qualcuno' + 'andare d'accordo'", tags: ["chunk", "friendship", "presentare"], tier: 3 },
    { id: "a234-t3-036", type: "produce", prompt: "I didn't know that guy was her official boyfriend.", accepted: ["Non sapevo che quel ragazzo fosse il suo ragazzo ufficiale."], hint: "'il ragazzo' (both senses: guy / boyfriend)", tags: ["chunk", "dating", "ragazzo"], tier: 3 },
    { id: "a234-t3-037", type: "produce", prompt: "My childhood friend is a girl I've known since kindergarten.", accepted: ["La mia amica d'infanzia è una ragazza che conosco fin dall'asilo."], hint: "'l'amica d'infanzia'", tags: ["chunk", "friendship", "amico-infanzia"], tier: 3 },

    // ── Tier 3 – Fill-blank (context coverage batch) ─────────────────────────
    { id: "a234-t3-038", type: "fill_blank", prompt: "Dopo essersi trasferite all'estero, molte persone rischiano di ___ con i vecchi amici, ma noi siamo riuscite a restare in contatto ogni mese.", accepted: ["perdere i contatti"], hint: "the phrase for losing touch with old friends", tags: ["fill_blank", "friendship", "contatti"], tier: 3 },
    { id: "a234-t3-039", type: "fill_blank", prompt: "Vuole ___ tutti alla sua festa di compleanno, ed essere invitato a una delle sue feste è sempre speciale.", accepted: ["invitare"], hint: "the verb for asking people to come", tags: ["fill_blank", "party", "invitare"], tier: 3 },
    { id: "a234-t3-040", type: "fill_blank", prompt: "La festa doveva iniziare alle nove, come diceva ___, quindi abbiamo deciso di organizzare una festa a sorpresa prima che arrivassero tutti.", accepted: ["l'invito"], hint: "the noun for the card announcing the party", tags: ["fill_blank", "party", "invito"], tier: 3 },
    { id: "a234-t3-041", type: "fill_blank", prompt: "Vogliamo ___ il suo compleanno con il regalo che aspettava da mesi.", accepted: ["festeggiare"], hint: "the verb for marking an occasion", tags: ["fill_blank", "party", "festeggiare"], tier: 3 },

    // ── Tier 3 – Chunks & Phrases (coverage backfill) ─────────────────────────
    { id: "a234-t3-042", type: "produce", prompt: "Luca says he wants to be engaged before he turns thirty.", accepted: ["Luca dice che vuole essere fidanzato prima di compiere trent'anni."], hint: "'essere fidanzato' + 'volere' + infinitive", tags: ["chunk", "dating", "fidanzato"], tier: 3 },
    { id: "a234-t3-043", type: "produce", prompt: "Anna and Paolo will keep staying together even if they move to different cities.", accepted: ["Anna e Paolo continueranno a stare insieme anche se si trasferiranno in città diverse."], hint: "'stare insieme' after 'continuare a'", tags: ["chunk", "relationship", "stare-insieme"], tier: 3 },
    { id: "a234-t3-044", type: "produce", prompt: "Marco didn't want to be in love with anyone after the divorce.", accepted: ["Marco non voleva essere innamorato di nessuno dopo il divorzio."], hint: "'essere innamorato (di)' — imperfetto for a past state", tags: ["chunk", "dating", "innamorarsi"], tier: 3 },
    { id: "a234-t3-045", type: "produce", prompt: "It's easy to make friends when you travel alone.", accepted: ["È facile fare amicizia quando viaggi da solo."], hint: "'fare amicizia'", tags: ["chunk", "friendship", "amicizia"], tier: 3 },
  ],
};
export default unit;
