import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-14-daily-routine",
  name: "Daily Routine",
  level: "A2",
  theme: "Daily Routine & Reflexives",
  emoji: "🪥",
  prerequisiteUnits: ["a2-unit-13-shopping"],
  cards: [
    // ─── Tier 1 – Vocab ───────────────────────────────────────────────────────
    {
      id: "u14-t1-001",
      type: "produce",
      prompt: "the alarm clock",
      accepted: ["la sveglia"],
      hint: "feminine noun",
      tags: ["vocab", "morning", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-002",
      type: "produce",
      prompt: "the bathroom",
      accepted: ["il bagno"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "rooms"],
      tier: 1,
    },
    {
      id: "u14-t1-003",
      type: "produce",
      prompt: "the shower",
      accepted: ["la doccia"],
      hint: "feminine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-004",
      type: "produce",
      prompt: "the toothpaste",
      accepted: ["il dentifricio"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-005",
      type: "produce",
      prompt: "the mirror",
      accepted: ["lo specchio"],
      hint: "masculine noun; uses 'lo'",
      tags: ["vocab", "morning", "objects"],
      tier: 1,
    },
    {
      id: "u14-t1-006",
      type: "produce",
      prompt: "the toothbrush",
      accepted: ["lo spazzolino", "lo spazzolino da denti"],
      hint: "masculine noun; uses 'lo'",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },
    {
      id: "u14-t1-007",
      type: "produce",
      prompt: "the morning",
      accepted: ["la mattina", "il mattino"],
      hint: "time of day",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-008",
      type: "produce",
      prompt: "the evening",
      accepted: ["la sera"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-009",
      type: "produce",
      prompt: "the night",
      accepted: ["la notte"],
      hint: "feminine noun",
      tags: ["vocab", "time"],
      tier: 1,
    },
    {
      id: "u14-t1-010",
      type: "produce",
      prompt: "the comb",
      accepted: ["il pettine"],
      hint: "masculine noun",
      tags: ["vocab", "morning", "hygiene"],
      tier: 1,
    },

    // ─── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u14-t2-001",
      type: "conjugate",
      prompt: "alzarsi – io",
      accepted: ["mi alzo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-002",
      type: "conjugate",
      prompt: "alzarsi – tu",
      accepted: ["ti alzi"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-003",
      type: "conjugate",
      prompt: "alzarsi – lui/lei",
      accepted: ["si alza"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-004",
      type: "conjugate",
      prompt: "alzarsi – noi",
      accepted: ["ci alziamo"],
      hint: "reflexive: ci + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-005",
      type: "conjugate",
      prompt: "alzarsi – voi",
      accepted: ["vi alzate"],
      hint: "reflexive: vi + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-006",
      type: "conjugate",
      prompt: "alzarsi – loro",
      accepted: ["si alzano"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "alzarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-007",
      type: "conjugate",
      prompt: "lavarsi – io",
      accepted: ["mi lavo"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-008",
      type: "conjugate",
      prompt: "lavarsi – tu",
      accepted: ["ti lavi"],
      hint: "reflexive: ti + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-009",
      type: "conjugate",
      prompt: "lavarsi – lui/lei",
      accepted: ["si lava"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "lavarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-010",
      type: "conjugate",
      prompt: "svegliarsi – io",
      accepted: ["mi sveglio"],
      hint: "reflexive: mi + verb stem; drop -arsi",
      tags: ["grammar", "reflexive", "svegliarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-011",
      type: "conjugate",
      prompt: "vestirsi – io",
      accepted: ["mi vesto"],
      hint: "reflexive -irsi verb",
      tags: ["grammar", "reflexive", "vestirsi"],
      tier: 2,
    },
    {
      id: "u14-t2-012",
      type: "conjugate",
      prompt: "addormentarsi – lui/lei",
      accepted: ["si addormenta"],
      hint: "reflexive: si + verb stem",
      tags: ["grammar", "reflexive", "addormentarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-013",
      type: "conjugate",
      prompt: "pettinarsi – io",
      accepted: ["mi pettino"],
      hint: "reflexive: mi + verb stem",
      tags: ["grammar", "reflexive", "pettinarsi"],
      tier: 2,
    },
    {
      id: "u14-t2-014",
      type: "conjugate",
      prompt: "mettersi – io",
      accepted: ["mi metto"],
      hint: "reflexive irregular: mettere → metto",
      tags: ["grammar", "reflexive", "mettersi"],
      tier: 2,
    },
    {
      id: "u14-t2-015",
      type: "conjugate",
      prompt: "stare + gerundio – io (mangiare)",
      accepted: ["sto mangiando"],
      hint: "stare (io) + gerundio of mangiare",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },
    {
      id: "u14-t2-016",
      type: "conjugate",
      prompt: "stare + gerundio – lui/lei (dormire)",
      accepted: ["sta dormendo"],
      hint: "stare (lui/lei) + gerundio of dormire",
      tags: ["grammar", "stare+gerundio", "present-progressive"],
      tier: 2,
    },

    // ─── Tier 3 – Chunks ──────────────────────────────────────────────────────
    {
      id: "u14-t3-001",
      type: "produce",
      prompt: "I wake up at seven o'clock.",
      accepted: ["Mi sveglio alle sette.", "Mi sveglio alle sette"],
      hint: "reflexive verb + time expression",
      tags: ["chunk", "routine", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-002",
      type: "produce",
      prompt: "I get up at seven.",
      accepted: ["Mi alzo alle sette.", "Mi alzo alle sette"],
      hint: "alzarsi io form + alle + time",
      tags: ["chunk", "routine", "time"],
      tier: 3,
    },
    {
      id: "u14-t3-003",
      type: "produce",
      prompt: "What are you doing?",
      accepted: ["Cosa stai facendo?", "Cosa stai facendo"],
      hint: "stare + gerundio of fare",
      tags: ["chunk", "stare+gerundio", "question"],
      tier: 3,
    },
    {
      id: "u14-t3-004",
      type: "produce",
      prompt: "I am studying Italian.",
      accepted: ["Sto studiando l'italiano.", "Sto studiando l'italiano"],
      hint: "stare io + gerundio of studiare",
      tags: ["chunk", "stare+gerundio"],
      tier: 3,
    },
    {
      id: "u14-t3-005",
      type: "produce",
      prompt: "She takes a shower every morning.",
      accepted: [
        "Si fa la doccia ogni mattina.",
        "Si fa la doccia ogni mattino.",
        "Lei si fa la doccia ogni mattina.",
      ],
      hint: "farsi la doccia – reflexive chunk",
      tags: ["chunk", "routine", "reflexive"],
      tier: 3,
    },
    {
      id: "u14-t3-006",
      type: "produce",
      prompt: "He gets dressed before breakfast.",
      accepted: [
        "Si veste prima di colazione.",
        "Lui si veste prima di colazione.",
      ],
      hint: "vestirsi lui + prima di colazione",
      tags: ["chunk", "routine", "reflexive"],
      tier: 3,
    },

    // ─── Tier 4 – Production & Passages ───────────────────────────────────────
    {
      id: "u14-t4-001",
      type: "produce",
      prompt: "Every night I brush my teeth and go to sleep.",
      accepted: [
        "Ogni sera mi lavo i denti e mi addormento.",
        "Ogni notte mi lavo i denti e mi addormento.",
      ],
      hint: "lavarsi i denti + addormentarsi",
      tags: ["sentence", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-009", "u14-t2-007", "u14-t2-012"],
    },
    {
      id: "u14-t4-002",
      type: "fill_blank",
      prompt: "La mattina Marco ___ alle sei e poi va in bagno.",
      accepted: ["si sveglia"],
      hint: "svegliarsi lui/lei form",
      tags: ["fill-blank", "reflexive", "routine"],
      tier: 4,
      prerequisites: ["u14-t1-007", "u14-t1-002", "u14-t2-010"],
    },
    {
      id: "u14-t4-003",
      type: "fill_blank",
      prompt: "Sto ___ la doccia adesso — ti chiamo dopo.",
      accepted: ["facendo"],
      hint: "stare + gerundio of fare",
      tags: ["fill-blank", "stare+gerundio"],
      tier: 4,
      prerequisites: ["u14-t1-003", "u14-t2-015"],
    },
    {
      id: "u14-t4-004",
      type: "passage_cloze",
      prompt:
        "Ogni mattina mi sveglio alle sette.\nPrima vado in bagno e mi lavo la faccia.\nPoi mi guardo nello specchio e mi ___.\nDopo colazione mi vesto e esco di casa.",
      accepted: ["pettino"],
      hint: "pettinarsi – io form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-007", "u14-t1-002", "u14-t1-005", "u14-t2-013"],
    },
    {
      id: "u14-t4-005",
      type: "passage_cloze",
      prompt:
        "Luisa ha una routine molto precisa.\nLa sera fa la doccia e usa il dentifricio.\nSi mette il pigiama e legge un libro.\nPoi spegne la luce e ___ lentamente.",
      accepted: ["si addormenta"],
      hint: "addormentarsi – lei form",
      tags: ["passage_cloze", "routine", "reflexive"],
      tier: 4,
      prerequisites: ["u14-t1-003", "u14-t1-004", "u14-t1-008", "u14-t2-012"],
    },
  ],
};
export default unit;
