import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-19-weather",
  name: "Weather",
  level: "A2",
  theme: "Weather & Seasons",
  emoji: "⛅",
  prerequisiteUnits: ["a2-unit-18-a2-review"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a219-t1-001",
      type: "recognize",
      prompt: "la pioggia",
      accepted: ["the rain", "rain"],
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-002",
      type: "recognize",
      prompt: "la neve",
      accepted: ["the snow", "snow"],
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-003",
      type: "recognize",
      prompt: "il sole",
      accepted: ["the sun", "sun"],
      hint: "also used in 'fa sole' — it's sunny",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-004",
      type: "recognize",
      prompt: "la nuvola",
      accepted: ["the cloud", "cloud"],
      hint: "plural: le nuvole",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-005",
      type: "recognize",
      prompt: "il vento",
      accepted: ["the wind", "wind"],
      hint: "used in 'tira vento' — it's windy",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-006",
      type: "recognize",
      prompt: "il temporale",
      accepted: ["the storm", "the thunderstorm", "storm", "thunderstorm"],
      hint: "a full storm with thunder/lightning — not just rain",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-007",
      type: "recognize",
      prompt: "la nebbia",
      accepted: ["the fog", "fog"],
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-008",
      type: "recognize",
      prompt: "la grandine",
      accepted: ["the hail", "hail"],
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-009",
      type: "recognize",
      prompt: "l'arcobaleno",
      accepted: ["the rainbow", "rainbow"],
      hint: "literally 'sky bow' — arco (arc/bow) + baleno (flash/sky)",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-010",
      type: "recognize",
      prompt: "il gelo",
      accepted: ["the frost", "frost", "the freeze", "freezing cold"],
      hint: "from 'gelare' — to freeze",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-011",
      type: "produce",
      prompt: "heat / hot weather (noun)",
      accepted: ["il caldo"],
      hint: "also used as adjective: fa caldo — it's hot",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-012",
      type: "produce",
      prompt: "cold (noun / adjective)",
      accepted: ["il freddo", "freddo"],
      hint: "fa freddo — it's cold",
      tags: ["weather", "noun", "adjective", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-013",
      type: "produce",
      prompt: "humidity / dampness",
      accepted: ["l'umidità", "l'umidità"],
      hint: "invariable noun — always feminine",
      tags: ["weather", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-014",
      type: "produce",
      prompt: "to rain (infinitive)",
      accepted: ["piovere"],
      hint: "impersonal verb — used only in 3rd person singular: piove",
      tags: ["weather", "verb", "impersonal", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-015",
      type: "produce",
      prompt: "to snow (infinitive)",
      accepted: ["nevicare"],
      hint: "impersonal verb — 3rd person singular: nevica",
      tags: ["weather", "verb", "impersonal", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-016",
      type: "produce",
      prompt: "the weather forecast",
      accepted: ["le previsioni del tempo"],
      hint: "always plural — previsioni is feminine plural",
      tags: ["weather", "phrase", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-017",
      type: "produce",
      prompt: "What's the weather like? (set question)",
      accepted: ["Che tempo fa?"],
      hint: "'fare' is used for weather — what weather does it make?",
      tags: ["weather", "phrase", "question", "A2"],
      tier: 1,
    },
    {
      id: "a219-t1-018",
      type: "produce",
      prompt: "nice/good weather (expression with 'fare')",
      accepted: ["fa bello", "fare bello"],
      hint: "opposite: fa brutto — the weather is bad",
      tags: ["weather", "phrase", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (impersonal verbs, fa + adj, seasons) ───────────────
    {
      id: "a219-t2-001",
      type: "fill_blank",
      prompt: "Guarda fuori dalla finestra — ___ a dirotto! Prendi l'ombrello.",
      accepted: ["piove"],
      hint: "impersonal verb 'piovere', 3rd person singular present",
      tags: ["weather", "impersonal verb", "A2"],
      tier: 2,
    },
    {
      id: "a219-t2-002",
      type: "fill_blank",
      prompt: "In montagna ___ spesso a dicembre; i bambini adorano giocare nella neve.",
      accepted: ["nevica"],
      hint: "impersonal verb 'nevicare', 3rd person singular present",
      tags: ["weather", "impersonal verb", "A2"],
      tier: 2,
    },
    {
      id: "a219-t2-003",
      type: "fill_blank",
      prompt: "Non mi piace quando ___ vento così forte — fa difficile camminare.",
      accepted: ["tira"],
      hint: "'tirare vento' — the wind blows; use 3rd person singular",
      tags: ["weather", "phrase", "A2"],
      tier: 2,
    },
    {
      id: "a219-t2-004",
      type: "fill_blank",
      prompt: "In estate ___ molto caldo a Roma; a volte supera i 35 gradi.",
      accepted: ["fa"],
      hint: "'fare' + adjective for weather conditions",
      tags: ["weather", "fa + adjective", "seasons", "A2"],
      tier: 2,
      prerequisites: ["a219-t1-011"],
    },
    {
      id: "a219-t2-005",
      type: "fill_blank",
      prompt: "Le quattro stagioni in italiano: la ___, l'estate, l'autunno e l'inverno.",
      accepted: ["primavera"],
      hint: "spring — the first season listed",
      tags: ["weather", "seasons", "vocabulary", "A2"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a219-t3-001",
      type: "produce",
      prompt: "It's raining.",
      accepted: ["Piove.", "Sta piovendo."],
      hint: "impersonal — no subject pronoun; or use stare + gerundio",
      tags: ["weather", "impersonal verb", "A2"],
      tier: 3,
      prerequisites: ["a219-t1-014", "a219-t2-001"],
    },
    {
      id: "a219-t3-002",
      type: "produce",
      prompt: "What's the weather like today?",
      accepted: ["Che tempo fa oggi?"],
      hint: "use the set question phrase + 'oggi'",
      tags: ["weather", "phrase", "question", "A2"],
      tier: 3,
      prerequisites: ["a219-t1-017"],
    },
    {
      id: "a219-t3-003",
      type: "produce",
      prompt: "I love sunny days.",
      accepted: [
        "Adoro le giornate di sole.",
        "Adoro i giorni di sole.",
        "Amo le giornate di sole.",
        "Amo i giorni di sole.",
      ],
      hint: "'di sole' after giornata/giorno — 'sunny' is expressed as 'of sun'",
      tags: ["weather", "phrase", "A2"],
      tier: 3,
      prerequisites: ["a219-t1-003"],
    },
    {
      id: "a219-t3-004",
      type: "produce",
      prompt: "The weather forecast says snow.",
      accepted: [
        "Le previsioni del tempo dicono neve.",
        "Le previsioni del tempo prevedono neve.",
        "Le previsioni del tempo annunciano neve.",
      ],
      hint: "start with 'le previsioni del tempo' + a verb of saying/predicting",
      tags: ["weather", "phrase", "A2"],
      tier: 3,
      prerequisites: ["a219-t1-002", "a219-t1-016"],
    },
    {
      id: "a219-t3-005",
      type: "produce",
      prompt: "In winter it's very cold here.",
      accepted: ["In inverno fa molto freddo qui.", "D'inverno fa molto freddo qui."],
      hint: "'in inverno' or 'd'inverno' — both are correct for 'in winter'",
      tags: ["weather", "seasons", "fa + adjective", "A2"],
      tier: 3,
      prerequisites: ["a219-t1-012", "a219-t2-004"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a219-t4-001",
      type: "passage_cloze",
      prompt: "Buonasera, sono il vostro meteorologo Marco Belli con le ___ del tempo per domani.\nAl nord Italia nevicherà sulle Alpi e farà molto freddo, intorno ai meno cinque gradi.\nAl centro, a Roma e Firenze, il cielo sarà nuvoloso con possibilità di pioggia nel pomeriggio.\nAl sud invece farà bello: sole e temperature miti, intorno ai quindici gradi.\nAttenzione: tira già forte vento sulle coste della Sicilia, con raffiche fino a sessanta chilometri orari.\nA domani con altri aggiornamenti meteo!",
      accepted: ["previsioni"],
      hint: "the plural noun for 'forecast' — part of the phrase 'le ___ del tempo'",
      tags: ["weather", "passage_cloze", "vocabulary", "A2"],
      tier: 4,
      prerequisites: [
        "a219-t1-002",
        "a219-t1-003",
        "a219-t1-004",
        "a219-t1-005",
        "a219-t1-016",
        "a219-t2-002",
        "a219-t2-003",
        "a219-t2-004",
      ],
    },
  ],
};
export default unit;
