import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-17-comparisons",
  name: "Comparisons",
  level: "A2",
  theme: "Comparative & Superlative",
  emoji: "⚖️",
  prerequisiteUnits: ["a2-unit-16-conditional"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u17-t1-001",
      type: "produce",
      prompt: "fast (adjective)",
      accepted: ["veloce"],
      hint: "same form for m/f",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "u17-t1-002",
      type: "produce",
      prompt: "slow (adjective)",
      accepted: ["lento", "lenta"],
      hint: "lento/lenta",
      tags: ["adjective", "speed"],
      tier: 1,
    },
    {
      id: "u17-t1-003",
      type: "produce",
      prompt: "the expensive (thing)",
      accepted: ["il caro", "il costoso"],
      hint: "think of 'dear' in price",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "u17-t1-004",
      type: "produce",
      prompt: "cheap / affordable (adjective)",
      accepted: ["economico", "economica"],
      hint: "sounds like 'economic'",
      tags: ["adjective", "price"],
      tier: 1,
    },
    {
      id: "u17-t1-005",
      type: "produce",
      prompt: "the heavy (thing)",
      accepted: ["il pesante"],
      hint: "same form for m/f",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "u17-t1-006",
      type: "produce",
      prompt: "light (not heavy) (adjective)",
      accepted: ["leggero", "leggera"],
      hint: "leggero/leggera",
      tags: ["adjective", "weight"],
      tier: 1,
    },
    {
      id: "u17-t1-007",
      type: "produce",
      prompt: "difficult (adjective)",
      accepted: ["difficile"],
      hint: "same form for m/f",
      tags: ["adjective", "difficulty"],
      tier: 1,
    },
    {
      id: "u17-t1-008",
      type: "produce",
      prompt: "easy (adjective)",
      accepted: ["facile"],
      hint: "same form for m/f",
      tags: ["adjective", "difficulty"],
      tier: 1,
    },
    {
      id: "u17-t1-009",
      type: "produce",
      prompt: "important (adjective)",
      accepted: ["importante"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-010",
      type: "produce",
      prompt: "interesting (adjective)",
      accepted: ["interessante"],
      hint: "same form for m/f",
      tags: ["adjective", "value"],
      tier: 1,
    },
    {
      id: "u17-t1-011",
      type: "recognize",
      prompt: "molto",
      accepted: ["very", "a lot", "much"],
      tags: ["adverb", "degree"],
      tier: 1,
    },
    {
      id: "u17-t1-012",
      type: "recognize",
      prompt: "abbastanza",
      accepted: ["enough", "quite", "fairly"],
      tags: ["adverb", "degree"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u17-t2-001",
      type: "fill_blank",
      prompt: "This car is faster than that one. → Questa macchina è ___ veloce di quella.",
      accepted: ["più"],
      hint: "comparative of superiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-002",
      type: "fill_blank",
      prompt: "This bag is less heavy than mine. → Questa borsa è ___ pesante della mia.",
      accepted: ["meno"],
      hint: "comparative of inferiority",
      tags: ["comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-003",
      type: "fill_blank",
      prompt: "Maria is as fast as Luca. → Maria è ___ veloce come Luca.",
      accepted: ["così", "tanto"],
      hint: "equality comparative – così…come or tanto…quanto",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-004",
      type: "fill_blank",
      prompt: "This pizza is as good as that one. → Questa pizza è tanto buona ___ quella.",
      accepted: ["quanto"],
      hint: "tanto…quanto = as…as",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-005",
      type: "produce",
      prompt: "better (irregular comparative of buono)",
      accepted: ["migliore", "migliori"],
      hint: "buono → ___",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-006",
      type: "produce",
      prompt: "worse (irregular comparative of cattivo)",
      accepted: ["peggiore", "peggiori"],
      hint: "cattivo → ___",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-007",
      type: "produce",
      prompt: "greater / older (irregular comparative of grande)",
      accepted: ["maggiore", "maggiori"],
      hint: "grande → ___ (also means 'elder')",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-008",
      type: "produce",
      prompt: "smaller / younger (irregular comparative of piccolo)",
      accepted: ["minore", "minori"],
      hint: "piccolo → ___ (also means 'younger')",
      tags: ["irregular", "comparative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-009",
      type: "fill_blank",
      prompt: "It is the most beautiful city. → È la ___ bella città.",
      accepted: ["più"],
      hint: "relative superlative: il/la più + adjective",
      tags: ["superlative", "relative", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-010",
      type: "fill_blank",
      prompt: "Transform 'difficile' into its absolute superlative (masculine singular).",
      accepted: ["difficilissimo"],
      hint: "drop the final vowel, add -issimo",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-011",
      type: "fill_blank",
      prompt: "Transform 'veloce' into its absolute superlative (feminine singular).",
      accepted: ["velocissima"],
      hint: "drop the final -e, add -issima",
      tags: ["superlative", "absolute", "grammar"],
      tier: 2,
    },
    {
      id: "u17-t2-012",
      type: "recognize",
      prompt: "tanto … quanto (used with adjectives)",
      accepted: ["as … as", "just as … as"],
      hint: "equality: tanto bello quanto…",
      tags: ["comparative", "equality", "grammar"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u17-t3-001",
      type: "produce",
      prompt: "It is bigger than…",
      accepted: ["È più grande di…", "è più grande di"],
      hint: "use più … di",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-002",
      type: "produce",
      prompt: "It is the most beautiful.",
      accepted: ["È il più bello.", "è il più bello", "È la più bella.", "è la più bella"],
      hint: "relative superlative",
      tags: ["chunk", "superlative"],
      tier: 3,
    },
    {
      id: "u17-t3-003",
      type: "produce",
      prompt: "It is absolutely delicious! (absolute superlative)",
      accepted: ["È buonissimo!", "è buonissimo", "È buonissima!", "è buonissima"],
      hint: "-issimo/-issima suffix",
      tags: ["chunk", "superlative", "absolute"],
      tier: 3,
    },
    {
      id: "u17-t3-004",
      type: "produce",
      prompt: "Less than I thought.",
      accepted: ["Meno di quanto pensavo.", "meno di quanto pensavo"],
      hint: "meno di quanto + imperfect",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-005",
      type: "produce",
      prompt: "This exam is more difficult than the last one.",
      accepted: [
        "Questo esame è più difficile dell'ultimo.",
        "Questo esame è più difficile di quello precedente.",
        "questo esame è più difficile dell'ultimo",
      ],
      hint: "più … di",
      tags: ["chunk", "comparative"],
      tier: 3,
    },
    {
      id: "u17-t3-006",
      type: "produce",
      prompt: "Rome is the most important city in Italy.",
      accepted: [
        "Roma è la città più importante d'Italia.",
        "Roma è la più importante città d'Italia.",
        "roma è la città più importante d'italia",
      ],
      hint: "relative superlative: la città più + adj",
      tags: ["chunk", "superlative"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passage Cloze ──────────────────────────────────
    {
      id: "u17-t4-001",
      type: "produce",
      prompt: "Translate: My brother is younger than me, but he is better at football.",
      accepted: [
        "Mio fratello è più piccolo di me, ma è migliore nel calcio.",
        "Mio fratello è minore di me, ma è migliore a calcio.",
        "Mio fratello è più giovane di me, ma è migliore nel calcio.",
      ],
      hint: "younger = più piccolo / minore; better = migliore",
      tags: ["production", "comparative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-001", "u17-t2-005", "u17-t2-008"],
    },
    {
      id: "u17-t4-002",
      type: "fill_blank",
      prompt: "Complete with the correct comparative or superlative form:\nQuesto ristorante è ___ (the best) della città. Lo conosco da anni e non ho mai mangiato male qui.",
      accepted: ["il migliore", "il più buono"],
      hint: "irregular superlative of buono",
      tags: ["production", "superlative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t2-005", "u17-t2-009"],
    },
    {
      id: "u17-t4-003",
      type: "passage_cloze",
      prompt: "Ho visitato due musei oggi. Il primo era molto grande e interessante, ma il secondo era ancora ___.\nLe opere d'arte erano bellissime e i prezzi erano meno cari di quanto mi aspettassi.\nSicuramente tornerò: è il museo più importante della regione.",
      accepted: ["migliore"],
      hint: "irregular comparative of buono — 'even better'",
      tags: ["passage_cloze", "comparative", "irregular"],
      tier: 4,
      prerequisites: ["u17-t1-010", "u17-t2-005", "u17-t2-002"],
    },
    {
      id: "u17-t4-004",
      type: "passage_cloze",
      prompt: "Marco e sua sorella sono molto diversi. Marco è alto e veloce, mentre sua sorella è più ___.\nIn compenso, lei studia più di lui: i suoi voti sono migliori e i professori dicono che è la più brava della classe.\nMarco non è triste però — dice che lo sport è più importante dei voti!",
      accepted: ["lenta"],
      hint: "opposite of veloce, feminine singular",
      tags: ["passage_cloze", "comparative", "adjective"],
      tier: 4,
      prerequisites: ["u17-t1-001", "u17-t1-002", "u17-t2-001", "u17-t2-005"],
    },
    {
      id: "u17-t4-005",
      type: "produce",
      prompt: "Translate: Italian grammar is as difficult as I expected, but it is more interesting than I thought.",
      accepted: [
        "La grammatica italiana è tanto difficile quanto mi aspettavo, ma è più interessante di quanto pensavo.",
        "La grammatica italiana è così difficile come mi aspettavo, ma è più interessante di quanto pensassi.",
      ],
      hint: "tanto … quanto for equality; più … di quanto for comparison",
      tags: ["production", "comparative", "equality"],
      tier: 4,
      prerequisites: ["u17-t1-007", "u17-t1-010", "u17-t2-001", "u17-t2-003", "u17-t2-004"],
    },
  ],
};
export default unit;
