import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "a2-unit-25-nature",
  name: "Nature",
  level: "A2",
  theme: "The Natural World",
  emoji: "🌿",
  prerequisiteUnits: ["a2-unit-24-adjectives-ii"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "a225-t1-001",
      type: "recognize",
      prompt: "l'albero",
      accepted: ["the tree", "tree"],
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-002",
      type: "recognize",
      prompt: "il fiore",
      accepted: ["the flower", "flower"],
      hint: "plural: i fiori",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-003",
      type: "recognize",
      prompt: "la foglia",
      accepted: ["the leaf", "leaf"],
      hint: "plural: le foglie",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-004",
      type: "recognize",
      prompt: "l'erba",
      accepted: ["the grass", "grass", "the herb", "herb"],
      hint: "context determines whether it means grass or herb",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-005",
      type: "recognize",
      prompt: "il bosco",
      accepted: ["the wood", "the woods", "wood", "woods", "the woodland", "woodland"],
      hint: "smaller than a forest — a wood or grove",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-006",
      type: "recognize",
      prompt: "la foresta",
      accepted: ["the forest", "forest"],
      hint: "larger and denser than un bosco",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-007",
      type: "recognize",
      prompt: "la montagna",
      accepted: ["the mountain", "mountain"],
      hint: "used in 'in montagna' — in the mountains",
      tags: ["nature", "noun", "geography", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-008",
      type: "recognize",
      prompt: "la collina",
      accepted: ["the hill", "hill"],
      hint: "smaller than la montagna",
      tags: ["nature", "noun", "geography", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-009",
      type: "recognize",
      prompt: "la valle",
      accepted: ["the valley", "valley"],
      hint: "plural: le valli",
      tags: ["nature", "noun", "geography", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-010",
      type: "recognize",
      prompt: "il fiume",
      accepted: ["the river", "river"],
      tags: ["nature", "noun", "water", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-011",
      type: "recognize",
      prompt: "il lago",
      accepted: ["the lake", "lake"],
      tags: ["nature", "noun", "water", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-012",
      type: "recognize",
      prompt: "il mare",
      accepted: ["the sea", "sea", "the ocean", "ocean"],
      hint: "used in 'al mare' — at the seaside / to the beach",
      tags: ["nature", "noun", "water", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-013",
      type: "recognize",
      prompt: "la spiaggia",
      accepted: ["the beach", "beach"],
      hint: "plural: le spiagge",
      tags: ["nature", "noun", "water", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-014",
      type: "recognize",
      prompt: "l'isola",
      accepted: ["the island", "island"],
      hint: "Sicilia e Sardegna sono due grandi isole italiane",
      tags: ["nature", "noun", "geography", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-015",
      type: "recognize",
      prompt: "la campagna",
      accepted: ["the countryside", "countryside", "the country", "country"],
      hint: "used in 'in campagna' — in the countryside",
      tags: ["nature", "noun", "geography", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-016",
      type: "recognize",
      prompt: "il cielo",
      accepted: ["the sky", "sky", "the heaven", "heaven"],
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-017",
      type: "recognize",
      prompt: "la luna",
      accepted: ["the moon", "moon"],
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-018",
      type: "recognize",
      prompt: "la stella",
      accepted: ["the star", "star"],
      hint: "plural: le stelle",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-019",
      type: "recognize",
      prompt: "la terra",
      accepted: ["the earth", "earth", "the ground", "ground", "the land", "land", "the soil", "soil"],
      hint: "context-dependent: can mean earth, ground, land, or soil",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-020",
      type: "recognize",
      prompt: "la roccia",
      accepted: ["the rock", "rock", "the cliff", "cliff"],
      hint: "plural: le rocce — a large rock or rocky face",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-021",
      type: "recognize",
      prompt: "la sabbia",
      accepted: ["the sand", "sand"],
      hint: "always uncountable in Italian — no plural",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },
    {
      id: "a225-t1-022",
      type: "recognize",
      prompt: "il ghiacciaio",
      accepted: ["the glacier", "glacier"],
      hint: "from 'ghiaccio' (ice) — a glacier is a river of ice",
      tags: ["nature", "noun", "A2"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (prepositions with geography) ───────────────────────
    {
      id: "a225-t2-001",
      type: "fill_blank",
      prompt: "Abito ___ montagna da tre anni. L'aria fresca e i paesaggi mi danno energia ogni giorno.",
      accepted: ["in"],
      hint: "'in montagna' — use 'in' (no article) with montagna, campagna, città",
      tags: ["nature", "preposition", "geography", "A2"],
      tier: 2,
      prerequisites: ["a225-t1-007"],
    },
    {
      id: "a225-t2-002",
      type: "fill_blank",
      prompt: "Quest'estate andiamo ___ mare per due settimane. Ho già prenotato un appartamento sulla spiaggia.",
      accepted: ["al"],
      hint: "'al mare' — use 'al' (a + il) with mare; compare: in campagna, in montagna",
      tags: ["nature", "preposition", "geography", "A2"],
      tier: 2,
      prerequisites: ["a225-t1-012"],
    },
    {
      id: "a225-t2-003",
      type: "fill_blank",
      prompt: "I miei nonni vivono ___ campagna, fuori città. Hanno un grande orto e tanti alberi da frutto.",
      accepted: ["in"],
      hint: "'in campagna' — no article before campagna, just like 'in montagna'",
      tags: ["nature", "preposition", "geography", "A2"],
      tier: 2,
      prerequisites: ["a225-t1-015"],
    },
    {
      id: "a225-t2-004",
      type: "fill_blank",
      prompt: "Da bambino trascorrevo le vacanze ___ lago. Nuotavamo e pescavamo ogni mattina.",
      accepted: ["al"],
      hint: "'al lago' — use 'al' (a + il) with lago, as with mare",
      tags: ["nature", "preposition", "geography", "A2"],
      tier: 2,
      prerequisites: ["a225-t1-011"],
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "a225-t3-001",
      type: "produce",
      prompt: "The forest is full of birds.",
      accepted: [
        "La foresta è piena di uccelli.",
        "Il bosco è pieno di uccelli.",
        "La foresta è piena d'uccelli.",
      ],
      hint: "'pieno/piena di' = full of; foresta (f.) → piena",
      tags: ["nature", "phrase", "A2"],
      tier: 3,
      prerequisites: ["a225-t1-006"],
    },
    {
      id: "a225-t3-002",
      type: "produce",
      prompt: "I love walking in the mountains.",
      accepted: [
        "Adoro camminare in montagna.",
        "Mi piace camminare in montagna.",
        "Amo camminare in montagna.",
        "Adoro fare passeggiate in montagna.",
      ],
      hint: "'in montagna' — no article; 'camminare' or 'fare una passeggiata'",
      tags: ["nature", "phrase", "preposition", "A2"],
      tier: 3,
      prerequisites: ["a225-t1-007", "a225-t2-001"],
    },
    {
      id: "a225-t3-003",
      type: "produce",
      prompt: "The river flows into the sea.",
      accepted: [
        "Il fiume scorre nel mare.",
        "Il fiume sfocia nel mare.",
        "Il fiume va nel mare.",
      ],
      hint: "'scorrere' = to flow; 'sfociare' = to flow into (used for rivers meeting the sea)",
      tags: ["nature", "phrase", "A2"],
      tier: 3,
      prerequisites: ["a225-t1-010", "a225-t1-012"],
    },
    {
      id: "a225-t3-004",
      type: "produce",
      prompt: "We spent the summer on the beach.",
      accepted: [
        "Abbiamo trascorso l'estate in spiaggia.",
        "Abbiamo passato l'estate in spiaggia.",
        "Abbiamo trascorso l'estate sulla spiaggia.",
        "Abbiamo passato l'estate sulla spiaggia.",
      ],
      hint: "'trascorrere' or 'passare' = to spend (time); 'in spiaggia' or 'sulla spiaggia'",
      tags: ["nature", "phrase", "passato prossimo", "A2"],
      tier: 3,
      prerequisites: ["a225-t1-013"],
    },
    {
      id: "a225-t3-005",
      type: "produce",
      prompt: "Stars are beautiful at night.",
      accepted: [
        "Le stelle sono belle di notte.",
        "Le stelle sono bellissime di notte.",
        "Le stelle sono belle la notte.",
      ],
      hint: "'di notte' = at night (no article); 'bellissime' for the absolute superlative",
      tags: ["nature", "phrase", "A2"],
      tier: 3,
      prerequisites: ["a225-t1-018"],
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "a225-t4-001",
      type: "passage_cloze",
      prompt: "Ieri abbiamo fatto un'escursione in montagna. Siamo partiti all'alba, quando il cielo era ancora rosa e le stelle quasi visibili.\nIl sentiero saliva attraverso un bosco fitto di alberi altissimi. Le foglie cadevano lentamente e il profumo dell'erba bagnata era bellissimo.\nDopo due ore abbiamo raggiunto un piccolo lago di montagna, circondato da rocce grigie e neve.\nL'acqua era così limpida che si vedeva il fondo. In lontananza, il ___ scorreva giù nella valle verso il mare.\nÈ stata una giornata indimenticabile.",
      accepted: ["fiume"],
      hint: "a body of flowing water that runs down into a valley — not a lake or the sea",
      tags: ["nature", "passage_cloze", "vocabulary", "A2"],
      tier: 4,
      prerequisites: [
        "a225-t1-001",
        "a225-t1-003",
        "a225-t1-004",
        "a225-t1-005",
        "a225-t1-007",
        "a225-t1-009",
        "a225-t1-010",
        "a225-t1-011",
        "a225-t1-016",
        "a225-t1-017",
        "a225-t1-018",
        "a225-t1-020",
        "a225-t3-003",
      ],
    },
  ],
};
export default unit;
