import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-49-italian-history-ancient-medieval",
  name: "Rome and the Middle Ages",
  level: "B1",
  theme: "Italian History — Ancient & Medieval",
  emoji: "🏛️",
  prerequisiteUnits: [],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "b149-t1-001", type: "recognize", prompt: "fondare", accepted: ["to found", "to establish"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-002", type: "produce", prompt: "to found", accepted: ["fondare"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-003", type: "recognize", prompt: "la fondazione", accepted: ["the founding", "the foundation"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-004", type: "produce", prompt: "the founding", accepted: ["la fondazione"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-005", type: "recognize", prompt: "l'impero", accepted: ["the empire"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-006", type: "produce", prompt: "the empire", accepted: ["l'impero"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-007", type: "recognize", prompt: "l'imperatore", accepted: ["the emperor"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-008", type: "produce", prompt: "the emperor", accepted: ["l'imperatore"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-009", type: "recognize", prompt: "la repubblica", accepted: ["the republic"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-010", type: "produce", prompt: "the republic", accepted: ["la repubblica"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-011", type: "recognize", prompt: "conquistare", accepted: ["to conquer"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-012", type: "produce", prompt: "to conquer", accepted: ["conquistare"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-013", type: "recognize", prompt: "la conquista", accepted: ["the conquest"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-014", type: "produce", prompt: "the conquest", accepted: ["la conquista"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-015", type: "recognize", prompt: "crollare", accepted: ["to collapse"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-016", type: "produce", prompt: "to collapse", accepted: ["crollare"], hint: "verb, regular -are", tags: ["verb", "history", "vocab"], tier: 1 },
    { id: "b149-t1-017", type: "recognize", prompt: "il crollo", accepted: ["the collapse"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-018", type: "produce", prompt: "the collapse", accepted: ["il crollo"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-019", type: "recognize", prompt: "la caduta", accepted: ["the fall"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-020", type: "produce", prompt: "the fall", accepted: ["la caduta"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-021", type: "recognize", prompt: "il Medioevo", accepted: ["the Middle Ages"], hint: "noun, masculine, historical period", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-022", type: "produce", prompt: "the Middle Ages", accepted: ["il Medioevo"], hint: "noun, masculine, historical period", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-023", type: "recognize", prompt: "medievale", accepted: ["medieval"], hint: "adjective, invariable for gender", tags: ["adj", "history", "vocab"], tier: 1 },
    { id: "b149-t1-024", type: "produce", prompt: "medieval", accepted: ["medievale"], hint: "adjective, invariable for gender", tags: ["adj", "history", "vocab"], tier: 1 },
    { id: "b149-t1-025", type: "recognize", prompt: "la città-stato", accepted: ["the city-state"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-026", type: "produce", prompt: "the city-state", accepted: ["la città-stato"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-027", type: "recognize", prompt: "il comune", accepted: ["the commune", "the town council"], hint: "noun, masculine; medieval self-governing city", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-028", type: "produce", prompt: "the (medieval) commune", accepted: ["il comune"], hint: "noun, masculine; medieval self-governing city", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-029", type: "recognize", prompt: "il feudalesimo", accepted: ["feudalism"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-030", type: "produce", prompt: "feudalism", accepted: ["il feudalesimo"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-031", type: "recognize", prompt: "il feudo", accepted: ["the fief"], hint: "noun, masculine; land granted by a feudal lord", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-032", type: "produce", prompt: "the fief", accepted: ["il feudo"], hint: "noun, masculine; land granted by a feudal lord", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-033", type: "recognize", prompt: "il vassallo", accepted: ["the vassal"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-034", type: "produce", prompt: "the vassal", accepted: ["il vassallo"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-035", type: "recognize", prompt: "il senato", accepted: ["the senate"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-036", type: "produce", prompt: "the senate", accepted: ["il senato"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-037", type: "recognize", prompt: "la legione", accepted: ["the legion"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-038", type: "produce", prompt: "the legion", accepted: ["la legione"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-039", type: "recognize", prompt: "l'esercito", accepted: ["the army"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-040", type: "produce", prompt: "the army", accepted: ["l'esercito"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-041", type: "recognize", prompt: "il regno", accepted: ["the kingdom"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-042", type: "produce", prompt: "the kingdom", accepted: ["il regno"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-043", type: "recognize", prompt: "il barbaro", accepted: ["the barbarian"], hint: "noun, masculine; plural i barbari", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-044", type: "produce", prompt: "the barbarian", accepted: ["il barbaro"], hint: "noun, masculine; plural i barbari", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-045", type: "recognize", prompt: "l'invasione", accepted: ["the invasion"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-046", type: "produce", prompt: "the invasion", accepted: ["l'invasione"], hint: "noun, feminine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-047", type: "recognize", prompt: "il papa", accepted: ["the pope"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-048", type: "produce", prompt: "the pope", accepted: ["il papa"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-049", type: "recognize", prompt: "il cavaliere", accepted: ["the knight"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-050", type: "produce", prompt: "the knight", accepted: ["il cavaliere"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-051", type: "recognize", prompt: "il mercante", accepted: ["the merchant"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },
    { id: "b149-t1-052", type: "produce", prompt: "the merchant", accepted: ["il mercante"], hint: "noun, masculine", tags: ["noun", "history", "vocab"], tier: 1 },

    // ── Tier 2 – Grammar (passato remoto, for historical narration) ────────────
    { id: "b149-t2-001", type: "conjugate", prompt: "essere (passato remoto) – io", accepted: ["fui"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-002", type: "conjugate", prompt: "essere (passato remoto) – tu", accepted: ["fosti"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-003", type: "conjugate", prompt: "essere (passato remoto) – lui/lei", accepted: ["fu"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-004", type: "conjugate", prompt: "essere (passato remoto) – noi", accepted: ["fummo"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-005", type: "conjugate", prompt: "essere (passato remoto) – voi", accepted: ["foste"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-006", type: "conjugate", prompt: "essere (passato remoto) – loro", accepted: ["furono"], hint: "essere, passato remoto, irregular throughout", tags: ["passato-remoto", "essere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-007", type: "conjugate", prompt: "avere (passato remoto) – io", accepted: ["ebbi"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-008", type: "conjugate", prompt: "avere (passato remoto) – tu", accepted: ["avesti"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-009", type: "conjugate", prompt: "avere (passato remoto) – lui/lei", accepted: ["ebbe"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-010", type: "conjugate", prompt: "avere (passato remoto) – noi", accepted: ["avemmo"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-011", type: "conjugate", prompt: "avere (passato remoto) – voi", accepted: ["aveste"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-012", type: "conjugate", prompt: "avere (passato remoto) – loro", accepted: ["ebbero"], hint: "avere, passato remoto, irregular throughout", tags: ["passato-remoto", "avere", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-013", type: "conjugate", prompt: "fondare (passato remoto) – lui/lei", accepted: ["fondò"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-014", type: "conjugate", prompt: "fondare (passato remoto) – loro", accepted: ["fondarono"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-015", type: "conjugate", prompt: "conquistare (passato remoto) – lui/lei", accepted: ["conquistò"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-016", type: "conjugate", prompt: "conquistare (passato remoto) – loro", accepted: ["conquistarono"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-017", type: "conjugate", prompt: "cadere (passato remoto) – lui/lei", accepted: ["cadde"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-018", type: "conjugate", prompt: "cadere (passato remoto) – loro", accepted: ["caddero"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-019", type: "conjugate", prompt: "crollare (passato remoto) – lui/lei", accepted: ["crollò"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-020", type: "conjugate", prompt: "crollare (passato remoto) – loro", accepted: ["crollarono"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-021", type: "conjugate", prompt: "nascere (passato remoto) – lui/lei", accepted: ["nacque"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-022", type: "conjugate", prompt: "nascere (passato remoto) – loro", accepted: ["nacquero"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-023", type: "conjugate", prompt: "morire (passato remoto) – lui/lei", accepted: ["morì"], hint: "regular -ire passato remoto pattern", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-024", type: "conjugate", prompt: "morire (passato remoto) – loro", accepted: ["morirono"], hint: "regular -ire passato remoto pattern", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-025", type: "conjugate", prompt: "invadere (passato remoto) – lui/lei", accepted: ["invase"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-026", type: "conjugate", prompt: "invadere (passato remoto) – loro", accepted: ["invasero"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-027", type: "conjugate", prompt: "vincere (passato remoto) – lui/lei", accepted: ["vinse"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-028", type: "conjugate", prompt: "vincere (passato remoto) – loro", accepted: ["vinsero"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-029", type: "conjugate", prompt: "perdere (passato remoto) – lui/lei", accepted: ["perse"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-030", type: "conjugate", prompt: "perdere (passato remoto) – loro", accepted: ["persero"], hint: "irregular passato remoto", tags: ["passato-remoto", "history", "conjugation", "irregular"], tier: 2 },
    { id: "b149-t2-031", type: "conjugate", prompt: "diventare (passato remoto) – lui/lei", accepted: ["diventò"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-032", type: "conjugate", prompt: "diventare (passato remoto) – loro", accepted: ["diventarono"], hint: "regular -are passato remoto", tags: ["passato-remoto", "history", "conjugation"], tier: 2 },
    { id: "b149-t2-033", type: "fill_blank", prompt: "Romolo ___ (fondare) Roma secondo la leggenda, nel 753 avanti Cristo.", accepted: ["fondò"], hint: "passato remoto, lui/lei, fondare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-034", type: "fill_blank", prompt: "Giulio Cesare ___ (conquistare) gran parte della Gallia in pochi anni di guerra.", accepted: ["conquistò"], hint: "passato remoto, lui/lei, conquistare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-035", type: "fill_blank", prompt: "L'Impero Romano d'Occidente ___ (cadere) nel quattrocentosettantasei dopo Cristo.", accepted: ["cadde"], hint: "passato remoto, lui/lei, cadere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-036", type: "fill_blank", prompt: "Il governo centrale ___ (crollare) rapidamente dopo le continue invasioni barbariche.", accepted: ["crollò"], hint: "passato remoto, lui/lei, crollare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-037", type: "fill_blank", prompt: "L'imperatore Costantino ___ (nascere) in una provincia lontana dell'impero.", accepted: ["nacque"], hint: "passato remoto, lui/lei, nascere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-038", type: "fill_blank", prompt: "L'imperatore Augusto ___ (morire) dopo aver governato Roma per quarant'anni.", accepted: ["morì"], hint: "passato remoto, lui/lei, morire", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-039", type: "fill_blank", prompt: "I barbari ___ (invadere) il territorio romano più volte nel quinto secolo.", accepted: ["invasero"], hint: "passato remoto, loro, invadere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-040", type: "fill_blank", prompt: "Le legioni romane ___ (vincere) molte battaglie contro i nemici del nord.", accepted: ["vinsero"], hint: "passato remoto, loro, vincere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-041", type: "fill_blank", prompt: "L'esercito romano ___ (perdere) una battaglia importante contro i barbari in Germania.", accepted: ["perse"], hint: "passato remoto, lui/lei, perdere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-042", type: "fill_blank", prompt: "Con il tempo, Roma ___ (diventare) la città più potente del Mediterraneo.", accepted: ["diventò"], hint: "passato remoto, lui/lei, diventare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-043", type: "fill_blank", prompt: "Carlo Magno ___ (governare) un vasto regno per più di quarant'anni.", accepted: ["governò"], hint: "passato remoto, lui/lei, governare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-044", type: "fill_blank", prompt: "I romani ___ (costruire) strade e acquedotti in tutto l'impero.", accepted: ["costruirono"], hint: "passato remoto, loro, costruire (regular -ire)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-045", type: "fill_blank", prompt: "L'imperatore ___ (dividere) l'impero in due parti per governarlo meglio.", accepted: ["divise"], hint: "passato remoto, lui/lei, dividere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-046", type: "fill_blank", prompt: "Un re normanno ___ (unificare) diversi territori del sud Italia nel Medioevo.", accepted: ["unificò"], hint: "passato remoto, lui/lei, unificare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-047", type: "fill_blank", prompt: "La guerra tra le due città-stato ___ (scoppiare) per il controllo del porto.", accepted: ["scoppiò"], hint: "passato remoto, lui/lei, scoppiare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-048", type: "fill_blank", prompt: "Il dominio dei Longobardi ___ (durare) circa due secoli in Italia.", accepted: ["durò"], hint: "passato remoto, lui/lei, durare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-049", type: "fill_blank", prompt: "Dopo la morte del re, il figlio ___ (succedere) al trono senza problemi.", accepted: ["successe"], hint: "passato remoto, lui/lei, succedere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-050", type: "fill_blank", prompt: "Il nuovo imperatore ___ (regnare) con saggezza per oltre vent'anni.", accepted: ["regnò"], hint: "passato remoto, lui/lei, regnare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-051", type: "fill_blank", prompt: "L'esercito del comune ___ (sconfiggere) i cavalieri nemici fuori dalle mura.", accepted: ["sconfisse"], hint: "passato remoto, lui/lei, sconfiggere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-052", type: "fill_blank", prompt: "Le truppe ___ (attraversare) il confine all'alba, prima che la città si svegliasse.", accepted: ["attraversarono"], hint: "passato remoto, loro, attraversare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-053", type: "fill_blank", prompt: "Il senato romano ___ (scegliere) un nuovo console dopo la battaglia.", accepted: ["scelse"], hint: "passato remoto, lui/lei, scegliere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-054", type: "fill_blank", prompt: "I mercanti ___ (scoprire) nuove rotte commerciali durante il tardo Medioevo.", accepted: ["scoprirono"], hint: "passato remoto, loro, scoprire (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-055", type: "fill_blank", prompt: "Il papa ___ (incoronare) l'imperatore nella basilica, davanti a migliaia di persone.", accepted: ["incoronò"], hint: "passato remoto, lui/lei, incoronare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-056", type: "fill_blank", prompt: "Un vassallo ___ (tradire) il proprio signore feudale durante la guerra civile.", accepted: ["tradì"], hint: "passato remoto, lui/lei, tradire (regular -ire)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-057", type: "fill_blank", prompt: "La città-stato ___ (resistere) all'assedio per quasi un anno intero.", accepted: ["resistette"], hint: "passato remoto, lui/lei, resistere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-058", type: "fill_blank", prompt: "I cavalieri ___ (partire) per la crociata lasciando le loro famiglie a casa.", accepted: ["partirono"], hint: "passato remoto, loro, partire (regular -ire)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-059", type: "fill_blank", prompt: "Attila e i suoi guerrieri ___ (arrivare) fino alle porte di Roma.", accepted: ["arrivarono"], hint: "passato remoto, loro, arrivare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-060", type: "fill_blank", prompt: "Il vecchio imperatore ___ (scegliere) un giovane generale come suo successore.", accepted: ["scelse"], hint: "passato remoto, lui/lei, scegliere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-061", type: "fill_blank", prompt: "Il monastero ___ (diventare) un centro importante di cultura durante il Medioevo.", accepted: ["diventò"], hint: "passato remoto, lui/lei, diventare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-062", type: "fill_blank", prompt: "La popolazione della città ___ (crescere) rapidamente dopo la fine della guerra.", accepted: ["crebbe"], hint: "passato remoto, lui/lei, crescere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-063", type: "fill_blank", prompt: "Il comune ___ (ottenere) l'indipendenza dal signore feudale dopo anni di lotta.", accepted: ["ottenne"], hint: "passato remoto, lui/lei, ottenere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-064", type: "fill_blank", prompt: "I barbari ___ (saccheggiare) la città prima di ritirarsi verso nord.", accepted: ["saccheggiarono"], hint: "passato remoto, loro, saccheggiare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-065", type: "fill_blank", prompt: "Il re normanno ___ (sposare) una principessa per rafforzare la sua alleanza.", accepted: ["sposò"], hint: "passato remoto, lui/lei, sposare (regular -are)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },
    { id: "b149-t2-066", type: "fill_blank", prompt: "L'ultimo imperatore d'Occidente ___ (perdere) il trono senza opporre resistenza.", accepted: ["perse"], hint: "passato remoto, lui/lei, perdere (irregular)", tags: ["passato-remoto", "history", "fill_blank"], tier: 2 },

    // ── Tier 3 – Phrases & Collocations ─────────────────────────────────────
    { id: "b149-t3-001", type: "produce", prompt: "the founding of Rome", accepted: ["la fondazione di Roma"], hint: "fondazione + di + place", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-002", type: "produce", prompt: "to found a city", accepted: ["fondare una città"], hint: "fondare + object", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-003", type: "produce", prompt: "to found an empire", accepted: ["fondare un impero"], hint: "fondare + object", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-004", type: "produce", prompt: "an ancient empire", accepted: ["un antico impero"], hint: "adjective before noun for emphasis", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-005", type: "produce", prompt: "imperial power", accepted: ["il potere imperiale"], hint: "potere + adjective imperiale", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-006", type: "produce", prompt: "the emperor's palace", accepted: ["il palazzo dell'imperatore"], hint: "noun + di + noun possession", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-007", type: "produce", prompt: "to expand the empire", accepted: ["espandere l'impero"], hint: "espandere + object", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-008", type: "produce", prompt: "the empire's borders", accepted: ["i confini dell'impero"], hint: "plural noun + di + noun", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-009", type: "produce", prompt: "a powerful emperor", accepted: ["un imperatore potente"], hint: "noun + adjective", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-010", type: "produce", prompt: "the birth of an empire", accepted: ["la nascita di un impero"], hint: "nascita + di + noun", tags: ["chunk", "history", "empire"], tier: 3 },
    { id: "b149-t3-011", type: "produce", prompt: "the Roman Republic", accepted: ["la Repubblica Romana"], hint: "proper name, capitalized in Italian", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-012", type: "produce", prompt: "to elect a consul", accepted: ["eleggere un console"], hint: "eleggere + object", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-013", type: "produce", prompt: "the Roman senate", accepted: ["il senato romano"], hint: "noun + adjective romano", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-014", type: "produce", prompt: "a senate meeting", accepted: ["una seduta del senato"], hint: "seduta + del + noun", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-015", type: "produce", prompt: "the will of the senate", accepted: ["la volontà del senato"], hint: "volontà + del + noun", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-016", type: "produce", prompt: "republican institutions", accepted: ["le istituzioni repubblicane"], hint: "plural noun + adjective repubblicane", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-017", type: "produce", prompt: "to serve the republic", accepted: ["servire la repubblica"], hint: "servire + object", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-018", type: "produce", prompt: "senate power", accepted: ["il potere del senato"], hint: "potere + del + noun", tags: ["chunk", "history", "republic"], tier: 3 },
    { id: "b149-t3-019", type: "produce", prompt: "to occupy a territory", accepted: ["occupare un territorio"], hint: "occupare + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-020", type: "produce", prompt: "the Roman conquest of Gaul", accepted: ["la conquista romana della Gallia"], hint: "conquista + adjective + di + place", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-021", type: "produce", prompt: "to start a war", accepted: ["scatenare una guerra"], hint: "scatenare + object, to unleash/trigger", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-022", type: "produce", prompt: "to win a battle", accepted: ["vincere una battaglia"], hint: "vincere + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-023", type: "produce", prompt: "to lose a war", accepted: ["perdere una guerra"], hint: "perdere + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-024", type: "produce", prompt: "to lead an army", accepted: ["guidare un esercito"], hint: "guidare + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-025", type: "produce", prompt: "a bloody battle", accepted: ["una battaglia sanguinosa"], hint: "noun + adjective", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-026", type: "produce", prompt: "to cross the border", accepted: ["attraversare il confine"], hint: "attraversare + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-027", type: "produce", prompt: "an invading army", accepted: ["un esercito invasore"], hint: "noun + adjective invasore", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-028", type: "produce", prompt: "to conquer new lands", accepted: ["conquistare nuove terre"], hint: "conquistare + object", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-029", type: "produce", prompt: "a long war", accepted: ["una guerra lunga"], hint: "noun + adjective", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-030", type: "produce", prompt: "a decisive victory", accepted: ["una vittoria decisiva"], hint: "noun + adjective", tags: ["chunk", "history", "war"], tier: 3 },
    { id: "b149-t3-031", type: "produce", prompt: "the fall of the Roman Empire", accepted: ["la caduta dell'Impero Romano"], hint: "caduta + di + proper noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-032", type: "produce", prompt: "the collapse of the empire", accepted: ["il crollo dell'impero"], hint: "crollo + di + noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-033", type: "produce", prompt: "the barbarian invasions", accepted: ["le invasioni barbariche"], hint: "plural noun + adjective barbariche", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-034", type: "produce", prompt: "to fall into decline", accepted: ["cadere in declino"], hint: "cadere + in + noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-035", type: "produce", prompt: "the end of an era", accepted: ["la fine di un'epoca"], hint: "fine + di + noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-036", type: "produce", prompt: "political instability", accepted: ["l'instabilità politica"], hint: "noun + adjective politica", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-037", type: "produce", prompt: "the empire's decline", accepted: ["il declino dell'impero"], hint: "declino + di + noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-038", type: "produce", prompt: "to sack a city", accepted: ["saccheggiare una città"], hint: "saccheggiare + object", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-039", type: "produce", prompt: "the last emperor", accepted: ["l'ultimo imperatore"], hint: "adjective ultimo before noun", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-040", type: "produce", prompt: "a fallen empire", accepted: ["un impero caduto"], hint: "noun + past participle as adjective", tags: ["chunk", "history", "decline"], tier: 3 },
    { id: "b149-t3-041", type: "produce", prompt: "life in the Middle Ages", accepted: ["la vita nel Medioevo"], hint: "vita + nel + historical period", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-042", type: "produce", prompt: "a medieval castle", accepted: ["un castello medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-043", type: "produce", prompt: "a medieval city", accepted: ["una città medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-044", type: "produce", prompt: "an independent city-state", accepted: ["una città-stato indipendente"], hint: "noun + adjective indipendente", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-045", type: "produce", prompt: "the medieval commune", accepted: ["il comune medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-046", type: "produce", prompt: "medieval Italy", accepted: ["l'Italia medievale"], hint: "proper noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-047", type: "produce", prompt: "a walled city", accepted: ["una città murata"], hint: "noun + adjective murata", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-048", type: "produce", prompt: "medieval society", accepted: ["la società medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-049", type: "produce", prompt: "a medieval kingdom", accepted: ["un regno medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-050", type: "produce", prompt: "medieval trade routes", accepted: ["le rotte commerciali medievali"], hint: "plural noun + adjectives", tags: ["chunk", "history", "medieval"], tier: 3 },
    { id: "b149-t3-051", type: "produce", prompt: "the feudal system", accepted: ["il sistema feudale"], hint: "sistema + adjective feudale", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-052", type: "produce", prompt: "the rise of feudalism", accepted: ["l'ascesa del feudalesimo"], hint: "ascesa + del + noun", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-053", type: "produce", prompt: "to grant a fief", accepted: ["concedere un feudo"], hint: "concedere + object", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-054", type: "produce", prompt: "a feudal lord", accepted: ["un signore feudale"], hint: "noun + adjective feudale", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-055", type: "produce", prompt: "to swear loyalty", accepted: ["giurare fedeltà"], hint: "giurare + object, no article", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-056", type: "produce", prompt: "a vassal's duty", accepted: ["il dovere di un vassallo"], hint: "dovere + di + noun", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-057", type: "produce", prompt: "to serve one's lord", accepted: ["servire il proprio signore"], hint: "servire + possessive proprio", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-058", type: "produce", prompt: "feudal obligations", accepted: ["gli obblighi feudali"], hint: "plural noun + adjective feudali", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-059", type: "produce", prompt: "land and loyalty", accepted: ["terra e fedeltà"], hint: "two nouns joined by e", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-060", type: "produce", prompt: "to inherit a fief", accepted: ["ereditare un feudo"], hint: "ereditare + object", tags: ["chunk", "history", "feudalism"], tier: 3 },
    { id: "b149-t3-061", type: "produce", prompt: "the power of the pope", accepted: ["il potere del papa"], hint: "potere + del + noun", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-062", type: "produce", prompt: "to crown an emperor", accepted: ["incoronare un imperatore"], hint: "incoronare + object", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-063", type: "produce", prompt: "a medieval monastery", accepted: ["un monastero medievale"], hint: "noun + adjective medievale", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-064", type: "produce", prompt: "a life of prayer", accepted: ["una vita di preghiera"], hint: "vita + di + noun", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-065", type: "produce", prompt: "to join a monastery", accepted: ["entrare in un monastero"], hint: "entrare in + noun", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-066", type: "produce", prompt: "the pope's authority", accepted: ["l'autorità del papa"], hint: "autorità + del + noun", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-067", type: "produce", prompt: "a crusader knight", accepted: ["un cavaliere crociato"], hint: "noun + adjective crociato", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-068", type: "produce", prompt: "to go on crusade", accepted: ["partire per la crociata"], hint: "partire per + noun", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-069", type: "produce", prompt: "church and empire", accepted: ["la chiesa e l'impero"], hint: "two nouns joined by e", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-070", type: "produce", prompt: "a devout monk", accepted: ["un monaco devoto"], hint: "noun + adjective", tags: ["chunk", "history", "church"], tier: 3 },
    { id: "b149-t3-071", type: "produce", prompt: "a wealthy merchant", accepted: ["un mercante ricco"], hint: "noun + adjective", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-072", type: "produce", prompt: "to trade goods", accepted: ["commerciare merci"], hint: "commerciare + object", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-073", type: "produce", prompt: "a trade route", accepted: ["una rotta commerciale"], hint: "noun + adjective commerciale", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-074", type: "produce", prompt: "maritime trade", accepted: ["il commercio marittimo"], hint: "noun + adjective marittimo", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-075", type: "produce", prompt: "to found a trading post", accepted: ["fondare un porto commerciale"], hint: "fondare + object", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-076", type: "produce", prompt: "merchant ships", accepted: ["le navi mercantili"], hint: "plural noun + adjective mercantili", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-077", type: "produce", prompt: "a flourishing trade", accepted: ["un commercio fiorente"], hint: "noun + adjective fiorente", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-078", type: "produce", prompt: "commercial power", accepted: ["il potere commerciale"], hint: "potere + adjective commerciale", tags: ["chunk", "history", "trade"], tier: 3 },
    { id: "b149-t3-079", type: "produce", prompt: "a noble knight", accepted: ["un nobile cavaliere"], hint: "adjective before noun for emphasis", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-080", type: "produce", prompt: "to become a knight", accepted: ["diventare cavaliere"], hint: "diventare + profession, no article", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-081", type: "produce", prompt: "knightly honor", accepted: ["l'onore cavalleresco"], hint: "onore + adjective cavalleresco", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-082", type: "produce", prompt: "a suit of armor", accepted: ["un'armatura"], hint: "single noun, feminine", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-083", type: "produce", prompt: "a knight's sword", accepted: ["la spada di un cavaliere"], hint: "spada + di + noun", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-084", type: "produce", prompt: "to defend the castle", accepted: ["difendere il castello"], hint: "difendere + object", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-085", type: "produce", prompt: "noble blood", accepted: ["sangue nobile"], hint: "noun + adjective, no article in this fixed phrase", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-086", type: "produce", prompt: "a knight in service", accepted: ["un cavaliere al servizio"], hint: "al servizio (di)", tags: ["chunk", "history", "knights"], tier: 3 },
    { id: "b149-t3-087", type: "produce", prompt: "a Roman legion", accepted: ["una legione romana"], hint: "noun + adjective romana", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-088", type: "produce", prompt: "to command a legion", accepted: ["comandare una legione"], hint: "comandare + object", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-089", type: "produce", prompt: "a legionary soldier", accepted: ["un legionario"], hint: "single noun, masculine", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-090", type: "produce", prompt: "a disciplined army", accepted: ["un esercito disciplinato"], hint: "noun + adjective", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-091", type: "produce", prompt: "to march on Rome", accepted: ["marciare su Roma"], hint: "marciare su + place", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-092", type: "produce", prompt: "a border garrison", accepted: ["una guarnigione di confine"], hint: "guarnigione + di + noun", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-093", type: "produce", prompt: "imperial troops", accepted: ["le truppe imperiali"], hint: "plural noun + adjective imperiali", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-094", type: "produce", prompt: "to defend the territory", accepted: ["difendere il territorio"], hint: "difendere + object", tags: ["chunk", "history", "legion"], tier: 3 },
    { id: "b149-t3-095", type: "produce", prompt: "ancient history", accepted: ["la storia antica"], hint: "noun + adjective antica", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-096", type: "produce", prompt: "a historical era", accepted: ["un'epoca storica"], hint: "noun + adjective storica", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-097", type: "produce", prompt: "according to legend", accepted: ["secondo la leggenda"], hint: "secondo + noun, fixed expression", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-098", type: "produce", prompt: "throughout history", accepted: ["nel corso della storia"], hint: "fixed expression", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-099", type: "produce", prompt: "a turning point in history", accepted: ["una svolta nella storia"], hint: "svolta + in + noun", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-100", type: "produce", prompt: "to shape history", accepted: ["plasmare la storia"], hint: "plasmare + object", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-101", type: "produce", prompt: "a historical figure", accepted: ["una figura storica"], hint: "noun + adjective storica", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-102", type: "produce", prompt: "the ancient world", accepted: ["il mondo antico"], hint: "noun + adjective antico", tags: ["chunk", "history", "discourse"], tier: 3 },
    { id: "b149-t3-103", type: "produce", prompt: "a sudden invasion", accepted: ["un'invasione improvvisa"], hint: "noun + adjective improvvisa", tags: ["chunk", "history", "decline"], tier: 3 },

    // ── Tier 4 – Passage Cloze ───────────────────────────────────────────────
    {
      id: "b149-t4-001",
      type: "passage_cloze",
      prompt: "Secondo la leggenda, i due fratelli Romolo e Remo crebbero vicino al fiume Tevere, allevati da una lupa. Da adulti, i due litigarono per decidere dove costruire la nuova città. Alla fine Romolo ___ (fondare) Roma sulla collina del Palatino, nel 753 avanti Cristo, e diede alla città il proprio nome. Da quel piccolo villaggio nacque, secoli dopo, uno dei più grandi imperi della storia.",
      accepted: ["fondò"],
      hint: "passato remoto, lui/lei, fondare",
      tags: ["passage_cloze", "history", "empire"],
      tier: 4,
    },
    {
      id: "b149-t4-002",
      type: "passage_cloze",
      prompt: "Prima di diventare un impero, Roma fu per secoli una repubblica. Ogni anno i cittadini eleggevano due consoli che governavano insieme, così che nessuno avesse troppo potere. Il senato, formato dai membri delle famiglie più importanti, ___ (discutere) le leggi e le decisioni più delicate. Questo sistema durò quasi cinquecento anni, prima che le guerre civili portassero alla nascita dell'impero.",
      accepted: ["discuteva"],
      hint: "imperfetto, lui/lei, discutere; azione abituale nel passato",
      tags: ["passage_cloze", "history", "republic"],
      tier: 4,
    },
    {
      id: "b149-t4-003",
      type: "passage_cloze",
      prompt: "Giulio Cesare era uno dei generali più ambiziosi della Repubblica Romana. Nel giro di pochi anni ___ (conquistare) quasi tutta la Gallia, portando enormi ricchezze e nuovi territori a Roma. I suoi successi militari, però, spaventarono il senato, che temeva il suo potere crescente. Pochi anni dopo, Cesare fu assassinato proprio dai senatori che lo temevano di più.",
      accepted: ["conquistò"],
      hint: "passato remoto, lui/lei, conquistare",
      tags: ["passage_cloze", "history", "war"],
      tier: 4,
    },
    {
      id: "b149-t4-004",
      type: "passage_cloze",
      prompt: "Nel quinto secolo dopo Cristo, l'Impero Romano d'Occidente era ormai indebolito da decenni di guerre civili e crisi economiche. I popoli barbari, spinti da altre invasioni provenienti da est, attraversarono i confini sempre più spesso. Nel 476, il generale Odoacre depose l'ultimo imperatore e ___ (prendere) il controllo di Roma. Per molti storici, quella data segna la fine del mondo antico.",
      accepted: ["prese"],
      hint: "passato remoto, lui/lei, prendere",
      tags: ["passage_cloze", "history", "decline"],
      tier: 4,
    },
    {
      id: "b149-t4-005",
      type: "passage_cloze",
      prompt: "L'imperatore Costantino cambiò per sempre la storia dell'impero. Dopo una battaglia decisiva, decise di sostenere la religione cristiana, fino ad allora perseguitata. Anni dopo ___ (fondare) una nuova capitale a est, chiamata Costantinopoli, che sarebbe rimasta importante per altri mille anni. Grazie a lui, la chiesa cristiana ottenne un potere che non aveva mai avuto prima.",
      accepted: ["fondò"],
      hint: "passato remoto, lui/lei, fondare",
      tags: ["passage_cloze", "history", "church"],
      tier: 4,
    },
    {
      id: "b149-t4-006",
      type: "passage_cloze",
      prompt: "Durante il quarto e il quinto secolo, molti popoli barbari si spostarono verso l'Europa occidentale in cerca di terre più sicure. I Visigoti, spinti dagli Unni, ___ (invadere) l'Italia più volte, arrivando persino a saccheggiare Roma nel 410. Per gli abitanti dell'impero, ormai abituati a secoli di pace, quegli eventi sembravano la fine del mondo conosciuto.",
      accepted: ["invasero"],
      hint: "passato remoto, loro, invadere",
      tags: ["passage_cloze", "history", "decline"],
      tier: 4,
    },
    {
      id: "b149-t4-007",
      type: "passage_cloze",
      prompt: "Dopo la caduta dell'impero, l'Italia non fu più unita sotto un solo governo per molti secoli. Al loro posto nacquero decine di piccole città-stato, ognuna con le proprie leggi e il proprio esercito. Firenze, Venezia e Genova ___ (diventare) tra le più potenti, grazie soprattutto al commercio marittimo. Questa frammentazione politica avrebbe segnato la storia italiana fino all'Ottocento.",
      accepted: ["diventarono"],
      hint: "passato remoto, loro, diventare (regular -are)",
      tags: ["passage_cloze", "history", "medieval"],
      tier: 4,
    },
    {
      id: "b149-t4-008",
      type: "passage_cloze",
      prompt: "Nel Medioevo, molte città italiane si organizzarono come comuni, governati da consigli di cittadini invece che da un unico signore. Il comune di Milano, ad esempio, ___ (ottenere) importanti libertà dopo anni di lotta contro l'imperatore. I mercanti e gli artigiani, sempre più ricchi, iniziarono a partecipare direttamente alla vita politica della città. Con il tempo, questo nuovo equilibrio di potere cambiò per sempre i rapporti tra le città italiane e l'imperatore.",
      accepted: ["ottenne"],
      hint: "passato remoto, lui/lei, ottenere",
      tags: ["passage_cloze", "history", "medieval"],
      tier: 4,
    },
    {
      id: "b149-t4-009",
      type: "passage_cloze",
      prompt: "Nel sistema feudale, un signore concedeva un feudo, cioè un territorio, a un vassallo in cambio di fedeltà e servizio militare. Il vassallo ___ (giurare) fedeltà al proprio signore durante una cerimonia solenne, inginocchiandosi davanti a lui. In cambio, riceveva protezione e il diritto di sfruttare le terre ricevute. Questo scambio di doveri teneva insieme la società medievale.",
      accepted: ["giurava"],
      hint: "imperfetto, lui/lei, giurare; descrive una cerimonia tipica e ripetuta",
      tags: ["passage_cloze", "history", "feudalism"],
      tier: 4,
    },
    {
      id: "b149-t4-010",
      type: "passage_cloze",
      prompt: "I cavalieri medievali seguivano un codice d'onore che imponeva coraggio, lealtà e protezione dei più deboli. Quando il papa chiese aiuto per liberare i luoghi sacri, migliaia di cavalieri ___ (partire) per la prima crociata. Il viaggio fu lunghissimo e pericoloso, e molti di loro non fecero mai ritorno a casa. Chi sopravvisse portò in Europa nuove idee, nuove merci e un contatto più diretto con culture fino ad allora sconosciute.",
      accepted: ["partirono"],
      hint: "passato remoto, loro, partire",
      tags: ["passage_cloze", "history", "church"],
      tier: 4,
    },
    {
      id: "b149-t4-011",
      type: "passage_cloze",
      prompt: "I monasteri medievali non erano solo luoghi di preghiera, ma anche centri di cultura e di sapere. I monaci copiavano a mano antichi manoscritti, conservando testi che altrimenti sarebbero andati perduti. In un monastero del nord Italia, un giovane monaco ___ (dedicare) tutta la vita a questo lavoro paziente, senza mai vedere il risultato finale del proprio impegno.",
      accepted: ["dedicò"],
      hint: "passato remoto, lui/lei, dedicare",
      tags: ["passage_cloze", "history", "church"],
      tier: 4,
    },
    {
      id: "b149-t4-012",
      type: "passage_cloze",
      prompt: "Venezia divenne una delle repubbliche marinare più ricche del Medioevo grazie al commercio con l'Oriente. I suoi mercanti viaggiavano per mesi su navi cariche di spezie, seta e altri prodotti preziosi. Un mercante veneziano, dopo un lungo viaggio, ___ (tornare) in città con un carico che valeva una piccola fortuna. Storie come la sua resero Venezia famosa in tutta Europa.",
      accepted: ["tornò"],
      hint: "passato remoto, lui/lei, tornare",
      tags: ["passage_cloze", "history", "trade"],
      tier: 4,
    },
    {
      id: "b149-t4-013",
      type: "passage_cloze",
      prompt: "Nel Medioevo, il papa non era solo il capo della chiesa, ma anche una figura politica potente. La sera di Natale dell'ottocento, il papa ___ (incoronare) Carlo Magno come nuovo imperatore, davanti a una folla emozionata nella basilica di San Pietro. Quell'incoronazione segnò la nascita di un nuovo impero in Occidente. Da quel momento, i rapporti tra il potere religioso e quello politico rimasero intrecciati per secoli, influenzando ogni futuro sovrano europeo.",
      accepted: ["incoronò"],
      hint: "passato remoto, lui/lei, incoronare",
      tags: ["passage_cloze", "history", "church"],
      tier: 4,
    },
    {
      id: "b149-t4-014",
      type: "passage_cloze",
      prompt: "Le legioni romane erano famose per la loro disciplina e organizzazione. Ogni soldato si allenava per anni prima di poter combattere in battaglia. Durante una campagna in Germania, una legione intera ___ (perdere) quasi tutti i suoi uomini in un'imboscata nella foresta. La notizia sconvolse l'imperatore, che pianse per giorni la perdita di quei soldati.",
      accepted: ["perse"],
      hint: "passato remoto, lui/lei, perdere",
      tags: ["passage_cloze", "history", "legion"],
      tier: 4,
    },
    {
      id: "b149-t4-015",
      type: "passage_cloze",
      prompt: "I romani costruirono migliaia di chilometri di strade per collegare le città dell'impero. Grazie a queste vie, l'esercito ___ (potere) muoversi rapidamente da una regione all'altra in caso di guerra. Anche i mercanti e i viaggiatori usavano le stesse strade, che restarono in uso per secoli dopo la fine dell'impero. Ancora oggi, alcuni tratti di quelle antiche vie romane sono visibili nelle campagne italiane, testimonianza silenziosa di un'ingegneria straordinaria.",
      accepted: ["poteva"],
      hint: "imperfetto, lui/lei, potere; capacità continuativa nel passato",
      tags: ["passage_cloze", "history", "legion"],
      tier: 4,
    },
    {
      id: "b149-t4-016",
      type: "passage_cloze",
      prompt: "Nell'undicesimo secolo, alcuni cavalieri normanni arrivarono nel sud Italia in cerca di fortuna come mercenari. Con il tempo, questi guerrieri ___ (conquistare) l'intera regione, unificando territori che prima erano divisi tra diversi signori. Fondarono così un nuovo regno che sarebbe durato per secoli. Il nuovo regno unì popoli e tradizioni diverse, dai bizantini agli arabi, creando una cultura originale nel Mediterraneo. Ancora oggi, castelli e chiese normanne raccontano quella straordinaria stagione della storia siciliana.",
      accepted: ["conquistarono"],
      hint: "passato remoto, loro, conquistare",
      tags: ["passage_cloze", "history", "medieval"],
      tier: 4,
    },
    {
      id: "b149-t4-017",
      type: "passage_cloze",
      prompt: "L'imperatore Federico Barbarossa cercò più volte di riportare le città-stato italiane sotto il proprio controllo diretto. I comuni del nord Italia, però, si unirono in una lega per resistere insieme. Nella battaglia decisiva, l'esercito dei comuni ___ (sconfiggere) le truppe imperiali, difendendo la propria indipendenza. Quella vittoria rafforzò per sempre il potere dei comuni italiani.",
      accepted: ["sconfisse"],
      hint: "passato remoto, lui/lei, sconfiggere",
      tags: ["passage_cloze", "history", "medieval"],
      tier: 4,
    },
    {
      id: "b149-t4-018",
      type: "passage_cloze",
      prompt: "Attila, il temuto capo degli Unni, guidò il suo popolo attraverso l'Europa in cerca di ricchezze e territori. Il suo esercito ___ (arrivare) fino alle porte di Roma, seminando paura in tutto l'impero. Solo un incontro diplomatico con il papa convinse Attila a ritirarsi senza attaccare la città. Quell'incontro divenne leggendario, ricordato per secoli come un esempio raro in cui le parole fermarono un esercito invece delle armi.",
      accepted: ["arrivò"],
      hint: "passato remoto, lui/lei, arrivare",
      tags: ["passage_cloze", "history", "decline"],
      tier: 4,
    },
    {
      id: "b149-t4-019",
      type: "passage_cloze",
      prompt: "Negli ultimi secoli dell'impero, l'economia romana entrò in una crisi profonda. Le tasse aumentarono, il commercio rallentò e molte città persero abitanti. Un piccolo comune agricolo, un tempo prospero, ___ (diventare) quasi deserto in pochi decenni. Molti abitanti abbandonarono le proprie case in cerca di zone più sicure, lasciando dietro di sé campi coltivati per generazioni. Storie simili si ripeterono in tutto l'impero, fino al suo definitivo crollo.",
      accepted: ["diventò"],
      hint: "passato remoto, lui/lei, diventare (regular -are)",
      tags: ["passage_cloze", "history", "decline"],
      tier: 4,
    },
    {
      id: "b149-t4-020",
      type: "passage_cloze",
      prompt: "Guardando indietro, la storia italiana appare come un lungo susseguirsi di imperi, regni e città-stato. Roma fondò un impero che unificò per secoli gran parte del mondo conosciuto. Dopo la sua caduta, il Medioevo ___ (portare) un'Italia divisa tra comuni, signori feudali e potere papale. Solo molti secoli dopo, quella frammentazione avrebbe lasciato spazio a una nuova unità nazionale.",
      accepted: ["portò"],
      hint: "passato remoto, lui/lei, portare",
      tags: ["passage_cloze", "history", "medieval"],
      tier: 4,
    },
  ],
};
export default unit;
