import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-21-trapassato",
  name: "The Distant Past",
  level: "B1",
  theme: "Trapassato Prossimo",
  emoji: "📜",
  prerequisiteUnits: ["b1-unit-20-congiuntivo"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u21-t1-001",
      type: "recognize",
      prompt: "la storia",
      accepted: ["the story", "the history"],
      hint: "can mean both 'story' and 'history'",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-002",
      type: "produce",
      prompt: "the story (a narrative tale)",
      accepted: ["il racconto"],
      hint: "more specifically a short narrative",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-003",
      type: "produce",
      prompt: "the character (in a story)",
      accepted: ["il personaggio"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-004",
      type: "produce",
      prompt: "the beginning",
      accepted: ["l'inizio"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-005",
      type: "produce",
      prompt: "the end",
      accepted: ["la fine"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-006",
      type: "recognize",
      prompt: "poi",
      accepted: ["then", "afterwards", "next"],
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-007",
      type: "recognize",
      prompt: "dopo",
      accepted: ["after", "afterwards", "later"],
      tags: ["adverb", "preposition", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-008",
      type: "recognize",
      prompt: "infine",
      accepted: ["finally", "in the end", "at last"],
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-009",
      type: "recognize",
      prompt: "alla fine",
      accepted: ["in the end", "at the end", "finally"],
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-010",
      type: "recognize",
      prompt: "nel frattempo",
      accepted: ["meanwhile", "in the meantime"],
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-011",
      type: "produce",
      prompt: "the event",
      accepted: ["l'evento"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-012",
      type: "recognize",
      prompt: "già",
      accepted: ["already", "yet"],
      hint: "used to indicate something completed before another action",
      tags: ["adverb", "trapassato", "sequencing"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ────────────────────────────────────────────────────
    {
      id: "u21-t2-001",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – io",
      accepted: ["avevo mangiato"],
      hint: "avere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-002",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (maschile)",
      accepted: ["ero andato"],
      hint: "essere in imperfetto + participio passato; accordo con soggetto",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-003",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (femminile)",
      accepted: ["ero andata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-004",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – tu",
      accepted: ["avevi visto"],
      hint: "avere in imperfetto (avevi) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-005",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – lui/lei",
      accepted: ["aveva fatto"],
      hint: "avere in imperfetto (aveva) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-006",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – noi",
      accepted: ["eravamo partiti"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-007",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – lui/lei",
      accepted: ["aveva finito"],
      hint: "avere in imperfetto (aveva) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-008",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – loro",
      accepted: ["erano arrivati"],
      hint: "essere in imperfetto + participio; plurale",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u21-t3-001",
      type: "produce",
      prompt: "He had already finished when she arrived.",
      accepted: ["Aveva già finito quando lei è arrivata.", "Aveva già finito quando è arrivata."],
      hint: "trapassato + già + quando + passato prossimo",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-002",
      type: "produce",
      prompt: "After we had left, it started to rain.",
      accepted: ["Dopo che eravamo partiti, ha cominciato a piovere.", "Dopo che eravamo partiti, è cominciato a piovere."],
      hint: "Dopo che + trapassato, passato prossimo",
      tags: ["trapassato-prossimo", "chunk", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-003",
      type: "produce",
      prompt: "I had never seen such a beautiful story.",
      accepted: ["Non avevo mai visto una storia così bella.", "Non avevo mai visto un racconto così bello."],
      hint: "non + trapassato + mai",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-004",
      type: "fill_blank",
      prompt: "As soon as the character ___ (arrivare, trapassato, lui) at the beginning, the story changed.",
      accepted: ["era arrivato"],
      hint: "appena + trapassato with essere",
      tags: ["trapassato-prossimo", "fill-blank", "appena"],
      tier: 3,
    },
    {
      id: "u21-t3-005",
      type: "fill_blank",
      prompt: "Meanwhile, she had already read the end of the story: aveva già ___ la fine della storia.",
      accepted: ["letto"],
      hint: "participio passato irregolare di 'leggere'",
      tags: ["trapassato-prossimo", "fill-blank", "irregular-participle"],
      tier: 3,
    },
    {
      id: "u21-t3-006",
      type: "produce",
      prompt: "He had done everything before the event.",
      accepted: ["Aveva fatto tutto prima dell'evento.", "Aveva fatto tutto prima dell'evento."],
      hint: "trapassato di 'fare' + prima di",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },

    // ── Tier 4 – Sentences & Passages ───────────────────────────────────────
    {
      id: "u21-t4-001",
      type: "produce",
      prompt: "When I arrived at the end of the story, I had already understood the character.",
      accepted: [
        "Quando sono arrivato alla fine della storia, avevo già capito il personaggio.",
        "Quando sono arrivata alla fine della storia, avevo già capito il personaggio.",
      ],
      hint: "passato prossimo for the arrival; trapassato for the earlier understanding",
      tags: ["trapassato-prossimo", "sentence", "sequencing"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-003", "u21-t1-005", "u21-t1-012", "u21-t2-001"],
    },
    {
      id: "u21-t4-002",
      type: "fill_blank",
      prompt: "Dopo che il personaggio ___ (partire, trapassato, lui) dalla città, la storia è diventata più interessante.",
      accepted: ["era partito"],
      hint: "essere in imperfetto + participio passato di 'partire'",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 4,
      prerequisites: ["u21-t1-003", "u21-t1-007", "u21-t2-006"],
    },
    {
      id: "u21-t4-003",
      type: "passage_cloze",
      prompt: "Marco aprì il libro e cominciò a leggere il racconto dall'inizio.\nIl personaggio principale era un giovane che non aveva mai viaggiato lontano dalla sua città.\nMa quella mattina tutto era cambiato: qualcuno gli aveva dato una mappa misteriosa.\nMarco si rese conto che il personaggio ___ già la risposta, ma non lo sapeva ancora.\nAlla fine del primo capitolo, la storia era diventata impossibile da lasciare.",
      accepted: ["aveva trovato", "aveva capito"],
      hint: "trapassato prossimo con avere – lui/lei",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-009", "u21-t2-005", "u21-t2-007"],
    },
    {
      id: "u21-t4-004",
      type: "passage_cloze",
      prompt: "Era una sera tranquilla quando Giulia decise di scrivere la fine del suo racconto.\nNel frattempo, il suo personaggio preferito aveva già perso tutto ciò che possedeva.\nDopo che la protagonista ___ dall'ultima città, non era rimasto più niente.\nPoi, inaspettatamente, un nuovo personaggio era apparso all'inizio del terzo capitolo.\nInfone, Giulia capì che la storia non era ancora finita.",
      accepted: ["era partita"],
      hint: "essere in imperfetto + participio di 'partire'; soggetto femminile",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-006", "u21-t1-008", "u21-t1-010", "u21-t2-006"],
    },
    {
      id: "u21-t4-005",
      type: "produce",
      prompt: "In the end, we had already seen the beginning and the end of the story before the event started.",
      accepted: [
        "Alla fine, avevamo già visto l'inizio e la fine della storia prima che l'evento cominciasse.",
        "Alla fine, avevamo già visto l'inizio e la fine del racconto prima che l'evento cominciasse.",
      ],
      hint: "trapassato + già; 'prima che' triggers congiuntivo",
      tags: ["trapassato-prossimo", "sentence", "sequencing", "congiuntivo"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-004", "u21-t1-005", "u21-t1-009", "u21-t1-011", "u21-t1-012", "u21-t2-004"],
    },

    // ── Tier 1 additions – narrative & sequencing vocabulary (2026-08-01 expansion) ──
    {
      id: "u21-t1-013",
      type: "recognize",
      prompt: "non appena",
      accepted: ["as soon as"],
      hint: "used right before trapassato prossimo to mark an action just completed",
      tags: ["conjunction", "trapassato", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-014",
      type: "recognize",
      prompt: "mai",
      accepted: ["never", "ever"],
      hint: "used with non...mai to mean 'never'",
      tags: ["adverb", "trapassato", "negation"],
      tier: 1,
    },
    {
      id: "u21-t1-015",
      type: "recognize",
      prompt: "ancora",
      accepted: ["still", "yet"],
      hint: "non...ancora = not yet",
      tags: ["adverb", "trapassato", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-016",
      type: "produce",
      prompt: "the chapter",
      accepted: ["il capitolo"],
      hint: "used to divide a racconto or romanzo",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-017",
      type: "produce",
      prompt: "the plot",
      accepted: ["la trama"],
      hint: "the sequence of events in a story",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-018",
      type: "produce",
      prompt: "the writer",
      accepted: ["lo scrittore", "la scrittrice"],
      hint: "masculine/feminine forms, from scrivere",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-019",
      type: "produce",
      prompt: "the narrator",
      accepted: ["il narratore", "la narratrice"],
      hint: "the voice telling la storia",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-020",
      type: "recognize",
      prompt: "accadere",
      accepted: ["to happen", "to occur"],
      hint: "impersonal verb, takes essere: è accaduto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-021",
      type: "recognize",
      prompt: "succedere",
      accepted: ["to happen"],
      hint: "impersonal verb, takes essere: è successo",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-022",
      type: "recognize",
      prompt: "ricordare",
      accepted: ["to remember"],
      hint: "regular -are verb, takes avere",
      tags: ["verb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-023",
      type: "produce",
      prompt: "to forget",
      accepted: ["dimenticare"],
      hint: "regular -are verb, takes avere",
      tags: ["verb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-024",
      type: "recognize",
      prompt: "rendersi conto",
      accepted: ["to realize"],
      hint: "reflexive; trapassato: mi ero reso conto",
      tags: ["verb", "narrative", "vocabulary", "reflexive"],
      tier: 1,
    },
    {
      id: "u21-t1-025",
      type: "produce",
      prompt: "to discover",
      accepted: ["scoprire"],
      hint: "irregular participio passato: scoperto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-026",
      type: "produce",
      prompt: "the discovery",
      accepted: ["la scoperta"],
      hint: "noun from scoprire",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-027",
      type: "recognize",
      prompt: "improvvisamente",
      accepted: ["suddenly"],
      hint: "marks an unexpected event breaking the narrative flow",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-028",
      type: "recognize",
      prompt: "finalmente",
      accepted: ["finally", "at last"],
      hint: "different from alla fine — marks relief, not just sequence",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-029",
      type: "recognize",
      prompt: "purtroppo",
      accepted: ["unfortunately"],
      hint: "introduces an unwelcome outcome",
      tags: ["adverb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-030",
      type: "produce",
      prompt: "the surprise",
      accepted: ["la sorpresa"],
      hint: "from sorprendere",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-031",
      type: "produce",
      prompt: "the secret",
      accepted: ["il segreto"],
      hint: "collocation: nascondere un segreto",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-032",
      type: "recognize",
      prompt: "nascondere",
      accepted: ["to hide"],
      hint: "irregular participio passato: nascosto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-033",
      type: "produce",
      prompt: "the past",
      accepted: ["il passato"],
      hint: "il tempo che precede il presente",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-034",
      type: "produce",
      prompt: "the scene",
      accepted: ["la scena"],
      hint: "a specific moment within a story",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },

    // ── Tier 2 additions – expanded conjugation drills (2026-08-01 expansion) ──
    {
      id: "u21-t2-009",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – tu",
      accepted: ["avevi mangiato"],
      hint: "avere in imperfetto (avevi) + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-010",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – lui/lei",
      accepted: ["aveva mangiato"],
      hint: "avere in imperfetto (aveva) + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-011",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – noi",
      accepted: ["avevamo mangiato"],
      hint: "avere in imperfetto (avevamo) + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-012",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – voi",
      accepted: ["avevate mangiato"],
      hint: "avere in imperfetto (avevate) + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-013",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – loro",
      accepted: ["avevano mangiato"],
      hint: "avere in imperfetto (avevano) + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-014",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – io",
      accepted: ["avevo visto"],
      hint: "avere in imperfetto (avevo) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-015",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – lui/lei",
      accepted: ["aveva visto"],
      hint: "avere in imperfetto (aveva) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-016",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – noi",
      accepted: ["avevamo visto"],
      hint: "avere in imperfetto (avevamo) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-017",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – voi",
      accepted: ["avevate visto"],
      hint: "avere in imperfetto (avevate) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-018",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – loro",
      accepted: ["avevano visto"],
      hint: "avere in imperfetto (avevano) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-019",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – io",
      accepted: ["avevo fatto"],
      hint: "avere in imperfetto (avevo) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-020",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – tu",
      accepted: ["avevi fatto"],
      hint: "avere in imperfetto (avevi) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-021",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – noi",
      accepted: ["avevamo fatto"],
      hint: "avere in imperfetto (avevamo) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-022",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – voi",
      accepted: ["avevate fatto"],
      hint: "avere in imperfetto (avevate) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-023",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – loro",
      accepted: ["avevano fatto"],
      hint: "avere in imperfetto (avevano) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-024",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – io",
      accepted: ["avevo finito"],
      hint: "avere in imperfetto (avevo) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-025",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – tu",
      accepted: ["avevi finito"],
      hint: "avere in imperfetto (avevi) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-026",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – noi",
      accepted: ["avevamo finito"],
      hint: "avere in imperfetto (avevamo) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-027",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – voi",
      accepted: ["avevate finito"],
      hint: "avere in imperfetto (avevate) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-028",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – loro",
      accepted: ["avevano finito"],
      hint: "avere in imperfetto (avevano) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-029",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – tu (maschile)",
      accepted: ["eri andato"],
      hint: "essere in imperfetto + participio passato; accordo con soggetto",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-030",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – tu (femminile)",
      accepted: ["eri andata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-031",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – lui",
      accepted: ["era andato"],
      hint: "essere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-032",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – lei",
      accepted: ["era andata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-033",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo andati"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-034",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – loro (maschile)",
      accepted: ["erano andati"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-035",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – io (maschile)",
      accepted: ["ero partito"],
      hint: "essere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-036",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – io (femminile)",
      accepted: ["ero partita"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-037",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – lui",
      accepted: ["era partito"],
      hint: "essere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-038",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – voi (maschile)",
      accepted: ["eravate partiti"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-039",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – io (maschile)",
      accepted: ["ero arrivato"],
      hint: "essere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-040",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – tu (femminile)",
      accepted: ["eri arrivata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-041",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – lei",
      accepted: ["era arrivata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-042",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo arrivati"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-043",
      type: "conjugate",
      prompt: "scrivere (trapassato prossimo) – io",
      accepted: ["avevo scritto"],
      hint: "avere in imperfetto (avevo) + participio irregolare: scritto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-044",
      type: "conjugate",
      prompt: "dire (trapassato prossimo) – lui/lei",
      accepted: ["aveva detto"],
      hint: "avere in imperfetto (aveva) + participio irregolare: detto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-045",
      type: "conjugate",
      prompt: "leggere (trapassato prossimo) – noi",
      accepted: ["avevamo letto"],
      hint: "avere in imperfetto (avevamo) + participio irregolare: letto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-046",
      type: "conjugate",
      prompt: "prendere (trapassato prossimo) – loro",
      accepted: ["avevano preso"],
      hint: "avere in imperfetto (avevano) + participio irregolare: preso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-047",
      type: "conjugate",
      prompt: "mettere (trapassato prossimo) – tu",
      accepted: ["avevi messo"],
      hint: "avere in imperfetto (avevi) + participio irregolare: messo",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-048",
      type: "conjugate",
      prompt: "aprire (trapassato prossimo) – io",
      accepted: ["avevo aperto"],
      hint: "avere in imperfetto (avevo) + participio irregolare: aperto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-049",
      type: "conjugate",
      prompt: "chiudere (trapassato prossimo) – lei",
      accepted: ["aveva chiuso"],
      hint: "avere in imperfetto (aveva) + participio irregolare: chiuso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-050",
      type: "conjugate",
      prompt: "decidere (trapassato prossimo) – loro",
      accepted: ["avevano deciso"],
      hint: "avere in imperfetto (avevano) + participio irregolare: deciso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-051",
      type: "conjugate",
      prompt: "rompere (trapassato prossimo) – io",
      accepted: ["avevo rotto"],
      hint: "avere in imperfetto (avevo) + participio irregolare: rotto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-052",
      type: "conjugate",
      prompt: "perdere (trapassato prossimo) – tu",
      accepted: ["avevi perso"],
      hint: "avere in imperfetto (avevi) + participio irregolare: perso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-053",
      type: "conjugate",
      prompt: "rispondere (trapassato prossimo) – lui",
      accepted: ["aveva risposto"],
      hint: "avere in imperfetto (aveva) + participio irregolare: risposto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-054",
      type: "conjugate",
      prompt: "chiedere (trapassato prossimo) – noi",
      accepted: ["avevamo chiesto"],
      hint: "avere in imperfetto (avevamo) + participio irregolare: chiesto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-055",
      type: "conjugate",
      prompt: "offrire (trapassato prossimo) – voi",
      accepted: ["avevate offerto"],
      hint: "avere in imperfetto (avevate) + participio irregolare: offerto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-056",
      type: "conjugate",
      prompt: "nascondere (trapassato prossimo) – loro",
      accepted: ["avevano nascosto"],
      hint: "avere in imperfetto (avevano) + participio irregolare: nascosto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-057",
      type: "conjugate",
      prompt: "scoprire (trapassato prossimo) – io",
      accepted: ["avevo scoperto"],
      hint: "avere in imperfetto (avevo) + participio irregolare: scoperto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-058",
      type: "conjugate",
      prompt: "nascere (trapassato prossimo) – lui",
      accepted: ["era nato"],
      hint: "essere in imperfetto (era) + participio irregolare: nato",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-059",
      type: "conjugate",
      prompt: "morire (trapassato prossimo) – lei",
      accepted: ["era morta"],
      hint: "essere in imperfetto (era) + participio irregolare accordato: morta",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-060",
      type: "conjugate",
      prompt: "venire (trapassato prossimo) – io (maschile)",
      accepted: ["ero venuto"],
      hint: "essere in imperfetto (ero) + participio irregolare: venuto",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-061",
      type: "conjugate",
      prompt: "rimanere (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo rimasti"],
      hint: "essere in imperfetto (eravamo) + participio irregolare: rimasti",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-062",
      type: "conjugate",
      prompt: "scendere (trapassato prossimo) – tu (femminile)",
      accepted: ["eri scesa"],
      hint: "essere in imperfetto (eri) + participio irregolare accordato: scesa",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-063",
      type: "conjugate",
      prompt: "diventare (trapassato prossimo) – loro (maschile)",
      accepted: ["erano diventati"],
      hint: "essere in imperfetto (erano) + participio regolare: diventati",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-064",
      type: "conjugate",
      prompt: "tornare (trapassato prossimo) – voi (femminile)",
      accepted: ["eravate tornate"],
      hint: "essere in imperfetto (eravate) + participio regolare accordato: tornate",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-065",
      type: "conjugate",
      prompt: "ricordare (trapassato prossimo) – io",
      accepted: ["avevo ricordato"],
      hint: "avere in imperfetto (avevo) + participio regolare: ricordato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-066",
      type: "conjugate",
      prompt: "dimenticare (trapassato prossimo) – lei",
      accepted: ["aveva dimenticato"],
      hint: "avere in imperfetto (aveva) + participio regolare: dimenticato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },

    // ── Tier 3 additions – deeper chunks & phrases (2026-08-01 expansion) ──
    {
      id: "u21-t3-007",
      type: "produce",
      prompt: "By the time the narrator arrived, the writer had already left.",
      accepted: ["Quando il narratore è arrivato, lo scrittore era già partito.", "Quando il narratore è arrivato, la scrittrice era già partita."],
      hint: "trapassato per l'azione anteriore (partire, essere)",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-008",
      type: "fill_blank",
      prompt: "Non appena Marco ___ (scoprire, trapassato, lui) il segreto, ha capito tutta la trama.",
      accepted: ["aveva scoperto"],
      hint: "non appena + trapassato con avere",
      tags: ["trapassato-prossimo", "fill-blank", "non-appena"],
      tier: 3,
    },
    {
      id: "u21-t3-009",
      type: "produce",
      prompt: "She had never read that chapter before.",
      accepted: ["Non aveva mai letto quel capitolo prima.", "Non aveva mai letto quel capitolo prima d'ora."],
      hint: "non + trapassato + mai",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-010",
      type: "fill_blank",
      prompt: "Dopo mesi di dubbi, Paolo e Chiara ___ (decidere, trapassato, loro) già di cambiare vita prima di conoscere quella storia.",
      accepted: ["avevano deciso"],
      hint: "dopo mesi di... + trapassato con avere, plurale",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-011",
      type: "produce",
      prompt: "We had already forgotten the beginning of the plot.",
      accepted: ["Avevamo già dimenticato l'inizio della trama."],
      hint: "trapassato di dimenticare + già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-012",
      type: "fill_blank",
      prompt: "Quando è arrivata la sorpresa, il personaggio ___ (capire, trapassato, lui) già tutto.",
      accepted: ["aveva capito"],
      hint: "quando + passato prossimo, trapassato per l'anteriorità",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-013",
      type: "produce",
      prompt: "He had hidden the secret before the writer's discovery.",
      accepted: ["Aveva nascosto il segreto prima della scoperta dello scrittore."],
      hint: "trapassato di nascondere + prima di + nome",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-014",
      type: "fill_blank",
      prompt: "Purtroppo, quando siamo arrivati, il narratore ___ (andare, trapassato, lui) via.",
      accepted: ["era andato"],
      hint: "essere in imperfetto + participio; purtroppo introduce un esito negativo",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-015",
      type: "produce",
      prompt: "By the time she realized the truth, the story had already changed.",
      accepted: ["Quando si è resa conto della verità, la storia era già cambiata."],
      hint: "rendersi conto al passato prossimo + trapassato per il cambiamento anteriore",
      tags: ["trapassato-prossimo", "chunk", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-016",
      type: "fill_blank",
      prompt: "Il personaggio si ___ (rendersi conto, trapassato, lui) del segreto solo alla fine.",
      accepted: ["era reso conto"],
      hint: "rendersi conto è riflessivo: essere + reso/a conto",
      tags: ["trapassato-prossimo", "fill-blank", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-017",
      type: "produce",
      prompt: "The scene had already happened before the beginning of the chapter.",
      accepted: ["La scena era già accaduta prima dell'inizio del capitolo."],
      hint: "accadere è impersonale, prende essere; accordo con la scena (f)",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-018",
      type: "fill_blank",
      prompt: "Non capivo cosa ___ (succedere, trapassato, esso) la sera prima.",
      accepted: ["era successo"],
      hint: "succedere prende essere: era successo",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-019",
      type: "produce",
      prompt: "Finally, the writer understood what had happened.",
      accepted: ["Finalmente lo scrittore ha capito cosa era successo."],
      hint: "finalmente + passato prossimo + trapassato nella subordinata",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-020",
      type: "fill_blank",
      prompt: "Dopo che il narratore ___ (finire, trapassato, lui) il racconto, tutti hanno applaudito.",
      accepted: ["aveva finito"],
      hint: "dopo che + trapassato, poi passato prossimo",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-021",
      type: "produce",
      prompt: "I had already opened the book when the surprise happened.",
      accepted: ["Avevo già aperto il libro quando è successa la sorpresa."],
      hint: "trapassato di aprire + già; quando + passato prossimo",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-022",
      type: "fill_blank",
      prompt: "La sorpresa ___ (accadere, trapassato, essa) improvvisamente, senza nessun segno prima.",
      accepted: ["era accaduta"],
      hint: "accadere prende essere; accordo con la sorpresa (f)",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-023",
      type: "produce",
      prompt: "They had written three chapters before the surprise ending.",
      accepted: ["Avevano scritto tre capitoli prima del finale a sorpresa."],
      hint: "trapassato di scrivere + prima di",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-024",
      type: "fill_blank",
      prompt: "Non appena ho letto la trama, ho capito che l'autore ___ (nascondere, trapassato, lui) un segreto.",
      accepted: ["aveva nascosto"],
      hint: "trapassato con avere: participio nascosto",
      tags: ["trapassato-prossimo", "fill-blank", "non-appena"],
      tier: 3,
    },
    {
      id: "u21-t3-025",
      type: "produce",
      prompt: "She had lost the notebook before writing the last chapter.",
      accepted: ["Aveva perso il quaderno prima di scrivere l'ultimo capitolo."],
      hint: "trapassato di perdere + prima di + infinito",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-026",
      type: "fill_blank",
      prompt: "Quando il libro è finito, io ___ (dimenticare, trapassato, io) già il nome del narratore.",
      accepted: ["avevo dimenticato"],
      hint: "trapassato con avere: dimenticare regolare",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-027",
      type: "produce",
      prompt: "In the end, we had already read the whole plot twice.",
      accepted: ["Alla fine, avevamo già letto tutta la trama due volte."],
      hint: "trapassato di leggere + già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-028",
      type: "fill_blank",
      prompt: "Il segreto ___ (rimanere, trapassato, lui) nascosto per molti anni.",
      accepted: ["era rimasto"],
      hint: "rimanere prende essere: era rimasto",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-029",
      type: "fill_blank",
      prompt: "Nel passato, quella grande scoperta ___ (cambiare, trapassato, essa) già tutta la trama del racconto.",
      accepted: ["aveva cambiato"],
      hint: "trapassato con avere; il participio resta invariato (aveva cambiato) — nessun accordo di genere con avere",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-030",
      type: "produce",
      prompt: "Unfortunately, the writer had already died before finishing the last chapter.",
      accepted: ["Purtroppo lo scrittore era già morto prima di finire l'ultimo capitolo."],
      hint: "morire prende essere: era morto",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-031",
      type: "produce",
      prompt: "The narrator had never said such an important secret before.",
      accepted: ["Il narratore non aveva mai detto un segreto così importante."],
      hint: "non + trapassato + mai; dire → detto",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-032",
      type: "fill_blank",
      prompt: "Ancora non ___ (capire, trapassato, noi) la trama, quando è arrivata la sorpresa finale.",
      accepted: ["avevamo capito"],
      hint: "ancora non + trapassato",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-033",
      type: "produce",
      prompt: "He had already become a famous writer before that book.",
      accepted: ["Era già diventato uno scrittore famoso prima di quel libro."],
      hint: "trapassato di diventare + già",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-034",
      type: "fill_blank",
      prompt: "Quando sono tornato al capitolo precedente, mi sono reso conto che ___ (perdere, trapassato, io) un dettaglio importante.",
      accepted: ["avevo perso"],
      hint: "trapassato con avere: perdere → perso",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-035",
      type: "produce",
      prompt: "By the time she came back, everyone had already left the scene.",
      accepted: ["Quando è tornata, tutti erano già andati via dalla scena."],
      hint: "quando + passato prossimo, trapassato per l'anteriorità",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-036",
      type: "fill_blank",
      prompt: "Il narratore ha spiegato tutto quello che ___ (accadere, trapassato, esso) nel passato.",
      accepted: ["era accaduto"],
      hint: "accadere è impersonale, sempre alla 3a persona con essere",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-037",
      type: "produce",
      prompt: "Unfortunately, they had already forgotten the secret before the end.",
      accepted: ["Purtroppo avevano già dimenticato il segreto prima della fine."],
      hint: "purtroppo + trapassato + già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-038",
      type: "fill_blank",
      prompt: "Il personaggio principale ___ (nascere, trapassato, lui) molto tempo prima degli eventi del racconto.",
      accepted: ["era nato"],
      hint: "nascere prende essere: era nato",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-039",
      type: "produce",
      prompt: "As soon as I had remembered the scene, I understood the whole secret.",
      accepted: ["Non appena mi ero ricordato della scena, ho capito tutto il segreto."],
      hint: "non appena + trapassato riflessivo con essere",
      tags: ["trapassato-prossimo", "chunk", "non-appena", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-040",
      type: "fill_blank",
      prompt: "Prima di quella sera, il narratore non ___ (dire, trapassato, lui) mai il segreto a nessuno.",
      accepted: ["aveva detto"],
      hint: "non...mai + trapassato",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-041",
      type: "produce",
      prompt: "The scene had already ended when the surprise arrived.",
      accepted: ["La scena era già finita quando è arrivata la sorpresa."],
      hint: "finire intransitivo prende essere quando il soggetto è la cosa che finisce",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-042",
      type: "fill_blank",
      prompt: "Il lettore si è chiesto se il narratore ___ (dire, trapassato, lui) tutta la verità.",
      accepted: ["aveva detto"],
      hint: "se + trapassato (indicativo, uso comune informale)",
      tags: ["trapassato-prossimo", "fill-blank", "dubbio"],
      tier: 3,
    },
    {
      id: "u21-t3-043",
      type: "produce",
      prompt: "We had already discussed the plot before reading the last chapter.",
      accepted: ["Avevamo già discusso la trama prima di leggere l'ultimo capitolo."],
      hint: "trapassato di discutere + già + prima di + infinito",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-044",
      type: "fill_blank",
      prompt: "Quando il narratore ha chiuso il libro, il lettore ___ (capire, trapassato, lui) finalmente tutta la trama.",
      accepted: ["aveva capito"],
      hint: "quando + passato prossimo, trapassato per la comprensione anteriore",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-045",
      type: "produce",
      prompt: "By the time the writer revealed the ending, we had already guessed the secret.",
      accepted: ["Quando lo scrittore ha rivelato il finale, avevamo già indovinato il segreto."],
      hint: "trapassato di indovinare + già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-046",
      type: "fill_blank",
      prompt: "Prima di quel capitolo, il personaggio non ___ (scendere, trapassato, lui) mai in quella scena.",
      accepted: ["era sceso"],
      hint: "scendere prende essere: era sceso",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },

    // ── Tier 4 additions – narrative passage_cloze mini-stories (2026-08-01 expansion) ──
    {
      id: "u21-t4-006",
      type: "passage_cloze",
      prompt: "Elena aprì il suo quaderno e cominciò a leggere il primo capitolo del racconto.\nIl narratore raccontava di uno scrittore che, molti anni prima, ___ una storia simile.\nNessuno nella scena ricordava il suo nome, ma la trama era rimasta famosa.\nElena capì che quel vecchio segreto era ancora nascosto tra le pagine.\nAlla fine del capitolo, la sorpresa cambiò tutta la sua idea sul narratore.",
      accepted: ["aveva già scritto"],
      hint: "trapassato prossimo con avere – lui/lei; scrivere → scritto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-016", "u21-t1-018", "u21-t1-019", "u21-t1-030", "u21-t1-031", "u21-t2-043"],
    },
    {
      id: "u21-t4-007",
      type: "passage_cloze",
      prompt: "Giulia trovò un vecchio libro in soffitta e ne cominciò a leggere le prime pagine.\nScoprì che sua nonna, da giovane, ___ quel racconto molte volte.\nIl narratore della storia sembrava conoscere ogni personaggio della sua famiglia.\nNon appena Giulia capì la trama, si rese conto che il segreto era proprio lì.\nFinalmente aveva trovato la risposta che cercava da tempo.",
      accepted: ["aveva già letto"],
      hint: "trapassato prossimo con avere – lei; leggere → letto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-003", "u21-t1-013", "u21-t1-017", "u21-t1-019", "u21-t1-028", "u21-t1-031", "u21-t2-045"],
    },
    {
      id: "u21-t4-008",
      type: "passage_cloze",
      prompt: "Marco si svegliò tardi e corse subito in ufficio.\nQuando è arrivato, ha scoperto che il suo collega ___ la porta dell'archivio.\nDentro, c'era una scena che nessuno si aspettava: vecchi documenti sparsi ovunque.\nPurtroppo, quel segreto era rimasto nascosto per anni.\nMarco capì che quella scoperta avrebbe cambiato tutto il progetto.",
      accepted: ["aveva già aperto"],
      hint: "trapassato prossimo con avere – lui; aprire → aperto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-029", "u21-t1-031", "u21-t1-034", "u21-t1-026", "u21-t2-048"],
    },
    {
      id: "u21-t4-009",
      type: "passage_cloze",
      prompt: "Era una sera d'inverno quando Sofia entrò nella vecchia libreria.\nIl proprietario le disse che, poco prima, ___ il negozio per la notte.\nSofia rimase sorpresa: non aveva mai visto quella scena così silenziosa.\nNel passato, quel posto era sempre stato pieno di gente.\nAlla fine, Sofia decise di tornare il giorno dopo per scoprire di più.",
      accepted: ["aveva già chiuso"],
      hint: "trapassato prossimo con avere – lui; chiudere → chiuso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-014", "u21-t1-033", "u21-t1-034", "u21-t1-025", "u21-t2-049"],
    },
    {
      id: "u21-t4-010",
      type: "passage_cloze",
      prompt: "Dopo mesi di dubbi, una giovane coppia decise di raccontare la propria esperienza a un giornale locale.\nIl giornalista scoprì che, prima ancora di quella decisione, i due ___ di lasciare il lavoro in città.\nIl narratore dell'articolo spiegò che questa scelta aveva cambiato completamente la trama della loro vita.\nNessuno immaginava che un evento così piccolo potesse portare tanto coraggio.\nAlla fine, la loro storia diventò un esempio per molte altre famiglie.",
      accepted: ["avevano già deciso"],
      hint: "trapassato prossimo con avere – loro; decidere → deciso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-017", "u21-t1-011", "u21-t2-050"],
    },
    {
      id: "u21-t4-011",
      type: "passage_cloze",
      prompt: "Quella mattina, Luca trovò la sua vecchia macchina fotografica sul tavolo.\nSua sorella gli confessò che, per errore, ___ l'obiettivo qualche giorno prima.\nLuca non si arrabbiò: capì che era stato solo un incidente.\nNel frattempo, ricordò un'altra scena simile accaduta anni prima.\nFinalmente decisero di comprarne una nuova insieme.",
      accepted: ["aveva già rotto"],
      hint: "trapassato prossimo con avere – lei; rompere → rotto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-010", "u21-t1-028", "u21-t1-034", "u21-t2-051"],
    },
    {
      id: "u21-t4-012",
      type: "passage_cloze",
      prompt: "Anna cercava disperatamente le chiavi di casa.\nSi rese conto che, senza accorgersene, ___ il portafoglio con dentro anche i documenti.\nIl narratore della vicenda avrebbe potuto aggiungere questo dettaglio alla trama del suo prossimo racconto.\nPer fortuna, un vicino trovò tutto vicino alla scena dell'incidente.\nAlla fine, Anna promise di stare più attenta in futuro.",
      accepted: ["aveva già perso"],
      hint: "trapassato prossimo con avere – lei; perdere → perso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-024", "u21-t1-019", "u21-t1-017", "u21-t1-002", "u21-t1-034", "u21-t2-052"],
    },
    {
      id: "u21-t4-013",
      type: "passage_cloze",
      prompt: "Durante l'intervista, il famoso scrittore raccontò un aneddoto curioso.\nDisse che, molti anni prima, un giornalista gli aveva fatto una domanda difficile e lui non ___ subito.\nSolo dopo giorni di riflessione, aveva trovato la risposta giusta.\nQuella storia divenne parte del suo prossimo capitolo.\nIl pubblico rimase sorpreso da tanta sincerità.",
      accepted: ["aveva risposto"],
      hint: "trapassato prossimo con avere – lui; rispondere → risposto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-016", "u21-t1-030", "u21-t2-053"],
    },
    {
      id: "u21-t4-014",
      type: "passage_cloze",
      prompt: "Davide raccontò alla sua amica un vecchio ricordo di famiglia.\nSuo nonno, da ragazzo, ___ il permesso di partire per l'America prima ancora di finire la scuola.\nNessuno nella famiglia conosceva questo segreto fino a quel momento.\nLa scoperta cambiò completamente la trama della loro storia familiare.\nFinalmente, tutti capirono da dove veniva quel coraggio.",
      accepted: ["aveva già chiesto"],
      hint: "trapassato prossimo con avere – lui; chiedere → chiesto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-028", "u21-t2-054"],
    },
    {
      id: "u21-t4-015",
      type: "passage_cloze",
      prompt: "Quando Marta arrivò alla festa, era già tardi.\nL'organizzatore le spiegò che un altro ospite ___ il suo aiuto per preparare tutto.\nMarta si sentì sollevata: non doveva più preoccuparsi di niente.\nQuella sera, la scena sembrava uscita da un vecchio racconto.\nAlla fine, tutti ricordarono quella serata come una piacevole sorpresa.",
      accepted: ["aveva già offerto"],
      hint: "trapassato prossimo con avere – lui; offrire → offerto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-034", "u21-t1-002", "u21-t1-030", "u21-t1-022"],
    },
    {
      id: "u21-t4-016",
      type: "passage_cloze",
      prompt: "Il detective aprì il vecchio baule trovato in soffitta.\nCapì subito che qualcuno ___ delle lettere importanti sotto i vestiti.\nQuel segreto era rimasto nascosto per più di trent'anni.\nLa scoperta cambiò completamente la trama dell'indagine.\nFinalmente, il narratore della storia poteva scrivere l'ultimo capitolo.",
      accepted: ["aveva già nascosto"],
      hint: "trapassato prossimo con avere – lui (impersonale, qualcuno); nascondere → nascosto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-028", "u21-t1-019", "u21-t1-016", "u21-t2-056"],
    },
    {
      id: "u21-t4-017",
      type: "passage_cloze",
      prompt: "Dopo settimane di ricerche, Elena tornò in biblioteca.\nIl bibliotecario le disse che un altro studioso ___ lo stesso documento anni prima.\nElena rimase sorpresa: nessuno aveva mai scoperto quel segreto prima.\nPurtroppo, la sua scoperta non era più una novità.\nAlla fine, decise comunque di scrivere il suo capitolo sull'argomento.",
      accepted: ["aveva già scoperto"],
      hint: "trapassato prossimo con avere – lui; scoprire → scoperto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-029", "u21-t1-016", "u21-t2-057"],
    },
    {
      id: "u21-t4-018",
      type: "passage_cloze",
      prompt: "Nel primo capitolo del romanzo, il narratore racconta la storia del protagonista.\nIl personaggio principale ___ molto tempo prima degli eventi narrati nella trama.\nNessuno conosceva il suo passato fino a quella sorpresa finale.\nIl segreto della sua nascita cambiò completamente la storia.\nFinalmente il lettore capì perché il narratore aveva aspettato tanto per rivelarlo.",
      accepted: ["era nato"],
      hint: "trapassato prossimo con essere – nascere prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-016", "u21-t1-019", "u21-t1-017", "u21-t1-033", "u21-t1-030", "u21-t1-031", "u21-t1-028", "u21-t2-058"],
    },
    {
      id: "u21-t4-019",
      type: "passage_cloze",
      prompt: "Il romanzo raccontava la storia triste di una famiglia di scrittori.\nIl protagonista scoprì che suo padre ___ molti anni prima, quando lui era ancora bambino.\nQuel segreto era rimasto nascosto per tutta la sua infanzia.\nLa scoperta cambiò per sempre la trama della sua vita.\nAlla fine del capitolo, il narratore lasciò il lettore senza parole.",
      accepted: ["era morto"],
      hint: "trapassato prossimo con essere – morire prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-016", "u21-t1-019", "u21-t1-015", "u21-t2-059"],
    },
    {
      id: "u21-t4-020",
      type: "passage_cloze",
      prompt: "Quella sera, alla festa del paese, tutti parlavano di un evento strano.\nUn uomo misterioso ___ da un altro paese solo per raccontare quella storia.\nNessuno lo conosceva, ma il suo racconto sembrava vero.\nIl segreto che portava con sé cambiò la trama di tutta la serata.\nFinalmente, qualcuno capì chi era davvero quell'uomo.",
      accepted: ["era venuto"],
      hint: "trapassato prossimo con essere – venire prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-011", "u21-t1-002", "u21-t1-031", "u21-t1-017", "u21-t2-060"],
    },
    {
      id: "u21-t4-021",
      type: "passage_cloze",
      prompt: "Dopo la fine della guerra, molte famiglie tornarono nel loro paese.\nSolo pochi abitanti ___ nella vecchia casa durante tutti quegli anni difficili.\nIl narratore della storia raccontava questo con grande rispetto.\nQuella scelta, fatta nel passato, aveva un segreto dietro.\nAlla fine, la scoperta di quel segreto cambiò la trama del racconto.",
      accepted: ["erano rimasti"],
      hint: "trapassato prossimo con essere – rimanere prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-033", "u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-002", "u21-t2-061"],
    },
    {
      id: "u21-t4-022",
      type: "passage_cloze",
      prompt: "Quella notte, Chiara sentì un rumore strano nel palazzo.\nLa sua vicina le raccontò che, poco prima, qualcuno ___ velocemente dalle scale.\nChiara capì che quella scena non era normale.\nIl segreto di quella notte rimase nascosto per settimane.\nFinalmente, la polizia scoprì la verità dietro tutto l'evento.",
      accepted: ["era sceso"],
      hint: "trapassato prossimo con essere – scendere prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-034", "u21-t1-031", "u21-t1-028", "u21-t1-011", "u21-t2-062"],
    },
    {
      id: "u21-t4-023",
      type: "passage_cloze",
      prompt: "Il vecchio scrittore raccontava spesso la sua storia ai giovani del paese.\nPrima di quel viaggio famoso, non ___ uno scrittore conosciuto.\nIl narratore spiegava che ogni capitolo della sua vita aveva cambiato la trama del suo destino.\nUn piccolo segreto del passato aveva reso possibile tutto questo.\nAlla fine, la sua storia diventò un esempio per molti.",
      accepted: ["era ancora diventato"],
      hint: "trapassato prossimo con essere – diventare prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-015", "u21-t1-019", "u21-t1-016", "u21-t1-017", "u21-t1-031", "u21-t1-033", "u21-t2-063"],
    },
    {
      id: "u21-t4-024",
      type: "passage_cloze",
      prompt: "Dopo tanti anni lontano da casa, Marco decise di scrivere le sue memorie.\nRicordava che sua madre ___ a casa quando lui arrivò quella sera d'estate.\nQuella scena era rimasta impressa nella sua mente per sempre.\nIl segreto di quel ritorno cambiò tutta la trama della sua vita.\nFinalmente, Marco capì il vero significato di quel momento.",
      accepted: ["era già tornata"],
      hint: "trapassato prossimo con essere – tornare prende essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-022", "u21-t1-034", "u21-t1-031", "u21-t1-017", "u21-t1-028", "u21-t2-064"],
    },
    {
      id: "u21-t4-025",
      type: "passage_cloze",
      prompt: "Durante la cena, il nonno cominciò a raccontare una vecchia storia di famiglia.\nDisse che, fino a quel momento, nessuno ___ mai quel segreto così importante.\nI nipoti rimasero in silenzio, sorpresi da quella scoperta improvvisa.\nIl narratore della serata capì che quella storia avrebbe cambiato tutto.\nAlla fine, la famiglia decise di scrivere insieme un nuovo capitolo della loro storia.",
      accepted: ["aveva ricordato"],
      hint: "trapassato prossimo con avere – ricordare è regolare",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-027", "u21-t1-019", "u21-t1-016", "u21-t1-014", "u21-t2-065"],
    },
    {
      id: "u21-t4-026",
      type: "passage_cloze",
      prompt: "Quando Sara aprì la vecchia scatola, trovò lettere e fotografie ingiallite.\nSi rese conto che, per anni, la sua famiglia ___ completamente quella storia.\nIl segreto nascosto in quelle pagine cambiò per sempre la trama della loro vita.\nPurtroppo, molti dettagli importanti erano andati persi nel passato.\nFinalmente, Sara decise di scrivere il primo capitolo di un libro su tutto questo.",
      accepted: ["aveva dimenticato"],
      hint: "trapassato prossimo con avere – dimenticare è regolare",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-024", "u21-t1-031", "u21-t1-032", "u21-t1-017", "u21-t1-029", "u21-t1-033", "u21-t1-016", "u21-t2-066"],
    },
    {
      id: "u21-t4-027",
      type: "passage_cloze",
      prompt: "Alla fine del romanzo, il narratore riassume tutta la trama in poche righe.\nIl lettore si rende conto che molti eventi strani ___ prima dell'inizio della storia.\nNessun personaggio aveva capito subito il vero segreto nascosto in quella scena.\nSolo dopo l'ultima sorpresa, tutti si sono resi conto della verità.\nPurtroppo, non tutti i misteri del passato trovano una risposta chiara.",
      accepted: ["erano già accaduti", "erano già successi"],
      hint: "trapassato prossimo con essere – accadere/succedere sono impersonali ma concordano col soggetto plurale",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-017", "u21-t1-011", "u21-t1-024", "u21-t1-031", "u21-t1-034", "u21-t1-030", "u21-t1-033", "u21-t1-029", "u21-t1-020", "u21-t1-021"],
    },
  ],
};
export default unit;
