import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-33-subjunctive-opinions",
  name: "What I Think",
  level: "B1",
  theme: "Subjunctive Triggers — Opinions",
  emoji: "💭",
  prerequisiteUnits: ["b1-unit-20-congiuntivo"],
  cards: [
    // ── Tier 1 – Vocab: opinion triggers ──────────────────────────────────────
    {
      id: "b133-t1-001",
      type: "recognize",
      prompt: "secondo me",
      accepted: ["in my opinion", "in my view"],
      hint: "Secondo + pronoun never triggers the congiuntivo — it takes the normal indicativo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-002",
      type: "produce",
      prompt: "in my opinion",
      accepted: ["secondo me"],
      hint: "Secondo me always takes the indicativo, never the congiuntivo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-003",
      type: "recognize",
      prompt: "secondo te",
      accepted: ["in your opinion"],
      hint: "Informal 'you' form of secondo + pronoun.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-004",
      type: "produce",
      prompt: "in your opinion",
      accepted: ["secondo te"],
      hint: "Secondo te takes the indicativo, exactly like secondo me.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-005",
      type: "recognize",
      prompt: "secondo lui",
      accepted: ["in his opinion"],
      hint: "Third-person singular masculine of secondo + pronoun.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-006",
      type: "produce",
      prompt: "in his opinion",
      accepted: ["secondo lui"],
      hint: "Followed by the indicativo of the verb.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-007",
      type: "recognize",
      prompt: "secondo lei",
      accepted: ["in her opinion"],
      hint: "Third-person singular feminine of secondo + pronoun.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-008",
      type: "produce",
      prompt: "in her opinion",
      accepted: ["secondo lei"],
      hint: "Followed by the indicativo, never the congiuntivo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-009",
      type: "recognize",
      prompt: "secondo noi",
      accepted: ["in our opinion"],
      hint: "First-person plural of secondo + pronoun.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-010",
      type: "produce",
      prompt: "in our opinion",
      accepted: ["secondo noi"],
      hint: "Secondo noi always takes the indicativo, like the rest of the secondo + pronoun paradigm.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-011",
      type: "recognize",
      prompt: "secondo loro",
      accepted: ["in their opinion"],
      hint: "Third-person plural of secondo + pronoun.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-012",
      type: "produce",
      prompt: "in their opinion",
      accepted: ["secondo loro"],
      hint: "Secondo loro always takes the indicativo — the whole secondo + pronoun paradigm never takes the congiuntivo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-013",
      type: "recognize",
      prompt: "ritenere",
      accepted: ["to consider", "to deem", "to believe"],
      hint: "A more formal synonym of pensare/credere — ritenere che triggers the congiuntivo.",
      tags: ["verb", "opinion", "trigger", "vocab", "irregular"],
      tier: 1,
    },
    {
      id: "b133-t1-014",
      type: "produce",
      prompt: "to consider (an opinion)",
      accepted: ["ritenere"],
      hint: "Conjugates like tenere: ritengo, ritieni, ritiene, riteniamo, ritenete, ritengono.",
      tags: ["verb", "opinion", "trigger", "vocab", "irregular"],
      tier: 1,
    },
    {
      id: "b133-t1-015",
      type: "recognize",
      prompt: "convinto",
      accepted: ["convinced"],
      hint: "Essere convinto/a che triggers the congiuntivo, agreeing in gender and number with the subject.",
      tags: ["adjective", "opinion", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-016",
      type: "produce",
      prompt: "convinced",
      accepted: ["convinto", "convinta"],
      hint: "Essere convinto/a che is always followed by che + congiuntivo; the adjective agrees with the subject, adding convinti/convinte for the plural.",
      tags: ["adjective", "opinion", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-017",
      type: "recognize",
      prompt: "immaginare",
      accepted: ["to imagine"],
      hint: "Immaginare che triggers the congiuntivo, just like pensare che.",
      tags: ["verb", "opinion", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-018",
      type: "produce",
      prompt: "to imagine",
      accepted: ["immaginare"],
      hint: "Regular -are verb: immagino, immagini, immagina, immaginiamo, immaginate, immaginano.",
      tags: ["verb", "opinion", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-019",
      type: "recognize",
      prompt: "supporre",
      accepted: ["to suppose", "to assume"],
      hint: "Conjugates like porre — irregular. Supporre che triggers the congiuntivo.",
      tags: ["verb", "opinion", "trigger", "vocab", "irregular"],
      tier: 1,
    },
    {
      id: "b133-t1-020",
      type: "produce",
      prompt: "to suppose",
      accepted: ["supporre"],
      hint: "Supponiamo, supponete are the only forms that look like the infinitive stem plus -iamo/-ete.",
      tags: ["verb", "opinion", "trigger", "vocab", "irregular"],
      tier: 1,
    },
    {
      id: "b133-t1-021",
      type: "recognize",
      prompt: "il parere",
      accepted: ["the opinion", "the view"],
      hint: "A more formal noun for opinion, often used with dare or cambiare.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-022",
      type: "produce",
      prompt: "the opinion (formal)",
      accepted: ["il parere"],
      hint: "Dare il proprio parere = to give one's opinion.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-023",
      type: "recognize",
      prompt: "a mio avviso",
      accepted: ["in my view", "in my opinion (formal)"],
      hint: "A more formal synonym of secondo me — also does not trigger the congiuntivo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-024",
      type: "produce",
      prompt: "in my view (formal)",
      accepted: ["a mio avviso"],
      hint: "Followed by the indicativo or conditional, never the congiuntivo.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-025",
      type: "recognize",
      prompt: "a suo avviso",
      accepted: ["in his view", "in her view"],
      hint: "Formal third-person version of a mio avviso.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-026",
      type: "produce",
      prompt: "in her view (formal)",
      accepted: ["a suo avviso"],
      hint: "Same rule as secondo lei: no congiuntivo follows.",
      tags: ["expression", "opinion", "trigger", "vocab", "no-subjunctive"],
      tier: 1,
    },
    {
      id: "b133-t1-027",
      type: "recognize",
      prompt: "la supposizione",
      accepted: ["the assumption", "the supposition"],
      hint: "Noun form of supporre — the thing you suppose.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-028",
      type: "produce",
      prompt: "the assumption",
      accepted: ["la supposizione"],
      hint: "Word family: supporre (verb) → la supposizione (noun).",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-029",
      type: "recognize",
      prompt: "l'immaginazione",
      accepted: ["the imagination"],
      hint: "Noun form of immaginare.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "b133-t1-030",
      type: "produce",
      prompt: "the imagination",
      accepted: ["l'immaginazione"],
      hint: "Word family: immaginare (verb) → l'immaginazione (noun).",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },

    // ── Tier 2 – Grammar: conjugations, agreement, contrast drills ───────────
    {
      id: "b133-t2-001",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – io",
      accepted: ["ritenga"],
      hint: "Ritenere conjugates like tenere: tenga → ritenga.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-002",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – tu",
      accepted: ["ritenga"],
      hint: "All three singular persons share the same form: ritenga.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-003",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – lui/lei",
      accepted: ["ritenga"],
      hint: "Same irregular stem as tenga for tenere.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-004",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – noi",
      accepted: ["riteniamo"],
      hint: "The noi form matches the indicativo presente: riteniamo.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-005",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – voi",
      accepted: ["riteniate"],
      hint: "Voi form: riteniate, built on the same stem as riteniamo.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-006",
      type: "conjugate",
      prompt: "ritenere (congiuntivo presente) – loro",
      accepted: ["ritengano"],
      hint: "Loro form: ritengano, from the same irregular stem as tengano.",
      tags: ["congiuntivo", "grammar", "ritenere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-007",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – io",
      accepted: ["immagini"],
      hint: "Regular -are verb: the singular persons all share the ending -i.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-008",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – tu",
      accepted: ["immagini"],
      hint: "Same form as io: immagini.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-009",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – lui/lei",
      accepted: ["immagini"],
      hint: "All three singular persons of -are verbs share one form: immagini.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-010",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – noi",
      accepted: ["immaginiamo"],
      hint: "Identical to the indicativo presente noi form.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-011",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – voi",
      accepted: ["immaginiate"],
      hint: "Voi form for -are verbs: -iate.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-012",
      type: "conjugate",
      prompt: "immaginare (congiuntivo presente) – loro",
      accepted: ["immaginino"],
      hint: "Loro form: immaginino.",
      tags: ["congiuntivo", "grammar", "immaginare", "conjugation"],
      tier: 2,
    },
    {
      id: "b133-t2-013",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – io",
      accepted: ["supponga"],
      hint: "Supporre conjugates like porre: ponga → supponga.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-014",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – tu",
      accepted: ["supponga"],
      hint: "Same irregular singular form as io: supponga.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-015",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – lui/lei",
      accepted: ["supponga"],
      hint: "All three singular persons share this irregular form.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-016",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – noi",
      accepted: ["supponiamo"],
      hint: "Matches the indicativo presente noi form.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-017",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – voi",
      accepted: ["supponiate"],
      hint: "Voi form: supponiate.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-018",
      type: "conjugate",
      prompt: "supporre (congiuntivo presente) – loro",
      accepted: ["suppongano"],
      hint: "Loro form: suppongano, from the same irregular stem as pongano.",
      tags: ["congiuntivo", "grammar", "supporre", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "b133-t2-019",
      type: "fill_blank",
      prompt: "Marco è convint__ che il suo capo abbia ragione. (soggetto maschile)",
      accepted: ["convinto"],
      hint: "Essere convinto/a che always takes the congiuntivo (abbia ragione); the adjective agrees with Marco here: masculine singular.",
      tags: ["congiuntivo", "grammar", "convinto", "agreement", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-020",
      type: "fill_blank",
      prompt: "Giulia è convint__ che il suo capo abbia ragione. (soggetto femminile)",
      accepted: ["convinta"],
      hint: "Essere convinto/a che always takes the congiuntivo (abbia ragione); the adjective agrees with Giulia here: feminine singular.",
      tags: ["congiuntivo", "grammar", "convinto", "agreement", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-021",
      type: "fill_blank",
      prompt: "Noi siamo convint__ che la squadra vinca la partita. (soggetto plurale maschile/misto)",
      accepted: ["convinti"],
      hint: "Essere convinto/a che always takes the congiuntivo (vinca); the adjective agrees with a plural masculine or mixed group here: convinti.",
      tags: ["congiuntivo", "grammar", "convinto", "agreement", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-022",
      type: "fill_blank",
      prompt: "Le mie colleghe sono convint__ che il progetto sia troppo ambizioso. (soggetto plurale femminile)",
      accepted: ["convinte"],
      hint: "Essere convinto/a che always takes the congiuntivo (sia troppo ambizioso); the adjective agrees with a plural feminine subject here: convinte.",
      tags: ["congiuntivo", "grammar", "convinto", "agreement", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-023",
      type: "fill_blank",
      prompt: "Secondo me, Laura ___ (avere) ragione in questa discussione.",
      accepted: ["ha"],
      hint: "Secondo me takes the indicativo — no congiuntivo here.",
      tags: ["congiuntivo", "grammar", "secondo me", "avere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-024",
      type: "fill_blank",
      prompt: "Ritengo che Laura ___ (avere) ragione in questa discussione.",
      accepted: ["abbia"],
      hint: "Ritenere che triggers the congiuntivo, unlike secondo me.",
      tags: ["congiuntivo", "grammar", "ritenere che", "avere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-025",
      type: "fill_blank",
      prompt: "Secondo me, il film ___ (essere) troppo lungo.",
      accepted: ["è"],
      hint: "Indicativo presente of essere, since secondo me never triggers the congiuntivo.",
      tags: ["congiuntivo", "grammar", "secondo me", "essere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-026",
      type: "fill_blank",
      prompt: "Ritengo che il film ___ (essere) troppo lungo.",
      accepted: ["sia"],
      hint: "Congiuntivo presente of essere, triggered by ritenere che.",
      tags: ["congiuntivo", "grammar", "ritenere che", "essere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-027",
      type: "fill_blank",
      prompt: "Secondo me, loro ___ (potere) risolvere il problema da soli.",
      accepted: ["possono"],
      hint: "Secondo me takes the indicativo presente of potere here: possono.",
      tags: ["congiuntivo", "grammar", "secondo me", "potere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-028",
      type: "fill_blank",
      prompt: "Ritengo che loro ___ (potere) risolvere il problema da soli.",
      accepted: ["possano"],
      hint: "Ritenere che triggers the congiuntivo presente of potere here: possano.",
      tags: ["congiuntivo", "grammar", "ritenere che", "potere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-029",
      type: "fill_blank",
      prompt: "Secondo me, tu ___ (dovere) parlare con il direttore.",
      accepted: ["devi"],
      hint: "Secondo me takes the indicativo presente of dovere here: devi.",
      tags: ["congiuntivo", "grammar", "secondo me", "dovere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-030",
      type: "fill_blank",
      prompt: "Ritengo che tu ___ (dovere) parlare con il direttore.",
      accepted: ["debba"],
      hint: "Ritenere che triggers the congiuntivo presente of dovere here: debba.",
      tags: ["congiuntivo", "grammar", "ritenere che", "dovere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-031",
      type: "fill_blank",
      prompt: "Secondo me, lei ___ (sapere) già la verità.",
      accepted: ["sa"],
      hint: "Secondo me takes the indicativo presente of sapere here: sa.",
      tags: ["congiuntivo", "grammar", "secondo me", "sapere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-032",
      type: "fill_blank",
      prompt: "Ritengo che lei ___ (sapere) già la verità.",
      accepted: ["sappia"],
      hint: "Ritenere che triggers the congiuntivo presente of sapere here: sappia.",
      tags: ["congiuntivo", "grammar", "ritenere che", "sapere", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-033",
      type: "fill_blank",
      prompt: "Secondo me, voi ___ (fare) un ottimo lavoro.",
      accepted: ["fate"],
      hint: "Secondo me takes the indicativo presente of fare here: fate.",
      tags: ["congiuntivo", "grammar", "secondo me", "fare", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-034",
      type: "fill_blank",
      prompt: "Ritengo che voi ___ (fare) un ottimo lavoro.",
      accepted: ["facciate"],
      hint: "Ritenere che triggers the congiuntivo presente of fare here: facciate.",
      tags: ["congiuntivo", "grammar", "ritenere che", "fare", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-035",
      type: "fill_blank",
      prompt: "Secondo me, Marco ___ (venire) alla festa stasera.",
      accepted: ["viene"],
      hint: "Secondo me takes the indicativo presente of venire here: viene.",
      tags: ["congiuntivo", "grammar", "secondo me", "venire", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-036",
      type: "fill_blank",
      prompt: "Ritengo che Marco ___ (venire) alla festa stasera.",
      accepted: ["venga"],
      hint: "Ritenere che triggers the congiuntivo presente of venire here: venga.",
      tags: ["congiuntivo", "grammar", "ritenere che", "venire", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-037",
      type: "fill_blank",
      prompt: "Secondo me, i ragazzi ___ (dire) la verità.",
      accepted: ["dicono"],
      hint: "Secondo me takes the indicativo presente of dire here: dicono.",
      tags: ["congiuntivo", "grammar", "secondo me", "dire", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-038",
      type: "fill_blank",
      prompt: "Ritengo che i ragazzi ___ (dire) la verità.",
      accepted: ["dicano"],
      hint: "Ritenere che triggers the congiuntivo presente of dire here: dicano.",
      tags: ["congiuntivo", "grammar", "ritenere che", "dire", "contrast", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-039",
      type: "fill_blank",
      prompt: "Sono convinto che il nuovo manager ___ (essere) molto capace.",
      accepted: ["sia"],
      hint: "Essere convinto che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-040",
      type: "fill_blank",
      prompt: "Sono convinta che i miei genitori ___ (avere) ragione su questo.",
      accepted: ["abbiano"],
      hint: "Essere convinta che triggers the congiuntivo presente of avere here; plural subject takes abbiano.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "avere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-041",
      type: "fill_blank",
      prompt: "Siamo convinti che tu ___ (potere) migliorare velocemente.",
      accepted: ["possa"],
      hint: "Essere convinti che triggers the congiuntivo presente of potere here; tu takes possa.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "potere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-042",
      type: "fill_blank",
      prompt: "È convinto che sua sorella ___ (sapere) la risposta esatta.",
      accepted: ["sappia"],
      hint: "Essere convinto che triggers the congiuntivo presente of sapere here: sappia.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "sapere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-043",
      type: "fill_blank",
      prompt: "Sono convinte che il progetto ___ (richiedere) più tempo del previsto.",
      accepted: ["richieda"],
      hint: "Essere convinte che triggers the congiuntivo presente of richiedere here: richieda.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "richiedere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-044",
      type: "fill_blank",
      prompt: "Sei convinto che loro ___ (dire) sempre la verità?",
      accepted: ["dicano"],
      hint: "Essere convinto che triggers the congiuntivo presente of dire here; plural subject takes dicano.",
      tags: ["congiuntivo", "grammar", "essere convinto che", "dire", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-045",
      type: "fill_blank",
      prompt: "Ho l'impressione che il capo ___ (essere) nervoso oggi.",
      accepted: ["sia"],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-046",
      type: "fill_blank",
      prompt: "Abbiamo l'impressione che i vicini ___ (fare) troppo rumore di notte.",
      accepted: ["facciano"],
      hint: "Avere l'impressione che triggers the congiuntivo presente of fare here; plural subject takes facciano.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "fare", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-047",
      type: "fill_blank",
      prompt: "Hai l'impressione che Marta ___ (volere) cambiare lavoro?",
      accepted: ["voglia"],
      hint: "Avere l'impressione che triggers the congiuntivo presente of volere here: voglia.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "volere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-048",
      type: "fill_blank",
      prompt: "Ha l'impressione che i suoi amici le ___ (nascondere) qualcosa.",
      accepted: ["nascondano"],
      hint: "Avere l'impressione che triggers the congiuntivo presente of nascondere here; plural subject takes nascondano.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "nascondere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-049",
      type: "fill_blank",
      prompt: "Avete l'impressione che il progetto ___ (andare) nella direzione giusta?",
      accepted: ["vada"],
      hint: "Avere l'impressione che triggers the congiuntivo presente of andare here: vada.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "andare", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-050",
      type: "fill_blank",
      prompt: "Hanno l'impressione che il prezzo ___ (essere) troppo alto.",
      accepted: ["sia"],
      hint: "Avere l'impressione che triggers the congiuntivo presente of essere here: sia.",
      tags: ["congiuntivo", "grammar", "avere l'impressione che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-051",
      type: "fill_blank",
      prompt: "Immagino che il viaggio ___ (essere) molto lungo.",
      accepted: ["sia"],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["congiuntivo", "grammar", "immaginare che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-052",
      type: "fill_blank",
      prompt: "Immaginiamo che loro ___ (avere) molte domande da fare.",
      accepted: ["abbiano"],
      hint: "Immaginare che triggers the congiuntivo presente of avere here; plural subject takes abbiano.",
      tags: ["congiuntivo", "grammar", "immaginare che", "avere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-053",
      type: "fill_blank",
      prompt: "Immagini che il tuo capo ___ (potere) capire la situazione?",
      accepted: ["possa"],
      hint: "Immaginare che triggers the congiuntivo presente of potere here: possa.",
      tags: ["congiuntivo", "grammar", "immaginare che", "potere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-054",
      type: "fill_blank",
      prompt: "Immagina che sua figlia ___ (sapere) già cucinare bene.",
      accepted: ["sappia"],
      hint: "Immaginare che triggers the congiuntivo presente of sapere here: sappia.",
      tags: ["congiuntivo", "grammar", "immaginare che", "sapere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-055",
      type: "fill_blank",
      prompt: "Immaginate che la riunione ___ (durare) più di due ore.",
      accepted: ["duri"],
      hint: "Immaginare che triggers the congiuntivo presente of durare here: duri.",
      tags: ["congiuntivo", "grammar", "immaginare che", "durare", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-056",
      type: "fill_blank",
      prompt: "Immaginano che il nuovo ristorante ___ (essere) troppo caro per loro.",
      accepted: ["sia"],
      hint: "Immaginare che triggers the congiuntivo presente of essere here: sia.",
      tags: ["congiuntivo", "grammar", "immaginare che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-057",
      type: "fill_blank",
      prompt: "Suppongo che l'aereo ___ (partire) in orario.",
      accepted: ["parta"],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo of partire.",
      tags: ["congiuntivo", "grammar", "supporre che", "partire", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-058",
      type: "fill_blank",
      prompt: "Supponiamo che loro ___ (arrivare) prima di sera.",
      accepted: ["arrivino"],
      hint: "Supporre che triggers the congiuntivo presente of arrivare here; plural subject takes arrivino.",
      tags: ["congiuntivo", "grammar", "supporre che", "arrivare", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-059",
      type: "fill_blank",
      prompt: "Supponi che il museo ___ (essere) chiuso di lunedì?",
      accepted: ["sia"],
      hint: "Supporre che triggers the congiuntivo presente of essere here: sia.",
      tags: ["congiuntivo", "grammar", "supporre che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-060",
      type: "fill_blank",
      prompt: "Suppone che i colleghi ___ (sapere) già la notizia.",
      accepted: ["sappiano"],
      hint: "Supporre che triggers the congiuntivo presente of sapere here; plural subject takes sappiano.",
      tags: ["congiuntivo", "grammar", "supporre che", "sapere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-061",
      type: "fill_blank",
      prompt: "Supponete che la strada ___ (essere) ancora bloccata?",
      accepted: ["sia"],
      hint: "Supporre che triggers the congiuntivo presente of essere here: sia.",
      tags: ["congiuntivo", "grammar", "supporre che", "essere", "fill_blank"],
      tier: 2,
    },
    {
      id: "b133-t2-062",
      type: "fill_blank",
      prompt: "Suppongono che il capo ___ (volere) parlare con tutti.",
      accepted: ["voglia"],
      hint: "Supporre che triggers the congiuntivo presente of volere here: voglia.",
      tags: ["congiuntivo", "grammar", "supporre che", "volere", "fill_blank"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & collocations ────────────────────────────────────────
    {
      id: "b133-t3-001",
      type: "produce",
      prompt: "In my opinion, this restaurant is too expensive.",
      accepted: ["Secondo me, questo ristorante è troppo caro."],
      hint: "Secondo me takes the indicativo here (è), not the congiuntivo.",
      tags: ["opinion", "chunk", "secondo me", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-002",
      type: "produce",
      prompt: "In your opinion, is this book interesting?",
      accepted: ["Secondo te, questo libro è interessante?"],
      hint: "Secondo te still takes the indicativo here, even in a question.",
      tags: ["opinion", "chunk", "secondo te", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-003",
      type: "produce",
      prompt: "In his opinion, the meeting went well.",
      accepted: ["Secondo lui, la riunione è andata bene."],
      hint: "Secondo lui takes the passato prossimo here — still the indicativo, never the congiuntivo.",
      tags: ["opinion", "chunk", "secondo lui", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-004",
      type: "produce",
      prompt: "In her opinion, the exam was too difficult.",
      accepted: ["Secondo lei, l'esame era troppo difficile."],
      hint: "Secondo lei takes the imperfetto here — still no congiuntivo.",
      tags: ["opinion", "chunk", "secondo lei", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-005",
      type: "produce",
      prompt: "In our opinion, the new policy is unfair.",
      accepted: ["Secondo noi, la nuova politica è ingiusta."],
      hint: "Secondo noi takes the indicativo presente here.",
      tags: ["opinion", "chunk", "secondo noi", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-006",
      type: "produce",
      prompt: "In their opinion, the film deserved the prize.",
      accepted: ["Secondo loro, il film meritava il premio."],
      hint: "Secondo loro takes the imperfetto here, since it never triggers the congiuntivo.",
      tags: ["opinion", "chunk", "secondo loro", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-007",
      type: "produce",
      prompt: "In my opinion, that decision was a mistake.",
      accepted: ["Secondo me, quella decisione è stata un errore."],
      hint: "Secondo me takes the passato prossimo here, since it never triggers the congiuntivo.",
      tags: ["opinion", "chunk", "secondo me", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-008",
      type: "produce",
      prompt: "In your opinion, who is right?",
      accepted: ["Secondo te, chi ha ragione?"],
      hint: "Secondo te takes the indicativo presente here: the indicativo of avere ragione.",
      tags: ["opinion", "chunk", "secondo te", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-009",
      type: "produce",
      prompt: "The architect considers that this design is the best solution for the flooding problem in the old town.",
      accepted: ["L'architetto ritiene che questo progetto sia la soluzione migliore per il problema delle alluvioni nel centro storico."],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of essere; note migliore is the irregular comparative of buono, not 'più buona'.",
      tags: ["opinion", "chunk", "ritenere che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-010",
      type: "produce",
      prompt: "The doctors consider that Marco's recovery requires patience, since the injury was severe.",
      accepted: ["I medici ritengono che il recupero di Marco richieda pazienza, poiché l'infortunio era grave."],
      hint: "Ritenere che triggers the congiuntivo of richiedere (richieda) here — poiché introduces the real reason in the indicativo (era), a separate clause.",
      tags: ["opinion", "chunk", "ritenere che", "richiedere"],
      tier: 3,
    },
    {
      id: "b133-t3-011",
      type: "produce",
      prompt: "The teacher considers that the students need more practice.",
      accepted: ["L'insegnante ritiene che gli studenti abbiano bisogno di più pratica."],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of avere bisogno.",
      tags: ["opinion", "chunk", "ritenere che", "avere bisogno"],
      tier: 3,
    },
    {
      id: "b133-t3-012",
      type: "produce",
      prompt: "I deem it necessary that we discuss this immediately.",
      accepted: ["Ritengo necessario che ne discutiamo subito."],
      hint: "Ritenere necessario che always triggers the congiuntivo — here, the congiuntivo of discutere.",
      tags: ["opinion", "chunk", "ritenere che", "discutere"],
      tier: 3,
    },
    {
      id: "b133-t3-013",
      type: "produce",
      prompt: "The buyers consider that the seller's price is too high, given the building's age.",
      accepted: ["I compratori ritengono che il prezzo del venditore sia troppo alto, considerata l'età dell'edificio."],
      hint: "Ritenere che triggers the congiuntivo of essere (sia) here — considerata l'età dell'edificio is a past-participle absolute, not a second subjunctive clause.",
      tags: ["opinion", "chunk", "ritenere che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-014",
      type: "produce",
      prompt: "She considers that her colleague deserves the promotion.",
      accepted: ["Ritiene che la sua collega meriti la promozione."],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of meritare.",
      tags: ["opinion", "chunk", "ritenere che", "meritare"],
      tier: 3,
    },
    {
      id: "b133-t3-015",
      type: "produce",
      prompt: "I consider it important that everyone participates.",
      accepted: ["Ritengo importante che tutti partecipino."],
      hint: "Ritenere importante che always triggers the congiuntivo — here, the congiuntivo of partecipare.",
      tags: ["opinion", "chunk", "ritenere che", "partecipare"],
      tier: 3,
    },
    {
      id: "b133-t3-016",
      type: "produce",
      prompt: "The investors consider that the startup's plan can succeed only if they hire a local manager.",
      accepted: ["Gli investitori ritengono che il piano della startup possa funzionare solo se assumono un direttore locale."],
      hint: "Ritenere che triggers the congiuntivo of potere (possa) here — solo se introduces a real condition and keeps the indicativo (assumono).",
      tags: ["opinion", "chunk", "ritenere che", "potere"],
      tier: 3,
    },
    {
      id: "b133-t3-017",
      type: "produce",
      prompt: "Even though he is the youngest on the team, he considers that his opinion counts during the budget meeting.",
      accepted: ["Anche se è il più giovane della squadra, ritiene che la sua opinione conti durante la riunione sul budget."],
      hint: "Ritenere che triggers the congiuntivo of contare (conti) here — anche se does not trigger the congiuntivo on its own verb (è), a distinct rule from ritenere che.",
      tags: ["opinion", "chunk", "ritenere che", "contare"],
      tier: 3,
    },
    {
      id: "b133-t3-018",
      type: "produce",
      prompt: "I consider that the new remote-work rule is fair to parents with young children.",
      accepted: ["Ritengo che la nuova regola sul lavoro da remoto sia giusta per i genitori con bambini piccoli."],
      hint: "Ritenere che triggers the congiuntivo of essere (sia) here — per i genitori con bambini piccoli specifies who benefits, without adding a second clause.",
      tags: ["opinion", "chunk", "ritenere che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-019",
      type: "produce",
      prompt: "It's hard to consider that this problem has no solution.",
      accepted: ["È difficile ritenere che questo problema non abbia soluzione."],
      hint: "Ritenere as a bare infinitive, still followed by che + congiuntivo.",
      tags: ["opinion", "chunk", "ritenere", "avere", "infinitive"],
      tier: 3,
    },
    {
      id: "b133-t3-020",
      type: "produce",
      prompt: "I am convinced that she is telling the truth.",
      accepted: ["Sono convinto che dica la verità.", "Sono convinta che dica la verità."],
      hint: "Essere convinto/a che always triggers the congiuntivo — here, the congiuntivo of dire.",
      tags: ["opinion", "chunk", "essere convinto che", "dire"],
      tier: 3,
    },
    {
      id: "b133-t3-021",
      type: "produce",
      prompt: "We are convinced that the plan will work.",
      accepted: ["Siamo convinti che il piano funzioni."],
      hint: "Essere convinti che always triggers the congiuntivo — here, the congiuntivo of funzionare.",
      tags: ["opinion", "chunk", "essere convinto che", "funzionare"],
      tier: 3,
    },
    {
      id: "b133-t3-022",
      type: "produce",
      prompt: "He is convinced that his son can succeed as a chef, since he trained under the best cooks in Bologna.",
      accepted: ["È convinto che suo figlio possa avere successo come cuoco, visto che si è formato con i migliori chef di Bologna."],
      hint: "Essere convinto che triggers the congiuntivo of potere (possa) here — visto che introduces the real reason in the indicativo, not a second subjunctive clause.",
      tags: ["opinion", "chunk", "essere convinto che", "potere"],
      tier: 3,
    },
    {
      id: "b133-t3-023",
      type: "produce",
      prompt: "After a week spent exploring its markets and churches, I am convinced that Palermo is a beautiful city.",
      accepted: [
        "Dopo una settimana passata a esplorare i suoi mercati e le sue chiese, sono convinto che Palermo sia una città bellissima.",
        "Dopo una settimana passata a esplorare i suoi mercati e le sue chiese, sono convinta che Palermo sia una città bellissima.",
      ],
      hint: "Essere convinto/a che triggers the congiuntivo of essere (sia) here — 'dopo una settimana passata a esplorare' is a time expression, unrelated to the congiuntivo trigger.",
      tags: ["opinion", "chunk", "essere convinto che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-024",
      type: "produce",
      prompt: "The fans are convinced that this small-town team deserves to win the championship after such a difficult season.",
      accepted: ["I tifosi sono convinti che questa squadra di provincia meriti di vincere il campionato dopo una stagione così difficile."],
      hint: "Essere convinti che triggers the congiuntivo of meritare (meriti) here — di vincere uses the infinitive after meritare, not another subjunctive clause.",
      tags: ["opinion", "chunk", "essere convinto che", "meritare"],
      tier: 3,
    },
    {
      id: "b133-t3-025",
      type: "produce",
      prompt: "Even though her parents disagreed, she is convinced that her choice to study abroad was right.",
      accepted: ["Anche se i suoi genitori non erano d'accordo, è convinta che la sua scelta di studiare all'estero sia stata giusta."],
      hint: "Essere convinta che triggers the congiuntivo passato (sia stata) for a completed choice — anche se keeps its own clause in the indicativo (erano).",
      tags: ["opinion", "chunk", "essere convinto che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-026",
      type: "produce",
      prompt: "I am convinced that we can find a solution to the delivery delays affecting the whole team.",
      accepted: [
        "Sono convinto che possiamo trovare una soluzione ai ritardi di consegna che stanno colpendo tutta la squadra.",
        "Sono convinta che possiamo trovare una soluzione ai ritardi di consegna che stanno colpendo tutta la squadra.",
      ],
      hint: "Essere convinto/a che triggers the congiuntivo of potere (possiamo, identical here to the indicativo for noi) — che stanno colpendo is a separate relative clause.",
      tags: ["opinion", "chunk", "essere convinto che", "potere"],
      tier: 3,
    },
    {
      id: "b133-t3-027",
      type: "produce",
      prompt: "After only two days of training, are you convinced that the new employee understands the safety procedure?",
      accepted: [
        "Dopo solo due giorni di formazione, sei convinto che il nuovo dipendente capisca la procedura di sicurezza?",
        "Dopo solo due giorni di formazione, sei convinta che il nuovo dipendente capisca la procedura di sicurezza?",
      ],
      hint: "Essere convinto/a che triggers the congiuntivo of capire (capisca) here — dopo solo due giorni signals the speaker's doubt, exactly why convinto che needs the congiuntivo.",
      tags: ["opinion", "chunk", "essere convinto che", "capire"],
      tier: 3,
    },
    {
      id: "b133-t3-028",
      type: "produce",
      prompt: "We are convinced that the judge's decision to suspend the license is fair, given how many complaints the restaurant received.",
      accepted: ["Siamo convinti che la decisione del giudice di sospendere la licenza sia giusta, viste le tante segnalazioni ricevute dal ristorante."],
      hint: "Essere convinti che triggers the congiuntivo of essere (sia) here — viste le tante segnalazioni is a past-participle absolute, not another subjunctive clause.",
      tags: ["opinion", "chunk", "essere convinto che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-029",
      type: "produce",
      prompt: "I am convinced that my grandmother deserves respect for raising five children alone during the war.",
      accepted: [
        "Sono convinto che mia nonna meriti rispetto per aver cresciuto cinque figli da sola durante la guerra.",
        "Sono convinta che mia nonna meriti rispetto per aver cresciuto cinque figli da sola durante la guerra.",
      ],
      hint: "Essere convinto/a che triggers the congiuntivo of meritare (meriti) here — per aver cresciuto uses the past infinitive to give the reason, not a new clause.",
      tags: ["opinion", "chunk", "essere convinto che", "meritare"],
      tier: 3,
    },
    {
      id: "b133-t3-030",
      type: "produce",
      prompt: "I have the impression that he is hiding something.",
      accepted: ["Ho l'impressione che nasconda qualcosa."],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo of nascondere.",
      tags: ["opinion", "chunk", "avere l'impressione che", "nascondere"],
      tier: 3,
    },
    {
      id: "b133-t3-031",
      type: "produce",
      prompt: "We have the impression that today's meeting will be long, since the agenda has twelve items.",
      accepted: ["Abbiamo l'impressione che la riunione di oggi sia lunga, dato che l'ordine del giorno ha dodici punti."],
      hint: "Avere l'impressione che triggers the congiuntivo of essere (sia) here — dato che introduces the real reason in the indicativo (ha), a separate clause.",
      tags: ["opinion", "chunk", "avere l'impressione che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-032",
      type: "produce",
      prompt: "She has the impression that her boss doesn't trust her.",
      accepted: ["Ha l'impressione che il suo capo non si fidi di lei."],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo of fidarsi.",
      tags: ["opinion", "chunk", "avere l'impressione che", "fidarsi"],
      tier: 3,
    },
    {
      id: "b133-t3-033",
      type: "produce",
      prompt: "Returning to Turin after ten years, I have the impression that this city has changed a lot.",
      accepted: ["Tornando a Torino dopo dieci anni, ho l'impressione che questa città sia cambiata molto."],
      hint: "Avere l'impressione che triggers the congiuntivo passato (sia cambiata) here — tornando is a gerund modifying the whole sentence, not a subjunctive form.",
      tags: ["opinion", "chunk", "avere l'impressione che", "cambiare"],
      tier: 3,
    },
    {
      id: "b133-t3-034",
      type: "produce",
      prompt: "The new interns have the impression that nobody in the office understands them.",
      accepted: ["I nuovi stagisti hanno l'impressione che nessuno in ufficio li capisca."],
      hint: "Avere l'impressione che triggers the congiuntivo of capire (capisca) here — nessuno as subject still takes a singular verb form.",
      tags: ["opinion", "chunk", "avere l'impressione che", "capire"],
      tier: 3,
    },
    {
      id: "b133-t3-035",
      type: "produce",
      prompt: "Since your brother stopped answering his phone, do you have the impression that something is wrong?",
      accepted: ["Da quando tuo fratello ha smesso di rispondere al telefono, hai l'impressione che ci sia qualcosa che non va?"],
      hint: "Avere l'impressione che triggers the congiuntivo of esserci (ci sia) here — da quando introduces a real timeframe in the indicativo (ha smesso).",
      tags: ["opinion", "chunk", "avere l'impressione che", "esserci"],
      tier: 3,
    },
    {
      id: "b133-t3-036",
      type: "produce",
      prompt: "After seeing everyone's high scores, we have the impression that yesterday's exam was too easy.",
      accepted: ["Dopo aver visto i voti alti di tutti, abbiamo l'impressione che l'esame di ieri sia stato troppo facile."],
      hint: "Avere l'impressione che triggers the congiuntivo passato (sia stato) here — dopo aver visto uses the past infinitive for the reason, a separate construction.",
      tags: ["opinion", "chunk", "avere l'impressione che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-037",
      type: "produce",
      prompt: "Every time we invite him to a family dinner, I have the impression that he doesn't want to come.",
      accepted: ["Ogni volta che lo invitiamo a una cena di famiglia, ho l'impressione che non voglia venire."],
      hint: "Avere l'impressione che triggers the congiuntivo of volere (voglia) here — ogni volta che keeps the indicativo (invitiamo) in its own clause.",
      tags: ["opinion", "chunk", "avere l'impressione che", "volere"],
      tier: 3,
    },
    {
      id: "b133-t3-038",
      type: "produce",
      prompt: "Since starting the new treatment, she has the impression that her mother's situation is improving.",
      accepted: ["Da quando ha iniziato la nuova cura, ha l'impressione che la situazione di sua madre stia migliorando."],
      hint: "Avere l'impressione che triggers the congiuntivo progressivo (stia migliorando) here — da quando keeps the indicativo (ha iniziato) in its own clause.",
      tags: ["opinion", "chunk", "avere l'impressione che", "migliorare"],
      tier: 3,
    },
    {
      id: "b133-t3-039",
      type: "produce",
      prompt: "Watching the panel's faces during my presentation, I have the impression that they already know the answer to my question.",
      accepted: ["Osservando le facce della commissione durante la mia presentazione, ho l'impressione che sappiano già la risposta alla mia domanda."],
      hint: "Avere l'impressione che triggers the congiuntivo of sapere (sappiano) here — osservando is a gerund describing how the speaker forms this impression.",
      tags: ["opinion", "chunk", "avere l'impressione che", "sapere"],
      tier: 3,
    },
    {
      id: "b133-t3-040",
      type: "produce",
      prompt: "I imagine that the trip will be tiring.",
      accepted: ["Immagino che il viaggio sia faticoso."],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["opinion", "chunk", "immaginare che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-041",
      type: "produce",
      prompt: "Once the merger is announced tomorrow, we imagine that the news will surprise everyone in the office.",
      accepted: ["Una volta annunciata la fusione domani, immaginiamo che la notizia sorprenda tutti in ufficio."],
      hint: "Immaginare che triggers the congiuntivo of sorprendere (sorprenda) here — una volta annunciata is a past-participle clause, not another subjunctive.",
      tags: ["opinion", "chunk", "immaginare che", "sorprendere"],
      tier: 3,
    },
    {
      id: "b133-t3-042",
      type: "produce",
      prompt: "Since her final exams start Monday, I imagine that she is very busy this week.",
      accepted: ["Dato che i suoi esami finali iniziano lunedì, immagino che sia molto occupata questa settimana."],
      hint: "Immaginare che triggers the congiuntivo of essere (sia) here — dato che introduces the real reason in the indicativo (iniziano).",
      tags: ["opinion", "chunk", "immaginare che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-043",
      type: "produce",
      prompt: "Given how outdated the old system is, they imagine that migrating all the data will take months.",
      accepted: ["Considerando quanto è obsoleto il vecchio sistema, immaginano che migrare tutti i dati richieda mesi."],
      hint: "Immaginare che triggers the congiuntivo of richiedere (richieda) here — considerando introduces a real fact in the indicativo (è), not a second subjunctive clause.",
      tags: ["opinion", "chunk", "immaginare che", "richiedere"],
      tier: 3,
    },
    {
      id: "b133-t3-044",
      type: "produce",
      prompt: "Since his sister already called him, I imagine that he already knows the news about their father.",
      accepted: ["Dato che sua sorella lo ha già chiamato, immagino che sappia già la notizia riguardo a suo padre."],
      hint: "Immaginare che triggers the congiuntivo of sapere (sappia) here — dato che keeps the indicativo (ha chiamato) in its own clause.",
      tags: ["opinion", "chunk", "immaginare che", "sapere"],
      tier: 3,
    },
    {
      id: "b133-t3-045",
      type: "produce",
      prompt: "Since tickets sold out in ten minutes, we imagine that Saturday's concert will be crowded.",
      accepted: ["Dato che i biglietti sono finiti in dieci minuti, immaginiamo che il concerto di sabato sia affollato."],
      hint: "Immaginare che triggers the congiuntivo of essere (sia) here — dato che introduces the real reason in the indicativo (sono finiti).",
      tags: ["opinion", "chunk", "immaginare che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-046",
      type: "produce",
      prompt: "Given how strict this professor is, I imagine that the final exam will be difficult.",
      accepted: ["Visto quanto è severo questo professore, immagino che l'esame finale sia difficile."],
      hint: "Immaginare che triggers the congiuntivo of essere (sia) here — visto quanto è severo introduces the real reason in the indicativo.",
      tags: ["opinion", "chunk", "immaginare che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-047",
      type: "produce",
      prompt: "She imagines that her friends are worried about her.",
      accepted: ["Immagina che i suoi amici siano preoccupati per lei."],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo of essere, in the plural.",
      tags: ["opinion", "chunk", "immaginare che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-048",
      type: "produce",
      prompt: "Since their car broke down this morning, I imagine that they can't come to the party tonight.",
      accepted: ["Dato che la loro macchina si è rotta stamattina, immagino che non possano venire alla festa stasera."],
      hint: "Immaginare che triggers the congiuntivo of potere (possano) here — dato che keeps the indicativo (si è rotta) in its own clause.",
      tags: ["opinion", "chunk", "immaginare che", "potere"],
      tier: 3,
    },
    {
      id: "b133-t3-049",
      type: "produce",
      prompt: "Even though it's raining now, we imagine that the weather will improve before the wedding this weekend.",
      accepted: ["Anche se ora piove, immaginiamo che il tempo migliori prima del matrimonio questo fine settimana."],
      hint: "Immaginare che triggers the congiuntivo of migliorare (migliori) here — anche se keeps the indicativo (piove) in its own clause.",
      tags: ["opinion", "chunk", "immaginare che", "migliorare"],
      tier: 3,
    },
    {
      id: "b133-t3-050",
      type: "produce",
      prompt: "It's hard to imagine that everything changes so quickly.",
      accepted: ["È difficile immaginare che tutto cambi così in fretta."],
      hint: "Immaginare as a bare infinitive, still followed by che + congiuntivo.",
      tags: ["opinion", "chunk", "immaginare", "cambiare", "infinitive"],
      tier: 3,
    },
    {
      id: "b133-t3-051",
      type: "produce",
      prompt: "I suppose that the train is late.",
      accepted: ["Suppongo che il treno sia in ritardo."],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["opinion", "chunk", "supporre che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-052",
      type: "produce",
      prompt: "Since the journalist has been asking pointed questions, we suppose that they already know the truth about the scandal.",
      accepted: ["Dato che il giornalista ha fatto domande pungenti, supponiamo che sappiano già la verità sullo scandalo."],
      hint: "Supporre che triggers the congiuntivo of sapere (sappiano) here — dato che keeps the indicativo (ha fatto) in its own clause.",
      tags: ["opinion", "chunk", "supporre che", "sapere"],
      tier: 3,
    },
    {
      id: "b133-t3-053",
      type: "produce",
      prompt: "Since she has a fever, I suppose that she wants to stay home tonight instead of coming to the concert.",
      accepted: ["Dato che ha la febbre, suppongo che voglia restare a casa stasera invece di venire al concerto."],
      hint: "Supporre che triggers the congiuntivo of volere (voglia) here — dato che introduces the real reason in the indicativo (ha).",
      tags: ["opinion", "chunk", "supporre che", "volere"],
      tier: 3,
    },
    {
      id: "b133-t3-054",
      type: "produce",
      prompt: "Since today is a national holiday, they suppose that the bakery on the corner is closed.",
      accepted: ["Dato che oggi è festa nazionale, suppongono che il panificio all'angolo sia chiuso."],
      hint: "Supporre che triggers the congiuntivo of essere (sia) here — dato che keeps the indicativo (è) in its own clause.",
      tags: ["opinion", "chunk", "supporre che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-055",
      type: "produce",
      prompt: "Since he used to work as an electrician, I suppose that he can help us fix the wiring.",
      accepted: ["Dato che lavorava come elettricista, suppongo che possa aiutarci a sistemare l'impianto elettrico."],
      hint: "Supporre che triggers the congiuntivo of potere (possa) here — dato che introduces the reason in the indicativo (lavorava).",
      tags: ["opinion", "chunk", "supporre che", "potere"],
      tier: 3,
    },
    {
      id: "b133-t3-056",
      type: "produce",
      prompt: "Given the storm warning over the Alps, we suppose that tonight's flight to Milan will be delayed.",
      accepted: ["Vista l'allerta temporali sulle Alpi, supponiamo che il volo di stasera per Milano sia in ritardo."],
      hint: "Supporre che triggers the congiuntivo of essere (sia) here — vista l'allerta is a past-participle absolute construction, not another subjunctive.",
      tags: ["opinion", "chunk", "supporre che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-057",
      type: "produce",
      prompt: "Since their car isn't in the driveway anymore, I suppose that they already left for the airport.",
      accepted: ["Dato che la loro macchina non è più nel vialetto, suppongo che siano già partiti per l'aeroporto."],
      hint: "Supporre che triggers the congiuntivo passato (siano partiti) here — dato che keeps the indicativo (è) in its own clause.",
      tags: ["opinion", "chunk", "supporre che", "essere"],
      tier: 3,
    },
    {
      id: "b133-t3-058",
      type: "produce",
      prompt: "She supposes that her sister forgot the appointment.",
      accepted: ["Suppone che sua sorella abbia dimenticato l'appuntamento."],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo passato (abbia dimenticato).",
      tags: ["opinion", "chunk", "supporre che", "dimenticare"],
      tier: 3,
    },
    {
      id: "b133-t3-059",
      type: "produce",
      prompt: "Given how many items are on today's agenda, I suppose that the meeting will end late.",
      accepted: ["Visti tutti i punti all'ordine del giorno di oggi, suppongo che la riunione finisca tardi."],
      hint: "Supporre che triggers the congiuntivo of finire (finisca) here — visti tutti i punti is a past-participle absolute, not another subjunctive clause.",
      tags: ["opinion", "chunk", "supporre che", "finire"],
      tier: 3,
    },
    {
      id: "b133-t3-060",
      type: "produce",
      prompt: "Since the report was published this morning without any complaints, we suppose that nobody noticed the mistake in the numbers.",
      accepted: ["Dato che il rapporto è stato pubblicato stamattina senza reclami, supponiamo che nessuno abbia notato l'errore nei numeri."],
      hint: "Supporre che triggers the congiuntivo passato (abbia notato) here — dato che keeps the indicativo (è stato pubblicato) in its own clause.",
      tags: ["opinion", "chunk", "supporre che", "notare"],
      tier: 3,
    },
    {
      id: "b133-t3-061",
      type: "produce",
      prompt: "We can't simply suppose that everything will be fine.",
      accepted: ["Non possiamo semplicemente supporre che tutto vada bene."],
      hint: "Supporre as a bare infinitive after a modal verb, still followed by che + congiuntivo.",
      tags: ["opinion", "chunk", "supporre", "andare", "infinitive"],
      tier: 3,
    },
    {
      id: "b133-t3-062",
      type: "produce",
      prompt: "In my view, the government should act quickly.",
      accepted: ["A mio avviso, il governo dovrebbe agire rapidamente."],
      hint: "A mio avviso takes the condizionale here, not the congiuntivo.",
      tags: ["opinion", "chunk", "a mio avviso", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-063",
      type: "produce",
      prompt: "In her view, the contract is unclear.",
      accepted: ["A suo avviso, il contratto non è chiaro."],
      hint: "A suo avviso takes the indicativo presente here, never the congiuntivo.",
      tags: ["opinion", "chunk", "a suo avviso", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-064",
      type: "produce",
      prompt: "I would like to know your opinion on this topic.",
      accepted: ["Vorrei conoscere il tuo parere su questo argomento."],
      hint: "Il parere = the opinion (formal register).",
      tags: ["opinion", "chunk", "il parere"],
      tier: 3,
    },
    {
      id: "b133-t3-065",
      type: "recognize",
      prompt: "dare il proprio parere",
      accepted: ["to give one's opinion"],
      hint: "A common collocation with il parere.",
      tags: ["opinion", "chunk", "il parere", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-066",
      type: "produce",
      prompt: "The expert gave his opinion on the new law.",
      accepted: ["L'esperto ha dato il suo parere sulla nuova legge."],
      hint: "Dare il proprio/suo parere su qualcosa.",
      tags: ["opinion", "chunk", "il parere", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-067",
      type: "recognize",
      prompt: "cambiare parere",
      accepted: ["to change one's mind"],
      hint: "Another common collocation with parere.",
      tags: ["opinion", "chunk", "il parere", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-068",
      type: "produce",
      prompt: "I changed my mind after talking to her.",
      accepted: ["Ho cambiato parere dopo aver parlato con lei."],
      hint: "Cambiare parere = to change one's mind.",
      tags: ["opinion", "chunk", "il parere", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-069",
      type: "produce",
      prompt: "This is just a supposition, not a certainty.",
      accepted: ["Questa è solo una supposizione, non una certezza."],
      hint: "La supposizione = the assumption, the noun form of supporre.",
      tags: ["opinion", "chunk", "la supposizione"],
      tier: 3,
    },
    {
      id: "b133-t3-070",
      type: "produce",
      prompt: "His theory is based on a wrong assumption.",
      accepted: ["La sua teoria si basa su una supposizione sbagliata."],
      hint: "Basarsi su una supposizione = to be based on an assumption.",
      tags: ["opinion", "chunk", "la supposizione", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-071",
      type: "produce",
      prompt: "Children have a lot of imagination.",
      accepted: ["I bambini hanno molta immaginazione."],
      hint: "Avere immaginazione = to have imagination.",
      tags: ["opinion", "chunk", "l'immaginazione"],
      tier: 3,
    },
    {
      id: "b133-t3-072",
      type: "produce",
      prompt: "This story is pure imagination.",
      accepted: ["Questa storia è pura immaginazione."],
      hint: "Pura immaginazione = pure imagination, a common phrase.",
      tags: ["opinion", "chunk", "l'immaginazione"],
      tier: 3,
    },
    {
      id: "b133-t3-073",
      type: "recognize",
      prompt: "avere fantasia e immaginazione",
      accepted: ["to have creativity and imagination"],
      hint: "A common paired collocation.",
      tags: ["opinion", "chunk", "l'immaginazione", "collocation"],
      tier: 3,
    },
    {
      id: "b133-t3-074",
      type: "produce",
      prompt: "In his view, the project needs more funding.",
      accepted: ["A suo avviso, il progetto ha bisogno di più finanziamenti."],
      hint: "A suo avviso takes the indicativo presente here, never the congiuntivo.",
      tags: ["opinion", "chunk", "a suo avviso", "no-subjunctive"],
      tier: 3,
    },
    {
      id: "b133-t3-075",
      type: "produce",
      prompt: "In my view, this rule should change.",
      accepted: ["A mio avviso, questa regola dovrebbe cambiare."],
      hint: "A mio avviso takes the condizionale here, not the congiuntivo.",
      tags: ["opinion", "chunk", "a mio avviso", "no-subjunctive"],
      tier: 3,
    },

    // ── Tier 4 – Passages ──────────────────────────────────────────────────────
    {
      id: "b133-t4-001",
      type: "passage_cloze",
      prompt:
        "Marco lavora in un ufficio con molti colleghi diversi.\nRitiene che il suo capo ___ una persona giusta, anche se a volte prende decisioni difficili.\nDurante l'ultima riunione, ha spiegato ai colleghi perché riteneva importante ascoltare tutti prima di agire.\nMolti hanno apprezzato questo atteggiamento aperto e sincero.\nMarco pensa che un buon ambiente di lavoro dipenda soprattutto dal rispetto reciproco tra le persone.",
      accepted: ["sia"],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo presente of essere: il capo requires sia.",
      tags: ["opinion", "passage_cloze", "ritenere che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-013", "b133-t1-014", "b133-t2-003"],
    },
    {
      id: "b133-t4-002",
      type: "passage_cloze",
      prompt:
        "Anna sta organizzando un viaggio a Roma con due amiche.\nSecondo lei, la primavera ___ il periodo migliore per visitare la città, perché non fa troppo caldo e ci sono meno turisti.\nLe sue amiche invece pensano che l'autunno sia altrettanto bello, con colori caldi e giornate più tranquille.\nDopo una lunga discussione, decidono di prenotare il viaggio per il mese di aprile, quando il tempo è generalmente stabile.",
      accepted: ["è"],
      hint: "Secondo lei takes the indicativo, not the congiuntivo — è, not sia.",
      tags: ["opinion", "passage_cloze", "secondo lei", "essere", "no-subjunctive", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-007", "b133-t1-008"],
    },
    {
      id: "b133-t4-003",
      type: "passage_cloze",
      prompt:
        "Durante la cena di famiglia, si parla spesso del futuro dei figli.\nLa nonna è convinta che suo nipote ___ una carriera importante, perché ha sempre lavorato con passione e dedizione.\nIl padre invece preferisce non fare previsioni troppo ottimistiche.\nNonostante le opinioni diverse, tutti sono d'accordo che il ragazzo abbia talento e voglia di imparare.\nLa cena finisce con una lunga chiacchierata piena di speranze per il domani.",
      accepted: ["abbia"],
      hint: "Essere convinta che always triggers the congiuntivo — here, the congiuntivo of avere (avere una carriera).",
      tags: ["opinion", "passage_cloze", "essere convinto che", "avere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-015", "b133-t1-016", "b133-t2-040"],
    },
    {
      id: "b133-t4-004",
      type: "passage_cloze",
      prompt:
        "Da qualche settimana, Sara ha problemi a dormire bene la notte.\nHa l'impressione che i nuovi vicini ___ troppo rumore dopo la mezzanotte, soprattutto nei fine settimana.\nHa provato a parlare gentilmente con loro, ma la situazione non è cambiata molto.\nAlcuni amici le hanno consigliato di scrivere una lettera formale all'amministratore del palazzo.\nSara spera di risolvere il problema senza creare tensioni con i vicini.",
      accepted: ["facciano"],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo of fare: i vicini requires facciano.",
      tags: ["opinion", "passage_cloze", "avere l'impressione che", "fare", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-046"],
    },
    {
      id: "b133-t4-005",
      type: "passage_cloze",
      prompt:
        "Luca sta pianificando un viaggio in montagna con alcuni amici per l'estate prossima.\nImmagina che il percorso ___ piuttosto impegnativo, perché include diverse ore di camminata ogni giorno.\nPer questo motivo, ha deciso di allenarsi ogni settimana in palestra e di fare lunghe passeggiate nel weekend.\nI suoi amici condividono lo stesso entusiasmo e stanno già organizzando l'attrezzatura necessaria per il viaggio.\nTutti non vedono l'ora di partire.",
      accepted: ["sia"],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo of essere: il percorso requires sia.",
      tags: ["opinion", "passage_cloze", "immaginare che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-017", "b133-t1-018"],
    },
    {
      id: "b133-t4-006",
      type: "passage_cloze",
      prompt:
        "Prima di partire per il mare, Elena controlla sempre le previsioni del tempo.\nSuppone che il tempo ___ buono per tutto il weekend, dato che le previsioni indicano cielo sereno e temperature miti.\nTuttavia, decide comunque di portare un ombrello, perché il meteo in questa zona cambia spesso all'improvviso.\nI suoi amici la prendono in giro per questa abitudine, ma lei preferisce essere prudente.",
      accepted: ["sia"],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo of essere: il tempo requires sia.",
      tags: ["opinion", "passage_cloze", "supporre che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-019", "b133-t1-020"],
    },
    {
      id: "b133-t4-007",
      type: "passage_cloze",
      prompt:
        "Prima dell'esame di fine anno, gli studenti discutono spesso del programma da studiare.\nIl professore ritiene che l'esame ___ molta preparazione, soprattutto per la parte di grammatica avanzata.\nAlcuni studenti si sentono già pronti, mentre altri preferiscono ripassare ogni argomento più volte.\nNonostante la tensione generale, la maggior parte della classe si impegna con serietà per ottenere un buon risultato finale.",
      accepted: ["richieda"],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of richiedere.",
      tags: ["opinion", "passage_cloze", "ritenere che", "richiedere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-004"],
    },
    {
      id: "b133-t4-008",
      type: "passage_cloze",
      prompt:
        "Giulia e Marco discutono spesso di politica durante le loro cene tra amici.\nSecondo lui, il nuovo piano economico ___ vantaggi soprattutto per le piccole imprese locali.\nGiulia invece pensa che i benefici siano minimi e che il governo debba fare di più per i giovani.\nNonostante le opinioni opposte, i due riescono sempre a discutere con rispetto, senza litigare veramente.",
      accepted: ["porta"],
      hint: "Secondo lui takes the indicativo of portare here, never the congiuntivo.",
      tags: ["opinion", "passage_cloze", "secondo lui", "portare", "no-subjunctive", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-005", "b133-t1-006"],
    },
    {
      id: "b133-t4-009",
      type: "passage_cloze",
      prompt:
        "Paolo sta per aprire un piccolo ristorante nel centro della città.\nÈ convinto che il locale ___ successo, grazie alla qualità dei piatti e all'atmosfera accogliente che ha creato con cura.\nI suoi amici lo sostengono e alcuni hanno già prenotato un tavolo per la serata di apertura.\nPaolo sa che il primo periodo sarà impegnativo, ma crede fermamente nel suo progetto e nella sua squadra di cucina.",
      accepted: ["abbia"],
      hint: "Essere convinto che always triggers the congiuntivo — here, the congiuntivo of avere (avere successo).",
      tags: ["opinion", "passage_cloze", "essere convinto che", "avere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-039"],
    },
    {
      id: "b133-t4-010",
      type: "passage_cloze",
      prompt:
        "Dopo il colloquio di lavoro, Chiara torna a casa pensierosa.\nHa l'impressione che l'intervista ___ andata abbastanza bene, anche se non ha risposto perfettamente a tutte le domande.\nI selezionatori sembravano interessati alla sua esperienza precedente e le hanno fatto molte domande specifiche sul progetto che aveva presentato.\nChiara aspetta con ansia la risposta, sperando di ricevere presto buone notizie.",
      accepted: ["sia"],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo passato (sia andata).",
      tags: ["opinion", "passage_cloze", "avere l'impressione che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-045"],
    },
    {
      id: "b133-t4-011",
      type: "passage_cloze",
      prompt:
        "Ogni giorno i telegiornali parlano dei cambiamenti climatici e delle loro conseguenze.\nMolti esperti immaginano che la situazione ___ ulteriormente nei prossimi decenni, se non si adottano misure urgenti a livello internazionale.\nPer questo motivo, diverse organizzazioni ambientali stanno lavorando per sensibilizzare i cittadini sull'importanza di ridurre i consumi energetici.\nAlcuni governi hanno già iniziato a investire in energie rinnovabili.",
      accepted: ["peggiori"],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo of peggiorare.",
      tags: ["opinion", "passage_cloze", "immaginare che", "peggiorare", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-010"],
    },
    {
      id: "b133-t4-012",
      type: "passage_cloze",
      prompt:
        "All'aeroporto, molti passeggeri aspettano notizie sul loro volo per Milano.\nSuppongono che il ritardo ___ causato dal maltempo, visto che fuori piove molto forte da questa mattina.\nIl personale dell'aeroporto ha annunciato solo che il volo partirà con qualche ora di ritardo, senza dare ulteriori dettagli.\nAlcuni passeggeri decidono di prendere un caffè al bar, mentre altri controllano continuamente il proprio telefono.",
      accepted: ["sia"],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo passivo (sia causato).",
      tags: ["opinion", "passage_cloze", "supporre che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-018"],
    },
    {
      id: "b133-t4-013",
      type: "passage_cloze",
      prompt:
        "Federico deve decidere quale università frequentare dopo il diploma.\nA mio avviso, la scelta dipende soprattutto dagli interessi personali e dalle opportunità future.\nIl suo professore ritiene che un anno di esperienza all'estero ___ molto la sua formazione, sia dal punto di vista linguistico che culturale.\nFederico sta valutando questa possibilità con attenzione, parlando anche con studenti che hanno già vissuto un'esperienza simile.",
      accepted: ["aiuti"],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of aiutare.",
      tags: ["opinion", "passage_cloze", "ritenere che", "aiutare", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-023", "b133-t1-024"],
    },
    {
      id: "b133-t4-014",
      type: "passage_cloze",
      prompt:
        "Al bar sotto casa, un gruppo di amici discute spesso delle ultime notizie politiche.\nSecondo me, i giornali ___ troppa attenzione agli scandali e poca ai problemi reali dei cittadini.\nSecondo loro invece, la stampa fa semplicemente il suo lavoro, informando la gente di ciò che accade.\nLa discussione continua per un'ora, tra caffè e opinioni diverse, senza che nessuno riesca a convincere l'altro.",
      accepted: ["danno"],
      hint: "Secondo me takes the indicativo of dare here (danno), never the congiuntivo.",
      tags: ["opinion", "passage_cloze", "secondo me", "dare", "no-subjunctive", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-001", "b133-t1-002", "b133-t1-011", "b133-t1-012"],
    },
    {
      id: "b133-t4-015",
      type: "passage_cloze",
      prompt:
        "Dopo le analisi del sangue, il medico chiama Roberto per un controllo.\nÈ convinto che tutto ___ nella norma, ma preferisce comunque prescrivere qualche esame in più per sicurezza.\nRoberto, un po' preoccupato, decide di seguire il consiglio senza discutere.\nDopo qualche giorno, i risultati confermano che il medico aveva ragione e che non c'è nulla di cui preoccuparsi.",
      accepted: ["sia"],
      hint: "Essere convinto che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["opinion", "passage_cloze", "essere convinto che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-039"],
    },
    {
      id: "b133-t4-016",
      type: "passage_cloze",
      prompt:
        "Marta e suo marito stanno cercando un nuovo appartamento in centro.\nHanno l'impressione che il prezzo di questa zona ___ troppo alto rispetto alla qualità degli edifici disponibili.\nPer questo motivo, hanno deciso di allargare la ricerca anche ai quartieri più periferici, dove i prezzi sono più accessibili.\nLa loro agente immobiliare li aiuta a confrontare diverse opzioni ogni settimana.",
      accepted: ["sia"],
      hint: "Avere l'impressione che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["opinion", "passage_cloze", "avere l'impressione che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-050"],
    },
    {
      id: "b133-t4-017",
      type: "passage_cloze",
      prompt:
        "Ogni mese, Valentina scrive recensioni di libri per un blog culturale.\nNel suo ultimo articolo, dà il proprio parere su un romanzo molto discusso quest'anno.\nImmagina che la trama ___ piaciuta a molti lettori, grazie ai personaggi complessi e alla scrittura scorrevole.\nTuttavia, aggiunge anche qualche critica sul finale, che secondo lei risulta un po' affrettato rispetto al resto della storia.",
      accepted: ["sia"],
      hint: "Immaginare che always triggers the congiuntivo — here, the congiuntivo passato (sia piaciuta), agreeing with trama.",
      tags: ["opinion", "passage_cloze", "immaginare che", "piacere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-021", "b133-t1-022"],
    },
    {
      id: "b133-t4-018",
      type: "passage_cloze",
      prompt:
        "Prima della partita più importante della stagione, i tifosi sono molto emozionati.\nL'allenatore suppone che la sua squadra ___ questa partita, grazie alla buona forma fisica mostrata nelle ultime settimane.\nGli avversari però sono forti e hanno vinto le ultime tre partite consecutive.\nI giocatori si preparano con concentrazione, consapevoli che ogni dettaglio può fare la differenza sul campo.",
      accepted: ["vinca"],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo of vincere.",
      tags: ["opinion", "passage_cloze", "supporre che", "vincere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t2-013"],
    },
    {
      id: "b133-t4-019",
      type: "passage_cloze",
      prompt:
        "Chiara ha fondato una piccola startup che produce prodotti ecologici per la casa.\nRitiene che il mercato ___ sempre più interessato a soluzioni sostenibili, soprattutto tra i consumatori più giovani.\nPer questo motivo, ha deciso di investire tutti i suoi risparmi nel progetto, nonostante i rischi.\nI suoi collaboratori condividono la stessa visione e lavorano insieme con grande motivazione ogni giorno.",
      accepted: ["sia"],
      hint: "Ritenere che always triggers the congiuntivo — here, the congiuntivo of essere.",
      tags: ["opinion", "passage_cloze", "ritenere che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-013", "b133-t1-014"],
    },
    {
      id: "b133-t4-020",
      type: "passage_cloze",
      prompt:
        "Ogni estate, la famiglia Rossi organizza una grande riunione al mare.\nSecondo noi, quest'anno la festa dovrebbe essere ancora più speciale, perché festeggiamo anche gli ottant'anni della nonna.\nSupponiamo che tutti i parenti ___ partecipare, anche quelli che vivono all'estero da anni.\nI preparativi sono già iniziati, con inviti, decorazioni e un menù pensato per accontentare grandi e piccini.",
      accepted: ["vogliano"],
      hint: "Supporre che always triggers the congiuntivo — here, the congiuntivo of volere.",
      tags: ["opinion", "passage_cloze", "supporre che", "volere", "tier4"],
      tier: 4,
      prerequisites: ["b133-t1-009", "b133-t1-010", "b133-t2-016"],
    },
  ],
};
export default unit;
