import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-32-social",
  name: "Relationships & Values",
  level: "B1",
  theme: "Social Life & Human Values",
  emoji: "🤝",
  prerequisiteUnits: ["b1-unit-31-materials"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "b132-t1-001",
      type: "recognize",
      prompt: "l'amicizia",
      accepted: ["friendship"],
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-002",
      type: "recognize",
      prompt: "la fiducia",
      accepted: ["trust", "confidence"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-003",
      type: "produce",
      prompt: "respect",
      accepted: ["il rispetto"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-004",
      type: "recognize",
      prompt: "la lealtà",
      accepted: ["loyalty", "faithfulness"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-005",
      type: "produce",
      prompt: "jealousy",
      accepted: ["la gelosia"],
      hint: "also used for possessiveness in relationships",
      tags: ["social", "emotion", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-006",
      type: "recognize",
      prompt: "l'invidia",
      accepted: ["envy", "jealousy"],
      hint: "wanting what someone else has — different from 'gelosia'",
      tags: ["social", "emotion", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-007",
      type: "produce",
      prompt: "betrayal",
      accepted: ["il tradimento"],
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-008",
      type: "recognize",
      prompt: "il perdono",
      accepted: ["forgiveness", "pardon"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-009",
      type: "produce",
      prompt: "reconciliation",
      accepted: ["la riconciliazione"],
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-010",
      type: "recognize",
      prompt: "la solidarietà",
      accepted: ["solidarity"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-011",
      type: "produce",
      prompt: "generosity",
      accepted: ["la generosità"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-012",
      type: "recognize",
      prompt: "l'egoismo",
      accepted: ["selfishness", "egoism"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-013",
      type: "produce",
      prompt: "kindness",
      accepted: ["la gentilezza"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-014",
      type: "recognize",
      prompt: "la cortesia",
      accepted: ["courtesy", "politeness"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-015",
      type: "produce",
      prompt: "rudeness / bad manners",
      accepted: ["la maleducazione"],
      hint: "the noun from 'maleducato' (rude/ill-mannered)",
      tags: ["social", "behaviour", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-016",
      type: "recognize",
      prompt: "la comprensione",
      accepted: ["understanding", "comprehension"],
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-017",
      type: "produce",
      prompt: "conflict",
      accepted: ["il conflitto"],
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-018",
      type: "recognize",
      prompt: "l'accordo",
      accepted: ["agreement", "accord"],
      hint: "'essere d'accordo' means to agree",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-019",
      type: "produce",
      prompt: "disagreement",
      accepted: ["il disaccordo"],
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-020",
      type: "recognize",
      prompt: "il compromesso",
      accepted: ["compromise"],
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-021",
      type: "produce",
      prompt: "quarrel / argument / fight",
      accepted: ["il litigio"],
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-022",
      type: "recognize",
      prompt: "il rapporto",
      accepted: ["relationship", "rapport", "relation"],
      hint: "more neutral than 'relazione'; often used for working or social ties",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-023",
      type: "produce",
      prompt: "bond / tie (between people)",
      accepted: ["il legame"],
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },

    // ── Tier 2 – Grammar / Fill-blank ────────────────────────────────────────
    {
      id: "b132-t2-001",
      type: "fill_blank",
      prompt: "Non ho molta fiducia ___ lui — mi ha già deluso una volta.",
      accepted: ["in"],
      hint: "'avere fiducia in qualcuno' — trust takes the preposition 'in'",
      tags: ["fill_blank", "preposition", "fiducia"],
      tier: 2,
    },
    {
      id: "b132-t2-002",
      type: "fill_blank",
      prompt: "Ieri i due ragazzi hanno fatto ___ botte davanti alla scuola.",
      accepted: ["a"],
      hint: "'fare a botte' is an idiomatic phrase meaning to come to blows / have a fight",
      tags: ["fill_blank", "idiom", "conflict"],
      tier: 2,
    },
    {
      id: "b132-t2-003",
      type: "fill_blank",
      prompt: "Non vado d'accordo ___ mio fratello — siamo troppo diversi.",
      accepted: ["con"],
      hint: "'andare d'accordo con qualcuno' — to get along with someone",
      tags: ["fill_blank", "preposition", "accordo"],
      tier: 2,
    },
    {
      id: "b132-t2-004",
      type: "fill_blank",
      prompt: "Ho molto rispetto ___ persone oneste e leali.",
      accepted: ["per"],
      hint: "'rispetto per' — respect for someone uses the preposition 'per'",
      tags: ["fill_blank", "preposition", "rispetto"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ─────────────────────────────────────────────
    {
      id: "b132-t3-001",
      type: "produce",
      prompt: "They made up after the argument.",
      accepted: [
        "Si sono riconciliati dopo il litigio.",
        "Si sono riconciliate dopo il litigio.",
        "Si sono fatti la pace dopo il litigio.",
        "Si sono fatte la pace dopo il litigio.",
        "Hanno fatto la pace dopo il litigio.",
      ],
      hint: "use 'riconciliarsi' or the idiom 'fare la pace'; passato prossimo",
      tags: ["chunk", "conflict", "reconciliation", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "b132-t3-002",
      type: "produce",
      prompt: "I value loyalty in a friend.",
      accepted: [
        "Apprezzo la lealtà in un amico.",
        "Per me la lealtà è importante in un amico.",
        "Valuto molto la lealtà in un amico.",
        "Do molto valore alla lealtà in un amico.",
      ],
      hint: "use 'apprezzare' or 'dare valore a' to express valuing something",
      tags: ["chunk", "value", "loyalty"],
      tier: 3,
    },
    {
      id: "b132-t3-003",
      type: "produce",
      prompt: "She apologized and asked for forgiveness.",
      accepted: [
        "Si è scusata e ha chiesto perdono.",
        "Si è scusata e ha chiesto il perdono.",
        "Ha chiesto scusa e ha chiesto perdono.",
      ],
      hint: "'scusarsi' (reflexive) or 'chiedere scusa' for apologising; 'chiedere perdono' for asking forgiveness",
      tags: ["chunk", "forgiveness", "apology", "passato-prossimo"],
      tier: 3,
    },
    {
      id: "b132-t3-004",
      type: "produce",
      prompt: "Jealousy destroys relationships.",
      accepted: [
        "La gelosia distrugge i rapporti.",
        "La gelosia distrugge le relazioni.",
        "La gelosia rovina i rapporti.",
        "La gelosia rovina le relazioni.",
      ],
      hint: "use 'distruggere' or 'rovinare'; present tense for general truths",
      tags: ["chunk", "jealousy", "relationship"],
      tier: 3,
    },
    {
      id: "b132-t3-005",
      type: "produce",
      prompt: "A good compromise is better than a bad victory.",
      accepted: [
        "Un buon compromesso è meglio di una cattiva vittoria.",
        "Un buon compromesso vale più di una cattiva vittoria.",
      ],
      hint: "use 'meglio di' (better than) or 'valere più di' (worth more than)",
      tags: ["chunk", "compromise", "proverb", "comparison"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "b132-t4-001",
      type: "passage_cloze",
      prompt: "Luca e Matteo erano amici da vent'anni.\nQualche mese fa hanno avuto un litigio serio: Matteo aveva rivelato un segreto di Luca a tutta la comitiva, e Luca si era sentito tradito.\nPer settimane non si sono parlati, e Luca ha pensato che il ___ fosse finito per sempre.\nPoi, un giorno, Matteo è andato a casa sua e ha chiesto perdono con sincerità.\nLuca ha capito che l'amicizia vera vale più dell'orgoglio e ha deciso di perdonarlo.\nOggi i due hanno un rapporto ancora più solido di prima, costruito su una nuova fiducia reciproca.",
      accepted: ["rapporto", "legame"],
      hint: "the word refers to their long-standing connection or tie — it felt as though it had ended forever",
      tags: ["passage_cloze", "friendship", "conflict", "reconciliation"],
      tier: 4,
      prerequisites: ["b132-t1-007", "b132-t1-008", "b132-t1-018", "b132-t1-023"],
    },

    // ── Tier 1 – Vocabulary (expansion: trust, betrayal, honesty) ────────────
    {
      id: "b132-t1-024",
      type: "recognize",
      prompt: "fidarsi (di qualcuno)",
      accepted: ["to trust (someone)"],
      hint: "reflexive verb; 'fidarsi di' + person — to trust someone",
      tags: ["social", "trust", "verb", "reflexive"],
      tier: 1,
    },
    {
      id: "b132-t1-025",
      type: "produce",
      prompt: "to trust (someone)",
      accepted: ["fidarsi (di qualcuno)", "fidarsi di qualcuno"],
      hint: "reflexive 'fidarsi' + 'di' + person",
      tags: ["social", "trust", "verb", "reflexive"],
      tier: 1,
    },
    {
      id: "b132-t1-026",
      type: "recognize",
      prompt: "diffidare (di qualcuno)",
      accepted: ["to distrust (someone)", "to be wary (of someone)"],
      hint: "verb; 'diffidare di' — to distrust or be wary of someone",
      tags: ["social", "trust", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-027",
      type: "produce",
      prompt: "to distrust (someone)",
      accepted: ["diffidare (di qualcuno)", "diffidare di qualcuno"],
      hint: "'diffidare di' + person",
      tags: ["social", "trust", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-028",
      type: "recognize",
      prompt: "deludere",
      accepted: ["to disappoint"],
      hint: "transitive verb — to let someone down",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-029",
      type: "produce",
      prompt: "to disappoint",
      accepted: ["deludere"],
      hint: "'deludere' — direct object, no preposition",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-030",
      type: "recognize",
      prompt: "la delusione",
      accepted: ["disappointment"],
      hint: "feminine noun from 'deludere'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-031",
      type: "produce",
      prompt: "disappointment",
      accepted: ["la delusione"],
      hint: "feminine noun 'la delusione'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-032",
      type: "recognize",
      prompt: "il segreto",
      accepted: ["secret", "the secret"],
      hint: "masculine noun — something kept hidden",
      tags: ["social", "trust", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-033",
      type: "produce",
      prompt: "secret",
      accepted: ["il segreto"],
      hint: "masculine noun 'il segreto'",
      tags: ["social", "trust", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-034",
      type: "recognize",
      prompt: "confidare (a qualcuno)",
      accepted: ["to confide (in someone)"],
      hint: "verb; 'confidare qualcosa a qualcuno' — to confide",
      tags: ["social", "trust", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-035",
      type: "produce",
      prompt: "to confide (in someone)",
      accepted: ["confidare (a qualcuno)", "confidare a qualcuno"],
      hint: "'confidare' + 'a' + person",
      tags: ["social", "trust", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-036",
      type: "recognize",
      prompt: "la confidenza",
      accepted: ["familiarity", "closeness (between people)"],
      hint: "feminine noun — closeness/familiarity, not to be confused with 'la fiducia' (trust)",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-037",
      type: "produce",
      prompt: "closeness / familiarity (between people)",
      accepted: ["la confidenza"],
      hint: "feminine noun 'la confidenza'",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-038",
      type: "recognize",
      prompt: "il rancore",
      accepted: ["resentment", "grudge"],
      hint: "masculine noun — a lingering grudge",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-039",
      type: "produce",
      prompt: "resentment / grudge",
      accepted: ["il rancore"],
      hint: "masculine noun 'il rancore'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-040",
      type: "recognize",
      prompt: "l'appoggio",
      accepted: ["support (moral or emotional)"],
      hint: "masculine noun starting with a vowel — moral or emotional support",
      tags: ["social", "support", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-041",
      type: "produce",
      prompt: "support (moral, emotional)",
      accepted: ["l'appoggio"],
      hint: "masculine noun 'l'appoggio'",
      tags: ["social", "support", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-042",
      type: "recognize",
      prompt: "appoggiare",
      accepted: ["to support / back (someone)"],
      hint: "transitive verb — to back or support someone",
      tags: ["social", "support", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-043",
      type: "produce",
      prompt: "to support (someone)",
      accepted: ["appoggiare"],
      hint: "'appoggiare' — direct object, no preposition",
      tags: ["social", "support", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-044",
      type: "recognize",
      prompt: "contare su (qualcuno)",
      accepted: ["to count on (someone)"],
      hint: "verb phrase — to rely on someone",
      tags: ["social", "support", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-045",
      type: "produce",
      prompt: "to count on (someone)",
      accepted: ["contare su (qualcuno)", "contare su qualcuno"],
      hint: "'contare su' + person",
      tags: ["social", "support", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-046",
      type: "recognize",
      prompt: "la lontananza",
      accepted: ["distance", "being apart"],
      hint: "feminine noun — physical or emotional distance",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-047",
      type: "produce",
      prompt: "distance / being apart",
      accepted: ["la lontananza"],
      hint: "feminine noun 'la lontananza'",
      tags: ["social", "relationship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-048",
      type: "recognize",
      prompt: "mantenere",
      accepted: ["to maintain", "to keep up"],
      hint: "verb — to keep something going over time",
      tags: ["social", "relationship", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-049",
      type: "produce",
      prompt: "to maintain / keep up",
      accepted: ["mantenere"],
      hint: "'mantenere' — irregular like 'tenere'",
      tags: ["social", "relationship", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-050",
      type: "recognize",
      prompt: "stringere (un legame)",
      accepted: ["to forge (a bond)", "to form (a bond)"],
      hint: "verb phrase — to forge a bond",
      tags: ["social", "relationship", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-051",
      type: "produce",
      prompt: "to forge a bond",
      accepted: ["stringere un legame"],
      hint: "'stringere un legame'",
      tags: ["social", "relationship", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-052",
      type: "recognize",
      prompt: "rafforzare",
      accepted: ["to strengthen"],
      hint: "verb — to make stronger",
      tags: ["social", "relationship", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-053",
      type: "produce",
      prompt: "to strengthen",
      accepted: ["rafforzare"],
      hint: "'rafforzare'",
      tags: ["social", "relationship", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-054",
      type: "recognize",
      prompt: "incrinare (un rapporto)",
      accepted: ["to crack (a relationship)", "to strain (a relationship)"],
      hint: "verb phrase — to crack or strain a relationship",
      tags: ["social", "conflict", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-055",
      type: "produce",
      prompt: "to strain a relationship",
      accepted: ["incrinare un rapporto"],
      hint: "'incrinare un rapporto'",
      tags: ["social", "conflict", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-056",
      type: "recognize",
      prompt: "guastare",
      accepted: ["to spoil", "to ruin"],
      hint: "verb — to spoil or ruin",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-057",
      type: "produce",
      prompt: "to spoil / ruin",
      accepted: ["guastare"],
      hint: "'guastare'",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-058",
      type: "recognize",
      prompt: "riparare (un rapporto)",
      accepted: ["to repair (a relationship)", "to mend (a relationship)"],
      hint: "verb phrase — to repair a relationship",
      tags: ["social", "reconciliation", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-059",
      type: "produce",
      prompt: "to repair a relationship",
      accepted: ["riparare un rapporto"],
      hint: "'riparare un rapporto'",
      tags: ["social", "reconciliation", "verb-phrase"],
      tier: 1,
    },
    {
      id: "b132-t1-060",
      type: "recognize",
      prompt: "il malinteso",
      accepted: ["misunderstanding"],
      hint: "masculine noun — a misunderstanding",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-061",
      type: "produce",
      prompt: "misunderstanding",
      accepted: ["il malinteso"],
      hint: "masculine noun 'il malinteso'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-062",
      type: "recognize",
      prompt: "chiarire",
      accepted: ["to clarify"],
      hint: "verb — to clear something up",
      tags: ["social", "reconciliation", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-063",
      type: "produce",
      prompt: "to clarify",
      accepted: ["chiarire"],
      hint: "'chiarire'",
      tags: ["social", "reconciliation", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-064",
      type: "recognize",
      prompt: "l'errore",
      accepted: ["mistake", "error"],
      hint: "masculine noun starting with a vowel — a mistake",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-065",
      type: "produce",
      prompt: "mistake",
      accepted: ["l'errore"],
      hint: "masculine noun 'l'errore'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-066",
      type: "recognize",
      prompt: "perdonare",
      accepted: ["to forgive"],
      hint: "verb, from 'il perdono' — to forgive",
      tags: ["social", "forgiveness", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-067",
      type: "produce",
      prompt: "to forgive",
      accepted: ["perdonare"],
      hint: "'perdonare'",
      tags: ["social", "forgiveness", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-068",
      type: "recognize",
      prompt: "imperdonabile",
      accepted: ["unforgivable"],
      hint: "adjective — cannot be forgiven",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-069",
      type: "produce",
      prompt: "unforgivable",
      accepted: ["imperdonabile"],
      hint: "'imperdonabile'",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-070",
      type: "recognize",
      prompt: "fedele",
      accepted: ["faithful"],
      hint: "adjective — invariable for masculine/feminine",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-071",
      type: "produce",
      prompt: "faithful",
      accepted: ["fedele"],
      hint: "'fedele' — same form for both genders",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-072",
      type: "recognize",
      prompt: "la fedeltà",
      accepted: ["faithfulness", "fidelity"],
      hint: "feminine noun, from 'fedele'",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-073",
      type: "produce",
      prompt: "faithfulness",
      accepted: ["la fedeltà"],
      hint: "feminine noun 'la fedeltà'",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-074",
      type: "recognize",
      prompt: "infedele",
      accepted: ["unfaithful"],
      hint: "adjective — the opposite of 'fedele'",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-075",
      type: "produce",
      prompt: "unfaithful",
      accepted: ["infedele"],
      hint: "'infedele' — same form for both genders",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-076",
      type: "recognize",
      prompt: "l'onestà",
      accepted: ["honesty"],
      hint: "feminine noun starting with a vowel",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-077",
      type: "produce",
      prompt: "honesty",
      accepted: ["l'onestà"],
      hint: "feminine noun 'l'onestà'",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-078",
      type: "recognize",
      prompt: "onesto / onesta",
      accepted: ["honest"],
      hint: "adjective agreeing with gender",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-079",
      type: "produce",
      prompt: "honest",
      accepted: ["onesto", "onesta"],
      hint: "'onesto' (m) / 'onesta' (f)",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-080",
      type: "recognize",
      prompt: "disonesto / disonesta",
      accepted: ["dishonest"],
      hint: "adjective, opposite of 'onesto'",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-081",
      type: "produce",
      prompt: "dishonest",
      accepted: ["disonesto", "disonesta"],
      hint: "'disonesto' (m) / 'disonesta' (f)",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-082",
      type: "recognize",
      prompt: "sincero / sincera",
      accepted: ["sincere"],
      hint: "adjective agreeing with gender",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-083",
      type: "produce",
      prompt: "sincere",
      accepted: ["sincero", "sincera"],
      hint: "'sincero' (m) / 'sincera' (f)",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-084",
      type: "recognize",
      prompt: "la sincerità",
      accepted: ["sincerity"],
      hint: "feminine noun, invariable in the plural",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-085",
      type: "produce",
      prompt: "sincerity",
      accepted: ["la sincerità"],
      hint: "feminine noun 'la sincerità'",
      tags: ["social", "value", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-086",
      type: "recognize",
      prompt: "ipocrita",
      accepted: ["hypocritical", "a hypocrite"],
      hint: "adjective/noun — same form for masculine and feminine",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-087",
      type: "produce",
      prompt: "hypocritical / a hypocrite",
      accepted: ["ipocrita"],
      hint: "'ipocrita' — same form for both genders",
      tags: ["social", "conflict", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-088",
      type: "recognize",
      prompt: "l'ipocrisia",
      accepted: ["hypocrisy"],
      hint: "feminine noun starting with a vowel",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-089",
      type: "produce",
      prompt: "hypocrisy",
      accepted: ["l'ipocrisia"],
      hint: "feminine noun 'l'ipocrisia'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-090",
      type: "recognize",
      prompt: "il pettegolezzo",
      accepted: ["gossip", "a piece of gossip"],
      hint: "masculine noun — a piece of gossip",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-091",
      type: "produce",
      prompt: "gossip (a piece of)",
      accepted: ["il pettegolezzo"],
      hint: "masculine noun 'il pettegolezzo'",
      tags: ["social", "conflict", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-092",
      type: "recognize",
      prompt: "spettegolare",
      accepted: ["to gossip"],
      hint: "verb; 'spettegolare su qualcuno' — to gossip about someone",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-093",
      type: "produce",
      prompt: "to gossip",
      accepted: ["spettegolare"],
      hint: "'spettegolare su' + person",
      tags: ["social", "conflict", "verb"],
      tier: 1,
    },
    {
      id: "b132-t1-094",
      type: "recognize",
      prompt: "affidabile",
      accepted: ["reliable", "trustworthy"],
      hint: "adjective — invariable for masculine/feminine",
      tags: ["social", "trust", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-095",
      type: "produce",
      prompt: "reliable / trustworthy",
      accepted: ["affidabile"],
      hint: "'affidabile' — same form for both genders",
      tags: ["social", "trust", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-096",
      type: "recognize",
      prompt: "inaffidabile",
      accepted: ["unreliable"],
      hint: "adjective, opposite of 'affidabile'",
      tags: ["social", "trust", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-097",
      type: "produce",
      prompt: "unreliable",
      accepted: ["inaffidabile"],
      hint: "'inaffidabile' — same form for both genders",
      tags: ["social", "trust", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-098",
      type: "recognize",
      prompt: "genuino / genuina",
      accepted: ["genuine"],
      hint: "adjective agreeing with gender",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-099",
      type: "produce",
      prompt: "genuine",
      accepted: ["genuino", "genuina"],
      hint: "'genuino' (m) / 'genuina' (f)",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-100",
      type: "recognize",
      prompt: "autentico / autentica",
      accepted: ["authentic"],
      hint: "adjective agreeing with gender",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-101",
      type: "produce",
      prompt: "authentic",
      accepted: ["autentico", "autentica"],
      hint: "'autentico' (m) / 'autentica' (f)",
      tags: ["social", "value", "adjective"],
      tier: 1,
    },
    {
      id: "b132-t1-102",
      type: "recognize",
      prompt: "la complicità",
      accepted: ["close rapport", "complicity (in a positive sense)"],
      hint: "feminine noun, invariable in the plural — an easy, unspoken understanding",
      tags: ["social", "friendship", "noun"],
      tier: 1,
    },
    {
      id: "b132-t1-103",
      type: "produce",
      prompt: "close rapport (between friends)",
      accepted: ["la complicità"],
      hint: "feminine noun 'la complicità'",
      tags: ["social", "friendship", "noun"],
      tier: 1,
    },

    // ── Tier 2 – Grammar / Fill-blank (expansion) ────────────────────────────
    {
      id: "b132-t2-005",
      type: "fill_blank",
      prompt: "Dopo tanti anni di amicizia, mi fido ciecamente ___ lei.",
      accepted: ["di"],
      hint: "'fidarsi di' — trust takes the preposition 'di'",
      tags: ["fill_blank", "preposition", "fidarsi"],
      tier: 2,
    },
    {
      id: "b132-t2-006",
      type: "fill_blank",
      prompt: "All'inizio diffidavo ___ lui, ma adesso è il mio migliore amico.",
      accepted: ["di"],
      hint: "'diffidare di' — to distrust someone",
      tags: ["fill_blank", "preposition", "diffidare"],
      tier: 2,
    },
    {
      id: "b132-t2-007",
      type: "fill_blank",
      prompt: "Ho confidato il mio segreto ___ una sola persona.",
      accepted: ["a"],
      hint: "'confidare qualcosa a qualcuno' — preposition 'a'",
      tags: ["fill_blank", "preposition", "confidare"],
      tier: 2,
    },
    {
      id: "b132-t2-008",
      type: "fill_blank",
      prompt: "Nei momenti difficili, conto sempre ___ il mio amico più fidato.",
      accepted: ["su"],
      hint: "'contare su qualcuno' — to count on someone",
      tags: ["fill_blank", "preposition", "contare"],
      tier: 2,
    },
    {
      id: "b132-t2-009",
      type: "fill_blank",
      prompt: "Ho perdonato Marco ___ il suo errore, ma non l'ho dimenticato.",
      accepted: ["per"],
      hint: "'perdonare qualcuno per qualcosa'",
      tags: ["fill_blank", "preposition", "perdonare"],
      tier: 2,
    },
    {
      id: "b132-t2-010",
      type: "fill_blank",
      prompt: "Nonostante la lontananza, restiamo legati ___ una fiducia che non è mai cambiata.",
      accepted: ["da"],
      hint: "'legato da' — bound by (trust)",
      tags: ["fill_blank", "preposition", "lontananza"],
      tier: 2,
    },
    {
      id: "b132-t2-011",
      type: "fill_blank",
      prompt: "Il mio amico d'infanzia mi ha aiutato a riprendermi ___ quella delusione.",
      accepted: ["da"],
      hint: "'riprendersi da' — to recover from",
      tags: ["fill_blank", "preposition", "delusione"],
      tier: 2,
    },
    {
      id: "b132-t2-012",
      type: "fill_blank",
      prompt: "Non voglio parlare male ___ i miei amici alle loro spalle.",
      accepted: ["di"],
      hint: "'parlare male di qualcuno' — to speak ill of someone",
      tags: ["fill_blank", "preposition", "gossip"],
      tier: 2,
    },
    {
      id: "b132-t2-013",
      type: "fill_blank",
      prompt: "Il nostro legame si è rafforzato proprio ___ causa di quella crisi.",
      accepted: ["a"],
      hint: "'a causa di' — because of; the preposition 'a' before 'causa'",
      tags: ["fill_blank", "preposition", "rafforzare"],
      tier: 2,
    },
    {
      id: "b132-t2-014",
      type: "fill_blank",
      prompt: "Quella bugia ha incrinato la fiducia ___ noi due per mesi.",
      accepted: ["tra"],
      hint: "'tra noi due' — between the two of us",
      tags: ["fill_blank", "preposition", "incrinare"],
      tier: 2,
    },
    {
      id: "b132-t2-015",
      type: "fill_blank",
      prompt: "Non è da lui spettegolare ___ i colleghi, di solito è molto discreto.",
      accepted: ["sui"],
      hint: "'spettegolare su qualcuno' — the preposition contracts to 'sui' before a plural masculine noun",
      tags: ["fill_blank", "preposition", "spettegolare"],
      tier: 2,
    },
    {
      id: "b132-t2-016",
      type: "fill_blank",
      prompt: "Ha sempre dimostrato lealtà ___ i suoi amici, anche nei momenti più difficili.",
      accepted: ["verso"],
      hint: "'lealtà verso qualcuno' — loyalty towards someone",
      tags: ["fill_blank", "preposition", "lealta"],
      tier: 2,
    },
    {
      id: "b132-t2-017",
      type: "fill_blank",
      prompt: "Mi vergogno ___ quel pettegolezzo che ho ripetuto senza pensarci.",
      accepted: ["di"],
      hint: "'vergognarsi di' — to be ashamed of",
      tags: ["fill_blank", "preposition", "pettegolezzo"],
      tier: 2,
    },
    {
      id: "b132-t2-018",
      type: "fill_blank",
      prompt: "Abbiamo chiarito il malinteso ___ una lunga chiacchierata sincera.",
      accepted: ["con"],
      hint: "'chiarire qualcosa con una chiacchierata' — preposition 'con'",
      tags: ["fill_blank", "preposition", "malinteso"],
      tier: 2,
    },
    {
      id: "b132-t2-019",
      type: "fill_blank",
      prompt: "Il tradimento del suo migliore amico l'ha resa diffidente ___ tutti, per un po'.",
      accepted: ["verso"],
      hint: "'diffidente verso' — wary/distrustful towards",
      tags: ["fill_blank", "preposition", "diffidente"],
      tier: 2,
    },
    {
      id: "b132-t2-020",
      type: "fill_blank",
      prompt: "Nonostante il litigio, i due fratelli hanno deciso di dare un'altra possibilità ___ loro amicizia.",
      accepted: ["alla"],
      hint: "'dare una possibilità a' — contracted with the definite article: 'alla'",
      tags: ["fill_blank", "preposition", "possibilita"],
      tier: 2,
    },
    {
      id: "b132-t2-021",
      type: "fill_blank",
      prompt: "Ho sempre potuto contare ___ il suo appoggio, anche quando tutti gli altri mi avevano voltato le spalle.",
      accepted: ["sul"],
      hint: "'contare su' + 'il suo appoggio' — contracted to 'sul'",
      tags: ["fill_blank", "preposition", "appoggio"],
      tier: 2,
    },
    {
      id: "b132-t2-022",
      type: "fill_blank",
      prompt: "È stata sincera ___ me fin dal primo giorno, senza mai nascondermi nulla.",
      accepted: ["con"],
      hint: "'sincero/a con qualcuno' — sincere with someone",
      tags: ["fill_blank", "preposition", "sincero"],
      tier: 2,
    },
    {
      id: "b132-t2-023",
      type: "fill_blank",
      prompt: "Il segreto che le avevo confidato è ormai ___ bocca di tutti quanti.",
      accepted: ["sulla"],
      hint: "'essere sulla bocca di tutti' — idiom: to be on everyone's lips, common knowledge",
      tags: ["fill_blank", "preposition", "segreto"],
      tier: 2,
    },
    {
      id: "b132-t2-024",
      type: "fill_blank",
      prompt: "Ha ammesso il proprio errore ed è tornato ___ chiedere scusa.",
      accepted: ["a"],
      hint: "'tornare a fare qualcosa' — to come back to do something",
      tags: ["fill_blank", "preposition", "errore"],
      tier: 2,
    },
    {
      id: "b132-t2-025",
      type: "fill_blank",
      prompt: "Non bisogna mai smettere di credere ___ le persone oneste.",
      accepted: ["nelle"],
      hint: "'credere in qualcuno' — contracted to 'nelle' before a feminine plural noun",
      tags: ["fill_blank", "preposition", "onesto"],
      tier: 2,
    },
    {
      id: "b132-t2-026",
      type: "fill_blank",
      prompt: "L'amicizia vera resiste anche ___ distanza di migliaia di chilometri.",
      accepted: ["alla"],
      hint: "'resistere a' — to withstand; contracted to 'alla' before 'distanza'",
      tags: ["fill_blank", "preposition", "lontananza"],
      tier: 2,
    },
    {
      id: "b132-t2-027",
      type: "fill_blank",
      prompt: "È difficile ___ di nuovo dopo un tradimento così doloroso.",
      accepted: ["fidarsi"],
      hint: "'fidarsi' — reflexive infinitive after an impersonal expression",
      tags: ["fill_blank", "verb-form", "fidarsi"],
      tier: 2,
    },
    {
      id: "b132-t2-028",
      type: "fill_blank",
      prompt: "Dopo essere stato tradito, ha imparato a ___ delle promesse troppo facili.",
      accepted: ["diffidare"],
      hint: "'diffidare' — infinitive after 'imparare a'",
      tags: ["fill_blank", "verb-form", "diffidare"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases (expansion) ────────────────────────────────
    {
      id: "b132-t3-006",
      type: "produce",
      prompt: "I don't trust him anymore after that lie.",
      accepted: ["Non mi fido più di lui dopo quella bugia."],
      hint: "'fidarsi di' + negation",
      tags: ["chunk", "trust", "fidarsi"],
      tier: 3,
    },
    {
      id: "b132-t3-007",
      type: "produce",
      prompt: "She confided her secret only to her best friend.",
      accepted: ["Ha confidato il suo segreto solo alla sua migliore amica."],
      hint: "'confidare qualcosa a qualcuno'",
      tags: ["chunk", "trust", "confidare"],
      tier: 3,
    },
    {
      id: "b132-t3-008",
      type: "produce",
      prompt: "He always counts on his friends in hard times.",
      accepted: ["Conta sempre sui suoi amici nei momenti difficili."],
      hint: "'contare su' + plural article",
      tags: ["chunk", "support", "contare"],
      tier: 3,
    },
    {
      id: "b132-t3-009",
      type: "produce",
      prompt: "Her constant lies destroyed his trust completely.",
      accepted: ["Le sue bugie costanti hanno distrutto completamente la sua fiducia."],
      hint: "'distruggere la fiducia'",
      tags: ["chunk", "trust", "betrayal"],
      tier: 3,
    },
    {
      id: "b132-t3-010",
      type: "produce",
      prompt: "We stayed close friends despite the distance between us.",
      accepted: ["Siamo rimasti amici stretti nonostante la lontananza tra noi."],
      hint: "'nonostante la lontananza'",
      tags: ["chunk", "friendship", "lontananza"],
      tier: 3,
    },
    {
      id: "b132-t3-011",
      type: "produce",
      prompt: "A long-distance friendship needs real effort to survive.",
      accepted: ["Un'amicizia a distanza ha bisogno di un vero impegno per sopravvivere."],
      hint: "'un'amicizia a distanza'",
      tags: ["chunk", "friendship", "long-distance"],
      tier: 3,
    },
    {
      id: "b132-t3-012",
      type: "produce",
      prompt: "We call each other every week to keep the bond alive.",
      accepted: ["Ci sentiamo ogni settimana per mantenere vivo il legame."],
      hint: "'mantenere vivo il legame'",
      tags: ["chunk", "friendship", "mantenere"],
      tier: 3,
    },
    {
      id: "b132-t3-013",
      type: "produce",
      prompt: "He never holds a grudge, even after a serious argument.",
      accepted: ["Non porta mai rancore, nemmeno dopo un litigio serio."],
      hint: "'portare rancore'",
      tags: ["chunk", "conflict", "rancore"],
      tier: 3,
    },
    {
      id: "b132-t3-014",
      type: "produce",
      prompt: "She still holds a grudge against her old friend.",
      accepted: ["Serba ancora rancore verso la sua vecchia amica."],
      hint: "'serbare rancore verso qualcuno'",
      tags: ["chunk", "conflict", "rancore"],
      tier: 3,
    },
    {
      id: "b132-t3-015",
      type: "produce",
      prompt: "I don't want to strain our friendship over something so small.",
      accepted: ["Non voglio incrinare la nostra amicizia per una cosa così piccola."],
      hint: "'incrinare un'amicizia'",
      tags: ["chunk", "conflict", "incrinare"],
      tier: 3,
    },
    {
      id: "b132-t3-016",
      type: "produce",
      prompt: "One word too many can ruin years of trust.",
      accepted: ["Una parola di troppo può guastare anni di fiducia."],
      hint: "'guastare' + 'anni di fiducia'",
      tags: ["chunk", "conflict", "guastare"],
      tier: 3,
    },
    {
      id: "b132-t3-017",
      type: "produce",
      prompt: "They finally repaired their friendship after months of silence.",
      accepted: ["Hanno finalmente riparato la loro amicizia dopo mesi di silenzio."],
      hint: "'riparare un'amicizia'",
      tags: ["chunk", "reconciliation", "riparare"],
      tier: 3,
    },
    {
      id: "b132-t3-018",
      type: "produce",
      prompt: "It took a long, honest conversation to clear up the misunderstanding.",
      accepted: ["Ci è voluta una lunga conversazione sincera per chiarire il malinteso."],
      hint: "'chiarire il malinteso'",
      tags: ["chunk", "reconciliation", "malinteso"],
      tier: 3,
    },
    {
      id: "b132-t3-019",
      type: "produce",
      prompt: "The whole argument started from a stupid misunderstanding.",
      accepted: ["Tutto il litigio è nato da uno stupido malinteso."],
      hint: "'nascere da un malinteso'",
      tags: ["chunk", "conflict", "malinteso"],
      tier: 3,
    },
    {
      id: "b132-t3-020",
      type: "produce",
      prompt: "He admitted his mistake and asked for forgiveness.",
      accepted: ["Ha riconosciuto il proprio errore e ha chiesto perdono."],
      hint: "'riconoscere il proprio errore'",
      tags: ["chunk", "forgiveness", "errore"],
      tier: 3,
    },
    {
      id: "b132-t3-021",
      type: "produce",
      prompt: "Some mistakes are simply unforgivable.",
      accepted: ["Alcuni errori sono semplicemente imperdonabili."],
      hint: "'imperdonabile'",
      tags: ["chunk", "conflict", "imperdonabile"],
      tier: 3,
    },
    {
      id: "b132-t3-022",
      type: "produce",
      prompt: "She decided to give him another chance despite the betrayal.",
      accepted: ["Ha deciso di dargli un'altra possibilità nonostante il tradimento."],
      hint: "'dare un'altra possibilità'",
      tags: ["chunk", "forgiveness", "tradimento"],
      tier: 3,
    },
    {
      id: "b132-t3-023",
      type: "produce",
      prompt: "After the reconciliation, they decided to turn the page.",
      accepted: ["Dopo la riconciliazione, hanno deciso di voltare pagina."],
      hint: "idiom 'voltare pagina' — to turn the page, move on",
      tags: ["chunk", "reconciliation", "idiom"],
      tier: 3,
    },
    {
      id: "b132-t3-024",
      type: "produce",
      prompt: "It's better to leave certain arguments in the past.",
      accepted: ["È meglio lasciarsi certi litigi alle spalle."],
      hint: "idiom 'lasciarsi qualcosa alle spalle'",
      tags: ["chunk", "conflict", "idiom"],
      tier: 3,
    },
    {
      id: "b132-t3-025",
      type: "produce",
      prompt: "A true friend is always a shoulder to cry on.",
      accepted: ["Un vero amico è sempre una spalla su cui piangere."],
      hint: "idiom 'una spalla su cui piangere'",
      tags: ["chunk", "support", "idiom"],
      tier: 3,
    },
    {
      id: "b132-t3-026",
      type: "produce",
      prompt: "Don't talk behind your friends' backs.",
      accepted: ["Non parlare alle spalle dei tuoi amici."],
      hint: "idiom 'parlare alle spalle di qualcuno'",
      tags: ["chunk", "conflict", "idiom"],
      tier: 3,
    },
    {
      id: "b132-t3-027",
      type: "produce",
      prompt: "I found out he had been gossiping about me for months.",
      accepted: ["Ho scoperto che spettegolava su di me da mesi."],
      hint: "'spettegolare su qualcuno'",
      tags: ["chunk", "conflict", "spettegolare"],
      tier: 3,
    },
    {
      id: "b132-t3-028",
      type: "produce",
      prompt: "That piece of gossip ruined her reputation in the group.",
      accepted: ["Quel pettegolezzo ha rovinato la sua reputazione nel gruppo."],
      hint: "'il pettegolezzo'",
      tags: ["chunk", "conflict", "pettegolezzo"],
      tier: 3,
    },
    {
      id: "b132-t3-029",
      type: "produce",
      prompt: "He's the most reliable friend I've ever had.",
      accepted: ["È l'amico più affidabile che abbia mai avuto."],
      hint: "'affidabile'",
      tags: ["chunk", "trust", "affidabile"],
      tier: 3,
    },
    {
      id: "b132-t3-030",
      type: "produce",
      prompt: "I can't trust someone so unreliable with a secret.",
      accepted: ["Non posso fidarmi di una persona così inaffidabile con un segreto."],
      hint: "'inaffidabile' + 'fidarsi di'",
      tags: ["chunk", "trust", "inaffidabile"],
      tier: 3,
    },
    {
      id: "b132-t3-031",
      type: "produce",
      prompt: "Her friendship has always felt genuine, never fake.",
      accepted: ["La sua amicizia è sempre sembrata genuina, mai falsa."],
      hint: "'genuina'",
      tags: ["chunk", "value", "genuino"],
      tier: 3,
    },
    {
      id: "b132-t3-032",
      type: "produce",
      prompt: "I look for authentic relationships, not convenient ones.",
      accepted: ["Cerco rapporti autentici, non rapporti di comodo."],
      hint: "'autentico' + 'di comodo' (convenient/for convenience)",
      tags: ["chunk", "value", "autentico"],
      tier: 3,
    },
    {
      id: "b132-t3-033",
      type: "produce",
      prompt: "There's a rare complicity between the two of them.",
      accepted: ["C'è una rara complicità tra loro due."],
      hint: "'la complicità'",
      tags: ["chunk", "friendship", "complicita"],
      tier: 3,
    },
    {
      id: "b132-t3-034",
      type: "produce",
      prompt: "Honesty is the foundation of every true friendship.",
      accepted: ["L'onestà è il fondamento di ogni vera amicizia."],
      hint: "'l'onestà'",
      tags: ["chunk", "value", "onesta"],
      tier: 3,
    },
    {
      id: "b132-t3-035",
      type: "produce",
      prompt: "He's honest even when the truth hurts.",
      accepted: ["È onesto anche quando la verità fa male."],
      hint: "'onesto'",
      tags: ["chunk", "value", "onesto"],
      tier: 3,
    },
    {
      id: "b132-t3-036",
      type: "produce",
      prompt: "I can't stand dishonest people who pretend to be your friend.",
      accepted: ["Non sopporto le persone disoneste che fingono di essere tue amiche."],
      hint: "'disonesto' + 'fingere di'",
      tags: ["chunk", "conflict", "disonesto"],
      tier: 3,
    },
    {
      id: "b132-t3-037",
      type: "produce",
      prompt: "She was always sincere with me, even about hard things.",
      accepted: ["È sempre stata sincera con me, anche sulle cose difficili."],
      hint: "'sincero/a con qualcuno'",
      tags: ["chunk", "value", "sincero"],
      tier: 3,
    },
    {
      id: "b132-t3-038",
      type: "produce",
      prompt: "His sincerity is what I admire most about him.",
      accepted: ["La sua sincerità è quello che ammiro di più in lui."],
      hint: "'la sincerità'",
      tags: ["chunk", "value", "sincerita"],
      tier: 3,
    },
    {
      id: "b132-t3-039",
      type: "produce",
      prompt: "Don't be a hypocrite: either you're loyal or you're not.",
      accepted: ["Non essere ipocrita: o sei leale o non lo sei."],
      hint: "'ipocrita'",
      tags: ["chunk", "conflict", "ipocrita"],
      tier: 3,
    },
    {
      id: "b132-t3-040",
      type: "produce",
      prompt: "That kind of hypocrisy destroys any real bond.",
      accepted: ["Quel tipo di ipocrisia distrugge qualsiasi legame vero."],
      hint: "'l'ipocrisia'",
      tags: ["chunk", "conflict", "ipocrisia"],
      tier: 3,
    },
    {
      id: "b132-t3-041",
      type: "produce",
      prompt: "A faithful friend never abandons you when things get hard.",
      accepted: ["Un amico fedele non ti abbandona mai quando le cose si complicano."],
      hint: "'fedele'",
      tags: ["chunk", "value", "fedele"],
      tier: 3,
    },
    {
      id: "b132-t3-042",
      type: "produce",
      prompt: "Being unfaithful to a friendship is worse than any lie.",
      accepted: ["Essere infedele a un'amicizia è peggio di qualsiasi bugia."],
      hint: "'infedele a un'amicizia'",
      tags: ["chunk", "conflict", "infedele"],
      tier: 3,
    },
    {
      id: "b132-t3-043",
      type: "produce",
      prompt: "I trust her with my eyes closed — she's never betrayed me.",
      accepted: [
        "Mi fido di lei a occhi chiusi: non mi ha mai tradita.",
        "Mi fido di lei a occhi chiusi: non mi ha mai tradito.",
      ],
      hint: "idiom 'a occhi chiusi' — with total trust",
      tags: ["chunk", "trust", "idiom"],
      tier: 3,
    },
    {
      id: "b132-t3-044",
      type: "produce",
      prompt: "There's a real closeness between those two sisters.",
      accepted: ["C'è una vera confidenza tra quelle due sorelle."],
      hint: "'la confidenza' — familiarity/closeness between people, not to be confused with 'la fiducia'",
      tags: ["chunk", "relationship", "confidenza"],
      tier: 3,
    },
    {
      id: "b132-t3-045",
      type: "produce",
      prompt: "In a family, it's not always easy to support everyone's choices.",
      accepted: ["In famiglia, non è facile appoggiare sempre le scelte di tutti."],
      hint: "'appoggiare le scelte di qualcuno' — infinitive after 'facile'",
      tags: ["chunk", "support", "appoggiare"],
      tier: 3,
    },
    {
      id: "b132-t3-046",
      type: "produce",
      prompt: "It takes little time to forge a true bond.",
      accepted: ["Basta poco tempo per stringere un legame vero."],
      hint: "'stringere un legame' — after 'per' + infinitive",
      tags: ["chunk", "relationship", "stringere"],
      tier: 3,
    },
    {
      id: "b132-t3-047",
      type: "produce",
      prompt: "A single lie is enough to strain a relationship forever.",
      accepted: ["Basta una sola bugia per incrinare un rapporto per sempre."],
      hint: "'incrinare un rapporto' — after 'per' + infinitive",
      tags: ["chunk", "conflict", "incrinare"],
      tier: 3,
    },
    {
      id: "b132-t3-048",
      type: "produce",
      prompt: "It's never too late to repair a relationship.",
      accepted: ["Non è mai troppo tardi per riparare un rapporto."],
      hint: "'riparare un rapporto' — after 'per' + infinitive",
      tags: ["chunk", "reconciliation", "riparare"],
      tier: 3,
    },
    {
      id: "b132-t3-049",
      type: "produce",
      prompt: "To forgive doesn't mean to forget.",
      accepted: ["Perdonare non significa dimenticare."],
      hint: "'perdonare' — infinitive as the sentence subject",
      tags: ["chunk", "forgiveness", "perdonare"],
      tier: 3,
    },
    {
      id: "b132-t3-050",
      type: "produce",
      prompt: "Faithfulness in a friendship is not negotiable.",
      accepted: ["La fedeltà in un'amicizia non è negoziabile."],
      hint: "'la fedeltà'",
      tags: ["chunk", "value", "fedelta"],
      tier: 3,
    },
    {
      id: "b132-t3-051",
      type: "produce",
      prompt: "He seemed nice, but he was actually quite dishonest.",
      accepted: ["Sembrava simpatico, ma in realtà era piuttosto disonesto."],
      hint: "'disonesto' — masculine singular",
      tags: ["chunk", "conflict", "disonesto"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze (expansion) ───────────────────────────────────
    {
      id: "b132-t4-002",
      type: "passage_cloze",
      prompt: "Quando Sara si è trasferita in Canada per lavoro, io e lei ci siamo promesse di restare vicine nonostante la lontananza.\nAll'inizio ci scrivevamo ogni giorno, poi i messaggi sono diventati più rari per via del fuso orario.\nNonostante tutto, ogni domenica troviamo un'ora per una videochiamata, senza mai saltarla nemmeno una volta.\nSara dice sempre che la vera amicizia non si misura in chilometri, ma nella ___ costruita negli anni.",
      accepted: ["complicità"],
      hint: "the easy, unspoken understanding between them, built over years — feminine noun",
      tags: ["passage_cloze", "friendship", "long-distance", "complicita"],
      tier: 4,
      prerequisites: ["b132-t1-046", "b132-t1-047", "b132-t1-102", "b132-t1-103"],
    },
    {
      id: "b132-t4-003",
      type: "passage_cloze",
      prompt: "Dopo che Luca ha scoperto il tradimento del suo migliore amico, per mesi ha diffidato di chiunque gli si avvicinasse.\nPiano piano, però, ha imparato a distinguere le persone davvero affidabili da quelle che dicono solo belle parole.\nOggi si fida di nuovo, ma con più cautela di prima, e sceglie con cura a chi confidare i suoi segreti.\nLa vera lezione, dice, è che la ___ va guadagnata un giorno alla volta, non regalata subito.",
      accepted: ["fiducia"],
      hint: "the thing rebuilt slowly, one day at a time — the central word of this whole unit",
      tags: ["passage_cloze", "trust", "betrayal"],
      tier: 4,
      prerequisites: ["b132-t1-002", "b132-t1-026", "b132-t1-027", "b132-t1-094", "b132-t1-095"],
    },
    {
      id: "b132-t4-004",
      type: "passage_cloze",
      prompt: "Chiara ha scoperto per caso che la sua collega spettegolava su di lei durante le pause caffè.\nAll'inizio ha pensato di ignorare tutto, ma il pettegolezzo continuava a girare per l'ufficio.\nAlla fine ha deciso di affrontarla direttamente, chiedendole con calma perché lo facesse.\nLa collega si è scusata, ammettendo che era stato un ___ imperdonabile, e da allora non ne ha più parlato con nessuno.",
      accepted: ["errore"],
      hint: "the mistake she admits — masculine noun",
      tags: ["passage_cloze", "gossip", "betrayal"],
      tier: 4,
      prerequisites: ["b132-t1-064", "b132-t1-065", "b132-t1-090", "b132-t1-091", "b132-t1-092", "b132-t1-093"],
    },
    {
      id: "b132-t4-005",
      type: "passage_cloze",
      prompt: "Io e Giulia abbiamo litigato per una sciocchezza e per una settimana non ci siamo parlate.\nOgni giorno che passava, il malinteso sembrava crescere invece di risolversi da solo.\nAlla fine ho deciso di scriverle un messaggio sincero, spiegando cosa provavo davvero senza orgoglio.\nLei mi ha risposto subito, e insieme abbiamo capito che nessuna delle due voleva davvero rompere quel ___.",
      accepted: ["legame"],
      hint: "the bond between them, almost broken by pride — masculine noun",
      tags: ["passage_cloze", "conflict", "reconciliation"],
      tier: 4,
      prerequisites: ["b132-t1-023", "b132-t1-060", "b132-t1-061"],
    },
    {
      id: "b132-t4-006",
      type: "passage_cloze",
      prompt: "Quando ho perso il lavoro, non mi aspettavo quanto appoggio avrei ricevuto dai miei amici.\nUno mi ha aiutato a rifare il curriculum, un'altra mi ha offerto ospitalità mentre cercavo un nuovo appartamento.\nOgni volta che mi sentivo scoraggiato, sapevo di poter contare su di loro senza nemmeno chiedere.\nHo capito allora che un vero amico è qualcuno su cui puoi sempre ___, anche nei momenti più bui.",
      accepted: ["contare"],
      hint: "the verb for relying on someone — infinitive",
      tags: ["passage_cloze", "support", "friendship"],
      tier: 4,
      prerequisites: ["b132-t1-040", "b132-t1-041", "b132-t1-044", "b132-t1-045"],
    },
    {
      id: "b132-t4-007",
      type: "passage_cloze",
      prompt: "Da bambina, mia madre mi ripeteva sempre che l'onestà vale più di qualsiasi bugia detta per convenienza.\nCrescendo, ho capito quanto fosse difficile essere sincera anche quando la verità poteva ferire qualcuno che amavo.\nUna volta ho detto una bugia a una mia amica per non deluderla, e mi sono sentita in colpa per settimane.\nDa allora ho deciso di essere sempre ___, anche quando è scomodo.",
      accepted: ["sincera"],
      hint: "adjective agreeing with the female narrator — sincere",
      tags: ["passage_cloze", "honesty", "sincerity"],
      tier: 4,
      prerequisites: ["b132-t1-076", "b132-t1-077", "b132-t1-082", "b132-t1-083"],
    },
    {
      id: "b132-t4-008",
      type: "passage_cloze",
      prompt: "Marco aveva promesso di aiutarmi con il trasloco, ma all'ultimo momento non si è più fatto vedere.\nNon era la prima volta: cancellava sempre gli appuntamenti all'ultimo minuto, senza mai una vera spiegazione.\nI miei altri amici mi avevano avvertito che non potevo fidarmi troppo di lui.\nCon il tempo ho imparato che un amico ___ finisce sempre per deludere, prima o poi.",
      accepted: ["inaffidabile"],
      hint: "adjective for someone you cannot rely on",
      tags: ["passage_cloze", "reliability", "disappointment"],
      tier: 4,
      prerequisites: ["b132-t1-028", "b132-t1-029", "b132-t1-096", "b132-t1-097"],
    },
    {
      id: "b132-t4-009",
      type: "passage_cloze",
      prompt: "Durante la festa, ho notato che Elena parlava benissimo di tutti in faccia, ma dietro le spalle diceva tutt'altro.\nQuando l'ho affrontata, ha negato tutto, ma un'altra amica aveva sentito la stessa conversazione.\nMi sono resa conto che la sua gentilezza era solo una maschera, e questo mi ha ferito più di un vero litigio.\nOra so che non c'è niente di peggio dell'___ in un'amicizia.",
      accepted: ["ipocrisia"],
      hint: "the noun for saying one thing and doing another — feminine",
      tags: ["passage_cloze", "hypocrisy", "betrayal"],
      tier: 4,
      prerequisites: ["b132-t1-086", "b132-t1-087", "b132-t1-088", "b132-t1-089"],
    },
    {
      id: "b132-t4-010",
      type: "passage_cloze",
      prompt: "Anni fa, mio fratello mi ha deluso profondamente, dimenticando la promessa più importante della mia vita.\nPer molto tempo ho portato rancore, rifiutando persino di parlargli alle feste di famiglia.\nUn giorno, però, ho capito che il rancore faceva più male a me che a lui.\nHo deciso di dargli un'altra possibilità, perché il ___ è più forte di qualsiasi errore.",
      accepted: ["perdono"],
      hint: "the noun already taught in this unit — forgiveness",
      tags: ["passage_cloze", "forgiveness", "reconciliation"],
      tier: 4,
      prerequisites: ["b132-t1-008", "b132-t1-038", "b132-t1-039", "b132-t1-066", "b132-t1-067"],
    },
    {
      id: "b132-t4-011",
      type: "passage_cloze",
      prompt: "Dopo l'incidente d'auto, Marta ha passato settimane in ospedale, e i suoi amici si sono alternati ogni giorno per starle vicino.\nQuella crisi, invece di allontanarli, ha rafforzato il gruppo in un modo che nessuno si aspettava.\nOggi si vedono ancora più spesso di prima, e Marta dice che quella brutta esperienza le ha insegnato chi erano i suoi veri amici.\nA volte, dice, un momento difficile può ___ un'amicizia più di dieci anni di normalità.",
      accepted: ["rafforzare"],
      hint: "the verb for making a bond stronger — infinitive",
      tags: ["passage_cloze", "support", "friendship"],
      tier: 4,
      prerequisites: ["b132-t1-052", "b132-t1-053"],
    },
    {
      id: "b132-t4-012",
      type: "passage_cloze",
      prompt: "Da quando eravamo adolescenti, io e Valeria ci siamo sempre confidate ogni segreto, anche i più imbarazzanti.\nUna volta mi ha rivelato una cosa molto personale, chiedendomi di non dirla a nessun altro.\nNonostante la tentazione di raccontarla ad altri amici, ho mantenuto la promessa per anni.\nValeria dice che sono l'unica persona di cui si fida completamente con un ___ così delicato.",
      accepted: ["segreto"],
      hint: "the noun for something told in confidence",
      tags: ["passage_cloze", "trust", "secret"],
      tier: 4,
      prerequisites: ["b132-t1-032", "b132-t1-033", "b132-t1-034", "b132-t1-035"],
    },
    {
      id: "b132-t4-013",
      type: "passage_cloze",
      prompt: "Quando ho lasciato il mio vecchio lavoro, molte persone che consideravo amici hanno smesso di scrivermi.\nMi sono resa conto che per loro ero solo utile, non una vera amica.\nCon il tempo, ho imparato a riconoscere chi cercava un rapporto autentico e chi voleva solo un contatto comodo.\nOggi preferisco avere pochi amici ___ piuttosto che tanti conoscenti interessati.",
      accepted: ["genuini"],
      hint: "adjective agreeing with 'amici' (masculine plural) — genuine",
      tags: ["passage_cloze", "authenticity", "friendship"],
      tier: 4,
      prerequisites: ["b132-t1-098", "b132-t1-099", "b132-t1-100", "b132-t1-101"],
    },
    {
      id: "b132-t4-014",
      type: "passage_cloze",
      prompt: "Per settimane, Paolo pensava che il suo amico Davide lo stesse evitando apposta senza motivo.\nIn realtà, Davide stava solo attraversando un periodo difficile e non aveva energie per vedere nessuno.\nQuando finalmente si sono parlati con calma, tutto si è chiarito in pochi minuti.\nPaolo ha capito che spesso basta una conversazione sincera per risolvere un ___ che sembrava insormontabile.",
      accepted: ["malinteso"],
      hint: "the noun for a misunderstanding between friends",
      tags: ["passage_cloze", "misunderstanding", "conflict"],
      tier: 4,
      prerequisites: ["b132-t1-060", "b132-t1-061", "b132-t1-062", "b132-t1-063"],
    },
    {
      id: "b132-t4-015",
      type: "passage_cloze",
      prompt: "Quando tutti gli altri hanno smesso di credere nel progetto di Anna, il suo amico Filippo è rimasto al suo fianco fino alla fine.\nNon l'ha mai giudicata, nemmeno quando le cose sembravano andare male.\nAnna dice che quella lealtà silenziosa vale più di mille parole di incoraggiamento.\nOggi capisce che un amico davvero ___ non se ne va mai nei momenti difficili.",
      accepted: ["fedele"],
      hint: "adjective agreeing with 'amico' (masculine) — faithful",
      tags: ["passage_cloze", "loyalty", "friendship"],
      tier: 4,
      prerequisites: ["b132-t1-004", "b132-t1-070", "b132-t1-071"],
    },
  ],
};
export default unit;
