import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-24-si-impersonale",
  name: "One Does…",
  level: "B1",
  theme: "Si Impersonale & Si Passivante",
  emoji: "👥",
  prerequisiteUnits: ["b1-unit-23-passivo"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u24-t1-001",
      type: "recognize",
      prompt: "gli ingredienti",
      accepted: ["the ingredients"],
      hint: "what a recipe lists",
      tags: ["noun", "recipe", "food"],
      tier: 1,
    },
    {
      id: "u24-t1-002",
      type: "produce",
      prompt: "the recipe",
      accepted: ["la ricetta"],
      tags: ["noun", "recipe", "food"],
      tier: 1,
    },
    {
      id: "u24-t1-003",
      type: "produce",
      prompt: "the sign / notice",
      accepted: ["il cartello"],
      hint: "posted in public places",
      tags: ["noun", "notices", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-004",
      type: "produce",
      prompt: "the rule",
      accepted: ["la regola"],
      tags: ["noun", "general"],
      tier: 1,
    },
    {
      id: "u24-t1-005",
      type: "recognize",
      prompt: "cuocere",
      accepted: ["to cook", "to bake", "to boil"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-006",
      type: "recognize",
      prompt: "mescolare",
      accepted: ["to mix", "to stir"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-007",
      type: "recognize",
      prompt: "aggiungere",
      accepted: ["to add"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-008",
      type: "recognize",
      prompt: "versare",
      accepted: ["to pour"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-009",
      type: "recognize",
      prompt: "scaldare",
      accepted: ["to heat", "to warm up"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-010",
      type: "recognize",
      prompt: "tagliare",
      accepted: ["to cut", "to slice"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-011",
      type: "recognize",
      prompt: "servire",
      accepted: ["to serve"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-012",
      type: "produce",
      prompt: "the custom / habit (general)",
      accepted: ["l'abitudine", "la consuetudine", "l'usanza"],
      hint: "what people generally do",
      tags: ["noun", "general", "culture"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u24-t2-001",
      type: "conjugate",
      prompt: "mangiare – si impersonale (one eats / people eat)",
      accepted: ["si mangia"],
      hint: "always third-person singular for si impersonale",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-002",
      type: "conjugate",
      prompt: "potere – si impersonale (one can / is one allowed?)",
      accepted: ["si può"],
      hint: "modal + infinitive follows",
      tags: ["grammar", "si-impersonale", "modal"],
      tier: 2,
    },
    {
      id: "u24-t2-003",
      type: "conjugate",
      prompt: "dire – si impersonale (it is said / they say)",
      accepted: ["si dice"],
      hint: "si dice che + subjunctive or indicative",
      tags: ["grammar", "si-impersonale", "expression"],
      tier: 2,
    },
    {
      id: "u24-t2-004",
      type: "conjugate",
      prompt: "vendere (casa, sing.) – si passivante (the house is for sale)",
      accepted: ["si vende"],
      hint: "si passivante agrees with the noun: casa → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-005",
      type: "conjugate",
      prompt: "affittare (camere, plur.) – si passivante (rooms for rent)",
      accepted: ["si affittano"],
      hint: "si passivante agrees with the noun: camere → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-006",
      type: "conjugate",
      prompt: "parlare (italiano, sing.) – si passivante (Italian is spoken here)",
      accepted: ["si parla"],
      hint: "italiano is singular → verb stays singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-007",
      type: "conjugate",
      prompt: "fare – si impersonale (one does / it is done this way)",
      accepted: ["si fa"],
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-008",
      type: "conjugate",
      prompt: "usare – si impersonale (one uses / it is used)",
      accepted: ["si usa"],
      hint: "followed by an infinitive in instructions",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u24-t3-001",
      type: "produce",
      prompt: "It is said that… (opening phrase)",
      accepted: ["Si dice che…", "Si dice che"],
      hint: "a fixed expression for rumours or general truths",
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-002",
      type: "produce",
      prompt: "For sale: house (sign)",
      accepted: ["Si vende casa", "Vendesi casa"],
      hint: "si passivante – no article needed on signs",
      tags: ["chunk", "si-passivante", "notices"],
      tier: 3,
    },
    {
      id: "u24-t3-003",
      type: "produce",
      prompt: "How do you say ___? / How does one say ___?",
      accepted: ["Come si dice?", "Come si dice ___?"],
      hint: "extremely common question in language learning",
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-004",
      type: "produce",
      prompt: "That's how it's done. / One does it this way.",
      accepted: ["Si fa così", "Si fa così."],
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-005",
      type: "produce",
      prompt: "One uses a knife to cut it. (si usa + infinitive pattern)",
      accepted: ["Si usa un coltello per tagliarlo.", "Si usa un coltello per tagliare."],
      hint: "si usa + infinitive is very common in instructions",
      tags: ["chunk", "si-impersonale", "recipe"],
      tier: 3,
    },
    {
      id: "u24-t3-006",
      type: "fill_blank",
      prompt: "In Italia ___ bene ovunque. (People eat well everywhere in Italy.)",
      accepted: ["si mangia"],
      hint: "si impersonale of mangiare",
      tags: ["chunk", "si-impersonale", "culture"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passages ───────────────────────────────────────
    {
      id: "u24-t4-001",
      type: "produce",
      prompt: "Translate: 'In this restaurant one eats well and Italian is spoken.'",
      accepted: [
        "In questo ristorante si mangia bene e si parla italiano.",
        "In questo ristorante si mangia bene e si parla l'italiano.",
      ],
      hint: "si impersonale for 'eats'; si passivante for 'Italian is spoken'",
      tags: ["production", "si-impersonale", "si-passivante"],
      tier: 4,
      prerequisites: ["u24-t2-001", "u24-t2-006"],
    },
    {
      id: "u24-t4-002",
      type: "fill_blank",
      prompt: "Annuncio immobiliare: ___ appartamento al terzo piano. (Apartment for sale on the third floor.)",
      accepted: ["Si vende"],
      hint: "si passivante – appartamento is singular masculine",
      tags: ["production", "si-passivante", "notices"],
      tier: 4,
      prerequisites: ["u24-t2-004"],
    },
    {
      id: "u24-t4-003",
      type: "passage_cloze",
      prompt: "Questa è la ricetta della pasta al pomodoro.\nPrima, ___ la cipolla a pezzi piccoli.\nPoi si scalda l'olio in una padella e si aggiunge la cipolla.\nSi cuoce per cinque minuti, poi si versano i pomodori.\nSi mescola bene e si serve con la pasta cotta al dente.",
      accepted: ["si taglia"],
      hint: "si passivante of tagliare – la cipolla is singular feminine",
      tags: ["passage_cloze", "si-passivante", "recipe"],
      tier: 4,
      prerequisites: ["u24-t1-005", "u24-t1-006", "u24-t1-007", "u24-t1-008", "u24-t1-009", "u24-t1-010", "u24-t1-011", "u24-t2-006"],
    },
    {
      id: "u24-t4-004",
      type: "passage_cloze",
      prompt: "In Italia esistono molte tradizioni culinarie.\nSi dice che ogni regione abbia la propria ricetta speciale.\nIn Toscana ___ molto olio d'oliva in cucina.\nSi aggiungono erbe aromatiche a quasi tutti i piatti.\nSi mangia spesso insieme in famiglia, specialmente la domenica.",
      accepted: ["si usa"],
      hint: "si impersonale of usare – always singular",
      tags: ["passage_cloze", "si-impersonale", "culture"],
      tier: 4,
      prerequisites: ["u24-t1-001", "u24-t2-001", "u24-t2-003", "u24-t2-008"],
    },
    {
      id: "u24-t4-005",
      type: "produce",
      prompt: "Translate: 'It is said that in this city rooms are rented cheaply.'",
      accepted: [
        "Si dice che in questa città si affittano camere a buon prezzo.",
        "Si dice che in questa città si affittino camere a buon prezzo.",
      ],
      hint: "combine si dice che with si passivante of affittare (camere = plural)",
      tags: ["production", "si-impersonale", "si-passivante"],
      tier: 4,
      prerequisites: ["u24-t2-003", "u24-t2-005"],
    },

    // ── Tier 1 – Vocabulary (expansion) ───────────────────────────────────────
    {
      id: "u24-t1-013",
      type: "recognize",
      prompt: "il divieto",
      accepted: ["the ban", "the prohibition"],
      hint: "seen on signs forbidding something",
      tags: ["noun", "rules", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-014",
      type: "produce",
      prompt: "the parking / stopping (as in a no-parking sign)",
      accepted: ["la sosta"],
      hint: "used in 'divieto di sosta'",
      tags: ["noun", "traffic", "rules"],
      tier: 1,
    },
    {
      id: "u24-t1-015",
      type: "recognize",
      prompt: "il semaforo",
      accepted: ["the traffic light"],
      hint: "red, yellow, green",
      tags: ["noun", "traffic"],
      tier: 1,
    },
    {
      id: "u24-t1-016",
      type: "recognize",
      prompt: "l'incrocio",
      accepted: ["the intersection", "the crossroads"],
      hint: "where two streets meet",
      tags: ["noun", "traffic"],
      tier: 1,
    },
    {
      id: "u24-t1-017",
      type: "recognize",
      prompt: "il marciapiede",
      accepted: ["the sidewalk", "the pavement"],
      hint: "pedestrians walk here, not cars",
      tags: ["noun", "traffic", "city"],
      tier: 1,
    },
    {
      id: "u24-t1-018",
      type: "produce",
      prompt: "the crosswalk (lit. 'the stripes')",
      accepted: ["le strisce pedonali"],
      hint: "where pedestrians cross legally",
      tags: ["noun", "traffic", "city"],
      tier: 1,
    },
    {
      id: "u24-t1-019",
      type: "produce",
      prompt: "the flyer",
      accepted: ["il volantino"],
      hint: "handed out on the street or left in mailboxes",
      tags: ["noun", "shopping", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-020",
      type: "recognize",
      prompt: "l'orario",
      accepted: ["the schedule", "the timetable", "the opening hours"],
      hint: "when a shop or office is open",
      tags: ["noun", "time", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-021",
      type: "recognize",
      prompt: "la fila",
      accepted: ["the line", "the queue"],
      hint: "people wait their turn in one",
      tags: ["noun", "general", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-022",
      type: "produce",
      prompt: "the receipt",
      accepted: ["lo scontrino"],
      hint: "proof of purchase from a shop",
      tags: ["noun", "shopping"],
      tier: 1,
    },
    {
      id: "u24-t1-023",
      type: "recognize",
      prompt: "il resto",
      accepted: ["the change (money)"],
      hint: "what the cashier gives back",
      tags: ["noun", "money", "shopping"],
      tier: 1,
    },
    {
      id: "u24-t1-024",
      type: "produce",
      prompt: "the (small) bag",
      accepted: ["il sacchetto"],
      hint: "for carrying groceries",
      tags: ["noun", "shopping"],
      tier: 1,
    },
    {
      id: "u24-t1-025",
      type: "recognize",
      prompt: "la raccolta",
      accepted: ["the collection"],
      hint: "as in raccolta differenziata, recycling",
      tags: ["noun", "environment"],
      tier: 1,
    },
    {
      id: "u24-t1-026",
      type: "produce",
      prompt: "the bin",
      accepted: ["il bidone"],
      hint: "for sorting recyclables",
      tags: ["noun", "environment"],
      tier: 1,
    },
    {
      id: "u24-t1-027",
      type: "recognize",
      prompt: "i rifiuti",
      accepted: ["the waste", "the garbage", "the trash"],
      hint: "always plural in Italian",
      tags: ["noun", "environment"],
      tier: 1,
    },
    {
      id: "u24-t1-028",
      type: "recognize",
      prompt: "l'ambiente",
      accepted: ["the environment"],
      hint: "what recycling protects",
      tags: ["noun", "environment"],
      tier: 1,
    },
    {
      id: "u24-t1-029",
      type: "produce",
      prompt: "the museum",
      accepted: ["il museo"],
      hint: "houses art and artifacts",
      tags: ["noun", "culture", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-030",
      type: "produce",
      prompt: "the library",
      accepted: ["la biblioteca"],
      hint: "where books are borrowed",
      tags: ["noun", "culture", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-031",
      type: "recognize",
      prompt: "il prestito",
      accepted: ["the loan"],
      hint: "borrowing a library book",
      tags: ["noun", "culture"],
      tier: 1,
    },
    {
      id: "u24-t1-032",
      type: "produce",
      prompt: "the (membership) card",
      accepted: ["la tessera"],
      hint: "needed to borrow library books",
      tags: ["noun", "general"],
      tier: 1,
    },
    {
      id: "u24-t1-033",
      type: "recognize",
      prompt: "il turno",
      accepted: ["the shift", "the turn"],
      hint: "a work shift, or a turn in line",
      tags: ["noun", "work"],
      tier: 1,
    },
    {
      id: "u24-t1-034",
      type: "recognize",
      prompt: "il cartellino",
      accepted: ["the time card", "the badge"],
      hint: "clocked in and out at work",
      tags: ["noun", "work"],
      tier: 1,
    },
    {
      id: "u24-t1-035",
      type: "produce",
      prompt: "the salary",
      accepted: ["lo stipendio"],
      hint: "paid at the end of the month",
      tags: ["noun", "work"],
      tier: 1,
    },
    {
      id: "u24-t1-036",
      type: "recognize",
      prompt: "il modulo",
      accepted: ["the form"],
      hint: "filled out for paperwork",
      tags: ["noun", "paperwork"],
      tier: 1,
    },
    {
      id: "u24-t1-037",
      type: "recognize",
      prompt: "la firma",
      accepted: ["the signature"],
      hint: "goes at the bottom of a form",
      tags: ["noun", "paperwork"],
      tier: 1,
    },
    {
      id: "u24-t1-038",
      type: "produce",
      prompt: "the appointment",
      accepted: ["l'appuntamento"],
      hint: "booked before a doctor's visit",
      tags: ["noun", "health", "general"],
      tier: 1,
    },
    {
      id: "u24-t1-039",
      type: "produce",
      prompt: "the waiting room",
      accepted: ["la sala d'attesa"],
      hint: "where patients wait their turn",
      tags: ["noun", "health"],
      tier: 1,
    },
    {
      id: "u24-t1-040",
      type: "recognize",
      prompt: "il biglietto",
      accepted: ["the ticket"],
      hint: "for a bus, train, or museum",
      tags: ["noun", "transport"],
      tier: 1,
    },
    {
      id: "u24-t1-041",
      type: "produce",
      prompt: "the (bus/train) stop",
      accepted: ["la fermata"],
      hint: "where you get on or off",
      tags: ["noun", "transport"],
      tier: 1,
    },
    {
      id: "u24-t1-042",
      type: "recognize",
      prompt: "la mancia",
      accepted: ["the tip"],
      hint: "left for good service",
      tags: ["noun", "restaurant", "money"],
      tier: 1,
    },

    // ── Tier 2 – Grammar (expansion: more si-impersonale verbs) ───────────────
    {
      id: "u24-t2-009",
      type: "conjugate",
      prompt: "dovere – si impersonale (one must)",
      accepted: ["si deve"],
      hint: "followed by an infinitive, like potere",
      tags: ["grammar", "si-impersonale", "modal"],
      tier: 2,
    },
    {
      id: "u24-t2-010",
      type: "conjugate",
      prompt: "sapere – si impersonale (it is known / one knows)",
      accepted: ["si sa"],
      hint: "si sa che + clause",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-011",
      type: "conjugate",
      prompt: "capire – si impersonale (one understands / it's understandable)",
      accepted: ["si capisce"],
      hint: "si capisce che + clause",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-012",
      type: "conjugate",
      prompt: "vedere – si impersonale (one can see / it shows)",
      accepted: ["si vede"],
      hint: "si vede che + clause",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-013",
      type: "conjugate",
      prompt: "sentire – si impersonale (one can hear / feel)",
      accepted: ["si sente"],
      hint: "si sente che + clause",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-014",
      type: "conjugate",
      prompt: "trovare – si impersonale (one finds / it is found)",
      accepted: ["si trova"],
      hint: "used for locations: si trova in centro",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-015",
      type: "conjugate",
      prompt: "vivere – si impersonale (one lives)",
      accepted: ["si vive"],
      hint: "si vive bene / male + place",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-016",
      type: "conjugate",
      prompt: "lavorare – si impersonale (one works)",
      accepted: ["si lavora"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-017",
      type: "conjugate",
      prompt: "studiare – si impersonale (one studies)",
      accepted: ["si studia"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-018",
      type: "conjugate",
      prompt: "camminare – si impersonale (one walks)",
      accepted: ["si cammina"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-019",
      type: "conjugate",
      prompt: "girare – si impersonale (one turns)",
      accepted: ["si gira"],
      hint: "used for directions: si gira a destra/sinistra",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-020",
      type: "conjugate",
      prompt: "attraversare – si impersonale (one crosses)",
      accepted: ["si attraversa"],
      hint: "used for crossing a street",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-021",
      type: "conjugate",
      prompt: "guidare – si impersonale (one drives)",
      accepted: ["si guida"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-022",
      type: "conjugate",
      prompt: "pagare – si impersonale (one pays)",
      accepted: ["si paga"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-023",
      type: "conjugate",
      prompt: "fumare – si impersonale, negative (smoking is not allowed)",
      accepted: ["non si fuma"],
      hint: "common sign/rule wording",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-024",
      type: "conjugate",
      prompt: "parcheggiare – si impersonale (one parks)",
      accepted: ["si parcheggia"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-025",
      type: "conjugate",
      prompt: "viaggiare – si impersonale (one travels)",
      accepted: ["si viaggia"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-026",
      type: "conjugate",
      prompt: "scherzare – si impersonale, negative (one doesn't joke about it)",
      accepted: ["non si scherza"],
      hint: "used to stress that something is serious",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-027",
      type: "conjugate",
      prompt: "arrivare – si impersonale (one arrives)",
      accepted: ["si arriva"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-028",
      type: "conjugate",
      prompt: "entrare – si impersonale (one enters)",
      accepted: ["si entra"],
      hint: "always third-person singular",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },

    // ── Tier 2 – Grammar (expansion: si-passivante singular/plural agreement) ─
    {
      id: "u24-t2-029",
      type: "conjugate",
      prompt: "vendere (case, plur.) – si passivante (houses are sold)",
      accepted: ["si vendono"],
      hint: "si passivante agrees with the noun: case → plural (pairs with 'si vende casa')",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-030",
      type: "conjugate",
      prompt: "cercare (un lavoratore, sing.) – si passivante (a worker is wanted)",
      accepted: ["si cerca"],
      hint: "si passivante agrees with the noun: un lavoratore → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-031",
      type: "conjugate",
      prompt: "cercare (lavoratori, plur.) – si passivante (workers are wanted)",
      accepted: ["si cercano"],
      hint: "si passivante agrees with the noun: lavoratori → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-032",
      type: "conjugate",
      prompt: "accettare (la carta, sing.) – si passivante (the card is accepted)",
      accepted: ["si accetta"],
      hint: "si passivante agrees with the noun: la carta → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-033",
      type: "conjugate",
      prompt: "accettare (le carte, plur.) – si passivante (cards are accepted)",
      accepted: ["si accettano"],
      hint: "si passivante agrees with the noun: le carte → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-034",
      type: "conjugate",
      prompt: "aprire (il negozio, sing.) – si passivante (the shop opens)",
      accepted: ["si apre"],
      hint: "si passivante agrees with the noun: il negozio → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-035",
      type: "conjugate",
      prompt: "aprire (i negozi, plur.) – si passivante (the shops open)",
      accepted: ["si aprono"],
      hint: "si passivante agrees with the noun: i negozi → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-036",
      type: "conjugate",
      prompt: "chiudere (il museo, sing.) – si passivante (the museum closes)",
      accepted: ["si chiude"],
      hint: "si passivante agrees with the noun: il museo → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-037",
      type: "conjugate",
      prompt: "chiudere (i musei, plur.) – si passivante (the museums close)",
      accepted: ["si chiudono"],
      hint: "si passivante agrees with the noun: i musei → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-038",
      type: "conjugate",
      prompt: "organizzare (la festa, sing.) – si passivante (the party is organized)",
      accepted: ["si organizza"],
      hint: "si passivante agrees with the noun: la festa → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-039",
      type: "conjugate",
      prompt: "organizzare (gli eventi, plur.) – si passivante (the events are organized)",
      accepted: ["si organizzano"],
      hint: "si passivante agrees with the noun: gli eventi → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-040",
      type: "conjugate",
      prompt: "offrire (un caffè, sing.) – si passivante (a coffee is offered)",
      accepted: ["si offre"],
      hint: "si passivante agrees with the noun: un caffè → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-041",
      type: "conjugate",
      prompt: "offrire (sconti, plur.) – si passivante (discounts are offered)",
      accepted: ["si offrono"],
      hint: "si passivante agrees with the noun: sconti → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-042",
      type: "conjugate",
      prompt: "costruire (una casa, sing.) – si passivante (a house is built)",
      accepted: ["si costruisce"],
      hint: "si passivante agrees with the noun: una casa → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-043",
      type: "conjugate",
      prompt: "costruire (nuove case, plur.) – si passivante (new houses are built)",
      accepted: ["si costruiscono"],
      hint: "si passivante agrees with the noun: nuove case → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-044",
      type: "conjugate",
      prompt: "pulire (la stanza, sing.) – si passivante (the room is cleaned)",
      accepted: ["si pulisce"],
      hint: "si passivante agrees with the noun: la stanza → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-045",
      type: "conjugate",
      prompt: "pulire (le stanze, plur.) – si passivante (the rooms are cleaned)",
      accepted: ["si puliscono"],
      hint: "si passivante agrees with the noun: le stanze → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-046",
      type: "conjugate",
      prompt: "preparare (la cena, sing.) – si passivante (dinner is prepared)",
      accepted: ["si prepara"],
      hint: "si passivante agrees with the noun: la cena → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-047",
      type: "conjugate",
      prompt: "preparare (i piatti, plur.) – si passivante (the dishes are prepared)",
      accepted: ["si preparano"],
      hint: "si passivante agrees with the noun: i piatti → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-048",
      type: "conjugate",
      prompt: "servire (il pranzo, sing.) – si passivante (lunch is served)",
      accepted: ["si serve"],
      hint: "si passivante agrees with the noun: il pranzo → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-049",
      type: "conjugate",
      prompt: "servire (i pasti, plur.) – si passivante (meals are served)",
      accepted: ["si servono"],
      hint: "si passivante agrees with the noun: i pasti → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-050",
      type: "conjugate",
      prompt: "scrivere (una lettera, sing.) – si passivante (a letter is written)",
      accepted: ["si scrive"],
      hint: "si passivante agrees with the noun: una lettera → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-051",
      type: "conjugate",
      prompt: "scrivere (lettere, plur.) – si passivante (letters are written)",
      accepted: ["si scrivono"],
      hint: "si passivante agrees with the noun: lettere → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-052",
      type: "conjugate",
      prompt: "leggere (un libro, sing.) – si passivante (a book is read)",
      accepted: ["si legge"],
      hint: "si passivante agrees with the noun: un libro → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-053",
      type: "conjugate",
      prompt: "leggere (molti libri, plur.) – si passivante (many books are read)",
      accepted: ["si leggono"],
      hint: "si passivante agrees with the noun: molti libri → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-054",
      type: "conjugate",
      prompt: "indossare (la giacca, sing.) – si passivante (the jacket is worn)",
      accepted: ["si indossa"],
      hint: "si passivante agrees with the noun: la giacca → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-055",
      type: "conjugate",
      prompt: "indossare (le scarpe, plur.) – si passivante (the shoes are worn)",
      accepted: ["si indossano"],
      hint: "si passivante agrees with the noun: le scarpe → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-056",
      type: "conjugate",
      prompt: "rispettare (la regola, sing.) – si passivante (the rule is respected)",
      accepted: ["si rispetta"],
      hint: "si passivante agrees with the noun: la regola → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-057",
      type: "conjugate",
      prompt: "rispettare (le regole, plur.) – si passivante (the rules are respected)",
      accepted: ["si rispettano"],
      hint: "si passivante agrees with the noun: le regole → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases (expansion) ─────────────────────────────────
    {
      id: "u24-t3-007",
      type: "produce",
      prompt: "No stopping / no parking (sign wording)",
      accepted: ["Divieto di sosta"],
      hint: "notices often drop the verb entirely — a bare noun phrase",
      tags: ["chunk", "si-passivante", "notices", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-008",
      type: "fill_blank",
      prompt: "Non ___ mai col rosso al semaforo. (One never goes through a red light.)",
      accepted: ["si passa"],
      hint: "si impersonale of passare, negative",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-009",
      type: "produce",
      prompt: "One turns right at the intersection.",
      accepted: ["Si gira a destra all'incrocio."],
      hint: "si impersonale of girare",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-010",
      type: "produce",
      prompt: "One crosses at the crosswalk, not on the sidewalk.",
      accepted: ["Si attraversa sulle strisce pedonali, non sul marciapiede."],
      hint: "si impersonale of attraversare",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-011",
      type: "fill_blank",
      prompt: "In centro non ___ mai un parcheggio libero. (Downtown, one never finds a free parking spot.)",
      accepted: ["si trova"],
      hint: "si impersonale of trovare",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-012",
      type: "produce",
      prompt: "A flyer is handed out at the entrance.",
      accepted: ["Si distribuisce un volantino all'ingresso."],
      hint: "si passivante, singular agreement with un volantino",
      tags: ["chunk", "si-passivante", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-013",
      type: "fill_blank",
      prompt: "Il negozio ___ con un orario molto comodo. (The shop opens with a very convenient schedule.)",
      accepted: ["si apre"],
      hint: "si passivante of aprire, singular subject (il negozio)",
      tags: ["chunk", "si-passivante", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-014",
      type: "produce",
      prompt: "People queue at the checkout on Saturdays.",
      accepted: ["Si fa la fila alla cassa il sabato."],
      hint: "si impersonale + fare la fila (to queue)",
      tags: ["chunk", "si-impersonale", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-015",
      type: "fill_blank",
      prompt: "Dopo aver pagato, ___ lo scontrino. (After paying, one gets the receipt.)",
      accepted: ["si riceve"],
      hint: "si impersonale of ricevere",
      tags: ["chunk", "si-impersonale", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-016",
      type: "produce",
      prompt: "In this shop, they always give the exact change.",
      accepted: ["In questo negozio si dà sempre il resto esatto."],
      hint: "si impersonale of dare",
      tags: ["chunk", "si-impersonale", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-017",
      type: "fill_blank",
      prompt: "Alla cassa ___ un sacchetto per la spesa. (At the register, you're given a bag for the shopping.)",
      accepted: ["si dà"],
      hint: "si impersonale of dare + il sacchetto",
      tags: ["chunk", "si-impersonale", "shopping"],
      tier: 3,
    },
    {
      id: "u24-t3-018",
      type: "produce",
      prompt: "Paper is recycled in the blue bin.",
      accepted: ["Si ricicla la carta nel bidone blu."],
      hint: "si impersonale of riciclare; bidone is singular here",
      tags: ["chunk", "si-impersonale", "environment"],
      tier: 3,
    },
    {
      id: "u24-t3-019",
      type: "fill_blank",
      prompt: "Nella raccolta differenziata ___ il vetro dalla plastica. (In recycling, glass is separated from plastic.)",
      accepted: ["si separa"],
      hint: "si impersonale of separare",
      tags: ["chunk", "si-impersonale", "environment"],
      tier: 3,
    },
    {
      id: "u24-t3-020",
      type: "produce",
      prompt: "You don't throw trash on the ground.",
      accepted: ["Non si buttano i rifiuti per terra."],
      hint: "si passivante, plural agreement with i rifiuti",
      tags: ["chunk", "si-passivante", "environment"],
      tier: 3,
    },
    {
      id: "u24-t3-021",
      type: "fill_blank",
      prompt: "Per proteggere l'ambiente ___ meno plastica possibile. (To protect the environment, one uses as little plastic as possible.)",
      accepted: ["si usa"],
      hint: "si impersonale of usare",
      tags: ["chunk", "si-impersonale", "environment"],
      tier: 3,
    },
    {
      id: "u24-t3-022",
      type: "produce",
      prompt: "At the museum, nothing is touched.",
      accepted: ["Al museo non si tocca niente."],
      hint: "si impersonale of toccare, negative",
      tags: ["chunk", "si-impersonale", "culture"],
      tier: 3,
    },
    {
      id: "u24-t3-023",
      type: "fill_blank",
      prompt: "In biblioteca ___ prendere un libro in prestito per un mese. (At the library, one can borrow a book for a month.)",
      accepted: ["si può"],
      hint: "si impersonale + potere + infinitive",
      tags: ["chunk", "si-impersonale", "culture"],
      tier: 3,
    },
    {
      id: "u24-t3-024",
      type: "produce",
      prompt: "You use the membership card to borrow books.",
      accepted: ["Si usa la tessera per prendere libri in prestito."],
      hint: "si impersonale of usare",
      tags: ["chunk", "si-impersonale", "culture"],
      tier: 3,
    },
    {
      id: "u24-t3-025",
      type: "produce",
      prompt: "You clock in at the start of the shift.",
      accepted: ["Si timbra il cartellino all'inizio del turno."],
      hint: "si impersonale of timbrare",
      tags: ["chunk", "si-impersonale", "work"],
      tier: 3,
    },
    {
      id: "u24-t3-026",
      type: "fill_blank",
      prompt: "Con questo lavoro ___ bene, anche se il turno è pesante. (This job pays well, even though the shift is heavy.)",
      accepted: ["si guadagna"],
      hint: "si impersonale of guadagnare",
      tags: ["chunk", "si-impersonale", "work"],
      tier: 3,
    },
    {
      id: "u24-t3-027",
      type: "produce",
      prompt: "A good salary is earned in this profession.",
      accepted: ["Si guadagna un buono stipendio in questa professione."],
      hint: "si impersonale of guadagnare",
      tags: ["chunk", "si-impersonale", "work"],
      tier: 3,
    },
    {
      id: "u24-t3-028",
      type: "fill_blank",
      prompt: "Prima di partire ___ il modulo e si firma in fondo. (Before leaving, you fill out the form and sign at the bottom.)",
      accepted: ["si compila"],
      hint: "si impersonale of compilare",
      tags: ["chunk", "si-impersonale", "paperwork"],
      tier: 3,
    },
    {
      id: "u24-t3-029",
      type: "produce",
      prompt: "One always signs next to the date.",
      accepted: ["Si firma sempre accanto alla data."],
      hint: "si impersonale of firmare",
      tags: ["chunk", "si-impersonale", "paperwork"],
      tier: 3,
    },
    {
      id: "u24-t3-030",
      type: "produce",
      prompt: "You make an appointment before going to the doctor.",
      accepted: ["Si prende un appuntamento prima di andare dal medico."],
      hint: "si impersonale of prendere",
      tags: ["chunk", "si-impersonale", "health"],
      tier: 3,
    },
    {
      id: "u24-t3-031",
      type: "fill_blank",
      prompt: "In sala d'attesa ___ il proprio turno in silenzio. (In the waiting room, one waits one's turn in silence.)",
      accepted: ["si aspetta"],
      hint: "si impersonale of aspettare",
      tags: ["chunk", "si-impersonale", "health"],
      tier: 3,
    },
    {
      id: "u24-t3-032",
      type: "produce",
      prompt: "The ticket is validated before boarding the train.",
      accepted: ["Si convalida il biglietto prima di salire sul treno."],
      hint: "si impersonale of convalidare",
      tags: ["chunk", "si-impersonale", "transport"],
      tier: 3,
    },
    {
      id: "u24-t3-033",
      type: "fill_blank",
      prompt: "___ alla fermata giusta, altrimenti si arriva tardi. (One gets off at the right stop, otherwise one arrives late.)",
      accepted: ["Si scende"],
      hint: "si impersonale of scendere",
      tags: ["chunk", "si-impersonale", "transport"],
      tier: 3,
    },
    {
      id: "u24-t3-034",
      type: "produce",
      prompt: "In this café, one always leaves a tip.",
      accepted: ["In questo bar si lascia sempre la mancia."],
      hint: "si impersonale of lasciare",
      tags: ["chunk", "si-impersonale", "restaurant"],
      tier: 3,
    },
    {
      id: "u24-t3-035",
      type: "fill_blank",
      prompt: "Con questa tessera ___ anche i libri più recenti. (With this card, one can also borrow the newest books.)",
      accepted: ["si prendono"],
      hint: "si passivante, plural agreement with i libri",
      tags: ["chunk", "si-passivante", "culture"],
      tier: 3,
    },
    {
      id: "u24-t3-036",
      type: "produce",
      prompt: "One drives on the right in Italy.",
      accepted: ["In Italia si guida a destra."],
      hint: "si impersonale of guidare",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-037",
      type: "fill_blank",
      prompt: "Non ___ mai al telefono mentre si guida. (One never talks on the phone while driving.)",
      accepted: ["si parla"],
      hint: "si impersonale of parlare, negative",
      tags: ["chunk", "si-impersonale", "traffic"],
      tier: 3,
    },
    {
      id: "u24-t3-038",
      type: "produce",
      prompt: "One arrives early to avoid the line.",
      accepted: ["Si arriva presto per evitare la fila."],
      hint: "si impersonale of arrivare",
      tags: ["chunk", "si-impersonale", "general"],
      tier: 3,
    },
    {
      id: "u24-t3-039",
      type: "fill_blank",
      prompt: "___ dalla porta laterale quando quella principale è chiusa. (One enters through the side door when the main one is closed.)",
      accepted: ["Si entra"],
      hint: "si impersonale of entrare",
      tags: ["chunk", "si-impersonale", "general"],
      tier: 3,
    },
    {
      id: "u24-t3-040",
      type: "produce",
      prompt: "One travels a lot for work in this profession.",
      accepted: ["Si viaggia molto per lavoro in questa professione."],
      hint: "si impersonale of viaggiare",
      tags: ["chunk", "si-impersonale", "work"],
      tier: 3,
    },
    {
      id: "u24-t3-041",
      type: "fill_blank",
      prompt: "Con questo capo non ___: le regole sono chiare. (With this boss, one doesn't joke around: the rules are clear.)",
      accepted: ["si scherza"],
      hint: "si impersonale of scherzare, negative",
      tags: ["chunk", "si-impersonale", "work"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passages (expansion) ────────────────────────────
    {
      id: "u24-t4-006",
      type: "passage_cloze",
      prompt: "Parcheggiare in centro non è mai facile. Ci sono molte strade con il divieto di sosta, e i vigili controllano spesso. Vicino al semaforo dell'incrocio principale ___ un parcheggio a pagamento, ma di solito è pieno entro le nove del mattino. Molti automobilisti preferiscono lasciare la macchina vicino alla fermata dell'autobus e continuare a piedi. Camminare sul marciapiede è più tranquillo che cercare un posto libero tra le macchine.",
      accepted: ["si trova"],
      hint: "si impersonale of trovare",
      tags: ["passage_cloze", "si-impersonale", "traffic"],
      tier: 4,
      prerequisites: ["u24-t1-013", "u24-t1-014", "u24-t1-015", "u24-t1-016", "u24-t1-017", "u24-t1-041", "u24-t2-014"],
    },
    {
      id: "u24-t4-007",
      type: "passage_cloze",
      prompt: "La raccolta differenziata è ormai un'abitudine in quasi tutte le case italiane. La carta e il cartone vanno in un sacchetto separato, mentre il vetro e la plastica finiscono in bidoni diversi. In condominio ___ i rifiuti negli orari stabiliti dal comune, di solito la mattina presto o la sera tardi. Rispettare queste regole aiuta a proteggere l'ambiente e a mantenere pulite le strade del quartiere.",
      accepted: ["si portano"],
      hint: "si passivante, plural agreement with i rifiuti",
      tags: ["passage_cloze", "si-passivante", "environment"],
      tier: 4,
      prerequisites: ["u24-t1-024", "u24-t1-025", "u24-t1-027", "u24-t1-028"],
    },
    {
      id: "u24-t4-008",
      type: "passage_cloze",
      prompt: "In biblioteca ci sono regole semplici da seguire. Prima di entrare, ___ il cellulare, perché il silenzio è importante per chi studia. Con la tessera si possono prendere in prestito fino a cinque libri per volta, di solito per un mese intero. Se un libro non viene restituito in tempo, la biblioteca invia un promemoria. Molti studenti ci passano il pomeriggio, seduti ai grandi tavoli vicino alle finestre.",
      accepted: ["si spegne"],
      hint: "si impersonale of spegnere",
      tags: ["passage_cloze", "si-impersonale", "culture"],
      tier: 4,
      prerequisites: ["u24-t1-030", "u24-t1-031", "u24-t1-032"],
    },
    {
      id: "u24-t4-009",
      type: "passage_cloze",
      prompt: "Il primo giorno in un nuovo lavoro può essere strano. Appena arrivati, ___ il cartellino per segnare l'inizio del turno, un gesto che diventa presto automatico. In molti uffici si lavora dalle nove alle diciotto, con una pausa pranzo di un'ora. Alla fine del mese si riceve lo stipendio direttamente in banca. Chi rispetta gli orari e le regole dell'azienda viene generalmente ben visto dai colleghi.",
      accepted: ["si timbra"],
      hint: "si impersonale of timbrare",
      tags: ["passage_cloze", "si-impersonale", "work"],
      tier: 4,
      prerequisites: ["u24-t1-033", "u24-t1-034", "u24-t1-035"],
    },
    {
      id: "u24-t4-010",
      type: "passage_cloze",
      prompt: "Andare dal medico in Italia richiede un po' di organizzazione. Prima di tutto ___ un appuntamento, di persona o per telefono, soprattutto per le visite specialistiche. Il giorno della visita si aspetta il proprio turno in sala d'attesa insieme ad altri pazienti. Quando arriva il momento, l'infermiera chiama il nome e si entra nello studio del medico. Alla fine si paga il ticket, se richiesto, e si torna a casa.",
      accepted: ["si prende"],
      hint: "si impersonale of prendere",
      tags: ["passage_cloze", "si-impersonale", "health"],
      tier: 4,
      prerequisites: ["u24-t1-038", "u24-t1-039"],
    },
    {
      id: "u24-t4-011",
      type: "passage_cloze",
      prompt: "In Italia il servizio è quasi sempre incluso nel conto al ristorante, quindi la mancia non è obbligatoria come in altri paesi. Tuttavia, quando il servizio è stato buono, spesso ___ qualche moneta sul tavolo prima di uscire. Nei bar più informali, invece, si arrotonda semplicemente il conto. Ogni regione ha le proprie abitudini: al nord la mancia è più rara, al sud capita più spesso di lasciarla.",
      accepted: ["si lascia"],
      hint: "si impersonale of lasciare",
      tags: ["passage_cloze", "si-impersonale", "restaurant"],
      tier: 4,
      prerequisites: ["u24-t1-042"],
    },
    {
      id: "u24-t4-012",
      type: "passage_cloze",
      prompt: "Visitare un museo richiede attenzione e rispetto per le opere esposte. Alla biglietteria si compra il biglietto, spesso con uno sconto per gli studenti. Dentro le sale non ___ le opere, anche quando sembrano vicinissime, perché il calore delle mani può danneggiarle nel tempo. Molti musei chiudono un giorno alla settimana, di solito il lunedì, per la pulizia e la manutenzione delle sale.",
      accepted: ["si toccano"],
      hint: "si passivante, plural agreement with le opere",
      tags: ["passage_cloze", "si-passivante", "culture"],
      tier: 4,
      prerequisites: ["u24-t1-029", "u24-t1-040"],
    },
    {
      id: "u24-t4-013",
      type: "passage_cloze",
      prompt: "Prendere l'autobus in città segue regole precise. Si compra il biglietto in edicola o online prima di salire, perché sull'autobus spesso non si può pagare in contanti. Appena saliti, ___ subito il biglietto nella macchinetta gialla vicino alla porta, altrimenti si rischia una multa dal controllore. Alla fermata giusta si scende, di solito annunciata da un display o da una voce registrata.",
      accepted: ["si convalida"],
      hint: "si impersonale of convalidare",
      tags: ["passage_cloze", "si-impersonale", "transport"],
      tier: 4,
      prerequisites: ["u24-t1-040", "u24-t1-041"],
    },
    {
      id: "u24-t4-014",
      type: "passage_cloze",
      prompt: "Fare la spesa al supermercato ha le sue piccole abitudini. Alla cassa si mettono i prodotti sul nastro e ___ direttamente sul display quanto si deve pagare. Dopo aver pagato con carta o contanti, si riceve sempre lo scontrino, utile in caso di reso. Molti negozi offrono anche un sacchetto riutilizzabile, spesso a pagamento, per portare a casa la spesa senza rovinare l'ambiente.",
      accepted: ["si vede"],
      hint: "si impersonale of vedere",
      tags: ["passage_cloze", "si-impersonale", "shopping"],
      tier: 4,
      prerequisites: ["u24-t1-022", "u24-t1-024", "u24-t2-012"],
    },
    {
      id: "u24-t4-015",
      type: "passage_cloze",
      prompt: "Vivere in un piccolo paese ha un ritmo diverso rispetto alla grande città. Ci si conosce quasi tutti, e ___ per strada anche con persone che non si vedono da tempo. La mattina si va al bar per il caffè, e spesso si resta a parlare del più e del meno. Nel weekend si organizzano piccole feste in piazza, dove tutto il paese si ritrova insieme.",
      accepted: ["si saluta"],
      hint: "si impersonale of salutare",
      tags: ["passage_cloze", "si-impersonale", "culture"],
      tier: 4,
      prerequisites: ["u24-t2-015"],
    },
    {
      id: "u24-t4-016",
      type: "passage_cloze",
      prompt: "Chi affitta un appartamento firma un contratto con il proprietario e riceve le chiavi il giorno del trasloco. In molti condomini ___ le regole scritte vicino all'ascensore: niente rumore dopo le ventidue, niente biciclette nell'androne. Ogni mese si paga l'affitto tramite bonifico, di solito entro il cinque. Se qualcosa si rompe, come una serratura o un rubinetto, si avvisa subito l'amministratore del palazzo.",
      accepted: ["si rispettano"],
      hint: "si passivante, plural agreement with le regole",
      tags: ["passage_cloze", "si-passivante", "general"],
      tier: 4,
      prerequisites: ["u24-t1-004", "u24-t2-057"],
    },
    {
      id: "u24-t4-017",
      type: "passage_cloze",
      prompt: "Prendere la patente in Italia richiede lezioni di teoria e di guida pratica. Prima di guidare da soli, ___ molte ore con un istruttore, imparando a rispettare i limiti di velocità e le precedenze agli incroci. Al semaforo rosso ci si ferma sempre, anche se la strada sembra vuota. Dopo l'esame, finalmente si può guidare senza l'istruttore accanto, anche se all'inizio si va piano per prudenza.",
      accepted: ["si passano"],
      hint: "si passivante, plural agreement with molte ore",
      tags: ["passage_cloze", "si-passivante", "traffic"],
      tier: 4,
      prerequisites: ["u24-t1-015", "u24-t1-016"],
    },
    {
      id: "u24-t4-018",
      type: "passage_cloze",
      prompt: "Prima di un esame importante ___ molto, spesso in biblioteca dove il silenzio aiuta a concentrarsi. Gli studenti italiani si scambiano appunti e si aiutano a vicenda per le materie più difficili. La sera prima, molti preferiscono ripassare in modo leggero invece di studiare tutta la notte. Il giorno dell'esame ci si presenta con largo anticipo, per non arrivare tardi e perdere la calma.",
      accepted: ["si studia"],
      hint: "si impersonale of studiare",
      tags: ["passage_cloze", "si-impersonale", "general"],
      tier: 4,
      prerequisites: ["u24-t1-030", "u24-t2-017"],
    },
    {
      id: "u24-t4-019",
      type: "passage_cloze",
      prompt: "Prima di un viaggio lungo ___ la valigia con calma, controllando due volte di non aver dimenticato niente di importante. Molti italiani portano sempre qualcosa da mangiare per il viaggio, anche solo un panino. In aeroporto si arriva con anticipo, perché i controlli di sicurezza possono richiedere tempo. Una volta atterrati, si cambia subito valuta se necessario e si cerca un mezzo per raggiungere il centro.",
      accepted: ["si prepara"],
      hint: "si impersonale of preparare",
      tags: ["passage_cloze", "si-impersonale", "general"],
      tier: 4,
      prerequisites: ["u24-t2-046"],
    },
    {
      id: "u24-t4-020",
      type: "passage_cloze",
      prompt: "In molti uffici italiani si lavora in gruppo su progetti condivisi. Ogni mattina ___ una breve riunione per organizzare la giornata, di solito non più di dieci minuti. Durante la pausa pranzo, i colleghi spesso mangiano insieme, anche solo un panino veloce. Alla fine della settimana si controllano i risultati raggiunti e si pianificano gli obiettivi per la settimana successiva, sempre con calma e senza fretta.",
      accepted: ["si organizza"],
      hint: "si passivante, singular agreement with una riunione",
      tags: ["passage_cloze", "si-passivante", "work"],
      tier: 4,
      prerequisites: ["u24-t2-038"],
    },
  ],
};
export default unit;
