import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-31-materials",
  name: "Materials & Textures",
  level: "B1",
  theme: "Physical Properties & Materials",
  emoji: "🪵",
  prerequisiteUnits: ["b1-unit-30-school-education"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "b131-t1-001",
      type: "recognize",
      prompt: "il legno",
      accepted: ["wood", "the wood"],
      tags: ["materials", "natural", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-002",
      type: "recognize",
      prompt: "il metallo",
      accepted: ["metal", "the metal"],
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-003",
      type: "recognize",
      prompt: "la plastica",
      accepted: ["plastic", "the plastic"],
      tags: ["materials", "synthetic", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-004",
      type: "recognize",
      prompt: "il vetro",
      accepted: ["glass", "the glass"],
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-005",
      type: "recognize",
      prompt: "il tessuto",
      accepted: ["fabric", "the fabric", "cloth", "the cloth", "material", "the material"],
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-006",
      type: "recognize",
      prompt: "il cotone",
      accepted: ["cotton", "the cotton"],
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-007",
      type: "recognize",
      prompt: "la lana",
      accepted: ["wool", "the wool"],
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-008",
      type: "recognize",
      prompt: "la seta",
      accepted: ["silk", "the silk"],
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-009",
      type: "recognize",
      prompt: "il lino",
      accepted: ["linen", "the linen"],
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-010",
      type: "recognize",
      prompt: "la pelle",
      accepted: ["leather", "the leather", "skin", "the skin"],
      hint: "context determines which meaning: clothing/accessories → leather; human/animal body → skin",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-011",
      type: "recognize",
      prompt: "il cuoio",
      accepted: ["leather", "the leather", "hide", "the hide"],
      hint: "thicker, treated animal hide; used for shoes, belts, bags",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-012",
      type: "recognize",
      prompt: "la carta",
      accepted: ["paper", "the paper"],
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-013",
      type: "recognize",
      prompt: "il cartone",
      accepted: ["cardboard", "the cardboard"],
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-014",
      type: "recognize",
      prompt: "il ferro",
      accepted: ["iron", "the iron"],
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-015",
      type: "recognize",
      prompt: "l'acciaio",
      accepted: ["steel", "the steel"],
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-016",
      type: "recognize",
      prompt: "l'alluminio",
      accepted: ["aluminium", "aluminum", "the aluminium", "the aluminum"],
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-017",
      type: "recognize",
      prompt: "il rame",
      accepted: ["copper", "the copper"],
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-018",
      type: "recognize",
      prompt: "l'oro",
      accepted: ["gold", "the gold"],
      tags: ["materials", "metal", "precious", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-019",
      type: "recognize",
      prompt: "l'argento",
      accepted: ["silver", "the silver"],
      tags: ["materials", "metal", "precious", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-020",
      type: "recognize",
      prompt: "liscio / ruvido",
      accepted: ["smooth / rough"],
      hint: "opposite texture pair",
      tags: ["materials", "texture", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-021",
      type: "recognize",
      prompt: "lucido / opaco",
      accepted: ["shiny / matte", "glossy / matte", "shiny / opaque"],
      hint: "opposite surface-finish pair",
      tags: ["materials", "texture", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-022",
      type: "recognize",
      prompt: "trasparente / flessibile / fragile / resistente / impermeabile",
      accepted: ["transparent / flexible / fragile / resistant / waterproof"],
      hint: "five key material properties",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },

    // ── Tier 2 – Fill in the Blank (di ___; material collocations) ────────────
    {
      id: "b131-t2-001",
      type: "fill_blank",
      prompt: "Questo tavolo è di ___. È pesante ma molto robusto.",
      accepted: ["legno"],
      hint: "the most common wooden furniture material",
      tags: ["materials", "collocation", "di+material"],
      tier: 2,
    },
    {
      id: "b131-t2-002",
      type: "fill_blank",
      prompt: "Ho comprato una borsa di ___. È morbida e molto elegante.",
      accepted: ["pelle", "cuoio"],
      hint: "una borsa di ___ — leather bag",
      tags: ["materials", "collocation", "di+material", "fashion"],
      tier: 2,
    },
    {
      id: "b131-t2-003",
      type: "fill_blank",
      prompt: "Per favore, metti i rifiuti nella bottiglia di ___ nel contenitore giusto.",
      accepted: ["vetro"],
      hint: "una bottiglia di ___ — a glass bottle",
      tags: ["materials", "collocation", "di+material", "environment"],
      tier: 2,
    },
    {
      id: "b131-t2-004",
      type: "fill_blank",
      prompt: "La maglietta è di ___ biologico, quindi è morbida sulla pelle e fa meno male all'ambiente.",
      accepted: ["cotone"],
      hint: "the most common natural textile for a t-shirt",
      tags: ["materials", "collocation", "di+material", "textile"],
      tier: 2,
    },

    // ── Tier 3 – Sentence Production ─────────────────────────────────────────
    {
      id: "b131-t3-001",
      type: "produce",
      prompt: "This chair is made of wood.",
      accepted: [
        "Questa sedia è di legno.",
        "Questa sedia è fatta di legno.",
        "Questa sedia è in legno.",
      ],
      tags: ["chunk", "materials", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-002",
      type: "produce",
      prompt: "I prefer cotton to synthetic fabrics.",
      accepted: [
        "Preferisco il cotone ai tessuti sintetici.",
        "Preferisco il cotone ai materiali sintetici.",
      ],
      hint: "preferire + noun + a + noun",
      tags: ["chunk", "materials", "textile", "preference"],
      tier: 3,
    },
    {
      id: "b131-t3-003",
      type: "produce",
      prompt: "Glass is fragile.",
      accepted: ["Il vetro è fragile."],
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-004",
      type: "produce",
      prompt: "The table has a smooth surface.",
      accepted: [
        "Il tavolo ha una superficie liscia.",
        "Il tavolo ha una superficie morbida e liscia.",
      ],
      tags: ["chunk", "materials", "texture"],
      tier: 3,
    },
    {
      id: "b131-t3-005",
      type: "produce",
      prompt: "She bought a leather bag.",
      accepted: [
        "Ha comprato una borsa di pelle.",
        "Ha comprato una borsa di cuoio.",
        "Lei ha comprato una borsa di pelle.",
        "Lei ha comprato una borsa di cuoio.",
      ],
      tags: ["chunk", "materials", "fashion", "di+material"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "b131-t4-001",
      type: "passage_cloze",
      prompt:
        "Ieri sono entrata in un negozio di arredamento per cercare una scrivania nuova.\n" +
        "Ne ho vista una bellissima: era di ___, con le gambe di metallo nero.\n" +
        "La superficie era liscia e lucida, perfetta per lavorare al computer.\n" +
        "Il commesso mi ha spiegato che il materiale è trattato per essere resistente ai graffi.\n" +
        "Alla fine l'ho comprata. Arriverà a casa mia la prossima settimana.",
      accepted: ["legno"],
      hint: "the classic material for a desk top, paired with metal legs",
      tags: ["passage_cloze", "materials", "shopping", "furniture"],
      tier: 4,
      prerequisites: ["b131-t1-001", "b131-t1-002", "b131-t1-021", "b131-t2-001"],
    },

    // ── Tier 1 – Vocabulary (expansion) ───────────────────────────────────────
    {
      id: "b131-t1-023",
      type: "recognize",
      prompt: "la ceramica",
      accepted: ["ceramic", "the ceramic"],
      hint: "used for pottery, tiles, and dishware",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-024",
      type: "recognize",
      prompt: "la porcellana",
      accepted: ["porcelain", "the porcelain"],
      hint: "fine, delicate ceramic used for fine dishware",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-025",
      type: "recognize",
      prompt: "la gomma",
      accepted: ["rubber", "the rubber", "eraser", "the eraser"],
      hint: "flexible material for tires and soles, or an eraser, depending on context",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-026",
      type: "recognize",
      prompt: "il cemento",
      accepted: ["cement", "the cement", "concrete", "the concrete"],
      hint: "used to build walls, floors, and sidewalks",
      tags: ["materials", "construction", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-027",
      type: "recognize",
      prompt: "la pietra",
      accepted: ["stone", "the stone"],
      hint: "natural rock material, common in old buildings",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-028",
      type: "recognize",
      prompt: "il marmo",
      accepted: ["marble", "the marble"],
      hint: "polished stone used for floors, statues, and countertops",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-029",
      type: "recognize",
      prompt: "il granito",
      accepted: ["granite", "the granite"],
      hint: "hard stone often used for kitchen countertops",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-030",
      type: "recognize",
      prompt: "il bambù",
      accepted: ["bamboo", "the bamboo"],
      hint: "fast-growing plant material, used for eco-friendly furniture and flooring",
      tags: ["materials", "natural", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-031",
      type: "recognize",
      prompt: "il sughero",
      accepted: ["cork", "the cork"],
      hint: "light, spongy bark material, used for wine stoppers",
      tags: ["materials", "natural", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-032",
      type: "recognize",
      prompt: "il nylon",
      accepted: ["nylon", "the nylon"],
      hint: "strong, lightweight synthetic fiber",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-033",
      type: "recognize",
      prompt: "il poliestere",
      accepted: ["polyester", "the polyester"],
      hint: "common wrinkle-resistant synthetic fabric",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-034",
      type: "recognize",
      prompt: "il velluto",
      accepted: ["velvet", "the velvet"],
      hint: "soft fabric with a dense, plush pile",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-035",
      type: "recognize",
      prompt: "il denim",
      accepted: ["denim", "the denim"],
      hint: "sturdy cotton twill fabric used for jeans",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-036",
      type: "recognize",
      prompt: "il feltro",
      accepted: ["felt", "the felt"],
      hint: "dense, non-woven fabric made from pressed fibers",
      tags: ["materials", "textile", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-037",
      type: "recognize",
      prompt: "la paglia",
      accepted: ["straw", "the straw"],
      hint: "dried plant material used for hats and baskets",
      tags: ["materials", "natural", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-038",
      type: "recognize",
      prompt: "il vimini",
      accepted: ["wicker", "the wicker"],
      hint: "woven plant fiber used for baskets and chairs",
      tags: ["materials", "natural", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-039",
      type: "recognize",
      prompt: "la terracotta",
      accepted: ["terracotta", "the terracotta"],
      hint: "baked reddish-brown clay, used for pots and tiles",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-040",
      type: "recognize",
      prompt: "il bronzo",
      accepted: ["bronze", "the bronze"],
      hint: "alloy of copper and tin, used for statues and bells",
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-041",
      type: "recognize",
      prompt: "l'ottone",
      accepted: ["brass", "the brass"],
      hint: "alloy of copper and zinc, used for fittings and instruments",
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-042",
      type: "recognize",
      prompt: "il piombo",
      accepted: ["lead", "the lead"],
      hint: "heavy, soft metal, historically used in pipes and paint",
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-043",
      type: "recognize",
      prompt: "lo stagno",
      accepted: ["tin", "the tin"],
      hint: "soft, silvery metal used in alloys and old toys",
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-044",
      type: "recognize",
      prompt: "il titanio",
      accepted: ["titanium", "the titanium"],
      hint: "very strong, lightweight metal used in aerospace and jewelry",
      tags: ["materials", "metal", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-045",
      type: "recognize",
      prompt: "il platino",
      accepted: ["platinum", "the platinum"],
      hint: "rare, dense precious metal, more valuable than gold",
      tags: ["materials", "metal", "precious", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-046",
      type: "recognize",
      prompt: "il cristallo",
      accepted: ["crystal", "the crystal"],
      hint: "fine, clear glass with a high lead content",
      tags: ["materials", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-047",
      type: "recognize",
      prompt: "il mattone",
      accepted: ["brick", "the brick"],
      hint: "baked clay block used to build walls",
      tags: ["materials", "construction", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-048",
      type: "recognize",
      prompt: "il gesso",
      accepted: ["plaster", "the plaster", "chalk", "the chalk"],
      hint: "used for casts and walls, or for writing on a blackboard",
      tags: ["materials", "construction", "noun"],
      tier: 1,
    },
    {
      id: "b131-t1-049",
      type: "recognize",
      prompt: "durevole",
      accepted: ["durable", "long-lasting"],
      hint: "lasts a long time without wearing out",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-050",
      type: "recognize",
      prompt: "delicato",
      accepted: ["delicate"],
      hint: "needs careful handling; easily damaged",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-051",
      type: "recognize",
      prompt: "elastico",
      accepted: ["elastic", "stretchy"],
      hint: "stretches and returns to its original shape",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-052",
      type: "recognize",
      prompt: "rigido",
      accepted: ["rigid", "stiff"],
      hint: "does not bend or flex easily",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-053",
      type: "recognize",
      prompt: "poroso",
      accepted: ["porous"],
      hint: "has tiny holes that let liquid or air through",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-054",
      type: "recognize",
      prompt: "infiammabile",
      accepted: ["flammable"],
      hint: "catches fire easily",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-055",
      type: "recognize",
      prompt: "riciclabile",
      accepted: ["recyclable"],
      hint: "can be processed and used again",
      tags: ["materials", "sustainability", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-056",
      type: "recognize",
      prompt: "biodegradabile",
      accepted: ["biodegradable"],
      hint: "breaks down naturally over time",
      tags: ["materials", "sustainability", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-057",
      type: "recognize",
      prompt: "sintetico",
      accepted: ["synthetic"],
      hint: "man-made, not found in nature",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-058",
      type: "recognize",
      prompt: "artificiale",
      accepted: ["artificial"],
      hint: "made by humans rather than occurring naturally",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-059",
      type: "recognize",
      prompt: "ecologico",
      accepted: ["eco-friendly", "ecological"],
      hint: "has a low impact on the environment",
      tags: ["materials", "sustainability", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-060",
      type: "recognize",
      prompt: "sostenibile",
      accepted: ["sustainable"],
      hint: "can be maintained without depleting resources",
      tags: ["materials", "sustainability", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-061",
      type: "recognize",
      prompt: "pregiato",
      accepted: ["fine", "prized"],
      hint: "of high quality, valued highly",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },
    {
      id: "b131-t1-062",
      type: "recognize",
      prompt: "massiccio",
      accepted: ["solid", "massive"],
      hint: "made entirely of one material, not hollow or plated",
      tags: ["materials", "properties", "adjective"],
      tier: 1,
    },

    // ── Tier 2 – Fill in the Blank (expansion) ────────────────────────────────
    {
      id: "b131-t2-005",
      type: "fill_blank",
      prompt: "Il pavimento della cucina è di ___, quindi è freddo d'inverno ma facile da pulire.",
      accepted: ["ceramica"],
      hint: "common tile material for floors, cool and easy to clean",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-006",
      type: "fill_blank",
      prompt: "Quel vaso antico è di ___ ed è così delicato che non lo tocco mai.",
      accepted: ["porcellana"],
      hint: "fine, fragile ceramic used for antique dishware",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-007",
      type: "fill_blank",
      prompt: "La suola delle scarpe da corsa è di ___ per assorbire meglio gli urti.",
      accepted: ["gomma"],
      hint: "flexible material used for shoe soles and tires",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-008",
      type: "fill_blank",
      prompt: "Il marciapiede davanti a casa mia è di ___ e si è crepato con il freddo.",
      accepted: ["cemento"],
      hint: "material used for sidewalks and building foundations",
      tags: ["materials", "collocation", "di+material", "construction"],
      tier: 2,
    },
    {
      id: "b131-t2-009",
      type: "fill_blank",
      prompt: "Il muro del castello medievale è fatto di ___ e ha resistito per secoli.",
      accepted: ["pietra"],
      hint: "natural rock material used in old buildings",
      tags: ["materials", "collocation", "fatto di", "construction"],
      tier: 2,
    },
    {
      id: "b131-t2-010",
      type: "fill_blank",
      prompt: "Il pavimento del bagno è di ___ bianco, lucido e molto elegante.",
      accepted: ["marmo"],
      hint: "polished stone, common in bathrooms and statues",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-011",
      type: "fill_blank",
      prompt: "Il piano della cucina è di ___ nero, resistente ai graffi e al calore.",
      accepted: ["granito"],
      hint: "hard stone often chosen for kitchen countertops",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-012",
      type: "fill_blank",
      prompt: "Ho comprato un tagliere di ___ perché è più leggero ed ecologico del legno.",
      accepted: ["bambù"],
      hint: "fast-growing, eco-friendly plant material",
      tags: ["materials", "collocation", "di+material", "sustainability"],
      tier: 2,
    },
    {
      id: "b131-t2-013",
      type: "fill_blank",
      prompt: "Il tappo della bottiglia di vino è di ___, un materiale naturale e leggero.",
      accepted: ["sughero"],
      hint: "light material from tree bark, used for wine stoppers",
      tags: ["materials", "collocation", "di+material"],
      tier: 2,
    },
    {
      id: "b131-t2-014",
      type: "fill_blank",
      prompt: "Questa giacca impermeabile è di ___, un tessuto sintetico molto resistente.",
      accepted: ["nylon"],
      hint: "strong synthetic fiber, common in waterproof jackets",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-015",
      type: "fill_blank",
      prompt: "La camicia è di ___ perché non si stropiccia facilmente in valigia.",
      accepted: ["poliestere"],
      hint: "wrinkle-resistant synthetic fabric",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-016",
      type: "fill_blank",
      prompt: "Il divano del salotto è di ___ rosso, morbido al tatto ma difficile da pulire.",
      accepted: ["velluto"],
      hint: "soft, plush fabric used for upholstery",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-017",
      type: "fill_blank",
      prompt: "I miei jeans preferiti sono di ___ scuro e durano da anni.",
      accepted: ["denim"],
      hint: "sturdy cotton fabric used for jeans",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-018",
      type: "fill_blank",
      prompt: "Il cappello invernale è di ___ grigio, caldo ma non troppo pesante.",
      accepted: ["feltro"],
      hint: "dense pressed-fiber fabric used for hats",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-019",
      type: "fill_blank",
      prompt: "Il cappello estivo è di ___ intrecciata e protegge dal sole.",
      accepted: ["paglia"],
      hint: "dried plant material woven into summer hats",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-020",
      type: "fill_blank",
      prompt: "Il cesto della biancheria è di ___ e ha un bel motivo intrecciato.",
      accepted: ["vimini"],
      hint: "woven plant fiber used for baskets",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-021",
      type: "fill_blank",
      prompt: "Il vaso da giardino è di ___ rossa e assorbe l'umidità del terreno.",
      accepted: ["terracotta"],
      hint: "baked reddish clay used for garden pots",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-022",
      type: "fill_blank",
      prompt: "La statua nella piazza è di ___ ed è verde per l'ossidazione.",
      accepted: ["bronzo"],
      hint: "copper-tin alloy used for statues, turns green over time",
      tags: ["materials", "collocation", "di+material", "art"],
      tier: 2,
    },
    {
      id: "b131-t2-023",
      type: "fill_blank",
      prompt: "Le maniglie delle porte sono di ___ lucido, dorato e freddo al tatto.",
      accepted: ["ottone"],
      hint: "gold-colored copper-zinc alloy used for fittings",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-024",
      type: "fill_blank",
      prompt: "I tubi vecchi di questa casa erano di ___, un materiale ormai vietato per l'acqua potabile.",
      accepted: ["piombo"],
      hint: "heavy, soft metal now banned in drinking-water pipes",
      tags: ["materials", "collocation", "di+material", "construction"],
      tier: 2,
    },
    {
      id: "b131-t2-025",
      type: "fill_blank",
      prompt: "Il soldatino antico sul comodino è di ___ ed è molto pesante per le sue dimensioni.",
      accepted: ["stagno"],
      hint: "soft silvery metal used for toy soldiers and alloys",
      tags: ["materials", "collocation", "di+material"],
      tier: 2,
    },
    {
      id: "b131-t2-026",
      type: "fill_blank",
      prompt: "L'orologio da polso è di ___, leggerissimo ma resistentissimo ai graffi.",
      accepted: ["titanio"],
      hint: "very strong, lightweight metal used in watches and aerospace",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-027",
      type: "fill_blank",
      prompt: "L'anello di fidanzamento ha una montatura di ___, più raro e prezioso dell'oro.",
      accepted: ["platino"],
      hint: "rare precious metal, denser and more valuable than gold",
      tags: ["materials", "collocation", "di+material", "jewelry"],
      tier: 2,
    },
    {
      id: "b131-t2-028",
      type: "fill_blank",
      prompt: "Il lampadario del salone è di ___ e riflette la luce in modo spettacolare.",
      accepted: ["cristallo"],
      hint: "fine lead glass used for chandeliers and fine glassware",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-029",
      type: "fill_blank",
      prompt: "Il medico ha messo un ___ al braccio rotto, un materiale rigido che si indurisce in pochi minuti.",
      accepted: ["gesso"],
      hint: "hardens quickly; used for casts on broken bones, or blackboard chalk",
      tags: ["materials", "collocation", "di+material", "health"],
      tier: 2,
    },
    {
      id: "b131-t2-030",
      type: "fill_blank",
      prompt: "Le pentole professionali sono spesso di ___ perché conduce il calore in modo uniforme.",
      accepted: ["rame"],
      hint: "reddish metal, excellent heat conductor for cookware",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-031",
      type: "fill_blank",
      prompt: "Gli attrezzi da giardino di buona qualità sono di ___ inossidabile, così non arrugginiscono.",
      accepted: ["acciaio"],
      hint: "stainless version of this metal resists rust",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-032",
      type: "fill_blank",
      prompt: "Il vecchio ponte di ___ sul fiume è stato costruito più di cent'anni fa.",
      accepted: ["ferro"],
      hint: "strong metal traditionally used for bridges and railings",
      tags: ["materials", "collocation", "di+material", "construction"],
      tier: 2,
    },
    {
      id: "b131-t2-033",
      type: "fill_blank",
      prompt: "Le lenzuola di ___ egiziano sono famose per la loro morbidezza e qualità.",
      accepted: ["cotone"],
      hint: "soft natural fiber, prized in fine bed linens",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-034",
      type: "fill_blank",
      prompt: "Il maglione di ___ tiene caldo anche nelle giornate più fredde dell'inverno.",
      accepted: ["lana"],
      hint: "warm natural fiber from sheep, used in sweaters",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-035",
      type: "fill_blank",
      prompt: "La cravatta di ___ ha un aspetto lucido ed elegante, perfetta per le occasioni importanti.",
      accepted: ["seta"],
      hint: "shiny, luxurious natural fiber used for fine accessories",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-036",
      type: "fill_blank",
      prompt: "Le lenzuola di ___ sono fresche d'estate ma si stropicciano facilmente.",
      accepted: ["lino"],
      hint: "breathable natural fabric, wrinkles easily",
      tags: ["materials", "collocation", "di+material", "household"],
      tier: 2,
    },
    {
      id: "b131-t2-037",
      type: "fill_blank",
      prompt: "Il portafoglio di ___ invecchia bene e diventa più bello con il tempo.",
      accepted: ["pelle", "cuoio"],
      hint: "leather ages well and develops character over time",
      tags: ["materials", "collocation", "di+material", "clothing"],
      tier: 2,
    },
    {
      id: "b131-t2-038",
      type: "fill_blank",
      prompt: "Le scatole per il trasloco sono di ___ robusto, riciclato e facile da smaltire.",
      accepted: ["cartone"],
      hint: "sturdy recycled material used for moving boxes",
      tags: ["materials", "collocation", "di+material", "sustainability"],
      tier: 2,
    },
    {
      id: "b131-t2-039",
      type: "fill_blank",
      prompt: "I quaderni scolastici sono fatti di ___ riciclata per rispettare l'ambiente.",
      accepted: ["carta"],
      hint: "recycled version of this material reduces environmental impact",
      tags: ["materials", "collocation", "fatto di", "sustainability"],
      tier: 2,
    },

    // ── Tier 3 – Sentence Production (expansion) ──────────────────────────────
    {
      id: "b131-t3-006",
      type: "produce",
      prompt: "This backpack is durable.",
      accepted: ["Questo zaino è durevole."],
      hint: "durevole = long-lasting, withstands wear",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-007",
      type: "produce",
      prompt: "This vase is delicate.",
      accepted: ["Questo vaso è delicato."],
      hint: "delicato = needs careful handling",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-008",
      type: "produce",
      prompt: "This fabric is elastic and adapts to the body.",
      accepted: ["Questo tessuto è elastico e si adatta al corpo."],
      hint: "elastico = stretches and returns to shape",
      tags: ["chunk", "materials", "textile", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-009",
      type: "produce",
      prompt: "This plastic material is rigid and doesn't bend.",
      accepted: ["Questo materiale plastico è rigido e non si piega."],
      hint: "rigido = stiff, does not flex",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-010",
      type: "produce",
      prompt: "This wood is porous and absorbs moisture.",
      accepted: ["Questo legno è poroso e assorbe l'umidità."],
      hint: "poroso = has tiny holes that absorb liquid",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-011",
      type: "produce",
      prompt: "This fabric is flammable, so it's dangerous near fire.",
      accepted: ["Questo tessuto è infiammabile, quindi è pericoloso vicino al fuoco."],
      hint: "infiammabile = catches fire easily",
      tags: ["chunk", "materials", "properties", "safety"],
      tier: 3,
    },
    {
      id: "b131-t3-012",
      type: "produce",
      prompt: "This material is recyclable.",
      accepted: ["Questo materiale è riciclabile."],
      hint: "riciclabile = can be processed and reused",
      tags: ["chunk", "materials", "sustainability"],
      tier: 3,
    },
    {
      id: "b131-t3-013",
      type: "produce",
      prompt: "This bag is biodegradable and breaks down within a few months.",
      accepted: ["Questo sacchetto è biodegradabile e si decompone in pochi mesi."],
      hint: "biodegradabile = breaks down naturally",
      tags: ["chunk", "materials", "sustainability"],
      tier: 3,
    },
    {
      id: "b131-t3-014",
      type: "produce",
      prompt: "This fabric is synthetic, not natural.",
      accepted: ["Questo tessuto è sintetico, non naturale."],
      hint: "sintetico = man-made",
      tags: ["chunk", "materials", "textile", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-015",
      type: "produce",
      prompt: "This flower is artificial but looks very real.",
      accepted: ["Questo fiore è artificiale ma sembra molto vero."],
      hint: "artificiale = man-made, not natural",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-016",
      type: "produce",
      prompt: "This bag is eco-friendly because it's made of recycled cotton.",
      accepted: ["Questo sacchetto è ecologico perché è fatto di cotone riciclato."],
      hint: "ecologico = low environmental impact",
      tags: ["chunk", "materials", "sustainability"],
      tier: 3,
    },
    {
      id: "b131-t3-017",
      type: "produce",
      prompt: "This choice is more sustainable than plastic.",
      accepted: ["Questa scelta è più sostenibile della plastica."],
      hint: "sostenibile = can be maintained without depleting resources",
      tags: ["chunk", "materials", "sustainability", "comparison"],
      tier: 3,
    },
    {
      id: "b131-t3-018",
      type: "produce",
      prompt: "This wood is prized for its color and hardness.",
      accepted: ["Questo legno è pregiato per il suo colore e la sua durezza."],
      hint: "pregiato = highly valued, fine quality",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-019",
      type: "produce",
      prompt: "This ring is made of solid gold.",
      accepted: ["Questo anello è d'oro massiccio."],
      hint: "massiccio = solid all the way through, not hollow or plated",
      tags: ["chunk", "materials", "jewelry", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-020",
      type: "produce",
      prompt: "Every brick in this house was laid by hand.",
      accepted: ["Ogni mattone di questa casa è stato posato a mano."],
      hint: "mattone = brick, the basic unit of a wall",
      tags: ["chunk", "materials", "construction"],
      tier: 3,
    },
    {
      id: "b131-t3-021",
      type: "produce",
      prompt: "This table is handmade.",
      accepted: ["Questo tavolo è fatto a mano."],
      hint: "fatto a mano = handmade, a common quality collocation",
      tags: ["chunk", "materials", "collocation", "quality"],
      tier: 3,
    },
    {
      id: "b131-t3-022",
      type: "produce",
      prompt: "This suit is tailor-made.",
      accepted: ["Questo vestito è fatto su misura."],
      hint: "fatto su misura = made to measure, custom-made",
      tags: ["chunk", "materials", "collocation", "clothing"],
      tier: 3,
    },
    {
      id: "b131-t3-023",
      type: "produce",
      prompt: "This is high-quality leather.",
      accepted: ["Questa è pelle di prima scelta."],
      hint: "di prima scelta = top quality, first choice",
      tags: ["chunk", "materials", "collocation", "quality"],
      tier: 3,
    },
    {
      id: "b131-t3-024",
      type: "produce",
      prompt: "This wool is 100% natural.",
      accepted: ["Questa lana è al cento per cento naturale."],
      hint: "al cento per cento = 100%, a common quality phrase",
      tags: ["chunk", "materials", "collocation", "quality"],
      tier: 3,
    },
    {
      id: "b131-t3-025",
      type: "produce",
      prompt: "Steel is more resistant than iron.",
      accepted: ["L'acciaio è più resistente del ferro."],
      hint: "più resistente di = more resistant than",
      tags: ["chunk", "materials", "comparison"],
      tier: 3,
    },
    {
      id: "b131-t3-026",
      type: "produce",
      prompt: "Aluminium is lighter than steel.",
      accepted: ["L'alluminio è più leggero dell'acciaio."],
      hint: "più leggero di = lighter than",
      tags: ["chunk", "materials", "comparison"],
      tier: 3,
    },
    {
      id: "b131-t3-027",
      type: "produce",
      prompt: "Gold doesn't rust.",
      accepted: ["L'oro non si arrugginisce."],
      hint: "arrugginirsi = to rust, reflexive verb",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-028",
      type: "produce",
      prompt: "Silver tarnishes over time.",
      accepted: ["L'argento si annerisce con il tempo."],
      hint: "annerirsi = to tarnish, literally 'to turn black'",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-029",
      type: "produce",
      prompt: "This glass doesn't break easily.",
      accepted: ["Questo vetro non si rompe facilmente."],
      hint: "rompersi = to break, reflexive verb",
      tags: ["chunk", "materials", "properties"],
      tier: 3,
    },
    {
      id: "b131-t3-030",
      type: "produce",
      prompt: "This plastic can be recycled at any collection point.",
      accepted: ["Questa plastica può essere riciclata in qualsiasi punto di raccolta."],
      hint: "può essere riciclata = can be recycled, passive construction",
      tags: ["chunk", "materials", "sustainability"],
      tier: 3,
    },
    {
      id: "b131-t3-031",
      type: "produce",
      prompt: "This chair is made of solid oak wood.",
      accepted: ["Questa sedia è fatta di legno di quercia massiccio."],
      hint: "quercia = oak; massiccio reinforces 'solid, not hollow'",
      tags: ["chunk", "materials", "furniture", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-032",
      type: "produce",
      prompt: "This copper pot heats food evenly.",
      accepted: ["Questa pentola di rame scalda il cibo in modo uniforme."],
      hint: "conducts heat evenly, a key reason copper cookware is prized",
      tags: ["chunk", "materials", "household", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-033",
      type: "produce",
      prompt: "This titanium watch is scratch-resistant.",
      accepted: ["Questo orologio di titanio è resistente ai graffi."],
      hint: "resistente ai graffi = scratch-resistant",
      tags: ["chunk", "materials", "clothing", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-034",
      type: "produce",
      prompt: "This platinum ring was very expensive.",
      accepted: ["Questo anello di platino è costato molto."],
      hint: "costare molto = to cost a lot",
      tags: ["chunk", "materials", "jewelry", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-035",
      type: "produce",
      prompt: "This crystal glass shines under the light.",
      accepted: ["Questo bicchiere di cristallo brilla sotto la luce."],
      hint: "brillare = to shine, sparkle",
      tags: ["chunk", "materials", "household", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-036",
      type: "produce",
      prompt: "This basket is made of wicker.",
      accepted: ["Questo cesto è fatto di vimini."],
      hint: "reinforces vimini in a simple fatto di construction",
      tags: ["chunk", "materials", "household", "fatto di"],
      tier: 3,
    },
    {
      id: "b131-t3-037",
      type: "produce",
      prompt: "This hat is made of straw and protects from the sun.",
      accepted: ["Questo cappello di paglia protegge dal sole."],
      hint: "proteggere dal sole = to protect from the sun",
      tags: ["chunk", "materials", "clothing", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-038",
      type: "produce",
      prompt: "This scarf is made of pure silk.",
      accepted: ["Questa sciarpa è di pura seta."],
      hint: "pura seta = pure silk",
      tags: ["chunk", "materials", "clothing", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-039",
      type: "produce",
      prompt: "This tablecloth is made of linen.",
      accepted: ["Questa tovaglia è di lino."],
      hint: "tovaglia = tablecloth",
      tags: ["chunk", "materials", "household", "di+material"],
      tier: 3,
    },
    {
      id: "b131-t3-040",
      type: "produce",
      prompt: "This cardboard box is sturdy enough for the move.",
      accepted: ["Questa scatola di cartone è abbastanza robusta per il trasloco."],
      hint: "abbastanza + adjective = adjective enough",
      tags: ["chunk", "materials", "household", "di+material"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze (expansion) ────────────────────────────────────
    {
      id: "b131-t4-002",
      type: "passage_cloze",
      prompt:
        "Il mese scorso ho visitato un mercatino dell'antiquariato con mia nonna, che colleziona piccoli oggetti da tutta la vita.\n" +
        "Ha trovato un tavolino rotondo con il piano di ___, freddo al tatto ma bellissimo da vedere.\n" +
        "Il venditore ha raccontato che veniva da una villa ottocentesca vicino a Firenze.\n" +
        "Mia nonna ha contrattato un po' sul prezzo e alla fine lo ha comprato.\n" +
        "Ora quel tavolino ha un posto d'onore nel suo salotto.",
      accepted: ["marmo"],
      hint: "cold, elegant stone often used for antique tabletops and statues",
      tags: ["passage_cloze", "materials", "shopping", "furniture"],
      tier: 4,
      prerequisites: ["b131-t1-028", "b131-t2-010"],
    },
    {
      id: "b131-t4-003",
      type: "passage_cloze",
      prompt:
        "Quest'estate abbiamo deciso di rinnovare la cucina e cambiare il vecchio pavimento di piastrelle.\n" +
        "Il pavimento nuovo è di ___, un materiale che cresce velocemente e inquina meno del legno tradizionale.\n" +
        "L'operaio ci ha spiegato che è anche più resistente all'umidità rispetto al parquet classico.\n" +
        "All'inizio eravamo indecisi sul colore, ma alla fine abbiamo scelto un tono chiaro che illumina la stanza.\n" +
        "Ora la cucina sembra più grande e più moderna di prima.",
      accepted: ["bambù"],
      hint: "fast-growing, eco-friendly material increasingly used for flooring",
      tags: ["passage_cloze", "materials", "home", "sustainability"],
      tier: 4,
      prerequisites: ["b131-t1-030", "b131-t2-012"],
    },
    {
      id: "b131-t4-004",
      type: "passage_cloze",
      prompt:
        "Per il mio trentesimo compleanno mio marito mi ha regalato un orologio sportivo.\n" +
        "La cassa è di ___, un metallo leggerissimo ma allo stesso tempo molto resistente agli urti.\n" +
        "Lo indosso ogni giorno, anche quando corro o vado in piscina, perché non arrugginisce mai.\n" +
        "Il commesso in negozio mi aveva assicurato che dura molti anni senza perdere la sua bellezza.\n" +
        "Da allora non l'ho più tolto dal polso.",
      accepted: ["titanio"],
      hint: "extremely light, strong metal used in high-end watches",
      tags: ["passage_cloze", "materials", "clothing", "gift"],
      tier: 4,
      prerequisites: ["b131-t1-044", "b131-t2-026"],
    },
    {
      id: "b131-t4-005",
      type: "passage_cloze",
      prompt:
        "Ogni estate la nonna prepara il pranzo per tutta la famiglia e lo porta al parco.\n" +
        "Mette la focaccia, la frutta e le bibite in un grande cesto di ___ che ha comprato anni fa al mercato.\n" +
        "Il cesto è leggero ma abbastanza forte da reggere tutto il peso del cibo.\n" +
        "I bambini si siedono intorno alla coperta e aspettano che la nonna apra il cesto.\n" +
        "Quel momento è ormai una tradizione che nessuno vuole perdere.",
      accepted: ["vimini"],
      hint: "woven material for baskets, strong but lightweight",
      tags: ["passage_cloze", "materials", "family", "household"],
      tier: 4,
      prerequisites: ["b131-t1-038", "b131-t3-036"],
    },
    {
      id: "b131-t4-006",
      type: "passage_cloze",
      prompt:
        "Quando abbiamo comprato la casa vecchia, le porte avevano ancora le maniglie originali.\n" +
        "Erano di ___, un po' opache dopo tanti anni, ma con un disegno molto elegante.\n" +
        "Abbiamo deciso di pulirle invece di sostituirle, perché raccontano la storia dell'edificio.\n" +
        "Dopo ore di lavoro con un panno morbido, hanno ripreso a brillare come nuove.\n" +
        "Ora sono uno dei dettagli che i nostri ospiti notano subito.",
      accepted: ["ottone"],
      hint: "copper-zinc alloy, common on old door fittings",
      tags: ["passage_cloze", "materials", "home", "history"],
      tier: 4,
      prerequisites: ["b131-t1-041", "b131-t2-023"],
    },
    {
      id: "b131-t4-007",
      type: "passage_cloze",
      prompt:
        "Nella credenza di mia madre ci sono sei bicchieri che erano della bisnonna.\n" +
        "Sono di ___ e li usiamo soltanto nelle occasioni speciali, come Natale o i compleanni importanti.\n" +
        "Ogni volta che li laviamo, mia madre ci ricorda di fare attenzione perché si possono scheggiare facilmente.\n" +
        "Alla luce del lampadario, quei bicchieri brillano in un modo che nessun altro oggetto in casa ha.\n" +
        "Un giorno li lascerò a mia figlia, insieme alla loro storia.",
      accepted: ["cristallo"],
      hint: "fine, fragile glass reserved for special occasions",
      tags: ["passage_cloze", "materials", "family", "household"],
      tier: 4,
      prerequisites: ["b131-t1-046", "b131-t2-028"],
    },
    {
      id: "b131-t4-008",
      type: "passage_cloze",
      prompt:
        "Il weekend scorso ci siamo trasferiti in un appartamento più grande, vicino al centro.\n" +
        "Abbiamo riempito più di trenta scatole di ___ con libri, vestiti e piatti.\n" +
        "Alla fine del trasloco, invece di buttarle, le abbiamo portate al centro di riciclaggio del quartiere.\n" +
        "È stato un lavoro faticoso, ma finalmente abbiamo più spazio per vivere.\n" +
        "Il nuovo appartamento ha anche un balcone, cosa che prima non avevamo mai avuto.",
      accepted: ["cartone"],
      hint: "sturdy recyclable material used for moving boxes",
      tags: ["passage_cloze", "materials", "home", "sustainability"],
      tier: 4,
      prerequisites: ["b131-t1-013", "b131-t2-038"],
    },
    {
      id: "b131-t4-009",
      type: "passage_cloze",
      prompt:
        "A dicembre siamo andati in montagna per una settimana di vacanza sulla neve.\n" +
        "Mia sorella mi ha prestato un maglione di ___ pesante, perfetto per le serate fredde davanti al camino.\n" +
        "La prima notte ha nevicato tantissimo e la mattina dopo tutto il paese era bianco.\n" +
        "Abbiamo passato i giorni a sciare e le sere a giocare a carte con gli amici.\n" +
        "Quel maglione ora è diventato il mio preferito per ogni inverno.",
      accepted: ["lana"],
      hint: "warm natural fiber, ideal for cold-weather trips",
      tags: ["passage_cloze", "materials", "clothing", "travel"],
      tier: 4,
      prerequisites: ["b131-t1-007", "b131-t2-034"],
    },
    {
      id: "b131-t4-010",
      type: "passage_cloze",
      prompt:
        "Per la laurea di mio fratello, i nostri genitori gli hanno regalato un portafoglio elegante.\n" +
        "È di ___ marrone scuro, cucito a mano da un artigiano fiorentino molto conosciuto.\n" +
        "Mio fratello lo usa ogni giorno per andare al lavoro e dice che con il tempo diventa sempre più bello.\n" +
        "L'artigiano gli aveva spiegato che questo materiale invecchia bene, a differenza di molti tessuti sintetici.\n" +
        "Ora anche io vorrei un regalo simile per la mia laurea.",
      accepted: ["cuoio", "pelle"],
      hint: "leather that ages well, prized in handmade goods",
      tags: ["passage_cloze", "materials", "clothing", "gift"],
      tier: 4,
      prerequisites: ["b131-t1-010", "b131-t1-011", "b131-t2-037"],
    },
    {
      id: "b131-t4-011",
      type: "passage_cloze",
      prompt:
        "Il palazzo dove abito ha dei balconi molto antichi, costruiti più di cent'anni fa.\n" +
        "Le ringhiere sono di ___ battuto, decorate con motivi floreali molto dettagliati.\n" +
        "Ogni tanto un fabbro viene a controllare che non ci sia ruggine e a ridipingerle di nero.\n" +
        "I vicini dicono che quei balconi sono uno dei motivi per cui i turisti si fermano a fotografare l'edificio.\n" +
        "Anche dopo un secolo, quelle ringhiere sembrano ancora solide.",
      accepted: ["ferro"],
      hint: "strong metal traditionally shaped into decorative railings",
      tags: ["passage_cloze", "materials", "home", "history"],
      tier: 4,
      prerequisites: ["b131-t1-014", "b131-t2-032"],
    },
  ],
};
export default unit;
