import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-21-trapassato",
  name: "The Distant Past",
  level: "B1",
  theme: "Trapassato Prossimo",
  emoji: "📜",
  prerequisiteUnits: ["b1-unit-20-congiuntivo"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u21-t1-001",
      type: "recognize",
      prompt: "la storia",
      accepted: ["the story", "the history"],
      hint: "can mean both 'story' and 'history'",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-002",
      type: "produce",
      prompt: "the story (a narrative tale)",
      accepted: ["il racconto"],
      hint: "more specifically a short narrative",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-003",
      type: "produce",
      prompt: "the character (in a story)",
      accepted: ["il personaggio"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-004",
      type: "produce",
      prompt: "the beginning",
      accepted: ["l'inizio"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-005",
      type: "produce",
      prompt: "the end",
      accepted: ["la fine"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-006",
      type: "recognize",
      prompt: "poi",
      accepted: ["then", "afterwards", "next"],
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-007",
      type: "recognize",
      prompt: "dopo",
      accepted: ["after", "afterwards", "later"],
      tags: ["adverb", "preposition", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-008",
      type: "recognize",
      prompt: "infine",
      accepted: ["finally", "in the end", "at last"],
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-009",
      type: "recognize",
      prompt: "alla fine",
      accepted: ["in the end", "at the end", "finally"],
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-010",
      type: "recognize",
      prompt: "nel frattempo",
      accepted: ["meanwhile", "in the meantime"],
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-011",
      type: "produce",
      prompt: "the event",
      accepted: ["l'evento"],
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-012",
      type: "recognize",
      prompt: "già",
      accepted: ["already", "yet"],
      hint: "used to indicate something completed before another action",
      tags: ["adverb", "trapassato", "sequencing"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ────────────────────────────────────────────────────
    {
      id: "u21-t2-001",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – io",
      accepted: ["avevo mangiato"],
      hint: "avere in imperfetto + participio passato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-002",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (maschile)",
      accepted: ["ero andato"],
      hint: "essere in imperfetto + participio passato; accordo con soggetto",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-003",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (femminile)",
      accepted: ["ero andata"],
      hint: "essere in imperfetto + participio passato accordato",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-004",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – tu",
      accepted: ["avevi visto"],
      hint: "avere in imperfetto (avevi) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-005",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – lui/lei",
      accepted: ["aveva fatto"],
      hint: "avere in imperfetto (aveva) + participio irregolare",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-006",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – noi",
      accepted: ["eravamo partiti"],
      hint: "essere in imperfetto + participio; plurale maschile",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-007",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – lui/lei",
      accepted: ["aveva finito"],
      hint: "avere in imperfetto (aveva) + participio regolare",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-008",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – loro",
      accepted: ["erano arrivati"],
      hint: "essere in imperfetto + participio; plurale",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u21-t3-001",
      type: "produce",
      prompt: "He had already finished when she arrived.",
      accepted: ["Aveva già finito quando lei è arrivata.", "Aveva già finito quando è arrivata."],
      hint: "trapassato + già + quando + passato prossimo",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-002",
      type: "produce",
      prompt: "After we had left, it started to rain.",
      accepted: ["Dopo che eravamo partiti, ha cominciato a piovere.", "Dopo che eravamo partiti, è cominciato a piovere."],
      hint: "Dopo che + trapassato, passato prossimo",
      tags: ["trapassato-prossimo", "chunk", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-003",
      type: "produce",
      prompt: "I had never seen such a beautiful story.",
      accepted: ["Non avevo mai visto una storia così bella.", "Non avevo mai visto un racconto così bello."],
      hint: "non + trapassato + mai",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-004",
      type: "fill_blank",
      prompt: "As soon as the character ___ (arrivare, trapassato, lui) at the beginning, the story changed.",
      accepted: ["era arrivato"],
      hint: "appena + trapassato with essere",
      tags: ["trapassato-prossimo", "fill-blank", "appena"],
      tier: 3,
    },
    {
      id: "u21-t3-005",
      type: "fill_blank",
      prompt: "Meanwhile, she had already read the end of the story: aveva già ___ la fine della storia.",
      accepted: ["letto"],
      hint: "participio passato irregolare di 'leggere'",
      tags: ["trapassato-prossimo", "fill-blank", "irregular-participle"],
      tier: 3,
    },
    {
      id: "u21-t3-006",
      type: "produce",
      prompt: "He had done everything before the event.",
      accepted: ["Aveva fatto tutto prima dell'evento.", "Aveva fatto tutto prima dell'evento."],
      hint: "trapassato di 'fare' + prima di",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },

    // ── Tier 4 – Sentences & Passages ───────────────────────────────────────
    {
      id: "u21-t4-001",
      type: "produce",
      prompt: "When I arrived at the end of the story, I had already understood the character.",
      accepted: [
        "Quando sono arrivato alla fine della storia, avevo già capito il personaggio.",
        "Quando sono arrivata alla fine della storia, avevo già capito il personaggio.",
      ],
      hint: "passato prossimo for the arrival; trapassato for the earlier understanding",
      tags: ["trapassato-prossimo", "sentence", "sequencing"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-003", "u21-t1-005", "u21-t1-012", "u21-t2-001"],
    },
    {
      id: "u21-t4-002",
      type: "fill_blank",
      prompt: "Dopo che il personaggio ___ (partire, trapassato, lui) dalla città, la storia è diventata più interessante.",
      accepted: ["era partito"],
      hint: "essere in imperfetto + participio passato di 'partire'",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 4,
      prerequisites: ["u21-t1-003", "u21-t1-007", "u21-t2-006"],
    },
    {
      id: "u21-t4-003",
      type: "passage_cloze",
      prompt: "Marco aprì il libro e cominciò a leggere il racconto dall'inizio.\nIl personaggio principale era un giovane che non aveva mai viaggiato lontano dalla sua città.\nMa quella mattina tutto era cambiato: qualcuno gli aveva dato una mappa misteriosa.\nMarco si rese conto che il personaggio ___ già la risposta, ma non lo sapeva ancora.\nAlla fine del primo capitolo, la storia era diventata impossibile da lasciare.",
      accepted: ["aveva trovato", "aveva capito"],
      hint: "trapassato prossimo con avere – lui/lei",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-009", "u21-t2-005", "u21-t2-007"],
    },
    {
      id: "u21-t4-004",
      type: "passage_cloze",
      prompt: "Era una sera tranquilla quando Giulia decise di scrivere la fine del suo racconto.\nNel frattempo, il suo personaggio preferito aveva già perso tutto ciò che possedeva.\nDopo che la protagonista ___ dall'ultima città, non era rimasto più niente.\nPoi, inaspettatamente, un nuovo personaggio era apparso all'inizio del terzo capitolo.\nInfone, Giulia capì che la storia non era ancora finita.",
      accepted: ["era partita"],
      hint: "essere in imperfetto + participio di 'partire'; soggetto femminile",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-006", "u21-t1-008", "u21-t1-010", "u21-t2-006"],
    },
    {
      id: "u21-t4-005",
      type: "produce",
      prompt: "In the end, we had already seen the beginning and the end of the story before the event started.",
      accepted: [
        "Alla fine, avevamo già visto l'inizio e la fine della storia prima che l'evento cominciasse.",
        "Alla fine, avevamo già visto l'inizio e la fine del racconto prima che l'evento cominciasse.",
      ],
      hint: "trapassato + già; 'prima che' triggers congiuntivo",
      tags: ["trapassato-prossimo", "sentence", "sequencing", "congiuntivo"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-004", "u21-t1-005", "u21-t1-009", "u21-t1-011", "u21-t1-012", "u21-t2-004"],
    },
  ],
};
export default unit;
