import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-21-trapassato",
  name: "The Distant Past",
  level: "B1",
  theme: "Trapassato Prossimo",
  emoji: "📜",
  prerequisiteUnits: ["b1-unit-20-congiuntivo"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u21-t1-001",
      type: "recognize",
      prompt: "la storia",
      accepted: ["the story", "the history"],
      hint: "can mean both 'story' and 'history'",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-002",
      type: "produce",
      prompt: "the story (a narrative tale)",
      accepted: ["il racconto"],
      hint: "more specifically a short narrative",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-003",
      type: "produce",
      prompt: "the character (in a story)",
      accepted: ["il personaggio"],
      hint: "masculine even though it ends in -o; collocation: il personaggio principale",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-004",
      type: "produce",
      prompt: "the beginning",
      accepted: ["l'inizio"],
      hint: "masculine noun; collocation: all'inizio (at the beginning)",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-005",
      type: "produce",
      prompt: "the end",
      accepted: ["la fine"],
      hint: "feminine; contrast il fine (the goal or purpose) — same spelling, different gender and meaning",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-006",
      type: "recognize",
      prompt: "poi",
      accepted: ["then", "afterwards", "next"],
      hint: "pairs with prima in the fixed narrative structure prima... poi (first... then)",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-007",
      type: "recognize",
      prompt: "dopo",
      accepted: ["after", "afterwards", "later"],
      hint: "works alone as an adverb or with che (dopo che) as a conjunction — dopo che triggers the trapassato prossimo for the earlier action",
      tags: ["adverb", "preposition", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-008",
      type: "recognize",
      prompt: "infine",
      accepted: ["finally", "in the end", "at last"],
      hint: "one word, more literary register than alla fine — favored in written narration over speech",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-009",
      type: "recognize",
      prompt: "alla fine",
      accepted: ["in the end", "at the end", "finally"],
      hint: "fixed phrase with the article; more common in everyday speech than the one-word infine",
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-010",
      type: "recognize",
      prompt: "nel frattempo",
      accepted: ["meanwhile", "in the meantime"],
      hint: "opens a clause describing an action running parallel to the main storyline, not a step in the sequence",
      tags: ["phrase", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-011",
      type: "produce",
      prompt: "the event",
      accepted: ["l'evento"],
      hint: "masculine noun; more formal register than cosa — used for a significant or planned occurrence",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-012",
      type: "recognize",
      prompt: "già",
      accepted: ["already", "yet"],
      hint: "used to indicate something completed before another action",
      tags: ["adverb", "trapassato", "sequencing"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ────────────────────────────────────────────────────
    {
      id: "u21-t2-001",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – io",
      accepted: ["avevo mangiato"],
      hint: "auxiliary avere in the imperfetto + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-002",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (maschile)",
      accepted: ["ero andato"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-003",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – io (femminile)",
      accepted: ["ero andata"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-004",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – tu",
      accepted: ["avevi visto"],
      hint: "auxiliary avere in the imperfetto (avevi) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-005",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – lui/lei",
      accepted: ["aveva fatto"],
      hint: "auxiliary avere in the imperfetto (aveva) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-006",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – noi",
      accepted: ["eravamo partiti"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-007",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – lui/lei",
      accepted: ["aveva finito"],
      hint: "auxiliary avere in the imperfetto (aveva) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-008",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – loro",
      accepted: ["erano arrivati"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u21-t3-001",
      type: "produce",
      prompt: "He had already finished when she arrived.",
      accepted: ["Aveva già finito quando lei è arrivata.", "Aveva già finito quando è arrivata."],
      hint: "trapassato prossimo with avere for the earlier action (aveva finito), passato prossimo with essere for the later arrival (è arrivata)",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-002",
      type: "produce",
      prompt: "After we had left, it started to rain.",
      accepted: ["Dopo che eravamo partiti, ha cominciato a piovere.", "Dopo che eravamo partiti, è cominciato a piovere."],
      hint: "dopo che + trapassato prossimo with essere (eravamo partiti) for the earlier action, then passato prossimo for what followed",
      tags: ["trapassato-prossimo", "chunk", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-003",
      type: "produce",
      prompt: "I had never seen such a beautiful story.",
      accepted: ["Non avevo mai visto una storia così bella.", "Non avevo mai visto un racconto così bello."],
      hint: "non...mai wraps around the trapassato prossimo (non avevo mai visto) to say something had never happened before that point",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-004",
      type: "fill_blank",
      prompt: "As soon as the character ___ (arrivare, trapassato, lui) at the beginning, the story changed.",
      accepted: ["era arrivato"],
      hint: "appena triggers the trapassato prossimo; arrivare takes essere, so the participle agrees with the subject (arrivato/a)",
      tags: ["trapassato-prossimo", "fill-blank", "appena"],
      tier: 3,
    },
    {
      id: "u21-t3-005",
      type: "fill_blank",
      prompt: "Meanwhile, she had already read the end of the story: aveva già ___ la fine della storia.",
      accepted: ["letto"],
      hint: "leggere has the irregular past participle letto, used here with avere in the trapassato prossimo",
      tags: ["trapassato-prossimo", "fill-blank", "irregular-participle"],
      tier: 3,
    },
    {
      id: "u21-t3-006",
      type: "produce",
      prompt: "He had done everything before the event.",
      accepted: ["Aveva fatto tutto prima dell'evento.", "Aveva fatto tutto prima dell'evento."],
      hint: "trapassato prossimo of fare (aveva fatto) combined with prima di to mark what came before",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },

    // ── Tier 4 – Sentences & Passages ───────────────────────────────────────
    {
      id: "u21-t4-001",
      type: "produce",
      prompt: "When I arrived at the end of the story, I had already understood the character.",
      accepted: [
        "Quando sono arrivato alla fine della storia, avevo già capito il personaggio.",
        "Quando sono arrivata alla fine della storia, avevo già capito il personaggio.",
      ],
      hint: "passato prossimo for the arrival; trapassato for the earlier understanding",
      tags: ["trapassato-prossimo", "sentence", "sequencing"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-003", "u21-t1-005", "u21-t1-012", "u21-t2-001"],
      deprecated: true,
    },
    {
      id: "u21-t4-002",
      type: "fill_blank",
      prompt: "Dopo che il personaggio ___ (partire, trapassato, lui) dalla città, la storia è diventata più interessante.",
      accepted: ["era partito"],
      hint: "trapassato prossimo with essere; partire is a motion verb, so the participle agrees with il personaggio (masculine)",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 4,
      prerequisites: ["u21-t1-003", "u21-t1-007", "u21-t2-006"],
      deprecated: true,
    },
    {
      id: "u21-t4-003",
      type: "passage_cloze",
      prompt: "Marco aprì il libro e cominciò a leggere il racconto dall'inizio.\nIl personaggio principale era un giovane che non aveva mai viaggiato lontano dalla sua città.\nMa quella mattina tutto era cambiato: qualcuno gli aveva dato una mappa misteriosa.\nMarco si rese conto che il personaggio ___ già la risposta, ma non lo sapeva ancora.\nAlla fine del primo capitolo, la storia era diventata impossibile da lasciare.",
      accepted: ["aveva trovato", "aveva capito"],
      hint: "trapassato prossimo with avere – lui/lei; both trovare and capire are regular verbs in this pattern",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-009", "u21-t2-005", "u21-t2-007"],
    },
    {
      id: "u21-t4-004",
      type: "passage_cloze",
      prompt: "Era una sera tranquilla quando Giulia decise di scrivere la fine del suo racconto.\nNel frattempo, il suo personaggio preferito aveva già perso tutto ciò che possedeva.\nDopo che la protagonista ___ dall'ultima città, non era rimasto più niente.\nPoi, inaspettatamente, un nuovo personaggio era apparso all'inizio del terzo capitolo.\nInfone, Giulia capì che la storia non era ancora finita.",
      accepted: ["era partita"],
      hint: "trapassato prossimo with essere; partire agrees with the feminine subject la protagonista, giving partita",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-003", "u21-t1-004", "u21-t1-006", "u21-t1-008", "u21-t1-010", "u21-t2-006"],
    },
    {
      id: "u21-t4-005",
      type: "produce",
      prompt: "In the end, we had already seen the beginning and the end of the story before the event started.",
      accepted: [
        "Alla fine, avevamo già visto l'inizio e la fine della storia prima che l'evento cominciasse.",
        "Alla fine, avevamo già visto l'inizio e la fine del racconto prima che l'evento cominciasse.",
      ],
      hint: "trapassato + già; 'prima che' triggers congiuntivo",
      tags: ["trapassato-prossimo", "sentence", "sequencing", "congiuntivo"],
      tier: 4,
      prerequisites: ["u21-t1-001", "u21-t1-004", "u21-t1-005", "u21-t1-009", "u21-t1-011", "u21-t1-012", "u21-t2-004"],
      deprecated: true,
    },

    // ── Tier 1 additions – narrative & sequencing vocabulary (2026-08-01 expansion) ──
    {
      id: "u21-t1-013",
      type: "recognize",
      prompt: "non appena",
      accepted: ["as soon as"],
      hint: "used right before trapassato prossimo to mark an action just completed",
      tags: ["conjunction", "trapassato", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-014",
      type: "recognize",
      prompt: "mai",
      accepted: ["never", "ever"],
      hint: "used with non...mai to mean 'never'",
      tags: ["adverb", "trapassato", "negation"],
      tier: 1,
    },
    {
      id: "u21-t1-015",
      type: "recognize",
      prompt: "ancora",
      accepted: ["still", "yet"],
      hint: "non...ancora = not yet",
      tags: ["adverb", "trapassato", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-016",
      type: "produce",
      prompt: "the chapter",
      accepted: ["il capitolo"],
      hint: "used to divide a racconto or romanzo",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-017",
      type: "produce",
      prompt: "the plot",
      accepted: ["la trama"],
      hint: "the sequence of events in a story",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-018",
      type: "produce",
      prompt: "the writer",
      accepted: ["lo scrittore", "la scrittrice"],
      hint: "masculine/feminine forms, from scrivere",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-019",
      type: "produce",
      prompt: "the narrator",
      accepted: ["il narratore", "la narratrice"],
      hint: "the voice telling la storia",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-020",
      type: "recognize",
      prompt: "accadere",
      accepted: ["to happen", "to occur"],
      hint: "impersonal verb, takes essere: è accaduto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-021",
      type: "recognize",
      prompt: "succedere",
      accepted: ["to happen"],
      hint: "impersonal verb, takes essere: è successo",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-022",
      type: "recognize",
      prompt: "ricordare",
      accepted: ["to remember"],
      hint: "regular -are verb, takes avere",
      tags: ["verb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-023",
      type: "produce",
      prompt: "to forget",
      accepted: ["dimenticare"],
      hint: "regular -are verb, takes avere",
      tags: ["verb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-024",
      type: "recognize",
      prompt: "rendersi conto",
      accepted: ["to realize"],
      hint: "reflexive; trapassato: mi ero reso conto",
      tags: ["verb", "narrative", "vocabulary", "reflexive"],
      tier: 1,
    },
    {
      id: "u21-t1-025",
      type: "produce",
      prompt: "to discover",
      accepted: ["scoprire"],
      hint: "irregular past participle: scoperto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-026",
      type: "produce",
      prompt: "the discovery",
      accepted: ["la scoperta"],
      hint: "noun from scoprire",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-027",
      type: "recognize",
      prompt: "improvvisamente",
      accepted: ["suddenly"],
      hint: "marks an unexpected event breaking the narrative flow",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-028",
      type: "recognize",
      prompt: "finalmente",
      accepted: ["finally", "at last"],
      hint: "different from alla fine — marks relief, not just sequence",
      tags: ["adverb", "narrative", "sequencing"],
      tier: 1,
    },
    {
      id: "u21-t1-029",
      type: "recognize",
      prompt: "purtroppo",
      accepted: ["unfortunately"],
      hint: "introduces an unwelcome outcome",
      tags: ["adverb", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-030",
      type: "produce",
      prompt: "the surprise",
      accepted: ["la sorpresa"],
      hint: "from sorprendere",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-031",
      type: "produce",
      prompt: "the secret",
      accepted: ["il segreto"],
      hint: "collocation: nascondere un segreto",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-032",
      type: "recognize",
      prompt: "nascondere",
      accepted: ["to hide"],
      hint: "irregular past participle: nascosto",
      tags: ["verb", "narrative", "vocabulary", "irregular"],
      tier: 1,
    },
    {
      id: "u21-t1-033",
      type: "produce",
      prompt: "the past",
      accepted: ["il passato"],
      hint: "collocation: nel passato (in the past); also the grammar term for past tenses, i tempi del passato",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },
    {
      id: "u21-t1-034",
      type: "produce",
      prompt: "the scene",
      accepted: ["la scena"],
      hint: "a specific moment within a story",
      tags: ["noun", "narrative", "vocabulary"],
      tier: 1,
    },

    // ── Tier 2 additions – expanded conjugation drills (2026-08-01 expansion) ──
    {
      id: "u21-t2-009",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – tu",
      accepted: ["avevi mangiato"],
      hint: "auxiliary avere in the imperfetto (avevi) + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-010",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – lui/lei",
      accepted: ["aveva mangiato"],
      hint: "auxiliary avere in the imperfetto (aveva) + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-011",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – noi",
      accepted: ["avevamo mangiato"],
      hint: "auxiliary avere in the imperfetto (avevamo) + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-012",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – voi",
      accepted: ["avevate mangiato"],
      hint: "auxiliary avere in the imperfetto (avevate) + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-013",
      type: "conjugate",
      prompt: "mangiare (trapassato prossimo) – loro",
      accepted: ["avevano mangiato"],
      hint: "auxiliary avere in the imperfetto (avevano) + past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-014",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – io",
      accepted: ["avevo visto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-015",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – lui/lei",
      accepted: ["aveva visto"],
      hint: "auxiliary avere in the imperfetto (aveva) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-016",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – noi",
      accepted: ["avevamo visto"],
      hint: "auxiliary avere in the imperfetto (avevamo) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-017",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – voi",
      accepted: ["avevate visto"],
      hint: "auxiliary avere in the imperfetto (avevate) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-018",
      type: "conjugate",
      prompt: "vedere (trapassato prossimo) – loro",
      accepted: ["avevano visto"],
      hint: "auxiliary avere in the imperfetto (avevano) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-019",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – io",
      accepted: ["avevo fatto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-020",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – tu",
      accepted: ["avevi fatto"],
      hint: "auxiliary avere in the imperfetto (avevi) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-021",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – noi",
      accepted: ["avevamo fatto"],
      hint: "auxiliary avere in the imperfetto (avevamo) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-022",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – voi",
      accepted: ["avevate fatto"],
      hint: "auxiliary avere in the imperfetto (avevate) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-023",
      type: "conjugate",
      prompt: "fare (trapassato prossimo) – loro",
      accepted: ["avevano fatto"],
      hint: "auxiliary avere in the imperfetto (avevano) + irregular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-024",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – io",
      accepted: ["avevo finito"],
      hint: "auxiliary avere in the imperfetto (avevo) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-025",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – tu",
      accepted: ["avevi finito"],
      hint: "auxiliary avere in the imperfetto (avevi) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-026",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – noi",
      accepted: ["avevamo finito"],
      hint: "auxiliary avere in the imperfetto (avevamo) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-027",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – voi",
      accepted: ["avevate finito"],
      hint: "auxiliary avere in the imperfetto (avevate) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-028",
      type: "conjugate",
      prompt: "finire (trapassato prossimo) – loro",
      accepted: ["avevano finito"],
      hint: "auxiliary avere in the imperfetto (avevano) + regular past participle",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-029",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – tu (maschile)",
      accepted: ["eri andato"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-030",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – tu (femminile)",
      accepted: ["eri andata"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-031",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – lui",
      accepted: ["era andato"],
      hint: "auxiliary essere in the imperfetto + past participle",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-032",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – lei",
      accepted: ["era andata"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-033",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo andati"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-034",
      type: "conjugate",
      prompt: "andare (trapassato prossimo) – loro (maschile)",
      accepted: ["erano andati"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-035",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – io (maschile)",
      accepted: ["ero partito"],
      hint: "auxiliary essere in the imperfetto + past participle",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-036",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – io (femminile)",
      accepted: ["ero partita"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-037",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – lui",
      accepted: ["era partito"],
      hint: "auxiliary essere in the imperfetto + past participle",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-038",
      type: "conjugate",
      prompt: "partire (trapassato prossimo) – voi (maschile)",
      accepted: ["eravate partiti"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-039",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – io (maschile)",
      accepted: ["ero arrivato"],
      hint: "auxiliary essere in the imperfetto + past participle",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-040",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – tu (femminile)",
      accepted: ["eri arrivata"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-041",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – lei",
      accepted: ["era arrivata"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing feminine with the subject",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-042",
      type: "conjugate",
      prompt: "arrivare (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo arrivati"],
      hint: "auxiliary essere in the imperfetto + past participle, agreeing masculine plural",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-043",
      type: "conjugate",
      prompt: "scrivere (trapassato prossimo) – io",
      accepted: ["avevo scritto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle: scritto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-044",
      type: "conjugate",
      prompt: "dire (trapassato prossimo) – lui/lei",
      accepted: ["aveva detto"],
      hint: "auxiliary avere in the imperfetto (aveva) + irregular past participle: detto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-045",
      type: "conjugate",
      prompt: "leggere (trapassato prossimo) – noi",
      accepted: ["avevamo letto"],
      hint: "auxiliary avere in the imperfetto (avevamo) + irregular past participle: letto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-046",
      type: "conjugate",
      prompt: "prendere (trapassato prossimo) – loro",
      accepted: ["avevano preso"],
      hint: "auxiliary avere in the imperfetto (avevano) + irregular past participle: preso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-047",
      type: "conjugate",
      prompt: "mettere (trapassato prossimo) – tu",
      accepted: ["avevi messo"],
      hint: "auxiliary avere in the imperfetto (avevi) + irregular past participle: messo",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-048",
      type: "conjugate",
      prompt: "aprire (trapassato prossimo) – io",
      accepted: ["avevo aperto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle: aperto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-049",
      type: "conjugate",
      prompt: "chiudere (trapassato prossimo) – lei",
      accepted: ["aveva chiuso"],
      hint: "auxiliary avere in the imperfetto (aveva) + irregular past participle: chiuso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-050",
      type: "conjugate",
      prompt: "decidere (trapassato prossimo) – loro",
      accepted: ["avevano deciso"],
      hint: "auxiliary avere in the imperfetto (avevano) + irregular past participle: deciso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-051",
      type: "conjugate",
      prompt: "rompere (trapassato prossimo) – io",
      accepted: ["avevo rotto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle: rotto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-052",
      type: "conjugate",
      prompt: "perdere (trapassato prossimo) – tu",
      accepted: ["avevi perso"],
      hint: "auxiliary avere in the imperfetto (avevi) + irregular past participle: perso",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-053",
      type: "conjugate",
      prompt: "rispondere (trapassato prossimo) – lui",
      accepted: ["aveva risposto"],
      hint: "auxiliary avere in the imperfetto (aveva) + irregular past participle: risposto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-054",
      type: "conjugate",
      prompt: "chiedere (trapassato prossimo) – noi",
      accepted: ["avevamo chiesto"],
      hint: "auxiliary avere in the imperfetto (avevamo) + irregular past participle: chiesto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-055",
      type: "conjugate",
      prompt: "offrire (trapassato prossimo) – voi",
      accepted: ["avevate offerto"],
      hint: "auxiliary avere in the imperfetto (avevate) + irregular past participle: offerto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-056",
      type: "conjugate",
      prompt: "nascondere (trapassato prossimo) – loro",
      accepted: ["avevano nascosto"],
      hint: "auxiliary avere in the imperfetto (avevano) + irregular past participle: nascosto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-057",
      type: "conjugate",
      prompt: "scoprire (trapassato prossimo) – io",
      accepted: ["avevo scoperto"],
      hint: "auxiliary avere in the imperfetto (avevo) + irregular past participle: scoperto",
      tags: ["trapassato-prossimo", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-058",
      type: "conjugate",
      prompt: "nascere (trapassato prossimo) – lui",
      accepted: ["era nato"],
      hint: "auxiliary essere in the imperfetto (era) + irregular past participle: nato",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-059",
      type: "conjugate",
      prompt: "morire (trapassato prossimo) – lei",
      accepted: ["era morta"],
      hint: "auxiliary essere in the imperfetto (era) + irregular past participle, agreeing: morta",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-060",
      type: "conjugate",
      prompt: "venire (trapassato prossimo) – io (maschile)",
      accepted: ["ero venuto"],
      hint: "auxiliary essere in the imperfetto (ero) + irregular past participle: venuto",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-061",
      type: "conjugate",
      prompt: "rimanere (trapassato prossimo) – noi (maschile)",
      accepted: ["eravamo rimasti"],
      hint: "auxiliary essere in the imperfetto (eravamo) + irregular past participle: rimasti",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-062",
      type: "conjugate",
      prompt: "scendere (trapassato prossimo) – tu (femminile)",
      accepted: ["eri scesa"],
      hint: "auxiliary essere in the imperfetto (eri) + irregular past participle, agreeing: scesa",
      tags: ["trapassato-prossimo", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u21-t2-063",
      type: "conjugate",
      prompt: "diventare (trapassato prossimo) – loro (maschile)",
      accepted: ["erano diventati"],
      hint: "auxiliary essere in the imperfetto (erano) + regular past participle: diventati",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-064",
      type: "conjugate",
      prompt: "tornare (trapassato prossimo) – voi (femminile)",
      accepted: ["eravate tornate"],
      hint: "auxiliary essere in the imperfetto (eravate) + regular past participle, agreeing: tornate",
      tags: ["trapassato-prossimo", "essere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-065",
      type: "conjugate",
      prompt: "ricordare (trapassato prossimo) – io",
      accepted: ["avevo ricordato"],
      hint: "auxiliary avere in the imperfetto (avevo) + regular past participle: ricordato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },
    {
      id: "u21-t2-066",
      type: "conjugate",
      prompt: "dimenticare (trapassato prossimo) – lei",
      accepted: ["aveva dimenticato"],
      hint: "auxiliary avere in the imperfetto (aveva) + regular past participle: dimenticato",
      tags: ["trapassato-prossimo", "avere", "conjugation"],
      tier: 2,
    },

    // ── Tier 3 additions – deeper chunks & phrases (2026-08-01 expansion) ──
    {
      id: "u21-t3-007",
      type: "produce",
      prompt: "By the time the narrator arrived, the writer had already left.",
      accepted: ["Quando il narratore è arrivato, lo scrittore era già partito.", "Quando il narratore è arrivato, la scrittrice era già partita."],
      hint: "trapassato prossimo for the earlier departure (era partito); partire takes essere",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-008",
      type: "fill_blank",
      prompt: "Non appena Marco ___ (scoprire, trapassato, lui) il segreto, ha capito tutta la trama.",
      accepted: ["aveva scoperto"],
      hint: "non appena + trapassato prossimo with avere; scoprire has the irregular participle scoperto",
      tags: ["trapassato-prossimo", "fill-blank", "non-appena"],
      tier: 3,
    },
    {
      id: "u21-t3-009",
      type: "produce",
      prompt: "She had never read that chapter before.",
      accepted: ["Non aveva mai letto quel capitolo prima.", "Non aveva mai letto quel capitolo prima d'ora."],
      hint: "non...mai + trapassato prossimo; leggere has the irregular participle letto",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-010",
      type: "fill_blank",
      prompt: "Dopo mesi di dubbi, Paolo e Chiara ___ (decidere, trapassato, loro) già di cambiare vita prima di conoscere quella storia.",
      accepted: ["avevano deciso"],
      hint: "trapassato prossimo with avere, plural; decidere has the irregular participle deciso",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-011",
      type: "produce",
      prompt: "We had already forgotten the beginning of the plot.",
      accepted: ["Avevamo già dimenticato l'inizio della trama."],
      hint: "trapassato prossimo of dimenticare (regular -are verb) with già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-012",
      type: "fill_blank",
      prompt: "Quando è arrivata la sorpresa, il personaggio ___ (capire, trapassato, lui) già tutto.",
      accepted: ["aveva capito"],
      hint: "quando + passato prossimo marks the later event; trapassato prossimo (aveva capito) marks what came before it",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-013",
      type: "produce",
      prompt: "He had hidden the secret before the writer's discovery.",
      accepted: ["Aveva nascosto il segreto prima della scoperta dello scrittore."],
      hint: "trapassato prossimo of nascondere (irregular participle nascosto) with prima di + noun",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-014",
      type: "fill_blank",
      prompt: "Purtroppo, quando siamo arrivati, il narratore ___ (andare, trapassato, lui) via.",
      accepted: ["era andato"],
      hint: "essere in the imperfetto + past participle; purtroppo signals an unwelcome outcome",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-015",
      type: "produce",
      prompt: "By the time she realized the truth, the story had already changed.",
      accepted: ["Quando si è resa conto della verità, la storia era già cambiata."],
      hint: "passato prossimo for the realization, trapassato prossimo (era già cambiata) for the earlier change; cambiare takes essere here because the subject is la storia",
      tags: ["trapassato-prossimo", "chunk", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-016",
      type: "fill_blank",
      prompt: "Il personaggio si ___ (rendersi conto, trapassato, lui) del segreto solo alla fine.",
      accepted: ["era reso conto"],
      hint: "rendersi conto is reflexive: conjugated with essere + reso/a conto",
      tags: ["trapassato-prossimo", "fill-blank", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-017",
      type: "produce",
      prompt: "The scene had already happened before the beginning of the chapter.",
      accepted: ["La scena era già accaduta prima dell'inizio del capitolo."],
      hint: "accadere is impersonal and takes essere; the participle agrees with la scena (feminine)",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-018",
      type: "fill_blank",
      prompt: "Non capivo cosa ___ (succedere, trapassato, esso) la sera prima.",
      accepted: ["era successo"],
      hint: "succedere takes essere: era successo",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-019",
      type: "produce",
      prompt: "Finally, the writer understood what had happened.",
      accepted: ["Finalmente lo scrittore ha capito cosa era successo."],
      hint: "finalmente + passato prossimo for the realization, trapassato prossimo in the subordinate clause (era successo) for what had already happened",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-020",
      type: "fill_blank",
      prompt: "Dopo che il narratore ___ (finire, trapassato, lui) il racconto, tutti hanno applaudito.",
      accepted: ["aveva finito"],
      hint: "dopo che + trapassato prossimo for the earlier action, then passato prossimo for what followed",
      tags: ["trapassato-prossimo", "fill-blank", "dopo-che"],
      tier: 3,
    },
    {
      id: "u21-t3-021",
      type: "produce",
      prompt: "I had already opened the book when the surprise happened.",
      accepted: ["Avevo già aperto il libro quando è successa la sorpresa."],
      hint: "trapassato prossimo of aprire (avevo aperto) with già; quando introduces the later passato prossimo event",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-022",
      type: "fill_blank",
      prompt: "La sorpresa ___ (accadere, trapassato, essa) improvvisamente, senza nessun segno prima.",
      accepted: ["era accaduta"],
      hint: "accadere takes essere; the participle agrees with la sorpresa (feminine)",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-023",
      type: "produce",
      prompt: "They had written three chapters before the surprise ending.",
      accepted: ["Avevano scritto tre capitoli prima del finale a sorpresa."],
      hint: "trapassato prossimo of scrivere (irregular participle scritto) with prima di",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-024",
      type: "fill_blank",
      prompt: "Non appena ho letto la trama, ho capito che l'autore ___ (nascondere, trapassato, lui) un segreto.",
      accepted: ["aveva nascosto"],
      hint: "trapassato prossimo with avere; nascondere has the irregular participle nascosto",
      tags: ["trapassato-prossimo", "fill-blank", "non-appena"],
      tier: 3,
    },
    {
      id: "u21-t3-025",
      type: "produce",
      prompt: "She had lost the notebook before writing the last chapter.",
      accepted: ["Aveva perso il quaderno prima di scrivere l'ultimo capitolo."],
      hint: "trapassato prossimo of perdere (irregular participle perso) with prima di + infinitive",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-026",
      type: "fill_blank",
      prompt: "Quando il libro è finito, io ___ (dimenticare, trapassato, io) già il nome del narratore.",
      accepted: ["avevo dimenticato"],
      hint: "trapassato prossimo with avere; dimenticare is a regular -are verb",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-027",
      type: "produce",
      prompt: "In the end, we had already read the whole plot twice.",
      accepted: ["Alla fine, avevamo già letto tutta la trama due volte."],
      hint: "trapassato prossimo of leggere (irregular participle letto) with già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-028",
      type: "fill_blank",
      prompt: "Il segreto ___ (rimanere, trapassato, lui) nascosto per molti anni.",
      accepted: ["era rimasto"],
      hint: "rimanere takes essere: era rimasto",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-029",
      type: "fill_blank",
      prompt: "Nel passato, quella grande scoperta ___ (cambiare, trapassato, essa) già tutta la trama del racconto.",
      accepted: ["aveva cambiato"],
      hint: "trapassato with avere; the participle stays invariable (aveva cambiato) — no gender agreement with avere, unlike essere",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-030",
      type: "produce",
      prompt: "Unfortunately, the writer had already died before finishing the last chapter.",
      accepted: ["Purtroppo lo scrittore era già morto prima di finire l'ultimo capitolo."],
      hint: "morire takes essere: era morto",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-031",
      type: "produce",
      prompt: "The narrator had never said such an important secret before.",
      accepted: ["Il narratore non aveva mai detto un segreto così importante."],
      hint: "non...mai + trapassato prossimo; dire has the irregular participle detto",
      tags: ["trapassato-prossimo", "chunk", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-032",
      type: "fill_blank",
      prompt: "Ancora non ___ (capire, trapassato, noi) la trama, quando è arrivata la sorpresa finale.",
      accepted: ["avevamo capito"],
      hint: "ancora non + trapassato prossimo, marking something still not accomplished when the later event arrived",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-033",
      type: "produce",
      prompt: "He had already become a famous writer before that book.",
      accepted: ["Era già diventato uno scrittore famoso prima di quel libro."],
      hint: "trapassato prossimo of diventare (takes essere) with già",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-034",
      type: "fill_blank",
      prompt: "Quando sono tornato al capitolo precedente, mi sono reso conto che ___ (perdere, trapassato, io) un dettaglio importante.",
      accepted: ["avevo perso"],
      hint: "trapassato prossimo with avere; perdere has the irregular participle perso",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-035",
      type: "produce",
      prompt: "By the time she came back, everyone had already left the scene.",
      accepted: ["Quando è tornata, tutti erano già andati via dalla scena."],
      hint: "quando + passato prossimo for the later event, trapassato prossimo (erano già andati) for what had already happened",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-036",
      type: "fill_blank",
      prompt: "Il narratore ha spiegato tutto quello che ___ (accadere, trapassato, esso) nel passato.",
      accepted: ["era accaduto"],
      hint: "accadere is impersonal, always third person, and takes essere",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-037",
      type: "produce",
      prompt: "Unfortunately, they had already forgotten the secret before the end.",
      accepted: ["Purtroppo avevano già dimenticato il segreto prima della fine."],
      hint: "purtroppo signals an unwelcome outcome; trapassato prossimo of dimenticare with già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-038",
      type: "fill_blank",
      prompt: "Il personaggio principale ___ (nascere, trapassato, lui) molto tempo prima degli eventi del racconto.",
      accepted: ["era nato"],
      hint: "nascere takes essere: era nato",
      tags: ["trapassato-prossimo", "fill-blank", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-039",
      type: "produce",
      prompt: "As soon as I had remembered the scene, I understood the whole secret.",
      accepted: ["Non appena mi ero ricordato della scena, ho capito tutto il segreto."],
      hint: "non appena + reflexive trapassato prossimo with essere (mi ero ricordato)",
      tags: ["trapassato-prossimo", "chunk", "non-appena", "reflexive"],
      tier: 3,
    },
    {
      id: "u21-t3-040",
      type: "fill_blank",
      prompt: "Prima di quella sera, il narratore non ___ (dire, trapassato, lui) mai il segreto a nessuno.",
      accepted: ["aveva detto"],
      hint: "non...mai + trapassato prossimo; dire has the irregular participle detto",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },
    {
      id: "u21-t3-041",
      type: "produce",
      prompt: "The scene had already ended when the surprise arrived.",
      accepted: ["La scena era già finita quando è arrivata la sorpresa."],
      hint: "intransitive finire takes essere when the subject is the thing that ends, contrast the transitive use with avere (ho finito il libro)",
      tags: ["trapassato-prossimo", "chunk", "essere"],
      tier: 3,
    },
    {
      id: "u21-t3-042",
      type: "fill_blank",
      prompt: "Il lettore si è chiesto se il narratore ___ (dire, trapassato, lui) tutta la verità.",
      accepted: ["aveva detto"],
      hint: "se introducing an indirect question here, not a hypothetical; trapassato prossimo (aveva detto) is common in informal speech in this construction",
      tags: ["trapassato-prossimo", "fill-blank", "dubbio"],
      tier: 3,
    },
    {
      id: "u21-t3-043",
      type: "produce",
      prompt: "We had already discussed the plot before reading the last chapter.",
      accepted: ["Avevamo già discusso la trama prima di leggere l'ultimo capitolo."],
      hint: "trapassato prossimo of discutere with già, followed by prima di + infinitive",
      tags: ["trapassato-prossimo", "chunk", "prima-di"],
      tier: 3,
    },
    {
      id: "u21-t3-044",
      type: "fill_blank",
      prompt: "Quando il narratore ha chiuso il libro, il lettore ___ (capire, trapassato, lui) finalmente tutta la trama.",
      accepted: ["aveva capito"],
      hint: "quando + passato prossimo marks the later event; trapassato prossimo (aveva capito) marks the earlier understanding",
      tags: ["trapassato-prossimo", "fill-blank", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-045",
      type: "produce",
      prompt: "By the time the writer revealed the ending, we had already guessed the secret.",
      accepted: ["Quando lo scrittore ha rivelato il finale, avevamo già indovinato il segreto."],
      hint: "trapassato prossimo of indovinare with già",
      tags: ["trapassato-prossimo", "chunk", "sequencing"],
      tier: 3,
    },
    {
      id: "u21-t3-046",
      type: "fill_blank",
      prompt: "Prima di quel capitolo, il personaggio non ___ (scendere, trapassato, lui) mai in quella scena.",
      accepted: ["era sceso"],
      hint: "scendere takes essere: era sceso",
      tags: ["trapassato-prossimo", "fill-blank", "negation"],
      tier: 3,
    },

    // ── Tier 4 additions – narrative passage_cloze mini-stories (2026-08-01 expansion) ──
    {
      id: "u21-t4-006",
      type: "passage_cloze",
      prompt: "Elena aprì il suo quaderno e cominciò a leggere il primo capitolo del racconto.\nIl narratore raccontava di uno scrittore che, molti anni prima, ___ una storia simile.\nNessuno nella scena ricordava il suo nome, ma la trama era rimasta famosa.\nElena capì che quel vecchio segreto era ancora nascosto tra le pagine.\nAlla fine del capitolo, la sorpresa cambiò tutta la sua idea sul narratore.",
      accepted: ["aveva già scritto"],
      hint: "trapassato prossimo with avere – lui/lei; scrivere has the irregular participle scritto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-016", "u21-t1-018", "u21-t1-019", "u21-t1-030", "u21-t1-031", "u21-t2-043"],
    },
    {
      id: "u21-t4-007",
      type: "passage_cloze",
      prompt: "Giulia trovò un vecchio libro in soffitta e ne cominciò a leggere le prime pagine.\nScoprì che sua nonna, da giovane, ___ quel racconto molte volte.\nIl narratore della storia sembrava conoscere ogni personaggio della sua famiglia.\nNon appena Giulia capì la trama, si rese conto che il segreto era proprio lì.\nFinalmente aveva trovato la risposta che cercava da tempo.",
      accepted: ["aveva già letto"],
      hint: "trapassato prossimo with avere – lei; leggere has the irregular participle letto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-002", "u21-t1-003", "u21-t1-013", "u21-t1-017", "u21-t1-019", "u21-t1-028", "u21-t1-031", "u21-t2-045"],
    },
    {
      id: "u21-t4-008",
      type: "passage_cloze",
      prompt: "Marco si svegliò tardi e corse subito in ufficio.\nQuando è arrivato, ha scoperto che il suo collega ___ la porta dell'archivio.\nDentro, c'era una scena che nessuno si aspettava: vecchi documenti sparsi ovunque.\nPurtroppo, quel segreto era rimasto nascosto per anni.\nMarco capì che quella scoperta avrebbe cambiato tutto il progetto.",
      accepted: ["aveva già aperto"],
      hint: "trapassato prossimo with avere – lui; aprire has the irregular participle aperto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-029", "u21-t1-031", "u21-t1-034", "u21-t1-026", "u21-t2-048"],
    },
    {
      id: "u21-t4-009",
      type: "passage_cloze",
      prompt: "Era una sera d'inverno quando Sofia entrò nella vecchia libreria.\nIl proprietario le disse che, poco prima, ___ il negozio per la notte.\nSofia rimase sorpresa: non aveva mai visto quella scena così silenziosa.\nNel passato, quel posto era sempre stato pieno di gente.\nAlla fine, Sofia decise di tornare il giorno dopo per scoprire di più.",
      accepted: ["aveva già chiuso"],
      hint: "trapassato prossimo with avere – lui; chiudere has the irregular participle chiuso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-014", "u21-t1-033", "u21-t1-034", "u21-t1-025", "u21-t2-049"],
    },
    {
      id: "u21-t4-010",
      type: "passage_cloze",
      prompt: "Dopo mesi di dubbi, una giovane coppia decise di raccontare la propria esperienza a un giornale locale.\nIl giornalista scoprì che, prima ancora di quella decisione, i due ___ di lasciare il lavoro in città.\nIl narratore dell'articolo spiegò che questa scelta aveva cambiato completamente la trama della loro vita.\nNessuno immaginava che un evento così piccolo potesse portare tanto coraggio.\nAlla fine, la loro storia diventò un esempio per molte altre famiglie.",
      accepted: ["avevano già deciso"],
      hint: "trapassato prossimo with avere – loro; decidere has the irregular participle deciso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-017", "u21-t1-011", "u21-t2-050"],
    },
    {
      id: "u21-t4-011",
      type: "passage_cloze",
      prompt: "Quella mattina, Luca trovò la sua vecchia macchina fotografica sul tavolo.\nSua sorella gli confessò che, per errore, ___ l'obiettivo qualche giorno prima.\nLuca non si arrabbiò: capì che era stato solo un incidente.\nNel frattempo, ricordò un'altra scena simile accaduta anni prima.\nFinalmente decisero di comprarne una nuova insieme.",
      accepted: ["aveva già rotto"],
      hint: "trapassato prossimo with avere – lei; rompere has the irregular participle rotto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-010", "u21-t1-028", "u21-t1-034", "u21-t2-051"],
    },
    {
      id: "u21-t4-012",
      type: "passage_cloze",
      prompt: "Anna cercava disperatamente le chiavi di casa.\nSi rese conto che, senza accorgersene, ___ il portafoglio con dentro anche i documenti.\nIl narratore della vicenda avrebbe potuto aggiungere questo dettaglio alla trama del suo prossimo racconto.\nPer fortuna, un vicino trovò tutto vicino alla scena dell'incidente.\nAlla fine, Anna promise di stare più attenta in futuro.",
      accepted: ["aveva già perso"],
      hint: "trapassato prossimo with avere – lei; perdere has the irregular participle perso",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-024", "u21-t1-019", "u21-t1-017", "u21-t1-002", "u21-t1-034", "u21-t2-052"],
    },
    {
      id: "u21-t4-013",
      type: "passage_cloze",
      prompt: "Durante l'intervista, il famoso scrittore raccontò un aneddoto curioso.\nDisse che, molti anni prima, un giornalista gli aveva fatto una domanda difficile e lui non ___ subito.\nSolo dopo giorni di riflessione, aveva trovato la risposta giusta.\nQuella storia divenne parte del suo prossimo capitolo.\nIl pubblico rimase sorpreso da tanta sincerità.",
      accepted: ["aveva risposto"],
      hint: "trapassato prossimo with avere – lui; rispondere has the irregular participle risposto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-016", "u21-t1-030", "u21-t2-053"],
    },
    {
      id: "u21-t4-014",
      type: "passage_cloze",
      prompt: "Davide raccontò alla sua amica un vecchio ricordo di famiglia.\nSuo nonno, da ragazzo, ___ il permesso di partire per l'America prima ancora di finire la scuola.\nNessuno nella famiglia conosceva questo segreto fino a quel momento.\nLa scoperta cambiò completamente la trama della loro storia familiare.\nFinalmente, tutti capirono da dove veniva quel coraggio.",
      accepted: ["aveva già chiesto"],
      hint: "trapassato prossimo with avere – lui; chiedere has the irregular participle chiesto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-028", "u21-t2-054"],
    },
    {
      id: "u21-t4-015",
      type: "passage_cloze",
      prompt: "Quando Marta arrivò alla festa, era già tardi.\nL'organizzatore le spiegò che un altro ospite ___ il suo aiuto per preparare tutto.\nMarta si sentì sollevata: non doveva più preoccuparsi di niente.\nQuella sera, la scena sembrava uscita da un vecchio racconto.\nAlla fine, tutti ricordarono quella serata come una piacevole sorpresa.",
      accepted: ["aveva già offerto"],
      hint: "trapassato prossimo with avere – lui; offrire has the irregular participle offerto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-034", "u21-t1-002", "u21-t1-030", "u21-t1-022"],
    },
    {
      id: "u21-t4-016",
      type: "passage_cloze",
      prompt: "Il detective aprì il vecchio baule trovato in soffitta.\nCapì subito che qualcuno ___ delle lettere importanti sotto i vestiti.\nQuel segreto era rimasto nascosto per più di trent'anni.\nLa scoperta cambiò completamente la trama dell'indagine.\nFinalmente, il narratore della storia poteva scrivere l'ultimo capitolo.",
      accepted: ["aveva già nascosto"],
      hint: "trapassato prossimo with avere – impersonal qualcuno takes third-person singular; nascondere has the irregular participle nascosto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-028", "u21-t1-019", "u21-t1-016", "u21-t2-056"],
    },
    {
      id: "u21-t4-017",
      type: "passage_cloze",
      prompt: "Dopo settimane di ricerche, Elena tornò in biblioteca.\nIl bibliotecario le disse che un altro studioso ___ lo stesso documento anni prima.\nElena rimase sorpresa: nessuno aveva mai scoperto quel segreto prima.\nPurtroppo, la sua scoperta non era più una novità.\nAlla fine, decise comunque di scrivere il suo capitolo sull'argomento.",
      accepted: ["aveva già scoperto"],
      hint: "trapassato prossimo with avere – lui; scoprire has the irregular participle scoperto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-029", "u21-t1-016", "u21-t2-057"],
    },
    {
      id: "u21-t4-018",
      type: "passage_cloze",
      prompt: "Nel primo capitolo del romanzo, il narratore racconta la storia del protagonista.\nIl personaggio principale ___ molto tempo prima degli eventi narrati nella trama.\nNessuno conosceva il suo passato fino a quella sorpresa finale.\nIl segreto della sua nascita cambiò completamente la storia.\nFinalmente il lettore capì perché il narratore aveva aspettato tanto per rivelarlo.",
      accepted: ["era nato"],
      hint: "trapassato prossimo with essere – nascere always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-016", "u21-t1-019", "u21-t1-017", "u21-t1-033", "u21-t1-030", "u21-t1-031", "u21-t1-028", "u21-t2-058"],
    },
    {
      id: "u21-t4-019",
      type: "passage_cloze",
      prompt: "Il romanzo raccontava la storia triste di una famiglia di scrittori.\nIl protagonista scoprì che suo padre ___ molti anni prima, quando lui era ancora bambino.\nQuel segreto era rimasto nascosto per tutta la sua infanzia.\nLa scoperta cambiò per sempre la trama della sua vita.\nAlla fine del capitolo, il narratore lasciò il lettore senza parole.",
      accepted: ["era morto"],
      hint: "trapassato prossimo with essere – morire always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-016", "u21-t1-019", "u21-t1-015", "u21-t2-059"],
    },
    {
      id: "u21-t4-020",
      type: "passage_cloze",
      prompt: "Quella sera, alla festa del paese, tutti parlavano di un evento strano.\nUn uomo misterioso ___ da un altro paese solo per raccontare quella storia.\nNessuno lo conosceva, ma il suo racconto sembrava vero.\nIl segreto che portava con sé cambiò la trama di tutta la serata.\nFinalmente, qualcuno capì chi era davvero quell'uomo.",
      accepted: ["era venuto"],
      hint: "trapassato prossimo with essere – venire always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-011", "u21-t1-002", "u21-t1-031", "u21-t1-017", "u21-t2-060"],
    },
    {
      id: "u21-t4-021",
      type: "passage_cloze",
      prompt: "Dopo la fine della guerra, molte famiglie tornarono nel loro paese.\nSolo pochi abitanti ___ nella vecchia casa durante tutti quegli anni difficili.\nIl narratore della storia raccontava questo con grande rispetto.\nQuella scelta, fatta nel passato, aveva un segreto dietro.\nAlla fine, la scoperta di quel segreto cambiò la trama del racconto.",
      accepted: ["erano rimasti"],
      hint: "trapassato prossimo with essere – rimanere always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-033", "u21-t1-031", "u21-t1-026", "u21-t1-017", "u21-t1-002", "u21-t2-061"],
    },
    {
      id: "u21-t4-022",
      type: "passage_cloze",
      prompt: "Quella notte, Chiara sentì un rumore strano nel palazzo.\nLa sua vicina le raccontò che, poco prima, qualcuno ___ velocemente dalle scale.\nChiara capì che quella scena non era normale.\nIl segreto di quella notte rimase nascosto per settimane.\nFinalmente, la polizia scoprì la verità dietro tutto l'evento.",
      accepted: ["era sceso"],
      hint: "trapassato prossimo with essere – scendere always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-034", "u21-t1-031", "u21-t1-028", "u21-t1-011", "u21-t2-062"],
    },
    {
      id: "u21-t4-023",
      type: "passage_cloze",
      prompt: "Il vecchio scrittore raccontava spesso la sua storia ai giovani del paese.\nPrima di quel viaggio famoso, non ___ uno scrittore conosciuto.\nIl narratore spiegava che ogni capitolo della sua vita aveva cambiato la trama del suo destino.\nUn piccolo segreto del passato aveva reso possibile tutto questo.\nAlla fine, la sua storia diventò un esempio per molti.",
      accepted: ["era ancora diventato"],
      hint: "trapassato prossimo with essere – diventare always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-018", "u21-t1-015", "u21-t1-019", "u21-t1-016", "u21-t1-017", "u21-t1-031", "u21-t1-033", "u21-t2-063"],
    },
    {
      id: "u21-t4-024",
      type: "passage_cloze",
      prompt: "Dopo tanti anni lontano da casa, Marco decise di scrivere le sue memorie.\nRicordava che sua madre ___ a casa quando lui arrivò quella sera d'estate.\nQuella scena era rimasta impressa nella sua mente per sempre.\nIl segreto di quel ritorno cambiò tutta la trama della sua vita.\nFinalmente, Marco capì il vero significato di quel momento.",
      accepted: ["era già tornata"],
      hint: "trapassato prossimo with essere – tornare always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-022", "u21-t1-034", "u21-t1-031", "u21-t1-017", "u21-t1-028", "u21-t2-064"],
    },
    {
      id: "u21-t4-025",
      type: "passage_cloze",
      prompt: "Durante la cena, il nonno cominciò a raccontare una vecchia storia di famiglia.\nDisse che, fino a quel momento, nessuno ___ mai quel segreto così importante.\nI nipoti rimasero in silenzio, sorpresi da quella scoperta improvvisa.\nIl narratore della serata capì che quella storia avrebbe cambiato tutto.\nAlla fine, la famiglia decise di scrivere insieme un nuovo capitolo della loro storia.",
      accepted: ["aveva ricordato"],
      hint: "trapassato prossimo with avere – ricordare is a regular -are verb",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-031", "u21-t1-026", "u21-t1-027", "u21-t1-019", "u21-t1-016", "u21-t1-014", "u21-t2-065"],
    },
    {
      id: "u21-t4-026",
      type: "passage_cloze",
      prompt: "Quando Sara aprì la vecchia scatola, trovò lettere e fotografie ingiallite.\nSi rese conto che, per anni, la sua famiglia ___ completamente quella storia.\nIl segreto nascosto in quelle pagine cambiò per sempre la trama della loro vita.\nPurtroppo, molti dettagli importanti erano andati persi nel passato.\nFinalmente, Sara decise di scrivere il primo capitolo di un libro su tutto questo.",
      accepted: ["aveva dimenticato"],
      hint: "trapassato prossimo with avere – dimenticare is a regular -are verb",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-024", "u21-t1-031", "u21-t1-032", "u21-t1-017", "u21-t1-029", "u21-t1-033", "u21-t1-016", "u21-t2-066"],
    },
    {
      id: "u21-t4-027",
      type: "passage_cloze",
      prompt: "Alla fine del romanzo, il narratore riassume tutta la trama in poche righe.\nIl lettore si rende conto che molti eventi strani ___ prima dell'inizio della storia.\nNessun personaggio aveva capito subito il vero segreto nascosto in quella scena.\nSolo dopo l'ultima sorpresa, tutti si sono resi conto della verità.\nPurtroppo, non tutti i misteri del passato trovano una risposta chiara.",
      accepted: ["erano già accaduti", "erano già successi"],
      hint: "trapassato prossimo with essere – accadere/succedere are impersonal verbs, but the participle still agrees with a plural subject",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-019", "u21-t1-017", "u21-t1-011", "u21-t1-024", "u21-t1-031", "u21-t1-034", "u21-t1-030", "u21-t1-033", "u21-t1-029", "u21-t1-020", "u21-t1-021"],
    },

    // ── Tier 4 replacements – passage_cloze mini-stories replacing retired standalone-sentence cards (2026-08-01) ──
    {
      id: "u21-t4-028",
      type: "passage_cloze",
      prompt: "Chiara finì di leggere l'ultimo capitolo del romanzo poco prima di mezzanotte.\nSolo allora capì che il protagonista, fin dalle prime pagine, ___ un segreto pericoloso.\nAveva notato piccoli indizi durante la lettura, ma non aveva collegato tutto fino a quel momento.\nChiuse il libro lentamente e lo posò sul comodino accanto alla lampada.\nFuori, la strada era ormai deserta e silenziosa.",
      accepted: ["aveva nascosto"],
      hint: "trapassato prossimo with avere – lui; nascondere is irregular: nascosto",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative"],
      tier: 4,
      prerequisites: ["u21-t1-016", "u21-t1-031", "u21-t1-032", "u21-t2-056"],
    },
    {
      id: "u21-t4-029",
      type: "passage_cloze",
      prompt: "Dopo mesi di preparativi, Elena decise finalmente di lasciare la sua città natale per sempre.\nDopo che ___ dalla stazione centrale, si voltò a guardare per l'ultima volta le vecchie case.\nIl treno percorreva lentamente la campagna, e lei ripensava a tutti gli eventi degli ultimi anni.\nSuo fratello le aveva scritto una lettera piena di consigli per il nuovo lavoro.\nElena la lesse due volte, poi la ripiegò con cura nella borsa.",
      accepted: ["era partita"],
      hint: "trapassato prossimo with essere – lei; agreement makes the participle feminine: partita",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "dopo-che", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-007", "u21-t1-011", "u21-t2-037"],
    },
    {
      id: "u21-t4-030",
      type: "passage_cloze",
      prompt: "Alla fine della cerimonia, tutti si complimentarono con gli organizzatori per la buona riuscita della serata.\nPochi sapevano che, prima dell'inizio dell'evento, ___ molte cose storte dietro le quinte.\nUn cameriere aveva rotto un vassoio intero di bicchieri e nessuno sapeva dove trovarne altri.\nLa responsabile aveva già risolto il problema chiamando un fornitore vicino, senza dire nulla agli ospiti.\nSolo il personale in cucina conosceva la verità su quella serata quasi perfetta.",
      accepted: ["erano andate"],
      hint: "trapassato prossimo with essere – loro (cose, feminine plural); andare is one of the core motion verbs that always takes essere",
      tags: ["trapassato-prossimo", "passage-cloze", "narrative", "essere"],
      tier: 4,
      prerequisites: ["u21-t1-004", "u21-t1-009", "u21-t1-011", "u21-t2-034"],
    },
  ],
};
export default unit;
