import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-42-politics-civic-basics",
  name: "Voting and Government (Basics)",
  level: "B1",
  theme: "Politics & Civic Basics",
  emoji: "🗳️",
  prerequisiteUnits: [],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "b142-t1-001", type: "recognize", prompt: "votare", accepted: ["to vote"], hint: "regular -are verb; the core civic action of this unit", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-002", type: "produce", prompt: "to vote", accepted: ["votare"], hint: "regular -are verb", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-003", type: "recognize", prompt: "il voto", accepted: ["the vote"], hint: "masculine noun; also means 'grade' in a school context", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-004", type: "produce", prompt: "the vote", accepted: ["il voto"], hint: "masculine noun", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-005", type: "recognize", prompt: "l'elettore / l'elettrice", accepted: ["the voter"], hint: "masculine/feminine noun; anyone with the right to vote", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-006", type: "produce", prompt: "the voter", accepted: ["l'elettore", "l'elettrice"], hint: "elettore for a man, elettrice for a woman", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-007", type: "recognize", prompt: "il seggio elettorale", accepted: ["the polling station"], hint: "where you go to cast your ballot", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-008", type: "produce", prompt: "the polling station", accepted: ["il seggio elettorale"], hint: "where you go to cast your ballot", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-009", type: "recognize", prompt: "la scheda elettorale", accepted: ["the ballot paper", "the ballot"], hint: "the paper you mark and drop in the box", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-010", type: "produce", prompt: "the ballot paper", accepted: ["la scheda elettorale"], hint: "the paper you mark and drop in the box", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-011", type: "recognize", prompt: "le urne", accepted: ["the ballot boxes", "the polls"], hint: "plural noun; 'andare alle urne' = to go vote", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-012", type: "produce", prompt: "the polls", accepted: ["le urne"], hint: "plural noun", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-013", type: "recognize", prompt: "il partito", accepted: ["the (political) party"], hint: "an organized political group", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-014", type: "produce", prompt: "the political party", accepted: ["il partito"], hint: "an organized political group", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-015", type: "recognize", prompt: "il candidato / la candidata", accepted: ["the candidate"], hint: "the person running for office", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-016", type: "produce", prompt: "the candidate", accepted: ["il candidato", "la candidata"], hint: "the person running for office", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-017", type: "recognize", prompt: "la campagna elettorale", accepted: ["the election campaign"], hint: "the period of speeches, posters, and promises before a vote", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-018", type: "produce", prompt: "the election campaign", accepted: ["la campagna elettorale"], hint: "the period before a vote", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-019", type: "recognize", prompt: "il sindaco", accepted: ["the mayor"], hint: "head of a comune (municipality), male or female", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-020", type: "produce", prompt: "the mayor", accepted: ["il sindaco"], hint: "head of a comune, male or female", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-021", type: "recognize", prompt: "il comune", accepted: ["the municipality", "the town hall", "the local council"], hint: "the local level of government, as opposed to lo stato", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-022", type: "produce", prompt: "the municipality", accepted: ["il comune"], hint: "the local level of government", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-023", type: "recognize", prompt: "il consiglio comunale", accepted: ["the city council", "the town council"], hint: "the elected local assembly that supports the sindaco", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-024", type: "produce", prompt: "the city council", accepted: ["il consiglio comunale"], hint: "the elected local assembly", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-025", type: "recognize", prompt: "il primo ministro", accepted: ["the prime minister"], hint: "head of the national government", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-026", type: "produce", prompt: "the prime minister", accepted: ["il primo ministro"], hint: "head of the national government", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-027", type: "recognize", prompt: "il presidente", accepted: ["the president"], hint: "in Italy, the head of state (a different role from the prime minister)", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-028", type: "produce", prompt: "the president", accepted: ["il presidente"], hint: "the head of state", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-029", type: "recognize", prompt: "lo stato", accepted: ["the state"], hint: "the national level of government, as opposed to il comune", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-030", type: "produce", prompt: "the state", accepted: ["lo stato"], hint: "the national level of government", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-031", type: "recognize", prompt: "eleggere", accepted: ["to elect"], hint: "irregular -ere verb; past participle eletto", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-032", type: "produce", prompt: "to elect", accepted: ["eleggere"], hint: "irregular -ere verb; past participle eletto", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-033", type: "recognize", prompt: "governare", accepted: ["to govern", "to rule"], hint: "regular -are verb", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-034", type: "produce", prompt: "to govern", accepted: ["governare"], hint: "regular -are verb", tags: ["verb", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-035", type: "recognize", prompt: "la rielezione", accepted: ["the re-election"], hint: "ri- + elezione", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-036", type: "produce", prompt: "the re-election", accepted: ["la rielezione"], hint: "ri- + elezione", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-037", type: "recognize", prompt: "il mandato", accepted: ["the term of office", "the mandate"], hint: "the fixed period someone holds an elected office", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-038", type: "produce", prompt: "the term of office", accepted: ["il mandato"], hint: "the fixed period someone holds an elected office", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-039", type: "recognize", prompt: "la maggioranza", accepted: ["the majority"], hint: "more than half; opposite of minoranza", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-040", type: "produce", prompt: "the majority", accepted: ["la maggioranza"], hint: "opposite of minoranza", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-041", type: "recognize", prompt: "la minoranza", accepted: ["the minority"], hint: "less than half; opposite of maggioranza", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-042", type: "produce", prompt: "the minority", accepted: ["la minoranza"], hint: "opposite of maggioranza", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-043", type: "recognize", prompt: "il sondaggio", accepted: ["the poll", "the survey"], hint: "a survey of public opinion before an election", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-044", type: "produce", prompt: "the poll", accepted: ["il sondaggio"], hint: "a survey of public opinion", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-045", type: "recognize", prompt: "il dibattito", accepted: ["the debate"], hint: "a formal exchange of arguments, often televised during a campaign", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-046", type: "produce", prompt: "the debate", accepted: ["il dibattito"], hint: "a formal exchange of arguments", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-047", type: "recognize", prompt: "il manifesto elettorale", accepted: ["the campaign poster"], hint: "the poster a candidate puts up around town", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-048", type: "produce", prompt: "the campaign poster", accepted: ["il manifesto elettorale"], hint: "the poster a candidate puts up around town", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-049", type: "recognize", prompt: "l'affluenza", accepted: ["the turnout"], hint: "specifically 'l'affluenza alle urne' = voter turnout", tags: ["noun", "politics", "vocab"], tier: 1 },
    { id: "b142-t1-050", type: "produce", prompt: "the turnout", accepted: ["l'affluenza"], hint: "'l'affluenza alle urne' = voter turnout", tags: ["noun", "politics", "vocab"], tier: 1 },

    // ── Tier 2 – Grammar (futuro, condizionale, imperfetto, si impersonale, comparativi) ──
    { id: "b142-t2-001", type: "fill_blank", prompt: "Domenica prossima milioni di italiani ___ (votare) per il nuovo sindaco.", accepted: ["voteranno"], hint: "futuro semplice, loro; regular -are verb", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-002", type: "fill_blank", prompt: "Secondo i sondaggi, il partito di centro ___ (vincere) le elezioni comunali.", accepted: ["vincerà"], hint: "futuro semplice, lui/lei; regular -ere verb", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-003", type: "fill_blank", prompt: "Se i risultati saranno confermati, il candidato attuale ___ (perdere) il seggio.", accepted: ["perderà"], hint: "futuro semplice, lui/lei", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-004", type: "fill_blank", prompt: "Il nuovo consiglio comunale ___ (eleggere) il sindaco entro una settimana dal voto.", accepted: ["eleggerà"], hint: "futuro semplice; eleggere is regular in the future tense", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-005", type: "fill_blank", prompt: "Molti si chiedono chi ___ (governare) la città nei prossimi cinque anni.", accepted: ["governerà"], hint: "futuro semplice, lui/lei", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-006", type: "fill_blank", prompt: "Il primo ministro ___ (cambiare) alcune norme sulla sanità dopo le elezioni.", accepted: ["cambierà"], hint: "futuro semplice, lui/lei", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-007", type: "fill_blank", prompt: "Gli esperti prevedono che l'affluenza alle urne ___ (aumentare) rispetto all'anno scorso.", accepted: ["aumenterà"], hint: "futuro semplice, lei (l'affluenza)", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-008", type: "fill_blank", prompt: "Se il tempo sarà brutto domenica, l'affluenza ___ (diminuire) di sicuro.", accepted: ["diminuirà"], hint: "futuro semplice, -ire verb regolare", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-009", type: "fill_blank", prompt: "Il comune ___ (organizzare) i seggi elettorali in tutte le scuole della città.", accepted: ["organizzerà"], hint: "futuro semplice, lui/lei", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-010", type: "fill_blank", prompt: "Le prossime elezioni comunali si ___ (tenersi) la prima domenica di giugno.", accepted: ["terranno"], hint: "futuro irregolare di tenere, radice terr-; qui riflessivo, loro", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-011", type: "fill_blank", prompt: "Tre candidati ___ (presentarsi) alle elezioni per la carica di sindaco.", accepted: ["si presenteranno"], hint: "futuro semplice riflessivo, loro", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-012", type: "fill_blank", prompt: "Anche mia sorella ___ (candidarsi) al consiglio comunale il prossimo anno.", accepted: ["si candiderà"], hint: "futuro semplice riflessivo, lei", tags: ["politics", "grammar", "futuro", "fill_blank"], tier: 2 },
    { id: "b142-t2-013", type: "fill_blank", prompt: "Da cittadino responsabile, tu ___ (dovere) informarti bene prima di votare.", accepted: ["dovresti"], hint: "condizionale presente, tu; radice irregolare dovr-", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-014", type: "fill_blank", prompt: "Io ___ (votare) per il candidato più onesto, non per il più famoso.", accepted: ["voterei"], hint: "condizionale presente, io", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-015", type: "fill_blank", prompt: "Al posto tuo, io non ___ (cambiare) partito così spesso.", accepted: ["cambierei"], hint: "condizionale presente, io", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-016", type: "fill_blank", prompt: "Secondo i giornalisti, il nuovo sindaco ___ (governare) meglio del precedente.", accepted: ["governerebbe"], hint: "condizionale presente, lui/lei", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-017", type: "fill_blank", prompt: "Se ci fosse un altro candidato serio, molti elettori lo ___ (scegliere).", accepted: ["sceglierebbero"], hint: "condizionale presente, loro", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-018", type: "fill_blank", prompt: "Noi due ___ (preferire) un dibattito televisivo più lungo tra i candidati.", accepted: ["preferiremmo"], hint: "condizionale presente, noi", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-019", type: "fill_blank", prompt: "Senza una vera campagna elettorale, il partito non ___ (ottenere) molti voti.", accepted: ["otterrebbe"], hint: "condizionale presente, radice irregolare otterr-", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-020", type: "fill_blank", prompt: "Voi ___ (dovere) leggere il programma di ogni partito prima delle elezioni.", accepted: ["dovreste"], hint: "condizionale presente, voi", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-021", type: "fill_blank", prompt: "Il sindaco uscente ___ (potere) ricandidarsi, ma ha deciso di ritirarsi.", accepted: ["potrebbe"], hint: "condizionale presente, radice irregolare potr-", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-022", type: "fill_blank", prompt: "Con più fondi, il comune ___ (organizzare) più seggi elettorali in periferia.", accepted: ["organizzerebbe"], hint: "condizionale presente, lui/lei", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-023", type: "fill_blank", prompt: "Io non ___ (votare) mai scheda bianca, preferisco sempre scegliere qualcuno.", accepted: ["voterei"], hint: "condizionale presente, io", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-024", type: "fill_blank", prompt: "Al posto del primo ministro, io ___ (essere) più chiaro con gli elettori.", accepted: ["sarei"], hint: "condizionale presente di essere, io", tags: ["politics", "grammar", "condizionale", "fill_blank"], tier: 2 },
    { id: "b142-t2-025", type: "fill_blank", prompt: "Da giovane, mio nonno ___ (votare) sempre per lo stesso partito.", accepted: ["votava"], hint: "imperfetto, lui; abitudine ripetuta nel passato", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-026", type: "fill_blank", prompt: "Negli anni Ottanta, l'affluenza alle urne ___ (essere) molto più alta di oggi.", accepted: ["era"], hint: "imperfetto di essere, lei", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-027", type: "fill_blank", prompt: "Quando abitavo in campagna, il sindaco ci ___ (conoscere) personalmente tutti.", accepted: ["conosceva"], hint: "imperfetto, lui", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-028", type: "fill_blank", prompt: "Ogni mese, il consiglio comunale si ___ (riunire) per discutere del comune.", accepted: ["riuniva"], hint: "imperfetto riflessivo, lui/lei/esso", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-029", type: "fill_blank", prompt: "Da studentessa, mia madre ___ (seguire) ogni dibattito politico in televisione.", accepted: ["seguiva"], hint: "imperfetto, lei", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-030", type: "fill_blank", prompt: "Prima delle elezioni, i candidati ___ (girare) per le strade a distribuire volantini.", accepted: ["giravano"], hint: "imperfetto, loro", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-031", type: "fill_blank", prompt: "Da bambino non capivo perché i miei genitori ___ (discutere) sempre di politica a cena.", accepted: ["discutevano"], hint: "imperfetto, loro", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-032", type: "fill_blank", prompt: "Il vecchio sindaco ___ (avere) un mandato di soli quattro anni.", accepted: ["aveva"], hint: "imperfetto di avere, lui", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-033", type: "fill_blank", prompt: "Ogni sondaggio di quel periodo ___ (dare) il partito di maggioranza in vantaggio.", accepted: ["dava"], hint: "imperfetto di dare, lui/lei/esso", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-034", type: "fill_blank", prompt: "Da ragazzo, mio padre non ___ (potere) ancora votare perché aveva solo sedici anni.", accepted: ["poteva"], hint: "imperfetto di potere, lui", tags: ["politics", "grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b142-t2-035", type: "fill_blank", prompt: "In Italia si ___ (potere) votare a diciotto anni per la Camera.", accepted: ["può"], hint: "si impersonale + potere, presente", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-036", type: "fill_blank", prompt: "Per votare, si ___ (dovere) portare un documento d'identità al seggio.", accepted: ["deve"], hint: "si impersonale + dovere, presente", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-037", type: "fill_blank", prompt: "Prima di scegliere un candidato, bisogna ___ (informarsi) bene sul suo programma.", accepted: ["informarsi"], hint: "bisogna + infinito", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-038", type: "fill_blank", prompt: "Ogni cinque anni si ___ (rinnovare) il consiglio comunale in molte città.", accepted: ["rinnova"], hint: "si impersonale, presente", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-039", type: "fill_blank", prompt: "È importante ___ (andare) a votare, anche quando sembra inutile.", accepted: ["andare"], hint: "è importante + infinito", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-040", type: "fill_blank", prompt: "Non si ___ (dovere) mai sottovalutare l'importanza di un'elezione locale.", accepted: ["deve"], hint: "si impersonale + dovere, presente", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-041", type: "fill_blank", prompt: "Al seggio elettorale si ___ (ricevere) la scheda dopo aver mostrato un documento.", accepted: ["riceve"], hint: "si impersonale, presente", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-042", type: "fill_blank", prompt: "Per diventare sindaco, non basta essere popolari: bisogna anche saper ___ (governare).", accepted: ["governare"], hint: "saper + infinito", tags: ["politics", "grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b142-t2-043", type: "fill_blank", prompt: "Per molti giovani, la politica nazionale sembra ___ (più) interessante di quella locale.", accepted: ["più"], hint: "comparativo di maggioranza: più...di", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-044", type: "fill_blank", prompt: "Le decisioni del comune influenzano la vita quotidiana ___ (più) di quelle dello stato.", accepted: ["più"], hint: "comparativo di maggioranza: più...di", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-045", type: "fill_blank", prompt: "Il mandato del sindaco dura ___ (tanto) quanto quello di un consigliere comunale.", accepted: ["tanto"], hint: "comparativo di uguaglianza: tanto...quanto", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-046", type: "fill_blank", prompt: "Le elezioni comunali interessano la gente ___ (meno) di quelle nazionali, purtroppo.", accepted: ["meno"], hint: "comparativo di minoranza: meno...di", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-047", type: "fill_blank", prompt: "Il primo ministro ha ___ (più) potere del sindaco di una piccola città.", accepted: ["più"], hint: "comparativo di maggioranza: più...di", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-048", type: "fill_blank", prompt: "Secondo i sondaggi, il partito di maggioranza è ___ (il più) votato tra i giovani.", accepted: ["il più"], hint: "superlativo relativo", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-049", type: "fill_blank", prompt: "La campagna elettorale locale è di solito ___ (meno) costosa di quella nazionale.", accepted: ["meno"], hint: "comparativo di minoranza: meno...di", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },
    { id: "b142-t2-050", type: "fill_blank", prompt: "Un buon sindaco conosce gli elettori ___ (meglio) di un politico nazionale.", accepted: ["meglio"], hint: "comparativo irregolare di bene", tags: ["politics", "grammar", "comparativi", "fill_blank"], tier: 2 },

    // ── Tier 3 – Phrases & Collocations ──────────────────────────────────────
    { id: "b142-t3-001", type: "recognize", prompt: "andare a votare", accepted: ["to go vote", "to go and vote"], hint: "votare here is an infinitive after andare + a", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-002", type: "recognize", prompt: "andare alle urne", accepted: ["to go to the polls", "to go vote"], hint: "urne = ballot boxes; the classic phrase for election day", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-003", type: "recognize", prompt: "recarsi al seggio elettorale", accepted: ["to go to the polling station"], hint: "recarsi = formal verb for 'to go/head to'", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-004", type: "recognize", prompt: "fare la fila al seggio", accepted: ["to wait in line at the polling station"], hint: "fare la fila = to queue", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-005", type: "recognize", prompt: "mostrare un documento d'identità", accepted: ["to show an ID"], hint: "required before receiving your ballot", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-006", type: "recognize", prompt: "ritirare la scheda elettorale", accepted: ["to collect the ballot paper"], hint: "ritirare = to pick up / collect", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-007", type: "recognize", prompt: "entrare in cabina", accepted: ["to enter the voting booth"], hint: "cabina (elettorale) = the private voting booth", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-008", type: "recognize", prompt: "fare una croce sul nome", accepted: ["to mark an X next to the name"], hint: "the traditional way to mark a ballot in Italy", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-009", type: "recognize", prompt: "piegare la scheda", accepted: ["to fold the ballot"], hint: "piegare = to fold", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-010", type: "recognize", prompt: "imbucare la scheda nell'urna", accepted: ["to put the ballot in the ballot box"], hint: "imbucare usually means 'to mail', reused here for dropping in the ballot", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-011", type: "recognize", prompt: "votare per un partito", accepted: ["to vote for a party"], hint: "per = for, marking who/what you support", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-012", type: "recognize", prompt: "votare contro qualcuno", accepted: ["to vote against someone"], hint: "contro = against", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-013", type: "recognize", prompt: "votare scheda bianca", accepted: ["to cast a blank ballot"], hint: "scheda bianca = a ballot left intentionally blank", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-014", type: "recognize", prompt: "votare per la prima volta", accepted: ["to vote for the first time"], hint: "la prima volta = the first time", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-015", type: "recognize", prompt: "compiere diciotto anni", accepted: ["to turn eighteen"], hint: "compiere gli anni = to have a birthday", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-016", type: "recognize", prompt: "essere maggiorenne", accepted: ["to be of legal age", "to be an adult"], hint: "maggiorenne = of legal age (18+); opposite: minorenne", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-017", type: "recognize", prompt: "iscriversi alle liste elettorali", accepted: ["to register on the electoral roll"], hint: "iscriversi a = to register/sign up for", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-018", type: "recognize", prompt: "presentarsi alle elezioni", accepted: ["to run in the election"], hint: "reflexive presentarsi = to put oneself forward", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-019", type: "recognize", prompt: "candidarsi a sindaco", accepted: ["to run for mayor"], hint: "candidarsi a + role = to run for (a position)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-020", type: "recognize", prompt: "decidere di candidarsi", accepted: ["to decide to run (as a candidate)"], hint: "candidarsi is always reflexive", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-021", type: "recognize", prompt: "fare una campagna elettorale", accepted: ["to run an election campaign"], hint: "fare + campagna elettorale, the standard collocation", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-022", type: "recognize", prompt: "organizzare un comizio", accepted: ["to organize a rally"], hint: "comizio = a political rally", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-023", type: "recognize", prompt: "tenere un comizio in piazza", accepted: ["to hold a rally in the square"], hint: "tenere un comizio = to hold a rally", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-024", type: "recognize", prompt: "distribuire volantini", accepted: ["to hand out flyers"], hint: "volantini = campaign flyers", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-025", type: "recognize", prompt: "attaccare un manifesto elettorale", accepted: ["to put up a campaign poster"], hint: "attaccare = to stick/put up", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-026", type: "recognize", prompt: "bussare porta a porta", accepted: ["to go door to door"], hint: "a classic grassroots campaigning method", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-027", type: "recognize", prompt: "promettere durante la campagna", accepted: ["to make promises during the campaign"], hint: "promettere = to promise", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-028", type: "recognize", prompt: "mantenere una promessa elettorale", accepted: ["to keep a campaign promise"], hint: "mantenere una promessa = to keep a promise", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-029", type: "recognize", prompt: "rompere una promessa elettorale", accepted: ["to break a campaign promise"], hint: "rompere una promessa = to break a promise", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-030", type: "recognize", prompt: "fare un dibattito televisivo", accepted: ["to hold a televised debate"], hint: "dibattito televisivo = televised debate", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-031", type: "recognize", prompt: "il faccia a faccia tra candidati", accepted: ["the face-off between candidates"], hint: "faccia a faccia = face to face, a head-to-head confrontation", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-032", type: "recognize", prompt: "essere il favorito", accepted: ["to be the frontrunner"], hint: "favorito = the one expected to win", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-033", type: "recognize", prompt: "essere lo sfidante", accepted: ["to be the challenger"], hint: "sfidante = challenger, from sfidare (to challenge)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-034", type: "recognize", prompt: "essere in vantaggio nei sondaggi", accepted: ["to be ahead in the polls"], hint: "in vantaggio = ahead/in the lead", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-035", type: "recognize", prompt: "essere in testa ai sondaggi", accepted: ["to be leading in the polls"], hint: "in testa a = at the head of / leading", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-036", type: "recognize", prompt: "essere indietro nei sondaggi", accepted: ["to be behind in the polls"], hint: "indietro = behind", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-037", type: "recognize", prompt: "un sondaggio dà il partito in vantaggio", accepted: ["a poll shows the party ahead"], hint: "dare qualcuno in vantaggio = to show someone ahead", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-038", type: "recognize", prompt: "condurre un sondaggio", accepted: ["to conduct a poll"], hint: "condurre = to conduct/carry out", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-039", type: "recognize", prompt: "l'affluenza alle urne è alta", accepted: ["turnout is high"], hint: "affluenza = turnout", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-040", type: "recognize", prompt: "i seggi chiudono alle otto", accepted: ["the polling stations close at eight"], hint: "seggi = plural of seggio", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-041", type: "recognize", prompt: "contare i voti", accepted: ["to count the votes"], hint: "voti = plural of voto", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-042", type: "recognize", prompt: "lo spoglio delle schede", accepted: ["the vote count", "the ballot tally"], hint: "spoglio = the official counting of ballots", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-043", type: "recognize", prompt: "il risultato elettorale", accepted: ["the election result"], hint: "risultato = result", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-044", type: "recognize", prompt: "proclamare il vincitore", accepted: ["to declare the winner"], hint: "proclamare = to officially declare", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-045", type: "recognize", prompt: "vincere le elezioni", accepted: ["to win the election"], hint: "vincere = to win", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-046", type: "recognize", prompt: "perdere le elezioni", accepted: ["to lose the election"], hint: "perdere = to lose", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-047", type: "recognize", prompt: "vincere al primo turno", accepted: ["to win in the first round"], hint: "primo turno = first round of voting", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-048", type: "recognize", prompt: "andare al ballottaggio", accepted: ["to go to a runoff"], hint: "ballottaggio = runoff vote between the top two candidates", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-049", type: "recognize", prompt: "decidersi al secondo turno", accepted: ["to be decided in the second round"], hint: "secondo turno = second round / runoff", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-050", type: "recognize", prompt: "ottenere la maggioranza", accepted: ["to win a majority", "to obtain a majority"], hint: "ottenere = to obtain", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-051", type: "recognize", prompt: "non raggiungere la maggioranza", accepted: ["to fall short of a majority"], hint: "raggiungere = to reach", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-052", type: "recognize", prompt: "formare una coalizione", accepted: ["to form a coalition"], hint: "coalizione = alliance of parties", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-053", type: "recognize", prompt: "rompere una coalizione", accepted: ["to break up a coalition"], hint: "rompere = to break", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-054", type: "recognize", prompt: "cambiare partito", accepted: ["to switch parties"], hint: "cambiare = to change", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-055", type: "recognize", prompt: "iscriversi a un partito", accepted: ["to join a party"], hint: "iscriversi a = to enroll/join", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-056", type: "recognize", prompt: "lasciare un partito", accepted: ["to leave a party"], hint: "lasciare = to leave", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-057", type: "recognize", prompt: "il partito di maggioranza", accepted: ["the majority party"], hint: "di maggioranza = majority (adjectival use)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-058", type: "recognize", prompt: "il partito di minoranza", accepted: ["the minority party"], hint: "di minoranza = minority (adjectival use)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-059", type: "recognize", prompt: "essere di sinistra", accepted: ["to be left-wing"], hint: "sinistra = left (politically)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-060", type: "recognize", prompt: "essere di destra", accepted: ["to be right-wing"], hint: "destra = right (politically)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-061", type: "recognize", prompt: "essere di centro", accepted: ["to be centrist"], hint: "centro = center (politically)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-062", type: "recognize", prompt: "il sindaco uscente", accepted: ["the outgoing mayor"], hint: "uscente = outgoing", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-063", type: "recognize", prompt: "il sindaco entrante", accepted: ["the incoming mayor"], hint: "entrante = incoming", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-064", type: "recognize", prompt: "il nuovo eletto", accepted: ["the newly elected official"], hint: "eletto = elected, from eleggere, used here as a noun", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-065", type: "recognize", prompt: "rieleggere il sindaco", accepted: ["to re-elect the mayor"], hint: "rieleggere = ri- + eleggere", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-066", type: "recognize", prompt: "rinnovare il mandato", accepted: ["to renew the term", "to renew the mandate"], hint: "rinnovare = to renew", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-067", type: "recognize", prompt: "il mandato sta per scadere", accepted: ["the term is about to expire"], hint: "stare per + infinito = to be about to", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-068", type: "recognize", prompt: "insediarsi come sindaco", accepted: ["to take office as mayor"], hint: "insediarsi = to take office, formally settle in", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-069", type: "recognize", prompt: "prestare giuramento", accepted: ["to take an oath"], hint: "giuramento = oath, from giurare (to swear)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-070", type: "recognize", prompt: "succedere al sindaco uscente", accepted: ["to succeed the outgoing mayor"], hint: "succedere a = to succeed / take over from", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-071", type: "recognize", prompt: "il consiglio comunale si riunisce", accepted: ["the city council meets"], hint: "riunirsi = to meet, convene", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-072", type: "recognize", prompt: "discutere in consiglio comunale", accepted: ["to debate in the city council"], hint: "discutere = to discuss/debate", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-073", type: "recognize", prompt: "approvare un progetto in consiglio", accepted: ["to approve a project in council"], hint: "approvare = to approve", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-074", type: "recognize", prompt: "il comune finanzia un progetto", accepted: ["the municipality funds a project"], hint: "finanziare = to fund", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-075", type: "recognize", prompt: "parlare di politica a tavola", accepted: ["to talk politics at the table"], hint: "a tavola = at the (dinner) table", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-076", type: "recognize", prompt: "evitare di parlare di politica", accepted: ["to avoid talking about politics"], hint: "evitare di + infinito = to avoid doing", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-077", type: "recognize", prompt: "fare il tifo per un candidato", accepted: ["to root for a candidate"], hint: "fare il tifo per = to root/cheer for, usually sports slang", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-078", type: "recognize", prompt: "schierarsi con un partito", accepted: ["to side with a party"], hint: "schierarsi con = to align oneself with", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-079", type: "recognize", prompt: "restare neutrale in politica", accepted: ["to stay neutral in politics"], hint: "neutrale = neutral", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-080", type: "recognize", prompt: "essere indeciso su chi votare", accepted: ["to be undecided about who to vote for"], hint: "indeciso = undecided", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-081", type: "recognize", prompt: "esprimere il proprio voto", accepted: ["to cast one's vote"], hint: "esprimere il voto = a formal way to say 'to vote'", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-082", type: "recognize", prompt: "essere un elettore indeciso", accepted: ["to be an undecided voter"], hint: "combines elettore + indeciso", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-083", type: "recognize", prompt: "un candidato serio", accepted: ["a serious candidate"], hint: "serio = serious, credible", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-084", type: "recognize", prompt: "il discorso del primo ministro", accepted: ["the prime minister's speech"], hint: "discorso = speech", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-085", type: "recognize", prompt: "il presidente della repubblica", accepted: ["the president of the republic"], hint: "the Italian head of state's official title", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-086", type: "recognize", prompt: "eleggere il sindaco", accepted: ["to elect the mayor"], hint: "eleggere + role/person = to elect someone", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-087", type: "recognize", prompt: "governare una città", accepted: ["to govern a city"], hint: "governare + place = to govern/run (a place)", tags: ["politics", "chunk", "collocation"], tier: 3 },
    { id: "b142-t3-088", type: "recognize", prompt: "puntare alla rielezione", accepted: ["to aim for re-election"], hint: "puntare a = to aim for", tags: ["politics", "chunk", "collocation"], tier: 3 },

    // ── Tier 4 – Passage Cloze ───────────────────────────────────────────────
    {
      id: "b142-t4-001",
      type: "passage_cloze",
      prompt: "Domenica prossima Giulia voterà per la prima volta: ha compiuto diciotto anni a marzo e non vede l'ora di andare al seggio elettorale con suo padre. Ha letto i programmi di tre partiti diversi e ha già deciso chi sceglierà, anche se non ne ha parlato con nessuno. Sua madre le ha detto di portare sempre un documento d'identità, altrimenti al seggio non le daranno la ___.",
      accepted: ["scheda", "scheda elettorale"],
      hint: "the ballot paper you need before entering the voting booth",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-007", "b142-t1-009", "b142-t1-015"],
    },
    {
      id: "b142-t4-002",
      type: "passage_cloze",
      prompt: "Nel piccolo comune di Vallelunga, oggi si vota per il nuovo sindaco. I due candidati, entrambi molto conosciuti in paese, hanno fatto una campagna elettorale intensa nelle ultime settimane, con comizi in piazza e volantini distribuiti porta a porta. Alle sette di sera i seggi chiuderanno e comincerà lo spoglio delle schede. Molti abitanti sono curiosi di sapere chi ___ le elezioni, il macellaio o la maestra in pensione.",
      accepted: ["vincerà"],
      hint: "futuro semplice di vincere, lui/lei",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-019", "b142-t1-021", "b142-t1-017"],
    },
    {
      id: "b142-t4-003",
      type: "passage_cloze",
      prompt: "A cena, il nonno di Marco parla sempre di politica e critica ogni sindaco, vecchio o nuovo. Stasera dice che il primo ministro attuale non capisce i problemi della gente comune, mentre la nonna preferisce parlare del sindaco e dei problemi del comune, come le strade rotte. Marco ascolta in silenzio: sa che, alle prossime elezioni, anche lui ___ (potere) finalmente votare, perché il mese prossimo compie diciotto anni.",
      accepted: ["potrà"],
      hint: "futuro semplice di potere, lui",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-025", "b142-t1-019", "b142-t1-021"],
    },
    {
      id: "b142-t4-004",
      type: "passage_cloze",
      prompt: "Mancano due settimane alle elezioni nazionali e i sondaggi si susseguono ogni giorno. Il partito di maggioranza resta in vantaggio, ma la distanza con gli altri partiti si riduce settimana dopo settimana. Molti analisti pensano che il dibattito televisivo di ieri sera ha aiutato il candidato più giovane, apparso sicuro e preparato davanti a milioni di telespettatori. Se l'affluenza alle urne ___ (essere) alta domenica, il risultato finale potrebbe sorprendere tutti.",
      accepted: ["sarà"],
      hint: "futuro semplice di essere, lei (l'affluenza)",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-043", "b142-t1-045", "b142-t1-049"],
    },
    {
      id: "b142-t4-005",
      type: "passage_cloze",
      prompt: "Da mesi il consiglio comunale discute di come riparare le strade del centro, ma i lavori non iniziano mai. Il sindaco dice che mancano i fondi, mentre alcuni consiglieri pensano che il comune ___ (dovere) chiedere aiuto allo stato. Nel frattempo, il primo ministro ha promesso più soldi per i piccoli comuni durante la sua ultima campagna elettorale, ma finora nessuno ha visto un euro arrivare a Vallelunga.",
      accepted: ["dovrebbe"],
      hint: "condizionale presente di dovere, lui/lei (il comune)",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-023", "b142-t1-021", "b142-t1-029"],
    },
    {
      id: "b142-t4-006",
      type: "passage_cloze",
      prompt: "Per un compito di scuola, Sara deve spiegare la differenza tra il sindaco e il primo ministro. Scrive che il sindaco governa un solo comune e si occupa di cose pratiche, come le strade, mentre il primo ministro guida lo stato intero e si occupa delle questioni più importanti del paese. Sara aggiunge che entrambi hanno un mandato a tempo determinato e che, alla fine, gli elettori possono scegliere se ___ (rieleggere) loro o votare per qualcun altro.",
      accepted: ["rieleggere"],
      hint: "infinito dopo 'se', senza cambiare soggetto",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-019", "b142-t1-025", "b142-t1-029", "b142-t1-037"],
    },
    {
      id: "b142-t4-007",
      type: "passage_cloze",
      prompt: "Ieri sera, in televisione, i due candidati alla carica di sindaco si sono affrontati in un lungo dibattito. Il candidato uscente ha ricordato i progetti già realizzati durante il suo mandato, mentre la sfidante ha criticato la mancanza di nuove idee per il comune. A un certo punto, il moderatore ha chiesto a entrambi come ___ (pensare) di aumentare l'affluenza alle urne tra i giovani elettori.",
      accepted: ["pensano"],
      hint: "presente indicativo, loro",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-045", "b142-t1-037", "b142-t1-049"],
    },
    {
      id: "b142-t4-008",
      type: "passage_cloze",
      prompt: "Ogni sabato mattina, un gruppo di volontari del partito si ritrova in piazza per distribuire volantini e parlare con i passanti della campagna elettorale. Alcuni si fermano volentieri ad ascoltare, altri invece evitano di parlare di politica e tirano dritto. Il coordinatore dei volontari dice che, anche se il lavoro è faticoso, ogni voto in più conta, perché spesso le elezioni comunali si ___ (decidere) per poche decine di voti.",
      accepted: ["decidono"],
      hint: "presente indicativo riflessivo, loro",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-013", "b142-t1-017", "b142-t1-003"],
    },
    {
      id: "b142-t4-009",
      type: "passage_cloze",
      prompt: "Quest'anno l'affluenza alle urne è stata più alta del solito, soprattutto tra i giovani elettori. I sondaggi della vigilia avevano previsto un'affluenza bassa, ma la lunga campagna elettorale e un dibattito televisivo molto seguito hanno convinto molte persone a informarsi meglio sui candidati. Il sindaco uscente, che si è ricandidato per un secondo mandato, ha ringraziato tutti quelli che ___ (andare) a votare, anche chi non ha votato per lui.",
      accepted: ["sono andati"],
      hint: "passato prossimo di andare, loro",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-049", "b142-t1-043", "b142-t1-005"],
    },
    {
      id: "b142-t4-010",
      type: "passage_cloze",
      prompt: "Alle elezioni comunali di quest'anno, nessun candidato ha ottenuto la maggioranza al primo turno, così si andrà al ballottaggio tra i due partiti più votati. Il candidato del partito di maggioranza relativa sembra favorito, ma lo sfidante spera di convincere gli elettori che avevano votato per gli altri partiti eliminati. Il ballottaggio si terrà tra due settimane e molti si chiedono quale ___ (essere) l'affluenza questa volta.",
      accepted: ["sarà"],
      hint: "futuro semplice di essere, lei (l'affluenza)",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-039", "b142-t1-015", "b142-t1-049"],
    },
    {
      id: "b142-t4-011",
      type: "passage_cloze",
      prompt: "Dopo due mandati, il sindaco di Montepiano ha deciso di non ricandidarsi e di lasciare il posto a un nuovo candidato del suo stesso partito. Durante il suo ultimo discorso in consiglio comunale, ha ringraziato tutti gli elettori e ha detto di essere orgoglioso dei progetti realizzati per il comune. Il nuovo candidato, che ha lavorato per anni come assessore, spera di ___ (succedere) al sindaco uscente senza troppe difficoltà.",
      accepted: ["succedere"],
      hint: "infinito dopo 'sperare di'",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-037", "b142-t1-023", "b142-t1-015"],
    },
    {
      id: "b142-t4-012",
      type: "passage_cloze",
      prompt: "Il consiglio comunale si è riunito ieri sera per decidere se costruire una nuova pista ciclabile in centro. Alcuni consiglieri della maggioranza sostengono il progetto, mentre altri, soprattutto della minoranza, pensano che i soldi devono essere usati per riparare le strade. Dopo una lunga discussione, il sindaco ha proposto di ___ (chiedere) l'opinione diretta degli abitanti prima di decidere. Molti cittadini aspettano il risultato con curiosità.",
      accepted: ["chiedere"],
      hint: "infinito dopo 'proporre di'",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-023", "b142-t1-039", "b142-t1-041"],
    },
    {
      id: "b142-t4-013",
      type: "passage_cloze",
      prompt: "In Italia, il mandato di un sindaco dura normalmente cinque anni, proprio come quello del consiglio comunale che lo ha eletto. Al termine del mandato, il sindaco può decidere di candidarsi di nuovo per la rielezione, ma dopo due mandati consecutivi in molti comuni non può più farlo. Per questo motivo, molti sindaci uscenti passano l'ultimo anno a preparare chi li ___ (succedere).",
      accepted: ["succederà"],
      hint: "futuro semplice di succedere, lui/lei",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-037", "b142-t1-035", "b142-t1-019"],
    },
    {
      id: "b142-t4-014",
      type: "passage_cloze",
      prompt: "A una settimana dalle elezioni nazionali, l'ultimo sondaggio mostra i due partiti principali quasi alla pari: il partito di maggioranza uscente ha solo due punti di vantaggio sul rivale. Gli analisti dicono che il risultato dipenderà soprattutto dai giovani elettori indecisi, che secondo i sondaggi rappresentano quasi un quinto del totale. Il primo ministro uscente ha invitato tutti a ___ (votare), indipendentemente dalla scelta.",
      accepted: ["votare"],
      hint: "infinito dopo 'invitare a'",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-043", "b142-t1-039", "b142-t1-025"],
    },
    {
      id: "b142-t4-015",
      type: "passage_cloze",
      prompt: "Sabato sera, in piazza principale, si è tenuto l'ultimo grande comizio della campagna elettorale. Centinaia di persone hanno ascoltato il discorso del candidato favorito, che ha promesso di migliorare i trasporti pubblici e i servizi del comune. Alla fine, molti elettori si sono avvicinati per fargli domande dirette, mentre altri hanno preferito restare in disparte e ___ (ascoltare) in silenzio.",
      accepted: ["ascoltare"],
      hint: "infinito dopo 'preferire di'",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-017", "b142-t1-021", "b142-t1-005"],
    },
    {
      id: "b142-t4-016",
      type: "passage_cloze",
      prompt: "Alla scuola di Elena, ogni anno gli studenti eleggono un rappresentante di istituto, un po' come succede con il sindaco in un comune vero. Quest'anno Elena ha deciso di candidarsi per la prima volta e ha preparato un piccolo programma con idee per migliorare la biblioteca e la mensa. I suoi compagni di classe le hanno chiesto come pensa di convincere gli altri studenti a ___ (votare) per lei.",
      accepted: ["votare"],
      hint: "infinito dopo 'convincere a'",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-031", "b142-t1-019", "b142-t1-021"],
    },
    {
      id: "b142-t4-017",
      type: "passage_cloze",
      prompt: "Due vicini di casa, il signor Rossi e la signora Bianchi, discutono spesso davanti al portone del palazzo. Il signor Rossi sostiene che il sindaco attuale ha mantenuto quasi tutte le promesse della campagna elettorale, mentre la signora Bianchi ricorda che le strade del quartiere sono ancora rotte da anni. Alla fine, i due si trovano d'accordo su una cosa: alle prossime elezioni comunali, bisognerà ___ (informarsi) meglio prima di scegliere.",
      accepted: ["informarsi"],
      hint: "infinito dopo bisognerà",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-019", "b142-t1-017", "b142-t1-005"],
    },
    {
      id: "b142-t4-018",
      type: "passage_cloze",
      prompt: "La sera delle elezioni, milioni di italiani restano davanti alla televisione per seguire lo spoglio delle schede in diretta. I giornalisti mostrano i primi risultati parziali, comune per comune, mentre gli esperti commentano ogni sondaggio all'uscita dai seggi. Verso mezzanotte, i risultati diventano più chiari e si capisce quale partito ___ (ottenere) la maggioranza dei voti nel nuovo consiglio comunale.",
      accepted: ["otterrà"],
      hint: "futuro semplice di ottenere, radice irregolare otterr-",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-013", "b142-t1-039", "b142-t1-021"],
    },
    {
      id: "b142-t4-019",
      type: "passage_cloze",
      prompt: "Quando la nonna di Luca era giovane, le donne in Italia non potevano ancora votare, e lei ricorda ancora la prima volta che è andata alle urne. Oggi accompagna Luca, che vota per la prima volta, e gli racconta come la campagna elettorale di allora fosse diversa: niente televisione, solo manifesti elettorali e comizi in piazza. Luca ascolta con attenzione, mentre ___ (aspettare) il proprio turno davanti al seggio.",
      accepted: ["aspetta"],
      hint: "presente indicativo, lui",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-001", "b142-t1-017", "b142-t1-047"],
    },
    {
      id: "b142-t4-020",
      type: "passage_cloze",
      prompt: "Fino all'ultimo giorno, Paolo non sapeva per chi votare: trovava il candidato del partito di maggioranza troppo simile al passato e lo sfidante ancora troppo inesperto. La sera prima delle elezioni ha guardato un ultimo dibattito televisivo e ha deciso di dare una possibilità al candidato più giovane. La mattina dopo, al seggio elettorale, ha finalmente fatto la sua scelta e ___ (imbucare) la scheda nell'urna con convinzione.",
      accepted: ["ha imbucato"],
      hint: "passato prossimo di imbucare, lui",
      tags: ["politics", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b142-t1-015", "b142-t1-045", "b142-t1-011"],
    },
  ],
};
export default unit;
