import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-20-congiuntivo",
  name: "Expressing Doubt",
  level: "B1",
  theme: "Congiuntivo Presente",
  emoji: "🤔",
  prerequisiteUnits: ["b1-unit-19-relative-pronouns"],
  cards: [
    // ── Tier 1 – Vocab ──────────────────────────────────────────────────────
    {
      id: "u20-t1-001",
      type: "recognize",
      prompt: "il dubbio",
      accepted: ["the doubt", "the uncertainty"],
      hint: "Masculine noun; root of dubitare (to doubt) and dubbioso (doubtful).",
      tags: ["noun", "doubt", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-002",
      type: "produce",
      prompt: "the opinion",
      accepted: ["l'opinione"],
      hint: "Feminine noun with an elided article: l'opinione, plural le opinioni.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-003",
      type: "produce",
      prompt: "the belief",
      accepted: ["la credenza", "la convinzione"],
      hint: "La convinzione is the more common everyday choice; both are feminine, from credere and convincere.",
      tags: ["noun", "belief", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-004",
      type: "recognize",
      prompt: "forse",
      accepted: ["maybe", "perhaps", "possibly"],
      hint: "States plain possibility and does not itself trigger the congiuntivo, unlike è possibile che.",
      tags: ["adverb", "doubt", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-005",
      type: "recognize",
      prompt: "probabilmente",
      accepted: ["probably", "likely"],
      hint: "Formed from probabile + -mente; like forse, it does not force the following verb into the congiuntivo.",
      tags: ["adverb", "doubt", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-006",
      type: "produce",
      prompt: "the hope",
      accepted: ["la speranza"],
      hint: "Feminine noun; the verb sperare che is one of the core congiuntivo triggers in this unit.",
      tags: ["noun", "opinion", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-007",
      type: "produce",
      prompt: "the fear",
      accepted: ["la paura", "il timore"],
      hint: "La paura is the everyday word; il timore is more formal. Avere paura che also triggers the congiuntivo.",
      tags: ["noun", "emotion", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-008",
      type: "recognize",
      prompt: "mi sembra che",
      accepted: ["it seems to me that", "it appears to me that"],
      hint: "Fixed impersonal expression, always followed by the congiuntivo in the dependent clause.",
      tags: ["expression", "doubt", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-009",
      type: "recognize",
      prompt: "ho l'impressione che",
      accepted: ["I have the impression that", "I get the feeling that"],
      hint: "Like mi sembra che, this doubt expression always triggers the congiuntivo that follows.",
      tags: ["expression", "doubt", "trigger", "vocab"],
      tier: 1,
    },
    {
      id: "u20-t1-010",
      type: "produce",
      prompt: "the necessity",
      accepted: ["la necessità"],
      hint: "Feminine noun ending in -tà, invariable in the plural (le necessità); è necessario che triggers the congiuntivo.",
      tags: ["noun", "vocab"],
      tier: 1,
    },
    // ── Tier 2 – Grammar ────────────────────────────────────────────────────
    {
      id: "u20-t2-001",
      type: "conjugate",
      prompt: "parlare (congiuntivo presente) – io",
      accepted: ["parli"],
      hint: "All three singular persons share the same congiuntivo form for -are verbs.",
      tags: ["congiuntivo", "grammar", "parlare", "conjugation"],
      tier: 2,
    },
    {
      id: "u20-t2-002",
      type: "conjugate",
      prompt: "parlare (congiuntivo presente) – noi",
      accepted: ["parliamo"],
      hint: "The noi form of -are verbs in the congiuntivo is identical to the indicativo presente.",
      tags: ["congiuntivo", "grammar", "parlare", "conjugation"],
      tier: 2,
    },
    {
      id: "u20-t2-003",
      type: "conjugate",
      prompt: "parlare (congiuntivo presente) – loro",
      accepted: ["parlino"],
      hint: "Loro takes -ino for -are verbs, distinct from the three shared singular forms.",
      tags: ["congiuntivo", "grammar", "parlare", "conjugation"],
      tier: 2,
    },
    {
      id: "u20-t2-004",
      type: "conjugate",
      prompt: "essere (congiuntivo presente) – io",
      accepted: ["sia"],
      hint: "Essere is irregular throughout the congiuntivo; sia serves io, tu, and lui/lei alike.",
      tags: ["congiuntivo", "grammar", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u20-t2-005",
      type: "conjugate",
      prompt: "essere (congiuntivo presente) – noi",
      accepted: ["siamo"],
      hint: "Noi siamo matches the indicativo presente exactly, unlike the irregular singular forms.",
      tags: ["congiuntivo", "grammar", "essere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u20-t2-006",
      type: "conjugate",
      prompt: "avere (congiuntivo presente) – tu",
      accepted: ["abbia"],
      hint: "Avere's irregular stem abbi- covers io, tu, and lui/lei alike: abbia.",
      tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u20-t2-007",
      type: "conjugate",
      prompt: "avere (congiuntivo presente) – loro",
      accepted: ["abbiano"],
      hint: "Loro adds -no to the irregular abbia- stem: abbiano.",
      tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"],
      tier: 2,
    },
    {
      id: "u20-t2-008",
      type: "fill_blank",
      prompt: "È necessario che tu ___ (venire) alla riunione.",
      accepted: ["venga"],
      hint: "Irregular congiuntivo: venire → venga, venga, venga, veniamo, veniate, vengano.",
      tags: ["congiuntivo", "grammar", "trigger", "fill_blank"],
      tier: 2,
    },
    // ── Tier 3 – Chunks ─────────────────────────────────────────────────────
    {
      id: "u20-t3-001",
      type: "produce",
      prompt: "The chef has worked a double shift every day this week during the restaurant's busiest season, so I think he is tired.",
      accepted: [
        "Lo chef ha fatto un doppio turno ogni giorno questa settimana durante la stagione più intensa del ristorante, quindi credo che sia stanco.",
        "Lo chef ha fatto un doppio turno ogni giorno questa settimana durante la stagione più intensa del ristorante, quindi penso che sia stanco.",
      ],
      hint: "Use the congiuntivo of essere after credere/pensare che.",
      tags: ["congiuntivo", "chunk", "credo che", "essere"],
      tier: 3,
    },
    {
      id: "u20-t3-002",
      type: "produce",
      prompt: "It is possible that she will come.",
      accepted: ["È possibile che venga.", "È possibile che lei venga."],
      hint: "È possibile che triggers the congiuntivo; venire → venga for lei.",
      tags: ["congiuntivo", "chunk", "è possibile che", "venire"],
      tier: 3,
    },
    {
      id: "u20-t3-003",
      type: "produce",
      prompt: "Although it is difficult, I will try.",
      accepted: [
        "Sebbene sia difficile, ci proverò.",
        "Benché sia difficile, ci proverò.",
        "Nonostante sia difficile, ci proverò.",
      ],
      hint: "Sebbene / benché / nonostante all require the congiuntivo.",
      tags: ["congiuntivo", "chunk", "sebbene", "benché", "concessiva"],
      tier: 3,
    },
    {
      id: "u20-t3-004",
      type: "produce",
      prompt: "I want you to study.",
      accepted: ["Voglio che tu studi."],
      hint: "Volere che triggers the congiuntivo when the subjects differ.",
      tags: ["congiuntivo", "chunk", "volere che", "different subject"],
      tier: 3,
    },
    {
      id: "u20-t3-005",
      type: "produce",
      prompt: "Since my parents are driving three hours to reach the venue for the wedding, I hope they have time to rest before the ceremony starts.",
      accepted: [
        "Visto che i miei genitori guidano per tre ore per arrivare al locale per il matrimonio, spero che abbiano tempo per riposare prima che inizi la cerimonia.",
      ],
      hint: "Sperare che always triggers the congiuntivo; avere → abbiano for loro.",
      tags: ["congiuntivo", "chunk", "sperare che", "avere"],
      tier: 3,
    },
    {
      id: "u20-t3-006",
      type: "produce",
      prompt: "He has changed small details in his account three times since this morning, so I am not sure he is right.",
      accepted: [
        "Ha cambiato piccoli dettagli nel suo racconto tre volte da stamattina, quindi non sono sicuro che abbia ragione.",
        "Ha cambiato piccoli dettagli nel suo racconto tre volte da stamattina, quindi non sono sicura che abbia ragione.",
      ],
      hint: "Non essere sicuro/a che triggers the congiuntivo.",
      tags: ["congiuntivo", "chunk", "doubt", "non sono sicuro"],
      tier: 3,
    },
    // ── Tier 4 – Sentence & Passage ─────────────────────────────────────────
    {
      id: "u20-t4-001",
      type: "produce",
      prompt: "Although Marco has a lot of doubts, it seems to me that he has good opinions.",
      accepted: [
        "Benché Marco abbia molti dubbi, mi sembra che abbia buone opinioni.",
        "Sebbene Marco abbia molti dubbi, mi sembra che abbia buone opinioni.",
        "Nonostante Marco abbia molti dubbi, mi sembra che abbia buone opinioni.",
      ],
      hint: "Two congiuntivo triggers in one sentence: benché/sebbene/nonostante + mi sembra che.",
      tags: ["congiuntivo", "sentence", "complex", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-001", "u20-t1-002", "u20-t1-008", "u20-t2-006", "u20-t2-007"],
      deprecated: true,
    },
    {
      id: "u20-t4-002",
      type: "fill_blank",
      prompt: "Penso che la necessità di studiare ___ (essere) evidente per tutti gli studenti.",
      accepted: ["sia"],
      hint: "Pensare che requires the congiuntivo. Essere → sia (singular).",
      tags: ["congiuntivo", "fill_blank", "pensare che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-010", "u20-t2-004", "u20-t2-005"],
      deprecated: true,
    },
    {
      id: "u20-t4-003",
      type: "fill_blank",
      prompt: "Ho l'impressione che loro non ___ (avere) abbastanza tempo per finire il progetto.",
      accepted: ["abbiano"],
      hint: "Ho l'impressione che triggers the congiuntivo. Avere → abbiano (loro).",
      tags: ["congiuntivo", "fill_blank", "ho l'impressione che", "avere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-009", "u20-t2-007"],
      deprecated: true,
    },
    {
      id: "u20-t4-004",
      type: "passage_cloze",
      prompt:
        "Marco è uno studente universitario che ha molte opinioni sul futuro.\nPensa che il suo paese ___ bisogno di grandi cambiamenti per migliorare.\nSebbene la situazione sia difficile, spera che tutti i cittadini abbiano la forza di reagire.\nMi sembra che il suo ottimismo sia contagioso e che ispiri anche i suoi compagni di classe.",
      accepted: ["abbia"],
      hint: "Pensare che triggers the congiuntivo; with a singular subject, essere → sia.",
      tags: ["congiuntivo", "passage_cloze", "avere", "pensare che", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-006", "u20-t1-008", "u20-t2-006", "u20-t2-007"],
    },
    {
      id: "u20-t4-005",
      type: "passage_cloze",
      prompt:
        "Luisa parla con la sua amica di un viaggio che vorrebbe fare in Italia.\nÈ importante che lei ___ bene l'italiano prima di partire.\nForse sarà difficile, ma crede che la pratica quotidiana sia essenziale.\nNonostante abbia dubbi sulla sua pronuncia, ho l'impressione che faccia grandi progressi.\nSi dice anche che la motivazione sia la chiave del successo nell'apprendimento delle lingue.",
      accepted: ["parli"],
      hint: "È importante che triggers the congiuntivo; with a singular subject, parlare → parli.",
      tags: ["congiuntivo", "passage_cloze", "parlare", "è importante che", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-001", "u20-t1-004", "u20-t1-008", "u20-t2-001", "u20-t2-002", "u20-t2-003"],
    },

    // ── Tier 1 – Vocab (expansion): doubt & uncertainty word family ──────────
    { id: "u20-t1-011", type: "recognize", prompt: "dubitare", accepted: ["to doubt"], hint: "Dubitare che is one of the strongest doubt triggers — always followed by the congiuntivo.", tags: ["verb", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-012", type: "produce", prompt: "to doubt", accepted: ["dubitare"], hint: "Regular -are verb: dubito, dubiti, dubita, dubitiamo, dubitate, dubitano.", tags: ["verb", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-013", type: "recognize", prompt: "dubbioso", accepted: ["doubtful", "hesitant"], hint: "Adjective from il dubbio; agrees in gender: dubbioso/dubbiosa.", tags: ["adjective", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-014", type: "produce", prompt: "doubtful", accepted: ["dubbioso", "dubbiosa"], hint: "Essere dubbioso/a che triggers the congiuntivo, just like essere convinto/a che.", tags: ["adjective", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-015", type: "recognize", prompt: "il sospetto", accepted: ["the suspicion"], hint: "Masculine noun; word family with sospettare.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-016", type: "produce", prompt: "the suspicion", accepted: ["il sospetto"], hint: "Common in avere il sospetto che, which also triggers the congiuntivo.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-017", type: "recognize", prompt: "sospettare", accepted: ["to suspect"], hint: "Sospettare che triggers the congiuntivo, just like dubitare che.", tags: ["verb", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-018", type: "produce", prompt: "to suspect", accepted: ["sospettare"], hint: "Regular -are verb, word family with il sospetto.", tags: ["verb", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-019", type: "recognize", prompt: "l'incertezza", accepted: ["the uncertainty"], hint: "Feminine noun with an elided article; word family with incerto.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-020", type: "produce", prompt: "the uncertainty", accepted: ["l'incertezza"], hint: "Opposite of la certezza.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-021", type: "recognize", prompt: "incerto", accepted: ["uncertain"], hint: "Feminine incerta; used in essere incerto/a su qualcosa (to be uncertain about something), and pairs with su + noun rather than che when there is no dependent clause.", tags: ["adjective", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-022", type: "produce", prompt: "uncertain", accepted: ["incerto", "incerta"], hint: "Word family with l'incertezza.", tags: ["adjective", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-023", type: "recognize", prompt: "la perplessità", accepted: ["the perplexity", "the puzzlement"], hint: "Feminine noun; word family with perplesso.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-024", type: "produce", prompt: "the perplexity", accepted: ["la perplessità"], hint: "Often used in the phrase uno sguardo di perplessità.", tags: ["noun", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-025", type: "recognize", prompt: "perplesso", accepted: ["perplexed", "puzzled"], hint: "Feminine perplessa; common in the collocation uno sguardo perplesso (a puzzled look), from the same root as la perplessità.", tags: ["adjective", "doubt", "vocab"], tier: 1 },
    { id: "u20-t1-026", type: "produce", prompt: "perplexed", accepted: ["perplesso", "perplessa"], hint: "Word family with la perplessità.", tags: ["adjective", "doubt", "vocab"], tier: 1 },

    // ── Tier 2 – Grammar (expansion): congiuntivo presente, remaining persons ─
    { id: "u20-t2-009", type: "conjugate", prompt: "parlare (congiuntivo presente) – tu", accepted: ["parli"], hint: "Tu shares the same form as io and lui/lei: parli.", tags: ["congiuntivo", "grammar", "parlare", "conjugation"], tier: 2 },
    { id: "u20-t2-010", type: "conjugate", prompt: "parlare (congiuntivo presente) – lui/lei", accepted: ["parli"], hint: "Io, tu, and lui/lei share the identical form parli.", tags: ["congiuntivo", "grammar", "parlare", "conjugation"], tier: 2 },
    { id: "u20-t2-011", type: "conjugate", prompt: "parlare (congiuntivo presente) – voi", accepted: ["parliate"], hint: "Voi form for -are verbs: -iate.", tags: ["congiuntivo", "grammar", "parlare", "conjugation"], tier: 2 },
    { id: "u20-t2-012", type: "conjugate", prompt: "essere (congiuntivo presente) – tu", accepted: ["sia"], hint: "Io, tu, and lui/lei share the identical irregular form sia.", tags: ["congiuntivo", "grammar", "essere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-013", type: "conjugate", prompt: "essere (congiuntivo presente) – lui/lei", accepted: ["sia"], hint: "Same irregular singular form as io and tu: sia.", tags: ["congiuntivo", "grammar", "essere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-014", type: "conjugate", prompt: "essere (congiuntivo presente) – voi", accepted: ["siate"], hint: "Voi form of essere: siate.", tags: ["congiuntivo", "grammar", "essere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-015", type: "conjugate", prompt: "avere (congiuntivo presente) – io", accepted: ["abbia"], hint: "Io, tu, and lui/lei share the identical irregular form abbia.", tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-016", type: "conjugate", prompt: "avere (congiuntivo presente) – lui/lei", accepted: ["abbia"], hint: "Same irregular singular form as io and tu: abbia.", tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-017", type: "conjugate", prompt: "avere (congiuntivo presente) – noi", accepted: ["abbiamo"], hint: "The noi form matches the indicativo presente.", tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-018", type: "conjugate", prompt: "avere (congiuntivo presente) – voi", accepted: ["abbiate"], hint: "Voi form of avere: abbiate.", tags: ["congiuntivo", "grammar", "avere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-019", type: "conjugate", prompt: "fare (congiuntivo presente) – lui/lei", accepted: ["faccia"], hint: "Irregular stem facc-; io, tu, and lui/lei share this form.", tags: ["congiuntivo", "grammar", "fare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-020", type: "conjugate", prompt: "fare (congiuntivo presente) – voi", accepted: ["facciate"], hint: "Voi form: facciate, from the irregular stem facc-.", tags: ["congiuntivo", "grammar", "fare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-021", type: "conjugate", prompt: "finire (congiuntivo presente) – tu", accepted: ["finisca"], hint: "Isc-verb: io, tu, and lui/lei share the form finisca.", tags: ["congiuntivo", "grammar", "finire", "conjugation"], tier: 2 },
    { id: "u20-t2-022", type: "conjugate", prompt: "finire (congiuntivo presente) – lui/lei", accepted: ["finisca"], hint: "Same isc- form as io and tu: finisca.", tags: ["congiuntivo", "grammar", "finire", "conjugation"], tier: 2 },
    { id: "u20-t2-023", type: "conjugate", prompt: "finire (congiuntivo presente) – voi", accepted: ["finiate"], hint: "The voi form drops the -isc- infix: finiate.", tags: ["congiuntivo", "grammar", "finire", "conjugation"], tier: 2 },
    { id: "u20-t2-024", type: "conjugate", prompt: "dire (congiuntivo presente) – lui/lei", accepted: ["dica"], hint: "Irregular stem dic-; io, tu, and lui/lei share the form dica.", tags: ["congiuntivo", "grammar", "dire", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-025", type: "conjugate", prompt: "venire (congiuntivo presente) – tu", accepted: ["venga"], hint: "Irregular stem veng-; io, tu, and lui/lei share the form venga.", tags: ["congiuntivo", "grammar", "venire", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-026", type: "conjugate", prompt: "venire (congiuntivo presente) – lui/lei", accepted: ["venga"], hint: "Same irregular singular form as io and tu: venga.", tags: ["congiuntivo", "grammar", "venire", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-027", type: "conjugate", prompt: "venire (congiuntivo presente) – voi", accepted: ["veniate"], hint: "The voi form goes back to the regular stem ven-: veniate.", tags: ["congiuntivo", "grammar", "venire", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-028", type: "conjugate", prompt: "uscire (congiuntivo presente) – voi", accepted: ["usciate"], hint: "The voi form goes back to the regular stem usc-: usciate.", tags: ["congiuntivo", "grammar", "uscire", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-029", type: "conjugate", prompt: "andare (congiuntivo presente) – tu", accepted: ["vada"], hint: "Irregular stem vad-; io, tu, and lui/lei share the form vada.", tags: ["congiuntivo", "grammar", "andare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-030", type: "conjugate", prompt: "andare (congiuntivo presente) – voi", accepted: ["andiate"], hint: "The voi form goes back to the regular stem and-: andiate.", tags: ["congiuntivo", "grammar", "andare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-031", type: "conjugate", prompt: "sapere (congiuntivo presente) – voi", accepted: ["sappiate"], hint: "Irregular stem sapp- + -iate ending for voi.", tags: ["congiuntivo", "grammar", "sapere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-032", type: "conjugate", prompt: "potere (congiuntivo presente) – tu", accepted: ["possa"], hint: "Irregular stem poss-; io, tu, and lui/lei share the form possa.", tags: ["congiuntivo", "grammar", "potere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-033", type: "conjugate", prompt: "potere (congiuntivo presente) – voi", accepted: ["possiate"], hint: "Voi form: possiate, from the irregular stem poss-.", tags: ["congiuntivo", "grammar", "potere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-034", type: "conjugate", prompt: "dovere (congiuntivo presente) – tu", accepted: ["debba"], hint: "Irregular stem debb-; io, tu, and lui/lei share the form debba.", tags: ["congiuntivo", "grammar", "dovere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-035", type: "conjugate", prompt: "dovere (congiuntivo presente) – voi", accepted: ["dobbiate"], hint: "Irregular stem dobb- + -iate ending for voi.", tags: ["congiuntivo", "grammar", "dovere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-036", type: "conjugate", prompt: "dare (congiuntivo presente) – tu", accepted: ["dia"], hint: "Irregular stem d-; io, tu, and lui/lei share the form dia.", tags: ["congiuntivo", "grammar", "dare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-037", type: "conjugate", prompt: "dare (congiuntivo presente) – noi", accepted: ["diamo"], hint: "The noi form matches the indicativo presente: diamo.", tags: ["congiuntivo", "grammar", "dare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-038", type: "conjugate", prompt: "dare (congiuntivo presente) – voi", accepted: ["diate"], hint: "Voi form: diate.", tags: ["congiuntivo", "grammar", "dare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-039", type: "conjugate", prompt: "stare (congiuntivo presente) – tu", accepted: ["stia"], hint: "Irregular stem sti-; io, tu, and lui/lei share the form stia.", tags: ["congiuntivo", "grammar", "stare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-040", type: "conjugate", prompt: "stare (congiuntivo presente) – voi", accepted: ["stiate"], hint: "Voi form: stiate, from the irregular stem sti-.", tags: ["congiuntivo", "grammar", "stare", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-041", type: "conjugate", prompt: "volere (congiuntivo presente) – io", accepted: ["voglia"], hint: "Irregular stem vogli-/vogl-: voglia, voglia, voglia, vogliamo, vogliate, vogliano.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-042", type: "conjugate", prompt: "volere (congiuntivo presente) – tu", accepted: ["voglia"], hint: "Same irregular singular form as io: voglia.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-043", type: "conjugate", prompt: "volere (congiuntivo presente) – lui/lei", accepted: ["voglia"], hint: "All three singular persons share the irregular form voglia.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-044", type: "conjugate", prompt: "volere (congiuntivo presente) – noi", accepted: ["vogliamo"], hint: "The noi form matches the indicativo presente: vogliamo.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-045", type: "conjugate", prompt: "volere (congiuntivo presente) – voi", accepted: ["vogliate"], hint: "Voi form: vogliate, from the irregular stem vogli-.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },
    { id: "u20-t2-046", type: "conjugate", prompt: "volere (congiuntivo presente) – loro", accepted: ["vogliano"], hint: "Loro form: vogliano, from the irregular stem vogli-.", tags: ["congiuntivo", "grammar", "volere", "conjugation", "irregular"], tier: 2 },

    // ── Tier 2 – Grammar (expansion): fill_blank doubt-trigger drills ─────────
    { id: "u20-t2-047", type: "fill_blank", prompt: "Credo che tu ___ (dovere) parlare con lei prima di partire.", accepted: ["debba"], hint: "Credere che always triggers the congiuntivo; dovere → debba for tu.", tags: ["congiuntivo", "grammar", "credo che", "dovere", "fill_blank"], tier: 2 },
    { id: "u20-t2-048", type: "fill_blank", prompt: "Credo che i tuoi amici ___ (volere) organizzare una festa a sorpresa.", accepted: ["vogliano"], hint: "Credere che always triggers the congiuntivo; volere → vogliano for loro.", tags: ["congiuntivo", "grammar", "credo che", "volere", "fill_blank"], tier: 2 },
    { id: "u20-t2-049", type: "fill_blank", prompt: "Credo che il treno ___ (venire) cancellato per lo sciopero.", accepted: ["venga"], hint: "Credere che always triggers the congiuntivo; venire → venga for il treno/lui.", tags: ["congiuntivo", "grammar", "credo che", "venire", "fill_blank"], tier: 2 },
    { id: "u20-t2-050", type: "fill_blank", prompt: "Credo che loro ___ (uscire) presto stasera.", accepted: ["escano"], hint: "Credere che always triggers the congiuntivo; uscire → escano for loro.", tags: ["congiuntivo", "grammar", "credo che", "uscire", "fill_blank"], tier: 2 },
    { id: "u20-t2-051", type: "fill_blank", prompt: "Credo che Marco ___ (sapere) già la risposta.", accepted: ["sappia"], hint: "Credere che always triggers the congiuntivo; sapere → sappia for lui.", tags: ["congiuntivo", "grammar", "credo che", "sapere", "fill_blank"], tier: 2 },
    { id: "u20-t2-052", type: "fill_blank", prompt: "Credo che noi ___ (dare) troppo peso a questo problema.", accepted: ["diamo"], hint: "Credere che always triggers the congiuntivo; dare → diamo for noi, identical to the indicativo.", tags: ["congiuntivo", "grammar", "credo che", "dare", "fill_blank"], tier: 2 },
    { id: "u20-t2-053", type: "fill_blank", prompt: "Credo che tu ___ (stare) meglio dopo la pausa.", accepted: ["stia"], hint: "Credere che always triggers the congiuntivo; stare → stia for tu.", tags: ["congiuntivo", "grammar", "credo che", "stare", "fill_blank"], tier: 2 },
    { id: "u20-t2-054", type: "fill_blank", prompt: "Credo che i ragazzi ___ (finire) i compiti entro stasera.", accepted: ["finiscano"], hint: "Credere che always triggers the congiuntivo; finire → finiscano for loro.", tags: ["congiuntivo", "grammar", "credo che", "finire", "fill_blank"], tier: 2 },
    { id: "u20-t2-055", type: "fill_blank", prompt: "Penso che lei ___ (dire) la verità, anche se sembra strano.", accepted: ["dica"], hint: "Pensare che always triggers the congiuntivo; dire → dica for lei.", tags: ["congiuntivo", "grammar", "penso che", "dire", "fill_blank"], tier: 2 },
    { id: "u20-t2-056", type: "fill_blank", prompt: "Penso che voi ___ (potere) risolvere il problema senza il suo aiuto.", accepted: ["possiate"], hint: "Pensare che always triggers the congiuntivo; potere → possiate for voi.", tags: ["congiuntivo", "grammar", "penso che", "potere", "fill_blank"], tier: 2 },
    { id: "u20-t2-057", type: "fill_blank", prompt: "Penso che il capo ___ (fare) troppe promesse senza mantenerle.", accepted: ["faccia"], hint: "Pensare che always triggers the congiuntivo; fare → faccia for lui.", tags: ["congiuntivo", "grammar", "penso che", "fare", "fill_blank"], tier: 2 },
    { id: "u20-t2-058", type: "fill_blank", prompt: "Penso che loro ___ (andare) in vacanza la settimana prossima.", accepted: ["vadano"], hint: "Pensare che always triggers the congiuntivo; andare → vadano for loro.", tags: ["congiuntivo", "grammar", "penso che", "andare", "fill_blank"], tier: 2 },
    { id: "u20-t2-059", type: "fill_blank", prompt: "Penso che tu ___ (dovere) riposare un po' di più.", accepted: ["debba"], hint: "Pensare che always triggers the congiuntivo; dovere → debba for tu.", tags: ["congiuntivo", "grammar", "penso che", "dovere", "fill_blank"], tier: 2 },
    { id: "u20-t2-060", type: "fill_blank", prompt: "Penso che Giulia ___ (volere) cambiare lavoro presto.", accepted: ["voglia"], hint: "Pensare che always triggers the congiuntivo; volere → voglia for lei.", tags: ["congiuntivo", "grammar", "penso che", "volere", "fill_blank"], tier: 2 },
    { id: "u20-t2-061", type: "fill_blank", prompt: "Penso che i vicini ___ (uscire) ogni sera senza dircelo.", accepted: ["escano"], hint: "Pensare che always triggers the congiuntivo; uscire → escano for loro.", tags: ["congiuntivo", "grammar", "penso che", "uscire", "fill_blank"], tier: 2 },
    { id: "u20-t2-062", type: "fill_blank", prompt: "Penso che questo progetto ___ (venire) approvato dal direttore.", accepted: ["venga"], hint: "Pensare che always triggers the congiuntivo; venire → venga for il progetto/lui.", tags: ["congiuntivo", "grammar", "penso che", "venire", "fill_blank"], tier: 2 },
    { id: "u20-t2-063", type: "fill_blank", prompt: "Mi sembra che tu ___ (sapere) più di quello che dici.", accepted: ["sappia"], hint: "Mi sembra che always triggers the congiuntivo; sapere → sappia for tu.", tags: ["congiuntivo", "grammar", "mi sembra che", "sapere", "fill_blank"], tier: 2 },
    { id: "u20-t2-064", type: "fill_blank", prompt: "Mi sembra che i miei colleghi ___ (fare) del loro meglio nonostante tutto.", accepted: ["facciano"], hint: "Mi sembra che always triggers the congiuntivo; fare → facciano for loro.", tags: ["congiuntivo", "grammar", "mi sembra che", "fare", "fill_blank"], tier: 2 },
    { id: "u20-t2-065", type: "fill_blank", prompt: "Mi sembra che lei ___ (stare) molto meglio questa settimana.", accepted: ["stia"], hint: "Mi sembra che always triggers the congiuntivo; stare → stia for lei.", tags: ["congiuntivo", "grammar", "mi sembra che", "stare", "fill_blank"], tier: 2 },
    { id: "u20-t2-066", type: "fill_blank", prompt: "Mi sembra che loro ___ (dovere) ancora decidere la data del viaggio.", accepted: ["debbano"], hint: "Mi sembra che always triggers the congiuntivo; dovere → debbano for loro.", tags: ["congiuntivo", "grammar", "mi sembra che", "dovere", "fill_blank"], tier: 2 },
    { id: "u20-t2-067", type: "fill_blank", prompt: "Mi sembra che tu ___ (dare) troppa importanza a un piccolo errore.", accepted: ["dia"], hint: "Mi sembra che always triggers the congiuntivo; dare → dia for tu.", tags: ["congiuntivo", "grammar", "mi sembra che", "dare", "fill_blank"], tier: 2 },
    { id: "u20-t2-068", type: "fill_blank", prompt: "Mi sembra che Marco ___ (venire) sempre in ritardo apposta.", accepted: ["venga"], hint: "Mi sembra che always triggers the congiuntivo; venire → venga for lui.", tags: ["congiuntivo", "grammar", "mi sembra che", "venire", "fill_blank"], tier: 2 },
    { id: "u20-t2-069", type: "fill_blank", prompt: "Mi sembra che i ragazzi ___ (finire) prima del previsto oggi.", accepted: ["finiscano"], hint: "Mi sembra che always triggers the congiuntivo; finire → finiscano for loro.", tags: ["congiuntivo", "grammar", "mi sembra che", "finire", "fill_blank"], tier: 2 },
    { id: "u20-t2-070", type: "fill_blank", prompt: "Mi sembra che voi non ___ (volere) ammettere lo sbaglio.", accepted: ["vogliate"], hint: "Mi sembra che always triggers the congiuntivo; volere → vogliate for voi.", tags: ["congiuntivo", "grammar", "mi sembra che", "volere", "fill_blank"], tier: 2 },
    { id: "u20-t2-071", type: "fill_blank", prompt: "Spero che tu ___ (potere) venire alla cerimonia sabato.", accepted: ["possa"], hint: "Sperare che always triggers the congiuntivo; potere → possa for tu.", tags: ["congiuntivo", "grammar", "spero che", "potere", "fill_blank"], tier: 2 },
    { id: "u20-t2-072", type: "fill_blank", prompt: "Spero che loro ___ (dire) finalmente la verità su quello che è successo.", accepted: ["dicano"], hint: "Sperare che always triggers the congiuntivo; dire → dicano for loro.", tags: ["congiuntivo", "grammar", "spero che", "dire", "fill_blank"], tier: 2 },
    { id: "u20-t2-073", type: "fill_blank", prompt: "Spero che i bambini ___ (stare) tranquilli durante il viaggio lungo.", accepted: ["stiano"], hint: "Sperare che always triggers the congiuntivo; stare → stiano for loro.", tags: ["congiuntivo", "grammar", "spero che", "stare", "fill_blank"], tier: 2 },
    { id: "u20-t2-074", type: "fill_blank", prompt: "Spero che voi ___ (uscire) presto da questa situazione difficile.", accepted: ["usciate"], hint: "Sperare che always triggers the congiuntivo; uscire → usciate for voi.", tags: ["congiuntivo", "grammar", "spero che", "uscire", "fill_blank"], tier: 2 },
    { id: "u20-t2-075", type: "fill_blank", prompt: "Spero che lei ___ (finire) di preoccuparsi per questo esame.", accepted: ["finisca"], hint: "Sperare che always triggers the congiuntivo; finire → finisca for lei.", tags: ["congiuntivo", "grammar", "spero che", "finire", "fill_blank"], tier: 2 },
    { id: "u20-t2-076", type: "fill_blank", prompt: "Spero che il progetto ___ (andare) avanti senza altri ritardi.", accepted: ["vada"], hint: "Sperare che always triggers the congiuntivo; andare → vada for il progetto/lui.", tags: ["congiuntivo", "grammar", "spero che", "andare", "fill_blank"], tier: 2 },
    { id: "u20-t2-077", type: "fill_blank", prompt: "Spero che tu mi ___ (dare) un'altra possibilità.", accepted: ["dia"], hint: "Sperare che always triggers the congiuntivo; dare → dia for tu.", tags: ["congiuntivo", "grammar", "spero che", "dare", "fill_blank"], tier: 2 },
    { id: "u20-t2-078", type: "fill_blank", prompt: "Spero che noi non ___ (dovere) aspettare ancora molto per la risposta.", accepted: ["dobbiamo"], hint: "Sperare che always triggers the congiuntivo; dovere → dobbiamo for noi, identical to the indicativo.", tags: ["congiuntivo", "grammar", "spero che", "dovere", "fill_blank"], tier: 2 },
    { id: "u20-t2-079", type: "fill_blank", prompt: "Non sono sicuro che lui ___ (sapere) davvero cosa fare in questa situazione.", accepted: ["sappia"], hint: "Non essere sicuro/a che always triggers the congiuntivo; sapere → sappia for lui.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "sapere", "fill_blank"], tier: 2 },
    { id: "u20-t2-080", type: "fill_blank", prompt: "Non sono sicura che i miei genitori ___ (volere) trasferirsi in un'altra città.", accepted: ["vogliano"], hint: "Non essere sicuro/a che always triggers the congiuntivo; volere → vogliano for loro.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "volere", "fill_blank"], tier: 2 },
    { id: "u20-t2-081", type: "fill_blank", prompt: "Non sono sicuro che tu ___ (potere) finire tutto entro stasera.", accepted: ["possa"], hint: "Non essere sicuro/a che always triggers the congiuntivo; potere → possa for tu.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "potere", "fill_blank"], tier: 2 },
    { id: "u20-t2-082", type: "fill_blank", prompt: "Non sono sicura che loro ___ (venire) puntuali come al solito.", accepted: ["vengano"], hint: "Non essere sicuro/a che always triggers the congiuntivo; venire → vengano for loro.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "venire", "fill_blank"], tier: 2 },
    { id: "u20-t2-083", type: "fill_blank", prompt: "Non sono sicuro che questo piano ___ (andare) come previsto.", accepted: ["vada"], hint: "Non essere sicuro/a che always triggers the congiuntivo; andare → vada for il piano/lui.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "andare", "fill_blank"], tier: 2 },
    { id: "u20-t2-084", type: "fill_blank", prompt: "Non sono sicura che i colleghi ___ (fare) abbastanza per risolvere il problema.", accepted: ["facciano"], hint: "Non essere sicuro/a che always triggers the congiuntivo; fare → facciano for loro.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "fare", "fill_blank"], tier: 2 },
    { id: "u20-t2-085", type: "fill_blank", prompt: "Non sono sicuro che voi ___ (dovere) preoccuparvi così tanto.", accepted: ["dobbiate"], hint: "Non essere sicuro/a che always triggers the congiuntivo; dovere → dobbiate for voi.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "dovere", "fill_blank"], tier: 2 },
    { id: "u20-t2-086", type: "fill_blank", prompt: "Non sono sicura che lei ___ (dire) sempre quello che pensa davvero.", accepted: ["dica"], hint: "Non essere sicuro/a che always triggers the congiuntivo; dire → dica for lei.", tags: ["congiuntivo", "grammar", "non sono sicuro che", "dire", "fill_blank"], tier: 2 },

    // ── Tier 3 – Chunks (expansion): dubitare che / sospettare che + doubt vocab ─
    { id: "u20-t3-007", type: "produce", prompt: "I doubt that he is telling the truth.", accepted: ["Dubito che dica la verità."], hint: "Dubitare che always triggers the congiuntivo; dire → dica for lui. Dubitare che is one of the strongest doubt triggers.", tags: ["congiuntivo", "chunk", "dubitare che", "dire"], tier: 3 },
    { id: "u20-t3-008", type: "produce", prompt: "The contractor promised the kitchen would be ready by Friday, but I doubt they can finish on time.", accepted: ["L'impresario ha promesso che la cucina sarebbe stata pronta per venerdì, ma dubito che possano finire in tempo."], hint: "Dubitare che always triggers the congiuntivo; potere → possano for loro (gli operai).", tags: ["congiuntivo", "chunk", "dubitare che", "potere"], tier: 3 },
    { id: "u20-t3-009", type: "produce", prompt: "After the argument at the wedding, I doubt she wants to come to the reunion.", accepted: ["Dopo il litigio al matrimonio, dubito che lei voglia venire alla rimpatriata."], hint: "Dubitare che always triggers the congiuntivo; volere → voglia for lei.", tags: ["congiuntivo", "chunk", "dubitare che", "volere"], tier: 3 },
    { id: "u20-t3-010", type: "produce", prompt: "Given how thin the budget is, we doubt this plan will work out.", accepted: ["Visto quanto è risicato il budget, dubitiamo che questo piano vada bene."], hint: "Dubitare che always triggers the congiuntivo; andare → vada for il piano/lui.", tags: ["congiuntivo", "chunk", "dubitare che", "andare"], tier: 3 },
    { id: "u20-t3-011", type: "produce", prompt: "I suspect that he already knows the answer.", accepted: ["Sospetto che lui sappia già la risposta."], hint: "Sospettare che always triggers the congiuntivo; sapere → sappia for lui.", tags: ["congiuntivo", "chunk", "sospettare che", "sapere"], tier: 3 },
    { id: "u20-t3-012", type: "produce", prompt: "Ever since the inspection was postponed twice, I suspect they are hiding something.", accepted: ["Da quando l'ispezione è stata rimandata due volte, sospetto che nascondano qualcosa."], hint: "Sospettare che always triggers the congiuntivo; nascondere → nascondano for loro.", tags: ["congiuntivo", "chunk", "sospettare che", "nascondere"], tier: 3 },
    { id: "u20-t3-013", type: "produce", prompt: "After hearing two different excuses in a single day, she suspects her colleague is lying.", accepted: ["Dopo aver sentito due scuse diverse in un solo giorno, lei sospetta che il suo collega menta."], hint: "Sospettare che always triggers the congiuntivo; mentire → menta for il collega/lui.", tags: ["congiuntivo", "chunk", "sospettare che", "mentire"], tier: 3 },
    { id: "u20-t3-014", type: "produce", prompt: "Since the numbers don't match last year's report, we suspect the results are wrong.", accepted: ["Dato che i numeri non corrispondono al rapporto dell'anno scorso, sospettiamo che i risultati siano sbagliati."], hint: "Sospettare che always triggers the congiuntivo; essere → siano for i risultati/loro.", tags: ["congiuntivo", "chunk", "sospettare che", "essere"], tier: 3 },
    { id: "u20-t3-015", type: "produce", prompt: "He is doubtful that the plan will succeed.", accepted: ["Lui è dubbioso che il piano abbia successo."], hint: "Essere dubbioso che always triggers the congiuntivo; avere → abbia for il piano/lui.", tags: ["congiuntivo", "chunk", "dubbioso", "avere"], tier: 3 },
    { id: "u20-t3-016", type: "produce", prompt: "I am uncertain that he understands the problem.", accepted: ["Sono incerto che lui capisca il problema.", "Sono incerta che lui capisca il problema."], hint: "Essere incerto/a che always triggers the congiuntivo; capire → capisca for lui.", tags: ["congiuntivo", "chunk", "incerto", "capire"], tier: 3 },
    { id: "u20-t3-017", type: "produce", prompt: "She is perplexed that nobody has answered.", accepted: ["È perplessa che nessuno abbia risposto."], hint: "Essere perplesso/a che always triggers the congiuntivo passato (past subjunctive) here; avere → abbia risposto for nessuno.", tags: ["congiuntivo", "chunk", "perplesso"], tier: 3 },
    { id: "u20-t3-018", type: "produce", prompt: "We are perplexed that the store is still closed.", accepted: ["Siamo perplessi che il negozio sia ancora chiuso."], hint: "Essere perplesso/a che always triggers the congiuntivo; essere → sia for il negozio/lui.", tags: ["congiuntivo", "chunk", "perplesso", "essere"], tier: 3 },
    { id: "u20-t3-019", type: "produce", prompt: "His uncertainty makes me nervous.", accepted: ["La sua incertezza mi rende nervoso.", "La sua incertezza mi rende nervosa."], hint: "L'incertezza used as a plain noun, outside a congiuntivo trigger.", tags: ["doubt", "chunk", "incertezza", "collocation"], tier: 3 },
    { id: "u20-t3-020", type: "produce", prompt: "Her perplexity was obvious during the meeting.", accepted: ["La sua perplessità era evidente durante la riunione."], hint: "La perplessità used as a plain noun, outside a congiuntivo trigger.", tags: ["doubt", "chunk", "perplessità", "collocation"], tier: 3 },
    { id: "u20-t3-021", type: "produce", prompt: "I have a suspicion that he wants to leave.", accepted: ["Ho il sospetto che lui voglia andarsene."], hint: "Avere il sospetto che always triggers the congiuntivo; volere → voglia for lui.", tags: ["congiuntivo", "chunk", "sospetto", "volere"], tier: 3 },
    { id: "u20-t3-022", type: "produce", prompt: "Doubting yourself all the time is exhausting.", accepted: ["Dubitare di se stessi in continuazione è stancante."], hint: "Dubitare di + reflexive pronoun = to doubt oneself; here used as a bare infinitive, no congiuntivo.", tags: ["doubt", "chunk", "dubitare", "collocation"], tier: 3 },

    // ── Tier 3 – Chunks (expansion): more doubt-trigger sentences, all verbs ──
    { id: "u20-t3-023", type: "produce", prompt: "My cousin has missed every family dinner for two months because of his night shifts at the hospital, so I think he wants to change jobs.", accepted: ["Mio cugino ha perso ogni cena di famiglia per due mesi a causa dei turni di notte in ospedale, quindi credo che lui voglia cambiare lavoro."], hint: "Credere che always triggers the congiuntivo; volere → voglia for lui.", tags: ["congiuntivo", "chunk", "credo che", "volere"], tier: 3 },
    { id: "u20-t3-024", type: "produce", prompt: "The neighbors have avoided our eyes ever since the break-in came up at the building meeting, so I think they know the truth.", accepted: ["I vicini evitano il nostro sguardo da quando il furto è stato menzionato alla riunione di condominio, quindi credo che loro sappiano la verità."], hint: "Credere che always triggers the congiuntivo; sapere → sappiano for loro.", tags: ["congiuntivo", "chunk", "credo che", "sapere"], tier: 3 },
    { id: "u20-t3-025", type: "produce", prompt: "You've been coughing all week and still going to the gym — I think you should rest a little.", accepted: ["Tossisci da una settimana e vai ancora in palestra: credo che tu debba riposare un po'."], hint: "Credere che always triggers the congiuntivo; dovere → debba for tu.", tags: ["congiuntivo", "chunk", "credo che", "dovere"], tier: 3 },
    { id: "u20-t3-026", type: "produce", prompt: "With five items still on the agenda at six o'clock, I think the meeting will finish late.", accepted: ["Con cinque punti ancora all'ordine del giorno alle sei, credo che la riunione finisca tardi."], hint: "Credere che always triggers the congiuntivo; finire → finisca for la riunione/lei.", tags: ["congiuntivo", "chunk", "credo che", "finire"], tier: 3 },
    { id: "u20-t3-027", type: "produce", prompt: "Even with the exam results due any minute, I think she is staying calm.", accepted: ["Anche con i risultati dell'esame in arrivo da un momento all'altro, credo che lei stia calma."], hint: "Credere che always triggers the congiuntivo; stare → stia for lei.", tags: ["congiuntivo", "chunk", "credo che", "stare"], tier: 3 },
    { id: "u20-t3-028", type: "produce", prompt: "Now that the exams are finally over, I think they will go out tonight.", accepted: ["Ora che gli esami sono finalmente finiti, credo che escano stasera."], hint: "Credere che always triggers the congiuntivo; uscire → escano for loro.", tags: ["congiuntivo", "chunk", "credo che", "uscire"], tier: 3 },
    { id: "u20-t3-029", type: "produce", prompt: "The witness has repeated the exact same details in every police interview this week, so I think he is telling the truth about the accident.", accepted: ["Il testimone ha ripetuto esattamente gli stessi dettagli in ogni interrogatorio della polizia questa settimana, quindi penso che dica la verità sull'incidente."], hint: "Pensare che always triggers the congiuntivo; dire → dica for lui.", tags: ["congiuntivo", "chunk", "penso che", "dire"], tier: 3 },
    { id: "u20-t3-030", type: "produce", prompt: "The client signed the final contract yesterday after six months of revisions, so I think this project will move forward.", accepted: ["Il cliente ha firmato il contratto definitivo ieri dopo sei mesi di revisioni, quindi penso che questo progetto vada avanti."], hint: "Pensare che always triggers the congiuntivo; andare → vada for il progetto/lui.", tags: ["congiuntivo", "chunk", "penso che", "andare"], tier: 3 },
    { id: "u20-t3-031", type: "produce", prompt: "After how you handled last month's crisis without any help, I think you can handle this alone.", accepted: ["Dopo come hai gestito la crisi del mese scorso senza alcun aiuto, penso che tu possa gestire questo da solo.", "Dopo come hai gestito la crisi del mese scorso senza alcun aiuto, penso che tu possa gestire questo da sola."], hint: "Pensare che always triggers the congiuntivo; potere → possa for tu.", tags: ["congiuntivo", "chunk", "penso che", "potere"], tier: 3 },
    { id: "u20-t3-032", type: "produce", prompt: "Even though the team lost three players to injury, I think they are doing their best.", accepted: ["Anche se la squadra ha perso tre giocatori per infortunio, penso che facciano del loro meglio."], hint: "Pensare che always triggers the congiuntivo; fare → facciano for loro.", tags: ["congiuntivo", "chunk", "penso che", "fare"], tier: 3 },
    { id: "u20-t3-033", type: "produce", prompt: "Since he keeps calling and hanging up before I answer, I think he wants to apologize.", accepted: ["Dato che continua a chiamare e riattaccare prima che io risponda, penso che lui voglia scusarsi."], hint: "Pensare che always triggers the congiuntivo; volere → voglia for lui.", tags: ["congiuntivo", "chunk", "penso che", "volere"], tier: 3 },
    { id: "u20-t3-034", type: "produce", prompt: "Now that she and her ex are on speaking terms again, I think she will come to the party.", accepted: ["Ora che lei e il suo ex si parlano di nuovo, penso che venga alla festa."], hint: "Pensare che always triggers the congiuntivo; venire → venga for lei.", tags: ["congiuntivo", "chunk", "penso che", "venire"], tier: 3 },
    { id: "u20-t3-035", type: "produce", prompt: "It seems to me that we should discuss this calmly.", accepted: ["Mi sembra che dobbiamo discuterne con calma."], hint: "Mi sembra che always triggers the congiuntivo; dovere → dobbiamo for noi, identical to the indicativo.", tags: ["congiuntivo", "chunk", "mi sembra che", "dovere"], tier: 3 },
    { id: "u20-t3-036", type: "produce", prompt: "It seems to me that he wants to help us.", accepted: ["Mi sembra che lui voglia aiutarci."], hint: "Mi sembra che always triggers the congiuntivo; volere → voglia for lui.", tags: ["congiuntivo", "chunk", "mi sembra che", "volere"], tier: 3 },
    { id: "u20-t3-037", type: "produce", prompt: "Given that the tickets say the show starts at eleven, it seems to me that the film finishes very late.", accepted: ["Visto che i biglietti dicono che lo spettacolo inizia alle undici, mi sembra che il film finisca molto tardi."], hint: "Mi sembra che always triggers the congiuntivo; finire → finisca for il film/lui.", tags: ["congiuntivo", "chunk", "mi sembra che", "finire"], tier: 3 },
    { id: "u20-t3-038", type: "produce", prompt: "Judging by how tired my roommates look every morning, it seems to me that they go out too much during the week.", accepted: ["A giudicare da quanto sembrano stanchi i miei coinquilini ogni mattina, mi sembra che escano troppo durante la settimana."], hint: "Mi sembra che always triggers the congiuntivo; uscire → escano for loro.", tags: ["congiuntivo", "chunk", "mi sembra che", "uscire"], tier: 3 },
    { id: "u20-t3-039", type: "produce", prompt: "After seeing how the pilot program performed in the smaller branch, it seems to me that this idea can work.", accepted: ["Dopo aver visto come è andato il progetto pilota nella filiale più piccola, mi sembra che questa idea possa funzionare."], hint: "Mi sembra che always triggers the congiuntivo; potere → possa for l'idea/lei.", tags: ["congiuntivo", "chunk", "mi sembra che", "potere"], tier: 3 },
    { id: "u20-t3-040", type: "produce", prompt: "She rewrote the email five times over a single comma, so it seems to me that she gives too much importance to details.", accepted: ["Ha riscritto l'email cinque volte per una sola virgola, quindi mi sembra che dia troppa importanza ai dettagli."], hint: "Mi sembra che always triggers the congiuntivo; dare → dia for lei.", tags: ["congiuntivo", "chunk", "mi sembra che", "dare"], tier: 3 },
    { id: "u20-t3-041", type: "produce", prompt: "The landlord gave us until the end of the month to fix the plumbing or lose the lease, so I hope you can find a solution soon.", accepted: ["Il padrone di casa ci ha dato fino alla fine del mese per risolvere il problema idraulico o perdere il contratto d'affitto, quindi spero che tu possa trovare presto una soluzione."], hint: "Sperare che always triggers the congiuntivo; potere → possa for tu.", tags: ["congiuntivo", "chunk", "spero che", "potere"], tier: 3 },
    { id: "u20-t3-042", type: "produce", prompt: "The board has postponed this vote three times already this year, so I hope they say yes to the proposal this time.", accepted: ["Il consiglio ha rinviato questo voto già tre volte quest'anno, quindi spero che dicano di sì alla proposta questa volta."], hint: "Sperare che always triggers the congiuntivo; dire → dicano for loro.", tags: ["congiuntivo", "chunk", "spero che", "dire"], tier: 3 },
    { id: "u20-t3-043", type: "produce", prompt: "With the factory already running below half capacity, I hope the situation goes better next month.", accepted: ["Con la fabbrica che gira già a meno della metà della capacità, spero che la situazione vada meglio il mese prossimo."], hint: "Sperare che always triggers the congiuntivo; andare → vada for la situazione/lei.", tags: ["congiuntivo", "chunk", "spero che", "andare"], tier: 3 },
    { id: "u20-t3-044", type: "produce", prompt: "Since two engineers just quit in the middle of the sprint, I hope we finish this project without problems.", accepted: ["Dato che due ingegneri se ne sono appena andati a metà dello sprint, spero che finiamo questo progetto senza problemi."], hint: "Sperare che always triggers the congiuntivo; finire → finiamo for noi, identical to the indicativo.", tags: ["congiuntivo", "chunk", "spero che", "finire"], tier: 3 },
    { id: "u20-t3-045", type: "produce", prompt: "He froze during his last interview, so I hope he stays calm this time.", accepted: ["Si è bloccato durante l'ultimo colloquio, quindi spero che stia calmo questa volta."], hint: "Sperare che always triggers the congiuntivo; stare → stia for lui.", tags: ["congiuntivo", "chunk", "spero che", "stare"], tier: 3 },
    { id: "u20-t3-046", type: "produce", prompt: "The clinic already has three people ahead of you, so I hope you don't have to wait too long.", accepted: ["L'ambulatorio ha già tre persone davanti a te, quindi spero che tu non debba aspettare troppo."], hint: "Sperare che always triggers the congiuntivo; dovere → debba for tu.", tags: ["congiuntivo", "chunk", "spero che", "dovere"], tier: 3 },
    { id: "u20-t3-047", type: "produce", prompt: "He canceled plans with us twice this month without much explanation, so I am not sure he wants to come with us this weekend.", accepted: ["Ha annullato i piani con noi due volte questo mese senza molte spiegazioni, quindi non sono sicuro che lui voglia venire con noi questo fine settimana."], hint: "Non essere sicuro/a che always triggers the congiuntivo; volere → voglia for lui.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "volere"], tier: 3 },
    { id: "u20-t3-048", type: "produce", prompt: "The two witnesses gave completely different versions of what happened at the intersection, so I am not sure they know the whole story.", accepted: ["I due testimoni hanno dato versioni completamente diverse di quello che è successo all'incrocio, quindi non sono sicura che sappiano tutta la storia."], hint: "Non essere sicuro/a che always triggers the congiuntivo; sapere → sappiano for loro.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "sapere"], tier: 3 },
    { id: "u20-t3-049", type: "produce", prompt: "With only two investors on board out of the five we need, I am not sure this plan can succeed.", accepted: ["Con solo due investitori a bordo dei cinque che ci servono, non sono sicuro che questo piano possa riuscire."], hint: "Non essere sicuro/a che always triggers the congiuntivo; potere → possa for il piano/lui.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "potere"], tier: 3 },
    { id: "u20-t3-050", type: "produce", prompt: "She's already rewritten the introduction three times this afternoon, so I am not sure she finishes the report today.", accepted: ["Ha già riscritto l'introduzione tre volte questo pomeriggio, quindi non sono sicura che finisca la relazione oggi."], hint: "Non essere sicuro/a che always triggers the congiuntivo; finire → finisca for lei.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "finire"], tier: 3 },
    { id: "u20-t3-051", type: "produce", prompt: "The forecast shows only light rain for Saturday, so I am not sure we have to change our plans.", accepted: ["Le previsioni indicano solo pioggia leggera per sabato, quindi non sono sicuro che dobbiamo cambiare i nostri piani."], hint: "Non essere sicuro/a che always triggers the congiuntivo; dovere → dobbiamo for noi, identical to the indicativo.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "dovere"], tier: 3 },
    { id: "u20-t3-052", type: "produce", prompt: "Their car has been parked outside every Friday night this month, so I am not sure they go out on Fridays.", accepted: ["La loro macchina è rimasta parcheggiata fuori ogni venerdì sera questo mese, quindi non sono sicura che escano il venerdì."], hint: "Non essere sicuro/a che always triggers the congiuntivo; uscire → escano for loro.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "uscire"], tier: 3 },

    // ── Tier 3 – Chunks (expansion): doubt collocations ───────────────────────
    { id: "u20-t3-053", type: "produce", prompt: "to cast doubt on something", accepted: ["mettere in dubbio qualcosa"], hint: "Mettere in dubbio = to question, to cast doubt on.", tags: ["collocation", "dubbio"], tier: 3 },
    { id: "u20-t3-054", type: "produce", prompt: "to have doubts about a decision", accepted: ["avere dei dubbi su una decisione"], hint: "Avere dei dubbi su + noun = to have doubts about.", tags: ["collocation", "dubbio"], tier: 3 },
    { id: "u20-t3-055", type: "produce", prompt: "without a shadow of a doubt", accepted: ["senza ombra di dubbio"], hint: "A fixed idiomatic expression built on il dubbio.", tags: ["collocation", "dubbio"], tier: 3 },
    { id: "u20-t3-056", type: "produce", prompt: "to raise a suspicion", accepted: ["sollevare un sospetto"], hint: "Sollevare + noun = to raise/bring up.", tags: ["collocation", "sospetto"], tier: 3 },
    { id: "u20-t3-057", type: "produce", prompt: "to live in uncertainty", accepted: ["vivere nell'incertezza"], hint: "Vivere in/nell' + noun = to live in (a state).", tags: ["collocation", "incertezza"], tier: 3 },
    { id: "u20-t3-058", type: "produce", prompt: "a look of perplexity", accepted: ["uno sguardo di perplessità"], hint: "Uno sguardo di + noun = a look of.", tags: ["collocation", "perplessità"], tier: 3 },
    { id: "u20-t3-059", type: "produce", prompt: "to doubt everything", accepted: ["dubitare di tutto"], hint: "Dubitare di + noun/pronoun = to doubt (something/someone).", tags: ["collocation", "dubitare"], tier: 3 },
    { id: "u20-t3-060", type: "produce", prompt: "a doubtful expression", accepted: ["un'espressione dubbiosa"], hint: "Dubbioso/a used as a plain adjective, outside a congiuntivo trigger.", tags: ["collocation", "dubbioso"], tier: 3 },

    // ── Tier 3 – Chunks (expansion): mixed essere/avere in doubt framing ─────
    { id: "u20-t3-061", type: "produce", prompt: "I doubt that you understand how serious the situation is.", accepted: ["Dubito che tu capisca quanto sia grave la situazione."], hint: "Dubitare che always triggers the congiuntivo; capire → capisca for tu, essere → sia for la situazione/lei.", tags: ["congiuntivo", "chunk", "dubitare che", "essere"], tier: 3 },
    { id: "u20-t3-062", type: "produce", prompt: "We suspect that the numbers are not correct.", accepted: ["Sospettiamo che i numeri non siano corretti."], hint: "Sospettare che always triggers the congiuntivo; essere → siano for i numeri/loro.", tags: ["congiuntivo", "chunk", "sospettare che", "essere"], tier: 3 },
    { id: "u20-t3-063", type: "produce", prompt: "I still have two meetings and a deadline before six o'clock, so I am not sure I have enough time today to finish this.", accepted: ["Ho ancora due riunioni e una scadenza prima delle sei, quindi non sono sicuro che io abbia abbastanza tempo oggi per finire questo.", "Ho ancora due riunioni e una scadenza prima delle sei, quindi non sono sicura che io abbia abbastanza tempo oggi per finire questo."], hint: "Non essere sicuro/a che always triggers the congiuntivo; avere → abbia for io.", tags: ["congiuntivo", "chunk", "non sono sicuro che", "avere"], tier: 3 },
    { id: "u20-t3-064", type: "produce", prompt: "It seems to me that you are more worried than you say.", accepted: ["Mi sembra che tu sia più preoccupato di quanto dici.", "Mi sembra che tu sia più preoccupata di quanto dici."], hint: "Mi sembra che always triggers the congiuntivo; essere → sia for tu.", tags: ["congiuntivo", "chunk", "mi sembra che", "essere"], tier: 3 },
    { id: "u20-t3-065", type: "produce", prompt: "We still haven't heard back from the lab about the test results, so I think we have enough reasons to wait before deciding.", accepted: ["Non abbiamo ancora ricevuto risposta dal laboratorio sui risultati degli esami, quindi penso che abbiamo abbastanza motivi per aspettare prima di decidere."], hint: "Pensare che always triggers the congiuntivo; avere → abbiamo for noi, identical to the indicativo.", tags: ["congiuntivo", "chunk", "penso che", "avere"], tier: 3 },
    { id: "u20-t3-066", type: "produce", prompt: "You've been the only one insisting the numbers don't add up, so I hope you are right about this.", accepted: ["Sei stato l'unico a insistere che i numeri non tornano, quindi spero che tu abbia ragione su questo.", "Sei stata l'unica a insistere che i numeri non tornano, quindi spero che tu abbia ragione su questo."], hint: "Sperare che always triggers the congiuntivo; avere → abbia for tu.", tags: ["congiuntivo", "chunk", "spero che", "avere"], tier: 3 },
    { id: "u20-t3-067", type: "produce", prompt: "To suspect is not the same as to know.", accepted: ["Sospettare non è la stessa cosa che sapere."], hint: "Sospettare used as a bare infinitive subject, outside a congiuntivo trigger.", tags: ["doubt", "chunk", "sospettare", "collocation"], tier: 3 },
    { id: "u20-t3-068", type: "produce", prompt: "He seemed perplexed by the question.", accepted: ["Sembrava perplesso dalla domanda."], hint: "Perplesso as a predicate adjective, masculine singular.", tags: ["doubt", "chunk", "perplesso", "collocation"], tier: 3 },

    // ── Tier 4 – Passages (expansion): passage_cloze, doubt triggers ──────────
    {
      id: "u20-t4-006",
      type: "passage_cloze",
      prompt:
        "Luca aspetta una lettera importante dall'università da più di due settimane. Crede che la risposta ___ finalmente questa settimana, perché la segreteria gli ha detto che le decisioni sono quasi pronte. Ogni giorno controlla la cassetta della posta con un misto di speranza e ansia. I suoi genitori cercano di calmarlo, ricordandogli che la pazienza è importante in questi casi.",
      accepted: ["venga"],
      hint: "Credere che always triggers the congiuntivo; venire → venga for la risposta/lei.",
      tags: ["congiuntivo", "passage_cloze", "credo che", "venire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-025", "u20-t2-026"],
    },
    {
      id: "u20-t4-007",
      type: "passage_cloze",
      prompt:
        "Anna organizza una piccola festa a sorpresa per il compleanno di sua madre. Penso che noi ___ preparare tutto senza che lei se ne accorga, se ci muoviamo con attenzione nei prossimi giorni. Suo fratello si occupa delle decorazioni, mentre Anna prepara la torta preferita della madre. Sperano davvero che la sorpresa funzioni e che la madre sia felice di questo gesto.",
      accepted: ["possiamo"],
      hint: "Pensare che always triggers the congiuntivo; potere → possiamo for noi, identical to the indicativo.",
      tags: ["congiuntivo", "passage_cloze", "penso che", "potere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-032", "u20-t2-033"],
    },
    {
      id: "u20-t4-008",
      type: "passage_cloze",
      prompt:
        "Da qualche mese Marco lavora in un nuovo ufficio pieno di persone motivate. Mi sembra che i suoi colleghi ___ davvero del loro meglio per completare i progetti in tempo, anche quando le scadenze sono strette. Marco apprezza molto questo ambiente di lavoro e si sente ispirato ogni giorno. Spera di continuare a imparare da loro e di dare presto il proprio contributo importante.",
      accepted: ["facciano"],
      hint: "Mi sembra che always triggers the congiuntivo; fare → facciano for i colleghi/loro.",
      tags: ["congiuntivo", "passage_cloze", "mi sembra che", "fare", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-019", "u20-t2-020"],
    },
    {
      id: "u20-t4-009",
      type: "passage_cloze",
      prompt:
        "Il progetto di ristrutturazione della vecchia scuola del paese è iniziato sei mesi fa. Spero che gli operai ___ i lavori prima dell'inizio del nuovo anno scolastico, così i bambini potranno tornare in classe. Il sindaco controlla i progressi ogni settimana e promette che tutto procede secondo i piani. Gli abitanti del paese aspettano con impazienza di vedere l'edificio finalmente restaurato.",
      accepted: ["finiscano"],
      hint: "Sperare che always triggers the congiuntivo; finire → finiscano for gli operai/loro.",
      tags: ["congiuntivo", "passage_cloze", "spero che", "finire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-021", "u20-t2-022", "u20-t2-023"],
    },
    {
      id: "u20-t4-010",
      type: "passage_cloze",
      prompt:
        "Durante la riunione di lavoro, il direttore ha annunciato importanti cambiamenti nell'organizzazione dell'azienda. Non sono sicuro che tutti i dipendenti ___ già i dettagli di queste modifiche, perché molti sembravano confusi durante la discussione. Alcuni colleghi hanno fatto domande specifiche, mentre altri sono rimasti in silenzio senza reagire. Il direttore ha promesso di inviare un documento chiaro entro la fine della settimana.",
      accepted: ["sappiano"],
      hint: "Non sono sicuro che always triggers the congiuntivo; sapere → sappiano for i dipendenti/loro.",
      tags: ["congiuntivo", "passage_cloze", "non sono sicuro che", "sapere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-031"],
    },
    {
      id: "u20-t4-011",
      type: "passage_cloze",
      prompt:
        "Paolo racconta sempre storie incredibili sui suoi viaggi in giro per il mondo. Dubito che lui ___ sempre tutta la verità quando parla delle sue avventure, perché alcuni dettagli cambiano ogni volta che le racconta. I suoi amici lo ascoltano comunque con piacere, ridendo delle esagerazioni più evidenti. Nonostante i dubbi, nessuno gli chiede mai di dimostrare quello che dice.",
      accepted: ["dica"],
      hint: "Dubitare che is a strong doubt trigger and always takes the congiuntivo, just like credere che; dire → dica for lui.",
      tags: ["congiuntivo", "passage_cloze", "dubitare che", "dire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-011", "u20-t1-012", "u20-t2-024"],
    },
    {
      id: "u20-t4-012",
      type: "passage_cloze",
      prompt:
        "Da qualche settimana il vicino di Marta si comporta in modo strano, evitando ogni conversazione. Marta sospetta che lui ___ vendere l'appartamento e trasferirsi in un'altra città senza dirlo a nessuno. Ha notato scatoloni vuoti sul pianerottolo e alcune persone che visitano l'appartamento durante il weekend. Anche se non ne è certa, decide di non fare domande dirette per rispetto della sua privacy.",
      accepted: ["voglia"],
      hint: "Sospettare che triggers the congiuntivo, just like dubitare che; volere → voglia for lui.",
      tags: ["congiuntivo", "passage_cloze", "sospettare che", "volere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-017", "u20-t1-018", "u20-t2-041"],
    },
    {
      id: "u20-t4-013",
      type: "passage_cloze",
      prompt:
        "Federico è incerto sul futuro della sua carriera dopo la laurea. Crede che la situazione economica ___ meglio tra qualche mese, ma per ora preferisce accettare qualsiasi lavoro disponibile. I suoi genitori lo sostengono, anche se anche loro sono un po' preoccupati per la sua incertezza. Federico continua a mandare curriculum ogni settimana, sperando in una buona notizia.",
      accepted: ["vada"],
      hint: "Credere che always triggers the congiuntivo; andare → vada for la situazione/lei.",
      tags: ["congiuntivo", "passage_cloze", "credo che", "andare", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-021", "u20-t1-022", "u20-t2-029", "u20-t2-030"],
    },
    {
      id: "u20-t4-014",
      type: "passage_cloze",
      prompt:
        "Chiara è tornata da un lungo viaggio e i suoi amici la trovano diversa. Penso che lei ___ ancora un po' confusa per il cambio di fuso orario, perché risponde alle domande con perplessità. I suoi amici cercano di non stressarla troppo con troppe domande subito. Dopo qualche giorno di riposo, Chiara torna gradualmente alla sua solita energia.",
      accepted: ["stia"],
      hint: "Pensare che always triggers the congiuntivo; stare → stia for lei.",
      tags: ["congiuntivo", "passage_cloze", "penso che", "stare", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-025", "u20-t1-026", "u20-t2-039", "u20-t2-040"],
    },
    {
      id: "u20-t4-015",
      type: "passage_cloze",
      prompt:
        "Il professore ha restituito i compiti corretti con commenti molto dettagliati per ogni studente. Mi sembra che lui ___ molta importanza al modo in cui gli studenti argomentano le proprie idee, non solo al risultato finale. Alcuni studenti hanno il sospetto che questo nuovo metodo li aiuterà a migliorare più velocemente. Altri restano scettici, ma decidono comunque di seguire i consigli ricevuti.",
      accepted: ["dia"],
      hint: "Mi sembra che always triggers the congiuntivo; dare → dia for lui, il professore.",
      tags: ["congiuntivo", "passage_cloze", "mi sembra che", "dare", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-015", "u20-t1-016", "u20-t2-036", "u20-t2-037", "u20-t2-038"],
    },
    {
      id: "u20-t4-016",
      type: "passage_cloze",
      prompt:
        "Da giorni piove ininterrottamente in tutta la regione, e le strade sono quasi vuote. Spero che i miei amici ___ comunque con me sabato sera, nonostante il maltempo previsto. Ho prenotato un tavolo in un piccolo ristorante che vogliamo provare da tempo. Se il tempo migliora, potremmo anche fare una passeggiata dopo cena.",
      accepted: ["escano"],
      hint: "Sperare che always triggers the congiuntivo; uscire → escano for i miei amici/loro.",
      tags: ["congiuntivo", "passage_cloze", "spero che", "uscire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-028"],
    },
    {
      id: "u20-t4-017",
      type: "passage_cloze",
      prompt:
        "Il team di progetto ha ricevuto una nuova richiesta urgente dal cliente questa mattina. Non sono sicura che noi ___ cambiare tutto il piano di lavoro solo per questa richiesta, visto che siamo già in ritardo su altri compiti. La responsabile del progetto propone di discuterne insieme prima di prendere una decisione definitiva. Tutti concordano che serve più tempo per valutare le conseguenze di ogni scelta.",
      accepted: ["dobbiamo"],
      hint: "Non sono sicuro/a che always triggers the congiuntivo; dovere → dobbiamo for noi, identical to the indicativo.",
      tags: ["congiuntivo", "passage_cloze", "non sono sicuro che", "dovere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t2-034", "u20-t2-035"],
    },
    {
      id: "u20-t4-018",
      type: "passage_cloze",
      prompt:
        "L'artigiano lavora da mesi a un mobile antico molto danneggiato dal tempo. È dubbioso sui tempi di consegna, ma promette comunque un buon risultato finale. Credo che lui ___ il restauro entro la fine del mese, secondo quanto mi ha detto ieri al telefono. Il cliente aspetta con pazienza, felice di vedere il mobile tornare al suo antico splendore.",
      accepted: ["finisca"],
      hint: "Credere che always triggers the congiuntivo; finire → finisca for lui.",
      tags: ["congiuntivo", "passage_cloze", "credo che", "finire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-013", "u20-t1-014", "u20-t2-021", "u20-t2-022"],
    },
    {
      id: "u20-t4-019",
      type: "passage_cloze",
      prompt:
        "Dopo l'incidente in autostrada, molte persone vivono nell'incertezza su quando potranno tornare a casa. Penso che i soccorsi ___ presto per aiutare tutti i passeggeri bloccati nel traffico. Alcuni automobilisti scendono dalle macchine per sgranchirsi le gambe, mentre altri restano in attesa di notizie alla radio. La polizia stradale assicura che la situazione si risolverà entro un'ora.",
      accepted: ["vengano"],
      hint: "Pensare che always triggers the congiuntivo; venire → vengano for i soccorsi/loro.",
      tags: ["congiuntivo", "passage_cloze", "penso che", "venire", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-019", "u20-t1-020", "u20-t2-025", "u20-t2-026", "u20-t2-027"],
    },
    {
      id: "u20-t4-020",
      type: "passage_cloze",
      prompt:
        "Alla riunione del condominio, alcuni vicini hanno espresso una certa perplessità riguardo alle nuove regole sul parcheggio. Mi sembra che loro ___ semplicemente più chiarezza sulle decisioni prese dall'amministratore. L'amministratore promette di preparare un documento scritto con tutte le informazioni necessarie. La maggior parte dei condomini si dice comunque soddisfatta della gestione generale del palazzo.",
      accepted: ["vogliano"],
      hint: "Mi sembra che always triggers the congiuntivo; volere → vogliano for loro.",
      tags: ["congiuntivo", "passage_cloze", "mi sembra che", "volere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-023", "u20-t1-024", "u20-t2-041", "u20-t2-046"],
    },

    // ── Tier 4 – Passages (replacements for deprecated u20-t4-001/002/003) ────
    {
      id: "u20-t4-021",
      type: "passage_cloze",
      prompt:
        "Marco ha cambiato lavoro da poche settimane e i colleghi lo osservano con curiosità. Nonostante lui abbia ancora molti dubbi sulle procedure dell'ufficio, mi sembra che ___ già delle opinioni chiare su come migliorare il team. Durante le riunioni interviene raramente, ma quando parla propone sempre soluzioni concrete. Il direttore nota questo dettaglio e decide di affidargli presto un piccolo progetto autonomo.",
      accepted: ["abbia"],
      hint: "Mi sembra che always triggers the congiuntivo; avere → abbia for lui. Two triggers combine here: nonostante and mi sembra che.",
      tags: ["congiuntivo", "passage_cloze", "mi sembra che", "avere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-001", "u20-t1-002", "u20-t1-008", "u20-t2-006", "u20-t2-007"],
    },
    {
      id: "u20-t4-022",
      type: "passage_cloze",
      prompt:
        "Alla fine del semestre, molti studenti universitari si sentono stanchi e demotivati. Penso che la necessità di organizzare meglio il tempo ___ evidente ormai per tutta la classe, non solo per chi è in difficoltà. Alcuni professori propongono di ridurre il carico di esami nelle ultime settimane. Altri preferiscono mantenere il programma invariato, convinti che la disciplina aiuti a prepararsi al mondo del lavoro. Gli studenti intanto si confrontano nei corridoi, in cerca di consigli pratici per superare l'ultimo mese.",
      accepted: ["sia"],
      hint: "Pensare che always triggers the congiuntivo; essere → sia for la necessità. Necessità ends in -tà and stays the same in the plural.",
      tags: ["congiuntivo", "passage_cloze", "pensare che", "essere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-010", "u20-t2-004", "u20-t2-005"],
    },
    {
      id: "u20-t4-023",
      type: "passage_cloze",
      prompt:
        "Il gruppo di lavoro si riunisce ogni martedì per fare il punto sulla nuova app aziendale. Ho l'impressione che i programmatori non ___ abbastanza tempo per completare tutte le funzioni richieste dal cliente entro la scadenza. Il project manager ascolta le loro preoccupazioni e prende appunti su un quaderno. Propone di rimandare il lancio di due settimane, ma il cliente non risponde subito alla richiesta.",
      accepted: ["abbiano"],
      hint: "Ho l'impressione che always triggers the congiuntivo; avere → abbiano for i programmatori/loro.",
      tags: ["congiuntivo", "passage_cloze", "ho l'impressione che", "avere", "tier4"],
      tier: 4,
      prerequisites: ["u20-t1-009", "u20-t2-007"],
    },
  ],
};
export default unit;
