import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-53-subjunctive-connector-mastery",
  name: "Putting It All Together",
  level: "B1",
  theme: "B1 Consolidation — Subjunctive & Connector Mastery",
  emoji: "🎓",
  prerequisiteUnits: [
    "b1-unit-20-congiuntivo",
    "b1-unit-33-subjunctive-opinions",
    "b1-unit-34-subjunctive-impersonal",
    "b1-unit-35-subjunctive-emotion",
    "b1-unit-37-concession-contrast",
    "b1-unit-38-cause-effect",
    "b1-unit-39-purpose-result",
  ],
  cards: [
    // ── Tier 1 – Vocabulary: meta-language for reasoning and argument ────────
    { id: "b153-t1-001", type: "recognize", prompt: "la certezza", accepted: ["certainty"], hint: "Feminine noun from certo — 'avere la certezza che' means to be certain that.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-002", type: "produce", prompt: "certainty", accepted: ["la certezza"], hint: "La certezza (feminine); word family with certo/certa (certain).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-003", type: "recognize", prompt: "l'ipotesi", accepted: ["the hypothesis"], hint: "Feminine noun, invariable in the plural: le ipotesi.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-004", type: "produce", prompt: "the hypothesis", accepted: ["l'ipotesi"], hint: "l'ipotesi (feminine); the plural form is identical: le ipotesi.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-005", type: "recognize", prompt: "la premessa", accepted: ["the premise"], hint: "Feminine noun — the starting point an argument builds on.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-006", type: "produce", prompt: "the premise", accepted: ["la premessa"], hint: "La premessa (feminine); plural: le premesse.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-007", type: "recognize", prompt: "la conclusione", accepted: ["the conclusion"], hint: "Feminine noun ending in -zione, like most abstract nouns of this family.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-008", type: "produce", prompt: "the conclusion", accepted: ["la conclusione"], hint: "From concludere (to conclude); collocation: trarre una conclusione (to draw a conclusion).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-009", type: "recognize", prompt: "il ragionamento", accepted: ["the reasoning"], hint: "Masculine noun from ragionare (to reason).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-010", type: "produce", prompt: "the reasoning", accepted: ["il ragionamento"], hint: "Collocation: seguire il ragionamento (to follow the reasoning) — the -mento suffix is common for masculine nouns built from -are verbs.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-011", type: "recognize", prompt: "l'argomentazione", accepted: ["the argumentation", "the line of argument"], hint: "Feminine noun ending in -zione, with an elided article before the vowel.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-012", type: "produce", prompt: "the argumentation / the line of argument", accepted: ["l'argomentazione"], hint: "From argomentare (to argue a case); collocation: seguire l'argomentazione di qualcuno (to follow someone's line of argument).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-013", type: "recognize", prompt: "la deduzione", accepted: ["the deduction"], hint: "Feminine noun ending in -zione, from dedurre (to deduce).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-014", type: "produce", prompt: "the deduction", accepted: ["la deduzione"], hint: "Collocation: trarre una deduzione (to draw a deduction) — same trarre pattern as trarre una conclusione.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-015", type: "recognize", prompt: "la sfumatura", accepted: ["the nuance", "the shade of meaning"], hint: "Feminine noun — a small but meaningful difference in meaning or tone.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-016", type: "produce", prompt: "the nuance", accepted: ["la sfumatura"], hint: "Collocation: cogliere una sfumatura (to catch a nuance) — cogliere pairs naturally with verbs of perception.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-017", type: "recognize", prompt: "il registro", accepted: ["the register (level of language)"], hint: "Masculine noun — formal vs. informal register, a linguistics term.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-018", type: "produce", prompt: "the register (of language)", accepted: ["il registro"], hint: "Collocation: cambiare registro (to switch register) — used for shifting between formal and informal speech.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-019", type: "recognize", prompt: "la coerenza", accepted: ["the coherence"], hint: "Feminine noun from coerente (coherent).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-020", type: "produce", prompt: "the coherence", accepted: ["la coerenza"], hint: "Collocation: mancare di coerenza (to lack coherence); the opposite is incoerenza (inconsistency).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-021", type: "recognize", prompt: "il collegamento", accepted: ["the connection", "the link"], hint: "Masculine noun from collegare (to connect, to link).", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-022", type: "produce", prompt: "the connection / the link", accepted: ["il collegamento"], hint: "Near-synonym of connessione, but collegamento leans toward a link or connection established on purpose.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-023", type: "recognize", prompt: "la contrapposizione", accepted: ["the contrast", "the opposition (of ideas)"], hint: "Feminine noun, more formal than il contrasto — used for opposing ideas or positions.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-024", type: "produce", prompt: "the opposition (of ideas)", accepted: ["la contrapposizione"], hint: "Collocation: essere in contrapposizione con (to be in opposition to) — pairs with con, not a.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-025", type: "recognize", prompt: "il connettivo", accepted: ["the connector"], hint: "Masculine noun — the linguistic term for a linking word like tuttavia or affinché.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-026", type: "produce", prompt: "the connector (linking word)", accepted: ["il connettivo"], hint: "Covers both logical connectors (quindi, perciò) and concessive ones (tuttavia) — the umbrella term for any linking word.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-027", type: "recognize", prompt: "il paragone", accepted: ["the comparison"], hint: "Masculine noun — pairs with the collocation fare un paragone.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-028", type: "produce", prompt: "the comparison", accepted: ["il paragone"], hint: "Distinct from il confronto: paragone stresses similarity or likeness, confronto stresses a direct comparison or clash.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-029", type: "recognize", prompt: "la sintesi", accepted: ["the synthesis", "the summary"], hint: "Feminine noun, invariable in the plural: le sintesi.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-030", type: "produce", prompt: "the synthesis / the summary", accepted: ["la sintesi"], hint: "La sintesi (feminine); plural is identical.", tags: ["noun", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-031", type: "recognize", prompt: "il punto di vista", accepted: ["the point of view", "the viewpoint"], hint: "Fixed masculine expression — plural: i punti di vista.", tags: ["expression", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-032", type: "produce", prompt: "the point of view", accepted: ["il punto di vista"], hint: "Collocation: condividere il punto di vista di qualcuno (to share someone's point of view) — the phrase stays fixed, only punto pluralizes (punti di vista).", tags: ["expression", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-033", type: "recognize", prompt: "convincente", accepted: ["convincing"], hint: "Invariable adjective ending in -e, from the verb convincere.", tags: ["adjective", "argumentation", "vocab"], tier: 1 },
    { id: "b153-t1-034", type: "produce", prompt: "convincing", accepted: ["convincente"], hint: "Convincente, same form for masculine and feminine.", tags: ["adjective", "argumentation", "vocab"], tier: 1 },

    // ── Tier 2 – Grammar: mixed-trigger bank (doubt / opinion / impersonal / emotion / concession / cause / purpose) ──
    { id: "b153-t2-001", type: "fill_blank", prompt: "Dubito che questa ipotesi ___ (reggere) a un'analisi più approfondita.", accepted: ["regga"], hint: "Dubitare che always triggers the congiuntivo; reggere → regga (she/it, l'ipotesi).", tags: ["congiuntivo", "dubbio", "reggere", "fill_blank"], tier: 2 },
    { id: "b153-t2-002", type: "fill_blank", prompt: "Dato che l'ipotesi non ___ (reggere) a un'analisi più approfondita, il team l'ha abbandonata.", accepted: ["regge"], hint: "Dato che takes the indicativo, never the congiuntivo; reggere → regge.", tags: ["indicativo", "causa", "reggere", "fill_blank"], tier: 2 },
    { id: "b153-t2-003", type: "fill_blank", prompt: "Non sono sicuro che questa deduzione ___ (essere) corretta.", accepted: ["sia"], hint: "Non essere sicuro che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "dubbio", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-004", type: "fill_blank", prompt: "Siccome la deduzione non ___ (essere) corretta, dobbiamo rifare i calcoli.", accepted: ["è"], hint: "Siccome takes the indicativo; essere → è.", tags: ["indicativo", "causa", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-005", type: "fill_blank", prompt: "Ritengo che il nuovo regolamento ___ (richiedere) alcune modifiche.", accepted: ["richieda"], hint: "Ritenere che triggers the congiuntivo; richiedere → richieda.", tags: ["congiuntivo", "opinione", "richiedere", "fill_blank"], tier: 2 },
    { id: "b153-t2-006", type: "fill_blank", prompt: "A mio avviso, il nuovo regolamento ___ (richiedere) alcune modifiche.", accepted: ["richiede"], hint: "A mio avviso takes the indicativo, never the congiuntivo; richiedere → richiede.", tags: ["indicativo", "opinione", "richiedere", "fill_blank"], tier: 2 },
    { id: "b153-t2-007", type: "fill_blank", prompt: "È necessario che l'azienda ___ (chiarire) la propria posizione entro venerdì.", accepted: ["chiarisca"], hint: "È necessario che triggers the congiuntivo; chiarire is an -isc- verb, so chiarire → chiarisca.", tags: ["congiuntivo", "impersonale", "chiarire", "fill_blank"], tier: 2 },
    { id: "b153-t2-008", type: "fill_blank", prompt: "L'azienda ha organizzato un incontro affinché i dipendenti ___ (chiarire) ogni dubbio con la direzione.", accepted: ["chiariscano"], hint: "Affinché always takes the congiuntivo; chiarire → chiariscano (loro).", tags: ["congiuntivo", "scopo", "chiarire", "fill_blank"], tier: 2 },
    { id: "b153-t2-009", type: "fill_blank", prompt: "Mi sorprende che il pubblico non ___ (essere) più convinto dall'argomentazione del relatore.", accepted: ["sia"], hint: "Mi sorprende che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "emozione", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-010", type: "fill_blank", prompt: "Sebbene l'argomentazione ___ (essere) convincente, alcuni membri del comitato restano scettici.", accepted: ["sia"], hint: "Sebbene always takes the congiuntivo; essere → sia.", tags: ["congiuntivo", "concessiva", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-011", type: "fill_blank", prompt: "Poiché l'argomentazione ___ (essere) debole, la giuria non si è lasciata convincere.", accepted: ["era"], hint: "Poiché takes the indicativo; essere in the imperfetto → era.", tags: ["indicativo", "causa", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-012", type: "fill_blank", prompt: "Il relatore ha rifatto la presentazione per ___ (rendere) l'argomentazione più convincente.", accepted: ["rendere"], hint: "Same subject in both clauses (il relatore/il relatore) → per + infinito, never the congiuntivo.", tags: ["scopo", "stesso-soggetto", "rendere", "fill_blank"], tier: 2 },
    { id: "b153-t2-013", type: "fill_blank", prompt: "Dubitiamo che questa sintesi ___ (coprire) tutti gli aspetti del problema.", accepted: ["copra"], hint: "Dubitare che triggers the congiuntivo; coprire → copra.", tags: ["congiuntivo", "dubbio", "coprire", "fill_blank"], tier: 2 },
    { id: "b153-t2-014", type: "fill_blank", prompt: "È probabile che la sintesi finale ___ (richiedere) altre due settimane di lavoro.", accepted: ["richieda"], hint: "È probabile che triggers the congiuntivo; richiedere → richieda.", tags: ["congiuntivo", "impersonale", "richiedere", "fill_blank"], tier: 2 },
    { id: "b153-t2-015", type: "fill_blank", prompt: "Sono contenta che il mio punto di vista ___ (contare) qualcosa nella decisione finale.", accepted: ["conti"], hint: "Sono contento/a che triggers the congiuntivo; contare → conti.", tags: ["congiuntivo", "emozione", "contare", "fill_blank"], tier: 2 },
    { id: "b153-t2-016", type: "fill_blank", prompt: "Suppongo che il tuo punto di vista ___ (cambiare) dopo aver letto il rapporto completo.", accepted: ["cambi"], hint: "Supporre che triggers the congiuntivo; cambiare → cambi.", tags: ["congiuntivo", "opinione", "cambiare", "fill_blank"], tier: 2 },
    { id: "b153-t2-017", type: "fill_blank", prompt: "Nonostante il mio punto di vista non ___ (coincidere) con il loro, hanno accettato di ascoltarmi.", accepted: ["coincida"], hint: "Nonostante takes the congiuntivo; coincidere → coincida.", tags: ["congiuntivo", "concessiva", "coincidere", "fill_blank"], tier: 2 },
    { id: "b153-t2-018", type: "fill_blank", prompt: "Dal momento che i due punti di vista non ___ (coincidere), la discussione è durata più del previsto.", accepted: ["coincidono"], hint: "Dal momento che takes the indicativo; coincidere → coincidono (loro).", tags: ["indicativo", "causa", "coincidere", "fill_blank"], tier: 2 },
    { id: "b153-t2-019", type: "fill_blank", prompt: "Il mediatore ha proposto una pausa affinché entrambe le parti ___ (trovare) un punto di vista comune.", accepted: ["trovino"], hint: "Affinché takes the congiuntivo; trovare → trovino (loro).", tags: ["congiuntivo", "scopo", "trovare", "fill_blank"], tier: 2 },
    { id: "b153-t2-020", type: "fill_blank", prompt: "Non è affatto certo che questo collegamento tra le due cause ___ (essere) reale.", accepted: ["sia"], hint: "Non è certo che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "dubbio", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-021", type: "fill_blank", prompt: "Può darsi che il collegamento tra i due eventi ___ (essere) solo una coincidenza.", accepted: ["sia"], hint: "Può darsi che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "impersonale", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-022", type: "fill_blank", prompt: "Siccome non ___ (esserci) alcun collegamento provato tra i due eventi, gli scienziati restano cauti.", accepted: ["c'è"], hint: "Siccome takes the indicativo; esserci → c'è.", tags: ["indicativo", "causa", "esserci", "fill_blank"], tier: 2 },
    { id: "b153-t2-023", type: "fill_blank", prompt: "Per quanto il collegamento ___ (sembrare) evidente, servono altre prove per confermarlo.", accepted: ["sembri"], hint: "Per quanto takes the congiuntivo; sembrare → sembri.", tags: ["congiuntivo", "concessiva", "sembrare", "fill_blank"], tier: 2 },
    { id: "b153-t2-024", type: "fill_blank", prompt: "Sono convinto che la coerenza di questo ragionamento ___ (dipendere) dalle premesse iniziali.", accepted: ["dipenda"], hint: "Essere convinto che triggers the congiuntivo; dipendere → dipenda.", tags: ["congiuntivo", "opinione", "dipendere", "fill_blank"], tier: 2 },
    { id: "b153-t2-025", type: "fill_blank", prompt: "È importante che le premesse di un'argomentazione ___ (essere) sempre verificabili.", accepted: ["siano"], hint: "È importante che triggers the congiuntivo; essere → siano (loro, le premesse).", tags: ["congiuntivo", "impersonale", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-026", type: "fill_blank", prompt: "Poiché le premesse del suo ragionamento ___ (essere) sbagliate, la conclusione non poteva reggere.", accepted: ["erano"], hint: "Poiché takes the indicativo; essere in the imperfetto → erano.", tags: ["indicativo", "causa", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-027", type: "fill_blank", prompt: "Il professore ha riscritto la premessa in modo che gli studenti ___ (capire) meglio la logica dell'esperimento.", accepted: ["capiscano"], hint: "In modo che takes the congiuntivo; capire → capiscano (loro).", tags: ["congiuntivo", "scopo", "capire", "fill_blank"], tier: 2 },
    { id: "b153-t2-028", type: "fill_blank", prompt: "Mi dispiace che la tua conclusione ___ (essere) così pessimista.", accepted: ["sia"], hint: "Mi dispiace che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "emozione", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-029", type: "fill_blank", prompt: "Non credo che questa conclusione ___ (tenere) conto di tutti i fattori.", accepted: ["tenga"], hint: "Non credere che triggers the congiuntivo; tenere → tenga.", tags: ["congiuntivo", "dubbio", "tenere", "fill_blank"], tier: 2 },
    { id: "b153-t2-030", type: "fill_blank", prompt: "Dato che la conclusione non ___ (tenere) conto di tutti i fattori, il rapporto è stato respinto.", accepted: ["teneva"], hint: "Dato che takes the indicativo; tenere in the imperfetto → teneva.", tags: ["indicativo", "causa", "tenere", "fill_blank"], tier: 2 },
    { id: "b153-t2-031", type: "fill_blank", prompt: "Malgrado la conclusione ___ (sembrare) solida, il comitato ha chiesto ulteriori verifiche.", accepted: ["sembri"], hint: "Malgrado takes the congiuntivo; sembrare → sembri.", tags: ["congiuntivo", "concessiva", "sembrare", "fill_blank"], tier: 2 },
    { id: "b153-t2-032", type: "fill_blank", prompt: "Ha aggiunto una tabella cosicché la conclusione ___ (risultare) più chiara ai lettori.", accepted: ["risulti"], hint: "Cosicché takes the congiuntivo; risultare → risulti.", tags: ["congiuntivo", "scopo", "risultare", "fill_blank"], tier: 2 },
    { id: "b153-t2-033", type: "fill_blank", prompt: "È ovvio che la sfumatura tra questi due termini ___ (sfuggire) a chi non conosce bene l'italiano.", accepted: ["sfugga"], hint: "È ovvio che triggers the congiuntivo; sfuggire → sfugga.", tags: ["congiuntivo", "impersonale", "sfuggire", "fill_blank"], tier: 2 },
    { id: "b153-t2-034", type: "fill_blank", prompt: "Immagino che questa sfumatura ___ (essere) difficile da cogliere per un principiante.", accepted: ["sia"], hint: "Immaginare che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "opinione", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-035", type: "fill_blank", prompt: "Siccome la sfumatura tra i due termini ___ (essere) sottile, molti studenti li confondono.", accepted: ["è"], hint: "Siccome takes the indicativo; essere → è.", tags: ["indicativo", "causa", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-036", type: "fill_blank", prompt: "Sebbene la sfumatura ___ (essere) sottile, cambia completamente il significato della frase.", accepted: ["sia"], hint: "Sebbene always takes the congiuntivo; essere → sia.", tags: ["congiuntivo", "concessiva", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-037", type: "fill_blank", prompt: "Dubito che il registro di questa lettera ___ (essere) abbastanza formale per un cliente importante.", accepted: ["sia"], hint: "Dubitare che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "dubbio", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-038", type: "fill_blank", prompt: "È opportuno che il registro della tua email ___ (adattarsi) al destinatario.", accepted: ["si adatti"], hint: "È opportuno che triggers the congiuntivo, here on a reflexive verb; adattarsi → si adatti.", tags: ["congiuntivo", "impersonale", "adattarsi", "fill_blank"], tier: 2 },
    { id: "b153-t2-039", type: "fill_blank", prompt: "Ho cambiato alcune parole affinché il registro ___ (risultare) più professionale.", accepted: ["risulti"], hint: "Affinché takes the congiuntivo; risultare → risulti.", tags: ["congiuntivo", "scopo", "risultare", "fill_blank"], tier: 2 },
    { id: "b153-t2-040", type: "fill_blank", prompt: "Dato che il registro ___ (essere) troppo informale, l'ho riscritta prima di inviarla.", accepted: ["era"], hint: "Dato che takes the indicativo; essere in the imperfetto → era.", tags: ["indicativo", "causa", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-041", type: "fill_blank", prompt: "Mi dà fastidio che alcuni colleghi non ___ (rispettare) mai il registro adeguato nelle email ufficiali.", accepted: ["rispettino"], hint: "Mi dà fastidio che triggers the congiuntivo; rispettare → rispettino (loro).", tags: ["congiuntivo", "emozione", "rispettare", "fill_blank"], tier: 2 },
    { id: "b153-t2-042", type: "fill_blank", prompt: "Ritengo che un buon connettivo ___ (rendere) il testo molto più scorrevole.", accepted: ["renda"], hint: "Ritenere che triggers the congiuntivo; rendere → renda.", tags: ["congiuntivo", "opinione", "rendere", "fill_blank"], tier: 2 },
    { id: "b153-t2-043", type: "fill_blank", prompt: "Il capitolo era troppo lungo; ___, l'autore ha deciso di dividerlo in due parti.", accepted: ["Perciò", "Quindi", "Dunque"], hint: "Result connector at the start of a sentence: perciò, quindi, and dunque are interchangeable here.", tags: ["connettivo", "causa-effetto", "fill_blank"], tier: 2 },
    { id: "b153-t2-044", type: "fill_blank", prompt: "Il rapporto conteneva alcuni errori. ___, la conclusione generale restava valida.", accepted: ["Tuttavia", "Comunque", "Eppure"], hint: "Contrast connector at the start of a sentence: tuttavia, comunque, and eppure all work here.", tags: ["connettivo", "contrasto", "fill_blank"], tier: 2 },
    { id: "b153-t2-045", type: "fill_blank", prompt: "Ha riorganizzato i paragrafi in modo da ___ (migliorare) il collegamento tra le idee.", accepted: ["migliorare"], hint: "Same subject in both clauses → in modo da + infinito, never the congiuntivo.", tags: ["scopo", "stesso-soggetto", "migliorare", "fill_blank"], tier: 2 },
    { id: "b153-t2-046", type: "fill_blank", prompt: "Non sono sicuri che questo paragone ___ (essere) del tutto appropriato.", accepted: ["sia"], hint: "Non essere sicuro che triggers the congiuntivo; essere → sia.", tags: ["congiuntivo", "dubbio", "essere", "fill_blank"], tier: 2 },
    { id: "b153-t2-047", type: "fill_blank", prompt: "È strano che nessuno ___ (notare) la contraddizione tra le due dichiarazioni.", accepted: ["noti"], hint: "È strano che triggers the congiuntivo; notare → noti (nessuno takes a singular verb).", tags: ["congiuntivo", "impersonale", "notare", "fill_blank"], tier: 2 },
    { id: "b153-t2-048", type: "fill_blank", prompt: "Siccome il paragone tra le due situazioni non ___ (reggere), il giornalista ha dovuto correggere l'articolo.", accepted: ["regge"], hint: "Siccome takes the indicativo; reggere → regge.", tags: ["indicativo", "causa", "reggere", "fill_blank"], tier: 2 },
    { id: "b153-t2-049", type: "fill_blank", prompt: "Benché il paragone ___ (sembrare) azzardato, in realtà coglie un aspetto importante.", accepted: ["sembri"], hint: "Benché takes the congiuntivo; sembrare → sembri.", tags: ["congiuntivo", "concessiva", "sembrare", "fill_blank"], tier: 2 },
    { id: "b153-t2-050", type: "fill_blank", prompt: "Suppongo che questa sintesi ___ (bastare) per la riunione di domani.", accepted: ["basti"], hint: "Supporre che triggers the congiuntivo; bastare → basti.", tags: ["congiuntivo", "opinione", "bastare", "fill_blank"], tier: 2 },
    { id: "b153-t2-051", type: "fill_blank", prompt: "Sono felice che la sintesi del progetto ___ (piacere) al direttore.", accepted: ["piaccia"], hint: "Sono felice che triggers the congiuntivo; piacere → piaccia.", tags: ["congiuntivo", "emozione", "piacere", "fill_blank"], tier: 2 },
    { id: "b153-t2-052", type: "fill_blank", prompt: "Ha preparato una sintesi affinché i colleghi assenti ___ (potere) capire subito la situazione.", accepted: ["possano"], hint: "Affinché takes the congiuntivo; potere → possano (loro).", tags: ["congiuntivo", "scopo", "potere", "fill_blank"], tier: 2 },
    { id: "b153-t2-053", type: "fill_blank", prompt: "Le vendite sono calate del venti percento; di conseguenza, l'azienda ___ (dovere) rivedere il budget.", accepted: ["deve"], hint: "Di conseguenza takes the indicativo; dovere → deve.", tags: ["indicativo", "causa-effetto", "dovere", "fill_blank"], tier: 2 },
    { id: "b153-t2-054", type: "fill_blank", prompt: "Non è vero che ogni argomentazione convincente ___ (bastare) a cambiare idea a qualcuno.", accepted: ["basti"], hint: "Non è vero che triggers the congiuntivo; bastare → basti.", tags: ["congiuntivo", "dubbio", "bastare", "fill_blank"], tier: 2 },
    { id: "b153-t2-055", type: "fill_blank", prompt: "È raro che un'argomentazione così ___ (risultare) convincente a tutti, senza eccezioni.", accepted: ["risulti"], hint: "È raro che triggers the congiuntivo; risultare → risulti.", tags: ["congiuntivo", "impersonale", "risultare", "fill_blank"], tier: 2 },
    { id: "b153-t2-056", type: "fill_blank", prompt: "Anche se l'argomentazione ___ (essere) convincente, il giudice non ha cambiato la sentenza.", accepted: ["era"], hint: "Anche se takes the indicativo, never the congiuntivo; essere in the imperfetto → era.", tags: ["indicativo", "concessiva", "essere", "fill_blank"], tier: 2 },

    // ── Tier 3 – Phrases: combining two trigger categories per sentence ──────
    { id: "b153-t3-001", type: "produce", prompt: "Although the report is long, I think it deserves a careful reading.", accepted: ["Sebbene il rapporto sia lungo, ritengo che meriti una lettura attenta."], hint: "Two triggers here: sebbene (concessive) and ritengo che (opinion) — both take the congiuntivo.", tags: ["congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-002", type: "produce", prompt: "Even though the plan seems risky, I suppose it can work.", accepted: ["Anche se il piano sembra rischioso, suppongo che possa funzionare."], hint: "Anche se takes the indicativo (sembra), followed by suppongo che, which takes the congiuntivo (possa).", tags: ["indicativo", "congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-003", type: "produce", prompt: "Although she doubts the plan, I am convinced that it deserves a chance.", accepted: ["Sebbene lei dubiti del piano, sono convinto che meriti una possibilità.", "Sebbene lei dubiti del piano, sono convinta che meriti una possibilità."], hint: "Sebbene triggers the congiuntivo on dubitare (dubiti), and sono convinto/a che triggers the congiuntivo on meritare (meriti).", tags: ["congiuntivo", "concessiva", "dubbio", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-004", type: "produce", prompt: "Despite the doubts, I imagine that the project will succeed.", accepted: ["Nonostante i dubbi, immagino che il progetto abbia successo."], hint: "Nonostante takes a noun here, followed by immaginare che, which triggers the congiuntivo of avere successo (abbia successo).", tags: ["congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-005", type: "produce", prompt: "Although the professor is strict, we consider that his method works.", accepted: ["Sebbene il professore sia severo, riteniamo che il suo metodo funzioni."], hint: "Sebbene triggers the congiuntivo (sia), and riteniamo che also triggers the congiuntivo (funzioni).", tags: ["congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-006", type: "produce", prompt: "No matter how convincing the argument is, I suppose there are other explanations.", accepted: ["Per quanto l'argomentazione sia convincente, suppongo che esistano altre spiegazioni."], hint: "Per quanto triggers the congiuntivo (sia), and suppongo che triggers the congiuntivo (esistano).", tags: ["congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },
    { id: "b153-t3-007", type: "produce", prompt: "Despite everything, I am convinced this synthesis captures the key point.", accepted: ["Malgrado tutto, sono convinto che questa sintesi colga il punto chiave.", "Malgrado tutto, sono convinta che questa sintesi colga il punto chiave."], hint: "Malgrado tutto is a fixed phrase (despite everything); sono convinto/a che triggers the congiuntivo of cogliere (colga).", tags: ["congiuntivo", "concessiva", "opinione", "chunk"], tier: 3 },

    { id: "b153-t3-008", type: "produce", prompt: "Since the deadline is close, we have reorganized the schedule so that everyone can finish on time.", accepted: ["Dato che la scadenza è vicina, abbiamo riorganizzato il calendario affinché tutti possano finire in tempo."], hint: "Dato che takes the indicativo (è), while affinché takes the congiuntivo (possano).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-009", type: "produce", prompt: "As the budget was cut, the manager changed the plan so that the team doesn't lose motivation.", accepted: ["Poiché il budget è stato tagliato, il direttore ha cambiato il piano in modo che il team non perda la motivazione."], hint: "Poiché takes the indicativo (passato prossimo here), while in modo che takes the congiuntivo (perda).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-010", type: "produce", prompt: "Given that the students were confused, the teacher rewrote the exercise so that it is clearer.", accepted: ["Dato che gli studenti erano confusi, l'insegnante ha riscritto l'esercizio cosicché sia più chiaro."], hint: "Dato che takes the indicativo (imperfetto here), while cosicché takes the congiuntivo (sia).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-011", type: "produce", prompt: "Since the results were inconsistent, the team changed the method so that the data would be more reliable.", accepted: ["Siccome i risultati erano incoerenti, il team ha cambiato il metodo affinché i dati siano più affidabili."], hint: "Siccome takes the indicativo, while affinché takes the congiuntivo (siano).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-012", type: "produce", prompt: "As the city grew quickly, the council built new schools so that every child has a place.", accepted: ["Dato che la città è cresciuta rapidamente, il comune ha costruito nuove scuole affinché ogni bambino abbia un posto."], hint: "Dato che takes the indicativo (passato prossimo), while affinché takes the congiuntivo (abbia).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-013", type: "produce", prompt: "Given that the client complained, we rewrote the contract so that both parties understand every clause.", accepted: ["Dato che il cliente si è lamentato, abbiamo riscritto il contratto in modo che entrambe le parti capiscano ogni clausola."], hint: "Dato che takes the indicativo (passato prossimo), while in modo che takes the congiuntivo (capiscano).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-014", type: "produce", prompt: "Since trust had decreased, the company changed its policy so that employees feel safer.", accepted: ["Poiché la fiducia era diminuita, l'azienda ha cambiato la politica affinché i dipendenti si sentano più sicuri."], hint: "Poiché takes the indicativo (trapassato prossimo here), while affinché takes the congiuntivo, here on a reflexive verb (si sentano).", tags: ["indicativo", "congiuntivo", "causa", "scopo", "chunk"], tier: 3 },

    { id: "b153-t3-015", type: "produce", prompt: "I doubt he read the whole report, and it bothers me that he already has an opinion.", accepted: ["Dubito che lui abbia letto tutto il rapporto, e mi dà fastidio che abbia già un'opinione."], hint: "Dubitare che triggers the congiuntivo passato (abbia letto), and mi dà fastidio che also triggers the congiuntivo (abbia).", tags: ["congiuntivo", "dubbio", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-016", type: "produce", prompt: "I'm not sure the plan will work, and I'm worried that no one has a backup.", accepted: ["Non sono sicuro che il piano funzioni, e sono preoccupato che nessuno abbia un piano di riserva.", "Non sono sicura che il piano funzioni, e sono preoccupata che nessuno abbia un piano di riserva."], hint: "Non essere sicuro/a che triggers the congiuntivo (funzioni), and sono preoccupato/a che also triggers the congiuntivo (abbia).", tags: ["congiuntivo", "dubbio", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-017", type: "produce", prompt: "I doubt she noticed the mistake, and I'm sorry that no one told her.", accepted: ["Dubito che lei abbia notato l'errore, e mi dispiace che nessuno gliel'abbia detto."], hint: "Dubitare che triggers the congiuntivo passato (abbia notato), and mi dispiace che also takes the congiuntivo passato (abbia detto).", tags: ["congiuntivo", "dubbio", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-018", type: "produce", prompt: "It surprises me that you doubt his intentions.", accepted: ["Mi sorprende che tu dubiti delle sue intenzioni."], hint: "Mi sorprende che triggers the congiuntivo (dubiti); here dubitare is the verb inside the clause, not the trigger itself.", tags: ["congiuntivo", "emozione", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-019", type: "produce", prompt: "I doubt the results are final, and I'm afraid we'll have to redo the whole analysis.", accepted: ["Dubito che i risultati siano definitivi, e ho paura che dobbiamo rifare tutta l'analisi."], hint: "Dubitare che triggers the congiuntivo (siano), and ho paura che also triggers the congiuntivo — dobbiamo looks identical to the indicativo for the noi form.", tags: ["congiuntivo", "dubbio", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-020", type: "produce", prompt: "It's a shame that you doubt your own abilities so much.", accepted: ["È un peccato che tu dubiti così tanto delle tue capacità."], hint: "È un peccato che triggers the congiuntivo; dubitare → dubiti.", tags: ["congiuntivo", "emozione", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-021", type: "produce", prompt: "I'm glad that you doubt easy answers.", accepted: ["Sono contento che tu dubiti delle risposte facili.", "Sono contenta che tu dubiti delle risposte facili."], hint: "Sono contento/a che triggers the congiuntivo; dubitare → dubiti.", tags: ["congiuntivo", "emozione", "dubbio", "chunk"], tier: 3 },

    { id: "b153-t3-022", type: "produce", prompt: "It is necessary that we act quickly, although the risk remains high.", accepted: ["È necessario che agiamo in fretta, sebbene il rischio resti alto."], hint: "È necessario che triggers the congiuntivo (agiamo), and sebbene also triggers the congiuntivo (resti).", tags: ["congiuntivo", "impersonale", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-023", type: "produce", prompt: "Although the data seems clear, it is advisable that we verify the source.", accepted: ["Sebbene i dati sembrino chiari, è opportuno che verifichiamo la fonte."], hint: "Sebbene triggers the congiuntivo (sembrino), and è opportuno che also triggers the congiuntivo (verifichiamo).", tags: ["congiuntivo", "concessiva", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-024", type: "produce", prompt: "It's probable that the meeting will be postponed, despite the urgency.", accepted: ["È probabile che la riunione venga rimandata, nonostante l'urgenza."], hint: "È probabile che triggers the congiuntivo, here in the passive (venga rimandata); nonostante takes a noun.", tags: ["congiuntivo", "impersonale", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-025", type: "produce", prompt: "Although the argument is convincing, it's necessary that we hear the other side.", accepted: ["Benché l'argomentazione sia convincente, è necessario che ascoltiamo anche l'altra parte."], hint: "Benché triggers the congiuntivo (sia), and è necessario che also triggers the congiuntivo (ascoltiamo).", tags: ["congiuntivo", "concessiva", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-026", type: "produce", prompt: "No matter how solid the premise seems, it's odd that no one questions it.", accepted: ["Per quanto la premessa sembri solida, è strano che nessuno la metta in discussione."], hint: "Per quanto triggers the congiuntivo (sembri), and è strano che also triggers the congiuntivo (metta).", tags: ["congiuntivo", "concessiva", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-027", type: "produce", prompt: "It's a good thing that we double-check the conclusion, even though it looks obvious.", accepted: ["È bene che verifichiamo la conclusione, anche se sembra ovvia."], hint: "È bene che triggers the congiuntivo (verifichiamo); anche se, by contrast, takes the indicativo (sembra), never the congiuntivo.", tags: ["congiuntivo", "indicativo", "impersonale", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-028", type: "produce", prompt: "Despite the deadline, it's important that the synthesis stays accurate.", accepted: ["Nonostante la scadenza, è importante che la sintesi resti precisa."], hint: "Nonostante takes a noun here; è importante che triggers the congiuntivo (resti).", tags: ["congiuntivo", "concessiva", "impersonale", "chunk"], tier: 3 },

    { id: "b153-t3-029", type: "produce", prompt: "I think the report needs a clearer conclusion so that readers understand the point.", accepted: ["Ritengo che il rapporto abbia bisogno di una conclusione più chiara affinché i lettori capiscano il punto."], hint: "Ritengo che triggers the congiuntivo (abbia bisogno), and affinché also triggers the congiuntivo (capiscano).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-030", type: "produce", prompt: "I suppose the teacher simplified the example so that everyone could follow the reasoning.", accepted: ["Suppongo che l'insegnante abbia semplificato l'esempio affinché tutti possano seguire il ragionamento."], hint: "Suppongo che triggers the congiuntivo passato (abbia semplificato), while affinché takes the congiuntivo presente (possano).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-031", type: "produce", prompt: "I'm convinced the company changed its register so that the message would seem more professional.", accepted: ["Sono convinto che l'azienda abbia cambiato il registro affinché il messaggio sembri più professionale.", "Sono convinta che l'azienda abbia cambiato il registro affinché il messaggio sembri più professionale."], hint: "Sono convinto/a che triggers the congiuntivo passato (abbia cambiato), and affinché also triggers the congiuntivo (sembri).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-032", type: "produce", prompt: "I imagine they added a comparison so that the point would be easier to grasp.", accepted: ["Immagino che abbiano aggiunto un paragone affinché il punto sia più facile da cogliere."], hint: "Immagino che triggers the congiuntivo passato (abbiano aggiunto), and affinché also triggers the congiuntivo (sia).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-033", type: "produce", prompt: "I consider that the editor cut the passage so that the argument stays focused.", accepted: ["Ritengo che il redattore abbia tagliato il passaggio affinché l'argomentazione resti focalizzata."], hint: "Ritengo che triggers the congiuntivo passato (abbia tagliato), and affinché also triggers the congiuntivo (resti).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-034", type: "produce", prompt: "I suppose he changed his point of view so that the negotiation could continue.", accepted: ["Suppongo che abbia cambiato punto di vista affinché la trattativa possa continuare."], hint: "Suppongo che triggers the congiuntivo passato (abbia cambiato), and affinché also triggers the congiuntivo (possa).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-035", type: "produce", prompt: "I'm convinced the professor repeats the premise so that no student misses it.", accepted: ["Sono convinto che il professore ripeta la premessa affinché nessuno studente se la perda.", "Sono convinta che il professore ripeta la premessa affinché nessuno studente se la perda."], hint: "Sono convinto/a che triggers the congiuntivo (ripeta), and affinché also triggers the congiuntivo (perda).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },

    { id: "b153-t3-036", type: "produce", prompt: "Since the flight was delayed, I'm glad we had more time to talk.", accepted: ["Dato che il volo era in ritardo, sono contento che abbiamo avuto più tempo per parlare.", "Dato che il volo era in ritardo, sono contenta che abbiamo avuto più tempo per parlare."], hint: "Dato che takes the indicativo (era), while sono contento/a che triggers the congiuntivo passato (abbiamo avuto).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-037", type: "produce", prompt: "Since the news was bad, I'm sorry that no one warned you earlier.", accepted: ["Dato che la notizia era brutta, mi dispiace che nessuno ti abbia avvertito prima."], hint: "Dato che takes the indicativo (era), while mi dispiace che triggers the congiuntivo passato (abbia avvertito).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-038", type: "produce", prompt: "As the project failed, we're worried that the client has lost confidence.", accepted: ["Poiché il progetto è fallito, siamo preoccupati che il cliente abbia perso fiducia."], hint: "Poiché takes the indicativo (passato prossimo), while siamo preoccupati che triggers the congiuntivo passato (abbia perso).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-039", type: "produce", prompt: "Since the results were unexpected, it surprises me that nobody double-checked them.", accepted: ["Dato che i risultati erano inaspettati, mi sorprende che nessuno li abbia controllati due volte."], hint: "Dato che takes the indicativo (erano), while mi sorprende che triggers the congiuntivo passato (abbia controllati).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-040", type: "produce", prompt: "As the deadline passed, I'm afraid the client is upset.", accepted: ["Dato che la scadenza è passata, ho paura che il cliente sia arrabbiato."], hint: "Dato che takes the indicativo (passato prossimo), while ho paura che triggers the congiuntivo (sia).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-041", type: "produce", prompt: "Since she apologized, I'm happy that the conflict is finally over.", accepted: ["Dato che si è scusata, sono felice che il conflitto sia finalmente finito."], hint: "Dato che takes the indicativo (passato prossimo), while sono felice che triggers the congiuntivo (sia finito).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-042", type: "produce", prompt: "As nobody answered, it's a shame that the opportunity was lost.", accepted: ["Dato che nessuno ha risposto, è un peccato che l'occasione sia andata persa."], hint: "Dato che takes the indicativo (passato prossimo), while è un peccato che triggers the congiuntivo passato (sia andata persa).", tags: ["indicativo", "congiuntivo", "causa", "emozione", "chunk"], tier: 3 },

    { id: "b153-t3-043", type: "produce", prompt: "I doubt the plan is realistic, and it's probable that we'll need a new one.", accepted: ["Dubito che il piano sia realistico, ed è probabile che ne serva uno nuovo."], hint: "Dubitare che triggers the congiuntivo (sia), and è probabile che also triggers the congiuntivo (serva).", tags: ["congiuntivo", "dubbio", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-044", type: "produce", prompt: "It may be that she already knows, although I doubt it.", accepted: ["Può darsi che lei sappia già, sebbene io ne dubiti."], hint: "Può darsi che triggers the congiuntivo (sappia), and sebbene also triggers the congiuntivo (dubiti); dubitarne means 'to doubt it' (dubitare + ne).", tags: ["congiuntivo", "impersonale", "concessiva", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-045", type: "produce", prompt: "It's necessary that we verify the source, since I doubt its reliability.", accepted: ["È necessario che verifichiamo la fonte, dato che dubito della sua affidabilità."], hint: "È necessario che triggers the congiuntivo (verifichiamo); dato che, by contrast, takes the indicativo (dubito).", tags: ["congiuntivo", "indicativo", "impersonale", "causa", "chunk"], tier: 3 },
    { id: "b153-t3-046", type: "produce", prompt: "I doubt this hypothesis is complete, and it's strange that no one has questioned it.", accepted: ["Dubito che questa ipotesi sia completa, ed è strano che nessuno l'abbia messa in discussione."], hint: "Dubitare che triggers the congiuntivo (sia), and è strano che triggers the congiuntivo passato (abbia messa).", tags: ["congiuntivo", "dubbio", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-047", type: "produce", prompt: "It's rare that a hypothesis convinces everyone, and I doubt this one is an exception.", accepted: ["È raro che un'ipotesi convinca tutti, e dubito che questa sia un'eccezione."], hint: "È raro che triggers the congiuntivo (convinca), and dubitare che also triggers the congiuntivo (sia).", tags: ["congiuntivo", "impersonale", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-048", type: "produce", prompt: "It may be that the connection is a coincidence, though I doubt it.", accepted: ["Può darsi che il collegamento sia una coincidenza, sebbene io ne dubiti."], hint: "Può darsi che triggers the congiuntivo (sia), and sebbene also triggers the congiuntivo (dubiti).", tags: ["congiuntivo", "impersonale", "concessiva", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-049", type: "produce", prompt: "I doubt the synthesis is objective, and it's obvious that the author has a point of view.", accepted: ["Dubito che la sintesi sia obiettiva, ed è ovvio che l'autore abbia un punto di vista."], hint: "Dubitare che triggers the congiuntivo (sia), and è ovvio che also triggers the congiuntivo (abbia).", tags: ["congiuntivo", "dubbio", "impersonale", "chunk"], tier: 3 },

    { id: "b153-t3-050", type: "produce", prompt: "Even though the plan is risky, we'll go ahead.", accepted: ["Anche se il piano è rischioso, andiamo avanti."], hint: "Anche se takes the indicativo (è), never the congiuntivo.", tags: ["indicativo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-051", type: "produce", prompt: "Although the plan may be risky, we'll go ahead.", accepted: ["Sebbene il piano sia rischioso, andiamo avanti."], hint: "Sebbene takes the congiuntivo (sia); compare with the previous pair, which used anche se plus the indicativo.", tags: ["congiuntivo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-052", type: "produce", prompt: "Even though the argument seemed weak, the jury believed it.", accepted: ["Anche se l'argomentazione sembrava debole, la giuria ci ha creduto."], hint: "Anche se takes the indicativo (sembrava, imperfetto), never the congiuntivo.", tags: ["indicativo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-053", type: "produce", prompt: "Although the argument may seem weak, the jury believed it.", accepted: ["Benché l'argomentazione sembri debole, la giuria ci ha creduto."], hint: "Benché takes the congiuntivo (sembri); compare with anche se, which takes the indicativo.", tags: ["congiuntivo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-054", type: "produce", prompt: "Even though the hypothesis was wrong, it led to an important discovery.", accepted: ["Anche se l'ipotesi era sbagliata, ha portato a una scoperta importante."], hint: "Anche se takes the indicativo (era, imperfetto), never the congiuntivo.", tags: ["indicativo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-055", type: "produce", prompt: "Although the hypothesis may be wrong, it could still lead somewhere.", accepted: ["Sebbene l'ipotesi sia sbagliata, potrebbe comunque portare a qualcosa."], hint: "Sebbene takes the congiuntivo (sia); compare with anche se, which takes the indicativo.", tags: ["congiuntivo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-056", type: "produce", prompt: "Even though the register was too formal, everyone understood the message.", accepted: ["Anche se il registro era troppo formale, tutti hanno capito il messaggio."], hint: "Anche se takes the indicativo (era, imperfetto), never the congiuntivo.", tags: ["indicativo", "concessiva", "chunk"], tier: 3 },

    { id: "b153-t3-057", type: "produce", prompt: "I doubt the deduction is valid, so we should check the whole reasoning again.", accepted: ["Dubito che la deduzione sia valida, quindi dovremmo ricontrollare tutto il ragionamento."], hint: "Dubitare che triggers the congiuntivo (sia); quindi then introduces the consequence, taking the indicativo or condizionale.", tags: ["congiuntivo", "dubbio", "causa-effetto", "chunk"], tier: 3 },
    { id: "b153-t3-058", type: "produce", prompt: "It's obvious that the two positions contrast, although both have valid points.", accepted: ["È ovvio che le due posizioni siano in contrapposizione, sebbene entrambe abbiano punti validi."], hint: "È ovvio che triggers the congiuntivo (siano), and sebbene also triggers the congiuntivo (abbiano).", tags: ["congiuntivo", "impersonale", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-059", type: "produce", prompt: "I'm not certain the comparison is fair, and it bothers me that no one questioned it.", accepted: ["Non ho la certezza che il paragone sia giusto, e mi dà fastidio che nessuno l'abbia messo in discussione."], hint: "Non avere la certezza che triggers the congiuntivo (sia), and mi dà fastidio che triggers the congiuntivo passato (abbia messo).", tags: ["congiuntivo", "dubbio", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-060", type: "produce", prompt: "The professor rewrote the conclusion so that the coherence of the whole essay improves.", accepted: ["Il professore ha riscritto la conclusione affinché la coerenza dell'intero saggio migliori."], hint: "Affinché triggers the congiuntivo (migliori); the two clauses have different subjects (professore / coerenza).", tags: ["congiuntivo", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-061", type: "produce", prompt: "Since the connector was missing, the sentence lacked coherence, so we added tuttavia.", accepted: ["Siccome mancava il connettivo, la frase non aveva coerenza, quindi abbiamo aggiunto tuttavia."], hint: "Siccome takes the indicativo (mancava); quindi then introduces the consequence.", tags: ["indicativo", "causa-effetto", "chunk"], tier: 3 },
    { id: "b153-t3-062", type: "produce", prompt: "Although I doubt his deduction, I admit the reasoning is convincing.", accepted: ["Sebbene dubiti della sua deduzione, ammetto che il ragionamento è convincente."], hint: "Sebbene triggers the congiuntivo (dubiti); ammettere che, by contrast, takes the indicativo (è) — ammettere does not require the congiuntivo.", tags: ["congiuntivo", "indicativo", "concessiva", "chunk"], tier: 3 },
    { id: "b153-t3-063", type: "produce", prompt: "It's a shame that the point of view of the minority doesn't count more.", accepted: ["È un peccato che il punto di vista della minoranza non conti di più."], hint: "È un peccato che triggers the congiuntivo; contare → conti.", tags: ["congiuntivo", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-064", type: "produce", prompt: "Given that the premise was false, it's obvious that the conclusion can't hold.", accepted: ["Dato che la premessa era falsa, è ovvio che la conclusione non possa reggere."], hint: "Dato che takes the indicativo (era), while è ovvio che triggers the congiuntivo (possa).", tags: ["indicativo", "congiuntivo", "causa", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-065", type: "produce", prompt: "I imagine the editor changed the register so that the text seems less academic.", accepted: ["Immagino che il redattore abbia cambiato il registro affinché il testo sembri meno accademico."], hint: "Immagino che triggers the congiuntivo passato (abbia cambiato), and affinché also triggers the congiuntivo (sembri).", tags: ["congiuntivo", "opinione", "scopo", "chunk"], tier: 3 },
    { id: "b153-t3-066", type: "produce", prompt: "Since the two theories contradict each other, it's necessary that we choose one.", accepted: ["Siccome le due teorie si contraddicono, è necessario che ne scegliamo una."], hint: "Siccome takes the indicativo (si contraddicono), while è necessario che triggers the congiuntivo (scegliamo).", tags: ["indicativo", "congiuntivo", "causa", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-067", type: "produce", prompt: "Although I consider the synthesis excellent, I doubt it captures every nuance.", accepted: ["Sebbene io ritenga eccellente la sintesi, dubito che colga ogni sfumatura."], hint: "Sebbene triggers the congiuntivo (ritenga), and dubitare che also triggers the congiuntivo (colga).", tags: ["congiuntivo", "concessiva", "opinione", "dubbio", "chunk"], tier: 3 },
    { id: "b153-t3-068", type: "produce", prompt: "It's probable that the two arguments will end up in direct contrast.", accepted: ["È probabile che i due argomenti finiscano in aperta contrapposizione."], hint: "È probabile che triggers the congiuntivo; finire → finiscano.", tags: ["congiuntivo", "impersonale", "chunk"], tier: 3 },
    { id: "b153-t3-069", type: "produce", prompt: "I'm glad the connector makes the reasoning so much clearer.", accepted: ["Sono contento che il connettivo renda il ragionamento molto più chiaro.", "Sono contenta che il connettivo renda il ragionamento molto più chiaro."], hint: "Sono contento/a che triggers the congiuntivo; rendere → renda.", tags: ["congiuntivo", "emozione", "chunk"], tier: 3 },
    { id: "b153-t3-070", type: "produce", prompt: "Even though the register was too formal, I doubt anyone actually minded.", accepted: ["Anche se il registro era troppo formale, dubito che a qualcuno sia davvero importato."], hint: "Anche se takes the indicativo (era); dubitare che, in the same sentence, triggers the congiuntivo passato (sia importato).", tags: ["indicativo", "congiuntivo", "concessiva", "dubbio", "chunk"], tier: 3 },

    // ── Tier 4 – Passages: multi-category synthesis, one blank each ──────────
    {
      id: "b153-t4-001",
      type: "passage_cloze",
      prompt: "Elena si prepara per un colloquio importante e ripassa ogni possibile domanda con sua sorella. Sebbene il ragionamento dietro le sue risposte ___ (essere) solido, teme di bloccarsi davanti al selezionatore. Dato che ha già affrontato altri colloqui simili, sa gestire la tensione meglio di prima. Sua sorella le ricorda che, anche se l'ansia è normale, la sua preparazione parla da sola.",
      accepted: ["sia"],
      hint: "Sebbene always takes the congiuntivo; essere → sia.",
      tags: ["congiuntivo", "concessiva", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-009", "b153-t2-010"],
    },
    {
      id: "b153-t4-002",
      type: "passage_cloze",
      prompt: "Il comune ha organizzato un referendum sul nuovo parco cittadino, e molti abitanti dubitano che il progetto ___ (essere) davvero necessario. Il sindaco ritiene che il parco porti benefici concreti al quartiere, ma alcuni residenti temono il rumore dei lavori. Nonostante le proteste, il consiglio ha deciso di procedere affinché i cittadini abbiano presto un nuovo spazio verde. La contrapposizione tra favorevoli e contrari resta molto accesa.",
      accepted: ["sia"],
      hint: "Dubitare che triggers the congiuntivo; essere → sia.",
      tags: ["congiuntivo", "dubbio", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-023"],
    },
    {
      id: "b153-t4-003",
      type: "passage_cloze",
      prompt: "Da qualche giorno il nonno di Marco si sente stanco e ha perso l'appetito. La famiglia teme che ___ (esserci) qualcosa di serio, anche se il medico di famiglia lo ha visitato e sembra tranquillo. È necessario che il nonno faccia altri esami questa settimana, per avere maggiore certezza sulla diagnosi. Marco resta accanto a lui ogni sera, sperando che i risultati portino solo buone notizie.",
      accepted: ["ci sia"],
      hint: "Temere che triggers the congiuntivo; esserci → ci sia.",
      tags: ["congiuntivo", "emozione", "impersonale", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-001"],
    },
    {
      id: "b153-t4-004",
      type: "passage_cloze",
      prompt: "Giulia discute la sua tesi domani e ha rivisto ogni capitolo con la relatrice. Sebbene la conclusione ___ (sembrare) ben argomentata, la relatrice le consiglia di rafforzare la premessa iniziale. Giulia ha lavorato tutta la notte per rendere il ragionamento più coerente, cosicché la commissione possa seguire facilmente ogni passaggio. Nonostante la stanchezza, si sente pronta ad affrontare le domande.",
      accepted: ["sembri"],
      hint: "Sebbene takes the congiuntivo; sembrare → sembri.",
      tags: ["congiuntivo", "concessiva", "scopo", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-007", "b153-t1-005"],
    },
    {
      id: "b153-t4-005",
      type: "passage_cloze",
      prompt: "Un noto critico gastronomico ha scritto una recensione severa sul nuovo ristorante del centro. Il proprietario ritiene che il giudizio ___ (essere) troppo duro, dato che il locale ha aperto da appena un mese. Alcuni clienti, tuttavia, sono convinti che la critica contenga più di un punto di vista valido. Il proprietario ha deciso di rivedere il menu affinché i clienti tornino più soddisfatti.",
      accepted: ["sia"],
      hint: "Ritenere che triggers the congiuntivo; essere → sia.",
      tags: ["congiuntivo", "opinione", "causa", "scopo", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-031"],
    },
    {
      id: "b153-t4-006",
      type: "passage_cloze",
      prompt: "Due giovani imprenditori presentano il loro progetto a un gruppo di investitori scettici. Benché l'argomentazione ___ (risultare) convincente sulla carta, gli investitori dubitano che il mercato sia pronto per un prodotto così nuovo. I due fondatori hanno preparato una sintesi chiara affinché tutti capiscano subito il valore dell'idea. Nonostante le domande difficili, restano fiduciosi nel proprio progetto. Alla fine della presentazione, promettono di inviare un piano finanziario più dettagliato entro la prossima settimana.",
      accepted: ["risulti"],
      hint: "Benché takes the congiuntivo; risultare → risulti.",
      tags: ["congiuntivo", "concessiva", "dubbio", "scopo", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-011", "b153-t1-033"],
    },
    {
      id: "b153-t4-007",
      type: "passage_cloze",
      prompt: "Durante il processo, l'avvocato difensore sostiene che le prove ___ (essere) insufficienti per una condanna. Il pubblico ministero, al contrario, ritiene che il collegamento tra l'imputato e i fatti sia chiaro. Il giudice ha chiesto un rinvio affinché entrambe le parti possano presentare nuove prove. Fuori dal tribunale, i giornalisti discutono animatamente sulle possibili conclusioni del caso. Molti cronisti si chiedono se le nuove prove cambieranno davvero l'esito finale del processo prima di sera.",
      accepted: ["siano"],
      hint: "Sostenere che triggers the congiuntivo; essere → siano (le prove).",
      tags: ["congiuntivo", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-021"],
    },
    {
      id: "b153-t4-008",
      type: "passage_cloze",
      prompt: "I meteorologi non sono d'accordo sulla previsione per il weekend. Alcuni dubitano che la perturbazione ___ (arrivare) prima di sabato, mentre altri sono convinti che il tempo peggiorerà già venerdì sera. Gli organizzatori del festival all'aperto, dato che il rischio esiste comunque, hanno preparato un piano alternativo cosicché l'evento possa svolgersi al coperto in caso di pioggia. Il pubblico, però, continua a controllare le previsioni ogni ora, sperando che il sole vinca sulla pioggia.",
      accepted: ["arrivi"],
      hint: "Dubitare che triggers the congiuntivo; arrivare → arrivi.",
      tags: ["congiuntivo", "dubbio", "causa", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-009",
      type: "passage_cloze",
      prompt: "La mostra del giovane pittore ha diviso il pubblico fin dal primo giorno. Alcuni critici ritengono che le opere ___ (mancare) di originalità, mentre altri le considerano innovative. Sebbene il dibattito resti acceso, la galleria ha organizzato un incontro affinché il pubblico possa parlare direttamente con l'artista. Il pittore ascolta ogni opinione con curiosità, senza sembrare turbato dalle critiche. Alla fine della serata, promette di tornare presto con nuove opere che rispondano proprio a quei dubbi.",
      accepted: ["manchino"],
      hint: "Ritenere che triggers the congiuntivo; mancare → manchino.",
      tags: ["congiuntivo", "opinione", "concessiva", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-010",
      type: "passage_cloze",
      prompt: "Durante la riunione comunale, alcuni cittadini dubitano che il nuovo piano ambientale ___ (bastare) a ridurre l'inquinamento del fiume. L'assessore ritiene che la proposta sia un primo passo importante, anche se ammette che serviranno altri interventi. Il comune ha promesso nuovi fondi affinché gli agricoltori della zona possano adattare i propri metodi. La discussione continuerà nella prossima seduta. Nel frattempo, alcuni volontari hanno iniziato a raccogliere firme per chiedere controlli più frequenti sulla qualità dell'acqua.",
      accepted: ["basti"],
      hint: "Dubitare che triggers the congiuntivo; bastare → basti.",
      tags: ["congiuntivo", "dubbio", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-011",
      type: "passage_cloze",
      prompt: "Una traduttrice deve scegliere tra due versioni di una frase ambigua in un romanzo straniero. Immagina che l'autore ___ (volere) mantenere una certa sfumatura ironica, anche se il contesto lascia spazio a dubbi. Chiede consiglio a un collega, il quale ritiene che la prima versione renda meglio il registro originale del testo. Alla fine, sceglie la soluzione che le sembra più fedele allo spirito del libro.",
      accepted: ["voglia"],
      hint: "Immaginare che triggers the congiuntivo; volere → voglia.",
      tags: ["congiuntivo", "opinione", "concessiva", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-015", "b153-t1-017"],
    },
    {
      id: "b153-t4-012",
      type: "passage_cloze",
      prompt: "Il centrocampista si è infortunato durante l'ultimo allenamento e i tifosi temono che non ___ (potere) giocare la finale di sabato. L'allenatore, tuttavia, è convinto che il giocatore recupererà in tempo, dato che l'infortunio non sembra grave. La squadra continua gli allenamenti affinché tutti siano pronti, con o senza di lui, per la partita più importante della stagione. I tifosi, intanto, seguono ogni aggiornamento medico sperando in buone notizie prima del fischio d'inizio.",
      accepted: ["possa"],
      hint: "Temere che triggers the congiuntivo; potere → possa.",
      tags: ["congiuntivo", "emozione", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-013",
      type: "passage_cloze",
      prompt: "Durante il dibattito televisivo, i due candidati si scambiano accuse sull'economia della regione. Uno ritiene che i dati ___ (dimostrare) un miglioramento reale, mentre l'altro dubita della loro affidabilità. Nonostante il tono acceso, i moderatori chiedono a entrambi di chiarire le proprie proposte affinché gli elettori possano scegliere con maggiore consapevolezza prima del voto di domenica. A casa, molti spettatori commentano il dibattito sui social, ognuno convinto che il proprio candidato abbia vinto lo scontro.",
      accepted: ["dimostrino"],
      hint: "Ritenere che triggers the congiuntivo; dimostrare → dimostrino.",
      tags: ["congiuntivo", "opinione", "concessiva", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-014",
      type: "passage_cloze",
      prompt: "La guida spiega ai visitatori la storia di un antico affresco appena restaurato. Alcuni esperti dubitano che il restauro ___ (rispettare) del tutto i colori originali, ma il direttore del museo è convinto che il risultato sia fedele alle fonti storiche. La guida invita il gruppo a osservare da vicino, cosicché ognuno possa farsi una propria opinione sull'opera. Un bambino nel gruppo chiede timidamente perché gli antichi pittori scegliessero proprio quei colori così vivaci.",
      accepted: ["rispetti"],
      hint: "Dubitare che triggers the congiuntivo; rispettare → rispetti.",
      tags: ["congiuntivo", "dubbio", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-015",
      type: "passage_cloze",
      prompt: "Il team tecnico non riesce a capire perché l'applicazione si blocchi ogni mattina alla stessa ora. Un programmatore ritiene che il problema ___ (dipendere) da un aggiornamento recente, mentre un collega dubita che sia davvero questa la causa. Hanno deciso di controllare i registri del sistema riga per riga, in modo che l'errore emerga con certezza prima del prossimo rilascio.",
      accepted: ["dipenda"],
      hint: "Ritenere che triggers the congiuntivo; dipendere → dipenda.",
      tags: ["congiuntivo", "opinione", "dubbio", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-016",
      type: "passage_cloze",
      prompt: "Due vicini discutono da settimane per un albero che getta ombra sull'orto dell'altro. Uno ritiene che il ramo ___ (dovere) essere tagliato, mentre l'altro pensa che il danno sia esagerato. Il condominio ha proposto un incontro affinché entrambi trovino un accordo, dato che la tensione tra i due comincia a disturbare tutto il palazzo. Alcuni altri residenti, stanchi della lite continua, hanno chiesto all'amministratore di intervenire prima che la situazione peggiori ulteriormente.",
      accepted: ["debba"],
      hint: "Ritenere che triggers the congiuntivo; dovere → debba.",
      tags: ["congiuntivo", "opinione", "scopo", "causa", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-017",
      type: "passage_cloze",
      prompt: "Durante la gara culinaria, un giudice dubita che il piatto del concorrente ___ (rispettare) il tema della serata. Un altro giudice, invece, ritiene che l'originalità della ricetta meriti punti extra. Il concorrente ascolta i commenti con calma, convinto che il sapore, alla fine, parlerà più di ogni regola scritta sul foglio della gara. Il pubblico in sala applaude comunque, incuriosito dal coraggio di uscire così tanto dallo schema previsto.",
      accepted: ["rispetti"],
      hint: "Dubitare che triggers the congiuntivo; rispettare → rispetti.",
      tags: ["congiuntivo", "dubbio", "opinione", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-018",
      type: "passage_cloze",
      prompt: "L'aereo per Roma è fermo da due ore e i passeggeri cominciano a dubitare che il volo ___ (partire) prima di sera. Il personale di terra spiega che il ritardo dipende dal maltempo, e che stanno lavorando affinché tutti possano imbarcarsi il prima possibile. Alcuni passeggeri restano comunque scettici sulle informazioni ricevute. Un uomo anziano, seduto vicino al finestrino, ripete più volte che avrebbe dovuto scegliere un treno invece dell'aereo.",
      accepted: ["parta"],
      hint: "Dubitare che triggers the congiuntivo; partire → parta.",
      tags: ["congiuntivo", "dubbio", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
    {
      id: "b153-t4-019",
      type: "passage_cloze",
      prompt: "Il gruppo di lettura discute animatamente sul finale del romanzo appena letto. Alcuni membri dubitano che l'autrice ___ (volere) davvero lasciare un finale così aperto, mentre altri lo trovano perfettamente coerente con il resto della storia. Nonostante le opinioni diverse, tutti concordano che la sintesi finale del libro resta memorabile. Una lettrice propone persino di scrivere all'autrice per chiederle direttamente cosa intendesse davvero con quel finale.",
      accepted: ["voglia"],
      hint: "Dubitare che triggers the congiuntivo; volere → voglia.",
      tags: ["congiuntivo", "dubbio", "concessiva", "passage_cloze", "tier4"],
      tier: 4,
      prerequisites: ["b153-t1-029"],
    },
    {
      id: "b153-t4-020",
      type: "passage_cloze",
      prompt: "Un consulente finanziario spiega a una coppia le opzioni per la pensione. Loro dubitano che il piano proposto ___ (garantire) abbastanza sicurezza per il futuro, mentre il consulente ritiene che la strategia sia equilibrata. Decidono comunque di prendersi qualche giorno per riflettere, affinché la scelta finale rispecchi davvero le loro priorità. Il consulente promette di richiamarli entro la settimana per rispondere a ogni ultimo dubbio rimasto.",
      accepted: ["garantisca"],
      hint: "Dubitare che triggers the congiuntivo; garantire is an -isc- verb, so garantire → garantisca.",
      tags: ["congiuntivo", "dubbio", "opinione", "scopo", "passage_cloze", "tier4"],
      tier: 4,
    },
  ],
};
export default unit;
