import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-41-society-social-life",
  name: "Community and Connection",
  level: "B1",
  theme: "Society & Social Life",
  emoji: "🤝",
  prerequisiteUnits: [],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    { id: "b141-t1-001", type: "recognize", prompt: "il vicino / la vicina", accepted: ["the neighbor"], hint: "masculine or feminine by article; the person living next door or nearby", tags: ["noun", "people", "vocab"], tier: 1 },
    { id: "b141-t1-002", type: "produce", prompt: "the neighbor", accepted: ["il vicino", "la vicina"], hint: "'vicino di casa' is the common phrase for a next-door neighbor; the masculine plural 'i vicini' also covers a mixed-gender group", tags: ["noun", "people", "vocab"], tier: 1 },
    { id: "b141-t1-003", type: "recognize", prompt: "il vicinato", accepted: ["the neighborhood","the neighborhood (the neighbors as a group)"], hint: "masculine noun; the neighbors collectively, not the physical area", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-004", type: "produce", prompt: "the neighborhood (the neighbors collectively)", accepted: ["il vicinato"], hint: "masculine noun 'il vicinato', distinct from 'il quartiere' (the area itself)", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-005", type: "recognize", prompt: "il quartiere", accepted: ["the district", "the neighborhood (area)"], hint: "masculine noun; a district or area of a city or town", tags: ["noun", "place", "vocab"], tier: 1 },
    { id: "b141-t1-006", type: "produce", prompt: "the district / neighborhood (area)", accepted: ["il quartiere"], hint: "masculine noun; distinct from 'il vicinato' (the neighbors as a group) — 'il quartiere' is the physical area itself", tags: ["noun", "place", "vocab"], tier: 1 },
    { id: "b141-t1-007", type: "recognize", prompt: "la comunità", accepted: ["the community"], hint: "feminine noun, invariable in the plural", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-008", type: "produce", prompt: "the community", accepted: ["la comunità"], hint: "feminine noun 'la comunità', invariable plural", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-009", type: "recognize", prompt: "il volontariato", accepted: ["the volunteering", "volunteer work"], hint: "masculine noun; the activity itself, not the person", tags: ["noun", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-010", type: "produce", prompt: "volunteering / volunteer work", accepted: ["il volontariato"], hint: "masculine noun built from 'volontario' (volunteer) plus the suffix -ato, naming the activity itself rather than the person", tags: ["noun", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-011", type: "recognize", prompt: "il volontario / la volontaria", accepted: ["the volunteer"], hint: "the person who volunteers, masculine or feminine", tags: ["noun", "people", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-012", type: "produce", prompt: "the volunteer", accepted: ["il volontario", "la volontaria"], hint: "shares a root with 'volontariato' (volunteer work) and 'volontà' (will) — someone who acts by free will, not obligation", tags: ["noun", "people", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-013", type: "recognize", prompt: "l'associazione", accepted: ["the association"], hint: "feminine noun starting with a vowel", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-014", type: "produce", prompt: "the association", accepted: ["l'associazione"], hint: "feminine noun; nouns ending in -zione are always feminine in Italian, like most abstract nouns of this pattern", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-015", type: "recognize", prompt: "la generazione", accepted: ["the generation"], hint: "feminine noun", tags: ["noun", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-016", type: "produce", prompt: "the generation", accepted: ["la generazione"], hint: "feminine noun; another -zione noun, root of both 'divario generazionale' (generation gap) and 'ricambio generazionale' (generational turnover)", tags: ["noun", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-017", type: "recognize", prompt: "il divario generazionale", accepted: ["the generation gap"], hint: "masculine noun phrase; the gap in outlook between age groups", tags: ["noun", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-018", type: "produce", prompt: "the generation gap", accepted: ["il divario generazionale"], hint: "masculine noun phrase, same as the recognize card above — pairs with 'colmare' (to bridge/fill) in 'colmare il divario generazionale'", tags: ["noun", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-019", type: "recognize", prompt: "l'anziano / l'anziana", accepted: ["the elderly person"], hint: "noun for an elderly person, masculine or feminine", tags: ["noun", "people", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-020", type: "produce", prompt: "the elderly person", accepted: ["l'anziano", "l'anziana"], hint: "more respectful in register than 'vecchio'; also works as an adjective, as in 'una signora anziana'", tags: ["noun", "people", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-021", type: "recognize", prompt: "il coetaneo / la coetanea", accepted: ["the peer","the peer (person of the same age)"], hint: "someone of the same age as you", tags: ["noun", "people", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-022", type: "produce", prompt: "the peer (person of the same age)", accepted: ["il coetaneo", "la coetanea"], hint: "built on 'età' (age) — a 'coetaneo' shares your età; collocates with 'di' as in 'essere coetaneo di qualcuno'", tags: ["noun", "people", "generations", "vocab"], tier: 1 },
    { id: "b141-t1-023", type: "recognize", prompt: "il sostegno", accepted: ["the support"], hint: "masculine noun; emotional or practical backing", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-024", type: "produce", prompt: "the support", accepted: ["il sostegno"], hint: "masculine noun from 'sostenere' (to support/sustain) — practical or emotional backing, as in 'il sostegno tra coetanei'", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-025", type: "recognize", prompt: "la raccolta fondi", accepted: ["the fundraiser"], hint: "feminine compound noun; an organized effort to collect money", tags: ["noun", "event", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-026", type: "produce", prompt: "the fundraiser", accepted: ["la raccolta fondi"], hint: "feminine compound noun, literally 'collection of funds' — 'fondi' stays plural even though 'raccolta' is singular", tags: ["noun", "event", "volunteering", "vocab"], tier: 1 },
    { id: "b141-t1-027", type: "recognize", prompt: "l'isolamento", accepted: ["the isolation"], hint: "masculine noun starting with a vowel", tags: ["noun", "emotion", "vocab"], tier: 1 },
    { id: "b141-t1-028", type: "produce", prompt: "the isolation", accepted: ["l'isolamento"], hint: "masculine noun built from 'isolare' (to isolate) plus -mento, the standard suffix for turning a verb into an abstract noun", tags: ["noun", "emotion", "vocab"], tier: 1 },
    { id: "b141-t1-029", type: "recognize", prompt: "la solitudine", accepted: ["the loneliness"], hint: "feminine noun; the state of being alone", tags: ["noun", "emotion", "vocab"], tier: 1 },
    { id: "b141-t1-030", type: "produce", prompt: "the loneliness", accepted: ["la solitudine"], hint: "feminine noun ending in -tudine, always feminine; more emotionally loaded than the plain adjective 'solo' (alone)", tags: ["noun", "emotion", "vocab"], tier: 1 },
    { id: "b141-t1-031", type: "recognize", prompt: "il condominio", accepted: ["the apartment building", "the condo"], hint: "masculine noun; a building with multiple owners or tenants", tags: ["noun", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-032", type: "produce", prompt: "the apartment building / condo", accepted: ["il condominio"], hint: "masculine noun; names both the building itself and the shared ownership arrangement, so 'riunione di condominio' means the residents' meeting", tags: ["noun", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-033", type: "recognize", prompt: "l'iniziativa", accepted: ["the initiative"], hint: "feminine noun starting with a vowel", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-034", type: "produce", prompt: "the initiative", accepted: ["l'iniziativa"], hint: "feminine noun; collocates with 'prendere l'iniziativa' (to take the initiative) and 'un'iniziativa di quartiere' (a neighborhood initiative)", tags: ["noun", "community", "vocab"], tier: 1 },
    { id: "b141-t1-035", type: "recognize", prompt: "il conoscente / la conoscente", accepted: ["the acquaintance"], hint: "someone you know a little, not a close friend", tags: ["noun", "people", "relationship", "vocab"], tier: 1 },
    { id: "b141-t1-036", type: "produce", prompt: "the acquaintance", accepted: ["il conoscente", "la conoscente"], hint: "same form for masculine and feminine, only the article changes", tags: ["noun", "people", "relationship", "vocab"], tier: 1 },
    { id: "b141-t1-037", type: "recognize", prompt: "la convivenza", accepted: ["the coexistence", "the cohabitation"], hint: "feminine noun; living together and sharing daily life", tags: ["noun", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-038", type: "produce", prompt: "the coexistence / cohabitation", accepted: ["la convivenza"], hint: "feminine noun from 'convivere' (to live together) — describes an ongoing state, not a single event", tags: ["noun", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-039", type: "recognize", prompt: "l'inquilino / l'inquilina", accepted: ["the tenant"], hint: "the person who rents, masculine or feminine", tags: ["noun", "people", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-040", type: "produce", prompt: "the tenant", accepted: ["l'inquilino", "l'inquilina"], hint: "the counterpart of 'il padrone di casa' (the landlord); collocates with 'affittare a' — to rent to a tenant", tags: ["noun", "people", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-041", type: "recognize", prompt: "l'appartenenza", accepted: ["the sense of belonging", "belonging"], hint: "feminine noun; the feeling of being part of something", tags: ["noun", "emotion", "community", "vocab"], tier: 1 },
    { id: "b141-t1-042", type: "produce", prompt: "the sense of belonging", accepted: ["l'appartenenza"], hint: "feminine noun from 'appartenere' (to belong) — almost always paired with 'senso di' in 'il senso di appartenenza'", tags: ["noun", "emotion", "community", "vocab"], tier: 1 },
    { id: "b141-t1-043", type: "recognize", prompt: "il dirimpettaio / la dirimpettaia", accepted: ["the neighbor across the street", "the neighbor across the way"], hint: "the neighbor who lives directly across from you", tags: ["noun", "people", "vocab"], tier: 1 },
    { id: "b141-t1-044", type: "produce", prompt: "the neighbor across the street", accepted: ["il dirimpettaio", "la dirimpettaia"], hint: "derives from 'di rimpetto' (across, opposite) — literally 'the one across the way'; less common in speech than 'vicino' but more precise", tags: ["noun", "people", "vocab"], tier: 1 },
    { id: "b141-t1-045", type: "recognize", prompt: "la sagra", accepted: ["the local festival", "the fair"], hint: "feminine noun; a local festival, often centered on a food or patron saint", tags: ["noun", "event", "vocab"], tier: 1 },
    { id: "b141-t1-046", type: "produce", prompt: "the local festival / fair", accepted: ["la sagra"], hint: "feminine noun; specifically a local festival tied to a food or a patron saint, narrower than the general word 'festa'", tags: ["noun", "event", "vocab"], tier: 1 },
    { id: "b141-t1-047", type: "recognize", prompt: "il portinaio / la portinaia", accepted: ["the building caretaker", "the doorman"], hint: "the person who looks after the entrance of a building", tags: ["noun", "people", "housing", "vocab"], tier: 1 },
    { id: "b141-t1-048", type: "produce", prompt: "the building caretaker / doorman", accepted: ["il portinaio", "la portinaia"], hint: "from 'porta' (door) — works out of the building's 'portineria' (lodge), a role fading in newer buildings", tags: ["noun", "people", "housing", "vocab"], tier: 1 },

    // ── Tier 2 – Grammar: Imperfetto (community nostalgia) ──────────────────
    { id: "b141-t2-001", type: "fill_blank", prompt: "Quando ero bambino, tutti i vicini del palazzo ___ per nome. (imperfetto di 'chiamarsi', loro)", accepted: ["si chiamavano"], hint: "imperfetto of 'chiamarsi' (to be named/called) — describes a habitual past state", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-002", type: "fill_blank", prompt: "Negli anni Ottanta, la gente ___ i vicini per strada tutte le sere. (imperfetto di 'salutare')", accepted: ["salutava"], hint: "imperfetto for a repeated past habit", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-003", type: "fill_blank", prompt: "Una volta, gli abitanti del palazzo ___ senza mai chiudere la porta a chiave. (imperfetto di 'vivere')", accepted: ["vivevano"], hint: "imperfetto describing an ongoing past way of life", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-004", type: "fill_blank", prompt: "Quando i miei nonni erano giovani, ___ molta più solidarietà tra vicini rispetto a oggi. (imperfetto di 'esserci')", accepted: ["c'era"], hint: "'c'era' — imperfetto of 'esserci', singular for an uncountable idea", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-005", type: "fill_blank", prompt: "Da piccola, io ___ con i bambini del palazzo ogni pomeriggio dopo la scuola. (imperfetto di 'giocare')", accepted: ["giocavo"], hint: "imperfetto, io form", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-006", type: "fill_blank", prompt: "I miei genitori raccontano che il portinaio ___ sempre un occhio sui bambini del condominio. (imperfetto di 'tenere')", accepted: ["teneva"], hint: "'tenere un occhio su' + imperfetto for a habitual past role", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-007", type: "fill_blank", prompt: "Prima dell'arrivo dei telefonini, i vicini ___ molto più spesso tra loro sulle scale. (imperfetto di 'parlare')", accepted: ["parlavano"], hint: "imperfetto, loro form", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-008", type: "fill_blank", prompt: "Quand'ero giovane, la gente si ___ degli sconosciuti meno di oggi. (imperfetto di 'fidare')", accepted: ["fidava"], hint: "'fidarsi di' + imperfetto for a general past attitude", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-009", type: "fill_blank", prompt: "Una volta, una stretta di mano ___ per sigillare un accordo tra vicini di quartiere. (imperfetto di 'bastare')", accepted: ["bastava"], hint: "imperfetto of 'bastare' (to be enough)", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },
    { id: "b141-t2-010", type: "fill_blank", prompt: "Ogni estate, tutto il vicinato ___ alla sagra del paese insieme. (imperfetto di 'andare')", accepted: ["andava"], hint: "imperfetto for a repeated seasonal habit", tags: ["grammar", "imperfetto", "fill_blank"], tier: 2 },

    // ── Tier 2 – Grammar: Si impersonale (community norms) ──────────────────
    { id: "b141-t2-011", type: "fill_blank", prompt: "In questo quartiere, ___ molta attenzione ai vicini anziani. (si impersonale di 'prestare')", accepted: ["si presta"], hint: "'si presta attenzione a' — si impersonale, present", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-012", type: "fill_blank", prompt: "Nel nostro condominio, ___ le spese comuni una volta al mese. (si impersonale di 'dividere')", accepted: ["si dividono"], hint: "si impersonale agrees in the plural with 'le spese'", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-013", type: "fill_blank", prompt: "Quando c'è un problema nel palazzo, ___ subito una riunione di condominio. (si impersonale di 'organizzare')", accepted: ["si organizza"], hint: "si impersonale, singular subject 'una riunione'", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-014", type: "fill_blank", prompt: "Nella nostra comunità, ___ sempre una mano a chi ne ha bisogno. (si impersonale di 'dare')", accepted: ["si dà"], hint: "'dare una mano' (to lend a hand) stays fixed while si impersonale turns the sentence into a general statement about people", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-015", type: "fill_blank", prompt: "Al giorno d'oggi, ___ meno tempo per chiacchierare con i vicini rispetto al passato. (si impersonale di 'avere')", accepted: ["si ha"], hint: "si impersonale of 'avere'", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-016", type: "fill_blank", prompt: "In molti quartieri italiani, ___ ancora il caffè al dirimpettaio la domenica mattina. (si impersonale di 'offrire')", accepted: ["si offre"], hint: "si impersonale, singular", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-017", type: "fill_blank", prompt: "Per organizzare una festa di quartiere, ___ prima il permesso al portinaio per usare il cortile. (si impersonale di 'chiedere')", accepted: ["si chiede"], hint: "si impersonale, singular direct object 'il permesso'", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-018", type: "fill_blank", prompt: "Con il volontariato, ___ qualcosa alla propria comunità. (si impersonale di 'restituire')", accepted: ["si restituisce"], hint: "si impersonale of a -ire verb", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-019", type: "fill_blank", prompt: "Durante la sagra, ___ le bancarelle già dal mattino presto. (si impersonale di 'allestire')", accepted: ["si allestiscono"], hint: "si impersonale agrees in the plural with 'le bancarelle'", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },
    { id: "b141-t2-020", type: "fill_blank", prompt: "Quando un nuovo inquilino arriva nel palazzo, ___ sempre di presentarlo agli altri vicini. (si impersonale di 'cercare')", accepted: ["si cerca"], hint: "'si cerca di' + infinitive", tags: ["grammar", "si-impersonale", "fill_blank"], tier: 2 },

    // ── Tier 2 – Grammar: Relative pronouns che / cui / chi ──────────────────
    { id: "b141-t2-021", type: "fill_blank", prompt: "Il vicino ___ mi ha aiutato a traslocare abita al terzo piano. (pronome relativo soggetto)", accepted: ["che"], hint: "'che' as the subject of the relative clause", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-022", type: "fill_blank", prompt: "La signora anziana a ___ porto la spesa ogni settimana si chiama Rosa. (pronome relativo dopo la preposizione 'a')", accepted: ["cui"], hint: "after a preposition, 'cui' replaces 'che'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-023", type: "fill_blank", prompt: "___ fa volontariato ogni fine settimana merita rispetto. (pronome relativo indefinito: 'chiunque')", accepted: ["Chi"], hint: "'chi' meaning 'whoever' at the start of a sentence", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-024", type: "fill_blank", prompt: "L'associazione di ___ faccio parte organizza la sagra ogni estate. (pronome relativo dopo la preposizione 'di')", accepted: ["cui"], hint: "'fare parte di cui' — 'cui' after 'di'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-025", type: "fill_blank", prompt: "I coetanei con ___ sono cresciuto vivono ancora nel mio quartiere. (pronome relativo dopo la preposizione 'con')", accepted: ["cui"], hint: "'cui' after 'con'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-026", type: "fill_blank", prompt: "Il volontario ___ ho conosciuto ieri lavora anche al centro anziani. (pronome relativo oggetto)", accepted: ["che"], hint: "'che' as the object of the relative clause", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-027", type: "fill_blank", prompt: "Il portinaio, ___ conosce tutti nel palazzo, mi ha presentato il nuovo inquilino. (pronome relativo soggetto)", accepted: ["che"], hint: "'che' as the subject, in a non-restrictive clause set off by commas", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-028", type: "fill_blank", prompt: "Non c'è nessuno nel vicinato ___ non conosca almeno di vista il dirimpettaio. (pronome relativo dopo 'nessuno')", accepted: ["che"], hint: "'che' introducing a subjunctive clause after 'nessuno'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-029", type: "fill_blank", prompt: "La ragione per ___ i vicini si aiutano è semplice: si conoscono da una vita. (pronome relativo dopo la preposizione 'per')", accepted: ["cui"], hint: "'cui' after 'per'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },
    { id: "b141-t2-030", type: "fill_blank", prompt: "L'iniziativa ___ ha organizzato l'associazione ha coinvolto tutto il quartiere. (pronome relativo oggetto)", accepted: ["che"], hint: "'che' as the object, referring back to 'l'iniziativa'", tags: ["grammar", "relative-pronouns", "fill_blank"], tier: 2 },

    // ── Tier 2 – Grammar: Congiuntivo (opinion, doubt, necessity about social trends) ──
    { id: "b141-t2-031", type: "fill_blank", prompt: "Penso che il volontariato ___ un modo importante per rafforzare la comunità. (congiuntivo presente di 'essere')", accepted: ["sia"], hint: "penso che always triggers the congiuntivo presente in the clause that follows", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-032", type: "fill_blank", prompt: "Molti credono che i giovani ___ meno legati al proprio quartiere rispetto al passato. (congiuntivo presente di 'essere')", accepted: ["siano"], hint: "'credere che' + congiuntivo presente, plural subject", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-033", type: "fill_blank", prompt: "Non credo che l'isolamento ___ solo un problema degli anziani. (congiuntivo presente di 'essere')", accepted: ["sia"], hint: "negative opinion verb + congiuntivo", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-034", type: "fill_blank", prompt: "È importante che ogni quartiere ___ un'associazione attiva. (congiuntivo presente di 'avere')", accepted: ["abbia"], hint: "impersonal 'è importante che' + congiuntivo", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-035", type: "fill_blank", prompt: "Sembra che la partecipazione alla sagra ___ negli ultimi anni. (congiuntivo passato di 'crescere')", accepted: ["sia cresciuta"], hint: "the congiuntivo passato pairs the present subjunctive of essere with the past participle, giving sia cresciuta", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-036", type: "fill_blank", prompt: "Dubito che i coetanei di mio figlio ___ lo stesso senso di comunità che avevamo noi. (congiuntivo presente di 'provare')", accepted: ["provino"], hint: "dubitare che triggers the congiuntivo; here it takes the loro form, provino", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-037", type: "fill_blank", prompt: "È un peccato che tanti anziani ___ soli in città senza nessuno che li aiuti. (congiuntivo presente di 'vivere')", accepted: ["vivano"], hint: "è un peccato che (it's a shame that) triggers the congiuntivo in the clause that follows", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-038", type: "fill_blank", prompt: "Spero che questa iniziativa ___ il divario generazionale nel nostro quartiere. (congiuntivo presente di 'colmare')", accepted: ["colmi"], hint: "spero che (I hope that) always triggers the congiuntivo presente", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-039", type: "fill_blank", prompt: "Bisogna che qualcuno ___ un occhio sugli anziani che vivono soli nel palazzo. (congiuntivo presente di 'tenere')", accepted: ["tenga"], hint: "'bisogna che' + congiuntivo, an impersonal necessity", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-040", type: "fill_blank", prompt: "È necessario che l'associazione ___ nuovi volontari prima della prossima raccolta fondi. (congiuntivo presente di 'trovare')", accepted: ["trovi"], hint: "è necessario che (it's necessary that) triggers the congiuntivo, since necessity is a subjunctive trigger", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-041", type: "fill_blank", prompt: "Non penso che il portinaio ___ tutti gli inquilini del palazzo. (congiuntivo presente di 'conoscere')", accepted: ["conosca"], hint: "negative opinion + congiuntivo", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-042", type: "fill_blank", prompt: "È probabile che la sagra di quest'anno ___ più visitatori del solito. (congiuntivo presente di 'attirare')", accepted: ["attiri"], hint: "è probabile che (it's probable that) triggers the congiuntivo, since probability, not certainty, calls for the subjunctive", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-043", type: "fill_blank", prompt: "Mi sembra strano che il nuovo inquilino non ___ ancora nessuno nel vicinato. (congiuntivo presente di 'conoscere')", accepted: ["conosca"], hint: "mi sembra strano che (it seems strange to me that) is an opinion trigger, so it takes the congiuntivo", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-044", type: "fill_blank", prompt: "Credo che ogni generazione ___ qualcosa da insegnare a quella successiva. (congiuntivo presente di 'avere')", accepted: ["abbia"], hint: "credo che (I believe that) triggers the congiuntivo presente the same way penso che and credere che do", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },
    { id: "b141-t2-045", type: "fill_blank", prompt: "È giusto che i vicini si ___ a vicenda quando c'è bisogno. (congiuntivo presente di 'sostenere')", accepted: ["sostengano"], hint: "è giusto che (it's right that) triggers the congiuntivo; here it takes the loro form, sostengano", tags: ["grammar", "congiuntivo", "fill_blank"], tier: 2 },

    // ── Tier 2 – Grammar: Da + duration ───────────────────────────────────────
    { id: "b141-t2-046", type: "fill_blank", prompt: "Abito in questo quartiere ___ dieci anni. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration with a present-tense verb", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-047", type: "fill_blank", prompt: "Conosco la mia vicina ___ quando eravamo bambine. (preposizione che significa 'since')", accepted: ["da"], hint: "'da quando' — since a point in time", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-048", type: "fill_blank", prompt: "Faccio volontariato in questa associazione ___ tre anni. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-049", type: "fill_blank", prompt: "Il signor Bruni vive nello stesso condominio ___ sempre. (avverbio: 'da sempre')", accepted: ["da sempre"], hint: "fixed expression 'da sempre' — for as long as anyone can remember", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-050", type: "fill_blank", prompt: "Ci frequentiamo ___ molto tempo, ormai il vicinato ci considera una famiglia. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-051", type: "fill_blank", prompt: "Il portinaio lavora in questo palazzo ___ vent'anni. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-052", type: "fill_blank", prompt: "La sagra si svolge in questo paese ___ generazioni. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration, here measured in generations rather than years", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-053", type: "fill_blank", prompt: "L'associazione organizza la raccolta fondi ___ tre anni ormai. (preposizione di durata)", accepted: ["da"], hint: "'da' + duration", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-054", type: "fill_blank", prompt: "___ quando è arrivato il nuovo inquilino, il palazzo sembra più unito. (locuzione: 'from when / since')", accepted: ["Da"], hint: "'da quando' at the start of a sentence", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },
    { id: "b141-t2-055", type: "fill_blank", prompt: "Mio nonno abita da solo ___ quando è morta mia nonna. (preposizione: 'since')", accepted: ["da"], hint: "'da quando' — since a past event, no article-contraction needed", tags: ["grammar", "da-durata", "fill_blank"], tier: 2 },

    // ── Tier 3 – Phrases & Collocations: Volunteering & initiative ───────────
    { id: "b141-t3-001", type: "produce", prompt: "to volunteer", accepted: ["fare volontariato"], hint: "'fare volontariato' — the general verb phrase for volunteering", tags: ["chunk", "volunteering"], tier: 3 },
    { id: "b141-t3-002", type: "produce", prompt: "to volunteer for an association", accepted: ["fare volontariato in un'associazione"], hint: "'fare volontariato in' + the organization", tags: ["chunk", "volunteering"], tier: 3 },
    { id: "b141-t3-003", type: "produce", prompt: "to organize a fundraiser for the elderly", accepted: ["organizzare una raccolta fondi per gli anziani"], hint: "'per' introduces the beneficiary of the fundraiser — the same pattern works for any cause, not only the elderly", tags: ["chunk", "volunteering", "fundraiser"], tier: 3 },
    { id: "b141-t3-004", type: "produce", prompt: "to take part in a community initiative", accepted: ["partecipare a un'iniziativa della comunità"], hint: "'partecipare a' + noun", tags: ["chunk", "community", "initiative"], tier: 3 },
    { id: "b141-t3-005", type: "produce", prompt: "to make one's own contribution", accepted: ["dare il proprio contributo"], hint: "'proprio' here emphasizes ownership (one's own) rather than functioning as a reflexive verb form", tags: ["chunk", "volunteering"], tier: 3 },
    { id: "b141-t3-006", type: "produce", prompt: "to donate one's own time to the community", accepted: ["donare il proprio tempo alla comunità"], hint: "'donare' treats time as something you can literally give away, the same verb used for donating money", tags: ["chunk", "volunteering", "community"], tier: 3 },
    { id: "b141-t3-007", type: "produce", prompt: "to give back to the community", accepted: ["restituire qualcosa alla comunità"], hint: "'restituire' literally means to give something back, used here figuratively since the community never lent anything", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-008", type: "produce", prompt: "to found a neighborhood association", accepted: ["fondare un'associazione di quartiere"], hint: "'fondare' + noun", tags: ["chunk", "community", "association"], tier: 3 },
    { id: "b141-t3-009", type: "produce", prompt: "to join an association", accepted: ["iscriversi a un'associazione"], hint: "reflexive 'iscriversi a'", tags: ["chunk", "community", "association"], tier: 3 },
    { id: "b141-t3-010", type: "produce", prompt: "to be an active member of the association", accepted: ["essere un socio attivo dell'associazione", "essere una socia attiva dell'associazione"], hint: "'un socio / una socia' — the member of an association", tags: ["chunk", "community", "association"], tier: 3 },
    { id: "b141-t3-011", type: "produce", prompt: "to organize the volunteers", accepted: ["organizzare i volontari"], hint: "'organizzare' + plural noun", tags: ["chunk", "volunteering"], tier: 3 },
    { id: "b141-t3-012", type: "produce", prompt: "to be an active volunteer", accepted: ["essere un volontario attivo", "essere una volontaria attiva"], hint: "'essere' + adjective 'attivo/a'", tags: ["chunk", "volunteering"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Neighborliness & building life ──────
    { id: "b141-t3-013", type: "produce", prompt: "mutual aid", accepted: ["il mutuo soccorso"], hint: "fixed noun phrase, often used for associations", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-014", type: "produce", prompt: "to lend a hand to an elderly neighbor", accepted: ["dare una mano a un vicino anziano", "dare una mano a una vicina anziana"], hint: "'dare una mano a' + person", tags: ["chunk", "neighbor", "elderly"], tier: 3 },
    { id: "b141-t3-015", type: "produce", prompt: "to be a good neighbor", accepted: ["essere un buon vicino", "essere una buona vicina"], hint: "'buon/buona' before the noun", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-016", type: "produce", prompt: "to take care of an elderly neighbor", accepted: ["prendersi cura di un vicino anziano", "prendersi cura di una vicina anziana"], hint: "reflexive 'prendersi cura di'", tags: ["chunk", "neighbor", "elderly"], tier: 3 },
    { id: "b141-t3-017", type: "produce", prompt: "to welcome a new neighbor", accepted: ["dare il benvenuto a un nuovo vicino", "dare il benvenuto a una nuova vicina"], hint: "'dare il benvenuto a' is the standard phrase for welcoming someone, more formal than saying 'benvenuto' alone", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-018", type: "produce", prompt: "to introduce oneself to the neighbors", accepted: ["presentarsi ai vicini"], hint: "reflexive 'presentarsi' — to introduce oneself", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-019", type: "produce", prompt: "to introduce oneself to the neighbor across the street", accepted: ["presentarsi al dirimpettaio", "presentarsi alla dirimpettaia"], hint: "'presentarsi a' + person", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-020", type: "produce", prompt: "to open one's door to a neighbor", accepted: ["aprire la porta a un vicino", "aprire la porta a una vicina"], hint: "'aprire la porta a' works both literally (opening a door) and figuratively (being open to someone)", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-021", type: "produce", prompt: "to share the building expenses", accepted: ["dividere le spese del condominio"], hint: "'dividere le spese di' — 'dividere' here means to split between people, not mathematical division", tags: ["chunk", "housing", "condominio"], tier: 3 },
    { id: "b141-t3-022", type: "produce", prompt: "to organize a residents' meeting", accepted: ["organizzare una riunione di condominio"], hint: "'una riunione di condominio' — the standard term for this meeting", tags: ["chunk", "housing", "condominio"], tier: 3 },
    { id: "b141-t3-023", type: "produce", prompt: "to rent to a tenant", accepted: ["affittare a un inquilino", "affittare a un'inquilina"], hint: "'affittare a' + person", tags: ["chunk", "housing"], tier: 3 },
    { id: "b141-t3-024", type: "produce", prompt: "to live together peacefully", accepted: ["convivere in armonia", "convivere pacificamente"], hint: "'convivere' + adverbial phrase", tags: ["chunk", "housing", "convivenza"], tier: 3 },
    { id: "b141-t3-025", type: "produce", prompt: "coexistence between neighbors", accepted: ["la convivenza tra vicini"], hint: "'convivenza' pairs with 'tra' (between/among) rather than 'con', since it describes a mutual relationship", tags: ["chunk", "housing", "convivenza"], tier: 3 },
    { id: "b141-t3-026", type: "produce", prompt: "to call the building caretaker", accepted: ["chiamare il portinaio", "chiamare la portinaia"], hint: "'chiamare' + person", tags: ["chunk", "housing", "portinaio"], tier: 3 },
    { id: "b141-t3-027", type: "produce", prompt: "to leave the keys with the caretaker", accepted: ["lasciare le chiavi al portinaio", "lasciare le chiavi alla portinaia"], hint: "'lasciare qualcosa a qualcuno' is the general pattern for leaving or entrusting an object with a person", tags: ["chunk", "housing", "portinaio"], tier: 3 },
    { id: "b141-t3-028", type: "produce", prompt: "to respect the neighbors' peace and quiet", accepted: ["rispettare la tranquillità dei vicini"], hint: "'tranquillità' here means peace and quiet (noise), not calmness of temperament", tags: ["chunk", "neighbor"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Small talk & complaints ─────────────
    { id: "b141-t3-029", type: "produce", prompt: "to complain to the neighbor about the noise", accepted: ["lamentarsi con il vicino per il rumore", "lamentarsi con la vicina per il rumore"], hint: "reflexive 'lamentarsi con qualcuno per qualcosa'", tags: ["chunk", "neighbor"], tier: 3 },
    { id: "b141-t3-030", type: "produce", prompt: "to break the ice", accepted: ["rompere il ghiaccio"], hint: "idiom identical in structure to the English", tags: ["chunk", "idiom"], tier: 3 },
    { id: "b141-t3-031", type: "produce", prompt: "to have a little chat", accepted: ["fare due chiacchiere", "fare quattro chiacchiere"], hint: "idiom 'fare due/quattro chiacchiere'", tags: ["chunk", "idiom"], tier: 3 },
    { id: "b141-t3-032", type: "produce", prompt: "to have a good relationship with the neighbors", accepted: ["avere un buon rapporto con i vicini"], hint: "'rapporto' means relationship/rapport here, not a written report", tags: ["chunk", "neighbor"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Generational differences ────────────
    { id: "b141-t3-033", type: "produce", prompt: "to bridge the generation gap", accepted: ["colmare il divario generazionale"], hint: "'colmare' — to bridge/fill a gap", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-034", type: "produce", prompt: "to learn from the elderly", accepted: ["imparare dagli anziani"], hint: "'imparare' takes 'da' (from), not 'di', when naming the source you learn from", tags: ["chunk", "generations", "elderly"], tier: 3 },
    { id: "b141-t3-035", type: "produce", prompt: "to pass on values to the younger generations", accepted: ["trasmettere valori alle nuove generazioni"], hint: "'trasmettere' is used for passing on values or traditions, the same verb used for broadcasting a TV signal", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-036", type: "produce", prompt: "to change from one generation to the next", accepted: ["cambiare di generazione in generazione"], hint: "repeated noun phrase 'di generazione in generazione'", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-037", type: "produce", prompt: "generational turnover", accepted: ["il ricambio generazionale"], hint: "noun phrase for the replacement of older members by younger ones", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-038", type: "produce", prompt: "to have little in common with one's peers", accepted: ["avere poco in comune con i propri coetanei"], hint: "'in comune' (in common) stays invariable regardless of gender or number", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-039", type: "produce", prompt: "to feel closer to the older generation", accepted: ["sentirsi più vicino alla generazione più anziana", "sentirsi più vicina alla generazione più anziana"], hint: "reflexive 'sentirsi' + comparative", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-040", type: "produce", prompt: "young people and the elderly", accepted: ["i giovani e gli anziani"], hint: "fixed pairing contrasting age groups", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-041", type: "produce", prompt: "to grow up in a different generation", accepted: ["crescere in una generazione diversa"], hint: "'crescere in' takes 'in' before the place or context someone grows up in", tags: ["chunk", "generations"], tier: 3 },
    { id: "b141-t3-042", type: "produce", prompt: "to be a peer of someone", accepted: ["essere coetaneo di qualcuno", "essere coetanea di qualcuno"], hint: "the adjective 'coetaneo/a' agrees with the subject's gender, and 'di' introduces the person you're the same age as", tags: ["chunk", "generations"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Community & belonging ───────────────
    { id: "b141-t3-043", type: "produce", prompt: "to feel part of the community", accepted: ["sentirsi parte della comunità"], hint: "reflexive 'sentirsi parte di'", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-044", type: "produce", prompt: "to build community", accepted: ["fare comunità", "creare comunità"], hint: "'comunità' appears with no article here, treated as an abstract activity rather than a specific group", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-045", type: "produce", prompt: "to feel a sense of belonging", accepted: ["sentire un senso di appartenenza"], hint: "'sentire' (to feel/sense) takes a direct object here, not the reflexive 'sentirsi' used elsewhere in this unit", tags: ["chunk", "community", "appartenenza"], tier: 3 },
    { id: "b141-t3-046", type: "produce", prompt: "to lose one's sense of belonging", accepted: ["perdere il senso di appartenenza"], hint: "note the definite article 'il senso di', unlike 'sentire un senso di' which uses the indefinite 'un'", tags: ["chunk", "community", "appartenenza"], tier: 3 },
    { id: "b141-t3-047", type: "produce", prompt: "to be active in the community", accepted: ["essere attivo nella comunità", "essere attiva nella comunità"], hint: "the adjective 'attivo/a' agrees with the subject, and 'in' introduces the group or context", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-048", type: "produce", prompt: "close-knit community", accepted: ["una comunità molto unita"], hint: "'unita' — the adjective for close-knit", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-049", type: "produce", prompt: "to have deep roots in a community", accepted: ["avere radici profonde in una comunità"], hint: "'radici' (roots) is used figuratively here, the same word used for a plant's roots", tags: ["chunk", "community"], tier: 3 },
    { id: "b141-t3-050", type: "produce", prompt: "to network with other volunteers", accepted: ["fare rete con altri volontari"], hint: "'fare rete con' literally means to make a network with — the modern, informal way to say 'to network' in Italian", tags: ["chunk", "community", "volunteering"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Community events ────────────────────
    { id: "b141-t3-051", type: "produce", prompt: "to organize a neighborhood party", accepted: ["organizzare una festa di quartiere"], hint: "'di quartiere' functions like an adjective here, meaning neighborhood-wide rather than private", tags: ["chunk", "event"], tier: 3 },
    { id: "b141-t3-052", type: "produce", prompt: "the whole neighborhood came together", accepted: ["Tutto il vicinato si è riunito."], hint: "reflexive 'riunirsi' — passato prossimo", tags: ["chunk", "event", "vicinato"], tier: 3 },
    { id: "b141-t3-053", type: "produce", prompt: "to take part in the local festival", accepted: ["partecipare alla sagra del paese"], hint: "'partecipare a' always takes 'a', which contracts with the article into 'alla' before a feminine noun like 'sagra'", tags: ["chunk", "event", "sagra"], tier: 3 },
    { id: "b141-t3-054", type: "produce", prompt: "to set up the stalls for the festival", accepted: ["allestire le bancarelle per la sagra"], hint: "'allestire' — to set up / prepare", tags: ["chunk", "event", "sagra"], tier: 3 },
    { id: "b141-t3-055", type: "produce", prompt: "to organize a neighborhood market", accepted: ["organizzare un mercatino di quartiere"], hint: "'un mercatino di quartiere' — a small local market", tags: ["chunk", "event"], tier: 3 },
    { id: "b141-t3-056", type: "produce", prompt: "the local festival brings the whole community together", accepted: ["La sagra riunisce tutta la comunità."], hint: "present tense of 'riunire'", tags: ["chunk", "event", "sagra"], tier: 3 },
    { id: "b141-t3-057", type: "produce", prompt: "to organize activities for the elderly", accepted: ["organizzare attività per gli anziani"], hint: "'attività' is invariable in the plural, so the same form covers one activity or many", tags: ["chunk", "event", "elderly"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Isolation & loneliness ──────────────
    { id: "b141-t3-058", type: "produce", prompt: "to feel lonely", accepted: ["sentirsi solo", "sentirsi sola"], hint: "reflexive 'sentirsi' + adjective", tags: ["chunk", "emotion", "solitudine"], tier: 3 },
    { id: "b141-t3-059", type: "produce", prompt: "loneliness among the elderly is a serious problem", accepted: ["La solitudine tra gli anziani è un problema serio."], hint: "'tra' (among) introduces the group affected, rather than 'di'", tags: ["chunk", "emotion", "solitudine"], tier: 3 },
    { id: "b141-t3-060", type: "produce", prompt: "to come out of isolation", accepted: ["uscire dall'isolamento"], hint: "'uscire da' takes 'da' (out of) before the state or place being left", tags: ["chunk", "emotion", "isolamento"], tier: 3 },
    { id: "b141-t3-061", type: "produce", prompt: "to fall into isolation", accepted: ["cadere nell'isolamento"], hint: "'cadere in' takes 'in' (into) before the state being entered — the mirror image of 'uscire da'", tags: ["chunk", "emotion", "isolamento"], tier: 3 },
    { id: "b141-t3-062", type: "produce", prompt: "to spend time with an elderly neighbor", accepted: ["passare del tempo con un vicino anziano", "passare del tempo con una vicina anziana"], hint: "'del tempo' uses the partitive article, meaning 'some time' rather than 'the time'", tags: ["chunk", "elderly", "neighbor"], tier: 3 },
    { id: "b141-t3-063", type: "produce", prompt: "to organize a support initiative for isolated elderly people", accepted: ["organizzare un'iniziativa di sostegno per gli anziani isolati"], hint: "'un'iniziativa di sostegno per'", tags: ["chunk", "elderly", "sostegno"], tier: 3 },

    // ── Tier 3 – Phrases & Collocations: Acquaintances & closing set ─────────
    { id: "b141-t3-064", type: "produce", prompt: "to be an acquaintance, not a friend", accepted: ["essere un conoscente, non un amico", "essere una conoscente, non un'amica"], hint: "'conoscente' stays the same for both genders, only the article changes", tags: ["chunk", "relationship", "conoscente"], tier: 3 },
    { id: "b141-t3-065", type: "produce", prompt: "to move to a new neighborhood", accepted: ["trasferirsi in un nuovo quartiere"], hint: "reflexive 'trasferirsi in'", tags: ["chunk", "housing"], tier: 3 },
    { id: "b141-t3-066", type: "produce", prompt: "to grow up in the same neighborhood", accepted: ["crescere nello stesso quartiere"], hint: "'crescere in' takes 'in' before the place, the same pattern as 'crescere in una generazione diversa' above", tags: ["chunk", "housing"], tier: 3 },
    { id: "b141-t3-067", type: "produce", prompt: "the building caretaker knows everyone in the building", accepted: ["Il portinaio conosce tutti nel palazzo.", "La portinaia conosce tutti nel palazzo."], hint: "present tense of 'conoscere'", tags: ["chunk", "housing", "portinaio"], tier: 3 },
    { id: "b141-t3-068", type: "produce", prompt: "support between peers", accepted: ["il sostegno tra coetanei"], hint: "'tra' (between) describes mutual support among equals, rather than 'di' or 'per'", tags: ["chunk", "generations", "sostegno"], tier: 3 },
    { id: "b141-t3-069", type: "produce", prompt: "to keep an eye on the elderly neighbor", accepted: ["tenere d'occhio il vicino anziano", "tenere d'occhio la vicina anziana"], hint: "'tenere d'occhio' — to keep watch over", tags: ["chunk", "elderly", "neighbor"], tier: 3 },
    { id: "b141-t3-070", type: "produce", prompt: "generational turnover changed the association", accepted: ["Il ricambio generazionale ha cambiato l'associazione."], hint: "passato prossimo of 'cambiare'", tags: ["chunk", "generations", "association"], tier: 3 },

    // ── Tier 4 – Passage Cloze ────────────────────────────────────────────────
    {
      id: "b141-t4-001",
      type: "passage_cloze",
      prompt: "Da quando è rimasta sola, la signora Elvira esce sempre meno di casa e passa le giornate davanti alla finestra.\nIl suo vicino, Marco, si è accorto del suo isolamento e ha deciso di andare a trovarla ogni martedì pomeriggio.\nAll'inizio lei rispondeva a monosillabi, ma piano piano ha ricominciato a sorridere e a raccontare storie della sua giovinezza.\nOra, ogni martedì, la signora Elvira prepara il tè prima ancora che Marco suoni il campanello: della sua vecchia ___ non è rimasta quasi più traccia.",
      accepted: ["solitudine"],
      hint: "the loneliness this whole passage is about — feminine noun",
      tags: ["passage_cloze", "isolation", "elderly", "neighbor"],
      tier: 4,
      prerequisites: ["b141-t1-001", "b141-t1-002", "b141-t1-019", "b141-t1-027", "b141-t1-029", "b141-t3-016"],
    },
    {
      id: "b141-t4-002",
      type: "passage_cloze",
      prompt: "L'associazione del quartiere ha deciso di organizzare una raccolta fondi per ristrutturare il piccolo parco giochi dietro la chiesa.\nPer settimane i volontari hanno bussato porta per porta, chiedendo un contributo a ogni famiglia del palazzo.\nAnche il portinaio ha dato una mano, appendendo un cartello nell'androne con tutte le informazioni.\nGrazie all'iniziativa, in un mese hanno raccolto abbastanza soldi da comprare nuove altalene e uno scivolo.\nLa domenica dell'inaugurazione, tutto il ___ si è riunito per festeggiare insieme ai bambini.",
      accepted: ["vicinato"],
      hint: "the collective word for the neighbors, not a single street",
      tags: ["passage_cloze", "volunteering", "community", "fundraiser"],
      tier: 4,
      prerequisites: ["b141-t1-003", "b141-t1-013", "b141-t1-025", "b141-t1-033", "b141-t1-047", "b141-t3-003"],
    },
    {
      id: "b141-t4-003",
      type: "passage_cloze",
      prompt: "Mio nonno racconta sempre che, alla sua età, i ragazzi passavano il pomeriggio a giocare per strada invece che con uno schermo.\nDice che il divario generazionale tra noi si vede soprattutto nel modo di stare insieme agli altri.\nEppure, quando gli chiedo consiglio, capisco che ogni generazione ha qualcosa da insegnare all'altra.\nLa settimana scorsa mi ha insegnato a riparare una bicicletta, e io gli ho mostrato come video-chiamare mia cugina: uno scambio alla pari tra ___.",
      accepted: ["generazioni"],
      hint: "the two age groups involved — plural",
      tags: ["passage_cloze", "generations"],
      tier: 4,
      prerequisites: ["b141-t1-015", "b141-t1-017", "b141-t3-036"],
    },
    {
      id: "b141-t4-004",
      type: "passage_cloze",
      prompt: "Ogni anno, prima dell'estate, gli inquilini del nostro palazzo si riuniscono per decidere come dividere le spese del condominio.\nQuest'anno la discussione è stata più lunga del solito: il tetto ha bisogno di essere riparato e i costi sono alti.\nAlla fine, dopo due ore di discussione, tutti hanno trovato un accordo ragionevole.\nIl portinaio ha promesso di sorvegliare i lavori, e la riunione si è conclusa con un caffè offerto dalla ___ del terzo piano.",
      accepted: ["vicina"],
      hint: "feminine form of 'neighbor'",
      tags: ["passage_cloze", "housing", "condominio"],
      tier: 4,
      prerequisites: ["b141-t1-001", "b141-t1-031", "b141-t1-039", "b141-t1-047", "b141-t3-021", "b141-t3-022"],
    },
    {
      id: "b141-t4-005",
      type: "passage_cloze",
      prompt: "Quando la famiglia Conti si è trasferita nel nostro palazzo, nessuno sapeva molto di loro.\nIl giorno del trasloco, la signora del secondo piano ha bussato alla porta per dare il benvenuto ai nuovi vicini con una torta fatta in casa.\nIl dirimpettaio, di solito piuttosto riservato, si è presentato subito dopo, offrendo il suo numero di telefono in caso di emergenza.\nDopo un mese, i vicini hanno invitato la famiglia Conti alla festa che la ___ del palazzo organizza ogni anno in cortile.",
      accepted: ["comunità"],
      hint: "feminine noun for the community organizing the courtyard party",
      tags: ["passage_cloze", "neighbor", "community"],
      tier: 4,
      prerequisites: ["b141-t1-007", "b141-t1-043", "b141-t3-017", "b141-t3-019"],
    },
    {
      id: "b141-t4-006",
      type: "passage_cloze",
      prompt: "Ogni settembre, il paese di mia nonna organizza la sagra della castagna, una festa che dura tre giorni interi.\nLe famiglie del posto allestiscono le bancarelle già dal venerdì mattina, vendendo dolci, vino e prodotti locali.\nQuest'anno l'associazione del paese ha anche organizzato giochi per i bambini e musica dal vivo la sera.\nMia nonna, che da bambina ballava già in quella stessa piazza, quest'anno è rimasta fino all'ultimo fuoco d'artificio: la ___ finisce sempre troppo tardi per tornare a casa a piedi.",
      accepted: ["sagra"],
      hint: "the local festival this whole passage describes",
      tags: ["passage_cloze", "event", "sagra"],
      tier: 4,
      prerequisites: ["b141-t1-013", "b141-t1-045", "b141-t3-054", "b141-t3-056"],
    },
    {
      id: "b141-t4-007",
      type: "passage_cloze",
      prompt: "Il signor Rossi fa il portinaio in questo palazzo da più di trent'anni e conosce quasi tutte le famiglie del palazzo.\nOgni mattina saluta gli inquilini per nome e ritira i pacchi per tutti.\nQuando qualcuno ha un problema, dalla perdita d'acqua alla lite tra vicini, il primo a essere chiamato è sempre lui.\nAl momento della pensione, tutto il palazzo ha organizzato una festa per ringraziare il ___ per tanti anni di dedizione.",
      accepted: ["portinaio"],
      hint: "the person this whole passage is about",
      tags: ["passage_cloze", "housing", "portinaio"],
      tier: 4,
      prerequisites: ["b141-t1-039", "b141-t1-047", "b141-t3-026", "b141-t3-069"],
    },
    {
      id: "b141-t4-008",
      type: "passage_cloze",
      prompt: "All'inizio, io e il mio dirimpettaio ci scambiavamo solo un saluto veloce sul pianerottolo.\nPoi, una sera, si è rotto l'ascensore e siamo rimasti a chiacchierare per venti minuti aspettando il tecnico.\nDa quella sera abbiamo cominciato a bere un caffè insieme ogni tanto, e lui mi presta sempre gli attrezzi quando ne ho bisogno.\nLa settimana scorsa, prima di partire per due giorni, ho lasciato le chiavi di casa proprio a quel semplice ___ di pianerottolo.",
      accepted: ["conoscente"],
      hint: "the word for someone you know only a little — before he became closer",
      tags: ["passage_cloze", "neighbor", "conoscente"],
      tier: 4,
      prerequisites: ["b141-t1-035", "b141-t1-043", "b141-t3-030"],
    },
    {
      id: "b141-t4-009",
      type: "passage_cloze",
      prompt: "Dopo anni in cui il quartiere sembrava sempre più isolato, un gruppo di residenti ha deciso di fondare un'associazione di quartiere.\nIl primo obiettivo era semplice: organizzare eventi per permettere ai vicini di conoscersi meglio.\nHanno cominciato con un mercatino di quartiere ogni ultima domenica del mese, dove ognuno vendeva oggetti che non usava più.\nDopo un anno, l'associazione conta già più di cinquanta soci e organizza anche corsi gratuiti per gli anziani del ___.",
      accepted: ["vicinato"],
      hint: "the collective neighbors, the same word used earlier for the community around the association",
      tags: ["passage_cloze", "community", "association"],
      tier: 4,
      prerequisites: ["b141-t1-003", "b141-t1-005", "b141-t1-013", "b141-t1-019", "b141-t3-008", "b141-t3-055"],
    },
    {
      id: "b141-t4-010",
      type: "passage_cloze",
      prompt: "Durante l'inverno, il signor Bianchi esce raramente dal suo appartamento al piano terra.\nSua nipote, che studia in un'altra città, gli telefona ogni sera per sapere come sta.\nMa è soprattutto la vicina del piano di sopra a passare a trovarlo, portandogli sempre un piatto caldo.\nQuest'inverno, grazie a quella visita quotidiana, il signor Bianchi non ha pranzato nemmeno una volta da ___.",
      accepted: ["solo"],
      hint: "adjective meaning 'alone', in the idiom 'mangiare/pranzare da solo' (to eat alone)",
      tags: ["passage_cloze", "isolation", "elderly"],
      tier: 4,
      prerequisites: ["b141-t1-001", "b141-t1-027", "b141-t3-058"],
    },
    {
      id: "b141-t4-011",
      type: "passage_cloze",
      prompt: "Ho ritrovato per caso Giulia, la mia coetanea di scuola elementare, dopo più di vent'anni.\nCi siamo riconosciute subito, anche se i nostri percorsi di vita sono stati molto diversi.\nAbbiamo scoperto di avere ancora molto in comune: entrambe siamo tornate a vivere nello stesso quartiere dell'infanzia.\nOra ci vediamo ogni settimana, e sabato prossimo la mia vecchia ___ mi porta a rivedere il cortile della nostra scuola elementare.",
      accepted: ["coetanea"],
      hint: "feminine noun for someone the same age as you, agreeing with 'vecchia'",
      tags: ["passage_cloze", "generations", "coetaneo"],
      tier: 4,
      prerequisites: ["b141-t1-005", "b141-t1-021", "b141-t3-038", "b141-t3-066"],
    },
    {
      id: "b141-t4-012",
      type: "passage_cloze",
      prompt: "Per mesi, il rumore dei lavori in casa del vicino del piano di sotto aveva creato tensione nel palazzo.\nAlla fine, durante l'assemblea di condominio, i vicini hanno deciso di parlarne apertamente invece di lamentarsi soltanto tra loro.\nIl vicino si è scusato e ha promesso di lavorare solo negli orari concordati.\nDa allora, la ___ nel palazzo è tornata serena, e qualcuno ha persino proposto una cena tra vicini per festeggiare.",
      accepted: ["convivenza"],
      hint: "feminine noun for living together / coexisting",
      tags: ["passage_cloze", "housing", "convivenza"],
      tier: 4,
      prerequisites: ["b141-t1-031", "b141-t1-037", "b141-t3-024", "b141-t3-029"],
    },
    {
      id: "b141-t4-013",
      type: "passage_cloze",
      prompt: "Quando mi sono trasferito in questa città tre anni fa, non conoscevo nessuno e mi sentivo completamente estraneo.\nPiano piano ho cominciato a fare volontariato in una piccola associazione del quartiere, aiutando a organizzare eventi per gli anziani.\nLì ho conosciuto persone di ogni età, dai coetanei ai pensionati, e ho imparato molto dalle loro storie.\nLa settimana scorsa, l'associazione mi ha chiesto di organizzare la prossima festa del quartiere insieme al gruppo di ___ che frequento ormai da mesi.",
      accepted: ["appartenenza"],
      hint: "feminine noun in the phrase 'gruppo di appartenenza' (the group you belong to)",
      tags: ["passage_cloze", "community", "appartenenza"],
      tier: 4,
      prerequisites: ["b141-t1-005", "b141-t1-013", "b141-t1-021", "b141-t1-041", "b141-t3-045"],
    },
    {
      id: "b141-t4-014",
      type: "passage_cloze",
      prompt: "Ogni mercoledì pomeriggio, un gruppo di volontari si riunisce nel centro anziani del quartiere per insegnare a usare lo smartphone.\nMolti degli anziani non avevano mai scritto un messaggio prima, e all'inizio erano intimiditi dalla tecnologia.\nCon pazienza, i volontari, quasi tutti coetanei dei nipoti degli anziani stessi, hanno reso l'apprendimento un momento di scambio tra generazioni.\nOra alcuni anziani video-chiamano i nipoti lontani grazie a questa ___ nata quasi per caso.",
      accepted: ["iniziativa"],
      hint: "feminine noun for this whole project",
      tags: ["passage_cloze", "volunteering", "generations"],
      tier: 4,
      prerequisites: ["b141-t1-011", "b141-t1-019", "b141-t1-021", "b141-t1-033", "b141-t3-057"],
    },
    {
      id: "b141-t4-015",
      type: "passage_cloze",
      prompt: "Una volta al mese, l'associazione del quartiere organizza un mercatino dove i vicini possono scambiarsi libri, vestiti e giocattoli usati.\nNon si tratta solo di risparmiare soldi: è anche un'occasione per fare due chiacchiere e conoscere meglio chi abita nello stesso palazzo.\nQuest'anno hanno deciso di destinare una parte del ricavato a una raccolta fondi per il centro anziani.\nIl portinaio, che di solito osserva tutto dalla finestra, per la prima volta ha deciso di allestire una ___ anche lui.",
      accepted: ["bancarella"],
      hint: "singular of 'le bancarelle' — a market stall",
      tags: ["passage_cloze", "event", "portinaio"],
      tier: 4,
      prerequisites: ["b141-t1-013", "b141-t1-025", "b141-t1-047", "b141-t3-031", "b141-t3-054", "b141-t3-055"],
    },
    {
      id: "b141-t4-016",
      type: "passage_cloze",
      prompt: "Nel nostro palazzo, i ragazzi passano il tempo libero online, mentre gli anziani preferiscono incontrarsi in cortile.\nPer colmare questa distanza, l'associazione ha organizzato un pomeriggio di scambio: i giovani insegnano informatica, gli anziani raccontano storie del quartiere.\nAll'inizio sembrava un esperimento strano, ma dopo poche settimane sia i giovani che gli anziani aspettavano con piacere l'incontro settimanale.\nMercoledì scorso, un sedicenne del terzo piano ha persino chiesto alla vicina di ottant'anni di insegnargli a giocare a briscola, colmando per un pomeriggio il ___ generazionale tra i due.",
      accepted: ["divario"],
      hint: "masculine noun for 'gap', paired with 'generazionale'",
      tags: ["passage_cloze", "generations"],
      tier: 4,
      prerequisites: ["b141-t1-017", "b141-t1-019", "b141-t1-013", "b141-t3-033"],
    },
    {
      id: "b141-t4-017",
      type: "passage_cloze",
      prompt: "Da quando è andato in pensione, il signor Ferri si sentiva spesso inutile e passava le giornate da solo davanti alla televisione.\nUn giorno, sua figlia lo ha convinto a iscriversi come volontario in un'associazione che aiuta le famiglie del quartiere in difficoltà.\nAll'inizio era scettico, ma ben presto ha scoperto di avere ancora molto da offrire agli altri.\nOggi il signor Ferri passa il martedì mattina a consegnare la spesa a domicilio per l'associazione, lontano ormai dalla sua vecchia ___.",
      accepted: ["solitudine"],
      hint: "feminine noun for loneliness",
      tags: ["passage_cloze", "volunteering", "solitudine"],
      tier: 4,
      prerequisites: ["b141-t1-009", "b141-t1-013", "b141-t1-029", "b141-t3-009", "b141-t3-060"],
    },
    {
      id: "b141-t4-018",
      type: "passage_cloze",
      prompt: "Dopo trentacinque anni di servizio, la signora Anna, la portinaia del nostro palazzo, ha deciso di andare finalmente in pensione.\nGli inquilini, per ringraziarla, hanno organizzato una piccola festa nel cortile, con dolci portati da ogni famiglia.\nMolti vicini hanno raccontato aneddoti di quando lei li aveva aiutati con le chiavi dimenticate o i pacchi in ritardo.\nAlla fine della serata, tutti hanno promesso di continuare a passare a trovarla, anche se non sarebbe più stata la ___ ufficiale del palazzo.",
      accepted: ["portinaia"],
      hint: "feminine form of the building caretaker",
      tags: ["passage_cloze", "housing", "portinaio"],
      tier: 4,
      prerequisites: ["b141-t1-039", "b141-t1-047", "b141-t1-001", "b141-t3-027"],
    },
    {
      id: "b141-t4-019",
      type: "passage_cloze",
      prompt: "Ogni primavera, i membri dell'associazione si riuniscono per pianificare la sagra estiva del paese.\nQuest'anno il gruppo è più giovane del solito, e i nuovi volontari coetanei propongono idee diverse da quelle degli anni passati.\nGli anziani del comitato, però, insistono per mantenere alcune tradizioni, come la gara di torte fatte in casa.\nAlla fine trovano un compromesso: nuove attività per i più giovani e la stessa ___ di sempre per gli anziani.",
      accepted: ["gara"],
      hint: "feminine noun for 'competition/contest', referring to the cake contest",
      tags: ["passage_cloze", "event", "sagra"],
      tier: 4,
      prerequisites: ["b141-t1-013", "b141-t1-011", "b141-t1-019", "b141-t1-021", "b141-t1-045"],
    },
    {
      id: "b141-t4-020",
      type: "passage_cloze",
      prompt: "Da un anno, Sara, una studentessa universitaria, fa volontariato accompagnando una signora anziana del suo palazzo a fare la spesa.\nAll'inizio si vedevano solo una volta alla settimana, ma ora Sara passa a trovarla quasi ogni giorno dopo le lezioni.\nLa signora le racconta storie di quando il quartiere era ancora tutto campagna, e Sara le insegna a usare le videochiamate per parlare con il nipote all'estero.\nLa settimana scorsa la signora le ha detto: «Resta a cena, così la prossima volta mi spieghi anche le fotografie sul telefono» — ora si vedono anche il mercoledì, senza più bisogno di un pretesto per lo scambio tra ___.",
      accepted: ["generazioni"],
      hint: "plural noun for the two age groups Sara and the elderly woman represent",
      tags: ["passage_cloze", "generations", "volunteering"],
      tier: 4,
      prerequisites: ["b141-t1-009", "b141-t1-019", "b141-t1-005", "b141-t1-015"],
    },
    {
      id: "b141-t4-021",
      type: "passage_cloze",
      prompt: "Mio padre racconta spesso che, quando lui era giovane in questo stesso quartiere, i vicini si aiutavano senza nemmeno doverlo chiedere.\nOggi, dice, la gente si conosce meno e passa più tempo davanti agli schermi che in cortile.\nEppure, quando c'è stata l'alluvione l'anno scorso, tutto il vicinato si è organizzato in poche ore per aiutare le famiglie colpite.\nMio padre, per esempio, ha passato due notti a spalare il fango dal garage di vicini che prima conosceva solo di vista, gente che si è fatta avanti proprio nel momento di ___.",
      accepted: ["bisogno"],
      hint: "masculine noun for 'need'",
      tags: ["passage_cloze", "community", "vicinato"],
      tier: 4,
      prerequisites: ["b141-t1-005", "b141-t1-003", "b141-t1-007"],
    },
    {
      id: "b141-t4-022",
      type: "passage_cloze",
      prompt: "Un anno dopo la sua fondazione, l'associazione di quartiere ha già una raccolta fondi per il parco, un mercatino mensile e un progetto che unisce anziani e giovani.\nMolti inquilini che prima si conoscevano appena ora si salutano per nome ogni giorno.\nAnche il portinaio ammette che il palazzo ha finalmente un vero senso di ___, diverso da un anno fa.\nAlla fine dell'ultima riunione, invece di andarsene subito come si faceva prima, quasi tutti gli inquilini sono rimasti a bere un caffè insieme nel cortile, chiacchierando fino a tardi.",
      accepted: ["appartenenza"],
      hint: "feminine noun for the sense of belonging this whole unit has been building toward",
      tags: ["passage_cloze", "community", "appartenenza"],
      tier: 4,
      prerequisites: ["b141-t1-013", "b141-t1-025", "b141-t1-019", "b141-t1-021", "b141-t1-039", "b141-t1-047", "b141-t1-041"],
    },
  ],
};
export default unit;
