import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-48-keeping-up-with-news",
  name: "What's in the News",
  level: "B1",
  theme: "Keeping Up with the News",
  emoji: "📰",
  prerequisiteUnits: [],
  cards: [
    // ─── Tier 1 – Vocabulary ───────────────────────────────────────────────
    {
      id: "b148-t1-001",
      type: "recognize",
      prompt: "il notiziario",
      accepted: ["the news bulletin", "the newscast"],
      hint: "A TV or radio news broadcast, distinct from a printed newspaper.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-002",
      type: "produce",
      prompt: "the news bulletin / newscast",
      accepted: ["il notiziario"],
      hint: "ascoltare il notiziario alla radio = to listen to the radio news.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-003",
      type: "recognize",
      prompt: "il quotidiano",
      accepted: ["the daily newspaper"],
      hint: "From 'ogni giorno' — a paper published every day.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-004",
      type: "produce",
      prompt: "the daily newspaper",
      accepted: ["il quotidiano"],
      hint: "un quotidiano nazionale = a national daily.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-005",
      type: "recognize",
      prompt: "la rivista",
      accepted: ["the magazine"],
      hint: "Weekly or monthly, unlike a daily quotidiano.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-006",
      type: "produce",
      prompt: "the magazine",
      accepted: ["la rivista"],
      hint: "sfogliare una rivista = to flip through a magazine.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-007",
      type: "recognize",
      prompt: "l'articolo",
      accepted: ["the article"],
      hint: "A single written piece, whether in a paper, magazine, or website.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-008",
      type: "produce",
      prompt: "the article",
      accepted: ["l'articolo"],
      hint: "un articolo interessante = an interesting article.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-009",
      type: "recognize",
      prompt: "il meteo",
      accepted: ["the weather forecast"],
      hint: "Everyday spoken word; le previsioni del tempo is the more formal equivalent.",
      tags: ["news", "noun", "vocab", "weather"],
      tier: 1,
    },
    {
      id: "b148-t1-010",
      type: "produce",
      prompt: "the weather forecast (everyday word)",
      accepted: ["il meteo"],
      hint: "controllare il meteo = to check the forecast.",
      tags: ["news", "noun", "vocab", "weather"],
      tier: 1,
    },
    {
      id: "b148-t1-011",
      type: "recognize",
      prompt: "l'attualità",
      accepted: ["current affairs", "current events"],
      hint: "tenersi aggiornato sull'attualità = to keep up with current affairs.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-012",
      type: "produce",
      prompt: "current affairs / current events",
      accepted: ["l'attualità"],
      hint: "una rivista di attualità = a current-affairs magazine.",
      tags: ["news", "noun", "vocab", "media"],
      tier: 1,
    },
    {
      id: "b148-t1-013",
      type: "recognize",
      prompt: "l'evento",
      accepted: ["the event"],
      hint: "un evento locale = a local event.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-014",
      type: "produce",
      prompt: "the event",
      accepted: ["l'evento"],
      hint: "un evento sportivo importante = an important sports event.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-015",
      type: "recognize",
      prompt: "il commento",
      accepted: ["the comment"],
      hint: "lasciare un commento su un articolo = to leave a comment on an article.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-016",
      type: "produce",
      prompt: "the comment",
      accepted: ["il commento"],
      hint: "From commentare, to comment.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-017",
      type: "recognize",
      prompt: "il caso",
      accepted: ["the case", "the story"],
      hint: "Il caso è ancora aperto = the case/story is still open.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-018",
      type: "produce",
      prompt: "the case / the story (as in a news story)",
      accepted: ["il caso"],
      hint: "seguire un caso da vicino = to follow a story closely.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-019",
      type: "recognize",
      prompt: "lo scandalo",
      accepted: ["the scandal"],
      hint: "scoppia uno scandalo = a scandal breaks out.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-020",
      type: "produce",
      prompt: "the scandal",
      accepted: ["lo scandalo"],
      hint: "uno scandalo internazionale = an international scandal.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-021",
      type: "recognize",
      prompt: "l'indiscrezione",
      accepted: ["the leak", "the insider rumor", "the unconfirmed report"],
      hint: "Insider information not yet officially confirmed.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-022",
      type: "produce",
      prompt: "the leak / insider rumor (unconfirmed insider news)",
      accepted: ["l'indiscrezione"],
      hint: "secondo un'indiscrezione = according to an insider leak.",
      tags: ["news", "noun", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-023",
      type: "recognize",
      prompt: "locale",
      accepted: ["local"],
      hint: "Invariable for gender, only for number: locale / locali.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-024",
      type: "produce",
      prompt: "local (adjective)",
      accepted: ["locale"],
      hint: "un evento locale = a local event.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-025",
      type: "recognize",
      prompt: "nazionale",
      accepted: ["national"],
      hint: "un quotidiano nazionale = a national daily.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-026",
      type: "produce",
      prompt: "national (adjective)",
      accepted: ["nazionale"],
      hint: "Invariable for gender, only for number: nazionale / nazionali.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-027",
      type: "recognize",
      prompt: "internazionale",
      accepted: ["international"],
      hint: "uno scandalo internazionale = an international scandal.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-028",
      type: "produce",
      prompt: "international (adjective)",
      accepted: ["internazionale"],
      hint: "Invariable for gender, only for number: internazionale / internazionali.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-029",
      type: "recognize",
      prompt: "sportivo",
      accepted: ["sports (adjective)", "sporting", "sports-related"],
      hint: "un evento sportivo = a sports event; feminine is sportiva.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-030",
      type: "produce",
      prompt: "sports-related (adjective, masculine singular)",
      accepted: ["sportivo"],
      hint: "le notizie sportive = sports news (feminine plural form).",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-031",
      type: "recognize",
      prompt: "estero",
      accepted: ["foreign", "abroad"],
      hint: "le notizie dall'estero = news from abroad.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-032",
      type: "produce",
      prompt: "foreign / abroad",
      accepted: ["estero"],
      hint: "all'estero = abroad; feminine form is estera.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-033",
      type: "recognize",
      prompt: "informarsi",
      accepted: ["to keep oneself informed", "to find out information"],
      hint: "Reflexive verb: informarsi su qualcosa = to inform oneself about something.",
      tags: ["news", "verb", "vocab", "reflexive"],
      tier: 1,
    },
    {
      id: "b148-t1-034",
      type: "produce",
      prompt: "to keep oneself informed",
      accepted: ["informarsi"],
      hint: "informarsi su ciò che succede nel mondo = to keep informed about what's happening in the world.",
      tags: ["news", "verb", "vocab", "reflexive"],
      tier: 1,
    },
    {
      id: "b148-t1-035",
      type: "recognize",
      prompt: "seguire",
      accepted: ["to follow"],
      hint: "seguire un caso da vicino = to follow a story closely.",
      tags: ["news", "verb", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-036",
      type: "produce",
      prompt: "to follow (a story, an event)",
      accepted: ["seguire"],
      hint: "Regular -ire verb.",
      tags: ["news", "verb", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-037",
      type: "recognize",
      prompt: "condividere",
      accepted: ["to share"],
      hint: "condividere un articolo sui social = to share an article on social media.",
      tags: ["news", "verb", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-038",
      type: "produce",
      prompt: "to share (an article, a post)",
      accepted: ["condividere"],
      hint: "Irregular past participle: condiviso.",
      tags: ["news", "verb", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-039",
      type: "recognize",
      prompt: "sorprendente",
      accepted: ["surprising"],
      hint: "È una notizia sorprendente = it's a surprising piece of news.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-040",
      type: "produce",
      prompt: "surprising",
      accepted: ["sorprendente"],
      hint: "From sorprendere, to surprise.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-041",
      type: "recognize",
      prompt: "preoccupante",
      accepted: ["worrying", "concerning"],
      hint: "È una notizia preoccupante = it's worrying news.",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    {
      id: "b148-t1-042",
      type: "produce",
      prompt: "worrying / concerning",
      accepted: ["preoccupante"],
      hint: "From preoccupare, to worry (someone).",
      tags: ["news", "adjective", "vocab"],
      tier: 1,
    },
    // ─── Tier 2 – Grammar: condizionale composto for unconfirmed news, si dice / pare che + congiuntivo, passato prossimo vs imperfetto, secondo ───
    {
      id: "b148-t2-001",
      type: "conjugate",
      prompt: "dimettersi – il ministro (condizionale composto)",
      accepted: ["si sarebbe dimesso"],
      hint: "Reflexive verb in condizionale composto: si + sarebbe + participio, used for unconfirmed political news.",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-002",
      type: "conjugate",
      prompt: "vincere – la squadra (condizionale composto)",
      accepted: ["avrebbe vinto"],
      hint: "avere + participio passato; no agreement needed with avere.",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-003",
      type: "conjugate",
      prompt: "perdere – il governo (condizionale composto)",
      accepted: ["avrebbe perso"],
      hint: "avere + participio passato, reporting an unconfirmed political result.",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-004",
      type: "conjugate",
      prompt: "aumentare – il costo della vita (condizionale composto)",
      accepted: ["sarebbe aumentato"],
      hint: "essere + participio, agreeing with il costo (m.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-005",
      type: "conjugate",
      prompt: "diminuire – la disoccupazione (condizionale composto)",
      accepted: ["sarebbe diminuita"],
      hint: "essere + participio, agreeing with la disoccupazione (f.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-006",
      type: "conjugate",
      prompt: "succedere – un incidente (condizionale composto)",
      accepted: ["sarebbe successo"],
      hint: "essere + participio, agreeing with un incidente (m.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-007",
      type: "conjugate",
      prompt: "arrivare – l'aiuto internazionale (condizionale composto)",
      accepted: ["sarebbe arrivato"],
      hint: "essere + participio, agreeing with l'aiuto (m.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-008",
      type: "conjugate",
      prompt: "firmare – il presidente (condizionale composto)",
      accepted: ["avrebbe firmato"],
      hint: "avere + participio passato, reporting an unconfirmed signing.",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-009",
      type: "conjugate",
      prompt: "scoppiare – uno scandalo (condizionale composto)",
      accepted: ["sarebbe scoppiato"],
      hint: "essere + participio, agreeing with uno scandalo (m.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-010",
      type: "conjugate",
      prompt: "crescere – l'economia (condizionale composto)",
      accepted: ["sarebbe cresciuta"],
      hint: "essere + participio, agreeing with l'economia (f.sg.).",
      tags: ["grammar", "condizionale-composto", "verb", "news"],
      tier: 2,
    },
    {
      id: "b148-t2-011",
      type: "fill_blank",
      prompt: "Secondo alcune indiscrezioni, il ministro ___ (dimettersi) entro la fine della settimana.\n(Fill in the condizionale composto)",
      accepted: ["si sarebbe dimesso"],
      hint: "Condizionale composto used for a rumored, unconfirmed resignation.",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-012",
      type: "fill_blank",
      prompt: "Si vocifera che la squadra di casa ___ (vincere) il campionato già l'anno scorso.\n(Fill in the condizionale composto)",
      accepted: ["avrebbe vinto"],
      hint: "avere + participio, no agreement.",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-013",
      type: "fill_blank",
      prompt: "Secondo il quotidiano di oggi, il governo ___ (perdere) l'appoggio di due partiti alleati.\n(Fill in the condizionale composto)",
      accepted: ["avrebbe perso"],
      hint: "avere + participio, reporting unconfirmed political news.",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-014",
      type: "fill_blank",
      prompt: "Circolano indiscrezioni secondo cui il prezzo della benzina ___ (aumentare) già la settimana prossima.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe aumentato"],
      hint: "essere + participio, agreeing with il prezzo (m.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-015",
      type: "fill_blank",
      prompt: "Il notiziario ha detto che la disoccupazione ___ (diminuire) nell'ultimo trimestre.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe diminuita"],
      hint: "essere + participio, agreeing with la disoccupazione (f.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-016",
      type: "fill_blank",
      prompt: "Sul giornale si legge che un grave incidente ___ (succedere) sull'autostrada questa notte.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe successo"],
      hint: "essere + participio, agreeing with un incidente (m.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-017",
      type: "fill_blank",
      prompt: "Secondo voci non confermate, l'aiuto internazionale ___ (arrivare) già ieri sera.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe arrivato"],
      hint: "essere + participio, agreeing with l'aiuto (m.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-018",
      type: "fill_blank",
      prompt: "Si dice che il presidente ___ (firmare) già l'accordo in segreto.\n(Fill in the condizionale composto)",
      accepted: ["avrebbe firmato"],
      hint: "avere + participio, reporting an unconfirmed signing.",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-019",
      type: "fill_blank",
      prompt: "Secondo un'indiscrezione, uno scandalo ___ (scoppiare) all'interno della squadra di governo.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe scoppiato"],
      hint: "essere + participio, agreeing with uno scandalo (m.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-020",
      type: "fill_blank",
      prompt: "Il commento di un economista suggerisce che l'economia ___ (crescere) più del previsto.\n(Fill in the condizionale composto)",
      accepted: ["sarebbe cresciuta"],
      hint: "essere + participio, agreeing with l'economia (f.sg.).",
      tags: ["grammar", "condizionale-composto", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-021",
      type: "fill_blank",
      prompt: "Si dice che il governo ___ (aumentare) le tasse il prossimo anno.\n(Fill in the congiuntivo presente)",
      accepted: ["aumenti"],
      hint: "si dice che + congiuntivo presente for a rumored future change.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-022",
      type: "fill_blank",
      prompt: "Si dice che la squadra ___ (perdere) la partita di ieri sera.\n(Fill in the congiuntivo passato)",
      accepted: ["abbia perso"],
      hint: "si dice che + congiuntivo passato for a rumored past result.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-023",
      type: "fill_blank",
      prompt: "Si dice che il prezzo del gas ___ (salire) ancora questo inverno.\n(Fill in the congiuntivo presente)",
      accepted: ["salga"],
      hint: "si dice che + congiuntivo presente.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-024",
      type: "fill_blank",
      prompt: "Si dice che ci ___ (essere) un nuovo scandalo al comune.\n(Fill in the congiuntivo presente)",
      accepted: ["sia"],
      hint: "si dice che + congiuntivo presente of esserci.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-025",
      type: "fill_blank",
      prompt: "Si dice che l'attore famoso ___ (lasciare) il paese per motivi fiscali.\n(Fill in the congiuntivo passato)",
      accepted: ["abbia lasciato"],
      hint: "si dice che + congiuntivo passato.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-026",
      type: "fill_blank",
      prompt: "Si dice che la situazione economica ___ (peggiorare) nei prossimi mesi.\n(Fill in the congiuntivo presente)",
      accepted: ["peggiori"],
      hint: "si dice che + congiuntivo presente.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-027",
      type: "fill_blank",
      prompt: "Si dice che due ministri ___ (litigare) durante l'ultima riunione.\n(Fill in the congiuntivo passato)",
      accepted: ["abbiano litigato"],
      hint: "si dice che + congiuntivo passato, plural subject.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-028",
      type: "fill_blank",
      prompt: "Si dice che il traffico in centro ___ (diminuire) grazie alla nuova legge.\n(Fill in the congiuntivo passato)",
      accepted: ["sia diminuito"],
      hint: "essere + participio in congiuntivo passato, agreeing with il traffico (m.sg.).",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-029",
      type: "fill_blank",
      prompt: "Si dice che molte famiglie non ___ (leggere) più il quotidiano ogni giorno.\n(Fill in the congiuntivo presente)",
      accepted: ["leggano"],
      hint: "si dice che + congiuntivo presente, plural subject.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-030",
      type: "fill_blank",
      prompt: "Si dice che l'evento di sabato ___ (essere) rimandato per il maltempo.\n(Fill in the congiuntivo passato of essere + participio)",
      accepted: ["sia stato"],
      hint: "congiuntivo passato of essere, forming the passivo 'sia stato rimandato'.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-031",
      type: "fill_blank",
      prompt: "Pare che l'incidente sull'autostrada ___ (essere) causato dalla nebbia.\n(Fill in the congiuntivo passato of essere)",
      accepted: ["sia stato"],
      hint: "pare che + congiuntivo passato, forming the passivo 'sia stato causato'.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-032",
      type: "fill_blank",
      prompt: "Sembra che il numero dei casi ___ (crescere) rispetto al mese scorso.\n(Fill in the congiuntivo passato)",
      accepted: ["sia cresciuto"],
      hint: "essere + participio in congiuntivo passato, agreeing with il numero (m.sg.).",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-033",
      type: "fill_blank",
      prompt: "Pare che l'articolo sul giornale ___ (contenere) alcuni errori.\n(Fill in the congiuntivo presente)",
      accepted: ["contenga"],
      hint: "pare che + congiuntivo presente.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-034",
      type: "fill_blank",
      prompt: "Sembra che molte persone ___ (informarsi) solo sui social ormai.\n(Fill in the congiuntivo presente, reflexive)",
      accepted: ["si informino"],
      hint: "Reflexive verb in congiuntivo presente: si + informino.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-035",
      type: "fill_blank",
      prompt: "Pare che il governo ___ (volere) rivedere la legge sulla stampa.\n(Fill in the congiuntivo presente)",
      accepted: ["voglia"],
      hint: "pare che + congiuntivo presente of volere.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-036",
      type: "fill_blank",
      prompt: "Sembra che questa notizia ___ (essere) esagerata dai social media.\n(Fill in the congiuntivo presente)",
      accepted: ["sia"],
      hint: "sembra che + congiuntivo presente of essere.",
      tags: ["grammar", "congiuntivo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-037",
      type: "fill_blank",
      prompt: "Mentre io ___ (guardare) il notiziario, è arrivata la notizia del terremoto.\n(Fill in the imperfetto)",
      accepted: ["guardavo"],
      hint: "imperfetto for an ongoing background action interrupted by a sudden event.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-038",
      type: "fill_blank",
      prompt: "Ieri sera il quotidiano ___ (pubblicare) un lungo articolo molto discusso.\n(Fill in the passato prossimo)",
      accepted: ["ha pubblicato"],
      hint: "passato prossimo for a single completed action.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-039",
      type: "fill_blank",
      prompt: "Quando ___ (essere) piccolo, mio nonno leggeva il giornale ogni mattina a colazione.\n(Fill in the imperfetto)",
      accepted: ["ero"],
      hint: "imperfetto for a habitual/background situation in the past.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-040",
      type: "fill_blank",
      prompt: "L'anno scorso ___ (scoppiare) uno scandalo che ha coinvolto diversi politici.\n(Fill in the passato prossimo)",
      accepted: ["è scoppiato"],
      hint: "passato prossimo of scoppiare with essere, for a single completed event.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-041",
      type: "fill_blank",
      prompt: "Mentre leggevo la rivista, mio fratello ___ (guardare) il meteo alla TV.\n(Fill in the imperfetto)",
      accepted: ["guardava"],
      hint: "imperfetto for two simultaneous background actions.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-042",
      type: "fill_blank",
      prompt: "Ieri il notiziario ___ (parlare) per venti minuti dello sciopero dei treni.\n(Fill in the passato prossimo)",
      accepted: ["ha parlato"],
      hint: "passato prossimo, a bounded, completed span of time.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-043",
      type: "fill_blank",
      prompt: "Da bambina, mia madre ___ (seguire) sempre le notizie sportive con suo padre.\n(Fill in the imperfetto)",
      accepted: ["seguiva"],
      hint: "imperfetto for a repeated childhood habit.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-044",
      type: "fill_blank",
      prompt: "Il quotidiano ___ (scrivere) un lungo articolo sull'evento appena tre giorni dopo.\n(Fill in the passato prossimo)",
      accepted: ["ha scritto"],
      hint: "Irregular participle scritto, passato prossimo with avere.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-045",
      type: "fill_blank",
      prompt: "Mentre eravamo al bar, qualcuno ___ (condividere) la notizia sul telefono.\n(Fill in the passato prossimo)",
      accepted: ["ha condiviso"],
      hint: "Irregular participle condiviso, passato prossimo with avere.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-046",
      type: "fill_blank",
      prompt: "Quando è successo l'incidente, io ___ (essere) al lavoro e non ho visto nulla in diretta.\n(Fill in the imperfetto)",
      accepted: ["ero"],
      hint: "imperfetto for the background situation ('where I was') at the moment of the event.",
      tags: ["grammar", "imperfetto", "passato-prossimo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-047",
      type: "fill_blank",
      prompt: "___ me, la situazione politica peggiorerà entro l'anno.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + pronoun/noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-048",
      type: "fill_blank",
      prompt: "___ il quotidiano di oggi, i prezzi del gas aumenteranno il mese prossimo.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-049",
      type: "fill_blank",
      prompt: "___ gli esperti, l'economia crescerà lentamente quest'anno.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + plural noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-050",
      type: "fill_blank",
      prompt: "___ le previsioni del tempo, domani pioverà su tutta la regione.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-051",
      type: "fill_blank",
      prompt: "___ molti lettori, l'articolo era troppo di parte.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-052",
      type: "fill_blank",
      prompt: "___ te, questa notizia è vera o è solo un'indiscrezione?\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + pronoun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-053",
      type: "fill_blank",
      prompt: "___ il commento di ieri, la crisi non è ancora finita.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    {
      id: "b148-t2-054",
      type: "fill_blank",
      prompt: "___ la rivista di attualità che ho letto, il fenomeno è in crescita.\n(Fill in the preposition meaning 'according to')",
      accepted: ["Secondo"],
      hint: "secondo + noun = according to.",
      tags: ["grammar", "secondo", "news", "fill-blank"],
      tier: 2,
    },
    // ─── Tier 3 – Phrases & collocations for reading, watching, and discussing the news ───
    {
      id: "b148-t3-001",
      type: "produce",
      prompt: "to turn on the evening news",
      accepted: ["accendere il telegiornale della sera"],
      hint: "accendere = to turn on (a device).",
      tags: ["chunk", "news", "tv"],
      tier: 3,
    },
    {
      id: "b148-t3-002",
      type: "produce",
      prompt: "to turn off the TV",
      accepted: ["spegnere la televisione"],
      hint: "spegnere = to turn off; irregular past participle spento.",
      tags: ["chunk", "news", "tv"],
      tier: 3,
    },
    {
      id: "b148-t3-003",
      type: "produce",
      prompt: "to take a look at the newspaper",
      accepted: ["dare un'occhiata al giornale"],
      hint: "dare un'occhiata a = to glance at.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-004",
      type: "produce",
      prompt: "to flip through a magazine",
      accepted: ["sfogliare una rivista"],
      hint: "sfogliare = to leaf through (from foglio, a sheet/page).",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-005",
      type: "produce",
      prompt: "to read the news online",
      accepted: ["leggere le notizie online"],
      hint: "A common alternative to buying the printed paper.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-006",
      type: "produce",
      prompt: "to check the news on your phone",
      accepted: ["controllare le notizie sul telefono"],
      hint: "controllare = to check.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-007",
      type: "produce",
      prompt: "to listen to the radio news",
      accepted: ["ascoltare il notiziario alla radio"],
      hint: "il notiziario alla radio, common during a commute.",
      tags: ["chunk", "news", "radio"],
      tier: 3,
    },
    {
      id: "b148-t3-008",
      type: "produce",
      prompt: "to subscribe to a daily newspaper",
      accepted: ["abbonarsi a un quotidiano"],
      hint: "abbonarsi a = to subscribe to.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-009",
      type: "produce",
      prompt: "to follow a story closely",
      accepted: ["seguire un caso da vicino"],
      hint: "da vicino = closely (literally 'from close by').",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-010",
      type: "produce",
      prompt: "to keep up with current affairs",
      accepted: ["tenersi aggiornato sull'attualità"],
      hint: "tenersi aggiornato su = to stay updated on.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-011",
      type: "produce",
      prompt: "to be well-informed",
      accepted: ["essere ben informato"],
      hint: "essere + adverb + past participle used as adjective.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-012",
      type: "produce",
      prompt: "to be up to date on something",
      accepted: ["essere aggiornato su qualcosa"],
      hint: "essere aggiornato su = to be up to date on.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-013",
      type: "produce",
      prompt: "to keep oneself informed about what's happening in the world",
      accepted: ["informarsi su ciò che succede nel mondo"],
      hint: "ciò che succede = what happens/is happening.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-014",
      type: "produce",
      prompt: "to miss a piece of news",
      accepted: ["perdersi una notizia"],
      hint: "perdersi = to miss out on (reflexive).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-015",
      type: "produce",
      prompt: "to share an article on social media",
      accepted: ["condividere un articolo sui social"],
      hint: "sui social = on social media (colloquial, invariable).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-016",
      type: "produce",
      prompt: "to leave a comment on an article",
      accepted: ["lasciare un commento su un articolo"],
      hint: "lasciare un commento = to leave a comment.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-017",
      type: "produce",
      prompt: "to discuss the news with friends",
      accepted: ["discutere delle notizie con gli amici"],
      hint: "discutere di = to discuss.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-018",
      type: "produce",
      prompt: "to have heard about something",
      accepted: ["aver sentito parlare di qualcosa"],
      hint: "sentire parlare di = to hear about (through others).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-019",
      type: "produce",
      prompt: "Have you heard that...?",
      accepted: ["Hai sentito che...?"],
      hint: "A common conversational opener for sharing news.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-020",
      type: "produce",
      prompt: "Have you seen that...? (in the news)",
      accepted: ["Hai visto che...?"],
      hint: "Another conversational opener for sharing news.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-021",
      type: "produce",
      prompt: "Did you see the news today?",
      accepted: ["Hai visto le notizie oggi?"],
      hint: "le notizie = the news, plural in Italian.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-022",
      type: "produce",
      prompt: "I can't believe it.",
      accepted: ["Non ci posso credere."],
      hint: "credere a/in qualcosa; here 'ci' replaces 'a questo'.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-023",
      type: "produce",
      prompt: "What incredible news!",
      accepted: ["Che notizia incredibile!"],
      hint: "Che + noun + adjective, a common exclamation.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-024",
      type: "fill_blank",
      prompt: "Questa è una notizia molto ___.\n(Fill in the adjective meaning 'worrying')",
      accepted: ["preoccupante"],
      hint: "preoccupante, invariable for gender.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-025",
      type: "produce",
      prompt: "It's a surprising piece of news.",
      accepted: ["È una notizia sorprendente."],
      hint: "sorprendente, invariable for gender.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-026",
      type: "produce",
      prompt: "an important local event",
      accepted: ["un evento locale importante"],
      hint: "locale is invariable for gender.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-027",
      type: "produce",
      prompt: "a national daily (newspaper)",
      accepted: ["un quotidiano nazionale"],
      hint: "nazionale is invariable for gender.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-028",
      type: "produce",
      prompt: "an international scandal",
      accepted: ["uno scandalo internazionale"],
      hint: "internazionale is invariable for gender.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-029",
      type: "produce",
      prompt: "an important sports event",
      accepted: ["un evento sportivo importante"],
      hint: "sportivo agrees with evento (masculine).",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-030",
      type: "produce",
      prompt: "a current-affairs magazine",
      accepted: ["una rivista di attualità"],
      hint: "di + noun to describe the type of magazine.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-031",
      type: "produce",
      prompt: "the evening edition (of the paper)",
      accepted: ["l'edizione della sera"],
      hint: "l'edizione = the edition.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-032",
      type: "produce",
      prompt: "the latest news",
      accepted: ["le ultime notizie"],
      hint: "le ultime = the latest (feminine plural, agreeing with notizie).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-033",
      type: "produce",
      prompt: "breaking news",
      accepted: ["notizie dell'ultima ora"],
      hint: "Literally 'news of the last hour.'",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-034",
      type: "produce",
      prompt: "live (broadcast)",
      accepted: ["in diretta"],
      hint: "Used for TV/radio broadcasts happening in real time.",
      tags: ["chunk", "news", "tv"],
      tier: 3,
    },
    {
      id: "b148-t3-035",
      type: "produce",
      prompt: "What's new?",
      accepted: ["Cosa c'è di nuovo?"],
      hint: "A casual conversation opener.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-036",
      type: "produce",
      prompt: "What's going on in the world?",
      accepted: ["Cosa succede nel mondo?"],
      hint: "succedere = to happen.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-037",
      type: "produce",
      prompt: "Everyone is talking about it.",
      accepted: ["Tutti ne parlano."],
      hint: "'ne' replaces 'di questo/di questa cosa'.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-038",
      type: "produce",
      prompt: "It's all over the news.",
      accepted: ["È su tutti i notiziari."],
      hint: "su tutti i notiziari = on every newscast.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-039",
      type: "produce",
      prompt: "Nothing new today.",
      accepted: ["Niente di nuovo oggi."],
      hint: "niente di + adjective.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-040",
      type: "produce",
      prompt: "From what I read",
      accepted: ["Da quello che ho letto"],
      hint: "da quello che + verb = from what...",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-041",
      type: "produce",
      prompt: "As far as I know",
      accepted: ["Per quanto ne so"],
      hint: "'ne' = about it; a common hedge before sharing information.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-042",
      type: "produce",
      prompt: "As they say",
      accepted: ["Come si dice"],
      hint: "si dice = it is said (impersonal si).",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-043",
      type: "produce",
      prompt: "Word has it that...",
      accepted: ["Corre voce che..."],
      hint: "correre voce che = word/rumor is going around that.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-044",
      type: "produce",
      prompt: "an insider leak / rumor",
      accepted: ["un'indiscrezione"],
      hint: "Elided article un' before a vowel.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-045",
      type: "produce",
      prompt: "according to an insider leak",
      accepted: ["secondo un'indiscrezione"],
      hint: "secondo + noun.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-046",
      type: "produce",
      prompt: "to keep an eye on the news",
      accepted: ["tenere d'occhio le notizie"],
      hint: "tenere d'occhio = to keep an eye on.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-047",
      type: "produce",
      prompt: "to be behind on the news",
      accepted: ["essere indietro con le notizie"],
      hint: "essere indietro con = to be behind on.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-048",
      type: "produce",
      prompt: "to catch up on the news",
      accepted: ["mettersi in pari con le notizie"],
      hint: "mettersi in pari con = to catch up on.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-049",
      type: "produce",
      prompt: "News travels fast.",
      accepted: ["Le notizie viaggiano veloci."],
      hint: "viaggiare = to travel, used figuratively here.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-050",
      type: "produce",
      prompt: "bad news",
      accepted: ["una brutta notizia"],
      hint: "brutta agrees with notizia (feminine).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-051",
      type: "produce",
      prompt: "good news",
      accepted: ["una buona notizia"],
      hint: "buona agrees with notizia (feminine).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-052",
      type: "produce",
      prompt: "old news",
      accepted: ["una notizia vecchia"],
      hint: "Used for something already known, no longer new.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-053",
      type: "produce",
      prompt: "to make the headlines",
      accepted: ["finire su tutti i giornali"],
      hint: "Literally 'to end up in all the newspapers.'",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-054",
      type: "produce",
      prompt: "to be in the spotlight",
      accepted: ["essere sotto i riflettori"],
      hint: "sotto i riflettori = under the spotlights.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-055",
      type: "produce",
      prompt: "sports results",
      accepted: ["i risultati sportivi"],
      hint: "sportivi agrees with risultati (masculine plural).",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-056",
      type: "produce",
      prompt: "the final score",
      accepted: ["il punteggio finale"],
      hint: "il punteggio = the score.",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-057",
      type: "fill_blank",
      prompt: "___ uno scandalo ogni volta che cambia il governo.\n(Fill in the present-tense verb meaning 'a scandal breaks out')",
      accepted: ["Scoppia"],
      hint: "scoppiare, presente, terza persona singolare.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-058",
      type: "fill_blank",
      prompt: "Secondo il notiziario, la situazione sta ___.\n(Fill in the verb form meaning 'worsening')",
      accepted: ["peggiorando"],
      hint: "stare + gerundio = an action in progress.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-059",
      type: "produce",
      prompt: "The economy is growing.",
      accepted: ["L'economia sta crescendo."],
      hint: "stare + gerundio.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-060",
      type: "fill_blank",
      prompt: "La disoccupazione sta ___, secondo l'ultimo rapporto.\n(Fill in the verb form meaning 'decreasing')",
      accepted: ["diminuendo"],
      hint: "stare + gerundio of diminuire.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-061",
      type: "fill_blank",
      prompt: "I prezzi stanno ___ di nuovo, secondo il quotidiano.\n(Fill in the verb form meaning 'rising')",
      accepted: ["aumentando"],
      hint: "stare + gerundio of aumentare.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-062",
      type: "produce",
      prompt: "An earthquake struck the region.",
      accepted: ["Un terremoto ha colpito la regione."],
      hint: "colpire = to strike; passato prossimo with avere.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-063",
      type: "produce",
      prompt: "A storm is coming.",
      accepted: ["Sta arrivando un temporale."],
      hint: "stare + gerundio for an event in progress right now.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-064",
      type: "produce",
      prompt: "Rain is expected this weekend.",
      accepted: ["È prevista pioggia questo fine settimana."],
      hint: "essere previsto/a = to be expected/forecast.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-065",
      type: "produce",
      prompt: "Sunny weather all week.",
      accepted: ["Tempo soleggiato per tutta la settimana."],
      hint: "soleggiato = sunny.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-066",
      type: "produce",
      prompt: "The strike will continue tomorrow.",
      accepted: ["Lo sciopero continuerà domani."],
      hint: "futuro semplice of continuare.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-067",
      type: "produce",
      prompt: "There's a lot of traffic today because of the strike.",
      accepted: ["C'è molto traffico oggi per lo sciopero."],
      hint: "per + noun = because of.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-068",
      type: "produce",
      prompt: "an interesting article",
      accepted: ["un articolo interessante"],
      hint: "interessante is invariable for gender.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-069",
      type: "produce",
      prompt: "a well-written article",
      accepted: ["un articolo ben scritto"],
      hint: "ben scritto = well-written.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-070",
      type: "produce",
      prompt: "to read between the lines",
      accepted: ["leggere tra le righe"],
      hint: "tra le righe = between the lines.",
      tags: ["chunk", "news", "reading"],
      tier: 3,
    },
    {
      id: "b148-t3-071",
      type: "produce",
      prompt: "to take news with a grain of salt",
      accepted: ["prendere una notizia con le pinze"],
      hint: "con le pinze = literally 'with tongs' — an Italian idiom for caution.",
      tags: ["chunk", "news", "idiom"],
      tier: 3,
    },
    {
      id: "b148-t3-072",
      type: "produce",
      prompt: "word of mouth",
      accepted: ["il passaparola"],
      hint: "Literally 'pass-the-word'; a single compound noun.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-073",
      type: "produce",
      prompt: "to spread like wildfire (of news)",
      accepted: ["diffondersi a macchia d'olio"],
      hint: "a macchia d'olio = literally 'like an oil stain' — an Italian idiom.",
      tags: ["chunk", "news", "idiom"],
      tier: 3,
    },
    {
      id: "b148-t3-074",
      type: "produce",
      prompt: "Rumor has it that...",
      accepted: ["Si vocifera che..."],
      hint: "vociferare = to rumor, impersonal si.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-075",
      type: "produce",
      prompt: "to be a hot topic",
      accepted: ["essere un argomento caldo"],
      hint: "argomento caldo = a hot/current topic.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-076",
      type: "produce",
      prompt: "public opinion",
      accepted: ["l'opinione pubblica"],
      hint: "l'opinione pubblica, a fixed collocation.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-077",
      type: "produce",
      prompt: "to have a strong opinion about something",
      accepted: ["avere un'opinione forte su qualcosa"],
      hint: "opinione forte = strong opinion.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-078",
      type: "produce",
      prompt: "to change the subject",
      accepted: ["cambiare argomento"],
      hint: "cambiare argomento, a common conversational move.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-079",
      type: "produce",
      prompt: "to change the channel",
      accepted: ["cambiare canale"],
      hint: "cambiare canale, distinct from cambiare argomento.",
      tags: ["chunk", "news", "tv"],
      tier: 3,
    },
    {
      id: "b148-t3-080",
      type: "produce",
      prompt: "to keep track of something",
      accepted: ["tenere traccia di qualcosa"],
      hint: "tenere traccia di = to keep track of.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-081",
      type: "produce",
      prompt: "a reliable news channel",
      accepted: ["un canale di informazione affidabile"],
      hint: "affidabile = reliable/trustworthy.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-082",
      type: "produce",
      prompt: "fake news",
      accepted: ["le notizie false"],
      hint: "false agrees with notizie (feminine plural), avoiding the English loanword.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-083",
      type: "produce",
      prompt: "news from abroad",
      accepted: ["le notizie dall'estero"],
      hint: "dall'estero = from abroad.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-084",
      type: "produce",
      prompt: "to check the weather forecast (everyday word)",
      accepted: ["controllare il meteo"],
      hint: "controllare il meteo, everyday spoken register.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-085",
      type: "produce",
      prompt: "the weather forecast (formal)",
      accepted: ["le previsioni del tempo"],
      hint: "More formal/technical than il meteo.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-086",
      type: "produce",
      prompt: "What will the weather be like tomorrow?",
      accepted: ["Che tempo farà domani?"],
      hint: "fare + weather expression, futuro semplice.",
      tags: ["chunk", "news", "weather"],
      tier: 3,
    },
    {
      id: "b148-t3-087",
      type: "produce",
      prompt: "local news",
      accepted: ["le notizie locali"],
      hint: "locali agrees with notizie (feminine plural).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-088",
      type: "produce",
      prompt: "national news",
      accepted: ["le notizie nazionali"],
      hint: "nazionali agrees with notizie (feminine plural).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-089",
      type: "produce",
      prompt: "world / international news",
      accepted: ["le notizie internazionali"],
      hint: "internazionali agrees with notizie (feminine plural).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-090",
      type: "produce",
      prompt: "sports news",
      accepted: ["le notizie sportive"],
      hint: "sportive agrees with notizie (feminine plural).",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-091",
      type: "produce",
      prompt: "an ongoing case",
      accepted: ["un caso ancora aperto"],
      hint: "ancora aperto = still open.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-092",
      type: "fill_blank",
      prompt: "Il ___ è ancora aperto: la polizia continua a indagare.\n(Fill in the noun meaning 'case/story')",
      accepted: ["caso"],
      hint: "il caso, the same noun taught in Tier 1.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-093",
      type: "produce",
      prompt: "to open the newspaper to the sports section",
      accepted: ["aprire il giornale alla pagina sportiva"],
      hint: "la pagina sportiva = the sports page.",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-094",
      type: "produce",
      prompt: "to skip straight to the sports section",
      accepted: ["andare direttamente alla pagina sportiva"],
      hint: "andare direttamente a = to go straight to.",
      tags: ["chunk", "news", "sports"],
      tier: 3,
    },
    {
      id: "b148-t3-095",
      type: "produce",
      prompt: "to talk about politics at the table",
      accepted: ["parlare di politica a tavola"],
      hint: "a tavola = at the (dinner) table.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-096",
      type: "produce",
      prompt: "It's not official yet.",
      accepted: ["Non è ancora ufficiale."],
      hint: "ancora = yet/still with a negative.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-097",
      type: "produce",
      prompt: "Nothing has been confirmed.",
      accepted: ["Non è stato confermato niente."],
      hint: "passivo, essere + participio.",
      tags: ["chunk", "news", "conversation"],
      tier: 3,
    },
    {
      id: "b148-t3-098",
      type: "produce",
      prompt: "to wait for confirmation",
      accepted: ["aspettare una conferma"],
      hint: "una conferma = a confirmation.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-099",
      type: "fill_blank",
      prompt: "Per ora è solo una notizia non ___: aspettiamo la conferma ufficiale.\n(Fill in the adjective meaning 'confirmed')",
      accepted: ["confermata"],
      hint: "confermata agrees with notizia (feminine).",
      tags: ["chunk", "news"],
      tier: 3,
    },
    {
      id: "b148-t3-100",
      type: "produce",
      prompt: "to keep a story alive (in the news)",
      accepted: ["tenere viva una notizia"],
      hint: "tenere vivo/a = to keep alive.",
      tags: ["chunk", "news"],
      tier: 3,
    },
    // ─── Tier 4 – Passages: reading, watching, and discussing the news in everyday life ───
    {
      id: "b148-t4-001",
      type: "passage_cloze",
      prompt: "Ogni mattina mio nonno si siede a colazione e apre il quotidiano prima ancora di bere il caffè. Legge sempre le notizie locali per primo, poi passa alla pagina sportiva. Io, invece, controllo le notizie sul telefono mentre esco di casa. Ieri gli ho chiesto perché preferisce ancora la carta stampata. Mi ha risposto che, con un giornale in mano, riesce a ___ tra le righe molto meglio che su uno schermo.",
      accepted: ["leggere"],
      hint: "The infinitive following 'riesce a' — the collocation leggere tra le righe.",
      tags: ["passage_cloze", "news", "reading", "family"],
      tier: 4,
    },
    {
      id: "b148-t4-002",
      type: "passage_cloze",
      prompt: "\"Hai sentito che c'è stato un terremoto vicino a Napoli stanotte?\" mi ha scritto Marta stamattina. Non lo sapevo, così ho subito acceso il telegiornale della sera prima e poi ho controllato le notizie online. Per fortuna, sembra che nessuno ___ ferito, anche se alcune case hanno subito danni. Aspettiamo comunque la conferma ufficiale prima di credere a tutti i dettagli che girano sui social.",
      accepted: ["sia rimasto"],
      hint: "Congiuntivo passato after 'sembra che', agreeing with nessuno (masculine singular).",
      tags: ["passage_cloze", "news", "congiuntivo"],
      tier: 4,
    },
    {
      id: "b148-t4-003",
      type: "passage_cloze",
      prompt: "Questo weekend andiamo in montagna con gli amici, quindi ieri sera ho controllato il meteo prima di preparare le valigie. Le previsioni dicono che sabato ci sarà sole per tutto il giorno, ma domenica potrebbe arrivare un temporale nel pomeriggio. Se davvero ___ come previsto, torneremo a casa prima del previsto per evitare la pioggia in autostrada.",
      accepted: ["piovesse"],
      hint: "Congiuntivo imperfetto after 'se', for a hypothetical weather scenario.",
      tags: ["passage_cloze", "news", "weather"],
      tier: 4,
    },
    {
      id: "b148-t4-004",
      type: "passage_cloze",
      prompt: "Al bar, ogni mattina, un gruppo di pensionati discute delle notizie del giorno davanti a un caffè. Ieri l'argomento era uno scandalo scoppiato al comune: si dice che due consiglieri ___ soldi pubblici per anni senza che nessuno se ne accorgesse. Nessuno sa ancora quanto sia vero, ma tutti in paese ne parlano.",
      accepted: ["abbiano usato"],
      hint: "Congiuntivo passato after 'si dice che', plural subject (due consiglieri).",
      tags: ["passage_cloze", "news", "congiuntivo"],
      tier: 4,
    },
    {
      id: "b148-t4-005",
      type: "passage_cloze",
      prompt: "Mia nonna non si fida dei siti di notizie online: dice che chiunque può scrivere qualsiasi cosa senza controllare se è vera. Preferisce il suo quotidiano di sempre, che legge dalla prima all'ultima pagina ogni giorno. Io invece leggo le notizie sul telefono, ma cerco sempre di ___ le fonti prima di condividere un articolo con gli amici.",
      accepted: ["verificare"],
      hint: "The infinitive meaning 'to verify/check', object of 'cercare di'.",
      tags: ["passage_cloze", "news", "reading"],
      tier: 4,
    },
    {
      id: "b148-t4-006",
      type: "passage_cloze",
      prompt: "Durante il viaggio in treno ascolto sempre il notiziario dal telefono con le cuffie. Stamattina hanno parlato a lungo di uno sciopero dei mezzi pubblici previsto per venerdì. Secondo il commento di un esperto, il traffico in città ___ molto peggio del solito, quindi ho deciso di partire un'ora prima per essere sicuro di arrivare in tempo al lavoro.",
      accepted: ["sarebbe stato"],
      hint: "Condizionale composto of essere, for an unconfirmed prediction reported by an expert.",
      tags: ["passage_cloze", "news", "condizionale-composto"],
      tier: 4,
    },
    {
      id: "b148-t4-007",
      type: "passage_cloze",
      prompt: "Ieri sera, dopo cena, io e mio marito abbiamo guardato insieme il telegiornale come facciamo sempre. Prima le notizie nazionali, poi quelle internazionali, e infine il meteo per il weekend. Quando è arrivato il servizio sullo sport, lui si è alzato per prendere un caffè: dice che le notizie sportive non gli ___ mai interessate molto, a differenza mia.",
      accepted: ["sono"],
      hint: "Passato prossimo of interessare with essere (impersonal use, third person plural agreeing with 'notizie sportive').",
      tags: ["passage_cloze", "news", "sports"],
      tier: 4,
    },
    {
      id: "b148-t4-008",
      type: "passage_cloze",
      prompt: "Ho letto un articolo molto interessante su una rivista di attualità: parlava di come i giovani si informano oggi, quasi tutti tramite i social invece che con il quotidiano o il telegiornale. L'autore sosteneva che questo cambiamento ___ inevitabile, dato che le nuove generazioni sono cresciute con il telefono sempre in mano.",
      accepted: ["fosse"],
      hint: "Congiuntivo imperfetto after 'sosteneva che', matching the past tense of the reporting verb.",
      tags: ["passage_cloze", "news", "reading"],
      tier: 4,
    },
    {
      id: "b148-t4-009",
      type: "passage_cloze",
      prompt: "\"Cosa c'è di nuovo?\" mi ha chiesto Luca appena seduto al bar. Gli ho raccontato che, secondo un'indiscrezione uscita ieri sera, l'allenatore della nostra squadra ___ già le dimissioni al presidente, anche se il club non ha confermato nulla. Luca non ci voleva credere, ma tutti i tifosi al bar non parlavano d'altro.",
      accepted: ["avrebbe rassegnato"],
      hint: "Condizionale composto, avere + participio, reporting an unconfirmed insider leak.",
      tags: ["passage_cloze", "news", "condizionale-composto", "sports"],
      tier: 4,
    },
    {
      id: "b148-t4-010",
      type: "passage_cloze",
      prompt: "Mentre facevo colazione, ho sentito alla radio un commento su un nuovo scandalo internazionale legato a una grande azienda tecnologica. Pare che l'azienda ___ i dati dei clienti senza il loro permesso per anni. La notizia è già su tutti i notiziari e i giornali ne parlano da stamattina.",
      accepted: ["abbia usato"],
      hint: "Congiuntivo passato after 'pare che', agreeing with l'azienda.",
      tags: ["passage_cloze", "news", "congiuntivo"],
      tier: 4,
    },
    {
      id: "b148-t4-011",
      type: "passage_cloze",
      prompt: "Da bambina seguivo sempre il telegiornale con mia madre, seduta sul divano dopo cena. Lei mi spiegava le notizie più difficili e io facevo domande su tutto quello che non capivo. Oggi, molti anni dopo, continuo ad ___ ogni sera, ma ormai lo faccio da sola, sul divano di casa mia.",
      accepted: ["informarmi"],
      hint: "Reflexive verb informarsi, infinitive form after 'continuare ad'.",
      tags: ["passage_cloze", "news", "family"],
      tier: 4,
    },
    {
      id: "b148-t4-012",
      type: "passage_cloze",
      prompt: "In ufficio, durante la pausa caffè, i miei colleghi discutono spesso di attualità. Ieri l'argomento caldo era l'aumento dei prezzi del gas: secondo il quotidiano che legge il mio collega, il costo dell'energia ___ ancora prima dell'inverno. Nessuno era contento di sentirlo, ma tutti concordavano che era un'informazione utile da sapere in anticipo.",
      accepted: ["sarebbe aumentato"],
      hint: "Condizionale composto, essere + participio, agreeing with il costo (m.sg.).",
      tags: ["passage_cloze", "news", "condizionale-composto"],
      tier: 4,
    },
    {
      id: "b148-t4-013",
      type: "passage_cloze",
      prompt: "Ogni domenica compro una rivista di attualità e la sfoglio con calma dopo pranzo, senza fretta. Questa settimana c'era un lungo articolo su un caso locale che ha tenuto tutto il paese con il fiato sospeso per mesi. Alla fine dell'articolo, il caso ___ ancora aperto: la polizia continua a cercare nuove prove.",
      accepted: ["risultava"],
      hint: "Imperfetto of risultare, describing an ongoing state at the time of writing the article.",
      tags: ["passage_cloze", "news", "reading"],
      tier: 4,
    },
    {
      id: "b148-t4-014",
      type: "passage_cloze",
      prompt: "Mio fratello lavora all'estero e per restare aggiornato sulle notizie italiane legge il quotidiano online ogni sera, dopo il lavoro. Mi ha detto che, vivendo lontano, si sente più legato al suo paese proprio grazie a queste piccole abitudini. Ieri mi ha scritto che, secondo un articolo che aveva letto, l'economia italiana ___ più lentamente del previsto quest'anno.",
      accepted: ["starebbe crescendo"],
      hint: "Condizionale composto of stare + gerundio, expressing an unconfirmed ongoing trend reported in an article.",
      tags: ["passage_cloze", "news", "condizionale-composto"],
      tier: 4,
    },
    {
      id: "b148-t4-015",
      type: "passage_cloze",
      prompt: "Durante la cena di famiglia, mio zio ha acceso una discussione parlando di politica, come fa sempre. Mia zia gli ha ricordato che, secondo le buone maniere, non si dovrebbe parlare di politica a tavola. Lui ha risposto ridendo che, secondo lui, l'attualità ___ sempre un argomento interessante, anche durante il dolce.",
      accepted: ["resta"],
      hint: "Presente indicativo of restare, a simple opinion stated as fact.",
      tags: ["passage_cloze", "news", "family"],
      tier: 4,
    },
    {
      id: "b148-t4-016",
      type: "passage_cloze",
      prompt: "Ieri pomeriggio, mentre aspettavo l'autobus, ho visto un uomo leggere il giornale con molta attenzione, senza guardare mai il telefono. Mi ha colpito, perché ormai è raro vedere qualcuno sfogliare le pagine di carta invece dello schermo. Gli ho chiesto cosa stesse leggendo e mi ha detto che era un commento sulla situazione economica che ___ leggere per intero, senza distrazioni.",
      accepted: ["voleva"],
      hint: "Imperfetto of volere, describing an ongoing intention at that moment.",
      tags: ["passage_cloze", "news", "reading"],
      tier: 4,
    },
    {
      id: "b148-t4-017",
      type: "passage_cloze",
      prompt: "Ogni sabato sera, prima di cena, mio padre accende la radio per ascoltare i risultati sportivi della giornata. Se la sua squadra ha vinto, resta di buon umore per tutta la sera; se ha perso, meglio non parlargli di calcio fino al giorno dopo. Ieri, prima che i risultati ___ annunciati, era già nervosissimo.",
      accepted: ["fossero"],
      hint: "Congiuntivo imperfetto of essere after 'prima che', forming the passivo 'fossero annunciati'.",
      tags: ["passage_cloze", "news", "congiuntivo", "sports"],
      tier: 4,
    },
    {
      id: "b148-t4-018",
      type: "passage_cloze",
      prompt: "Da quando lavoro da casa, il mio unico contatto con le notizie del mattino è il notiziario che ascolto mentre preparo il caffè. Ieri hanno parlato per dieci minuti di un evento locale che aveva bloccato il traffico in centro. Secondo il commento del giornale locale, l'evento ___ organizzato senza il permesso del comune.",
      accepted: ["era stato"],
      hint: "Trapassato prossimo of the passivo, essere + participio, describing an action prior to the main narration.",
      tags: ["passage_cloze", "news"],
      tier: 4,
    },
    {
      id: "b148-t4-019",
      type: "passage_cloze",
      prompt: "Tornata dalle vacanze dopo due settimane senza internet, mi sono resa conto di essere completamente indietro con le notizie. Ho passato la prima serata a mettermi in pari: ho letto tre quotidiani diversi e ho guardato due notiziari di seguito. Alla fine ho capito che, in fondo, non ___ successo niente di così importante mentre ero via.",
      accepted: ["era"],
      hint: "Imperfetto of essere in the impersonal construction with 'niente', describing a background realization.",
      tags: ["passage_cloze", "news"],
      tier: 4,
    },
    {
      id: "b148-t4-020",
      type: "passage_cloze",
      prompt: "Al gruppo del quartiere sul telefono, qualcuno ha condiviso un articolo su un presunto scandalo alla scuola elementare locale. Molti genitori si sono preoccupati subito, ma un'altra madre ha scritto di aspettare prima di credere a tutto: secondo lei, bisognava prima ___ se la notizia fosse vera o solo un'indiscrezione senza fondamento.",
      accepted: ["verificare"],
      hint: "Infinitive after 'bisognava prima', meaning to check/verify before trusting a claim.",
      tags: ["passage_cloze", "news", "family"],
      tier: 4,
    },
    {
      id: "b148-t4-021",
      type: "passage_cloze",
      prompt: "Ogni tanto guardo un notiziario internazionale in un'altra lingua solo per confrontare come diversi paesi raccontano lo stesso evento. È interessante notare quanto possa cambiare un articolo a seconda di chi lo scrive. Ieri, per esempio, un giornale straniero descriveva la stessa notizia in modo molto più ___ rispetto ai quotidiani italiani.",
      accepted: ["preoccupante"],
      hint: "Adjective from Tier 1, invariable for gender, describing the tone of the foreign coverage.",
      tags: ["passage_cloze", "news"],
      tier: 4,
    },
    {
      id: "b148-t4-022",
      type: "passage_cloze",
      prompt: "Alla fine della cena, mia suocera ha acceso la televisione per il notiziario delle otto, come fa ogni sera senza eccezioni. Ha commentato ogni servizio ad alta voce, dal meteo alle notizie sportive, fino allo scandalo politico del giorno. Quando le ho chiesto perché lo guardasse sempre alla stessa ora, mi ha risposto che per lei era un modo per sentirsi ___ al resto del mondo.",
      accepted: ["collegata"],
      hint: "Past participle used as adjective, agreeing with 'lei' (feminine): connected to the rest of the world.",
      tags: ["passage_cloze", "news", "family"],
      tier: 4,
    },
  ],
};
export default unit;
