import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b1-unit-24-si-impersonale",
  name: "One Does…",
  level: "B1",
  theme: "Si Impersonale & Si Passivante",
  emoji: "👥",
  prerequisiteUnits: ["b1-unit-23-passivo"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u24-t1-001",
      type: "recognize",
      prompt: "gli ingredienti",
      accepted: ["the ingredients"],
      hint: "what a recipe lists",
      tags: ["noun", "recipe", "food"],
      tier: 1,
    },
    {
      id: "u24-t1-002",
      type: "produce",
      prompt: "the recipe",
      accepted: ["la ricetta"],
      tags: ["noun", "recipe", "food"],
      tier: 1,
    },
    {
      id: "u24-t1-003",
      type: "produce",
      prompt: "the sign / notice",
      accepted: ["il cartello"],
      hint: "posted in public places",
      tags: ["noun", "notices", "public"],
      tier: 1,
    },
    {
      id: "u24-t1-004",
      type: "produce",
      prompt: "the rule",
      accepted: ["la regola"],
      tags: ["noun", "general"],
      tier: 1,
    },
    {
      id: "u24-t1-005",
      type: "recognize",
      prompt: "cuocere",
      accepted: ["to cook", "to bake", "to boil"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-006",
      type: "recognize",
      prompt: "mescolare",
      accepted: ["to mix", "to stir"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-007",
      type: "recognize",
      prompt: "aggiungere",
      accepted: ["to add"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-008",
      type: "recognize",
      prompt: "versare",
      accepted: ["to pour"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-009",
      type: "recognize",
      prompt: "scaldare",
      accepted: ["to heat", "to warm up"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-010",
      type: "recognize",
      prompt: "tagliare",
      accepted: ["to cut", "to slice"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-011",
      type: "recognize",
      prompt: "servire",
      accepted: ["to serve"],
      tags: ["verb", "recipe", "cooking"],
      tier: 1,
    },
    {
      id: "u24-t1-012",
      type: "produce",
      prompt: "the custom / habit (general)",
      accepted: ["l'abitudine", "la consuetudine", "l'usanza"],
      hint: "what people generally do",
      tags: ["noun", "general", "culture"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u24-t2-001",
      type: "conjugate",
      prompt: "mangiare – si impersonale (one eats / people eat)",
      accepted: ["si mangia"],
      hint: "always third-person singular for si impersonale",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-002",
      type: "conjugate",
      prompt: "potere – si impersonale (one can / is one allowed?)",
      accepted: ["si può"],
      hint: "modal + infinitive follows",
      tags: ["grammar", "si-impersonale", "modal"],
      tier: 2,
    },
    {
      id: "u24-t2-003",
      type: "conjugate",
      prompt: "dire – si impersonale (it is said / they say)",
      accepted: ["si dice"],
      hint: "si dice che + subjunctive or indicative",
      tags: ["grammar", "si-impersonale", "expression"],
      tier: 2,
    },
    {
      id: "u24-t2-004",
      type: "conjugate",
      prompt: "vendere (casa, sing.) – si passivante (the house is for sale)",
      accepted: ["si vende"],
      hint: "si passivante agrees with the noun: casa → singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-005",
      type: "conjugate",
      prompt: "affittare (camere, plur.) – si passivante (rooms for rent)",
      accepted: ["si affittano"],
      hint: "si passivante agrees with the noun: camere → plural",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-006",
      type: "conjugate",
      prompt: "parlare (italiano, sing.) – si passivante (Italian is spoken here)",
      accepted: ["si parla"],
      hint: "italiano is singular → verb stays singular",
      tags: ["grammar", "si-passivante", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-007",
      type: "conjugate",
      prompt: "fare – si impersonale (one does / it is done this way)",
      accepted: ["si fa"],
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },
    {
      id: "u24-t2-008",
      type: "conjugate",
      prompt: "usare – si impersonale (one uses / it is used)",
      accepted: ["si usa"],
      hint: "followed by an infinitive in instructions",
      tags: ["grammar", "si-impersonale", "verb"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u24-t3-001",
      type: "produce",
      prompt: "It is said that… (opening phrase)",
      accepted: ["Si dice che…", "Si dice che"],
      hint: "a fixed expression for rumours or general truths",
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-002",
      type: "produce",
      prompt: "For sale: house (sign)",
      accepted: ["Si vende casa", "Vendesi casa"],
      hint: "si passivante – no article needed on signs",
      tags: ["chunk", "si-passivante", "notices"],
      tier: 3,
    },
    {
      id: "u24-t3-003",
      type: "produce",
      prompt: "How do you say ___? / How does one say ___?",
      accepted: ["Come si dice?", "Come si dice ___?"],
      hint: "extremely common question in language learning",
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-004",
      type: "produce",
      prompt: "That's how it's done. / One does it this way.",
      accepted: ["Si fa così", "Si fa così."],
      tags: ["chunk", "si-impersonale", "expression"],
      tier: 3,
    },
    {
      id: "u24-t3-005",
      type: "produce",
      prompt: "One uses a knife to cut it. (si usa + infinitive pattern)",
      accepted: ["Si usa un coltello per tagliarlo.", "Si usa un coltello per tagliare."],
      hint: "si usa + infinitive is very common in instructions",
      tags: ["chunk", "si-impersonale", "recipe"],
      tier: 3,
    },
    {
      id: "u24-t3-006",
      type: "fill_blank",
      prompt: "In Italia ___ bene ovunque. (People eat well everywhere in Italy.)",
      accepted: ["si mangia"],
      hint: "si impersonale of mangiare",
      tags: ["chunk", "si-impersonale", "culture"],
      tier: 3,
    },

    // ── Tier 4 – Production & Passages ───────────────────────────────────────
    {
      id: "u24-t4-001",
      type: "produce",
      prompt: "Translate: 'In this restaurant one eats well and Italian is spoken.'",
      accepted: [
        "In questo ristorante si mangia bene e si parla italiano.",
        "In questo ristorante si mangia bene e si parla l'italiano.",
      ],
      hint: "si impersonale for 'eats'; si passivante for 'Italian is spoken'",
      tags: ["production", "si-impersonale", "si-passivante"],
      tier: 4,
      prerequisites: ["u24-t2-001", "u24-t2-006"],
    },
    {
      id: "u24-t4-002",
      type: "fill_blank",
      prompt: "Annuncio immobiliare: ___ appartamento al terzo piano. (Apartment for sale on the third floor.)",
      accepted: ["Si vende"],
      hint: "si passivante – appartamento is singular masculine",
      tags: ["production", "si-passivante", "notices"],
      tier: 4,
      prerequisites: ["u24-t2-004"],
    },
    {
      id: "u24-t4-003",
      type: "passage_cloze",
      prompt: "Questa è la ricetta della pasta al pomodoro.\nPrima, ___ la cipolla a pezzi piccoli.\nPoi si scalda l'olio in una padella e si aggiunge la cipolla.\nSi cuoce per cinque minuti, poi si versano i pomodori.\nSi mescola bene e si serve con la pasta cotta al dente.",
      accepted: ["si taglia"],
      hint: "si passivante of tagliare – la cipolla is singular feminine",
      tags: ["passage_cloze", "si-passivante", "recipe"],
      tier: 4,
      prerequisites: ["u24-t1-005", "u24-t1-006", "u24-t1-007", "u24-t1-008", "u24-t1-009", "u24-t1-010", "u24-t1-011", "u24-t2-006"],
    },
    {
      id: "u24-t4-004",
      type: "passage_cloze",
      prompt: "In Italia esistono molte tradizioni culinarie.\nSi dice che ogni regione abbia la propria ricetta speciale.\nIn Toscana ___ molto olio d'oliva in cucina.\nSi aggiungono erbe aromatiche a quasi tutti i piatti.\nSi mangia spesso insieme in famiglia, specialmente la domenica.",
      accepted: ["si usa"],
      hint: "si impersonale of usare – always singular",
      tags: ["passage_cloze", "si-impersonale", "culture"],
      tier: 4,
      prerequisites: ["u24-t1-001", "u24-t2-001", "u24-t2-003", "u24-t2-008"],
    },
    {
      id: "u24-t4-005",
      type: "produce",
      prompt: "Translate: 'It is said that in this city rooms are rented cheaply.'",
      accepted: [
        "Si dice che in questa città si affittano camere a buon prezzo.",
        "Si dice che in questa città si affittino camere a buon prezzo.",
      ],
      hint: "combine si dice che with si passivante of affittare (camere = plural)",
      tags: ["production", "si-impersonale", "si-passivante"],
      tier: 4,
      prerequisites: ["u24-t2-003", "u24-t2-005"],
    },
  ],
};
export default unit;
