import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b2-unit-35-numbers-economy",
  name: "Numbers & Economy",
  level: "B2",
  theme: "Economy & Statistics",
  emoji: "📊",
  prerequisiteUnits: ["b2-unit-34-abstract-ideas"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────
    {
      id: "u35-t1-001",
      type: "recognize",
      prompt: "la crescita",
      accepted: ["growth", "the growth"],
      hint: "economic expansion",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-002",
      type: "produce",
      prompt: "the GDP",
      accepted: ["il PIL"],
      hint: "Prodotto Interno Lordo",
      tags: ["economics", "noun", "acronym"],
      tier: 1,
    },
    {
      id: "u35-t1-003",
      type: "produce",
      prompt: "the inflation",
      accepted: ["l'inflazione"],
      hint: "rise in price levels",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-004",
      type: "produce",
      prompt: "the rate",
      accepted: ["il tasso"],
      hint: "as in interest rate",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-005",
      type: "produce",
      prompt: "the market",
      accepted: ["il mercato"],
      hint: "place of exchange",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-006",
      type: "produce",
      prompt: "the investments",
      accepted: ["gli investimenti"],
      hint: "plural, masculine",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-007",
      type: "produce",
      prompt: "the budget / balance sheet",
      accepted: ["il bilancio"],
      hint: "state or corporate accounts",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-008",
      type: "produce",
      prompt: "the crisis",
      accepted: ["la crisi"],
      hint: "invariable in plural",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-009",
      type: "produce",
      prompt: "the recovery",
      accepted: ["la ripresa"],
      hint: "economic rebound",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-010",
      type: "produce",
      prompt: "the public debt",
      accepted: ["il debito pubblico"],
      hint: "government borrowing",
      tags: ["economics", "noun", "finance"],
      tier: 1,
    },
    {
      id: "u35-t1-011",
      type: "produce",
      prompt: "the unemployment",
      accepted: ["la disoccupazione"],
      hint: "opposite of occupazione",
      tags: ["economics", "noun", "labour"],
      tier: 1,
    },
    {
      id: "u35-t1-012",
      type: "produce",
      prompt: "the consumer",
      accepted: ["il consumatore"],
      hint: "who buys goods",
      tags: ["economics", "noun", "market"],
      tier: 1,
    },

    // ── Tier 2 – Grammar / Number Expressions ────────────────────────────
    {
      id: "u35-t2-001",
      type: "conjugate",
      prompt: "esprimere una frazione – un terzo",
      accepted: ["un terzo"],
      hint: "1/3 in formal Italian",
      tags: ["numbers", "fractions", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-002",
      type: "conjugate",
      prompt: "esprimere una frazione – due quinti",
      accepted: ["due quinti"],
      hint: "2/5",
      tags: ["numbers", "fractions", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-003",
      type: "conjugate",
      prompt: "esprimere una frazione – tre quarti",
      accepted: ["tre quarti"],
      hint: "3/4",
      tags: ["numbers", "fractions", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-004",
      type: "fill_blank",
      prompt: "Il trenta ___ cento dei lavoratori è in smart working.",
      accepted: ["per"],
      hint: "percentage connector",
      tags: ["numbers", "percentage", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-005",
      type: "produce",
      prompt: "about ten (collective numeral)",
      accepted: ["una decina di"],
      hint: "group of approximately 10",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-006",
      type: "produce",
      prompt: "about twenty (collective numeral)",
      accepted: ["una ventina di"],
      hint: "group of approximately 20",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-007",
      type: "produce",
      prompt: "about a hundred (collective numeral)",
      accepted: ["un centinaio di"],
      hint: "used with di + noun",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-008",
      type: "produce",
      prompt: "thousands of (collective numeral)",
      accepted: ["migliaia di"],
      hint: "plural of migliaio",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-009",
      type: "fill_blank",
      prompt: "___ la metà dei consumatori ha cambiato abitudini dopo la crisi.",
      accepted: ["Circa"],
      hint: "most common approximation adverb",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },
    {
      id: "u35-t2-010",
      type: "produce",
      prompt: "approximately / roughly (formal, literary)",
      accepted: ["pressappoco", "all'incirca"],
      hint: "two formal synonyms of circa",
      tags: ["numbers", "approximation", "grammar"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Collocations ───────────────────────────────────
    {
      id: "u35-t3-001",
      type: "produce",
      prompt: "Growth has increased by 3%",
      accepted: ["La crescita è aumentata del 3%", "La crescita è aumentata del tre per cento"],
      hint: "use del + percentage",
      tags: ["economics", "chunk", "statistics"],
      tier: 3,
    },
    {
      id: "u35-t3-002",
      type: "produce",
      prompt: "About half of the population…",
      accepted: ["Circa la metà della popolazione…", "All'incirca la metà della popolazione…"],
      hint: "metà is feminine",
      tags: ["economics", "chunk", "approximation"],
      tier: 3,
    },
    {
      id: "u35-t3-003",
      type: "produce",
      prompt: "The unemployment rate has fallen",
      accepted: ["Il tasso di disoccupazione è sceso", "Il tasso di disoccupazione è diminuito"],
      hint: "scendere or diminuire",
      tags: ["economics", "chunk", "labour"],
      tier: 3,
    },
    {
      id: "u35-t3-004",
      type: "produce",
      prompt: "Equal to a quarter of the total",
      accepted: ["Pari a un quarto del totale"],
      hint: "pari a = equal to / equivalent to",
      tags: ["economics", "chunk", "fractions"],
      tier: 3,
    },
    {
      id: "u35-t3-005",
      type: "fill_blank",
      prompt: "Gli investimenti esteri rappresentano ___ un quinto del PIL nazionale.",
      accepted: ["circa", "all'incirca", "pressappoco"],
      hint: "approximation adverb before a fraction",
      tags: ["economics", "chunk", "statistics"],
      tier: 3,
    },
    {
      id: "u35-t3-006",
      type: "produce",
      prompt: "the economic recovery is underway",
      accepted: ["la ripresa economica è in corso", "la ripresa economica è in atto"],
      hint: "in corso / in atto = underway",
      tags: ["economics", "chunk", "finance"],
      tier: 3,
    },

    // ── Tier 4 – Sentences & Passages ────────────────────────────────────
    {
      id: "u35-t4-001",
      type: "produce",
      prompt: "Public debt has reached about two thirds of the GDP.",
      accepted: [
        "Il debito pubblico ha raggiunto circa due terzi del PIL.",
        "Il debito pubblico ha raggiunto all'incirca due terzi del PIL.",
      ],
      hint: "due terzi + del PIL",
      tags: ["economics", "sentence", "fractions"],
      tier: 4,
      prerequisites: ["u35-t1-010", "u35-t1-002", "u35-t2-001", "u35-t2-009"],
    },
    {
      id: "u35-t4-002",
      type: "fill_blank",
      prompt: "Nonostante la crisi, il mercato del lavoro ha mostrato segnali di ___ negli ultimi mesi.",
      accepted: ["ripresa"],
      hint: "economic rebound, feminine noun",
      tags: ["economics", "sentence", "labour"],
      tier: 4,
      prerequisites: ["u35-t1-008", "u35-t1-005", "u35-t1-009"],
    },
    {
      id: "u35-t4-003",
      type: "passage_cloze",
      prompt: "Il rapporto annuale sull'economia nazionale presenta dati incoraggianti.\nLa crescita del PIL ha raggiunto il 2,4 per cento, superando le previsioni degli analisti.\nGli investimenti esteri sono aumentati di una ventina di miliardi di euro rispetto all'anno precedente.\nIl tasso di ___ è sceso al 6,8 per cento, il livello più basso degli ultimi dieci anni.\nQuesti risultati confermano che la ripresa economica è ormai in corso.",
      accepted: ["disoccupazione"],
      hint: "labour market indicator, opposite of occupazione",
      tags: ["economics", "passage", "statistics", "labour"],
      tier: 4,
      prerequisites: ["u35-t1-004", "u35-t1-006", "u35-t1-009", "u35-t1-011", "u35-t2-006"],
    },
    {
      id: "u35-t4-004",
      type: "passage_cloze",
      prompt: "Secondo l'ultimo rapporto della Banca Centrale, l'inflazione rimane sotto controllo.\nIl tasso di inflazione si attesta all'incirca all'1,5 per cento su base annua.\nUn centinaio di imprese del settore manifatturiero ha già registrato un aumento dei margini.\nIl bilancio statale mostra un deficit pari a un terzo di quello registrato durante la crisi del decennio scorso.\nGli economisti prevedono che la ___ economica consoliderà questi progressi nel prossimo trimestre.",
      accepted: ["ripresa", "crescita"],
      hint: "economic rebound or growth",
      tags: ["economics", "passage", "statistics", "finance"],
      tier: 4,
      prerequisites: ["u35-t1-003", "u35-t1-004", "u35-t1-007", "u35-t1-008", "u35-t1-009", "u35-t2-007", "u35-t2-001"],
    },
    {
      id: "u35-t4-005",
      type: "produce",
      prompt: "Thousands of consumers changed their spending habits during the crisis.",
      accepted: [
        "Migliaia di consumatori hanno cambiato le proprie abitudini di spesa durante la crisi.",
        "Migliaia di consumatori hanno cambiato le loro abitudini di spesa durante la crisi.",
      ],
      hint: "migliaia di + noun, passato prossimo",
      tags: ["economics", "sentence", "approximation"],
      tier: 4,
      prerequisites: ["u35-t1-008", "u35-t1-012", "u35-t2-008"],
    },
  ],
};
export default unit;
