import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b2-unit-37-advanced-idioms",
  name: "Advanced Idioms",
  level: "B2",
  theme: "Idioms & Collocations",
  emoji: "🗝️",
  prerequisiteUnits: ["b2-unit-36-italian-culture"],
  cards: [
    // --- TIER 1: Vocab / Idiom Meaning ---
    {
      id: "u37-t1-001",
      type: "recognize",
      prompt: "avere le mani in pasta",
      accepted: ["to have a hand in something", "to be involved in something", "to have connections"],
      hint: "Literally: to have one's hands in the dough",
      tags: ["idiom", "influence", "connections"],
      tier: 1,
    },
    {
      id: "u37-t1-002",
      type: "recognize",
      prompt: "prendere due piccioni con una fava",
      accepted: ["to kill two birds with one stone"],
      hint: "Literally: to catch two pigeons with one bean",
      tags: ["idiom", "efficiency"],
      tier: 1,
    },
    {
      id: "u37-t1-003",
      type: "recognize",
      prompt: "fare il diavolo a quattro",
      accepted: ["to raise hell", "to kick up a fuss", "to make a scene"],
      hint: "Literally: to play the devil at four",
      tags: ["idiom", "chaos", "anger"],
      tier: 1,
    },
    {
      id: "u37-t1-004",
      type: "recognize",
      prompt: "essere al verde",
      accepted: ["to be broke", "to be penniless", "to have no money"],
      hint: "Literally: to be at the green",
      tags: ["idiom", "money", "finance"],
      tier: 1,
    },
    {
      id: "u37-t1-005",
      type: "recognize",
      prompt: "avere il pollice verde",
      accepted: ["to have a green thumb", "to be good at gardening"],
      hint: "Same image as English!",
      tags: ["idiom", "gardening", "talent"],
      tier: 1,
    },
    {
      id: "u37-t1-006",
      type: "recognize",
      prompt: "mettere il carro davanti ai buoi",
      accepted: ["to put the cart before the horse"],
      hint: "Literally: to put the cart before the oxen",
      tags: ["idiom", "order", "planning"],
      tier: 1,
    },
    {
      id: "u37-t1-007",
      type: "recognize",
      prompt: "attuale",
      accepted: ["current", "present", "contemporary"],
      hint: "False friend — NOT 'actual'",
      tags: ["false-friend", "adjective"],
      tier: 1,
    },
    {
      id: "u37-t1-008",
      type: "recognize",
      prompt: "sensibile",
      accepted: ["sensitive", "perceptible", "noticeable"],
      hint: "False friend — NOT 'sensible'",
      tags: ["false-friend", "adjective"],
      tier: 1,
    },
    {
      id: "u37-t1-009",
      type: "recognize",
      prompt: "pretendere",
      accepted: ["to demand", "to claim", "to expect"],
      hint: "False friend — NOT 'to pretend'",
      tags: ["false-friend", "verb"],
      tier: 1,
    },
    {
      id: "u37-t1-010",
      type: "produce",
      prompt: "to make a decision",
      accepted: ["prendere una decisione"],
      hint: "Do NOT use 'fare' here — this is a fixed collocation",
      tags: ["collocation", "prendere"],
      tier: 1,
    },

    // --- TIER 2: Grammar / Collocation / Verbo+Prep ---
    {
      id: "u37-t2-001",
      type: "produce",
      prompt: "to ask a question",
      accepted: ["fare una domanda"],
      hint: "Use 'fare', NOT 'chiedere una domanda'",
      tags: ["collocation", "fare"],
      tier: 2,
    },
    {
      id: "u37-t2-002",
      type: "fill_blank",
      prompt: "La qualità del prodotto ___ dal prezzo dei materiali. (to depend on)",
      accepted: ["dipende da", "dipende"],
      hint: "dipendere + da",
      tags: ["verb-prep", "dipendere"],
      tier: 2,
    },
    {
      id: "u37-t2-003",
      type: "fill_blank",
      prompt: "Lei ___ se stessa e nelle proprie capacità. (to believe in)",
      accepted: ["crede in", "crede"],
      hint: "credere + in",
      tags: ["verb-prep", "credere"],
      tier: 2,
    },
    {
      id: "u37-t2-004",
      type: "fill_blank",
      prompt: "Non voglio ___ ai miei sogni per il lavoro. (to give up)",
      accepted: ["rinunciare a"],
      hint: "rinunciare + a",
      tags: ["verb-prep", "rinunciare"],
      tier: 2,
    },
    {
      id: "u37-t2-005",
      type: "fill_blank",
      prompt: "Il capo ___ una risposta immediata. (to insist on)",
      accepted: ["insiste su", "insiste"],
      hint: "insistere + su",
      tags: ["verb-prep", "insistere"],
      tier: 2,
    },
    {
      id: "u37-t2-006",
      type: "fill_blank",
      prompt: "Devo ___ quello che ho, non posso volere di più. (to make do with / be content with)",
      accepted: ["accontentarmi di", "accontentarmi"],
      hint: "accontentarsi + di",
      tags: ["verb-prep", "accontentarsi"],
      tier: 2,
    },
    {
      id: "u37-t2-007",
      type: "produce",
      prompt: "the current situation (use the false-friend adjective)",
      accepted: ["la situazione attuale", "situazione attuale"],
      hint: "'attuale' = current, not actual",
      tags: ["false-friend", "collocation"],
      tier: 2,
    },
    {
      id: "u37-t2-008",
      type: "produce",
      prompt: "He demands an explanation. (use 'pretendere')",
      accepted: ["Pretende una spiegazione.", "Lui pretende una spiegazione.", "pretende una spiegazione"],
      hint: "'pretendere' = to demand, not to pretend",
      tags: ["false-friend", "pretendere"],
      tier: 2,
    },

    // --- TIER 3: Chunks & Expressions ---
    {
      id: "u37-t3-001",
      type: "recognize",
      prompt: "A dire il vero…",
      accepted: ["To tell the truth…", "Truthfully…", "To be honest…", "Frankly…"],
      hint: "A common discourse marker",
      tags: ["chunk", "discourse-marker"],
      tier: 3,
    },
    {
      id: "u37-t3-002",
      type: "recognize",
      prompt: "Non ne posso più.",
      accepted: ["I can't take it anymore.", "I've had enough.", "I can't stand it anymore."],
      hint: "Expresses exhaustion or exasperation",
      tags: ["chunk", "emotion", "exasperation"],
      tier: 3,
    },
    {
      id: "u37-t3-003",
      type: "recognize",
      prompt: "Fare di necessità virtù",
      accepted: ["To make a virtue of necessity", "To make the best of a bad situation", "To make the best of things"],
      hint: "A proverb about resilience",
      tags: ["proverb", "chunk", "resilience"],
      tier: 3,
    },
    {
      id: "u37-t3-004",
      type: "recognize",
      prompt: "Avere una marcia in più",
      accepted: ["To have an edge", "To have something extra", "To have a leg up", "To have that extra gear"],
      hint: "Literally: to have one more gear",
      tags: ["chunk", "idiom", "advantage"],
      tier: 3,
    },
    {
      id: "u37-t3-005",
      type: "produce",
      prompt: "to give someone a hand",
      accepted: ["dare una mano", "dare una mano a qualcuno"],
      hint: "Collocation with 'dare'",
      tags: ["collocation", "dare", "chunk"],
      tier: 3,
    },
    {
      id: "u37-t3-006",
      type: "produce",
      prompt: "to take advantage of an opportunity",
      accepted: ["approfittare di un'opportunità", "cogliere l'opportunità", "prendere un'opportunità"],
      hint: "Several options work here",
      tags: ["collocation", "chunk"],
      tier: 3,
    },

    // --- TIER 4: Sentences & Passage Cloze ---
    {
      id: "u37-t4-001",
      type: "produce",
      prompt: "To tell the truth, I can't take it anymore — he always demands the impossible.",
      accepted: [
        "A dire il vero, non ne posso più — pretende sempre l'impossibile.",
        "A dire il vero, non ne posso più: lui pretende sempre l'impossibile.",
      ],
      hint: "Use 'a dire il vero', 'non ne posso più', and 'pretendere'",
      tags: ["sentence", "idiom", "false-friend"],
      tier: 4,
      prerequisites: ["u37-t1-009", "u37-t2-008", "u37-t3-001", "u37-t3-002"],
    },
    {
      id: "u37-t4-002",
      type: "fill_blank",
      prompt: "Riuscendo a finire il lavoro e a portare i bambini a scuola nello stesso tragitto, ha preso due piccioni ___.",
      accepted: ["con una fava"],
      hint: "Complete the idiom for 'killing two birds with one stone'",
      tags: ["idiom", "fill-blank"],
      tier: 4,
      prerequisites: ["u37-t1-002"],
    },
    {
      id: "u37-t4-003",
      type: "passage_cloze",
      prompt: "Marco lavora in questa ditta da vent'anni e conosce tutti i soci personalmente.\nGrazie alle sue relazioni, riesce sempre a risolvere i problemi velocemente.\nI colleghi dicono che lui ha le mani ___ e che nessuna porta rimane chiusa per lui.\nA dire il vero, anche il direttore gli chiede consiglio.",
      accepted: ["in pasta"],
      hint: "Complete the idiom: 'avere le mani ___'",
      tags: ["passage-cloze", "idiom", "connections"],
      tier: 4,
      prerequisites: ["u37-t1-001", "u37-t3-001"],
    },
    {
      id: "u37-t4-004",
      type: "passage_cloze",
      prompt: "Dopo mesi di trattative difficili, il team ha finalmente deciso di agire.\nIl presidente ha dichiarato: 'È arrivato il momento di ___  una decisione definitiva.'.\nTutti erano d'accordo che rimandare ancora sarebbe stato un errore.\nOra dipende da noi mettere in pratica il piano concordato.",
      accepted: ["prendere"],
      hint: "Which verb collocates with 'una decisione'?",
      tags: ["passage-cloze", "collocation", "prendere"],
      tier: 4,
      prerequisites: ["u37-t1-010", "u37-t2-002"],
    },
    {
      id: "u37-t4-005",
      type: "produce",
      prompt: "She has a green thumb: her garden is always in bloom and she never gives up on a plant.",
      accepted: [
        "Ha il pollice verde: il suo giardino è sempre in fiore e non rinuncia mai a una pianta.",
        "Ha il pollice verde: il suo giardino è sempre fiorito e non rinuncia mai a una pianta.",
      ],
      hint: "Use 'avere il pollice verde' and 'rinunciare a'",
      tags: ["sentence", "idiom", "verb-prep"],
      tier: 4,
      prerequisites: ["u37-t1-005", "u37-t2-004"],
    },
  ],
};
export default unit;
