import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b2-unit-36-italian-culture",
  name: "Italian Culture",
  level: "B2",
  theme: "Art, History & Cuisine",
  emoji: "🎨",
  prerequisiteUnits: ["b2-unit-35-numbers-economy"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "u36-t1-001",
      type: "recognize",
      prompt: "il dipinto",
      accepted: ["the painting", "the picture"],
      hint: "a work made with paint",
      tags: ["art", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-002",
      type: "produce",
      prompt: "the sculpture",
      accepted: ["la scultura"],
      hint: "three-dimensional artwork",
      tags: ["art", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-003",
      type: "produce",
      prompt: "the fresco",
      accepted: ["l'affresco"],
      hint: "painted directly onto wet plaster",
      tags: ["art", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-004",
      type: "recognize",
      prompt: "il capolavoro",
      accepted: ["the masterpiece"],
      tags: ["art", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-005",
      type: "produce",
      prompt: "the Renaissance",
      accepted: ["il Rinascimento"],
      hint: "the great cultural rebirth of 14th–17th centuries",
      tags: ["history", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-006",
      type: "recognize",
      prompt: "la corrente artistica",
      accepted: ["the artistic movement", "the art movement"],
      tags: ["art", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-007",
      type: "produce",
      prompt: "the Roman Empire",
      accepted: ["l'Impero Romano"],
      tags: ["history", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-008",
      type: "recognize",
      prompt: "il Risorgimento",
      accepted: ["the Risorgimento", "the Italian unification movement", "the resurgence"],
      hint: "19th-century Italian political movement",
      tags: ["history", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-009",
      type: "produce",
      prompt: "the unification",
      accepted: ["l'unificazione"],
      tags: ["history", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-010",
      type: "recognize",
      prompt: "il tartufo",
      accepted: ["the truffle"],
      hint: "a prized underground fungus used in Italian cooking",
      tags: ["cuisine", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-011",
      type: "produce",
      prompt: "the traditional recipe",
      accepted: ["la ricetta tradizionale"],
      tags: ["cuisine", "noun", "culture"],
      tier: 1,
    },
    {
      id: "u36-t1-012",
      type: "recognize",
      prompt: "i prodotti tipici",
      accepted: ["the typical products", "the local products", "the regional products"],
      tags: ["cuisine", "noun", "culture"],
      tier: 1,
    },

    // ── Tier 2 – Grammar ─────────────────────────────────────────────────────
    {
      id: "u36-t2-001",
      type: "fill_blank",
      prompt: "Un quadro ___ una scena mitologica è esposto agli Uffizi. (raffigurare – participio presente)",
      accepted: ["raffigurante"],
      hint: "participio presente of 'raffigurare' used as adjective",
      tags: ["grammar", "participio-presente", "art"],
      tier: 2,
    },
    {
      id: "u36-t2-002",
      type: "fill_blank",
      prompt: "I ___ al convegno hanno visitato i Musei Vaticani. (participio presente of 'partecipare' → noun)",
      accepted: ["partecipanti"],
      hint: "those who participate",
      tags: ["grammar", "participio-presente", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-003",
      type: "fill_blank",
      prompt: "Il ___ universitario ha spiegato l'importanza del Rinascimento. (participio presente of 'docere')",
      accepted: ["docente"],
      hint: "the one who teaches; a lecturer",
      tags: ["grammar", "participio-presente", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-004",
      type: "fill_blank",
      prompt: "Il ___ è potere. (infinito sostantivato of 'sapere')",
      accepted: ["sapere"],
      hint: "knowledge is power – the infinitive used as a noun",
      tags: ["grammar", "infinito-sostantivato", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-005",
      type: "fill_blank",
      prompt: "Il ___ bene è l'obiettivo di ogni civiltà. (infinito sostantivato of 'vivere')",
      accepted: ["vivere"],
      hint: "living well; the infinitive as noun",
      tags: ["grammar", "infinito-sostantivato", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-006",
      type: "fill_blank",
      prompt: "La cucina regionale, ___ ingredienti locali di qualità, riflette l'identità di ogni territorio. (participio presente of 'valorizzare')",
      accepted: ["valorizzando"],
      hint: "use gerundio here: valorizzando",
      tags: ["grammar", "participio-presente", "cuisine"],
      tier: 2,
    },
    {
      id: "u36-t2-007",
      type: "produce",
      prompt: "the DOP designation (Protected Designation of Origin)",
      accepted: ["la DOP", "la Denominazione di Origine Protetta"],
      hint: "EU quality label for food products",
      tags: ["cuisine", "noun", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-008",
      type: "recognize",
      prompt: "la cucina regionale",
      accepted: ["regional cuisine", "the regional cuisine"],
      tags: ["cuisine", "noun", "culture"],
      tier: 2,
    },
    {
      id: "u36-t2-009",
      type: "fill_blank",
      prompt: "L'olio d'oliva ___ (DOP) viene prodotto seguendo disciplinari severi. (participio presente / aggettivo from 'certificare')",
      accepted: ["certificato"],
      hint: "past participle used as adjective: certified",
      tags: ["grammar", "participio-passato", "cuisine"],
      tier: 2,
    },
    {
      id: "u36-t2-010",
      type: "produce",
      prompt: "the olive oil",
      accepted: ["l'olio d'oliva"],
      tags: ["cuisine", "noun", "culture"],
      tier: 2,
    },

    // ── Tier 3 – Chunks & Phrases ────────────────────────────────────────────
    {
      id: "u36-t3-001",
      type: "produce",
      prompt: "a masterpiece of the Renaissance",
      accepted: ["un capolavoro del Rinascimento"],
      tags: ["chunk", "art", "history"],
      tier: 3,
    },
    {
      id: "u36-t3-002",
      type: "produce",
      prompt: "Italian cuisine is famous for…",
      accepted: ["La cucina italiana è famosa per…", "La cucina italiana è famosa per"],
      tags: ["chunk", "cuisine", "culture"],
      tier: 3,
    },
    {
      id: "u36-t3-003",
      type: "produce",
      prompt: "As the proverb goes…",
      accepted: ["Come recita il proverbio…", "Come recita il proverbio"],
      tags: ["chunk", "culture", "idiom"],
      tier: 3,
    },
    {
      id: "u36-t3-004",
      type: "produce",
      prompt: "World Heritage (Site)",
      accepted: ["Patrimonio dell'umanità", "Sito Patrimonio dell'umanità"],
      hint: "UNESCO designation",
      tags: ["chunk", "culture", "history"],
      tier: 3,
    },
    {
      id: "u36-t3-005",
      type: "fill_blank",
      prompt: "Il Colosseo è considerato un simbolo ___ dell'Impero Romano. (two-word phrase: 'intramontabile della grandezza'… supply only the adjective meaning 'timeless')",
      accepted: ["intramontabile"],
      hint: "timeless, undying",
      tags: ["chunk", "history", "culture"],
      tier: 3,
    },
    {
      id: "u36-t3-006",
      type: "produce",
      prompt: "typical local products",
      accepted: ["i prodotti tipici locali", "i prodotti tipici del territorio"],
      tags: ["chunk", "cuisine", "culture"],
      tier: 3,
    },

    // ── Tier 4 – Sentences & Passage Cloze ──────────────────────────────────
    {
      id: "u36-t4-001",
      type: "produce",
      prompt: "The fresco depicting the Last Supper is Leonardo's most famous masterpiece.",
      accepted: [
        "L'affresco raffigurante l'Ultima Cena è il capolavoro più famoso di Leonardo.",
        "L'affresco che raffigura l'Ultima Cena è il capolavoro più famoso di Leonardo.",
      ],
      tags: ["sentence", "art", "history", "participio-presente"],
      tier: 4,
      prerequisites: ["u36-t1-003", "u36-t1-004", "u36-t2-001"],
    },
    {
      id: "u36-t4-002",
      type: "produce",
      prompt: "Regional cuisine, which enhances typical local products, reflects the identity of each territory.",
      accepted: [
        "La cucina regionale, valorizzando i prodotti tipici locali, riflette l'identità di ogni territorio.",
        "La cucina regionale, che valorizza i prodotti tipici, riflette l'identità di ogni territorio.",
      ],
      tags: ["sentence", "cuisine", "culture"],
      tier: 4,
      prerequisites: ["u36-t1-012", "u36-t2-008"],
    },
    {
      id: "u36-t4-003",
      type: "fill_blank",
      prompt: "Il Rinascimento fu la corrente artistica più influente della storia europea.\nNacque in Italia nel Trecento e raggiunse il suo apice nel Cinquecento.\nArtisti partecipanti a questa straordinaria stagione culturale lasciarono capolavori immortali.\nLa Cappella Sistina, con i suoi affreschi, rappresenta il trionfo del ___.\n(supply the infinito sostantivato meaning 'knowing / knowledge')",
      accepted: ["sapere"],
      tags: ["passage-cloze", "art", "history", "infinito-sostantivato"],
      tier: 4,
      prerequisites: ["u36-t1-005", "u36-t1-004", "u36-t1-003", "u36-t1-006", "u36-t2-004"],
    },
    {
      id: "u36-t4-004",
      type: "passage_cloze",
      prompt: "Il parmigiano reggiano è uno dei prodotti tipici più celebri d'Italia.\nProdotto secondo una ricetta tradizionale risalente al Medioevo, porta il marchio ___.\nOgni forma deve stagionare almeno dodici mesi prima di essere venduta.\nLa sua produzione è concentrata nelle province di Parma, Reggio Emilia e Modena.\nCome recita il proverbio, la qualità non si improvvisa.",
      accepted: ["DOP"],
      hint: "European quality certification label",
      tags: ["passage-cloze", "cuisine", "culture"],
      tier: 4,
      prerequisites: ["u36-t1-011", "u36-t1-012", "u36-t2-007"],
    },
    {
      id: "u36-t4-005",
      type: "passage_cloze",
      prompt: "Il tartufo è uno dei prodotti più pregiati della cucina regionale italiana.\nCresce spontaneamente sotto terra ed è considerato un vero capolavoro della natura.\nLa sua raccolta, seguendo tecniche tramandate di generazione in generazione, richiede cani appositamente addestrati.\nIn Umbria e in Piemonte esistono fiere dedicate a questo prezioso ___.\nI partecipanti provengono da tutto il mondo per assaporarne il profumo unico.",
      accepted: ["tartufo"],
      hint: "the subject of the whole passage",
      tags: ["passage-cloze", "cuisine", "culture"],
      tier: 4,
      prerequisites: ["u36-t1-010", "u36-t1-004", "u36-t2-008"],
    },
  ],
};
export default unit;
