import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b2-unit-39-science-tech",
  name: "Science & Technology",
  level: "B2",
  theme: "Innovation, Research & Digital Life",
  emoji: "🔬",
  prerequisiteUnits: ["b2-unit-38-b2-review"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "b239-t1-001",
      type: "recognize",
      prompt: "la ricerca",
      accepted: ["the research", "research"],
      hint: "systematic investigation to establish facts",
      tags: ["science", "noun", "research"],
      tier: 1,
    },
    {
      id: "b239-t1-002",
      type: "recognize",
      prompt: "l'esperimento",
      accepted: ["the experiment"],
      hint: "a scientific test or trial",
      tags: ["science", "noun", "research"],
      tier: 1,
    },
    {
      id: "b239-t1-003",
      type: "recognize",
      prompt: "l'ipotesi",
      accepted: ["the hypothesis"],
      hint: "a proposed explanation to be tested",
      tags: ["science", "noun", "research"],
      tier: 1,
    },
    {
      id: "b239-t1-004",
      type: "recognize",
      prompt: "i dati",
      accepted: ["the data", "the information"],
      hint: "plural noun — facts and statistics collected for reference",
      tags: ["science", "noun", "data"],
      tier: 1,
    },
    {
      id: "b239-t1-005",
      type: "recognize",
      prompt: "l'analisi",
      accepted: ["the analysis"],
      hint: "detailed examination of the elements of something",
      tags: ["science", "noun", "research"],
      tier: 1,
    },
    {
      id: "b239-t1-006",
      type: "recognize",
      prompt: "il risultato",
      accepted: ["the result", "the outcome"],
      hint: "what is obtained at the end of a process",
      tags: ["science", "noun", "research"],
      tier: 1,
    },
    {
      id: "b239-t1-007",
      type: "recognize",
      prompt: "la scoperta",
      accepted: ["the discovery"],
      hint: "finding something previously unknown",
      tags: ["science", "noun", "innovation"],
      tier: 1,
    },
    {
      id: "b239-t1-008",
      type: "recognize",
      prompt: "l'invenzione",
      accepted: ["the invention"],
      hint: "creating something that did not exist before",
      tags: ["science", "noun", "innovation"],
      tier: 1,
    },
    {
      id: "b239-t1-009",
      type: "recognize",
      prompt: "il brevetto",
      accepted: ["the patent"],
      hint: "legal protection for an invention",
      tags: ["science", "noun", "innovation"],
      tier: 1,
    },
    {
      id: "b239-t1-010",
      type: "recognize",
      prompt: "l'intelligenza artificiale",
      accepted: ["artificial intelligence", "AI"],
      hint: "abbreviated IA in Italian",
      tags: ["technology", "noun", "AI"],
      tier: 1,
    },
    {
      id: "b239-t1-011",
      type: "recognize",
      prompt: "l'algoritmo",
      accepted: ["the algorithm"],
      hint: "a step-by-step computational procedure",
      tags: ["technology", "noun", "computing"],
      tier: 1,
    },
    {
      id: "b239-t1-012",
      type: "recognize",
      prompt: "la rete neurale",
      accepted: ["the neural network"],
      hint: "computing system loosely modelled on the human brain",
      tags: ["technology", "noun", "AI"],
      tier: 1,
    },
    {
      id: "b239-t1-013",
      type: "recognize",
      prompt: "l'elaborazione dati",
      accepted: ["data processing"],
      hint: "the collection and manipulation of data",
      tags: ["technology", "noun", "computing"],
      tier: 1,
    },
    {
      id: "b239-t1-014",
      type: "recognize",
      prompt: "la realtà virtuale",
      accepted: ["virtual reality", "VR"],
      hint: "a simulated three-dimensional environment",
      tags: ["technology", "noun", "digital"],
      tier: 1,
    },
    {
      id: "b239-t1-015",
      type: "recognize",
      prompt: "la biotecnologia",
      accepted: ["biotechnology"],
      hint: "technology based on biology",
      tags: ["science", "noun", "biology"],
      tier: 1,
    },
    {
      id: "b239-t1-016",
      type: "recognize",
      prompt: "la nanotecnologia",
      accepted: ["nanotechnology"],
      hint: "manipulation of matter on an atomic scale",
      tags: ["science", "noun", "innovation"],
      tier: 1,
    },
    {
      id: "b239-t1-017",
      type: "recognize",
      prompt: "il cambiamento climatico",
      accepted: ["climate change"],
      hint: "long-term shifts in global temperatures and weather patterns",
      tags: ["science", "noun", "environment"],
      tier: 1,
    },
    {
      id: "b239-t1-018",
      type: "recognize",
      prompt: "l'energia rinnovabile",
      accepted: ["renewable energy"],
      hint: "energy from sources that are naturally replenished",
      tags: ["science", "noun", "environment"],
      tier: 1,
    },
    {
      id: "b239-t1-019",
      type: "recognize",
      prompt: "le emissioni di CO2",
      accepted: ["CO2 emissions", "carbon dioxide emissions", "carbon emissions"],
      hint: "greenhouse gas released by burning fossil fuels",
      tags: ["science", "noun", "environment"],
      tier: 1,
    },
    {
      id: "b239-t1-020",
      type: "recognize",
      prompt: "la digitalizzazione",
      accepted: ["digitalisation", "digitalization", "digitisation"],
      hint: "the process of converting processes to digital form",
      tags: ["technology", "noun", "digital"],
      tier: 1,
    },
    {
      id: "b239-t1-021",
      type: "recognize",
      prompt: "la connettività",
      accepted: ["connectivity"],
      hint: "the state of being connected, especially to the internet",
      tags: ["technology", "noun", "digital"],
      tier: 1,
    },
    {
      id: "b239-t1-022",
      type: "recognize",
      prompt: "la sicurezza informatica",
      accepted: ["cybersecurity", "IT security", "information security"],
      hint: "protection of computer systems from attack",
      tags: ["technology", "noun", "digital"],
      tier: 1,
    },

    // ── Tier 2 – Advanced Collocations & Scientific Passive ──────────────────
    {
      id: "b239-t2-001",
      type: "fill_blank",
      prompt: "Il gruppo ha deciso di ___ una ricerca sull'intelligenza artificiale nel settore medico. (verb meaning 'to conduct/carry out')",
      accepted: ["condurre", "svolgere", "effettuare"],
      hint: "condurre una ricerca is the canonical scientific collocation",
      tags: ["collocation", "science", "verb", "register"],
      tier: 2,
    },
    {
      id: "b239-t2-002",
      type: "fill_blank",
      prompt: "Prima di avviare l'esperimento, i ricercatori devono ___ un'ipotesi chiara e verificabile. (verb: to formulate)",
      accepted: ["formulare"],
      hint: "formulare un'ipotesi — standard scientific register",
      tags: ["collocation", "science", "verb", "register"],
      tier: 2,
    },
    {
      id: "b239-t2-003",
      type: "fill_blank",
      prompt: "Dopo aver completato l'analisi dei dati, il team ha deciso di ___ i risultati sulla rivista Nature. (verb: to publish)",
      accepted: ["pubblicare"],
      hint: "pubblicare i risultati — typical research writing phrase",
      tags: ["collocation", "science", "verb", "register"],
      tier: 2,
    },
    {
      id: "b239-t2-004",
      type: "fill_blank",
      prompt: "Il brevetto è ___ dall'ufficio competente dopo una valutazione approfondita. (passivo presente of 'concedere')",
      accepted: ["concesso"],
      hint: "passive construction: viene concesso / è concesso",
      tags: ["grammar", "passive", "science", "register"],
      tier: 2,
    },

    // ── Tier 3 – Sentences (eng_to_ita) ─────────────────────────────────────
    {
      id: "b239-t3-001",
      type: "produce",
      prompt: "The experiment confirmed the hypothesis.",
      accepted: [
        "L'esperimento ha confermato l'ipotesi.",
        "L'esperimento confermò l'ipotesi.",
      ],
      hint: "use passato prossimo or passato remoto",
      tags: ["sentence", "science", "research"],
      tier: 3,
      prerequisites: ["b239-t1-002", "b239-t1-003"],
    },
    {
      id: "b239-t3-002",
      type: "produce",
      prompt: "Artificial intelligence is transforming every sector.",
      accepted: [
        "L'intelligenza artificiale sta trasformando ogni settore.",
        "L'intelligenza artificiale trasforma ogni settore.",
      ],
      hint: "present progressive (stare + gerundio) or simple present both work",
      tags: ["sentence", "technology", "AI"],
      tier: 3,
      prerequisites: ["b239-t1-010"],
    },
    {
      id: "b239-t3-003",
      type: "produce",
      prompt: "Renewable energy is the key to fighting climate change.",
      accepted: [
        "L'energia rinnovabile è la chiave per combattere il cambiamento climatico.",
        "L'energia rinnovabile è la chiave nella lotta contro il cambiamento climatico.",
      ],
      hint: "'la chiave per + infinito' or 'la chiave nella lotta contro'",
      tags: ["sentence", "environment", "science"],
      tier: 3,
      prerequisites: ["b239-t1-017", "b239-t1-018"],
    },
    {
      id: "b239-t3-004",
      type: "produce",
      prompt: "Research published in the journal showed surprising results.",
      accepted: [
        "La ricerca pubblicata sulla rivista ha mostrato risultati sorprendenti.",
        "La ricerca pubblicata sulla rivista mostrò risultati sorprendenti.",
        "Una ricerca pubblicata sulla rivista ha mostrato risultati sorprendenti.",
      ],
      hint: "use participio passato 'pubblicata' as adjective; 'sulla rivista'",
      tags: ["sentence", "science", "passive", "research"],
      tier: 3,
      prerequisites: ["b239-t1-001", "b239-t1-006", "b239-t2-003"],
    },

    // ── Tier 4 – Passage Cloze ───────────────────────────────────────────────
    {
      id: "b239-t4-001",
      type: "passage_cloze",
      prompt: "Negli ultimi anni la digitalizzazione ha rivoluzionato il modo in cui le aziende operano.\nLa connettività globale permette di condurre ricerche in tempo reale e di pubblicare i risultati istantaneamente.\nTuttavia, con la crescita dell'elaborazione dati emergono nuove sfide legate alla ___.\nGli esperti sottolineano che proteggere i sistemi informatici è ormai priorità assoluta per governi e imprese.\nSenza adeguate misure di difesa, le reti neurali e gli algoritmi su cui si basa l'intelligenza artificiale rimangono vulnerabili.",
      accepted: ["sicurezza informatica"],
      hint: "the two-word term for protection of computer systems",
      tags: ["passage-cloze", "technology", "digital", "cybersecurity"],
      tier: 4,
      prerequisites: [
        "b239-t1-020",
        "b239-t1-021",
        "b239-t1-022",
        "b239-t1-013",
        "b239-t1-010",
        "b239-t1-011",
        "b239-t1-012",
        "b239-t2-003",
      ],
    },
  ],
};
export default unit;
