import type { Unit } from "@/content/types";
const unit: Unit = {
  id: "b2-unit-40-law-society",
  name: "Law & Society",
  level: "B2",
  theme: "Civic Life, Rights & Institutions",
  emoji: "⚖️",
  prerequisiteUnits: ["b2-unit-39-science-tech"],
  cards: [
    // ── Tier 1 – Vocabulary ──────────────────────────────────────────────────
    {
      id: "b240-t1-001",
      type: "recognize",
      prompt: "la legge",
      accepted: ["the law", "the act", "the statute"],
      hint: "the primary instrument of a state's legal order",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-002",
      type: "recognize",
      prompt: "la norma",
      accepted: ["the rule", "the norm", "the regulation", "the standard"],
      hint: "a binding rule within a legal or technical framework",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-003",
      type: "recognize",
      prompt: "il regolamento",
      accepted: ["the regulation", "the by-law", "the rules"],
      hint: "subordinate legislation implementing a law",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-004",
      type: "recognize",
      prompt: "il diritto",
      accepted: ["the right", "the law", "law"],
      hint: "both an entitlement and the body of law itself",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-005",
      type: "recognize",
      prompt: "il dovere",
      accepted: ["the duty", "the obligation"],
      hint: "the counterpart of 'il diritto'",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-006",
      type: "recognize",
      prompt: "la costituzione",
      accepted: ["the constitution"],
      hint: "the founding legal document of a state",
      tags: ["law", "noun", "civic", "politics"],
      tier: 1,
    },
    {
      id: "b240-t1-007",
      type: "recognize",
      prompt: "la cittadinanza",
      accepted: ["citizenship", "the citizenship"],
      hint: "the status of being a member of a state",
      tags: ["law", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-008",
      type: "recognize",
      prompt: "il suffragio",
      accepted: ["suffrage", "the right to vote", "the vote"],
      hint: "the formal right to participate in elections",
      tags: ["law", "noun", "civic", "politics"],
      tier: 1,
    },
    {
      id: "b240-t1-009",
      type: "recognize",
      prompt: "le elezioni",
      accepted: ["the elections", "elections"],
      hint: "plural; the process by which citizens choose representatives",
      tags: ["politics", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-010",
      type: "recognize",
      prompt: "il parlamento",
      accepted: ["parliament", "the parliament"],
      hint: "the legislative body of a democratic state",
      tags: ["politics", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-011",
      type: "recognize",
      prompt: "il governo",
      accepted: ["the government"],
      hint: "the executive branch led by a prime minister or president",
      tags: ["politics", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-012",
      type: "recognize",
      prompt: "l'opposizione",
      accepted: ["the opposition"],
      hint: "the political parties not in government",
      tags: ["politics", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-013",
      type: "recognize",
      prompt: "il referendum",
      accepted: ["the referendum"],
      hint: "a direct public vote on a specific question",
      tags: ["politics", "noun", "civic"],
      tier: 1,
    },
    {
      id: "b240-t1-014",
      type: "recognize",
      prompt: "il processo",
      accepted: ["the trial", "the legal process", "the court case"],
      hint: "a formal legal proceeding before a judge",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-015",
      type: "recognize",
      prompt: "il tribunale",
      accepted: ["the court", "the tribunal"],
      hint: "the institution where trials are held",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-016",
      type: "recognize",
      prompt: "la sentenza",
      accepted: ["the sentence", "the ruling", "the judgment", "the verdict"],
      hint: "the final decision issued by a court",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-017",
      type: "recognize",
      prompt: "l'imputato / l'imputata",
      accepted: ["the defendant", "the accused"],
      hint: "the person charged with a crime in a trial",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-018",
      type: "recognize",
      prompt: "la condanna",
      accepted: ["the conviction", "the condemnation", "the sentence"],
      hint: "the finding of guilt by a court",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-019",
      type: "recognize",
      prompt: "l'assoluzione",
      accepted: ["the acquittal", "the absolution"],
      hint: "the formal finding that the defendant is not guilty",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-020",
      type: "recognize",
      prompt: "l'appello",
      accepted: ["the appeal"],
      hint: "a challenge to a lower court's decision at a higher court",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-021",
      type: "recognize",
      prompt: "il ricorso",
      accepted: ["the appeal", "the legal recourse", "the petition"],
      hint: "a formal application to a court or authority; broader than 'appello'",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-022",
      type: "recognize",
      prompt: "la prescrizione",
      accepted: ["prescription", "the statute of limitations", "the lapse of time bar"],
      hint: "the expiry of the time limit within which a crime can be prosecuted",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-023",
      type: "recognize",
      prompt: "la pena detentiva",
      accepted: ["the custodial sentence", "the prison sentence", "the term of imprisonment"],
      hint: "punishment involving loss of liberty",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },
    {
      id: "b240-t1-024",
      type: "recognize",
      prompt: "la libertà condizionale",
      accepted: ["parole", "conditional release", "probation"],
      hint: "release from prison subject to conditions",
      tags: ["law", "noun", "judicial"],
      tier: 1,
    },

    // ── Tier 2 – Legal Collocations & Formal Constructions ──────────────────
    {
      id: "b240-t2-001",
      type: "fill_blank",
      prompt: "Ai ___ della legge, chiunque è considerato innocente fino a prova contraria.\n(supply the noun meaning 'in the terms of / per')",
      accepted: ["sensi"],
      hint: "'ai sensi della legge' = per the law / pursuant to the law",
      tags: ["law", "collocation", "formal", "fill_blank"],
      tier: 2,
    },
    {
      id: "b240-t2-002",
      type: "fill_blank",
      prompt: "L'imputato è stato ___ a tre anni di pena detentiva.\n(supply the past participle of 'condannare')",
      accepted: ["condannato"],
      hint: "'essere condannato a' = to be sentenced to",
      tags: ["law", "collocation", "judicial", "fill_blank"],
      tier: 2,
    },
    {
      id: "b240-t2-003",
      type: "fill_blank",
      prompt: "La difesa ha deciso di fare ___ contro la sentenza di primo grado.\n(supply the noun: the formal legal challenge)",
      accepted: ["ricorso"],
      hint: "'fare ricorso contro' = to appeal against / to challenge",
      tags: ["law", "collocation", "judicial", "fill_blank"],
      tier: 2,
    },
    {
      id: "b240-t2-004",
      type: "fill_blank",
      prompt: "Il reato è andato in ___ perché i termini di legge sono scaduti.\n(supply the noun for the lapse of the prosecution time limit)",
      accepted: ["prescrizione"],
      hint: "'andare in prescrizione' = to become time-barred",
      tags: ["law", "collocation", "judicial", "fill_blank"],
      tier: 2,
    },

    // ── Tier 3 – Sentence Translation (eng_to_ita) ──────────────────────────
    {
      id: "b240-t3-001",
      type: "produce",
      prompt: "The law was passed by parliament.",
      accepted: [
        "La legge è stata approvata dal parlamento.",
        "La legge è stata votata dal parlamento.",
      ],
      hint: "use 'approvare' or 'votare' in the passive; 'da' introduces the agent",
      tags: ["law", "sentence", "passive", "civic"],
      tier: 3,
    },
    {
      id: "b240-t3-002",
      type: "produce",
      prompt: "He was acquitted of all charges.",
      accepted: [
        "È stato assolto da tutte le accuse.",
        "Fu assolto da tutte le accuse.",
      ],
      hint: "'essere assolto da' = to be acquitted of",
      tags: ["law", "sentence", "passive", "judicial"],
      tier: 3,
    },
    {
      id: "b240-t3-003",
      type: "produce",
      prompt: "Citizens have the right to vote.",
      accepted: [
        "I cittadini hanno il diritto di votare.",
        "I cittadini hanno diritto al voto.",
        "I cittadini hanno diritto al suffragio.",
      ],
      hint: "'avere il diritto di' + infinitive, or 'avere diritto a' + noun",
      tags: ["law", "sentence", "civic", "rights"],
      tier: 3,
    },
    {
      id: "b240-t3-004",
      type: "produce",
      prompt: "She appealed against the conviction.",
      accepted: [
        "Ha fatto ricorso contro la condanna.",
        "Ha presentato appello contro la condanna.",
        "Ha fatto appello contro la condanna.",
      ],
      hint: "'fare ricorso contro' or 'presentare appello contro'",
      tags: ["law", "sentence", "judicial"],
      tier: 3,
    },
    {
      id: "b240-t3-005",
      type: "produce",
      prompt: "The constitution guarantees freedom of expression.",
      accepted: [
        "La costituzione garantisce la libertà di espressione.",
        "La Costituzione garantisce la libertà di espressione.",
      ],
      hint: "'garantire' = to guarantee; 'la libertà di espressione' = freedom of expression",
      tags: ["law", "sentence", "civic", "rights"],
      tier: 3,
    },

    // ── Tier 4 – Passage Cloze ───────────────────────────────────────────────
    {
      id: "b240-t4-001",
      type: "passage_cloze",
      prompt: "Il processo a carico dell'ex funzionario si è concluso ieri con una sentenza di primo grado.\nIl tribunale ha dichiarato l'imputato colpevole di corruzione e lo ha condannato a quattro anni di pena detentiva.\nAi sensi della legge vigente, la difesa ha trenta giorni per presentare ___.\nGli avvocati hanno già annunciato l'intenzione di contestare la decisione davanti alla corte d'appello.\nNel caso in cui anche l'appello venisse respinto, la condanna diventerebbe definitiva.",
      accepted: ["appello", "ricorso"],
      hint: "the formal legal challenge against a court ruling (two options are accepted)",
      tags: ["law", "passage_cloze", "judicial", "civic"],
      tier: 4,
      prerequisites: [
        "b240-t1-014",
        "b240-t1-015",
        "b240-t1-016",
        "b240-t1-017",
        "b240-t1-018",
        "b240-t1-020",
        "b240-t1-021",
        "b240-t1-023",
        "b240-t2-001",
        "b240-t2-002",
        "b240-t2-003",
      ],
    },
  ],
};
export default unit;
